if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["09 September"] = [
  {
    "day": 1,
    "title": "Lemonade Stand",
    "image": "09 September/images/day_01.webp",
    "audio": "09 September/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "Jeannie put up her sign. It said, Lemunaid: five cents a glass!", "ipa": "/ˈdʒiːni pʊt ʌp hɜːr saɪn. ɪt sɛd, lɪˈmuːneɪd: faɪv sɛnts ə ɡlɑːs/", "vi": "Jeannie dựng tấm biển của mình lên. Trên biển viết: 'Lemunaid: năm xu một cốc!'" },
      { "start": 12.0, "en": "Her neighbour, Mr. Brown, was walking by. He stopped and said, 'You didn't spell lemonade right. It should be spelled l-e-m-o-n-a-d-e.'", "ipa": "/hɜːr ˈneɪbər, ˈmɪstər braʊn, wɒz ˈwɔːkɪŋ baɪ. hiː stɒpt ænd sɛd, juː ˈdɪdnt spɛl ˈlɛməˌneɪd raɪt. ɪt ʃʊd biː spɛld ɛl-i-ɛm-o-en-e-di-i/", "vi": "Bác hàng xóm Mr. Brown đi ngang qua, dừng lại và bảo: 'Cháu viết sai chính tả chữ lemonade rồi. Phải viết là l-e-m-o-n-a-d-e cơ.'" },
      { "start": 23.0, "en": "'Thank you,' said Jeannie. 'I'll write it down so I know how to spell it in the future.'", "ipa": "/ˈθæŋk juː, sɛd ˈdʒiːni. aɪl raɪt ɪt daʊn soʊ aɪ noʊ haʊ tuː spɛl ɪt ɪn ðə ˈfjuːtʃər/", "vi": "'Cháu cảm ơn bác,' Jeannie nói. 'Cháu sẽ ghi lại để sau này biết cách viết đúng.'" },
      { "start": 32.0, "en": "All morning, people stopped to tell Jeannie about her spelling mistake. And right before leaving, they all bought a glass of lemonade.", "ipa": "/ɔːl ˈmɔːrnɪŋ, ˈpiːpl stɒpt tuː tɛl ˈdʒiːni əˈbaʊt hɜːr ˈspɛlɪŋ ˈmɪsteɪk. ænd raɪt bɪˈfɔːr ˈliːvɪŋ, ðeɪ ɔːl bɔːt ə ɡlɑːs əv ˈlɛməˌneɪd/", "vi": "Suốt buổi sáng, mọi người liên tục dừng chân để nhắc Jeannie về lỗi chính tả. Và trước khi rời đi, tất cả bọn họ đều mua một cốc nước chanh." },
      { "start": 44.0, "en": "A couple of hours later, Mr. Brown came back. This time, he had a sign with him. 'I saw that you have been too busy to make a new sign. So, I made one for you,' he told Jeannie.", "ipa": "/ə ˈkʌpl əv ˈaʊərz ˈleɪtər, ˈmɪstər braʊn keɪm bæk. ðɪs taɪm, hiː hæd ə saɪn wɪð hɪm. aɪ sɔː ðæt juː hæv biːn tuː ˈbɪzi tuː meɪk ə njuː saɪn. soʊ, aɪ meɪd wʌn fɔːr juː, hiː toʊld ˈdʒiːni/", "vi": "Vài tiếng sau, Mr. Brown quay lại. Lần này bác mang theo một tấm biển: 'Bác thấy cháu bận quá chưa kịp làm biển mới nên bác làm hộ cháu đấy,' bác bảo Jeannie." },
      { "start": 58.0, "en": "'Thank you, Mr. Brown. Yes, it's true that lemonade is spelled wrong. But my sign is just right,' said Jeannie. 'Why?' said Mr. Brown.", "ipa": "/ˈθæŋk juː, ˈmɪstər braʊn. jɛs, ɪts truː ðæt ˈlɛməˌneɪd ɪz spɛld rɒŋ. bʌt maɪ saɪn ɪz dʒʌst raɪt, sɛd ˈdʒiːni. waɪ?, sɛd ˈmɪstər braʊn/", "vi": "'Cháu cảm ơn bác Brown. Đúng là chữ lemonade trên biển bị sai chính tả thật. Nhưng tấm biển của cháu lại chuẩn không cần chỉnh ạ,' Jeannie nói. 'Sao lại thế?' bác Brown ngạc nhiên hỏi." },
      { "start": 68.0, "en": "'Everyone stops to tell me about the mistake,' said Jeannie. 'And then, they always buy lemonade.' Jeannie held up a jar full of money and smiled.", "ipa": "/ˈɛvriˌwʌn stɒps tuː tɛl miː əˈbaʊt ðə mɪsˈteɪk, sɛd ˈdʒiːni. ænd ðɛn, ðeɪ ˈɔːlweɪz baɪ ˈlɛməˌneɪd. ˈdʒiːni hɛld ʌp ə dʒɑːr fʊl əv ˈmʌni ænd smaɪld/", "vi": "'Mọi người đều dừng lại để góp ý lỗi sai cho cháu,' Jeannie đáp. 'Và thế là họ luôn mua nước chanh.' Jeannie giơ cao hũ đựng đầy tiền và mỉm cười rạng rỡ." }
    ]
  },
  {
    "day": 2,
    "title": "Teeth",
    "image": "09 September/images/day_02.webp",
    "audio": "09 September/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "On Monday, Amy bit into some corn. 'Ouch!' she said. Her tooth felt strange.", "ipa": "/ɒn ˈmʌndeɪ, ˈeɪmi bɪt ˈɪntuː sʌm kɔːrn. aʊtʃ!, ʃiː sɛd. hɜːr tuːθ fɛlt streɪndʒ/", "vi": "Thứ Hai, Amy cắn một bắp ngô. 'Ái chà!' cô bé kêu lên. Chiếc răng của cô bỗng thấy lạ lạ." },
      { "start": 12.0, "en": "On Tuesday, Amy bit into an apple. 'Ouch!' she said. Her tooth felt wiggly.", "ipa": "/ɒn ˈtuːzdeɪ, ˈeɪmi bɪt ˈɪntuː ən ˈæpl. aʊtʃ!, ʃiː sɛd. hɜːr tuːθ fɛlt ˈwɪɡli/", "vi": "Thứ Ba, Amy cắn một quả táo. 'Ái chà!' cô bé lại kêu. Chiếc răng bắt đầu lung lay." },
      { "start": 19.0, "en": "On Wednesday, Amy bit into a piece of cheese. 'Ouch!' she said. 'My tooth is loose!' She had heard about kids losing their teeth and she didn't like the way it sounded. She wanted to keep all of her teeth.", "ipa": "/ɒn ˈwɛnzdeɪ, ˈeɪmi bɪt ˈɪntuː ə piːs əv tʃiːz. aʊtʃ!, ʃiː sɛd. maɪ tuːθ ɪz luːs! ʃiː hæd hɜːrd əˈbaʊt kɪdz ˈluːzɪŋ ðɛər tiːθ ænd ʃiː ˈdɪdnt laɪk ðə weɪ ɪt ˈsaʊndɪd. ʃiː ˈwɒntɪd tuː kiːp ɔːl əv hɜːr tiːθ/", "vi": "Thứ Tư, Amy cắn một miếng phô mai. 'Ái chà!' cô thét lên. 'Răng tớ sắp rụng rồi!' Cô từng nghe các bạn kể chuyện thay răng và không thích chút nào. Cô muốn giữ lại tất cả hàm răng của mình." },
      { "start": 35.0, "en": "On Thursday, she was careful. So she ate yogurt, oatmeal and pudding. It worked. She didn't lose any of her teeth.", "ipa": "/ɒn ˈθɜːrzdeɪ, ʃiː wɒz ˈkɛrfʊl. soʊ ʃiː eɪt ˈjoʊɡərt, ˈoʊtˌmiːl ænd ˈpʊdɪŋ. ɪt wɜːrkt. ʃiː ˈdɪdnt luːz ˈɛni əv hɜːr tiːθ/", "vi": "Thứ Năm, cô bé cẩn thận hơn hẳn bằng cách ăn sữa chua, cháo yến mạch và bánh pudding. Cách này rất hiệu quả, cô chẳng bị rụng chiếc răng nào." },
      { "start": 48.0, "en": "On Friday, her mom made pizza for dinner. She poked the pizza. It felt soft enough, so she bit into a slice. 'Ouch!' she cried. Her tooth had fallen out!", "ipa": "/ɒn ˈfraɪdeɪ, hɜːr mɒm meɪd ˈpiːtsə fɔːr ˈdɪnər. ʃiː poʊkt ðə ˈpiːtsə. ɪt fɛlt sɒft ɪˈnʌf, soʊ ʃiː bɪt ˈɪntuː ə slaɪs. aʊtʃ!, ʃiː kraɪd. hɜːr tuːθ hæd ˈfɔːlən aʊt/", "vi": "Thứ Sáu, mẹ làm bánh pizza cho bữa tối. Cô bé ấn thử thấy bánh đủ mềm nên cắn một miếng. 'Ái chà!' cô khóc thét lên. Chiếc răng đã rụng ra mất rồi!" },
      { "start": 62.0, "en": "That night, Amy put her tooth under her pillow. In the morning, her tooth was gone. But, in its place was a coin!", "ipa": "/ðæt naɪt, ˈeɪmi pʊt hɜːr tuːθ ˈʌndər hɜːr ˈpɪloʊ. ɪn ðə ˈmɔːrnɪŋ, hɜːr tuːθ wɒz ɡɒn. bʌt, ɪn ɪts pleɪs wɒz ə kɔɪn/", "vi": "Đêm đó, Amy đặt chiếc răng dưới gối. Sáng hôm sau thức dậy, chiếc răng đã biến mất nhưng thay vào đó lại là một đồng xu sáng loáng!" },
      { "start": 72.0, "en": "On Saturday, Amy ate corn on the cob, an apple, a piece of cheese and pizza. She wanted to lose more teeth!", "ipa": "/ɒn ˈsætərdeɪ, ˈeɪmi eɪt kɔːrn ɒn ðə kɒb, ən ˈæpl, ə piːs əv tʃiːz ænd ˈpiːtsə. ʃiː ˈwɒntɪd tuː luːz mɔːr tiːθ/", "vi": "Thứ Bảy, Amy thoải mái ăn bắp ngô luộc, táo, phô mai và pizza. Giờ thì cô bé lại cực kỳ mong rụng thêm nhiều răng nữa!" }
    ]
  },
  {
    "day": 3,
    "title": "The Boy Who Cares",
    "image": "09 September/images/day_03.webp",
    "audio": "09 September/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Sandy is seven years old. Recently, his mom noticed that Sandy worries about things a lot.", "ipa": "/ˈsændi ɪz ˈsɛvn jɪərz oʊld. ˈriːsəntli, hɪz mɒm ˈnoʊtɪst ðæt ˈsændi ˈwʌriz əˈbaʊt θɪŋz ə lɒt/", "vi": "Sandy mới bảy tuổi. Dạo gần đây, mẹ nhận thấy cậu bé hay lo lắng về mọi thứ xung quanh." },
      { "start": 12.0, "en": "Every night before bed, Sandy's mom fills the bathtub for her son to take a bath. She used to fill it more than half full so that he could enjoy his hot bath.", "ipa": "/ˈɛvri naɪt bɪˈfɔːr bɛd, ˈsandiz mɒm fɪlz ðə ˈbæˌtʌb fɔːr hɜːr sʌn tuː teɪk ə bæθ. ʃiː juːzd tuː fɪl ɪt mɔːr ðæn hæf fʊl soʊ ðæt hiː kʊd ɪnˈdʒɔɪ hɪz hɒt bæθ/", "vi": "Mỗi tối trước khi đi ngủ, mẹ thường xả nước đầy bồn tắm để cậu con trai ngâm mình. Trước kia mẹ thường xả hơn nửa bồn để con ngâm nước nóng thỏa thích." },
      { "start": 25.0, "en": "But now, Sandy asks his mom to shut off the tap when the tub is only one third full.", "ipa": "/bʌt naʊ, ˈsændi ɑːsks hɪz mɒm tuː ʃʌt ɔːf ðə tæp wɛn ðə tʌb ɪz ˈoʊnli wʌn θɜːrd fʊl/", "vi": "Nhưng giờ đây, Sandy toàn nhờ mẹ khóa vòi khi nước mới chỉ ngập một phần ba bồn." },
      { "start": 33.0, "en": "Why? Sandy tells his mom that it is not easy for water to come to the tap. He doesn't want to waste any.", "ipa": "/waɪ? ˈsændi tɛlz hɪz mɒm ðæt ɪt ɪz nɒt ˈiːzi fɔːr ˈwɔːtər tuː kʌm tuː ðə tæp. hiː ˈdʌznt wɒnt tuː weɪst ˈɛni/", "vi": "Tại sao vậy? Sandy giải thích với mẹ rằng nước sạch chảy đến vòi không phải chuyện dễ dàng và cậu không muốn lãng phí dù chỉ một giọt." },
      { "start": 43.0, "en": "He says, 'Our teacher said that many people have trouble getting drinking water. Some kids walk miles to fetch water.'", "ipa": "/hiː sɛz, ˈaʊər ˈtiːtʃər sɛd ðæt ˈmɛni ˈpiːpl hæv ˈtrʌbl ˈɡɛtɪŋ ˈdrɪŋkɪŋ ˈwɔːtər. sʌm kɪdz wɔːk maɪlz tuː fɛtʃ ˈwɔːtər/", "vi": "Cậu bé nói: 'Thầy giáo bảo nhiều nơi trên thế giới đang thiếu nước sinh hoạt trầm trọng. Nhiều bạn nhỏ phải đi bộ hàng dặm đường mới gánh được nước về đấy mẹ ạ.'" },
      { "start": 56.0, "en": "Mom is moved by her little son. She tells her friends, 'Sandy is only seven, but he thinks about how to solve problems in the world.'", "ipa": "/mɒm ɪz muːvd baɪ hɜːr ˈlɪtl sʌn. ʃiː tɛlz hɜːr frɛndz, ˈsændi ɪz ˈoʊnli ˈsɛvn, bʌt hiː θɪŋks əˈbaʊt haʊ tuː sɒlv ˈprɒbləmz ɪn ðə wɜːrld/", "vi": "Mẹ vô cùng xúc động trước tấm lòng của cậu con trai nhỏ. Mẹ hay khoe với bạn bè: 'Sandy mới bảy tuổi thôi mà đã biết trăn trở tìm cách giải quyết các vấn đề lớn của thế giới rồi.'" },
      { "start": 68.0, "en": "She then adds, 'Shouldn't we all do our share to save this planet? We should not let our children worry all the time.' Yes. They all agree.", "ipa": "/ʃiː ðɛn ædz, ˈʃʊdnt wiː ɔːl duː ˈaʊər ʃɛər tuː seɪv ðɪs ˈplænɪt? wiː ʃʊd nɒt lɛt ˈaʊər ˈtʃɪldrən ˈwʌri ɔːl ðə taɪm. jɛs. ðeɪ ɔːl əˈɡriː/", "vi": "Mẹ nói thêm: 'Chẳng phải tất cả chúng ta nên chung tay cứu lấy hành tinh này sao? Ta không thể để con trẻ cứ mãi lo âu như thế được.' Vâng, mọi người đều đồng tình như thế." }
    ]
  },
  {
    "day": 4,
    "title": "Car Keys",
    "image": "09 September/images/day_04.webp",
    "audio": "09 September/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Freddy came to his father and asked, 'Dad, may I borrow your car keys?' 'I don't think so!' answered his father. 'You're not ready to drive yet.'", "ipa": "/wʌn deɪ, ˈfrɛdi keɪm tuː hɪz ˈfɑːðər ænd ɑːskt, dæd, meɪ aɪ ˈbɒroʊ jɔːr kɑːr kiːz? aɪ doʊnt θɪŋk soʊ!, ˈɑːnsərd hɪz ˈfɑːðər. jʊər nɒt ˈrɛdi tuː draɪv jɛt/", "vi": "Một hôm, Freddy đến gặp bố và xin mượn chìa khóa ô tô. 'Bố không nghĩ thế đâu!' bố từ chối ngay. 'Con chưa đủ tuổi và chưa sẵn sàng để lái xe đâu.'" },
      { "start": 16.0, "en": "Freddy laughed. 'Mom locked the car. I just need to get my baseball glove from the front seat.' 'I see. Here you go,' said Dad. 'Just don't try to drive.' 'Thanks,' said Freddy. 'I'll bring them right back.'", "ipa": "/ˈfrɛdi lɑːft. mɒm lɒkt ðə kɑːr. aɪ dʒʌst niːd tuː ɡɛt maɪ ˈbeɪsˌbɔːl ɡlʌv frɒm ðə frʌnt siːt. aɪ siː. hɪər juː ɡoʊ, sɛd dæd. dʒʌst doʊnt traɪ tuː draɪv. θæŋks, sɛd ˈfrɛdi. aɪl brɪŋ ðɛm raɪt bæk/", "vi": "Freddy cười xòa: 'Mẹ khóa cửa xe mất rồi, con chỉ muốn lấy chiếc găng tay bóng chày ở ghế trước thôi.' 'À ra vậy, cầm lấy này,' bố đưa chìa khóa. 'Miễn đừng tò mò tập lái nhé.' 'Vâng, con mang trả lại ngay đây ạ,' Freddy đáp." },
      { "start": 32.0, "en": "A couple of minutes later, Freddy got his glove and started walking back. Suddenly, the car started moving. Freddy raced after it, unlocked the door and grabbed the emergency break. The car stopped rolling.", "ipa": "/ə ˈkʌpl əv ˈmɪnɪts ˈleɪtər, ˈfrɛdi ɡɒt hɪz ɡlʌv ænd ˈstɑːrtɪd ˈwɔːkɪŋ bæk. ˈsʌdənli, ðə kɑːr ˈstɑːrtɪd ˈmuːvɪŋ. ˈfrɛdi reɪst ˈɑːftər ɪt, ˌʌnˈlɒkt ðə dɔːr ænd ɡræbt ði ɪˈmɜːrdʒənsi breɪk. ðə kɑːr stɒpt ˈroʊlɪŋ/", "vi": "Vài phút sau, lấy được găng tay xong, Freddy thong thả quay lại. Bỗng nhiên, chiếc xe chầm chậm lăn bánh! Cậu hộc tốc đuổi theo, mở cửa và giật phắt phanh tay. Chiếc xe khựng lại đứng yên." },
      { "start": 48.0, "en": "Dad came running out of the house. 'What did you do?' he asked. 'I must have hit something while I was getting my glove,' answered Freddy. 'I'm sorry. I didn't mean to drive the car.'", "ipa": "/dæd keɪm ˈrʌnɪŋ aʊt əv ðə haʊs. wɒt dɪd juː duː?, hiː ɑːskt. aɪ mʌst hæv hɪt ˈsʌmθɪŋ waɪl aɪ wɒz ˈɡɛtɪŋ maɪ ɡlʌv, ˈɑːnsərd ˈfrɛdi. aɪm ˈsɒri. aɪ ˈdɪdnt miːn tuː draɪv ðə kɑːr/", "vi": "Bố hộc tốc chạy từ trong nhà ra: 'Con làm cái quái gì thế?' 'Chắc lúc lấy găng tay con vô tình đụng phải cần số,' Freddy thanh minh. 'Con xin lỗi, con không cố ý lái xe đâu ạ.'" },
      { "start": 62.0, "en": "'I know,' said Dad. 'Accidents happen. I'm glad you acted quickly. But, next time you kids want something from the car, I'll get it for you. That made me age way too fast and I can't afford to do that!'", "ipa": "/aɪ noʊ, sɛd dæd. ˈæksɪdənts ˈhæpən. aɪm ɡlæd juː ˈæktɪd ˈkwɪkli. bʌt, nɛkst taɪm juː kɪdz wɒnt ˈsʌmθɪŋ frɒm ðə kɑːr, aɪl ɡɛt ɪt fɔːr juː. ðæt meɪd miː eɪdʒ weɪ tuː fɑːst ænd aɪ kænt əˈfɔːrd tuː duː ðæt!/", "vi": "'Bố biết rồi,' bố thở phào. 'Tai nạn có thể xảy ra bất cứ lúc nào, may mà con xử lý kịp thời. Nhưng từ nay về sau, cứ cần gì ở xe thì bảo bố lấy cho nhé. Vừa rồi suýt nữa làm bố già đi chục tuổi mất thôi!'" }
    ]
  },
  {
    "day": 5,
    "title": "Red Wolves",
    "image": "09 September/images/day_05.webp",
    "audio": "09 September/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Red wolves are the smallest wolves in the world. They are only about 26 inches tall at the shoulder.", "ipa": "/rɛd wʊlvz ɑːr ðə ˈsmɔːlɪst wʊlvz ɪn ðə wɜːrld. ðeɪ ɑːr ˈoʊnli əˈbaʊt ˈtwɛnti-sɪks ˈɪntʃɪz tɔːl æt ðə ˈʃoʊldər/", "vi": "Sói đỏ là loài sói nhỏ nhất trên thế giới. Chiều cao tính đến vai của chúng chỉ khoảng 26 inch (66 cm)." },
      { "start": 14.0, "en": "Red wolves live in packs of five to eight. A pack is made up of a father wolf, a mother wolf and their children. The pack lives and hunts together.", "ipa": "/rɛd wʊlvz lɪv ɪn pæks əv faɪv tuː eɪt. ə pæk ɪz meɪd ʌp əv ə ˈfɑːðər wʊlf, ə ˈmʌðər wʊlf ænd ðɛər ˈtʃɪldrən. ðə pæk lɪvz ænd hʌnts təˈɡɛðər/", "vi": "Sói đỏ sống theo bầy đàn từ năm đến tám con. Một bầy bao gồm sói bố, sói mẹ và các con. Cả bầy cùng sinh sống và đi săn mồi với nhau." },
      { "start": 25.0, "en": "They hunt for small animals to eat, like rabbits and rodents. They eat insects and berries too.", "ipa": "/ðeɪ hʌnt fɔːr smɔːl ˈænɪmlz tuː iːt, laɪk ˈræbɪts ænd ˈroʊdnts. ðeɪ iːt ˈɪnsɛkts ænd ˈbɛriz tuː/", "vi": "Chúng săn các loài động vật nhỏ để ăn như thỏ và loài gặm nhấm. Chúng cũng ăn cả côn trùng và quả mọng." },
      { "start": 35.0, "en": "Red wolves in a pack communicate in many different ways. They make noises and bark. They make faces and use body language as well.", "ipa": "/rɛd wʊlvz ɪn ə pæk kəˈmjuːnɪkeɪt ɪn ˈmɛni ˈdɪfrənt weɪz. ðeɪ meɪk ˈnɔɪzɪz ænd bɑːrk. ðeɪ meɪk ˈfeɪsɪz ænd juːz ˈbɒdi ˈlæŋɡwɪdʒ æz wɛl/", "vi": "Sói đỏ trong bầy giao tiếp với nhau bằng nhiều cách khác nhau. Chúng phát ra âm thanh và sủa, đồng thời biểu cảm khuôn mặt và sử dụng ngôn ngữ cơ thể." },
      { "start": 48.0, "en": "One time, red wolves lived all over the south-eastern United States. But thirty years ago, they almost disappeared completely.", "ipa": "/wʌn taɪm, rɛd wʊlvz lɪvd ɔːl ˈoʊvər ðə saʊθ-ˈiːstərn juˈnaɪtɪd steɪts. bʌt ˈθɜːrti jɪərz əˈɡoʊ, ðeɪ ˈɔːlmoʊst ˌdɪsəˈpɪərd kəmˈpliːtli/", "vi": "Đã có lúc, sói đỏ sinh sống khắp vùng Đông Nam nước Mỹ. Nhưng ba mươi năm trước, chúng suýt tuyệt chủng hoàn toàn." },
      { "start": 59.0, "en": "Then, in 1980, twenty red wolves were found in the wild and taken to a safe place. There, they were able to have babies and increase their numbers. Now, there are over one hundred red wolves living in the wild.", "ipa": "/ðɛn, ɪn ˌnaɪnˈtiːn ˈeɪti, ˈtwɛnti rɛd wʊlvz wɜːr faʊnd ɪn ðə waɪld ænd ˈteɪkən tuː ə seɪf pleɪs. ðɛər, ðeɪ wɜːr ˈeɪbl tuː hæv ˈbeɪbiːz ænd ˈɪnkriːs ðɛər ˈnʌmbərz. naʊ, ðɛər ɑːr ˈoʊvər wʌn ˈhʌndrəd rɛd wʊlvz ˈlɪvɪŋ ɪn ðə waɪld/", "vi": "Sau đó, vào năm 1980, hai mươi con sói đỏ đã được tìm thấy trong tự nhiên và đưa đến một nơi an toàn. Ở đó, chúng có thể sinh con và gia tăng số lượng. Hiện nay, có hơn một trăm con sói đỏ đang sống trong môi trường hoang dã." }
    ]
  },
  {
    "day": 6,
    "title": "Family Tree",
    "image": "09 September/images/day_06.webp",
    "audio": "09 September/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mom was drawing a picture. 'What are you drawing?' asked Barbara, looking over her mother's shoulder.", "ipa": "/mɒm wɒz ˈdrɔːɪŋ ə ˈpɪktʃər. wɒt ɑːr juː ˈdrɔːɪŋ?, ɑːskt ˈbɑːrbərə, ˈlʊkɪŋ ˈoʊvər hɜːr ˈmʌðərz ˈʃoʊldər/", vi: "Mẹ đang vẽ một bức tranh. 'Mẹ đang vẽ gì thế ạ?' Barbara vừa hỏi vừa nhìn qua vai mẹ." },
      { "start": 12.0, "en": "'This is our family tree,' answered her mother. 'It shows you, your sister and brother, Dad, and me. It also shows our parents, their parents and others from long ago.'", "ipa": "/ðɪs ɪz ˈaʊər ˈfæməli triː, ˈɑːnsərd hɜːr ˈmʌðər. ɪt ʃoʊz juː, jɔːr ˈsɪstər ænd ˈbrʌðər, dæd, ænd miː. ɪt ˈɔːlsoʊ ʃoʊz ˈaʊər ˈpɛərənts, ðɛər ˈpɛərənts ænd ˈʌðərz frɒm lɒŋ əˈɡoʊ/", "vi": "'Đây là cây gia đình của nhà mình,' mẹ đáp. 'Nó cho thấy con, chị và em trai con, bố và mẹ. Nó cũng cho thấy bố mẹ của chúng ta, bố mẹ của họ và những người khác từ lâu lắm rồi.'" },
      { "start": 27.0, "en": "'That's neat!' said Barbara. 'Who is Olive Willard?' she asked, pointing to a name.", "ipa": "/ðæts niːt!, sɛd ˈbɑːrbərə. huː ɪz ˈɒlɪv ˈwɪlərd?, ʃiː ɑːskt, ˈpɔɪntɪŋ tuː ə neɪm/", "vi": "'Thật gọn gàng và hay quá!' Barbara nói. 'Olive Willard là ai vậy ạ?' cô bé hỏi, vừa chỉ vào một cái tên." },
      { "start": 35.0, "en": "'That's Grandma Olive,' answered Mom. 'But I thought her name was Olive Flanders,' said Barbara.", "ipa": "/ðæts ˈɡrændmɑː ˈɒlɪv, ˈɑːnsərd mɒm. bʌt aɪ θɔːt hɜːr neɪm wɒz ˈɒlɪv ˈflændərz, sɛd ˈbɑːrbərə/", "vi": "'Đó là bà nội Olive,' mẹ trả lời. 'Nhưng con tưởng tên của bà là Olive Flanders cơ mà?' Barbara thắc mắc." },
      { "start": 44.0, "en": "'Before she married Grandpa Clint, her name was Olive Willard,' answered Mom. 'Look here. Here is my name. My name used to be Flanders.'", "ipa": "/bɪˈfɔːr ʃiː ˈmærid ˈɡrændpɑː klɪnt, hɜːr neɪm wɒz ˈɒlɪv ˈwɪlərd, ˈɑːnsərd mɒm. lʊk hɪər. hɪər ɪz maɪ neɪm. maɪ neɪm ˈjuːzd tuː biː ˈflændərz/", "vi": "'Trước khi kết hôn với ông nội Clint, tên của bà là Olive Willard,' mẹ đáp. 'Nhìn đây này. Đây là tên của mẹ. Tên của mẹ hồi trước là Flanders đấy.'" },
      { "start": 57.0, "en": "'It seems strange to think that you weren't always you, but someone else,' said Barbara. Her mother laughed.", "ipa": "/ɪt siːmz streɪndʒ tuː θɪŋk ðæt juː ˈwɜːnt ˈɔːlweɪz juː, bʌt ˈsʌmwʌn ɛls, sɛd ˈbɑːrbərə. hɜːr ˈmʌðər lɑːft/", "vi": "'Thật kỳ lạ khi nghĩ rằng mẹ không phải lúc nào cũng là mẹ, mà từng là một người khác,' Barbara nói. Mẹ cô bé bật cười." }
    ]
  },
  {
    "day": 7,
    "title": "The Father of South America",
    "image": "09 September/images/day_07.webp",
    "audio": "09 September/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "Imagine being so famous that a country is named after you? Well, about 200 years ago, there lived a man who was called the 'father of South America'.", "ipa": "/ɪˈmædʒɪŋ ˈbiːɪŋ soʊ ˈfeɪməs ðæt ə ˈkʌntri ɪz neɪmd ˈɑːftər juː? wɛl, əˈbaʊt ˈtuː ˈhʌndrəd jɪərz əˈɡoʊ, ðɛər lɪvd ə mæn huː wɒz kɔːld ðə ˈfɑːðər əv saʊθ əˈmɛrɪkə/", "vi": "Hãy tưởng tượng bạn nổi tiếng đến mức được đặt tên cho cả một quốc gia? Chà, khoảng 200 năm trước, từng có một người đàn ông được mệnh danh là 'cha đẻ của Nam Mỹ'." },
      { "start": 16.0, "en": "His name was Simon Bolivar. He was born in South America in 1783.", "ipa": "/hɪz neɪm wɒz ˈsaɪmən bəˈliːvɑːr. hiː wɔːz bɔːrn ɪn saʊθ əˈmɛrɪkə ɪn ˌeɪtiːn ˈeɪti-θriː/", "vi": "Tên của ông là Simon Bolivar. Ông sinh ra ở Nam Mỹ vào năm 1783." },
      { "start": 24.0, "en": "Back then, Spain ruled South America. Most people in South America did not like this. Simon was one of those people. So he led small groups of men to fight against the Spanish armies.", "ipa": "/bæk ðɛn, speɪn ruːld saʊθ əˈmɛrɪkə. moʊst ˈpiːpl ɪn saʊθ əˈmɛrɪkə dɪd nɒt laɪk ðɪs. ˈsaɪmən wɒz wʌn əv ðoʊz ˈpiːpl. soʊ hiː lɛd smɔːl ɡruːps əv mɛn tuː faɪt əˈɡɛnst ðə ˈspænɪʃ ˈɑːrmiz/", vi: "Hồi đó, Tây Ban Nha thống trị Nam Mỹ. Hầu hết người dân ở Nam Mỹ không thích điều này. Simon là một trong số những người đó. Vì vậy, ông đã dẫn dắt các nhóm nam giới nhỏ chiến đấu chống lại quân đội Tây Ban Nha." },
      { "start": 42.0, "en": "People called him 'El Liberator'. That means someone who makes people free.", "ipa": "/ˈpiːpl kɔːld hɪm ɛl ˈlɪbəˌreɪtər. ðæt miːnz ˈsʌmwʌn huː meɪks ˈpiːpl friː/", "vi": "Mọi người gọi ông là 'El Liberator' (Người giải phóng). Điều đó có nghĩa là một người mang lại sự tự do cho mọi người." },
      { "start": 50.0, "en": "He helped to free Colombia, Venezuela, Peru, Ecuador and... Bolivia!", "ipa": "/hiː hɛlpt tuː friː kəˈlʌmbɪə, ˌvɛnəˈzweɪlə, pəˈruː, ˈɛkwədɔːr ænd... bəˈlɪviə!/", "vi": "Ông đã giúp giải phóng Colombia, Venezuela, Peru, Ecuador và... Bolivia!" },
      { "start": 59.0, "en": "That's right, the country of Bolivia is named after Simon Bolivar. I wonder how many other countries are named after people?", "ipa": "/ðæts raɪt, ðə ˈkʌntri əv bəˈlɪviə ɪz neɪmd ˈɑːftər ˈsaɪmən bəˈliːvɑːr. aɪ ˈwʌndər haʊ ˈmɛni ˈʌðər ˈkʌntriz ɑːr neɪmd ˈɑːftər ˈpiːpl?/", "vi": "Đúng vậy, quốc gia Bolivia được đặt tên theo Simon Bolivar. Tự hỏi không biết có bao nhiêu quốc gia khác được đặt tên theo con người nhỉ?" }
    ]
  },
  {
    "day": 8,
    "title": "Dark or Light-It's Amazing",
    "image": "09 September/images/day_08.webp",
    "audio": "09 September/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "We all know what organs are. Things like the heart, lungs and kidneys are all organs. But, do you know what is the biggest organ of all?", "ipa": "/wiː ɔːl noʊ wɒt ˈɔːrɡənz ɑːr. θɪŋz laɪk ðə hɑːrt, lʌŋz ænd ˈkɪdniːz ɑːr ɔːl ˈɔːrɡənz. bʌt, duː juː noʊ wɒt ɪz ðə ˈbɪɡɪst ˈɔːrɡən əv ɔːl?/", "vi": "Chúng ta đều biết các cơ quan là gì. Những thứ như tim, phổi và thận đều là các cơ quan. Nhưng bạn có biết cơ quan nào là lớn nhất trong số đó không?" },
      { "start": 16.0, "en": "Here are some hints. It can be very dark or it can be very light. It can be very smooth or very rough. That's right-it's skin!", "ipa": "/hɪər ɑːr sʌm hɪnts. ɪt kæn biː ˈvɛri dɑːrk ɔːr ɪt kæn biː ˈvɛri laɪt. ɪt kæn biː ˈvɛri smuːð ɔːr ˈvɛri rʌf. ðæts raɪt-ɪts skɪn/", "vi": "Dưới đây là một số gợi ý. Nó có thể rất tối màu hoặc rất sáng màu. Nó có thể rất mịn hoặc rất thô ráp. Đúng vậy - đó chính là da!" },
      { "start": 28.0, "en": "Our skin is an amazing thing. Imagine if scientists could invent something that could heal itself? That's exactly what skin does!", "ipa": "/ˈaʊər skɪn ɪz ən əˈmeɪzɪŋ θɪŋ. ɪˈmædʒɪn ɪf ˈsaɪəntɪsts kʊd ɪnˈvɛnt ˈsʌmθɪŋ ðæt kʊd hiːl ɪtˈsɛlf? ðæts ɪɡˈzæktli wɒt skɪn dʌz!/", "vi": "Da của chúng ta là một thứ tuyệt vời. Hãy tưởng tượng nếu các nhà khoa học có thể phát minh ra một thứ gì đó có khả năng tự chữa lành? Đó chính xác là những gì da làm được!" },
      { "start": 38.0, "en": "Adults have more than 11 miles of blood vessels in their skin! Those blood vessels help to keep skin warm or to cool it down. In fact, on a hot summer day, a person can sweat as much as 3 gallons.", "ipa": "/əˈdʌlts hæv mɔːr ðæn ˈlɛvn maɪlz əv blʌd ˈvɛsəlz ɪn ðɛər skɪn! ðoʊz blʌd ˈvɛsəlz hɛlp tuː kiːp skɪn wɔːrm ɔːr tuː kuːl ɪt daʊn. ɪn fækt, ɒn ə hɒt ˈsʌmər deɪ, ə ˈpɜːrsn kæn swɛt æz mʌtʃ æz θriː ˈɡælənz/", "vi": "Người lớn có hơn 11 dặm mạch máu trong da của họ! Những mạch máu đó giúp giữ ấm cho da hoặc làm mát da. Trên thực tế, vào một ngày hè nóng bức, một người có thể tiết mồ hôi lên tới 3 gallon." },
      { "start": 57.0, "en": "The reason why there are different colours of skin is pigment. The more pigment you have in your skin, the darker it is. So, take care of your skin. Remember, you are going to need it for a long time!", "ipa": "/ðə ˈriːzn waɪ ðɛər ɑːr ˈdɪfrənt ˈkʌlərz əv skɪn ɪz ˈpɪɡmənt. ðə mɔːr ˈpɪɡmənt juː hæv ɪn jɔːr skɪn, ðə ˈdɑːrkər ɪt ɪz. soʊ, teɪk kɛər əv jɔːr skɪn. rɪˈmɛmbər, juː ɑːr ˈɡoʊɪŋ tuː niːd ɪt fɔːr ə lɒŋ taɪm!/", "vi": "Lý do tại sao có các màu da khác nhau là do sắc tố. Bạn càng có nhiều sắc tố trong da, da càng sậm màu. Vì vậy, hãy chăm sóc làn da của bạn. Hãy nhớ rằng, bạn sẽ cần đến nó trong một thời gian dài!" }
    ]
  },
  {
    "day": 9,
    "title": "Race Car",
    "image": "09 September/images/day_09.webp",
    "audio": "09 September/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "Billy loves cars. So does his brother Jeff. One day, Billy saw his brother working on something. He was curious.", "ipa": "/ˈbɪli lʌvz kɑːrz. soʊ dʌz hɪz ˈbrʌðər dʒɛf. wʌn deɪ, ˈbɪli sɔː hɪz ˈbrʌðər ˈwɜːrkɪŋ ɒn ˈsʌmθɪŋ. hiː wɒz ˈkjʊəriəs/", "vi": "Billy rất thích ô tô. Anh trai Jeff của cậu cũng vậy. Một ngày nọ, Billy nhìn thấy anh mình đang làm việc gì đó. Cậu cảm thấy tò mò." },
      { "start": 13.0, "en": "'What are you building?' asked Billy. 'A race car,' answered Jeff. 'One that's big enough for me to get into.'", "ipa": "/wɒt ɑːr juː ˈbɪldɪŋ?, ɑːskt ˈbɪli. ə reɪs kɑːr, ˈɑːnsərd dʒɛf. wʌn ðæts bɪɡ ɪˈnʌf fɔːr miː tuː ɡɛt ˈɪntuː/", "vi": "'Anh đang làm gì thế?' Billy hỏi. 'Một chiếc xe đua,' Jeff trả lời. 'Chiếc xe đủ lớn để anh có thể chui vào trong.'" },
      { "start": 21.0, "en": "'Can I help? Then, we can share it!' said Billy. Jeff agreed. It would be fun to have someone to build his race car with. And so, the two boys got to work.", "ipa": "/kæn aɪ hɛlp? ðɛn, wiː kæn ʃɛr ɪt!, sɛd ˈbɪli. dʒɛf əˈɡriːd. ɪt wʊd biː fʌn tuː hæv ˈsʌmwʌn tuː bɪld hɪz reɪs kɑːr wɪð. ænd soʊ, ðə tuː bɔɪz ɡɒt tuː wɜːrk/", "vi": "'Em giúp một chút nhé? Thế thì chúng ta có thể cùng dùng chung!' Billy nói. Jeff đồng ý. Sẽ rất vui nếu có ai đó cùng mình chế tạo chiếc xe đua. Và thế là, hai cậu bé bắt tay vào việc." },
      { "start": 36.0, "en": "They worked hard. Mrs. Smith from next door saw what they were doing. She gave them an old baby carriage.", "ipa": "/ðeɪ wɜːrkt hɑːrd. ˈmɪsɪz smɪθ frɒm nɛkst dɔːr sɔː wɒt ðeɪ wɜːr ˈduːɪŋ. ʃiː ɡeɪv ðɛm ən oʊld ˈbeɪbi ˈkærɪdʒ/", "vi": "Họ làm việc rất chăm chỉ. Bà Smith ở nhà bên nhìn thấy những gì họ đang làm. Bà liền cho họ một chiếc xe đẩy em bé cũ." },
      { "start": 44.0, "en": "'The wheels on this are still good,' she said. 'Maybe you can use them.' The boys worked even harder. Soon, it was finished—a very nice race car!", "ipa": "/ðə wiːlz ɒn ðɪs ɑːr stɪl ɡʊd, ʃiː sɛd. ˈmeɪbi juː kæn juːz ðɛm. ðə bɔɪz wɜːrkt ˈiːvn ˈhɑːrdər. suːn, ɪt wɒz ˈfɪnɪʃt—ə ˈvɛri naɪs reɪs kɑːr/", "vi": "'Bánh xe của chiếc này vẫn còn tốt,' bà nói. 'Có lẽ các cháu dùng được đấy.' Hai cậu bé càng làm chăm chỉ hơn. Chẳng mấy chốc, nó đã hoàn thành—một chiếc xe đua rất đẹp!" },
      { "start": 57.0, "en": "When their father came home from work, he smiled as he saw the car. Then, he brought out some more wood and wheels. 'If you build two, then you can race each other.'", "ipa": "/wɛn ðɛər ˈfɑːðər keɪm hoʊm frɒm wɜːrk, hiː smaɪld æz hiː sɔː ðə kɑːr. ðɛn, hiː brɔːt aʊt sʌm mɔːr wʊd ænd wiːlz. ɪf juː bɪld tuː, ðɛn juː kæn reɪs iːtʃ ˈʌðər/", "vi": "Khi bố của hai cậu đi làm về, ông mỉm cười khi nhìn thấy chiếc xe. Sau đó, ông mang ra thêm một ít gỗ và bánh xe. 'Nếu các con làm hai chiếc, thì các con có thể đua với nhau.'" },
      { "start": 68.0, "en": "Soon, the boys had two race cars. They were ready to race each other in their own cars!", "ipa": "/suːn, ðə bɔɪz hæd tuː reɪs kɑːrz. ðeɪ wɜːr ˈrɛdi tuː reɪs iːtʃ ˈʌðər ɪn ðɛər oʊn kɑːrz/", "vi": "Chẳng mấy chốc, hai cậu bé đã có hai chiếc xe đua. Họ đã sẵn sàng để đua với nhau trên những chiếc xe của chính mình!" }
    ]
  },
  {
    "day": 10,
    "title": "Henry Ford",
    "image": "09 September/images/day_10.webp",
    "audio": "09 September/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "Henry Ford was a man who truly changed the world. He was born on July 30, 1863. He grew up on a farm in Michigan in the United States.", "ipa": "/ˈhɛnri fɔːrd wɒz ə mæn huː ˈtruːli tʃeɪndʒd ðə wɜːrld. hiː wɒz bɔːrn ɒn dʒuˈlaɪ ˈθɜːrti, ˌeɪtiːn ˈsɪksti-θriː. hiː ɡruː ʌp ɒn ə fɑːrm ɪn ˈmɪʃɪɡən ɪn ði juˈnaɪtɪd steɪts/", "vi": "Henry Ford là một người đã thực sự thay đổi thế giới. Ông sinh ngày 30 tháng 7 năm 1863. Ông lớn lên tại một trang trại ở bang Michigan, Hoa Kỳ." },
      { "start": 17.0, "en": "When he was old enough, he left his family's farm and moved to Detroit to start living his dream.", "ipa": "/wɛn hiː wɒz oʊld ɪˈnʌf, hiː lɛft hɪz ˈfæməlɪz fɑːrm ænd muːvd tuː dɪˈtrɔɪt tuː stɑːrt ˈlɪvɪŋ hɪz driːm/", "vi": "Khi đủ lớn, ông rời trang trại của gia đình và chuyển đến Detroit để bắt đầu thực hiện ước mơ của mình." },
      { "start": 25.0, "en": "Mr. Ford wanted to make cars. In 1903, Mr. Ford started the Ford Motor Company. At that time, the company was able to make only a few cars each day.", "ipa": "/ˈmɪstər fɔːrd ˈwɒntɪd tuː meɪk kɑːrz. ɪn ˌnaɪnˈtiːn ˈoʊ-θriː, ˈmɪstər fɔːrd ˈstɑːrtɪd ðə fɔːrd ˈmoʊtər ˈkʌmpəni. ænd ðæt taɪm, ðə ˈkʌmpəni wɒz ˈeɪbl tuː meɪk ˈoʊnli ə fjuː kɑːrz iːtʃ deɪ/", "vi": "Ông Ford muốn chế tạo ô tô. Năm 1903, ông thành lập Công ty Ô tô Ford. Vào thời điểm đó, công ty chỉ có thể sản xuất được một vài chiếc xe mỗi ngày." },
      { "start": 39.0, "en": "In 1908, Mr. Ford made the Model T. Everyone loved it! However, Mr. Ford could not make the Model T cars fast enough to meet the high demand.", "ipa": "/ɪn ˌnaɪnˈtiːn ˈoʊ-eɪt, ˈmɪstər fɔːrd meɪd ðə ˈmɒdl tiː. ˈɛvriˌwʌn lʌvd ɪt! haʊˈɛvər, ˈmɪstər fɔːrd kʊd nɒt meɪk ðə ˈmɒdl tiː kɑːrz fɑːst ɪˈnʌf tuː miːt ðə haɪ dɪˈmænd/", "vi": "Năm 1908, ông Ford chế tạo ra mẫu xe Model T. Ai cũng yêu thích nó! Tuy nhiên, ông không thể sản xuất xe Model T đủ nhanh để đáp ứng nhu cầu cao." },
      { "start": 54.0, "en": "In 1913, Mr. Ford changed the way his company made cars. He decided to make a moving assembly line.", "ipa": "/ɪn ˌnaɪnˈtiːn ˈsɪkstiːn-ˈθɜːrti? [correction: ˌnaɪnˈtiːn ˈθɜːrti-θriː -> ˌnaɪnˈtiːn ˈwʌn ˈθaʊznd nʌn ˈhʌndrəd ðɜːrti] ˈmɪstər fɔːrd tʃeɪndʒd ðə weɪ hɪz ˈkʌmpəni meɪd kɑːrz. hiː dɪˈsaɪdɪd tuː meɪk ə ˈmuːvɪŋ əˈsɛmbli laɪn/", "vi": "Năm 1913, ông Ford thay đổi cách công ty mình chế tạo ô tô. Ông quyết định làm một dây chuyền lắp ráp di động." },
      { "start": 64.0, "en": "The workers stayed in one place while the car parts moved on a conveyor belt. This lowered both the time it took to make the cars and the costs.", "ipa": "/ðə ˈwɜːrkərz steɪd ɪn wʌn pleɪs waɪl ðə kɑːr pɑːrts muːvd ɒn ə kənˈveɪər bɛlt. ðɪs ˈloʊərd boʊθ ðə taɪm ɪt tʊk tuː meɪk ðə kɑːrz ænd ðə kɒsts/", "vi": "Công nhân ở một chỗ trong khi các bộ phận xe di chuyển trên băng chuyền. Điều này làm giảm cả thời gian chế tạo xe lẫn chi phí." },
      { "start": 76.0, "en": "Today, Henry Ford's great idea lives on. Assembly lines like his are still being used by many companies all over the world. Mr. Ford truly was an amazing man!", "ipa": "/təˈdeɪ, ˈhɛnri fɔːrdz ɡreɪt aɪˈdiːə lɪvz ɒn. əˈsɛmbli laɪnz laɪk hɪz ɑːr stɪl ˈbiːɪŋ juːzd baɪ ˈmɛni ˈkʌmpəniːz ɔːl ˈoʊvər ðə wɜːrld. ˈmɪstər fɔːrd ˈtruːli wɒz ən əˈmeɪzɪŋ mæn!/", "vi": "Ngày nay, ý tưởng tuyệt vời của Henry Ford vẫn sống mãi. Các dây chuyền lắp ráp như của ông vẫn đang được nhiều công ty trên khắp thế giới sử dụng. Ông Ford thực sự là một con người tuyệt vời!" }
    ]
  },
  {
    "day": 11,
    "title": "Busy As a...",
    "image": "09 September/images/day_11.webp",
    "audio": "09 September/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "Have you ever noticed a little creature called the bee? What an amazing insect.", "ipa": "/hæv juː ˈɛvər ˈnoʊtɪst ə ˈlɪtl ˈkriːtʃər kɔːld ðə biː? wɒt ən əˈmeɪzɪŋ ˈɪnsɛkt/", "vi": "Bạn đã bao giờ chú ý đến một sinh vật nhỏ bé gọi là ong chưa? Quả là một loài côn trùng tuyệt vời." },
      { "start": 12.0, "en": "Bees have little feet and big round eyes. They are yellow and black. You see them buzzing around sweet-smelling flowers everywhere.", "ipa": "/biːz hæv ˈlɪtl fiːt ænd bɪɡ raʊnd aɪz. ðeɪ ɑːr ˈjɛloʊ ænd blæk. juː siː ðɛm ˈbʌzɪŋ əˈraʊnd swiːt-ˈsmɛlɪŋ ˈflaʊərz ˈɛvriˌwɛər/", "vi": "Ong có đôi chân nhỏ và đôi mắt tròn to. Chúng có màu vàng và đen. Bạn có thể thấy chúng vo ve xung quanh những bông hoa thơm ngát ở khắp mọi nơi." },
      { "start": 23.0, "en": "Scientists say that bees are really important. If we did not have bees, there would be no food on earth.", "ipa": "/ˈsaɪəntɪsts seɪ ðæt biːz ɑːr ˈriːəli ɪmˈpɔːrtənt. ɪf wiː dɪd nɒt hæv biːz, ðɛər wʊd biː noʊ fuːd ɒn ɜːrθ/", "vi": "Các nhà khoa học nói rằng loài ong thực sự rất quan trọng. Nếu không có ong, sẽ không có thức ăn trên Trái Đất." },
      { "start": 33.0, "en": "Bees have a short life. They live only about a month, but in that time they fly up to 14 kilometres from their nest, searching for food.", "ipa": "/biːz hæv ə ʃɔːrt laɪf. ðeɪ lɪv ˈoʊnli əˈbaʊt ə mʌnθ, bʌt ɪn ðæt taɪm ðeɪ flaɪ ʌp tuː ˈfɔːrtiːn ˈkɪləˌmiːtərz frɒm ðɛər nɛst, ˈsɜːrtʃɪŋ fɔːr fuːd/", "vi": "Ong có đời sống ngắn ngủi. Chúng chỉ sống khoảng một tháng, nhưng trong khoảng thời gian đó, chúng bay tới 14 km từ tổ để tìm kiếm thức ăn." },
      { "start": 46.0, "en": "What are they looking for? Worker bees are looking for sweet nectar, which they find on flowers. Then they bring it back to the nest for the queen bee.", "ipa": "/wɒt ɑːr ðeɪ ˈlʊkɪŋ fɔːr? ˈwɜːrkər biːz ɑːr ˈlʊkɪŋ fɔːr swiːt ˈnɛktər, wɪtʃ ðeɪ faɪnd ɒn ˈflaʊərz. ðɛn ðeɪ brɪŋ ɪt bæk tuː ðə nɛst fɔːr ðə kwiːn biː/", "vi": "Chúng đang tìm gì vậy? Những con ong thợ đang tìm mật ngọt, thứ mà chúng tìm thấy trên các bông hoa. Sau đó, chúng mang mật về tổ cho ong chúa." },
      { "start": 57.0, "en": "The queen bee lays about 1,500 eggs each day. During her three or four year lifetime, one beehive can have 40,000 to 60,000 bees!", "ipa": "/ðə kwiːn biː leɪz əˈbaʊt wʌn ˈθaʊznd fɑːv ˈhʌndrəd ɛɡz iːtʃ deɪ. ˈdjʊərɪŋ hɜːr θriː ɔːr fɔːr jɪər ˈlaɪfˌtaɪm, wʌn ˈbiːˌhaɪv kæn hæv ˈfɔːrti ˈθaʊznd tuː ˈsɪksti ˈθaʊznd biːz/", "vi": "Ong chúa đẻ khoảng 1.500 quả trứng mỗi ngày. Trong suốt vòng đời 3 hoặc 4 năm của mình, một tổ ong có thể có từ 40.000 đến 60.000 con ong!" },
      { "start": 71.0, "en": "Have you ever been chased by an angry bee? Well, just remember: a bee can fly about 25 kilometres an hour. Most likely, you will never be able to outrun a bee!", "ipa": "/hæv juː ˈɛvər biːn tʃeɪst baɪ ən ˈæŋɡri biː? wɛl, dʒʌst rɪˈmɛmbər: ə biː kæn flaɪ əˈbaʊt ˈtwɛnti-faɪv ˈkɪləˌmiːtərz ən ˈaʊər. moʊst ˈlaɪkli, juː wɪl ˈnɛvər biː ˈeɪbl tuː ˈaʊtˌrʌn ə biː!/", "vi": "Bạn đã bao giờ bị một con ong giận dữ đuổi theo chưa? Chà, hãy nhớ rằng: một con ong có thể bay khoảng 25 km một giờ. Rất có thể, bạn sẽ không bao giờ chạy nhanh hơn một con ong được!" },
      { "start": 85.0, "en": "So don't be afraid of bees. Just let them do their work. They never stop working. That's why people say 'busy as a bee'.", "ipa": "/soʊ doʊnt biː əˈfreɪd əv biːz. dʒʌst lɛt ðɛm duː ðɛər wɜːrk. ðeɪ ˈnɛvər stɒp ˈwɜːrkɪŋ. ðæts waɪ ˈpiːpl seɪ ˈbɪzi æz ə biː/", "vi": "Vì vậy, đừng sợ ong. Hãy để chúng làm việc của mình. Chúng không bao giờ ngừng làm việc. Đó là lý do tại sao mọi người nói 'bận như ong'." }
    ]
  },
  {
    "day": 12,
    "title": "Stand Up Straight and Tall",
    "image": "09 September/images/day_12.webp",
    "audio": "09 September/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "We do not usually think about our feet. They are just there under our legs. Most days, we put socks and shoes on our feet. Some days, we even go barefoot.", "ipa": "/wiː duː nɒt ˈjuːʒuəli θɪŋk əˈbaʊt ˈaʊər fiːt. ðeɪ ɑːr dʒʌst ðɛər ˈʌndər ˈaʊər lɛɡz. moʊst deɪz, wiː pʊt sɒks ænd ʃuːz ɒn ˈaʊər fiːt. sʌm deɪz, wiː ˈiːvn ɡoʊ ˈbɛrˌfʊt/", "vi": "Chúng ta thường không hay nghĩ về đôi bàn chân của mình. Chúng chỉ ở đó dưới chân chúng ta. Hầu hết các ngày, chúng ta đi tất và giày vào chân. Có những ngày, chúng ta thậm chí còn đi chân trần." },
      { "start": 18.0, "en": "But our feet are very important. Why? Think about it. What do you walk on? You walk on your feet, of course. They carry all your weight. If you did not have feet, you would not be able to walk.", "ipa": "/bʌt ˈaʊər fiːt ɑːr ˈvɛri ɪmˈpɔːrtənt. waɪ? θɪŋk əˈbaʊt ɪt. wɒt duː juː wɔːk ɒn? juː wɔːk ɒn jɔːr fiːt, əv kɔːrs. ðeɪ ˈkæri ɔːl jɔːr weɪt. ɪf juː dɪd nɒt hæv fiːt, juː wʊd nɒt biː ˈeɪbl tuː wɔːk/", "vi": "Nhưng đôi bàn chân của chúng ta rất quan trọng. Tại sao ư? Hãy nghĩ về điều đó. Bạn đi trên cái gì? Dĩ nhiên là bạn đi trên đôi chân của mình. Chúng gánh toàn bộ trọng lượng cơ thể bạn. Nếu bạn không có bàn chân, bạn sẽ không thể đi lại được." },
      { "start": 33.0, "en": "What about your toes? Well, they are the most important part of your feet. Your big toes carry nearly half of your total weight.", "ipa": "/wɒt əˈbaʊt jɔːr toʊz? wɛl, ðeɪ ɑːr ðə moʊst ɪmˈpɔːrtənt pɑːrt əv jɔːr fiːt. jɔːr bɪɡ toʊz ˈkæri ˈnɪərli hæf əv jɔːr ˈtoʊtəl weɪt/", "vi": "Còn các ngón chân của bạn thì sao? Vâng, chúng là phần quan trọng nhất trong bàn chân của bạn. Ngón chân cái của bạn gánh gần một nửa tổng trọng lượng cơ thể." },
      { "start": 44.0, "en": "The other eight toes carry about one quarter of your weight. Your two heels carry the rest.", "ipa": "/ði ˈʌðər eɪt toʊz ˈkæri əˈbaʊt wʌn ˈkwɔːrtər əv jɔːr weɪt. jɔːr tuː hiːlz ˈkæri ðə rɛst/", "vi": "Tám ngón chân còn lại gánh khoảng một phần tư trọng lượng của bạn. Hai gót chân của bạn gánh phần còn lại." },
      { "start": 53.0, "en": "One more thing: if you did not have toes, you would fall over when you tried to stand. Toes give you balance.", "ipa": "/wʌn mɔːr θɪŋ: ɪf juː dɪd nɒt hæv toʊz, juː wʊd fɔːl ˈoʊvər wɛn juː traɪd tuː stænd. toʊz ɡɪv juː ˈbæləns/", "vi": "Thêm một điều nữa: nếu bạn không có ngón chân, bạn sẽ bị ngã khi cố đứng lên. Các ngón chân giúp bạn giữ thăng bằng." },
      { "start": 62.0, "en": "So, take care of your feet. Treat them well. You only get two to last a whole lifetime. And you will walk many thousands of kilometres on them.", "ipa": "/soʊ, teɪk kɛər əv jɔːr fiːt. triːt ðɛm wɛl. juː ˈoʊnli ɡɛt tuː tuː lɑːst ə hoʊl ˈlaɪfˌtaɪm. ænd juː wɪl wɔːk ˈmɛni ˈθaʊzndz əv ˈkɪləˌmiːtərz ɒn ðɛm/", "vi": "Vì vậy, hãy chăm sóc đôi bàn chân của bạn. Đối xử tốt với chúng. Bạn chỉ có hai chiếc để dùng cho cả cuộc đời. Và bạn sẽ đi hàng ngàn kilômét trên đôi chân đó." }
    ]
  },
  {
    "day": 13,
    "title": "27 Needles",
    "image": "09 September/images/day_13.webp",
    "audio": "09 September/audio/Track13.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Sam was walking his dog Homer in a field. He threw a ball for the dog to run after and bring back. But, the ball went far into some bushes.", "ipa": "/wʌn deɪ, sæm wɒz ˈwɔːkɪŋ hɪz dɔːɡ ˈhoʊmər ɪn ə fiːld. hiː θruː ə bɔːl fɔːr ðə dɔːr tuː rʌn ˈɑːftər ænd brɪŋ bæk. bʌt, ðə bɔːl wɛnt fɑːr ˈɪntuː sʌm ˈbʊʃɪz/", "vi": "Một hôm, Sam đang dắt chú chó Homer đi dạo trên một cánh đồng. Cậu ném một quả bóng để chó chạy theo và mang về. Nhưng quả bóng lại bay sâu vào trong mấy bụi cây." },
      { "start": 17.0, "en": "Homer ran to get the ball. But he was gone in the bushes for a long time. Sam started to worry.", "ipa": "/ˈhoʊmər ræn tuː ɡɛt ðə bɔːl. bʌt hiː wɒz ɡɒn ɪn ðə ˈbʊʃɪz fɔːr ə lɒŋ taɪm. sæm ˈstɑːrtɪd tuː ˈwʌri/", "vi": "Homer chạy đi lấy bóng. Nhưng nó biến mất trong bụi cây một lúc lâu. Sam bắt đầu cảm thấy lo lắng." },
      { "start": 26.0, "en": "He called and called, but he couldn't see Homer anywhere. So, Sam went deep inside the bushes to look for his dog.", "ipa": "/hiː kɔːld ænd kɔːld, bʌt hiː ˈkʊdnt siː ˈhoʊmər ˈɛniˌwɛər. soʊ, sæm wɛnt diːp ɪnˈsaɪd ðə ˈbʊʃɪz tuː lʊk fɔːr hɪz dɔːɡ/", "vi": "Cậu gọi mãi gọi mãi, nhưng chẳng thấy Homer ở đâu cả. Thế là Sam đành bước sâu vào bên trong bụi cây để tìm chú chó của mình." },
      { "start": 37.0, "en": "All of a sudden, he was face to face with a porcupine. Homer, being a very friendly dog, tried to sniff the porcupine.", "ipa": "/ɔːl əv ə ˈsʌdn, hiː wɒz feɪs tuː feɪs wɪð ə ˈpɔːrkjəˌpaɪn. ˈhoʊmər, ˈbiːɪŋ ə ˈvɛri ˈfrɛndli dɔːɡ, traɪd tuː snɪf ðə ˈpɔːrkjəˌpaɪn/", "vi": "Đột nhiên, cậu giáp mặt với một con nhím gai. Homer, vốn là một chú chó rất thân thiện, liền cố gắng ngửi con nhím." },
      { "start": 50.0, "en": "But the fearful animal turned his back and pushed its needles into poor Homer's face. Homer let out a terrible howl and ran away.", "ipa": "/bʌt ðə ˈfɪrfʊl ˈænɪml tɜːrnd hɪz bæk ænd pʊʃt ɪts ˈniːdlz ˈɪntuː pʊr ˈhoʊmərɪz feɪs. ˈhoʊmər lɛt aʊt ə ˈtɛrəbl haʊl ænd ræn əˈweɪ/", "vi": "Nhưng con vật sợ hãi đó đã quay lưng lại và phóng những chiếc kim nhím vào mặt tội nghiệp của Homer. Homer hét lên một tiếng đau đớn khủng khiếp và bỏ chạy." },
      { "start": 63.0, "en": "After that, Sam had to take his dog to the vet. Homer got 27 needles removed from his nose and face.", "ipa": "/ˈɑːftər ðæt, sæm hæd tuː teɪk hɪz dɔːɡ tuː ðə vɛt. ˈhoʊmər ɡɒt ˈtwɛnti-sēvən ˈniːdlz rɪˈmuːvd frɒm hɪz noʊz ænd feɪs/", "vi": "Sau đó, Sam phải đưa chú chó của mình đến bác sĩ thú y. Homer đã phải gắp ra 27 chiếc kim nhím cắm trên mũi và mặt." },
      { "start": 74.0, "en": "Poor Homer learned a big lesson that day. Never get too close to a porcupine-especially a scared one!", "ipa": "/pʊr ˈhoʊmər lɜːrnd ə bɪɡ ˈlɛsn ðæt deɪ. ˈnɛvər ɡɛt tuː kloʊs tuː ə ˈpɔːrkjəˌpaɪn-ɪˈspɛʃəli ə skɛrd wʌn!/", "vi": "Tội nghiệp Homer, hôm đó chú chó đã rút ra được một bài học xương máu. Đừng bao giờ đến quá gần một con nhím - đặc biệt là con nhím đang hoảng sợ!" }
    ]
  },
  {
    "day": 14,
    "title": "Baby Bird",
    "image": "09 September/images/day_14.webp",
    "audio": "09 September/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "'Look!' cried Julie. 'It's a baby bird!' The other children looked. There, on the ground in front of them, was a tiny bird.", "ipa": "/lʊk!, kraɪd ˈdʒuːli. ɪts ə ˈbeɪbi bɜːd! ði ˈʌðər ˈtʃɪldrən lʊkt. ðɛər, ɒn ðə ɡraʊnd ɪn frʌnt əv ðɛm, wɒz ə ˈtaɪni bɜːd/", "vi": "'Nhìn kìa!' Julie hét lên. 'Đó là một chú chim non!' Những đứa trẻ khác nhìn theo. Ở đó, trên mặt đất ngay trước mặt chúng, là một chú chim nhỏ xíu." },
      { "start": 16.0, "en": "'It must have fallen out of its nest,' said Richard, pointing up at a tree nearby. 'What should we do?' asked Flora. 'If we just leave it there, a cat might eat it.'", "ipa": "/ɪt mʌst hæv ˈfɔːlən aʊt əv ɪts nɛst, sɛd ˈrɪtʃərd, ˈpɔɪntɪŋ ʌp æt ə triː nɪrˈbaɪ. wɒt ʃʊd wiː duː?, ɑːskt ˈflɔːrə. ɪf wiː dʒʌst liːv ɪt ðɛər, ə kæt maɪt iːt ɪt/", "vi": "'Nó chắc hẳn đã rơi khỏi tổ,' Richard nói, vừa chỉ lên một cái cây gần đó. 'Chúng ta phải làm gì đây?' Flora hỏi. 'Nếu chúng ta cứ để nó ở đó, mèo có thể ăn thịt nó mất.'" },
      { "start": 32.0, "en": "'Let's ask Dad what to do,' said Richard. Julie ran to get Dad while the other children watched over the baby bird.", "ipa": "/lɛts ɑːsk dæd wɒt tuː duː, sɛd ˈrɪtʃərd. ˈdʒuːli ræn tuː ɡɛt dæd waɪl ði ˈʌðər ˈtʃɪldrən wɒtʃt ˈoʊvər ðə ˈbeɪbi bɜːd/", "vi": "'Hãy hỏi bố xem phải làm gì đi,' Richard nói. Julie chạy đi gọi bố trong khi những đứa trẻ khác ở lại canh chừng chú chim non." },
      { "start": 44.0, "en": "Dad brought his ladder to the tree. He held the ladder while Julie climbed up and put the baby bird back in the nest.", "ipa": "/dæd brɔːt hɪz ˈlædər tuː ðə triː. hiː hɛld ðə ˈlædər waɪl ˈdʒuːli klaɪmd ʌp ænd pʊt ðə ˈbeɪbi bɜːd bæk ɪn ðə nɛst/", "vi": "Bố mang chiếc thang đến cây. Bố giữ thang để Julie trèo lên và đặt chú chim non trở lại tổ của nó." },
      { "start": 56.0, "en": "'Julie was the one who found the bird, so she should be the one to put it back,' said Dad. The children and their father were all happy that the baby bird was safely back home.", "ipa": "/ˈdʒuːli wɒz ði wʌn huː faʊnd ðə bɜːd, soʊ ʃiː ʃʊd biː ði wʌn tuː pʊt ɪt bæk, sɛd dæd. ðə ˈtʃɪldrən ænd ðɛər ˈfɑːðər wɜːr ɔːl ˈhæpi ðæt ðə ˈbeɪbi bɜːd wɒz ˈseɪfli bæk hoʊm/", "vi": "'Julie là người tìm thấy chú chim, vì vậy con bé nên là người đưa nó về,' bố nói. Đám trẻ và bố của chúng đều rất vui vì chú chim non đã an toàn trở về nhà." }
    ]
  },
  {
    "day": 15,
    "title": "Ants in My Pants",
    "image": "09 September/images/day_15.webp",
    "audio": "09 September/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, while I was playing baseball, I slid onto second base and hurt my leg. I lay on the ground in pain.", "ipa": "/wʌn deɪ, waɪl aɪ wɒz ˈpleɪɪŋ ˈbeɪsˌbɔːl, aɪ slɪd ˈɒntuː ˈsɛkənd beɪs ænd hɜːrt maɪ lɛɡ. aɪ leɪ ɒn ðə ɡraʊnd ɪn peɪn/", "vi": "Một hôm, khi đang chơi bóng chày, tôi trượt chân vào gót chân thứ hai và làm đau chân mình. Tôi nằm dài trên mặt đất vì đau đớn." },
      { "start": 16.0, "en": "Suddenly, I felt a sting on my leg. I looked and saw hundreds of ants crawling all over me. I was lying on an anthill!", "ipa": "/ˈsʌdənli, aɪ fɛlt ə stɪŋ ɒn maɪ lɛɡ. aɪ lʊkt ænd sɔː ˈhʌndrədz əv ænts ˈkrɔːlɪŋ ɔːl ˈoʊvər miː. aɪ wɒz ˈlaɪɪŋ ɒn ən ˈænθˌhɪl/", "vi": "Đột nhiên, tôi cảm thấy nhói ở chân. Tôi nhìn xuống và thấy hàng trăm con kiến đang bò khắp người mình. Tôi đang nằm trên một tổ kiến!" },
      { "start": 27.0, "en": "I panicked and pulled my pants off, trying to get the ants off me. Of course, everyone laughed at me. I sat down and felt very silly. I even got mad at the ants.", "ipa": "/aɪ ˈpænɪkt ænd pʊld maɪ pænts ɔːf, ˈtraɪɪŋ tuː ɡɛt ði ænts ɔːf miː. əv kɔːrs, ˈɛvriˌwʌn lɑːft æt miː. aɪ sæt daʊn ænd fɛlt ˈvɛri ˈsɪli. aɪ ˈiːvn ɡɒt mæd æt ði ænts/", "vi": "Tôi hoảng loạn và cởi phăng quần ra, cố gắng phủi sạch lũ kiến trên người. Tất nhiên, mọi người đã cười chế nhạo tôi. Tôi ngồi xuống và cảm thấy mình thật ngớ ngẩn. Tôi thậm chí còn tức giận với cả lũ kiến." },
      { "start": 44.0, "en": "Then, I felt something on my arm. It was one last ant. I was just about to slap my hand down on it when I took a closer look.", "ipa": "/ðɛn, aɪ fɛlt ˈsʌmθɪŋ ɒn maɪ ɑːrm. ɪt wɒz wʌn lɑːst ænt. aɪ wɒz dʒʌst əˈbaʊt tuː slæp maɪ hænd daʊn ɒn ɪt wɛn aɪ tʊk ə ˈkloʊsər lʊk/", "vi": "Sau đó, tôi cảm thấy có gì đó trên tay mình. Đó là con kiến cuối cùng. Tôi chuẩn bị giơ tay đập bẹp nó thì chợt nhìn kỹ lại." },
      { "start": 56.0, "en": "Here was this little creature looking up at me. I thought, 'It didn't do anything to me. I was the one who charged into its home!'", "ipa": "/hɪər wɒz ðɪs ˈlɪtl ˈkriːtʃər ˈlʊkɪŋ ʌp æt miː. aɪ θɔːt, ɪt ˈdɪdnt duː ˈɛniˌθɪŋ tuː miː. aɪ wɒz ði wʌn huː tʃɑːrdʒd ˈɪntuː ɪts hoʊm!/", "vi": "Đó là một sinh vật nhỏ bé đang ngước nhìn lên tôi. Tôi nghĩ, 'Nó có làm gì mình đâu. Mình mới chính là kẻ xông vào nhà của nó cơ mà!'" },
      { "start": 68.0, "en": "I lowered my elbow to the ground and said, 'You go.' The ant ran off to his life at the anthill.", "ipa": "/aɪ ˈloʊərd maɪ ˈɛlboʊ tuː ðə ɡraʊnd ænd sɛd, juː ɡoʊ. ði ænt ræn ɔːf tuː hɪz laɪf æt ðə ˈænθˌhɪl/", "vi": "Tôi hạ khuỷu tay xuống mặt đất và nói: 'Đi đi.' Con kiến liền chạy đi để tiếp tục cuộc sống của nó ở tổ kiến." }
    ]
  },
  {
    "day": 16,
    "title": "The Race",
    "image": "09 September/images/day_16.webp",
    "audio": "09 September/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "Beetle was very fast and he loved showing off. One day, he challenged every other bug in the forest to a race.", "ipa": "/ˈbiːtl wɒz ˈvɛri fɑːst ænd hiː lʌvd ˈʃoʊɪŋ ɒf. wʌn deɪ, hiː ˈtʃælɪndʒd ˈɛvri ˈʌðər bʌɡ ɪn ðə ˈfɔːrɪst tuː ə reɪs/", "vi": "Bọ Cánh Cứng rất nhanh nhẹn và rất thích khoe khoang. Một hôm, cậu thách đấu đua với mọi loài côn trùng khác trong rừng." },
      { "start": 14.0, "en": "Ants, grasshoppers, spiders and one caterpillar lined up at the starting line. They waited a long time for Beetle to line up for the race.", "ipa": "/ænts, ˈɡræsˌhɒpərz, ˈspaɪdərz ænd wʌn ˈkætərˌpɪlər laɪnd ʌp æt ðə ˈstɑːrtɪŋ laɪn. ðeɪ ˈweɪtɪd ə lɒŋ taɪm fɔːr ˈbiːtl tuː laɪn ʌp fɔːr ðə reɪs/", "vi": "Kiến, châu chấu, nhện và một chú sâu bướm xếp hàng tại vạch xuất phát. Chúng phải đợi một thời gian dài để Bọ Cánh Cứng ra xếp hàng chuẩn bị đua." },
      { "start": 26.0, "en": "He could not stop bragging about how fast he was to all the other bugs that came to watch.", "ipa": "/hiː kʊd nɒt stɒp ˈbræɡɪŋ əˈbaʊt haʊ fɑːst hiː wɒz tuː ɔːl ði ˈʌðər bʌɡz ðæt keɪm tuː wɒtʃ/", "vi": "Cậu ta không ngừng khoác lác về việc mình chạy nhanh thế nào với tất cả những con côn trùng đến xem." },
      { "start": 35.0, "en": "By the time the race finally started, the caterpillar had turned into a cocoon right on the starting line.", "ipa": "/baɪ ðə taɪm ðə reɪs ˈfaɪnəli ˈstɑːrtɪd, ðə ˈkætərˌpɪlər hæd tɜːrnd ˈɪntuː ə kəˈkuːn raɪt ɒn ðə ˈstɑːrtɪŋ laɪn/", "vi": "Đến lúc cuộc đua chính thức bắt đầu, chú sâu bướm đã biến thành một cái kén ngay tại vạch xuất phát." },
      { "start": 44.0, "en": "Soon, the race was over and Beetle had won. He laughed and laughed at the poor caterpillar stuck on the starting line.", "ipa": "/suːn, ðə reɪs wɒz ˈoʊvər ænd ˈbiːtl hæd wʌn. hiː lɑːft ænd lɑːft æt ðə pʊr ˈkætərˌpɪlər stʌk ɒn ðə ˈstɑːrtɪŋ laɪn/", "vi": "Chẳng mấy chốc, cuộc đua kết thúc và Bọ Cánh Cứng là người chiến thắng. Cậu ta cười chế nhạo chú sâu bướm tội nghiệp đang kẹt lại ở vạch xuất phát." },
      { "start": 54.0, "en": "He loved making fun of the caterpillar. So he said, 'Hey, Caterpillar! Let's race again!'", "ipa": "/hiː lʌvd ˈmeɪkɪŋ fʌn əv ðə ˈkætərˌpɪlər. soʊ hiː sɛd, heɪ, ˈkætərˌpɪlər! lɛts reɪs əˈɡɛn!/", "vi": "Cậu ta rất thích trêu chọc sâu bướm. Thế nên cậu ta nói: 'Này, Sâu Bướm! Chúng ta đua lại đi!'" },
      { "start": 62.0, "en": "'Ready. Set. Go!' Beetle was off like a bullet, heading straight for the finish line and laughing the whole way.", "ipa": "/ˈrɛdi. sɛt. ɡoʊ! ˈbiːtl wɒz ɒf laɪk ə ˈbʊlɪt, ˈhɛdɪŋ streɪt fɔːr ðə ˈfɪnɪʃ laɪn ænd ˈlɑːfɪŋ ðə hoʊl weɪ/", "vi": "'Ra hiệu. Chuẩn bị. Chạy!' Bọ Cánh Cứng lao đi như một viên đạn, tiến thẳng về vạch đích và cười lớn suốt dọc đường." },
      { "start": 72.0, "en": "Suddenly, a moth with wings as white as snow broke out of the cocoon. It flew past Beetle and won the race!", "ipa": "/ˈsʌdənli, ə mɔːθ wɪð wɪŋz æz waɪt æz snoʊ broʊk aʊt əv ðə kəˈkuːn. ɪt fluː pɑːst ˈbiːtl ænd wʌn ðə reɪs/", "vi": "Đột nhiên, một chú ngài với đôi cánh trắng như tuyết chui ra khỏi cái kén. Nó bay vụt qua Bọ Cánh Cứng và giành chiến thắng cuộc đua!" }
    ]
  },
  {
    "day": 17,
    "title": "Sara's Dream (I)",
    "image": "09 September/images/day_17.webp",
    "audio": "09 September/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "Sara comes from a big family. They live a small apartment. Sara's dad works hard. But he doesn't make enough money to buy a house.", "ipa": "/ˈsɛərə kʌmz frɒm ə bɪɡ ˈfæməli. ðeɪ lɪv ə smɔːl əˈpɑːrtmənt. ˈsɛərəz dæd wɜːrks hɑːrd. bʌt hiː ˈdʌznt meɪk ɪˈnʌf ˈmʌni tuː baɪ ə haʊs/", "vi": "Sara đến từ một gia đình đông con. Họ sống trong một căn hộ nhỏ. Bố của Sara làm việc vất vả. Nhưng ông kiếm không đủ tiền để mua một ngôi nhà." },
      { "start": 16.0, "en": "Sara had a dream. She dreamed that one day, her family would have their own home. It seemed that this would never happen. But Sara's friend Jenny wanted to help.", "ipa": "/ˈsɛərə hæd ə driːm. ʃiː driːmd ðæt wʌn deɪ, hɜːr ˈfæməli wʊd hæv ðɛər oʊn hoʊm. ɪt siːmd ðæt ðɪs wʊd ˈnɛvər ˈhæpən. bʌt ˈsɛərəz frɛnd ˈdʒɛni ˈwɒntɪd tuː hɛlp/", "vi": "Sara có một giấc mơ. Cô bé mơ rằng một ngày nào đó, gia đình cô sẽ có ngôi nhà của riêng mình. Có vẻ như điều này sẽ không bao giờ xảy ra. Nhưng bạn của Sara là Jenny muốn giúp đỡ." },
      { "start": 29.0, "en": "Jenny heard about a program called Houses for People. Many people get together and help to build a house for a family in need. They work for free. Local businesses buy wood and materials to build the house.", "ipa": "/ˈdʒɛni hɜːrd əˈbaʊt ə ˈproʊɡræm kɔːld ˈhaʊzɪz fɔːr ˈpiːpl. ˈmɛni ˈpiːpl ɡɛt təˈɡɛðər ænd hɛlp tuː bɪld ə haʊs fɔːr ə ˈfæməli ɪn niːd. ðeɪ wɜːrk fɔːr friː. ˈloʊkl ˈbɪznɪsɪz baɪ wʊd ænd məˈtɪriəlz tuː bɪld ðə haʊs/", "vi": "Jenny đã nghe về một chương trình gọi là Những ngôi nhà cho mọi người. Nhiều người tụ tập lại và giúp xây dựng một ngôi nhà cho một gia đình cần giúp đỡ. Họ làm việc miễn phí. Các doanh nghiệp địa phương mua gỗ và vật liệu để xây nhà." },
      { "start": 47.0, "en": "Anyone can help. It doesn't matter if you don't have skills or experience building houses. There is always something to do. Jenny told Sara about the program. Her family applied.", "ipa": "/ˈɛniˌwʌn kæn hɛlp. ɪt ˈdʌznt ˈmætər ɪf juː doʊnt hæv skɪlz ɔːr ɪkˈspɪriəns ˈbɪldɪŋ ˈhaʊzɪz. ðɛər ɪz ˈɔːlweɪz ˈsʌmθɪŋ tuː duː. ˈdʒɛni toʊld ˈsɛərə əˈbaʊt ðə ˈproʊɡræm. hɜːr ˈfæməli əˈplaɪd/", vi: "Bất cứ ai cũng có thể giúp đỡ. Không quan trọng nếu bạn không có kỹ năng hay kinh nghiệm xây nhà. Luôn có việc gì đó để làm. Jenny kể cho Sara nghe về chương trình. Gia đình cô ấy đã đăng ký." },
      { "start": 62.0, "en": "And guess what? They were accepted! Everyone waited anxiously for the work to begin.", "ipa": "/ænd ɡɛs wɒt? ðeɪ wɜːr əkˈsɛptɪd! ˈɛvriˌwʌn ˈweɪtɪd ˈæŋkʃəsli fɔːr ðə wɜːrk tuː bɪˈɡɪn/", "vi": "Và đoán xem? Họ đã được chấp nhận! Mọi người nóng lòng chờ đợi công việc bắt đầu." }
    ]
  },
  {
    "day": 18,
    "title": "Sara's Dream (II)",
    "image": "09 September/images/day_18.webp",
    "audio": "09 September/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "After a long winter of waiting, Sara's family found a place to build their new home. On June 1, everything was ready.", "ipa": "/ˈɑːftər ə lɒŋ ˈwɪntər əv ˈweɪtɪŋ, ˈsɛərəz ˈfæməli faʊnd ə pleɪs tuː bɪld ðɛər njuː hoʊm. ɒn dʒuːn wʌn, ˈɛvriˌθɪŋ wɒz ˈrɛdi/", "vi": "Sau một mùa đông dài chờ đợi, gia đình Sara đã tìm được một nơi để xây dựng ngôi nhà mới của họ. Vào ngày 1 tháng 6, mọi thứ đã sẵn sàng." },
      { "start": 15.0, "en": "It was early Saturday morning. More than thirty people showed up. They brought tools and food. People worked hard all day. You could hear the sound of hammers and saws everywhere.", "ipa": "/ɪt wɒz ˈɜːrli ˈsætərdeɪ ˈmɔːrnɪŋ. mɔːr ðæn ˈθɜːrti ˈpiːpl ʃoʊd ʌp. ðeɪ brɔːt tuːlz ænd fuːd. ˈpiːpl wɜːrkt hɑːrd ɔːl deɪ. juː kʊd hɪər ðə saʊnd əv ˈhæmərz ænd sɔːz ˈɛvriˌwɛər/", "vi": "Đó là một buổi sáng thứ Bảy sớm. Hơn ba mươi người đã xuất hiện. Họ mang theo dụng cụ và thức ăn. Mọi người làm việc chăm chỉ suốt cả ngày. Bạn có thể nghe thấy tiếng búa và tiếng cưa ở khắp mọi nơi." },
      { "start": 30.0, "en": "Jenny and Sara came to help too. They could not believe how many people had come to help.", "ipa": "/ˈdʒɛni ænd ˈsɛərə keɪm tuː hɛlp tuː. ðeɪ kʊd nɒt bɪˈliːv haʊ ˈmɛni ˈpiːpl hæd kʌm tuː hɛlp/", "vi": "Jenny và Sara cũng đến giúp một tay. Họ không thể tin được có nhiều người đến giúp đỡ đến vậy." },
      { "start": 39.0, "en": "At the end of the weekend, the new house was well under way. It was a good beginning. Over the next three weeks, it was slowly built.", "ipa": "/æt ði ɛnd əv ðə ˈwiːkˌɛnd, ðə njuː haʊs wɒz wɛl ˈʌndər weɪ. ɪt wɒz ə ɡʊd bɪˈɡɪnɪŋ. ˈoʊvər ðə nɛkst θriː wiːks, ɪt wɒz ˈsloʊli bɪlt/", "vi": "Vào cuối tuần, ngôi nhà mới đã tiến triển rất tốt. Đó là một khởi đầu suôn sẻ. Trong ba tuần tiếp theo, ngôi nhà dần được xây lên." },
      { "start": 52.0, "en": "Finally, the big day came. Where once only a dream stood, there was now a small new house with pretty red and orange paint.", "ipa": "/ˈfaɪnəli, ðə bɪɡ deɪ keɪm. wɛər wʌns ˈoʊnli ə driːm stʊd, ðɛər wɒz naʊ ə smɔːl njuː haʊs wɪð ˈprɪti rɛd ænd ˈɔːrɪndʒ peɪnt/", "vi": "Cuối cùng, ngày trọng đại cũng đến. Nơi mà trước đây chỉ có trong giấc mơ, giờ đây đã xuất hiện một ngôi nhà mới nhỏ xinh với lớp sơn màu đỏ và cam đẹp mắt." }
    ]
  },
  {
    "day": 19,
    "title": "Where Is David?",
    "image": "09 September/images/day_19.webp",
    "audio": "09 September/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "David's mom always wants her son to be the best at everything in school.", "ipa": "/ˈdeɪvɪdz mɒm ˈɔːlweɪz wɒnts hɜːr sʌn tuː biː ðə bɛst æt ˈɛvriˌθɪŋ ɪn skuːl/", "vi": "Mẹ của David luôn muốn con trai mình giỏi nhất ở mọi thứ trong trường." },
      { "start": 10.0, "en": "One day, she had to go on a business trip. So, she sent her son to stay with her friend. Before she left, she told her friend to remind David to study for an important test.", "ipa": "/wʌn deɪ, ʃiː hæd tuː ɡoʊ ɒn ə ˈbɪznɪs trɪp. soʊ, ʃiː sɛnt hɜːr sʌn tuː steɪ wɪð hɜːr frɛnd. bɪˈfɔːr ʃiː lɛft, ʃiː toʊld hɜːr frɛnd tuː rɪˈmaɪnd ˈdeɪvɪd tuː ˈstʌdi fɔːr ən ɪmˈpɔːrtənt tɛst/", "vi": "Một ngày nọ, cô ấy phải đi công tác. Vì vậy, cô gửi con trai ở lại với bạn mình. Trước khi đi, cô dặn bạn mình nhắc David học bài cho một bài kiểm tra quan trọng." },
      { "start": 23.0, "en": "A week later, David's mom came back, eager to see her son. But David wasn't in his room.", "ipa": "/ə wiːk ˈleɪtər, ˈdeɪvɪdz mɒm keɪm bæk, ˈiːɡər tuː siː hɜːr sʌn. bʌt ˈdeɪvɪd ˈwɒznt ɪn hɪz ruːm/", "vi": "Một tuần sau, mẹ của David quay lại, rất háo hức muốn gặp con trai. Nhưng David không có trong phòng của mình." },
      { "start": 32.0, "en": "'That's strange. I thought he was working on his homework here,' said the friend. 'Let's see if he is downstairs.'", "ipa": "/ðæts streɪndʒ. aɪ θɔːt hiː wɒz ˈwɜːrkɪŋ ɒn hɪz ˈhoʊmˌwɜːrk hɪər, sɛd ðə frɛnd. lɛts siː ɪf hiː ɪz ˈdaʊnˌstɛərz/", "vi": "'Thật lạ. Tôi cứ nghĩ nó đang làm bài tập ở đây chứ,' người bạn nói. 'Hãy xem cậu bé có ở dưới nhà không.'" },
      { "start": 41.0, "en": "They looked everywhere. 'He can't be far,' said her friend. 'He was here a minute ago. Let's search the room again.'", "ipa": "/ðeɪ lʊkt ˈɛvriˌwɛər. hiː kænt biː fɑːr, sɛd hɜːr frɛnd. hiː wɒz hɪər ə ˈmɪnɪt əˈɡoʊ. lɛts sɜːrtʃ ðə ruːm əˈɡɛn/", "vi": "Họ tìm kiếm khắp mọi nơi. 'Nó không thể đi xa được đâu,' người bạn nói. 'Nó vừa ở đây một phút trước thôi. Hãy tìm lại trong phòng lần nữa xem.'" },
      { "start": 52.0, "en": "Finally, they found David hiding in the closet. David said that he was afraid to see his mom. He had not done well in his test. He was afraid that his mother would be disappointed and angry.", "ipa": "/ˈfaɪnəli, ðeɪ faʊnd ˈdeɪvɪd ˈhaɪdɪŋ ɪn ðə ˈklɒzɪt. ˈdeɪvɪd sɛd ðæt hiː wɒz əˈfreɪd tuː siː hɪz mɒm. hiː hæd nɒt dʌn wɛl ɪn hɪz tɛst. hiː wɒz əˈfreɪd ðæt hɪz ˈmʌðər wʊd biː ˌdɪsəˈpɔɪntɪd ænd ˈæŋɡri/", "vi": "Cuối cùng, họ tìm thấy David đang trốn trong tủ quần áo. David nói rằng cậu sợ gặp mẹ. Cậu đã làm bài kiểm tra không tốt. Cậu sợ rằng mẹ sẽ thất vọng và tức giận." },
      { "start": 68.0, "en": "Mom held her son tightly. 'I'm so sorry, David. I won't be angry as long as you did your best,' she said. 'Please don't hide in the closet or I'll be very disappointed!'", "ipa": "/mɒm hɛld hɜːr sʌn ˈtaɪtli. aɪm soʊ ˈsɒri, ˈdeɪvɪd. aɪ woʊnt biː ˈæŋɡri æz lɒŋ æz juː dɪd jɔːr bɛst, ʃiː sɛd. pliːz doʊnt haɪd ɪn ðə ˈklɒzɪt ɔːr aɪl biː ˈvɛri ˌdɪsəˈpɔɪntɪd!/", "vi": "Mẹ ôm chặt con trai. 'Mẹ rất xin lỗi, David. Mẹ sẽ không giận miễn là con đã cố gắng hết sức,' cô nói. 'Xin đừng trốn trong tủ nữa nếu không mẹ sẽ rất thất vọng đấy!'" }
    ]
  },
  {
    "day": 20,
    "title": "A Vacation Yurt",
    "image": "09 September/images/day_20.webp",
    "audio": "09 September/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "In school, we learned about the different ways people live in the world. You know, like the kinds of houses they live in, the food they eat and things like that.", "ipa": "/ɪn skuːl, wiː lɜːrnd əˈbaʊt ðə ˈdɪfrənt weɪz ˈpiːpl lɪv ɪn ðə wɜːrld. juː noʊ, laɪk ðə kaɪndz əv ˈhaʊzɪz ðeɪ lɪv ɪn, ðə fuːd ðeɪ iːt ænd θɪŋz laɪk ðæt/", "vi": "Ở trường, chúng tôi đã học về những cách sống khác nhau của con người trên thế giới. Bạn biết đấy, như những loại nhà họ ở, thức ăn họ ăn và những thứ đại loại như vậy." },
      { "start": 16.0, "en": "I found out something very interesting when we learned about Mongolia. For thousands of years, the Mongols have been building really unique houses. They are called yurts.", "ipa": "/aɪ faʊnd aʊt ˈsʌmθɪŋ ˈvɛri ˈɪntrəstɪŋ wɛn wiː lɜːrnd əˈbaʊt mɒŋˈɡoʊliə. fɔːr ˈθaʊzndz əv jɪərz, ðə ˈmɒŋɡəlz hæv biːn ˈbɪldɪŋ ˈriːəli juˈniːk ˈhaʊzɪz. ðeɪ ɑːr kɔːld jɜːrts/", "vi": "Tôi đã phát hiện ra điều rất thú vị khi học về Mông Cổ. Trong hàng ngàn năm, người Mông Cổ đã xây dựng những ngôi nhà thực sự độc đáo. Chúng được gọi là lều yurt." },
      { "start": 29.0, "en": "Long ago, yurts were the perfect homes for the people of Mongolia. They were easy to build. They were also easy to move around from place to place.", "ipa": "/lɒŋ əˈɡoʊ, jɜːrts wɜːr ðə ˈpɜːrfɪkt hoʊmz fɔːr ðə ˈpiːpl əv mɒŋˈɡoʊliə. ðeɪ wɜːr ˈiːzi tuː bɪld. ðeɪ wɜːr ˈɔːlsoʊ ˈiːzi tuː muːv əˈraʊnd frɒm pleɪs tuː pleɪs/", "vi": "Ngày xửa ngày xưa, lều yurt là những ngôi nhà hoàn hảo cho người dân Mông Cổ. Chúng rất dễ xây dựng. Chúng cũng dễ dàng di chuyển từ nơi này sang nơi khác." },
      { "start": 41.0, "en": "Yurts were warm in the winter and cool in the summer. Today, many Mongols still live in yurts.", "ipa": "/jɜːrts wɜːr wɔːrm ɪn ðə ˈwɪntər ænd kuːl ɪn ðə ˈsʌmər. təˈdeɪ, ˈmɛni ˈmɒŋɡəlz stɪl lɪv ɪn jɜːrts/", "vi": "Lều yurt ấm áp vào mùa đông và mát mẻ vào mùa hè. Ngày nay, nhiều người Mông Cổ vẫn sống trong lều yurt." },
      { "start": 50.0, "en": "There is a big park here in Canada where you can rent a yurt. When my family was planning our summer vacation, I asked if we could camp out in a yurt. My mom agreed.", "ipa": "/ðɛər ɪz ə bɪɡ pɑːrk hɪər ɪn ˈkænədə wɛr juː kæn rɛnt ə jɜːrt. wɛn maɪ ˈfæməli wɒz ˈplænɪŋ ˈaʊər ˈsʌmər vəˈkeɪʃn, aɪ ɑːskt ɪf wiː kʊd kæmp aʊt ɪn ə jɜːrt. maɪ mɒm əˈɡriːd/", "vi": "Có một công viên lớn ở đây tại Canada nơi bạn có thể thuê một chiếc lều yurt. Khi gia đình tôi đang lên kế hoạch cho kỳ nghỉ hè, tôi đã hỏi liệu chúng tôi có thể cắm trại trong lều yurt không. Mẹ tôi đã đồng ý." },
      { "start": 65.0, "en": "Wow, what a perfect house! As I went to sleep in the yurt the first night, I imagined that I was a Mongol boy, safe in my cozy family home.", "ipa": "/waʊ, wɒt ə ˈpɜːrfɪkt haʊs! æz aɪ wɛnt tuː sliːp ɪn ðə jɜːrt ðə fɜːrst naɪt, aɪ ɪˈmædʒɪnd ðæt aɪ wɒz ə ˈmɒŋɡəl bɔɪ, seɪf ɪn maɪ ˈkoʊzi ˈfæməli hoʊm/", "vi": "Ồ, thật là một ngôi nhà hoàn hảo! Khi tôi chìm vào giấc ngủ trong lều yurt vào đêm đầu tiên, tôi tưởng tượng mình là một cậu bé Mông Cổ, được an toàn trong ngôi nhà gia đình ấm cúng của mình." }
    ]
  },
  {
    "day": 21,
    "title": "City by the Sea",
    "image": "09 September/images/day_21.webp",
    "audio": "09 September/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "Some cities are thousands of years old, and some cities are young.", "ipa": "/sʌm ˈsɪtiz ɑːr ˈθaʊzndz əv jɪərz oʊld, ænd sʌm ˈsɪtiz ɑːr jʌŋ/", "vi": "Một số thành phố đã hàng ngàn năm tuổi, và một số thành phố thì còn trẻ." },
      { "start": 10.0, "en": "Long ago, in 1788, England decided to send all its bad criminals as far away as possible. So they were put on ships and sent all the way around the world to an island.", "ipa": "/lɒŋ əˈɡoʊ, ɪn ˌeɪtiːn ˈɛti-eɪt [correction: ˌsɪksti-eɪt], ˈɪŋɡlənd dɪˈsaɪdɪd tuː sɛnd ɔːl ɪts bæd ˈkrɪmənlz æz fɑːr əˈweɪ æz ˈpɒsəbl. soʊ ðeɪ wɜːr pʊt ɒn ʃɪps ænd sɛnt ɔːl ðə weɪ əˈraʊnd ðə wɜːrld tuː ən ˈaɪlənd/", "vi": "Cách đây lâu lắm rồi, vào năm 1788, nước Anh quyết định đày tất cả những tên tội phạm nguy hiểm của mình đi càng xa càng tốt. Vì vậy, chúng đã bị đưa lên tàu và chuyển đi vòng quanh thế giới đến một hòn đảo." },
      { "start": 26.0, "en": "This island was Australia. The main city was called Sydney.", "ipa": "/ðɪs ˈaɪlənd wɒz ɔːˈstreɪliə. ðə meɪn ˈsɪti wɒz kɔːld ˈsɪdni/", "vi": "Hòn đảo đó chính là Australia. Thành phố chính được gọi là Sydney." },
      { "start": 33.0, "en": "Hundreds of years later, Sydney is one of the most beautiful cities in the world. Millions of people live there today. It is famous for warm weather, beautiful beaches and an opera house.", "ipa": "/ˈhʌndrədz əv jɪərz ˈleɪtər, ˈsɪdni ɪz wʌn əv ðə moʊst ˈbjuːtɪfl ˈsɪtiz ɪn ðə wɜːrld. ˈmɪljənz əv ˈpiːpl lɪv ðɛər təˈdeɪ. ɪt ɪz ˈfeɪməs fɔːr wɔːrm ˈwɛðər, ˈbjuːtɪfl ˈbiːtʃɪz ænd ən ˈɒpərə haʊs/", "vi": "Hàng trăm năm sau, Sydney là một trong những thành phố đẹp nhất trên thế giới. Hàng triệu người sống ở đó ngày nay. Nó nổi tiếng với thời tiết ấm áp, những bãi biển tuyệt đẹp và một nhà hát ô-pê-ra." },
      { "start": 51.0, "en": "It is surrounded by parks, rivers and many beaches. Swimming is a favourite sport for people living in Sydney. Maybe one day, you will visit the city by the sea, Sydney.", "ipa": "/ɪt ɪz səˈraʊndɪd baɪ pɑːrks, ˈrɪvərz ænd ˈmɛni ˈbiːtʃɪz. ˈswɪmɪŋ ɪz ə ˈfeɪvərɪt spɔːrt fɔːr ˈpiːpl ˈlɪvɪŋ ɪn ˈsɪdni. ˈmeɪbi wʌn deɪ, juː wɪl ˈvɪzɪt ðə ˈsɪti baɪ ðə siː, ˈsɪdni/", "vi": "Nó được bao quanh bởi các công viên, sông ngòi và nhiều bãi biển. Bơi lội là môn thể thao yêu thích của những người sống ở Sydney. Có lẽ một ngày nào đó, bạn sẽ đến thăm thành phố bên bờ biển này, Sydney." }
    ]
  },
  {
    "day": 22,
    "title": "A Farmer and a Scientist",
    "image": "09 September/images/day_22.webp",
    "audio": "09 September/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "Everyone needs to eat. But what happens if there is not enough food? Jimmy Brown is only in Grade 3, but already he worries about this problem.", "ipa": "/ˈɛvriˌwʌn niːdz tuː iːt. bʌt wɒt ˈhæpənz ɪf ðɛər ɪz nɒt ɪˈnʌf fuːd? ˈdʒɪmi braʊn ɪz ˈoʊnli ɪn ɡreɪd θriː, bʌt ɔːlˈrɛdi hiː ˈwʌriz əˈbaʊt ðɪs ˈprɒbləm/", "vi": "Ai cũng cần phải ăn. Nhưng điều gì sẽ xảy ra nếu không có đủ thức ăn? Jimmy Brown mới học lớp 3, nhưng cậu đã sớm lo lắng về vấn đề này." },
      { "start": 16.0, "en": "Jimmy's dad told him about a great Chinese scientist named Yuan Longping.", "ipa": "/ˈdʒɪmiːz dæd toʊld hɪm əˈbaʊt ə ɡreɪt ˈtʃaɪˈniːz ˈsaɪəntɪst neɪmd ˈjuːən lɒŋˈpɪŋ/", "vi": "Bố của Jimmy đã kể cho cậu nghe về một nhà khoa học lớn người Trung Quốc tên là Viên Long Bình." },
      { "start": 23.0, "en": "'Mr. Yuan thought about this problem many years ago,' said Jimmy's dad. 'He wanted to help. So he dedicated his life to finding a solution.'", "ipa": "/ˈmɪstər ˈjuːən θɔːt əˈbaʊt ðɪs ˈprɒbləm ˈmɛni jɪərz əˈɡoʊ, sɛd ˈdʒɪmiːz dæd. hiː ˈwɒntɪd tuː hɛlp. soʊ hiː ˈdɛdɪkeɪtɪd hɪz laɪf tuː ˈfaɪndɪŋ ə səˈluːʃn/", "vi": "'Ông Viên đã nghĩ về vấn đề này từ nhiều năm trước,' bố của Jimmy nói. 'Ông muốn giúp đỡ. Vì vậy, ông đã cống hiến cả cuộc đời mình để tìm ra giải pháp.'" },
      { "start": 36.0, "en": "Mr. Yuan discovered a way to get rice plants to grow lots and lots of rice. He came up with a 'hybrid' rice plant. Now, China can feed many people with this special rice.", "ipa": "/ˈmɪstər ˈjuːən dɪsˈkʌvərd ə weɪ tuː ɡɛt raɪs plɑːnts tuː ɡroʊ lɒts ænd lɒts əv raɪs. hiː keɪm ʌp wɪð ə ˈhaɪbrɪd raɪs plɑːnt. naʊ, ˈtʃaɪnə kæn fiːd ˈmɛni ˈpiːpl wɪð ðɪs ˈspɛʃəl raɪs/", "vi": "Ông Viên đã phát ra cách giúp cây lúa trổ ra rất nhiều hạt gạo. Ông đã sáng tạo ra giống lúa 'lai'. Giờ đây, Trung Quốc có thể nuôi sống rất nhiều người nhờ loại gạo đặc biệt này." },
      { "start": 52.0, "en": "'So, if you really want to do something, you can. Just like Mr. Yuan, a farmer who is also a scientist,' said Jimmy's dad.", "ipa": "/soʊ, ɪf juː ˈrɪəli wɒnt tuː duː ˈsʌmθɪŋ, juː kæn. dʒʌst laɪk ˈmɪstər ˈjuːən, ə ˈfɑːrmər huː ɪz ˈɔːlsoʊ ə ˈsaɪəntɪst, sɛd ˈdʒɪmiːz dæd/", "vi": "'Vì vậy, nếu con thực sự muốn làm điều gì đó, con có thể làm được. Giống như ông Viên, một người nông dân đồng thời là một nhà khoa học,' bố của Jimmy nói." },
      { "start": 62.0, "en": "Jimmy was happy. When he grows up, he too will do something to help feed the people on this planet.", "ipa": "/ˈdʒɪmi wɒz ˈhæpi. wɛn hiː ɡroʊz ʌp, hiː tuː wɪl duː ˈsʌmθɪŋ tuː hɛlp fiːd ðə ˈpiːpl ɒn ðɪs ˈplænɪt/", "vi": "Jimmy rất vui. Khi lớn lên, cậu cũng sẽ làm điều gì đó để giúp nuôi sống những người trên hành tinh này." }
    ]
  },
  {
    "day": 23,
    "title": "When Teeth Become Weak",
    "image": "09 September/images/day_23.webp",
    "audio": "09 September/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "Bob likes food. Meat, vegetables, pizza and french fries are his favourites. He always says, 'I have good strong teeth. I can eat any food I want.'", "ipa": "/bɒb laɪks fuːd. miːt, ˈvɛdʒtəblz, ˈpiːtsə ænd frɛntʃ fraɪz ɑːr hɪz ˈfeɪvərɪts. hiː ˈɔːlweɪz sɛz, aɪ hæv ɡʊd strɔːŋ tiːθ. aɪ kæn iːt ˈɛni fuːd aɪ wɒnt/", "vi": "Bob rất thích đồ ăn. Thịt, rau củ, pizza và khoai tây chiên là những món ưa thích của cậu. Cậu luôn nói: 'Tớ có hàm răng chắc khỏe. Tớ có thể ăn bất kỳ món nào mình muốn.'" },
      { "start": 16.0, "en": "But one day, Bob had to go to the dentist to get braces. Two of his teeth were growing out of place.", "ipa": "/bʌt wʌn deɪ, bɒb hæd tuː ɡoʊ tuː ðə ˈdɛntɪst tuː ɡɛt ˈbreɪsɪz. tuː əv hɪz tiːθ wɜːr ˈɡroʊɪŋ aʊt əv pleɪs/", "vi": "Nhưng một hôm, Bob phải đến gặp nha sĩ để niềng răng. Hai chiếc răng của cậu đang mọc lệch vị trí." },
      { "start": 24.0, "en": "It took three hours to get it all done. Before he left, the dentist said, 'You may have trouble eating for the next few days. But don't worry, you will be back to normal in a week.'", "ipa": "/ɪt tʊk θriː ˈaʊərz tuː ɡɛt ɪt ɔːl dʌn. bɪˈfɔːr hiː lɛft, ðə ˈdɛntɪst sɛd, juː meɪ hæv ˈtrʌbl ˈiːtɪŋ fɔːr ðə nɛkst fjuː deɪz. bʌt doʊnt ˈwʌri, juː wɪl biː bæk tuː ˈnɔːrməl ɪn ə wiːk/", "vi": "Mất ba tiếng để hoàn tất mọi thứ. Trước khi cậu rời đi, nha sĩ dặn: 'Cháu có thể gặp khó khăn khi ăn trong vài ngày tới. Nhưng đừng lo, cháu sẽ trở lại bình thường sau một tuần.'" },
      { "start": 38.0, "en": "Bob looked in the mirror. He looked cool! He could barely wait to show his friends.", "ipa": "/bɒb lʊkt ɪn ðə ˈmɪrər. hiː lʊkt kuːl! hiː kʊd ˈbɛrli weɪt tuː shoʊ hɪz frɛndz/", "vi": "Bob nhìn vào gương. Trông cậu thật ngầu! Cậu suýt không thể đợi để khoe với bạn bè." },
      { "start": 44.0, "en": "But the next morning, Bob felt weird. His teeth felt so weak. It was like they lost their usual strength. He couldn't even chew a piece of bread.", "ipa": "/bʌt ðə nɛkst ˈmɔːrnɪŋ, bɒb fɛlt wɪrd. hɪz tiːθ fɛlt soʊ wiːk. ɪt wɒz laɪk ðeɪ lɒst ðɛər ˈuːʒuəl strɛŋθ. hiː ˈkʊdnt ˈiːvn tʃuː ə piːs əv brɛd/", "vi": "Nhưng sáng hôm sau, Bob cảm thấy lạ lùng. Răng cậu có vẻ rất yếu. Cứ như thể chúng đã mất đi độ chắc khỏe thường ngày. Cậu thậm chí không thể nhai nổi một miếng bánh mì." },
      { "start": 57.0, "en": "At lunch, while all his friends ate a variety of foods, Bob could only eat yogurt and drink milk. He felt like an old man. 'It's not cool at all,' said Bob to his friends. 'I hate these braces!' Bob groaned. 'When I get better, I am going to have a feast and eat all my favourite foods!'", "ipa": "/æt lʌntʃ, waɪl ɔːl hɪz frɛndz eɪt ə vəˈraɪəti əv fuːdz, bɒb kʊd ˈoʊnli iːt ˈjoʊɡərt ænd drɪŋk mɪlk. hiː fɛlt laɪk ən oʊld mæn. ɪts nɒt kuːl æt ɔːl, sɛd bɒb tuː hɪz frɛndz. aɪ heɪt ðiːz ˈbreɪsɪz!, bɒb ɡroʊnd. wɛn aɪ ɡɛt ˈbɛtər, aɪ æm ˈɡoʊɪŋ tuː hæv ə fiːst ænd iːt ɔːl maɪ ˈfeɪvərɪt fuːdz!/", "vi": "Vào bữa trưa, trong khi tất cả bạn bè ăn đủ loại thức ăn, Bob chỉ có thể ăn sữa chua và uống sữa. Cậu cảm thấy mình giống như một ông già. 'Chẳng ngầu chút nào cả,' Bob nói với các bạn. 'Tớ ghét niềng răng quá!' Bob rên rỉ. 'Khi nào khỏe lại, tớ sẽ làm một bữa tiệc thật linh đình và ăn tất cả những món ăn yêu thích!'" }
    ]
  },
  {
    "day": 24,
    "title": "Wind and Sun",
    "image": "09 September/images/day_24.webp",
    "audio": "09 September/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "In school, we are learning about the environment. Yesterday, we talked about solar energy. Solar energy is when you catch the rays of the sun and use them to power homes.", "ipa": "/ɪn skuːl, wiː ɑːr ˈlɜːrnɪŋ əˈbaʊt ði ɪnˈvaɪrənmənt. ˈjɛstərdeɪ, wiː tɔːkt əˈbaʊt ˈsoʊlər ˈɛnərdʒi. ˈsoʊlər ˈɛnərdʒi ɪz wɛn juː kætʃ ðə reɪz əv ðə sʌn ænd juːz ðɛm tuː ˈpaʊər hoʊmz/", "vi": "Ở trường, chúng tôi đang học về môi trường. Hôm qua, chúng tôi đã nói về năng lượng mặt trời. Năng lượng mặt trời là khi bạn thu bắt các tia nắng mặt trời và sử dụng chúng để cung cấp điện cho các ngôi nhà." },
      { "start": 21.0, "en": "We also learned about wind energy. This is when big windmills catch the wind and turn it into electricity.", "ipa": "/wiː ˈɔːlsoʊ lɜːrnd əˈbaʊt wɪnd ˈɛnərdʒi. ðɪs ɪz wɛn bɪɡ ˈwɪndˌmɪlz kætʃ ðə wɪnd ænd tɜːrn ɪt ˈɪntuː ɪlɛkˈtrɪsɪti/", "vi": "Chúng tôi cũng học về năng lượng gió. Đây là lúc những chiếc cối xay gió lớn đón gió và biến nó thành điện năng." },
      { "start": 29.0, "en": "Sure, wind and solar power are really good. But it takes a lot of money to set up a wind mill or a sun collector.", "ipa": "/ʃʊr, wɪnd ænd ˈsoʊlər ˈpaʊər ɑːr ˈriːəli ɡʊd. bʌt ɪt teɪks ə lɒt əv ˈmʌni tuː sɛt ʌp ə wɪnd mɪl ɔːr ə sʌn kəˈlɛktər/", "vi": "Chắc chắn rồi, năng lượng gió và năng lượng mặt trời thực sự rất tốt. Nhưng tốn rất nhiều tiền để lắp đặt một chiếc cối xay gió hoặc một thiết bị thu năng lượng mặt trời." },
      { "start": 40.0, "en": "One day, I told my grandma about all of this. She smiled. I know that when Grandma smiles, she has a plan.", "ipa": "/wʌn deɪ, aɪ toʊld maɪ ˈɡrændˌmɑː əˈbaʊt ɔːl əv ðɪs. ʃiː smaɪld. aɪ noʊ ðæt wɛn ˈɡrændˌmɑː smaɪld, ʃiː hæz ə plæn/", "vi": "Một ngày nọ, tôi kể với bà về tất cả những điều này. Bà mỉm cười. Tôi biết rằng khi bà mỉm cười, bà đang có một kế hoạch." },
      { "start": 51.0, "en": "'When I was a girl, we had a great sun-and wind-powered clothes dryer,' she said. 'All you need is a good rope and two places to attach it to. Hang the clothes, and let the sun and wind dry them. If you want, I can help you make a clothes line.'", "ipa": "/wɛn aɪ wɒz ə ɡɜːrl, wiː hæd ə ɡreɪt sʌn-ænd wɪnd-ˈpaʊərd cloʊðz ˈdraɪər, ʃiː sɛd. ɔːl juː niːd ɪz ə ɡʊd roʊp ænd tuː pleɪsɪz tuː əˈtætʃ ɪt tuː. hæŋ ðə cloʊðz, ænd lɛt ðə sʌn ænd wɪnd draɪ ðɛm. ɪf juː wɒnt, aɪ kæn hɛlp juː meɪk ə cloʊðz laɪn/", "vi": "'Khi còn là một cô bé, chúng tôi đã có một chiếc máy sấy quần áo chạy bằng năng lượng mặt trời và gió rất tuyệt vời,' bà nói. 'Tất cả những gì con cần là một sợi dây thừng tốt và hai nơi để buộc nó vào. Treo quần áo lên, và để mặt trời và gió làm khô chúng. Nếu con muốn, bà có thể giúp con làm một sợi dây phơi quần áo.'" },
      { "start": 71.0, "en": "Cool! I can't wait to tell my teacher about the new clothes dryer that we put in our house. And it all cost less than 15 dollars!", "ipa": "/kuːl! aɪ kænt weɪt tuː tɛl maɪ ˈtiːtʃər əˈbaʊt ðə njuː cloʊðz ˈdraɪər ðæt wiː pʊt ɪn ˈaʊər haʊs. ænd ɪt ɔːl kɒst lɛs ðæn ˈfɪftiːn ˈdɑːlərz/", "vi": "Thật tuyệt! Tôi nóng lòng muốn kể cho cô giáo nghe về chiếc máy sấy quần áo mới mà chúng tôi đã lắp ở nhà. Và tất cả chỉ tốn chưa đầy 15 đô la!" }
    ]
  },
  {
    "day": 25,
    "title": "The Little Things",
    "image": "09 September/images/day_25.webp",
    "audio": "09 September/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "A young fish loved collecting pebbles -those little shiny stones at the bottom of the ocean. He spent all of his time looking for them.", "ipa": "/ə jʌŋ fɪʃ lʌvd kəˈlɛktɪŋ ˈpɛblz -ðoʊz ˈlɪtl ˈʃaɪni stoʊnz æt ðə ˈbɒtəm əv ði ˈoʊʃn. hiː spɛnt ɔːl əv hɪz taɪm ˈlʊkɪŋ fɔːr ðɛm/", "vi": "Một chú cá nhỏ rất thích sưu tầm những viên sỏi - những viên đá lấp lánh nhỏ xíu ở dưới đáy đại dương. Chú dành toàn bộ thời gian của mình để tìm kiếm chúng." },
      { "start": 16.0, "en": "One day, an old fish said to him, 'You cannot spend your entire day looking for little pebbles. There is a whole world out there for you to learn about!'", "ipa": "/wʌn deɪ, ən oʊld fɪʃ sɛd tuː hɪm, juː ˈkænɒt spɛnd jɔːr ɪnˈtaɪər deɪ ˈlʊkɪŋ fɔːr ˈlɪtl ˈpɛblz. ðɛər ɪz ə hoʊl wɜːrld aʊt ðɛər fɔːr juː tuː lɜːrn əˈbaʊt!/", "vi": "Một ngày nọ, một con cá lớn tuổi đã nói với chú: 'Cháu không thể dành toàn bộ cả ngày để tìm những viên sỏi nhỏ được. Có cả một thế giới rộng lớn ngoài kia đang chờ cháu tìm hiểu đấy!'" },
      { "start": 28.0, "en": "But the young fish didn't listen.", "ipa": "/bʌt ðə jʌŋ fɪʃ ˈdɪdnt ˈlɪsn/", "vi": "Nhưng chú cá nhỏ đã không nghe theo." },
      { "start": 32.0, "en": "Early one morning, while the other fish were still sleeping, the young fish went for a swim. He came upon a pile of pebbles.", "ipa": "/ˈɜːrli wʌn ˈmɔːrnɪŋ, waɪl ði ˈʌðər fɪʃ wɜːr stɪl ˈsliːpɪŋ, ðə jʌŋ fɪʃ wɛnt fɔːr ə swɪm. hiː keɪm əˈpɒn ə paɪl əv ˈpɛblz/", "vi": "Sớm một ngày nọ, trong khi những con cá khác còn đang ngủ, chú cá nhỏ đã bơi đi. Chú tình cờ thấy một đống sỏi." },
      { "start": 42.0, "en": "Excited about his find, he started bringing the pebbles back to his home, one by one.", "ipa": "/ɪkˈsaɪtɪd əˈbaʊt hɪz faɪnd, hiː ˈstɑːrtɪd ˈbrɪŋɪŋ ðə ˈpɛblz bæk tuː hɪz hoʊm, wʌn baɪ wʌn/", "vi": "Vui mừng vì tìm được thứ mình thích, chú bắt đầu mang từng viên sỏi về nhà của mình, từng viên một." },
      { "start": 50.0, "en": "Just as he was making his last trip, he saw a shadow. It was a big, ugly lion fish-the scariest fish in the sea.", "ipa": "/dʒʌst æz hiː wɒz ˈmeɪkɪŋ hɪz lɑːst trɪp, hiː sɔː ə ˈʃædoʊ. ɪt wɒz ə bɪɡ, ˈʌɡli ˈlaɪən fɪʃ-ðə ˈskɛriɪst fɪʃ ɪn ðə siː/", "vi": "Ngay khi đang thực hiện chuyến đi cuối cùng, chú nhìn thấy một cái bóng. Đó là một con cá sư tử to lớn, xấu xí - loài cá đáng sợ nhất dưới biển." },
      { "start": 62.0, "en": "Suddenly, the lion fish started chasing the young fish. Very quickly, the young fish realized that the only way he could escape was to drop the pebble, and swim away as fast as he could.", "ipa": "/ˈsʌdənli, ðə ˈlaɪən fɪʃ ˈstɑːrtɪd ˈtʃeɪsɪŋ ðə jʌŋ fɪʃ. ˈvɛri ˈkwɪkli, ðə jʌŋ fɪʃ ˈriːəlaɪzd ðæt ðə ˈoʊnli weɪ hiː kʊd ɪˈskeɪp wɒz tuː drɒp ðə ˈpɛbl, ænd swɪm əˈweɪ æz fɑːst æz hiː kʊd/", "vi": "Đột nhiên, cá sư tử bắt đầu đuổi theo chú cá nhỏ. Rất nhanh chóng, chú cá nhỏ nhận ra rằng cách duy nhất để trốn thoát là thả viên sỏi xuống, và bơi đi nhanh nhất có thể." },
      { "start": 78.0, "en": "From then on, he always remembered what the wise fish had told him: Too many little things may make you lose sight of the big picture.", "ipa": "/frɒm ðɛn ɒn, hiː ˈɔːlweɪz rɪˈmɛmbərd wɒt ðə waɪz fɪʃ hæd toʊld hɪm: tuː ˈmɛni ˈlɪtl θɪŋz meɪ meɪk juː luːz saɪt əv ðə bɪɡ ˈpɪktʃər/", "vi": "Từ đó trở đi, chú luôn ghi nhớ những gì con cá khôn ngoan đã nói với mình: Quá nhiều điều nhỏ nhặt có thể khiến bạn quên mất bức tranh lớn (tầm nhìn bao quát)." }
    ]
  },
  {
    "day": 26,
    "title": "Turtle and Mr. Leopard (I)",
    "image": "09 September/images/day_26.webp",
    "audio": "09 September/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "Long ago, Turtle got sick. He needed to go to the forest to find some plants. On his way, Turtle stopped to see if his neighbour, Mr. Leopard, could give him a ride on his back.", "ipa": "/lɒŋ əˈɡoʊ, ˈtɜːrtl ɡɒt sɪk. hiː ˈniːdɪd tuː ɡoʊ tuː ðə ˈfɔːrɪst tuː faɪnd sʌm plɑːnts. ɒn hɪz weɪ, ˈtɜːrtl stɒpt tuː siː ɪf hɪz ˈneɪbər, ˈmɪstər ˈlɛpərd, kʊd ɡɪv hɪm ə raɪd ɒn hɪz bæk/", "vi": "Ngày xửa ngày xưa, Rùa bị ốm. Chú cần vào rừng để tìm một số loại cây thuốc. Trên đường đi, Rùa ghé qua xem người hàng xóm của mình, bác Báo, có thể cho mình đi nhờ trên lưng không." },
      { "start": 21.0, "en": "But, Mr. Leopard was not home. His wife answered the door. Turtle said, 'That is too bad. I was hoping I could ride on his back to the forest.'", "ipa": "/bʌt, ˈmɪstər ˈlɛpərd wɒz nɒt hoʊm. hɪz waɪf ˈænsərd ðə dɔːr. ˈtɜːrtl sɛd, ðæt ɪz tuː bæd. aɪ wɒz ˈhoʊpɪŋ aɪ kʊd raɪd ɒn hɪz bæk tuː ðə ˈfɔːrɪst/", "vi": "Nhưng bác Báo không có nhà. Vợ bác ra mở cửa. Rùa nói: 'Tiếc quá nhỉ. Tớ cứ hy vọng được đi nhờ lưng bác ấy vào rừng.'" },
      { "start": 35.0, "en": "Upon hearing this, Mrs. Leopard was not happy with Turtle. When Mr. Leopard came home, Mrs. Leopard told him what had happened.", "ipa": "/əˈpɒn ˈhɪərɪŋ ðɪs, ˈmɪsɪz ˈlɛpərd wɒz nɒt ˈhæpi wɪð ˈtɜːrtl. wɛn ˈmɪstər ˈlɛpərd keɪm hoʊm, ˈmɪsɪz ˈlɛpərd toʊld hɪm wɒt hæd ˈhæpənd/", "vi": "Nghe thấy vậy, cô Báo không vui với Rùa. Khi bác Báo về nhà, cô Báo đã kể lại chuyện đó cho bác nghe." },
      { "start": 48.0, "en": "Mr. Leopard was really mad too. He ran directly to Turtle's house and said, 'You think you can ride me like a horse. This will never happen! I am a leopard-fast and strong.'", "ipa": "/ˈmɪstər ˈlɛpərd wɒz ˈriːəli mæd tuː. hiː ræn dəˈrɛktli tuː ˈtɜːrtlz haʊs ænd sɛd, juː θɪŋk juː kæn raɪd miː laɪk ə hɔːrs. ðɪs wɪl ˈnɛvər ˈhæpən! aɪ æm ə ˈlɛpərd-fɑːst ænd strɔːŋ/", "vi": "Bác Báo cũng thực sự rất tức giận. Bác chạy thẳng đến nhà Rùa và nói: 'Cậu nghĩ cậu có thể cưỡi tôi như ngựa à. Điều đó không bao giờ xảy ra đâu! Tôi là một con báo - nhanh nhẹn và mạnh mẽ.'" },
      { "start": 65.0, "en": "Turtle said, 'I did not say this.' But Leopard did not believe him.", "ipa": "/ˈtɜːrtl sɛd, aɪ dɪd nɒt seɪ ðɪs. bʌt ˈlɛpərd dɪd nɒt bɪˈliːv hɪm/", "vi": "Rùa nói: 'Tớ không hề nói thế.' Nhưng Báo không tin chú." },
      { "start": 71.0, "en": "'Let's go and see my wife.' he said. 'She will prove that you did indeed say this.'", "ipa": "/lɛts ɡoʊ ænd siː maɪ waɪf., hiː sɛd. ʃiː wɪl pruːv ðæt juː dɪd ɪnˈdiːd seɪ ðɪs/", "vi": "'Đi gặp vợ tôi nào,' bác ấy nói. 'Cô ấy sẽ chứng minh rằng đúng là cậu đã nói thế.'" },
      { "start": 78.0, "en": "Turtle was a cunning animal. He said, 'I am too sick to walk that far. But, if you give me a ride, I will surely go.'", "ipa": "/ˈtɜːrtl wɒz ə ˈkʌnɪŋ ˈænɪml. hiː sɛd, aɪ æm tuː sɪk tuː wɔːk ðæt fɑːr. bʌt, ɪf juː ɡɪv miː ə raɪd, aɪ wɪl ˈʃʊərli ɡoʊ/", "vi": "Rùa là một con vật xảo quyệt. Chú nói: 'Tớ quá ốm để đi bộ xa thế. Nhưng, nếu bác cho tớ đi nhờ, tớ chắc chắn sẽ đi.'" },
      { "start": 91.0, "en": "Leopard agreed. And so, they prepared to leave.", "ipa": "/ˈlɛpərd əˈɡriːd. ænd soʊ, ðeɪ prɪˈpɛrd tuː liːv/", "vi": "Báo đồng ý. Và thế là, họ chuẩn bị lên đường." }
    ]
  },
  {
    "day": 27,
    "title": "Turtle and Mr. Leopard (II)",
    "image": "09 September/images/day_27.webp",
    "audio": "09 September/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "When Turtle got on Leopard's back, he cried, 'Oh, I am so weak! Please let me put a small rope in your mouth so that I will not fall off and hurt myself.' Leopard agreed for he could see no harm in this.", "ipa": "/wɛn ˈtɜːrtl ɡɒt ɒn ˈlɛpərdz bæk, hiː kraɪd, oʊ, aɪ æm soʊ wiːk! pliːz lɛt miː pʊt ə smɔːl roʊp ɪn jɔːr maʊθ soʊ ðæt aɪ wɪl nɒt fɔːl ɔːf ænd hɜːrt maɪˈsɛlf. ˈlɛpərd əˈɡriːd fɔːr hiː kʊd siː noʊ hɑːrm ɪn ðɪs/", "vi": "Khi Rùa trèo lên lưng Báo, chú kêu lên: 'Ôi, tớ yếu quá! Xin hãy để tớ ngậm một sợi dây thừng nhỏ trong miệng bác để tớ không bị ngã và làm tổn thương bản thân.' Báo đồng ý vì thấy việc này chẳng có hại gì." },
      { "start": 21.0, "en": "Then, Turtle said, 'May I have a small stick to help me keep the insects from biting me? Please allow me this one small thing.' Again, Leopard agreed.", "ipa": "/ðɛn, ˈtɜːrtl sɛd, meɪ aɪ hæv ə smɔːl stɪk tuː hɛlp miː kiːp ði ˈɪnsɛkts frɒm ˈbaɪtɪŋ miː? pliːz əˈlaʊ miː ðɪs wʌn smɔːl θɪŋ. əˈɡɛn, ˈlɛpərd əˈɡriːd/", "vi": "Sau đó, Rùa lại nói: 'Tớ có thể xin một chiếc gậy nhỏ để xua đuổi côn trùng cắn tớ không? Xin bác hãy cho phép tớ điều nhỏ nhặt này.' Lại một lần nữa, Báo đồng ý." },
      { "start": 36.0, "en": "And in this way, they began their trip to Leopard's home to check with Mrs. Leopard about what was or was not said.", "ipa": "/ænd ɪn ðɪs weɪ, ðeɪ bɪˈɡæn ðɛər trɪp tuː ˈlɛpərdz hoʊm tuː tʃɛk wɪð ˈmɪsɪz ˈlɛpərd əˈbaʊt wɒt wɒz ɔːr wɒz nɒt sɛd/", "vi": "Và cứ thế, họ bắt đầu chuyến đi đến nhà Báo để hỏi cô Báo về những gì đã được nói hay chưa được nói." },
      { "start": 48.0, "en": "Soon, they arrived. Mrs. Leopard saw her husband coming through the trees with Turtle on his back. Turtle had a rope in Leopard's mouth and was hitting him with the small stick.", "ipa": "/suːn, ðeɪ əˈraɪvd. ˈmɪsɪz ˈlɛpərd sɔː hɜːr ˈhʌzbənd ˈkʌmɪŋ θruː ðə triːz wɪð ˈtɜːrtl ɒn hɪz bæk. ˈtɜːrtl hæd ə roʊp ɪn ˈlɛpərdz maʊθ ænd wɒz ˈhɪtɪŋ hɪm wɪð ðə smɔːl stɪk/", "vi": "Chẳng mấy chốc, họ đã đến nơi. Cô Báo nhìn thấy chồng mình đi xuyên qua hàng cây với Rùa trên lưng. Rùa đang cầm dây thừng trong miệng Báo và dùng chiếc gậy nhỏ đánh vào bác ấy." },
      { "start": 64.0, "en": "Mrs. Leopard cried, 'See. It is just as I said. Turtle is riding you as if you were a horse!'", "ipa": "/ˈmɪsɪz ˈlɛpərd kraɪd, siː. ɪt ɪz dʒʌst æz aɪ sɛd. ˈtɜːrtl ɪz ˈraɪdɪŋ juː æz ɪf juː wɜːr a hɔːrs!/", "vi": "Cô Báo la lên: 'Thấy chưa. Đúng như em đã nói. Rùa đang cưỡi anh như thể anh là con ngựa vậy!'" },
      { "start": 74.0, "en": "Leopard was very mad. Turtle had made a fool of him. So, he threw Turtle to the ground and beat him with the stick.", "ipa": "/ˈlɛpərd wɒz ˈvɛri mæd. ˈtɜːrtl hæd meɪd ə fuːl əv hɪm. soʊ, hiː θruː ˈtɜːrtl tuː ðə ɡraʊnd ænd biːt hɪm wɪð ðə stɪk/", "vi": "Báo vô cùng tức giận. Rùa đã biến bác thành kẻ ngốc. Vì vậy, bác đã ném Rùa xuống đất và dùng gậy đánh chú ta." },
      { "start": 84.0, "en": "And even today, if you look closely at a turtle's shell, you can still see the marks from the beating.", "ipa": "/ænd ˈiːvn təˈdeɪ, ɪf juː lʊk ˈklʊsli æt ə ˈtɜːrtlz ʃɛl, juː kæn stɪl siː ðə mɑːrks frɒm ðə ˈbiːtɪŋ/", "vi": "Và ngay cả ngày nay, nếu bạn nhìn kỹ vào mai của một chú rùa, bạn vẫn có thể thấy những vết tích từ trận đòn roi đó." }
    ]
  },
  {
    "day": 28,
    "title": "Burning the Candle at Both Ends",
    "image": "09 September/images/day_28.webp",
    "audio": "09 September/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "My dad is very busy with his work. He does not sleep enough. On the weekends, he juggles work, family, our school sports and more. He feels tired all the time.", "ipa": "/maɪ dæd ɪz ˈvɛri ˈbɪzi wɪð hɪz wɜːrk. hiː dʌz nɒt sliːp ɪˈnʌf. ɒn ðə ˈwiːkˌɛndz, hiː ˈdʒʌɡlz wɜːrk, ˈfæməli, ˈaʊər skuːl spɔːrts ænd mɔːr. hiː fiːlz ˈtaɪərd ɔːl ðə taɪm/", "vi": "Bố tôi rất bận rộn với công việc của mình. Ông ngủ không đủ giấc. Vào cuối tuần, ông phải xoay sở với công việc, gia đình, thể thao trường học của chúng tôi và nhiều thứ khác. Ông cảm thấy mệt mỏi suốt thời gian qua." },
      { "start": 21.0, "en": "Finally, he had to go to see a doctor. The doctor said to my dad, 'You have been burning the candle at both ends.'", "ipa": "/ˈfaɪnəli, hiː hæd tuː ɡoʊ tuː siː ə ˈdɒktər. ðə ˈdɒktər sɛd tuː maɪ dæd, juː hæv biːn ˈbɜːrnɪŋ ðə ˈkændl æt boʊθ ɛndz/", "vi": "Cuối cùng, ông phải đi gặp bác sĩ. Bác sĩ nói với bố tôi rằng: 'Anh đang vắt kiệt sức lực của mình rồi đấy.'" },
      { "start": 32.0, "en": "'What do you mean?' Dad asked. 'Well, what would happen if you lit both ends of a candle at the same time?' said the doctor.", "ipa": "/wɒt duː juː miːn?, dæd ɑːskt. wɛl, wɒt wʊd ˈhæpən ɪf juː lɪt boʊθ ɛndz əv ə ˈkændl æt ðə seɪm taɪm?, sɛd ðə ˈdɒktər/", "vi": "'Ý bác sĩ là sao ạ?' Bố hỏi. 'Chà, điều gì sẽ xảy ra nếu bạn châm cả hai đầu của một cây nến cùng một lúc?' bác sĩ nói." },
      { "start": 44.0, "en": "'The candle would burn out very quickly,' my dad answered.", "ipa": "/ðə ˈkændl wʊd bɜːrn aʊt ˈvɛri ˈkwɪkli, maɪ dæd ˈɑːnsərd/", "vi": "'Cây nến sẽ cháy hết rất nhanh,' bố tôi trả lời." },
      { "start": 50.0, "en": "'Right,' the doctor nodded. 'This is what is happening to you. You are being burned out.' She was right. Dad was too tired.", "ipa": "/raɪt, ðə ˈdɒktər ˈnɒdɪd. ðɪs ɪz wɒt ɪz ˈhæpɪŋ tuː juː. juː ɑːr ˈbiːɪŋ bɜːrnd aʊt. ʃiː wɒz raɪt. dæd wɒz tuː ˈtaɪərd/", "vi": "'Đúng vậy,' bác sĩ gật đầu. 'Đây là những gì đang xảy ra với anh. Anh đang bị kiệt sức.' Bà ấy đã đúng. Bố đã quá mệt mỏi." },
      { "start": 62.0, "en": "The doctor told my dad to slow down. 'Do less every day,' she said. 'There is a time for work, a time for fun, and a time to blow out the candle!'", "ipa": "/ðə ˈdɒktər toʊld maɪ dæd tuː sloʊ daʊn. duː lɛs ˈɛvri deɪ, ʃiː sɛd. ðɛər ɪz ə taɪm fɔːr wɜːrk, ə taɪm fɔːr fʌn, ænd ə taɪm tuː bloʊ aʊt ðə ˈkændl!/", "vi": "Bác sĩ bảo bố tôi hãy sống chậm lại. 'Làm ít đi mỗi ngày,' bà nói. 'Có thời gian dành cho công việc, thời gian để vui chơi, và thời gian để thổi tắt nến đi!'" }
    ]
  },
  {
    "day": 29,
    "title": "Plant A Seed",
    "image": "09 September/images/day_29.webp",
    "audio": "09 September/audio/Track29.mp3",
    "sentences": [
      { "start": 4.8, "en": "We all know what plants are. You may have one in a glass jar on your desk. Or, you may have a flower in your garden.", "ipa": "/wiː ɔːl noʊ wɒt plɑːnts ɑːr. juː meɪ hæv wʌn ɪn ə ɡlɑːs dʒɑːr ɒn jɔːr dɛsk. ɔːr, juː meɪ hæv ə ˈflaʊər ɪn jɔːr ˈɡɑːrdn/", "vi": "Chúng ta đều biết thực vật là gì. Bạn có thể có một cây trong một lọ thủy tinh trên bàn làm việc của mình. Hoặc, bạn có thể có một bông hoa trong khu vườn của mình." },
      { "start": 14.0, "en": "A tree is really just a plant that grows every year and has branches!", "ipa": "/ə triː ɪz ˈriːəli dʒʌst ə plɑːnt ðæt ɡroʊz ˈɛvri jɪər ænd hæz ˈbræntʃɪz/", "vi": "Một cái cây thực chất chỉ là một loài thực vật phát triển mỗi năm và có cành!" },
      { "start": 21.0, "en": "One thing we know is that people would not be here on earth without plants.", "ipa": "/wʌn θɪŋ wiː noʊ ɪz ðæt ˈpiːpl wʊd nɒt biː hɪər ɒn ɜːrθ wɪˈðaʊt plɑːnts/", "vi": "Một điều chúng ta biết là con người sẽ không thể ở đây trên Trái Đất nếu không có thực vật." },
      { "start": 28.0, "en": "Plants are our medicine, our furniture and our clothes. Your cotton shirt comes from plants and trees.", "ipa": "/plɑːnts ɑːr ˈaʊər ˈmɛdɪsn, ˈaʊər ˈfɜːrnɪtʃər ænd ˈaʊər cloʊðz. jɔːr ˈkɑːtn ʃɜːrt kʌmz frɒm plɑːnts ænd triːz/", "vi": "Thực vật là thuốc men, đồ nội thất và quần áo của chúng ta. Áo sơ mi cotton của bạn đến từ thực vật và cây xanh." },
      { "start": 37.0, "en": "Your lunch is made of rice, corn or wheat. How about your salad? It's all made of plants.", "ipa": "/jɔːr lʌntʃ ɪz meɪd əv raɪs, kɔːrn ɔːr wiːt. haʊ əˈbaʊt jɔːr ˈsæləd? ɪts ɔːl meɪd əv plɑːnts/", "vi": "Bữa trưa của bạn được làm từ gạo, ngô hoặc lúa mì. Còn món salad của bạn thì sao? Tất cả đều được làm từ thực vật." },
      { "start": 47.0, "en": "My baseball bat, my pencil, my paper, the chair I am sitting on-all these things came from amazing little plants.", "ipa": "/maɪ ˈbeɪsˌbɔːl bæt, maɪ ˈpɛnsl, maɪ ˈpeɪpər, ðə tʃɛər aɪ æm ˈsɪtɪŋ ɒn-ɔːl ðiːz θɪŋz keɪm frɒm əˈmeɪzɪŋ ˈlɪtl plɑːnts/", "vi": "Cây gậy bóng chày của tôi, chiếc bút chì của tôi, tờ giấy của tôi, cái ghế tôi đang ngồi - tất cả những thứ này đều đến từ những loài thực vật nhỏ bé tuyệt vời." },
      { "start": 59.0, "en": "Did I say little? Of course, not all plants are little. Did you know that some trees live several thousands of years and grow to be 115 metres tall?", "ipa": "/dɪd aɪ seɪ ˈlɪtl? əv kɔːrs, nɒt ɔːl plɑːnts ɑːr ˈlɪtl. dɪd juː noʊ ðæt sʌm triːz lɪv ˈsɛvrəl ˈθaʊzndz əv jɪərz ænd ɡroʊ tuː biː wʌn ˈhʌndrəd fɪftiːn ˈmiːtərz tɔːl?/", "vi": "Tôi có nói là nhỏ không? Tất nhiên, không phải tất cả thực vật đều nhỏ. Bạn có biết rằng một số loài cây sống tới vài nghìn năm và phát triển cao tới 115 mét không?" },
      { "start": 72.0, "en": "That's like a 35-storey apartment building! And it started out as a little seed! Plants have taken care of us for thousands of years and hopefully will continue to do so for a long, long time!", "ipa": "/ðæts laɪk ə ˈθɜːrti-faɪv-ˈstɔːri əˈpɑːrtmənt ˈbɪldɪŋ! ænd ɪt ˈstɑːrtɪd aʊt æz ə ˈlɪtl siːd! plɑːnts hæv ˈteɪkən kɛr əv ʌs fɔːr ˈθaʊzndz əv jɪərz ænd ˈhoʊpfəli wɪl kənˈtɪnyuː tuː duː soʊ fɔːr ə lɒŋ, lɒŋ taɪm!/", "vi": "Điều đó giống như một tòa nhà chung cư 35 tầng! Và nó bắt đầu chỉ từ một hạt giống nhỏ! Thực vật đã chăm sóc chúng ta trong hàng ngàn năm và hy vọng sẽ tiếp tục làm như vậy trong một thời gian rất, rất dài!" },
      { "start": 91.0, "en": "So take care of your plants and trees. Take care of yourself and plant a seed.", "ipa": "/soʊ teɪk kɛər əv jɔːr plɑːnts ænd triːz. teɪk kɛər əv jɔːrˈsɛlf ænd plɑːnt ə siːd/", "vi": "Vì vậy, hãy chăm sóc cây cối và thực vật của bạn. Hãy chăm sóc bản thân mình và hãy gieo một hạt mầm nhé." }
    ]
  },
  {
    "day": 30,
    "title": "Soaring Through the Sky",
    "image": "09 September/images/day_30.webp",
    "audio": "09 September/audio/Track30.mp3",
    "sentences": [
      { "start": 4.8, "en": "We all have heroes. Most of my friends' heroes are big and strong hockey or basketball players. But my hero is not like that.", "ipa": "/wiː ɔːl hæv ˈhɪroʊz. moʊst əv maɪ frɛndz ˈhɪroʊz ɑːr bɪɡ ænd strɔːŋ ˈhɑːki ɔːr ˈbæskɪtˌbɔːl ˈpleɪərz. bʌt maɪ ˈhɪroʊ ɪz nɒt laɪk ðæt/", "vi": "Chúng ta ai cũng có những người hùng. Phần lớn những người hùng của bạn tôi là các vận động viên khúc côn cầu hoặc bóng rổ to lớn và mạnh mẽ. Nhưng người hùng của tôi không giống như thế." },
      { "start": 16.0, "en": "My hero has spent most of his life in a wheelchair. He cannot speak. He cannot move his arms. He needs a special computer to speak. The computer helps him pick out letters on the screen. This is how he spells words.", "ipa": "/maɪ ˈhɪroʊ hæz spɛnt moʊst əv hɪz laɪf ɪn ə ˈwiːlˌtʃɛər. hiː ˈkænɒt spiːk. hiː ˈkænɒt muːv hɪz ɑːrmz. hiː niːdz ə ˈspɛʃəl kəmˈpjuːtər tuː spiːk. ðə kəmˈpjuːtər hɛlps hɪm pɪk aʊt ˈlɛtərz ɒn ðə skriːn. ðɪs ɪz haʊ hiː spɛlz wɜːrdz/", "vi": "Người hùng của tôi đã dành phần lớn cuộc đời mình trên chiếc xe lăn. Ông không thể nói. Ông không thể cử động tay. Ông cần một chiếc máy tính đặc biệt để nói chuyện. Chiếc máy tính giúp ông chọn ra các chữ cái trên màn hình. Đây là cách ông đánh vần các từ." },
      { "start": 36.0, "en": "This is how he lives every day of his life. You would think this would keep him from doing anything. But it hasn't. If you were to ask him, he would tell you that he doesn't live in a wheelchair. He lives in his mind. And in his mind, he soars through the sky.", "ipa": "/ðɪs ɪz haʊ hiː lɪvz ˈɛvri deɪ əv hɪz laɪf. juː wʊd θɪŋk ðɪs wʊd kiːp hɪm frɒm ˈduːɪŋ ˈɛniˌθɪŋ. bʌt ɪt ˈhæznt. ɪf juː wɜːr tuː ɑːsk hɪm, hiː wʊd tɛl juː ðæt hiː ˈdʌznt lɪv ɪn ə ˈwiːlˌtʃɛər. hiː lɪvz ɪn hɪz maɪnd. ænd ɪn hɪz maɪnd, hiː sɔːrz θruː ðə skaɪ/", "vi": "Đây là cách ông sống mỗi ngày trong đời mình. Bạn sẽ nghĩ điều này ngăn cản ông làm bất cứ điều gì. Nhưng không phải vậy. Nếu bạn hỏi ông, ông sẽ nói với bạn rằng ông không sống trên xe lăn. Ông sống trong tâm trí mình. Và trong tâm trí, ông bay vút qua bầu trời." },
      { "start": 59.0, "en": "What does he love to do? He loves to think about math and the universe. People call him one of the smartest people in the world.", "ipa": "/wɒt dʌz hiː lʌv tuː duː? hiː lʌvz tuː θɪŋk əˈbaʊt mæθ ænd ðə ˈjuːnɪˌvɜːrs. ˈpiːpl kɔːld hɪm wʌn əv ðə ˈsmɑːrtɪst ˈpiːpl ɪn ðə wɜːrld/", "vi": "Ông thích làm gì? Ông thích suy nghĩ về toán học và vũ trụ. Mọi người gọi ông là một trong những người thông minh nhất trên thế giới." },
      { "start": 71.0, "en": "People all over the world look up to this tiny man, who cannot speak with words. Instead, he speaks with ideas. His name is Stephen Hawking.", "ipa": "/ˈpiːpl ɔːl ˈoʊvər ðə wɜːrld lʊk ʌp tuː ðɪs ˈtaɪni mæn, huː ˈkænɒt spiːk wɪð wɜːrdz. ɪnˈstɛd, hiː spiːks wɪð aɪˈdiːəz. hɪz neɪm ɪz ˈstiːvən ˈhɔːkɪŋ/", "vi": "Mọi người trên khắp thế giới ngưỡng mộ người đàn ông nhỏ bé này, người không thể nói bằng lời nói. Thay vào đó, ông nói bằng những ý tưởng. Tên ông là Stephen Hawking." }
    ]
  }
];