if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["04 April"] = [
  {
    "day": 1,
    "title": "Pieces of Me",
    "image": "04 April/images/day_01.webp",
    "audio": "04 April/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, my mom and I were looking at our family pictures. 'You look so much like your daddy when you smile,' Mom told me.", "ipa": "/wʌn deɪ, maɪ mɒm ænd aɪ wɜːr ˈlʊkɪŋ ɒn ˈaʊər ˈfæməli ˈpɪktʃərz. juː lʊk soʊ mʌtʃ laɪk jɔːr ˈdædi wɛn juː smaɪl, mɒm toʊld miː/", "vi": "Một hôm, mẹ và tôi đang cùng xem lại những bức ảnh gia đình. 'Con cười trông giống hệt bố đấy,' mẹ bảo tôi." },
      { "start": 12.0, "en": "'Really?' I said. 'But I have your eyes, right Mom?' 'That's right.'", "ipa": "/ˈriːəli?, aɪ sɛd. bʌt aɪ hæv jɔːr aɪz, raɪt mɒm? ðæts raɪt/", vi: "'Thật ạ?' tôi nói. 'Nhưng con mang đôi mắt của mẹ cơ mà, phải không mẹ?' 'Đúng thế.'" },
      { "start": 19.0, "en": "A couple of days later, while I was practising my dancing, Mom said, 'Did I ever tell you that my daddy owned a dance studio? I bet you get your grace and love of dancing from him.'", "ipa": "/ə ˈkʌpl əv deɪz ˈleɪtər, waɪl aɪ wɒz ˈpræktɪsɪŋ maɪ ˈdænsɪŋ, mɒm sɛd, dɪd aɪ ˈɛvər tɛl juː ðæt maɪ ˈdædi oʊnd a dæns ˈstudiˌoʊ? aɪ bɛt juː ɡɛt jɔːr ɡreɪs ænd lʌv əv ˈdænsɪŋ frɒm hɪm/", vi: "Vài ngày sau, trong lúc tôi đang tập múa, mẹ nói: 'Mẹ đã từng kể cho con nghe việc ông ngoại từng sở hữu một phòng tập nhảy chưa nhỉ? Mẹ cá là con được thừa hưởng sự uyển chuyển và tình yêu múa may từ ông đấy.'" },
      { "start": 32.0, "en": "Grandpa died before I was born. But after hearing my mom say this, I felt that I knew him better since we had something in common.", "ipa": "/ˈɡrændˌpɑː daɪd bɪˈfɔːr aɪ wɒz bɔːrn. bʌt ˈɑːftər ˈhɪərɪŋ maɪ mɒm seɪ ðɪs, aɪ fɛlt ðæt aɪ nuː hɪm ˈbɛtər sɪns wiː hæd ˈsʌmθɪŋ ɪn ˈkɒmən/", vi: "Ông ngoại đã qua đời trước khi tôi ra đời. Nhưng sau khi nghe mẹ kể, tôi cảm thấy như mình hiểu ông hơn vì hai ông cháu có điểm chung." },
      { "start": 41.0, "en": "'Who else am I like?' 'Let's see. You have a lovely singing voice like Uncle Kevin. And, you love girly things just like I did when I was your age.'", "ipa": "/huː ɛls æm aɪ laɪk? lɛts siː. juː hæv a ˈlʌvli ˈsɪŋɪŋ vɔɪs laɪk ˈʌŋkl ˈkɛvɪn. ænd, juː lʌv ˈɡɜːrli θɪŋz dʒʌst laɪk aɪ dɪd wɛn aɪ wɒz jɔːr eɪdʒ/", vi: "'Thế con còn giống ai nữa ạ?' 'Để xem nào. Con sở hữu giọng hát ngọt ngào giống chú Kevin. Hơn nữa, con cũng thích những món đồ nữ tính y hệt như mẹ hồi bằng tuổi con vậy.'" },
      { "start": 54.0, "en": "'I like those pieces of me,' I said as I ran upstairs to sing to my dolls. I like that there are pieces of me that are all my own. But most of all, I love the pieces that I share with the people I love.", "ipa": "/aɪ laɪk ðoʊz piːsɪz əv miː, aɪ sɛd æz aɪ ræn ˈʌpˌstɛərz tuː sɪŋ tuː maɪ dɒlz. aɪ laɪk ðæt ðɛr ɑːr piːsɪz əv miː ðæt ɑːr ɔːl maɪ oʊn. bʌt moʊst əv ɔːl, aɪ lʌv ðə piːsɪz ðæt aɪ ʃɛr wɪð ðə ˈpiːpl aɪ lʌv/", vi: "'Con rất thích những mảnh ghép đó của mình,' tôi vừa nói vừa chạy lên lầu để hát cho lũ búp bê nghe. Tôi thích việc mình có những nét tính cách độc bản chỉ thuộc về riêng mình. Nhưng trên hết, tôi yêu nhất những mảnh ghép mà tôi được sẻ chia với những người thân yêu." }
    ]
  },
  {
    "day": 2,
    "title": "The Gift",
    image: "04 April/images/day_02.webp",
    audio: "04 April/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "Today is Grandma's 85th birthday. 'I'm giving her a picture,' says Brian. 'I took it with my new camera. What are you going to give her?' he asks his brother Joey.", "ipa": "/təˈdeɪ ɪz ˈɡrænmɑːz ˈɛti-fɪfθ ˈbɜːrθdeɪ. aɪm ˈɡɪvɪŋ hɜːr a ˈpɪktʃər, sɛz ˈbraɪən. aɪ tʊk ɪt wɪð maɪ nuː ˈkæmərə. wɒt ɑːr juː ˈɡoʊɪŋ tuː ɡɪv hɜːr?, hiː ɑːsks hɪz ˈbrʌðər ˈdʒoʊi/", vi: "Hôm nay là sinh nhật lần thứ 85 của bà ngoại. 'Tớ sẽ tặng bà một bức ảnh,' Brian khoe. 'Tớ chụp nó bằng chiếc máy ảnh mới tinh. Thế cậu định tặng bà món quà gì?' cậu quay sang hỏi người em trai Joey." },
      { "start": 18.0, "en": "'I don't know,' says Joey. 'I don't have a camera. So I can't take a picture.' Joey goes into the kitchen. His mom is busy baking. 'Mom, what are you giving Grandma?' 'I'm baking her favourite cake,' says Joey's mom.", "ipa": "/aɪ doʊnt noʊ, sɛz ˈdʒoʊi. aɪ doʊnt hæv a ˈkæmərə. soʊ aɪ kænt teɪk a ˈpɪktʃər. ˈdʒoʊi ɡoʊz ˈɪntuː ðə ˈkɪtʃɪn. hɪz mɒm ɪz ˈbɪzi ˈbeɪkɪŋ. mɒm, wɒt ɑːr juː ˈɡɪvɪŋ ˈɡrænmɑː? aɪm ˈbeɪkɪŋ hɜːr ˈfeɪvərɪt keɪk, sɛd ˈdʒoʊiz mɒm/", vi: "'Tớ chịu thôi,' Joey đáp. 'Tớ có máy ảnh đâu mà chụp ảnh.' Joey bèn đi vào phòng bếp. Mẹ đang bận rộn nướng bánh. 'Mẹ ơi, mẹ tặng gì cho bà thế ạ?' 'Mẹ nướng chiếc bánh kem vị yêu thích của bà,' mẹ trả lời." },
      { "start": 35.0, "en": "'I can't bake cakes. I don't know how,' says Joey. Joey goes to his sister's room. She is busy sewing. 'Susan, what are you giving Grandma?' 'I'm making her a warm blanket,' says Susan.", "ipa": "/aɪ kænt beɪk keɪks. aɪ doʊnt noʊ haʊ, sɛz ˈdʒoʊi. ˈdʒoʊi ɡoʊz tuː hɪz ˈsɪstərz ruːm. ʃiː ɪz ˈbɪzi ˈsoʊɪŋ. ˈsuːzən, wɒt ɑːr juː ˈɡɪvɪŋ ˈɡrænmɑː? aɪm ˈmeɪkɪŋ hɜːr a wɔːrm ˈblæŋkɪt, sɛd ˈsuːzən/", vi: "'Con thì chẳng biết nướng bánh hay làm bánh gì cả,' Joey thở dài. Cậu lại sang phòng chị gái đang cặm cụi may vá. 'Susan ơi, chị tặng bà món quà gì thế?' 'Chị đang làm một chiếc chăn ấm áp tặng bà,' Susan đáp." },
      { "start": 50.0, "en": "'I can't sew blankets. I don't know how,' says Joey. Joey then goes and sits next to Grandma on the couch. 'Everyone has a present for you, but me. I can't take a picture, bake or sew. I don't have anything to give you,' says Joey.", "ipa": "/aɪ kænt soʊ ˈblæŋkɪts. aɪ doʊnt noʊ haʊ, sɛz ˈdʒoʊi. ˈdʒoʊi ðɛn ɡoʊz ænd sɪts nɛkst tuː ˈɡrænmɑː ɒn ðə kaʊtʃ. ˈɛvriˌwʌn hæz a ˈprɛznt fɔːr juː, bʌt miː. aɪ kænt teɪk a ˈpɪktʃər, beɪk ɔːr soʊ. aɪ doʊnt hæv ˈɛniˌθɪŋ tuː ɡɪv juː, sɛd ˈdʒoʊi/", vi: "'Em cũng chẳng biết may chăn,' Joey buồn bã nói. Cậu lủi thủi đi ra phòng khách ngồi thụp xuống bên cạnh bà ngoại. 'Ai cũng có quà sinh nhật tặng bà ngoại, chỉ có mỗi em là tay trắng. Em không biết chụp ảnh, không biết làm bánh cũng chẳng biết may vá, em chẳng có gì để tặng bà cả,' Joey thổ lộ." },
      { "start": 68.0, "en": "Grandma put her arm around Joey. 'No one else has the time to come and sit with me. That's what you can give me,' says Grandma. Joey snuggles in close to Grandma. 'Happy Birthday,' he says.", "ipa": "/ˈɡrænmɑː pʊt hɜːr ɑːrm əˈraʊnd ˈdʒoʊi. noʊ wʌn ɛls hæz ðə taɪm tuː kʌm ænd sɪt wɪð miː. ðæts wɒt juː kæn ɡɪv miː, sɛd ˈɡrænmɑː. ˈdʒoʊi ˈsnʌɡəlz ɪn kloʊs tuː ˈɡrænmɑː. ˈhæpi ˈbɜːrθdeɪ, hiː sɛd/", vi: "Bà ngoại dịu dàng vòng tay ôm lấy Joey vào lòng. 'Chẳng có ai ngoài cháu chịu dành thời gian đến ngồi bầu bạn tâm sự với bà cả. Đó chính là món quà quý giá nhất mà cháu có thể tặng cho bà rồi,' bà mỉm cười nói. Joey rúc đầu vào ngực bà thật ấm áp và thì thầm: 'Chúc mừng sinh nhật bà ạ.'" }
    ]
  },
  {
    "day": 3,
    "title": "Andrew and the Little Bird",
    image: "04 April/images/day_03.webp",
    audio: "04 April/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Andrew and his family were out in their car. Dad was driving. Suddenly, a little bird flew into the windshield and fell.", "ipa": "/ˈændruː ænd hɪz ˈfæməli wɜːr aʊt ɪn ðɛr kɑːr. dæd wɒz ˈdraɪvɪŋ. ˈsʌdənli, a ˈlɪtl bɜːrd fluː ˈɪntuː ðə ˈwɪndˌʃiːld ænd fɛl/", vi: "Andrew cùng gia đình đang ngồi trên xe ô tô đi chơi do bố cầm lái. Bất ngờ, một chú chim nhỏ lao thẳng vào kính chắn gió rồi rơi rụm xuống đường." },
      { "start": 14.0, "en": "'Stop!' yelled Andrew. Dad stopped the car, looking sad. He said, 'The bird is probably dead.'", "ipa": "/stɒp!, jɛld ˈændruː. dæd stɒpt ðə kɑːr, ˈlʊkɪŋ sæd. hiː sɛd, ðə bɜːrd ɪz ˈprɒbəbli dɛd/", vi: "'Dừng xe lại bố ơi!' Andrew hốt hoảng hét lên. Bố đạp phanh dừng xe, gương mặt đượm buồn và bảo: 'Chắc chú chim ấy không qua khỏi đâu con ạ.'" },
      { "start": 23.0, "en": "Andrew jumped out of the car, pulling off his woolly hat. Gently, he picked up the bird and put it in his hat. Then he put the hat inside his coat.", "ipa": "/ˈændruː dʒʌmpt aʊt əv ðə kɑːr, ˈpʊlɪŋ ɔːf hɪz ˈwʊli hæt. ˈdʒɛntli, hiː pɪkt ʌp ðə bɜːrd ænd pʊt ɪt ɪn hɪz hæt. ðɛn hiː pʊt ðə hæt ˈɪnˌsaɪd hɪz koʊt/", vi: "Andrew lập tức tung cửa nhảy tót khỏi xe, nhanh tay tháo chiếc mũ len ấm áp trên đầu ra. Cậu nhẹ nhàng nhặt chú chim đặt vào lòng mũ, rồi cẩn thận giấu chiếc mũ vào trong lớp áo khoác." },
      { "start": 35.0, "en": "All the way, Andrew kept the bird warm. When they got home, Dad said, 'We should bury that little bird, Andrew.'", "ipa": "/ɔːl ðə weɪ, ˈændruː kɛpt ðə bɜːrd wɔːrm. wɛn ðeɪ ɡɒt hoʊm, dæd sɛd, wiː ʃʊd ˈbɛri ðæt ˈlɪtl bɜːrd, ˈændruː/", vi: "Suốt dọc đường đi, Andrew luôn áp ngực giữ cho chú chim nhỏ được ấm áp. Về đến nhà, bố thở dài: 'Chúng ta nên chôn cất chú chim nhỏ thôi con ạ, Andrew.'" },
      { "start": 44.0, "en": "Sadly, Andrew took his hat out of his coat and opened it. The little bird opened his eyes and looked at him. 'Dad, it's alive. Look!' shouted Andrew.", "ipa": "/ˈsædli, ˈændruː tʊk hɪz hæt aʊt əv hɪz koʊt ænd ˈoʊpənd ɪt. ðə ˈlɪtl bɜːrd ˈoʊpənd hɪz aɪz ænd lʊkt æt hɪm. dæd, ɪts əˈlaɪv. lʊk!, ˈʃaʊtɪd ˈændruː/", vi: "Với nét mặt đượm buồn, Andrew từ từ lấy chiếc mũ ra khỏi áo và hé mở. Kỳ diệu thay, chú chim nhỏ từ từ chớp mắt tỉnh dậy và ngước nhìn cậu. 'Bố ơi, nó còn sống! Nhìn này bố,' Andrew reo lên vui sướng." },
      { "start": 56.0, "en": "The little bird hopped onto his hand and then flew into a tree. 'Well done Andrew! It was you who saved that little bird!' said Mom.", "ipa": "/ðə ˈlɪtl bɜːrd hɒpt ˈɒntuː hɪz hænd ænd ðɛn fluː ˈɪntuː a triː. wɛl dʌn ˈændruː! ɪt wɒz juː huː seɪvd ðæt ˈlɪtl bɜːrd!, sɛd mɒm/", vi: "Chú chim nhỏ chuyền phắt lên bàn tay cậu rồi vỗ cánh bay vút lên ngọn cây cao. 'Làm tốt lắm con trai! Chính con là người cứu sống chú chim nhỏ đó đấy,' mẹ mỉm cười tự hào khen ngợi." }
    ]
  },
  {
    "day": 4,
    "title": "Which Hand Do You Use?",
    image: "04 April/images/day_04.webp",
    audio: "04 April/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "Nine out of ten people in the world are right-handed. That means they use their right hands for doing things such as throwing, catching and writing.", "ipa": "/naɪn aʊt əv tɛn ˈpiːpl ɪn ðə wɜːrld ɑːr raɪt-ˈhændɪd. ðæt miːnz ðeɪ juːz ðɛr raɪt hændz fɔːr ˈduːɪŋ θɪŋz ˈsʌtʃ æz ˈθroʊɪŋ, ˈkætʃɪŋ ænd ˈraɪtɪŋ/", vi: "Cứ mười người trên thế giới thì có chín người thuận tay phải. Điều đó đồng nghĩa với việc họ sử dụng tay phải làm các công việc chủ đạo như ném bóng, bắt bóng hay viết lách." },
      { "start": 15.0, "en": "But not everyone is right-handed. One person in ten is left-handed.", "ipa": "/bʌt nɒt ˈɛvriˌwʌn ɪz raɪt-ˈhændɪd. wʌn ˈpɜːrsn ɪn tɛn ɪz lɛft-ˈhændɪd/", vi: "Tuy nhiên không phải tất cả mọi người đều thuận tay phải. Cứ mười người sẽ có một người thuận tay trái." },
      { "start": 21.0, "en": "Being left-handed is not a big problem now. But not so long ago in Europe, left-handed people had terrible lives. Everyone believed that left-handed people were evil. If they were caught writing with their left hands, they could be killed.", "ipa": "/ˈbiːɪŋ lɛft-ˈhændɪd ɪz nɒt a bɪɡ ˈprɒbləm naʊ. bʌt nɒt soʊ lɒŋ əˈɡoʊ ɪn ˈjʊərəp, lɛft-ˈhændɪd ˈpiːpl hæd ˈtɛrəbl laɪvz. ˈɛvriˌwʌn bɪˈliːvd ðæt lɛft-ˈhændɪd ˈpiːpl wɜːr ˈiːvl. ɪf ðeɪ wɜːr kɔːt ˈraɪtɪŋ wɪð ðɛr lɛft hændz, ðeɪ kʊd biː kɪld/", vi: "Ngày nay việc thuận tay trái không còn là vấn đề lớn lao gì, nhưng cách đây chưa lâu ở châu Âu, những người thuận tay trái từng có một cuộc đời vô cùng tồi tệ. Người ta từng tin rằng những kẻ thuận tay trái mang bản chất tà ác. Nếu bị bắt quả tang viết bằng tay trái, họ thậm chí có thể bị xử tử." },
      { "start": 39.0, "en": "Left-handed children were forced to write with their right hands. They were often beaten until they stopped using their left hands.", "ipa": "/lɛft-ˈhændɪd ˈtʃɪldrən wɜːr fɔːrst tɔː raɪt wɪð ðɛr raɪt hændz. ðeɪ wɜːr ˈɒfn ˈbiːtn ʌnˈtɪl ðeɪ stɒpt ˈjuːzɪŋ ðɛr lɛft hændz/", vi: "Trẻ em thuận tay trái bị ép buộc phải tập viết bằng tay phải. Chúng thường xuyên bị roi vọt đánh đập tàn nhẫn cho đến khi từ bỏ hoàn toàn thói quen dùng tay trái." },
      { "start": 48.0, "en": "No one wanted to marry left-handed people. It was hard for them to get a job, and they often had no friends. Today, it's still not easy being left-handed. Most things in the world are designed for people who are right-handed. But the way we think about being left-handed has changed. We now know that left-handed kids are just normal kids who prefer using their left hand over their right to get things done.", "ipa": "/noʊ wʌn ˈwɒntɪd tuː ˈmæri lɛft-ˈhændɪd ˈpiːpl. ɪt wɒz hɑːrd fɔːr ðɛm tuː ɡɛt a dʒɒb, ænd ðeɪ ˈɒfn hæd noʊ frɛndz. təˈdeɪ, ɪts stɪl nɒt ˈiːzi ˈbiːɪŋ lɛft-ˈhændɪd. moʊst θɪŋz ɪn ðə wɜːrld ɑːr dɪˈzaɪnd fɔːr ˈpiːpl whoː ɑːr raɪt-ˈhændɪd. bʌt ðə weɪ wiː θɪŋk əˈbaʊt ˈbiːɪŋ lɛft-ˈhændɪd hæz tʃeɪndʒd. wiː naʊ noʊ ðæt lɛft-ˈhændɪd kɪdz ɑːr dʒʌst ˈnɔːrməl kɪdz whoː prɪˈfɜːr ˈjuːzɪŋ ðɛr lɛft hænd ˈoʊvər ðə raɪt tuː ɡɛt θɪŋz dʌn/", vi: "Chẳng ai muốn kết hôn với người thuận tay trái, việc tìm kiếm công việc mưu sinh vô cùng khó khăn và họ thường bị cô lập không có lấy một người bạn. Ngày nay, cuộc sống của người thuận tay trái vẫn còn những bất tiện nhất định bởi phần lớn thiết kế trên thế giới đều ưu tiên cho người thuận tay phải. Dù vậy, tư duy xã hội về người thuận tay trái đã thay đổi tích cực. Giờ đây chúng ta hiểu rằng những đứa trẻ thuận tay trái hoàn toàn bình thường, chỉ là chúng có xu hướng ưa chuộng sử dụng tay trái hơn tay phải trong sinh hoạt hằng ngày." }
    ]
  },
  {
    "day": 5,
    "title": "Cars for Kids",
    image: "04 April/images/day_05.webp",
    audio: "04 April/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Patrick loves his cars. In his room, he has toy cars of all makes, models and colours everywhere. Near his home, there is a toy store. It is Patrick's favourite store.", "ipa": "/ˈpætrɪk lʌvz hɪz kɑːrz. ɪn hɪz ruːm, hiː hæz tɔɪ kɑːrz əv ɔːl meɪks, ˈmɒdəlz ænd ˈkʌlərz ˈɛvriˌwɛr. nɪər hɪz hoʊm, ðɛr ɪz a tɔɪ stɔːr. ɪt ɪz ˈpætrɪks ˈfeɪvərɪt stɔːr/", vi: "Patrick vô cùng mê ô tô. Trong phòng ngủ của cậu, ô tô đồ chơi đủ mọi hãng, mọi mẫu mã và màu sắc được bày la liệt khắp mọi nơi. Ngay gần nhà cậu có một cửa hàng đồ chơi, và đó chính là chốn thiên đường yêu thích nhất của Patrick." },
      { "start": 16.0, "en": "Patrick's grandparents love their little boy. Every time they come to visit, they take him to the store and add a few toy cars to his collection.", "ipa": "/ˈpætrɪks ˈɡrændˌpɛrənts lʌv ðɛr ˈlɪtl bɔɪ. ˈɛvri taɪm ðeɪ kʌm tuː ˈvɪzɪt, ðeɪ teɪk hɪm tuː ðə stɔːr ænd æd a fjuː tɔɪ kɑːrz tuː hɪz kəˈlɛkʃn/", vi: "Ông bà nội ngoại rất mực cưng chiều cậu cháu đích tôn. Mỗi lần sang chơi, ông bà lại dắt Patrick ra cửa hàng đồ chơi để tậu thêm vài chiếc xe mới bổ sung vào bộ sưu tập đồ sộ của cậu." },
      { "start": 25.0, "en": "One day, Patrick's mom said, 'You have too many toy cars, my boy. I have to give some of them away.' But Patrick begged, 'No, Mom! PLEASE.'", "ipa": "/wʌn deɪ, ˈpætrɪks mɒm sɛd, juː hæv tuː ˈmɛni tɔɪ kɑːrz, maɪ bɔɪ. aɪ hæv tuː ɡɪv sʌm əv ðɛm əˈweɪ. bʌt ˈpætrɪk bɛɡd, noʊ, mɒm! pliːz/", vi: "Đến một hôm, mẹ bảo: 'Con trai à, con có quá nhiều ô tô đồ chơi rồi đấy. Mẹ phải đem bớt đi cho người khác thôi.' Patrick hoảng hốt chắp tay van nài: 'Không đâu mẹ ơi! XIN MẸ ĐỪNG MÀ.'" },
      { "start": 36.0, "en": "A few days later, Patrick heard about an earthquake in Haiti. He felt sad for the kids there. He wanted to help. From his collection, he picked out several toy cars. He packed them into a nice box. Then he took out the money from his piggy bank.", "ipa": "/a fjuː deɪz ˈleɪtər, ˈpætrɪk hɜːrd əˈbaʊt ən ˈɜːrθˌkweɪk ɪn ˈheɪti. hiː fɛlt sæd fɔːr ðə kɪdz ðɛr. hiː ˈwɒntɪd tuː hɛlp. frɒm hɪz kəˈlɛkʃn, hiː pɪkt aʊt ˈsɛvrəl tɔɪ kɑːrz. hiː pækt ðɛm ˈɪntuː a naɪs bɒks. ðɛn hiː tʊk aʊt ðə ˈmʌni frɒm hɪz ˈpɪɡi bæŋk/", vi: "Vài ngày sau, Patrick xem được bản tin thời sự về trận động đất thảm khốc xảy ra ở Haiti. Cậu cảm thấy vô cùng thương xót cho những bạn nhỏ kém may mắn ở đó và khao khát muốn làm điều gì đó để giúp đỡ. Ngay lập tức, cậu chọn lọc ra hàng loạt chiếc xe đồ chơi đẹp nhất từ bộ sưu tập của mình, cẩn thận xếp chúng vào một chiếc hộp xinh xắn, rồi đập ống heo lấy hết số tiền tiết kiệm." },
      { "start": 54.0, "en": "He sent his cars and the money to the Haitian kids who suffered in the earthquake.", "ipa": "/hiː sɛnt hɪz kɑːrz ænd ðə ˈmʌni tuː ðə ˈheɪʃn kɪdz huː ˈsʌfərd ɪn ði ˈɜːrθˌkweɪk/", vi: "Cậu bé đã gửi toàn bộ số ô tô đồ chơi và số tiền tích cóp ấy đến tận tay các bạn nhỏ vùng nạn kiếp động đất ở Haiti." }
    ]
  },
  {
    "day": 6,
    "title": "Red Vest Day",
    image: "04 April/images/day_06.webp",
    audio: "04 April/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "Dick pulled on his red vest. Today, he and the rest of his class were all going to wear red vests. Why? They were going to clean up trash along the road.", "ipa": "/dɪk pʊld ɒn hɪz rɛd vɛst. təˈdeɪ, hiː ænd ðə rɛst əv hɪz klæs wɜːr ɔːl ˈɡoʊɪŋ tuː wɛr rɛd vɛsts. waɪ? ðeɪ wɜːr ˈɡoʊɪŋ tuː kliːn ʌp træʃ əˈlɒŋ ðə roʊd/", vi: "Dick khoác chiếc áo lê-gít màu đỏ rực lên người. Hôm nay, tất cả học sinh trong lớp cậu đều đồng loạt mặc áo lê-gít đỏ ra quân. Tại sao ư? Bởi vì chúng sắp sửa tổ chức một chiến dịch tổng dọn dẹp rác thải dọc theo các tuyến đường." },
      { "start": 16.0, "en": "They were wearing red vests so that anyone driving a car along the road could see them. Even Mr. Tyler, the gym teacher, was going to wear one.", "ipa": "/ðeɪ wɜːr ˈwɛərɪŋ rɛd vɛsts soʊ ðæt ˈɛniˌwʌn ˈdraɪvɪŋ a kɑːr əˈlɒŋ ðə roʊd kʊd siː ðɛm. ˈiːvn ˈmɪstər ˈtaɪlər, ðə dʒɪm ˈtiːtʃər, wɒz ˈɡoʊɪŋ tuː wɛr wʌn/", vi: "Việc mặc áo đỏ nổi bật giúp cho bất kỳ tài xế lái ô tô nào đi qua đoạn đường đó cũng dễ dàng nhìn thấy từ xa để tránh đảm bảo an toàn. Ngay cả thầy giáo thể dục Mr. Tyler cũng hưởng ứng mặc chiếc áo này." },
      { "start": 27.0, "en": "Mr. Tyler gave everyone a black bag. 'I want you all to be careful,' he told them. 'We don't want anyone getting hurt.'", "ipa": "/ˈmɪstər ˈtaɪlər ɡeɪv ˈɛvriˌwʌn a blæk bæɡ. aɪ wɒnt juː ɔːl tuː biː ˈkɛrfəl, hiː toʊld ðɛm. wiː doʊnt wɒnt ˈɛniˌwʌn ˈɡɛtɪŋ hɜːrt/", vi: "Thầy Tyler phát cho mỗi em một chiếc túi đựng rác màu đen to bản. 'Thầy muốn tất cả các em phải hết sức cẩn thận khi làm nhiệm vụ nhé,' thầy căn dặn. 'Chúng ta không muốn có bất kỳ ai gặp sự cố chấn thương nào cả.'" },
      { "start": 38.0, "en": "The boys and the girls worked hard. When the bags were full, the boys placed them along the side of the road.", "ipa": "/ðə bɔɪz ænd ðə ɡɜːrlz wɜːrkt hɑːrd. wɛn ðə bæɡz wɜːr fʊl, ðə bɔɪz pleɪst ðɛm əˈlɒŋ ðə saɪd əv ðə roʊd/", vi: "Đám trẻ trai gái hăng say làm việc không ngơi tay. Khi những chiếc túi đã được nhét kín rác nặng trịch, các bạn nam liền gom chúng xếp thành hàng dài ngay ngắn dọc lề đường." },
      { "start": 48.0, "en": "'I didn't think we'd find so much trash,' said Dick. His dad was going to take the garbage to the dump in his truck. Seeing the truck loaded with the full bags of trash, the children were happy to have played a part in cleaning up their town.", "ipa": "/aɪ ˈdɪdnt θɪŋk wiːd faɪnd soʊ mʌtʃ træʃ, sɛd dɪk. hɪz dæd wɒz ˈɡoʊɪŋ tuː teɪk ðə ˈɡɑːrbɪdʒ tuː ðə dʌmp ɪn hɪz trʌk. ˈsiːɪŋ ðə trʌk ˈloʊdɪd wɪð ðə fʊl bæɡz əv træʃ, ðə ˈtʃɪldrən wɜːr ˈhæpi tuː hæv pleɪd a pɑːrt ɪn ˈkliːnɪŋ ʌp ðɛər taʊn/", vi: "'Tớ không thể ngờ nổi dọc đường lại có nhiều rác rưởi vứt bừa bãi đến thế này,' Dick thốt lên ngạc nhiên. Bố của cậu sẽ lái xe tải chở toàn bộ số rác thải này ra bãi rác tập trung xử lý. Nhìn chiếc xe tải chất đầy những túi rác nặng trịch, bầy trẻ vô cùng tự hào và hạnh phúc vì đã góp phần nhỏ bé vào công cuộc làm sạch đẹp cho thị trấn." }
    ]
  },
  {
    "day": 7,
    "title": "Cry Wolf",
    image: "04 April/images/day_07.webp",
    audio: "04 April/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "Have you ever heard of the expression 'cry wolf'? Do you know what it means and where it comes from? Here is the story.", "ipa": "/hæv juː ˈɛvər hɜːrd əv ði ɪkˈsprɛʃn kraɪ wʊlf? duː juː noʊ wɒt ɪt miːnz ænd wɛr ɪt kʌmz frɒm? hɪər ɪz ðə ˈstɔːri/", vi: "Các bạn đã bao giờ nghe đến thành ngữ 'cố ý hô hoán báo động giả' hay chưa? Bạn có hiểu ý nghĩa và nguồn gốc xuất xứ của câu chuyện ngụ ngôn ấy từ đâu không? Hãy cùng lắng nghe nhé." },
      { "start": 13.0, "en": "One day, a boy was looking after some sheep in the fields near a village. He felt bored. 'It is fun to have people to talk to,' thought the boy. Then, he came up with an idea.", "ipa": "/wʌn deɪ, a bɔɪ wɒz ˈlʊkɪŋ ˈɑːftər sʌm ʃiːp ɪn ðə fiːldz nɪər a ˈvɪlɪdʒ. hiː fɛlt bɔːrd. ɪt ɪz fʌn tuː hæv ˈpiːpl tuː tɔːk tuː, θɔːt ðə bɔɪ. ðɛn, hiː keɪm ʌp wɪð an aɪˈdiːə/", vi: "Ngày xửa ngày xưa, có một cậu bé chăn cừu được giao nhiệm vụ trông coi đàn cừu trên cánh đồng gần một ngôi làng nhỏ. Cậu cảm thấy vô cùng buồn chán vì cô độc. 'Ước gì có ai đó ở đây để mình trò chuyện cùng nhỉ,' cậu thầm nghĩ, rồi một mưu mẹo ranh mãnh chợt lóe lên trong đầu." },
      { "start": 26.0, "en": "He shouted loudly, 'WOLF! WOLF! HELP!' The people in the nearby village heard his cries. They immediately dropped what they were doing and came running to help the boy.", "ipa": "/hiː ˈʃaʊtɪd ˈlaʊdli, wʊlf! wʊlf! hɛlp! ðə ˈpiːpl ɪn ðə ˈnɪrbaɪ ˈvɪlɪdʒ hɜːrd hɪz kraɪz. ðeɪ ɪˈmiːdiətli drɒpt wɒt ðeɪ wɜːr ˈduːɪŋ ænd keɪm ˈrʌnɪŋ tuː hɛlp ðə bɔɪ/", vi: "Cậu cất giọng gào thét thật to: 'SÓI! CÓ SÓI ĂN THỊT CỪU! CỨU TÔI VỚI!' Người dân ở ngôi làng dưới chân đồi nghe thấy tiếng kêu cứu thất thanh liền hoảng hốt buông bỏ hết mọi công việc đang dở dang, hộc tốc chạy như bay lên đồi để ứng cứu cậu bé." },
      { "start": 38.0, "en": "But there was no wolf. Both the boy and the sheep were safe. So the people returned to their work.", "ipa": "/bʌt ðɛr wɒz noʊ wʊlf. boʊθ ðə bɔɪ ænd ðə ʃiːp wɜːr seɪf. soʊ ðə ˈpiːpl rɪˈtɜːrnd tuː ðɛr wɜːrk/", vi: "Nhưng khi lên đến nơi thì chẳng có con sói nào cả. Cả cậu bé lẫn đàn cừu đều bình an vô sự. Thấy vậy, mọi người đành lắc đầu quay trở lại hạ sơn tiếp tục công việc." },
      { "start": 46.0, "en": "Soon, the boy grew lonely again. 'WOLF! WOLF!' he cried. Once again, the villagers came to help him. But again, there was no wolf.", "ipa": "/suːn, ðə bɔɪ ɡruː ˈloʊnli əˈɡɛn. wʊlf! wʊlf!, hiː kraɪd. wʌns əˈɡɛn, ðə ˈvɪlɪdʒərz keɪm tuː hɛlp hɪm. bʌt əˈɡɛn, ðɛr wɒz noʊ wʊlf/", vi: "Chẳng mấy chốc, sự cô đơn lại bủa vây cậu bé nghịch ngợm. 'SÓI KÌA! SÓI ĂN THỊT CỪU!' cậu lại tiếp tục trò đùa ác ý. Một lần nữa, dân làng lại hớt hải chạy lên cứu nạn, để rồi chưng hửng nhận ra vẫn chẳng có con sói nào bén mảng tới." },
      { "start": 57.0, "en": "A few days later, a pack of hungry wolves did come. They were hungry and started to attack the boy and his sheep. The boy was frightened. He cried as loud as he could, 'WOLF! WOLF! HELP! HELP!!!' But this time, the villagers did not come.", "ipa": "/a fjuː deɪz ˈleɪtər, a pæk əv ˈhʌŋɡri wʊlvz dɪd kʌm. ðeɪ wɜːr ˈhʌŋɡri ænd ˈstɑːrtɪd tuː əˈtæk ðə bɔɪ ænd hɪz ʃiːp. ðə bɔɪ wɒz ˈfraɪtnd. hiː kraɪd æz laʊd æz hiː kʊd, wʊlf! wʊlf! hɛlp! hɛlp!!! bʌt ðɪs taɪm, ðə ˈvɪlɪdʒərz dɪd nɒt kʌm/", vi: "Vài ngày sau, một bầy sói đói khát thực sự xuất hiện trên đồi. Chúng gầm gừ lao vào tấn công điên cuồng bầy cừu và cả cậu bé. Cậu vô cùng hoảng loạn, khóc thét gào lên bằng tất cả sức lực: 'SÓI! CÓ SÓI THẬT MÀ! CỨU TÔI VỚI!!!' Thế nhưng lần này, chẳng còn một ai trong làng đoái hoài chạy lên cứu cậu nữa." }
    ]
  },
  {
    "day": 8,
    "title": "Stick Out Your Tongue",
    image: "04 April/images/day_08.webp",
    audio: "04 April/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "Look in the mirror. Open your mouth and stick out your tongue. You probably don't think about it a lot. But your tongue is a very important part of your body.", "ipa": "/lʊk ɪn ðə ˈmɪrər. ˈoʊpən jɔːr maʊθ ænd stɪk aʊt jɔːr tʌŋ. juː ˈprɒbəbli doʊnt θɪŋk əˈbaʊt ɪt a lɒt. bʌt jɔːr tʌŋ ɪz a ˈvɛri ɪmˈpɔːrtənt pɑːrt əv jɔːr ˈbɒdi/", vi: "Hãy đứng trước gương, há miệng thật rộng và lè lưỡi ra ngoài xem nào. Có thể bạn ít khi để tâm đến nó, nhưng chiếc lưỡi lại là một bộ phận vô cùng tối quan trọng trên cơ thể chúng ta." },
      { "start": 16.0, "en": "Eat any ice cream lately? Well, you can thank your tongue for the wonderful taste. The top of your tongue has many small taste buds.", "ipa": "/iːt ˈɛni aɪs kriːm ˈleɪtli? wɛl, juː kæn θæŋk jɔːr tʌŋ fɔːr ðə ˈwʌndərfʊl teɪst. ðə tɒp əv jɔːr tʌŋ hæz ˈmɛni smɔːl teɪst bʌdz/", vi: "Bạn có thưởng thức món kem nào gần đây không? Chà, bạn phải gửi lời cảm ơn sâu sắc đến chiếc lưỡi vì đã mang lại hương vị tuyệt vời đó. Bề mặt lưỡi được phủ kín bởi vô số nụ vị giác nhỏ ti ti." },
      { "start": 26.0, "en": "When you lick ice cream, your tongue sends messages to your brain. And your brain tells you if something tastes good or bad. Your tongue weighs only about 50 grams. It's a muscle and it does a lot of work for you.", "ipa": "/wɛn juː lɪk aɪs kriːm, jɔːr tʌŋ sɛndz ˈmɛsɪdʒɪz tuː jɔːr breɪn. ænd jɔːr breɪn tɛlz juː ɪf ˈsʌmθɪŋ teɪsts ɡʊd ɔːr bæd. jɔːr tʌŋ weɪz ˈoʊnli əˈbaʊt 50 ɡræmz. ɪts a ˈmʌsl ænd ɪt dʌz a lɒt əv wɜːrk fɔːr juː/", vi: "Mỗi khi bạn liếm cây kem mát lạnh, các nụ vị giác trên lưỡi lập tức truyền tín hiệu lên não bộ, để não phân tích xem món ăn đó ngon hay dở. Chiếc lưỡi chỉ nặng vỏn vẹn khoảng 50 gram, thực chất là một khối cơ linh hoạt gánh vác vô vàn nhiệm vụ nặng nhọc." },
      { "start": 44.0, "en": "It helps you chew your food by moving it around inside your mouth. It helps you swallow by pushing the food to the back of your mouth.", "ipa": "/ɪt hɛlps juː tʃuː jɔːr fuːd baɪ ˈmuːvɪŋ ɪt əˈraʊnd ˈɪnˌsaɪd jɔːr maʊθ. ɪt hɛlps juː ˈswɑːloʊ baɪ ˈpʊʃɪŋ ðə fuːd tuː ðə bæk əv jɔːr maʊθ/", vi: "Nó hỗ trợ đắc lực cho việc nhai thức ăn bằng cách đảo đều nhịp nhàng trong khoang miệng, đồng thời giúp bạn nuốt dễ dàng hơn bằng cách dồn thức ăn xuống cổ họng." },
      { "start": 53.0, "en": "Your tongue helps you talk too. That's right. Many sounds cannot be made without your tongue. Does your tongue ever rest? No. Even when you are asleep, your tongue is moving. It keeps your mouth from getting too dry.", "ipa": "/jɔːr tʌŋ hɛlps juː tɔːk tuː. ðæts raɪt. ˈmɛni saʊndz ˈkænɒt biː meɪd wɪˈðaʊt jɔːr tʌŋ. dʌz jɔːr tʌŋ ˈɛvər rɛst? noʊ. ˈiːvn wɛn juː ɑːr əˈsliːp, jɔːr tʌŋ ɪz ˈmuːvɪŋ. ɪt kiːps jɔːr maʊθ frɒm ˈɡɛtɪŋ tuː draɪ/", vi: "Không chỉ vậy, lưỡi còn là chìa khóa giúp chúng ta phát âm chuẩn xác. Đúng vậy, có rất nhiều âm tiết con người không thể phát ra nổi nếu thiếu đi sự linh hoạt của lưỡi. Thế chiếc lưỡi có bao giờ được nghỉ ngơi không nhỉ? Không hề đâu nhé. Ngay cả khi bạn đang say giấc nồng, chiếc lưỡi vẫn chăm chỉ chuyển động liên tục nhằm giữ cho khoang miệng không bị khô rát." }
    ]
  },
  {
    "day": 9,
    "title": "When It Happened",
    image: "04 April/images/day_09.webp",
    audio: "04 April/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "Today, Emma was very unhappy. Mom noticed it right away when Emma got off the school bus.", "ipa": "/təˈdeɪ, ˈɛmə wɒz ˈvɛri ʌnˈhæpi. mɒm ˈnoʊtɪst ɪt raɪt əˈweɪ wɛn ˈɛmə ɡɒt ɔːf ðə skuːl bʌs/", vi: "Hôm nay tâm trạng của Emma vô cùng tồi tệ và buồn bã. Mẹ nhận ra ngay điều đó từ khoảnh khắc Emma vừa bước xuống xe buýt trường học." },
      { "start": 10.0, "en": "What happened? Her best friend Jamie stopped talking to her. Worse than that, he said that they were no longer friends. That really hurt.", "ipa": "/wɒt ˈhæpənd? hɜːr bɛst frɛnd ˈdʒeɪmi stɒpt ˈtɔːkɪŋ tuː hɜːr. wɜːrs ðæt ðæt, hiː sɛd ðæt ðeɪ wɜːr noʊ ˈlɔːŋɡər frɛndz. ðæt ˈrɪəli hɜːrt/", vi: "Chuyện gì đã xảy ra thế? Cậu bạn thân nhất của cô bé là Jamie bỗng dưng lơ đẹp không thèm nói chuyện nữa, tệ hơn thế, cậu ta còn phũ phàng tuyên bố từ nay hai người không còn là bạn bè gì sất. Cú sốc đó thực sự làm tim cô bé đau nhói." },
      { "start": 21.0, "en": "Emma told her mom that she would like to change schools. Mom was surprised. But she said, 'Leaving may not be the best solution. You know, something like this could happen in another school too. Would you keep changing schools every time something like this happened?'", "ipa": "/ˈɛmə toʊld hɜːr mɒm ðæt ʃiː wʊd laɪk tuː tʃeɪndʒ skuːlz. mɒm wɒz sərˈpraɪzd. bʌt ʃiː sɛd, ˈliːvɪŋ meɪ nɒt biː ðə bɛst səˈluːʃn. juː noʊ, ˈsʌmθɪŋ laɪk ðɪs kʊd ˈhæpən ɪn əˈnʌðər skuːl tuː. wʊd juː kiːp ˈtʃeɪndʒɪŋ skuːlz ˈɛvri taɪm ˈsʌmθɪŋ laɪk ðɪs ˈhæpənd?/", vi: "Emma ấm ức thổ lộ với mẹ rằng cô bé muốn xin chuyển sang học trường khác. Mẹ ngạc nhiên hỏi lại: 'Nhưng con yêu, trốn chạy chưa chắc đã là phương án giải quyết tốt nhất đâu. Con biết đấy, những hiểu lầm thế này hoàn lẽ cũng có thể tái diễn ở bất kỳ ngôi trường mới nào. Lẽ nào con cứ muốn đổi trường liên tục mỗi lần gặp chuyện không như ý hay sao?'" },
      { "start": 39.0, "en": "Mom suggested that Emma talk to Jamie and find out what happened. The next day, when Emma arrived home from school, she told her mom that Jamie had been upset the day before. Why? Because when he had licked the paper, his tongue got cut. That's why he was so mean to everyone-especially his best friend. The smile came back to Emma's face.", "ipa": "/mɒm səˈdʒɛstɪd ðæt ˈɛmə tɔːk tuː ˈdʒeɪmi ænd faɪnd aʊt wɒt ˈhæpənd. ðə nɛkst deɪ, wɛn ˈɛmə əˈraɪvd hoʊm frɒm skuːl, ʃiː toʊld hɜːr mɒm ðæt ˈdʒeɪmi hæd biːn ʌpˈsɛt ðə deɪ bɪˈfɔːr. waɪ? bɪˈkəz wɛn hiː hæd lɪkt ðə ˈpeɪpər, hɪz tʌŋ ɡɒt kʌt. ðæts waɪ hiː wɒz soʊ miːn tuː ˈɛvriˌwʌn—ɪˈspɛʃli hɪz bɛst frɛnd. ðə smaɪl keɪm bæk tuː ˈɛməz feɪs/", vi: "Mẹ ôn tồn khuyên Emma nên trực tiếp tìm gặp Jamie để làm rõ ngọn ngành câu chuyện. Hôm sau đi học về, Emma hớn hở chạy ra khoác tay mẹ kể lể: Jamie cáu kỉnh ngày hôm qua là có nguyên nhân cả đấy mẹ ạ. Cậu ấy vô tình bị mép giấy cứa rách lưỡi trong lúc liếm mép phong bì nên mới đau đớn và trút giận cáu bẳn lên tất cả mọi người — đặc biệt là với cô bạn thân nhất của mình. Nghe xong, nụ cười rạng rỡ lại bừng sáng trên gương mặt Emma." }
    ]
  },
  {
    "day": 10,
    "title": "Ban Ban",
    image: "04 April/images/day_10.webp",
    audio: "04 April/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "Ban Ban is a little dog who lives with my grandpa. A friend from the city sent her to Grandpa's farm when she was only one year old.", "ipa": "/bæn bæn ɪz a ˈlɪtl dɔːɡ huː lɪvz wɪð maɪ ˈɡrændpɑː. a frɛnd frɒm ðə ˈsɪti sɛnt hɜːr tuː ˈɡrændpɑːz fɑːrm wɛn ʃiː wɒz ˈoʊnli wʌn jɪər oʊld/", vi: "Ban Ban là một cô chó nhỏ đáng yêu đang bầu bạn cùng ông ngoại tôi. Hồi tròn một tuổi, một người bạn trên thành phố đã gửi tặng cô chó này về cho trang trại của ông." },
      { "start": 13.0, "en": "Since then, life has changed completely for her. Ban Ban is no longer a pet. She is a farm animal. No one gives her daily baths anymore. Every day, she waits at the dinner table, and she eats whatever Grandpa gives her from his plate. No expensive dog food, not anymore.", "ipa": "/sɪns ðɛn, laɪf hæz tʃeɪndʒd kəmˈpliːtli fɔːr hɜːr. bæn bæn ɪz noʊ ˈlɔːŋɡər a pɛt. ʃiː ɪz a fɑːrm ˈænɪml. noʊ wʌn ɡɪvz hɜːr ˈdeɪli bæðz ˈɛniˌmɔːr. ˈɛvri deɪ, ʃiː weɪts æt ðə ˈdɪnər ˈteɪbl, ænd ʃiː iːts wɒtˈɛvər ˈɡrændpɑː ɡɪvz hɜːr frɒm hɪz pleɪt. noʊ ɪkˈspɛnsɪv dɔːɡ fuːd, nɒt ˈɛniˌmɔːr/", vi: "Kể từ dạo đó, cuộc đời của Ban Ban đã sang trang hoàn toàn. Cô không còn được cưng chiều như một chú thú cưng thành phố nữa mà chính thức trở thành một 'cô nhân viên' nhà nông thực thụ. Chẳng còn ai tắm táp thơm tho hằng ngày cho cô; mỗi bữa cơm cô đều ngoan ngoãn chầu chực bên bàn ăn và ăn bất cứ thứ gì ông ngoại gắp sẻ từ đĩa của ông, chứ lấy đâu ra hạt thức ăn chó đắt đỏ hạng sang nữa." },
      { "start": 33.0, "en": "Ban Ban now sleeps outside rather than in a warm bed in an apartment. She protects Grandpa's home. She barks when strangers come to the door. She is a working dog now.", "ipa": "/bæn bæn naʊ sliːps ˈaʊtˌsaɪd ˈræðər ðæn ɪn a wɔːrm bɛd ɪn ən əˈpɑːrtmənt. ʃiː prəˈtɛkts ˈɡrændpɑːz hoʊm. ʃiː bɑːrks wɛn ˈstreɪndʒərz kʌm tuː ðə dɔːr. ʃiː ɪz a ˈwɜːrkɪŋ dɔːɡ naʊ/", vi: "Ban Ban giờ đây quen với việc ngủ sương gió ngoài hiên nhà thay vì nằm cuộn tròn trên chiếc đệm êm ấm trong căn hộ chung cư. Cô gánh vác trọng trách canh giữ bình yên cho trang trại của ông, dõng dạc sủa vang mỗi khi có người lạ bén mảng tới gần. Cô đã thực sự là một chú chó lao động thực thụ." },
      { "start": 47.0, "en": "But Ban Ban seems happy. She has space to run and play. In the vegetable fields, she chases birds and frogs. She plays with the snails. Now, she also has new dog friends in her neighbourhood. One year later, Ban Ban gives birth to seven little puppies.", "ipa": "/bʌt bæn bæn siːmz ˈhæpi. ʃiː hæz speɪs tuː rʌn ænd pleɪ. ɪn ðə ˈvɛdʒtəbl fiːldz, ʃiː ˈtʃeɪsɪz bɜːrdz ænd frɒɡz. ʃiː pleɪz wɪð ðə sneɪlz. naʊ, ʃiː ˈɔːlsoʊ hæz nuː dɔːɡ frɛndz ɪn hɜːr ˈneɪbərˌhʊd. wʌn jɪər ˈleɪtər, bæn bæn ɡɪvz bɜːrθ tuː ˈsɛvn ˈlɪtl ˈpʌpiz/", vi: "Dù vậy, Ban Ban trông vô cùng hạnh phúc và thỏa mãn. Cô có khoảng không gian mênh mông để tự do chạy nhảy thỏa thích. Giữa những luống rau xanh mướt, cô rượt đuổi chim chóc, bắt ếch nhái và chơi đùa cùng đám ốc sên. Chưa hết, cô còn kết thân với nhiều bạn chó hàng xóm tốt bụng khác. Chỉ một năm sau đó, Ban Ban đã hạ sinh một đàn cún con xinh xắn gồm bảy thành viên." }
    ]
  },
  {
    "day": 11,
    "title": "Smoke Detectors",
    image: "04 April/images/day_11.webp",
    audio: "04 April/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "Fire is dangerous. House fires kill many people. But there is something you can do about them. Get a smoke detector.", "ipa": "/ˈfaɪər ɪz ˈdeɪndʒərəs. haʊs ˈfaɪərz kɪl ˈmɛni ˈpiːpl. bʌt ðɛr ɪz ˈsʌmθɪŋ juː kæn duː əˈbaʊt ðɛm. ɡɛt a smoʊk dɪˈtɛktər/", vi: "Hỏa hoạn là một hiểm họa vô cùng đáng sợ. Những vụ cháy nhà cướp đi sinh mạng của biết bao người. Tuy nhiên bạn hoàn toàn có thể chủ động phòng ngừa bằng cách trang bị thiết bị báo khói." },
      { "start": 13.0, "en": "Smoke detectors save lives. How? They tell you to get out of a burning house.", "ipa": "/smoʊk dɪˈtɛktərz seɪv laɪvz. haʊ? ðeɪ tɛl juː tuː ɡɛt aʊt əv a ˈbɜːrnɪŋ haʊs/", vi: "Thiết bị báo khói chính là vị cứu tinh cướp lại mạng sống con người. Bằng cách nào ư? Chúng phát tín hiệu khẩn cấp cảnh báo bạn nhanh chóng tháo chạy khỏi ngôi nhà đang bốc cháy." },
      { "start": 21.0, "en": "Many house fires happen at night when people are sleeping. A fire starts slowly. First there is smoke... a lot of smoke. It's actually the smoke that kills most people, not the fire itself.", "ipa": "/ˈmɛni haʊs ˈfaɪərz ˈhæpən æt naɪt wɛn ˈpiːpl ɑːr ˈsliːpɪŋ. a ˈfaɪər stɑːrts ˈsloʊli. fɜːrst ðɛr ɪz smoʊk... a lɒt əv smoʊk. ɪts ˈæktʃuəli ðə smoʊk ðæt kɪlz moʊst ˈpiːpl, nɒt ðə ˈfaɪər ɪtˈsɛlf/", vi: "Phần lớn các vụ hỏa hoạn nhà dân thường xảy ra vào ban đêm khi mọi người đang say ngủ. Ngọn lửa thường bùng phát âm ỉ từ từ: Ban đầu chỉ là làn khói... rồi sau đó là cuồn cuộn khói độc. Trên thực tế, chính khói ngạt mới là thủ phạm tước đoạt sinh mạng của phần lớn nạn nhân chứ không phải ngọn lửa trực tiếp." },
      { "start": 37.0, "en": "A smoke detector gives you an early warning about a fire. It makes a very loud noise when there is smoke. It wakes you up so you can get out of the house. That's how smoke detectors work.", "ipa": "/a smoʊk dɪˈtɛktər ɡɪvz juː ən ˈɜːrli ˈwɔːrnɪŋ əˈbaʊt a ˈfaɪər. ɪt meɪks a ˈvɛri laʊd nɔɪz wɛn ðɛr ɪz smoʊk. ɪt weɪks juː ʌp soʊ juː kæn ɡɛt aʊt əv ðə haʊs. ðæts haʊ smoʊk dɪˈtɛktərz wɜːrk/", vi: "Cảm biến khói sẽ phát hiện và đưa ra cảnh báo sớm từ những giây phút đầu tiên. Thiết bị sẽ hú còi với âm lượng cực lớn ngay khi nhận diện có khói bốc lên, đánh thức bạn dậy kịp thời để tẩu thoát ra ngoài. Đó chính là cách mà thiết bị báo khói vận hành." },
      { "start": 54.0, "en": "If you have a plan, you will know what to do. The most important thing is to get out of the house. Ask your parents to get a smoke detector. Ask them to practise what they would do if there is a fire.", "ipa": "/ɪf juː hæv a plæn, juː wɪl noʊ wɒt tuː duː. ðə moʊst ɪmˈpɔːrtənt θɪŋ ɪz tuː ɡɛt aʊt əv ðə haʊs. ɑːsk jɔːr ˈpɛrənts tuː ɡɛt a smoʊk dɪˈtɛktər. ɑːsk ðɛm tuː ˈpræktɪs wɒt ðeɪ wʊd duː ɪf ðɛr ɪz a ˈfaɪər/", vi: "Nếu chuẩn bị sẵn một kế hoạch ứng phó, bạn sẽ không bị hoảng loạn và biết chính xác phải làm gì. Ưu tiên hàng đầu luôn là thoát thân an toàn khỏi ngôi nhà. Hãy nhờ bố mẹ trang bị ngay thiết bị báo khói và cùng nhau tập dượt các phương án di tản khẩn cấp nếu không may xảy ra cháy nổ." }
    ]
  },
  {
    "day": 12,
    "title": "The Mouse and the Lion",
    image: "04 April/images/day_12.webp",
    audio: "04 April/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "Some days I feel like a mouse. Other days I feel like a lion. Do you know what I mean?", "ipa": "/sʌm deɪz aɪ fiːl laɪk a maʊs. ˈʌðər deɪz aɪ fiːl laɪk a ˈlaɪən. duː juː noʊ wɒt aɪ miːn?/", vi: "Có những ngày tôi cảm thấy mình yếu đuối hèn nhát tựa một chú chuột nhắt, nhưng cũng có lúc lại mạnh mẽ oai phong như một vị chúa sơn lâm thực thụ. Các bạn có hiểu ý tôi muốn nói gì không?" },
      { "start": 12.0, "en": "Some days I feel like I can do anything. I can lift anything, run anywhere and talk to anyone... without any fear.", "ipa": "/sʌm deɪz aɪ fiːl laɪk aɪ kæn duː ˈɛniˌθɪŋ. aɪ kæn lɪft ˈɛniˌθɪŋ, rʌn ˈɛniˌwɛr ænd tɔːk tuː ˈɛniˌwʌn... wɪˈðaʊt ˈɛni fɪər/", vi: "Vào những ngày 'hóa sư tử', tôi cảm thấy mình có thể làm bất cứ chuyện gì trên đời: nhấc bổng mọi vật, chạy băng băng đến mọi nơi và đối thoại tự tin với bất kỳ ai mà chẳng chút sợ hãi." },
      { "start": 21.0, "en": "But some days, I feel small and quiet. Maybe even a little scared of everything that is around me.", "ipa": "/bʌt sʌm deɪz, aɪ fiːl smɔːl ænd ˈkwaɪət. ˈmeɪbi ˈiːvn a ˈlɪtl skɛrd əv ˈɛvriˌθɪŋ ðæt ɪz əˈraʊnd miː/", vi: "Nhưng ngược lại, có những ngày tôi lại thấy mình thật bé nhỏ và thu mình lặng lẽ, thậm chí còn đâm ra sợ sệt mọi thứ xung quanh." },
      { "start": 29.0, "en": "I thought I was the only person who felt these ups and downs. But one day, I talked to the principal in the schoolyard. She said, 'I know what you mean.'", "ipa": "/aɪ θɔːt aɪ wɒz ði ˈoʊnli ˈpɜːrsn huː fɛlt ðiːz ʌps ænd daʊnz. bʌt wʌn deɪ, aɪ tɔːkt tuː ðə ˈprɪnsɪpəl ɪn ðə ˈskuːlˌjɑːrd. ʃiː sɛd, aɪ noʊ wɒt juː miːn/", vi: "Tôi từng ngỡ rằng chỉ có mỗi bản thân mình mới trải qua những trạng thái tâm lý thất thường lên xuống thất thường đó. Thế rồi trong một lần trò chuyện với cô hiệu trưởng ở sân trường, cô mỉm cười bảo: 'Cô hiểu rõ cảm giác của cháu mà.'" },
      { "start": 43.0, "en": "I couldn't believe it! Our principal always seems so strong and happy. She talks to the whole school and everyone listens.", "ipa": "/aɪ ˈkʊdnt bɪˈliːv ɪt! ˈaʊər ˈprɪnsɪpəl ˈɔːlweɪz siːmz soʊ strɒŋ ænd ˈhæpi. ʃiː tɔːks tuː ðə hoʊl skuːl ænd ˈɛvriˌwʌn ˈlɪsnz/", vi: "Tôi kinh ngạc đến mức á khẩu! Cô hiệu trưởng trong mắt chúng tôi luôn là một người vô cùng bản lĩnh, vui vẻ và uy quyền — mỗi lần cô đứng lên phát biểu trước toàn trường là tất cả học sinh đều im lặng lắng nghe." },
      { "start": 53.0, "en": "She taught me a little trick. Now, whenever I feel a little unsure of myself, I do this little thing in my head. Promise not to laugh if I tell you? I roar!", "ipa": "/ʃiː tɔːt miː a ˈlɪtl trɪk. naʊ, wɛnˈɛvər aɪ fiːl a ˈlɪtl ʌnˈʃʊr əv maɪˈsɛlf, aɪ duː ðɪs ˈlɪtl θɪŋ ɪn maɪ hɛd. ˈprɒmɪs nɒt tuː lɑːf ɪf aɪ tɛl juː? aɪ rɔːr!/", vi: "Cô đã bật mí cho tôi một mẹo nhỏ tuyệt hay. Giờ đây, mỗi khi cảm thấy thiếu tự tin hay chùn bước, tôi lại tự nhủ thực hiện một bí kíp trong tâm trí. Hứa với tôi là không được cười chê nhé? Ấy là tôi... gầm lên dõng dạc như một con sư tử thực thụ!" }
    ]
  },
  {
    "day": 14,
    "title": "A Tree",
    image: "04 April/images/day_14.webp",
    audio: "04 April/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "There was a little tree growing on the vacant lot near Mr. Smith's house. Every day, Mr. Smith would see this tree on his way to work.", "ipa": "/ðɛr wɒz a ˈlɪtl triː ˈɡroʊɪŋ ɒn ðə ˈveɪkənt lɒt nɪər ˈmɪstər smɪθs haʊs. ˈɛvri deɪ, ˈmɪstər smɪθ wʊd siː ðɪs triː ɒn hɪz weɪ tuː wɜːrk/", vi: "Có một mầm cây nhỏ xíu đang ngoan cường sinh trưởng trên mảnh đất trống ngay cạnh nhà ông Smith. Mỗi ngày trên đường đi làm qua đây, ông Smith đều dừng lại ngắm nhìn cây con ấy." },
      { "start": 13.0, "en": "'Some day, you will be big and give people shade,' Mr. Smith said.", "ipa": "/sʌm deɪ, juː wɪl biː bɪɡ ænd ɡɪv ˈpiːpl ʃeɪd, ˈmɪstər smɪθ sɛd/", vi: "'Rồi một ngày nào đó, mày sẽ vươn mình thành cổ thụ to lớn để tỏa bóng râm mát cho mọi người,' ông Smith thì thầm với cây." },
      { "start": 21.0, "en": "Then one day, Mr. Smith saw a man with an axe standing near the tree. 'Please don't cut it down,' called Mr. Smith.", "ipa": "/ðɛn wʌn deɪ, ˈmɪstər smɪθ sɔː a mæn wɪð ən æks ˈstændɪŋ nɪər ðə triː. pliːz doʊnt kʌt ɪt daʊn, kɔːld ˈmɪstər smɪθ/", vi: "Thế rồi vào một ngày nọ, ông Smith hốt hoảng khi thấy một người đàn ông cầm rìu sắc lẹm đang đứng đăm đăm ngay sát gốc cây. 'Xin anh đừng chặt nó đi,' ông Smith vội vàng gọi lớn." },
      { "start": 32.0, "en": "'This is my land. I want to build a house here,' said Mr. Brown. 'This tree is in the way.'", "ipa": "/ðɪs ɪz maɪ lænd. aɪ wɒnt tuː bɪld a haʊs hɪər, sɛd ˈmɪstər braʊn. ðɪs triː ɪz ɪn ðə weɪ/", vi: "'Đây là mảnh đất thuộc sở hữu của tôi và tôi định dựng nhà ở đây,' người đàn ông tên Brown lạnh lùng đáp. 'Cái cây này đang vướng víu lối đi quá.'" },
      { "start": 42.0, "en": "'But it is such a nice tree,' said Mr. Smith. 'May I dig it up and put it in my yard?'", "ipa": "/bʌt ɪt ɪz sʌtʃ a naɪs triː, sɛd ˈmɪstər smɪθ. meɪ aɪ dɪɡ ɪt ʌp ænd pʊt ɪt ɪn maɪ jɑːrd?/", vi: "'Nhưng nó là một cái cây rất đáng yêu và kiên cường,' ông Smith nài nỉ. 'Anh có phiền không nếu tôi xin phép đánh bứng gốc nó mang về trồng ở sân nhà mình?'" },
      { "start": 52.0, "en": "'Yes,' said Mr. Brown. 'I would be glad to have somebody take it.' Mr. Smith got a shovel. Together, he and Mr. Brown dug up the tree and planted it in Mr. Smith's yard.", "ipa": "/jɛs, sɛd ˈmɪstər braʊn. aɪ wʊd biː ɡlæd tuː hæv ˈsʌmbədi teɪk ɪt. ˈmɪstər smɪθ ɡɒt a ˈʃʌvl. təˈɡɛðər, hiː ænd ˈmɪstər braʊn dʌɡ ʌp ðə triː ænd ˈplɑːntɪd ɪt ɪn ˈmɪstər smɪθs jɑːrd/", vi: "'Được thôi,' ông Brown vui vẻ nhận lời. 'Tôi lại mừng quá vì có người đến dọn hộ.' Lập tức ông Smith chạy đi lấy xẻng. Hai người cùng chung sức cẩn thận bứng gốc cây mang về vun trồng ngay ngắn trong khoảng sân nhà ông Smith." },
      { "start": 69.0, "en": "Mr. Smith was happy. Mr. Brown was happy too. And you know what? I think, just maybe, the tree was happy as well.", "ipa": "/ˈmɪstər smɪθ wɒz ˈhæpi. ˈmɪstər braʊn wɒz ˈhæpi tuː. ænd juː noʊ wɒt? aɪ θɪŋk, dʒʌst ˈmeɪbi, ðə triː wɒz ˈhæpi æz wɛl/", vi: "Ông Smith mãn nguyện, ông Brown cũng vui vẻ. Và bạn biết không? Tôi tin chắc rằng, có lẽ ngay cả chú cây xanh nhỏ bé kia cũng đang vô cùng hạnh phúc." }
    ]
  },
  {
    "day": 15,
    "title": "The Big Guy",
    image: "04 April/images/day_15.webp",
    audio: "04 April/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "Have you ever been told that you are too short or too tall? Well, don't worry. Everyone is short compared to one man who was born in the United States in 1918.", "ipa": "/hæv juː ˈɛvər biːn toʊld ðæt juː ɑːr tuː ʃɔːrt ɔːr tuː tɔːl? wɛl, doʊnt ˈwʌri. ˈɛvriˌwʌn ɪz ʃɔːrt kəmˈpɛrd tuː wʌn mæn huː wɒz bɔːrn ɪn ðə jʊˈnaɪtɪd steɪts ɪn ˈnaɪˈtiːn ˈeɪti-eɪt/", vi: "Đã bao giờ bạn bị ai đó trêu chọc là quá lùn hay quá cao chưa? Đừng bận tâm làm gì nhé, bởi vì tất cả chúng ta đều trở nên 'bé hạt tiêu' khi đặt lên bàn cân so sánh với một người đàn ông đặc biệt sinh ra tại Mỹ vào năm 1918." },
      { "start": 16.0, "en": "His name was Robert Wadlow. He was the tallest person ever. He was 2.72 metres tall!", "ipa": "/hɪz neɪm wɒz ˈrɑːbərt ˈwɒdˌloʊ. hiː wɒz ðə ˈtɔːlɪst ˈpɜːrsn ˈɛvər. hiː wɒz ˈtuː pɪnt ˈsɛvn-ti-tuː ˈmiːtərz tɔːl/", vi: "Cụ ông ấy tên là Robert Wadlow — người giữ kỷ lục là con người cao nhất trong lịch sử nhân loại với chiều cao kinh hoàng lên tới 2,72 mét!" },
      { "start": 26.0, "en": "Life was hard for Robert. When he died at age twenty-two, he was still growing! Today, the tallest person alive is Bao Xishun. He is 2.47 metres tall!", "ipa": "/laɪf wɒz hɑːrd fɔːr ˈrɑːbərt. wɛn hiː daɪd æt eɪdʒ ˈtwɛnti-tuː, hiː wɒz stɪl ˈɡroʊɪŋ! təˈdeɪ, ðə ˈtɔːlɪst ˈpɜːrsn əˈlaɪv ɪz baʊ ˈʃɪˌʃʊn. hiː ɪz ˈtuː pɪnt fɔːr-sɛvn ˈmiːtərz tɔːl/", vi: "Cuộc sống của Robert gặp vô vàn nỗi bất tiện. Khi qua đời ở tuổi 22, cơ thể ông thậm chí vẫn đang tiếp tục phát triển cao thêm! Ngày nay, người đàn ông cao nhất thế giới còn sống là ông Bao Xishun với chiều cao 2,47 mét." },
      { "start": 43.0, "en": "Bao is a herdsman from Inner Mongolia, China. He is very famous all around the world. But Bao Xishun is very shy and leads a simple life. His friends call him Xi Shun or 'The Big Guy'. It's easy to see why!", "ipa": "/baʊ ɪz a ˈhɜːrdzmən frɒm ˈɪnər mɒŋˈɡoʊliə, ˈtʃaɪnə. hiː ɪz ˈvɛri ˈfeɪməs ɔːl əv ˈraʊnd ðə wɜːrld. bʌt baʊ ˈʃɪˌʃʊn ɪz ˈvɛri ʃaɪ ænd liːdz a ˈsɪmpl laɪf. hɪz frɛndz kɔːl hɪm ʃiː ʃʊn ɔːr ðə bɪɡ ɡaɪ. ɪts ˈiːzi tuː siː waɪ!/", vi: "Ông Bao là một người du mục chăn gia súc đến từ Nội Mông, Trung Quốc. Dù nổi tiếng toàn cầu nhưng ông lại rất rụt rè, mộc mạc và chọn lối sống bình dị. Bạn bè thân thiết thường gọi ông là Xi Shun hoặc thân mật là 'The Big Guy' (Anh chàng khổng lồ). Quá dễ hiểu vì sao lại có biệt danh ấy phải không nào!" }
    ]
  },
  {
    "day": 16,
    "title": "I Cannot Tell a Lie",
    image: "04 April/images/day_16.webp",
    audio: "04 April/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "When George was six years old, his father gave him an axe. George chopped many things with his shiny new axe.", "ipa": "/wɛn dʒɔːrdʒ wɒz sɪks jɪərz oʊld, hɪz ˈfɑːðər ɡeɪv hɪm ən æks. dʒɔːrdʒ tʃɒpt ˈmɛni θɪŋz wɪð hɪz ˈʃaɪni nuː æks/", vi: "Hồi còn lên sáu tuổi, George được bố tặng cho một chiếc rìu nhỏ. Cậu nhóc hào hứng dùng chiếc rìu mới sáng loáng đi chặt phá lung tung khắp vườn." },
      { "start": 13.0, "en": "In his family's backyard was his father's favourite tree. One day, young George cut down the tree. Soon after, his father saw the poor dead tree. He was sad and also very angry.", "ipa": "/ɪn hɪz ˈfæməlɪz ˈbækˌjɑːrd wɒz hɪz ˈfɑːðərz ˈfeɪvərɪt triː. wʌn deɪ, jʌŋ dʒɔːrdʒ kʌt daʊn ðə triː. suːn ˈɑːftər, hɪz ˈfɑːðər sɔː ðə pʊr dɛd triː. hiː wɒz sæd ænd ˈɔːlsoʊ ˈvɛri ˈæŋɡri/", vi: "Ngay khu vườn sau nhà có một cây anh đào vốn là giống cây cảnh cưng chiều nhất của bố. Một hôm, George nghịch ngợm đốn hạ luôn cả cây anh đào ấy. Chẳng lâu sau, người bố phát hiện ra cái cây xấu số đã chết khô, ông vô cùng đau xót và nổi trận lôi đình." },
      { "start": 29.0, "en": "He called his son and asked, 'Do you know what happened to my cherry tree?' George was frightened. He thought about telling a lie. But he changed his mind and cried, 'It was I, Father. It was I who cut down your cherry tree!'", "ipa": "/hiː kɔːld hɪz sʌn ænd ɑːskt, duː juː noʊ wɒt ˈhæpənd tuː maɪ ˈtʃɛri triː? dʒɔːrdʒ wɒz ˈfraɪtnd. hiː θɔːt əˈbaʊt ˈtɛlɪŋ a laɪ. bʌt hiː tʃeɪndʒd hɪz maɪnd ænd kraɪd, ɪt wɒz aɪ, ˈfɑːðər. ɪt wɒz aɪ huː kʌt daʊn jɔːr ˈtʃɛri triː!/", vi: "Bố gọi giật con trai ra và hầm hầm hỏi: 'Con có biết ai đã phá hoại cây anh đào của bố không?' George sợ đến tái mặt, định bụng sẽ mở miệng nói dối để chối tội. Nhưng rồi nghĩ lại, cậu nuốt nước mắt dũng cảm thú nhận: 'Chính con thưa bố. Con là người đã đốn ngã cây anh đào của bố đấy ạ!'" },
      { "start": 48.0, "en": "George's father looked kindly at him. He hugged the boy. 'I am very proud of you, George. You were frightened. But still, you told the truth. You are worth more to me than a thousand cherry trees.'", "ipa": "/ˈdʒɔːrdʒɪz ˈfɑːðər lʊkt ˈkaɪndli ænd hɪm. hiː hʌɡd ðə bɔɪ. aɪ æm ˈvɛri praʊd əv juː, dʒɔːrdʒ. juː wɜːr ˈfraɪtnd. bʌt stɪl, juː toʊld ðə truːθ. juː ɑːr wɜːrθ mɔːr tuː miː ðæn a ˈθaʊznd ˈtʃɛri triːz/", vi: "Khuôn mặt giận dữ của bố giãn ra, ông nhìn con trai với ánh mắt hiền từ rồi ôm chầm lấy cậu bé vào lòng. 'Bố vô cùng tự hào về con, George. Dù rất sợ hãi nhưng con vẫn can đảm nói lên sự thật. Sự trung thực của con đối với bố còn đáng giá hơn vạn cây anh đào.'" }
    ]
  },
  {
    "day": 17,
    "title": "Three Little Pigs (I)",
    image: "04 April/images/day_17.webp",
    audio: "04 April/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "Long ago, three pigs grew up and left their parents' home. They said goodbye to each other and went their separate ways.", "ipa": "/lɒŋ əˈɡoʊ, θriː pɪɡz ɡruː ʌp ænd lɛft ðɛr ˈpɛrənts hoʊm. ðeɪ sɛd ɡʊdˈbaɪ tuː iːtʃ ˈʌðər ænd wɛnt ðɛr ˈsɛpərət weɪz/", vi: "Ngày xửa ngày xưa, có ba chú heo con khôn lớn và quyết định rời khỏi vòng tay bố mẹ để tự lập. Chúng tạm biệt nhau rồi mỗi chú rẽ sang một ngả đường riêng." },
      { "start": 13.0, "en": "The youngest little pig was lazy and did not like to work. The middle pig did not mind working but always took the easy way. The oldest pig worked hard and always thought before doing something.", "ipa": "/ðə ˈjʌŋɡɪst ˈlɪtl pɪɡ wɒz ˈleɪzi ænd dɪd nɒt laɪk tuː wɜːrk. ðə ˈmɪdl pɪɡ dɪd nɒt maɪnd ˈwɜːrkɪŋ bʌt ˈɔːlweɪz tʊk ði ˈiːzi weɪ. ði ˈoʊldɪst pɪɡ wɜːrkt hɑːrd ænd ˈɔːlweɪz θɔːt bɪˈfɔːr ˈduːɪŋ ˈsʌmθɪŋ/", vi: "Chú heo út bản tính lười biếng, ghét lao động chân tay. Chú heo thứ hai không ngại việc nhưng lúc nào cũng thích chọn lối đi tắt dễ dãi. Còn chú heo cả thì cực kỳ chăm chỉ và luôn suy tính kỹ lưỡng trước khi hành động bất cứ việc gì." },
      { "start": 26.0, "en": "Each little pig thought about how to build a house. The youngest brother said, 'I will build my house with grass. It is light and easy to build with. It will make a nice home.'", "ipa": "/iːtʃ ˈlɪtl pɪɡ θɔːt əˈbaʊt haʊ tuː bɪld a haʊs. ðə ˈjʌŋɡɪst ˈbrʌðər sɛd, aɪ wɪl bɪld maɪ haʊs wɪð ɡræs. ɪt ɪz laɪt ænd ˈiːzi tuː bɪld wɪð. ɪt wɪl meɪk a naɪs hoʊm/", vi: "Mỗi chú heo đều tự lên ý tưởng xây dựng ngôi nhà riêng cho mình. Cậu út tuyên bố: 'Tớ sẽ cất nhà bằng cỏ khô. Vừa nhẹ nhàng lại dễ thi công, thế là thành một tổ ấm tuyệt vời rồi.'" },
      { "start": 39.0, "en": "His older brother said, 'Here are many small sticks. They are easy to work with. I will build my house out of sticks. That will make a good home.'", "ipa": "/hɪz ˈoʊldər ˈbrʌðər sɛd, hɪər ɑːr ˈmɛni smɔːl stɪks. ðeɪ ɑːr ˈiːzi tuː wɜːrk wɪð. aɪ wɪl bɪld maɪ haʊs aʊt əv stɪks. ðæt wɪl meɪk a ɡʊd hoʊm/", vi: "Anh hai lém lỉnh lên tiếng: 'Ngoài này có rất nhiều cành cây nhỏ, thao tác cũng rất nhanh gọn. Tớ sẽ dựng nhà bằng gỗ cành cây, như vậy chắc chắn sẽ kiên cố lắm đấy.'" },
      { "start": 50.0, "en": "Then, the oldest brother said, 'There are many dangers in this world. I must build a strong house using stones.' And soon, the three pigs built their houses. And for a while, everything was good.", "ipa": "/ðɛn, ði ˈoʊldɪst ˈbrʌðər sɛd, ðɛr ɑːr ˈmɛni ˈdeɪndʒərz ɪn ðɪs wɜːrld. aɪ mʌst bɪld a strɒŋ haʊs ˈjuːzɪŋ stoʊnz. ænd suːn, ðə θriː pɪɡz bɪlt ðɛr ˈhaʊsɪz. ænd fɔːr a waɪl, ˈɛvriˌθɪŋ wɒz ɡʊd/", vi: "Trong khi đó, chú heo cả trầm ngâm bảo: 'Thế giới ngoài kia rình rập biết bao hiểm nguy. Tớ phải xây một ngôi nhà thật vững chãi bằng đá.' Chẳng mấy chốc, cả ba chú heo đã hoàn thành xong những ngôi nhà của riêng mình, và trong một thời gian ngắn, mọi thứ đều vô cùng bình yên." }
    ]
  },
  {
    "day": 18,
    "title": "Three Little Pigs (II)",
    image: "04 April/images/day_18.webp",
    audio: "04 April/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, a big bad wolf came to town. He was hungry, VERY hungry. His favourite food was pig.", "ipa": "/wʌn deɪ, a bɪɡ bæd wʊlf keɪm tuː taʊn. hiː wɒz ˈhʌŋɡri, ˈvɛri ˈhʌŋɡri. hɪz ˈfeɪvərɪt fuːd wɒz pɪɡ/", vi: "Vào một ngày nọ, mụt mụ sói già gian ác đột nhiên xuất hiện trong vùng. Lão ta đang đói, ĐÓI CỒN CÀO, và món khoái khẩu nhất của lão chính là thịt lợn béo bở." },
      { "start": 13.0, "en": "He came to the grass house built by the first little pig. 'Come out, little pig. For I want to eat you!' roared the wolf. The little pig locked his door. But the wolf took a big breath and blew the grass house down. Then, he ate the little pig.", "ipa": "/hiː keɪm tuː ðə ɡræs haʊs bɪlt baɪ ðə fɜːrst ˈlɪtl pɪɡ. kʌm aʊt, ˈlɪtl pɪɡ. fɔːr aɪ wɒnt tuː iːt juː!, rɔːrd ðə wʊlf. ðə ˈlɪtl pɪɡ lɒkt hɪz dɔːr. bʌt ðə wʊlf tʊk a bɪɡ brɛθ ænd bluː ðə ɡræs haʊs daʊn. ðɛn, hiː eɪt ðə ˈlɪtl pɪɡ/", vi: "Lão tiến đến ngôi nhà cỏ của chú heo út và gầm lên: 'Hãy chui đầu ra đây mau, chú lợn con kia! Ta muốn ăn thịt ngươi!' Chú heo út hoảng hồn khóa chặt cửa ríu rít. Nhưng sói già hít một hơi căng tràn lồng ngực rồi thổi một phát bay tung ngôi nhà cỏ. Ngay lập tức, lão nuốt chửng chú heo út vào bụng." },
      { "start": 30.0, "en": "Next, the wolf came to the house made of sticks. 'Come out, little pig. For I want to eat you!' roared the wolf. The little pig locked his door and hid. But the big bad wolf blew and blew... and the house of sticks fell down. He ate the little pig.", "ipa": "/nɛkst, ðə wʊlf keɪm tuː ðə haʊs meɪd əv stɪks. kʌm aʊt, ˈlɪtl pɪɡ. fɔːr aɪ wɒnt tuː iːt juː!, rɔːrd ðə wʊlf. ðə ˈlɪtl pɪɡ lɒkt hɪz dɔːr ænd hɪd. bʌt ðə bɪɡ bæd wʊlf bluː ænd bluː... ænd ðə haʊs əv stɪks fɛl daʊn. hiː eɪt ðə ˈlɪtl pɪɡ/", vi: "Tiếp đó, sói già mò đến ngôi nhà bằng gỗ cành cây của anh hai và gầm thét đe dọa tương tự. Chú heo thứ hai khép chặt cửa trốn biệt tệt. Thế nhưng sói già cứ hì hục thổi lấy thổi để... và chẳng mấy chốc ngôi nhà gỗ cũng đổ sụp tan tành. Lão lại ăn thịt luôn chú heo thứ hai." },
      { "start": 48.0, "en": "When the wolf came to the stone house, he blew and blew. He could not blow the house down for it was strong. Finally, the wolf gave up and went away. The little pig with the stone house lived a long and happy life.", "ipa": "/wɛn ðə wʊlf keɪm tuː ðə stoʊn haʊs, hiː bluː ænd bluː. hiː kʊd nɒt bloʊ ðə haʊs daʊn fɔːr ɪt wɒz strɒŋ. ˈfaɪnəli, ðə wʊlf ɡeɪv ʌp ænd wɛnt əˈweɪ. ðə ˈlɪtl pɪɡ wɪð ðə stoʊn haʊs lɪvd a lɒŋ ænd ˈhæpi laɪf/", vi: "Khi lững thững kéo đến ngôi nhà đá của chú heo cả, sói già dốc sức thổi cạn sức lực nhưng ngôi nhà đá vẫn trơ trơ kiên cố chẳng hề suy chuyển. Cuối cùng, mụ sói đành kiệt sức bỏ cuộc và lủi thủi rút lui. Chú heo cả thông minh sống một cuộc đời bình yên và hạnh phúc dài lâu trong ngôi nhà đá vững chãi của mình." }
    ]
  },
  {
    "day": 19,
    "title": "My Favourite Colour",
    image: "04 April/images/day_19.webp",
    audio: "04 April/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "What colour do I like best? Well, it's red. Why? Red is a pretty colour. Many things are red. My sweater is red. I have a red jacket.", "ipa": "/wɒt ˈkʌlər duː aɪ laɪk bɛst? wɛl, ɪts rɛd. waɪ? rɛd ɪz a ˈprɪti ˈkʌlər. ˈmɛni θɪŋz ɑːr rɛd. maɪ ˈswɛtər ɪz rɛd. aɪ hæv a rɛd ˈdʒækɪt/", vi: "Màu sắc nào là chân ái của tôi ư? Đích thị là màu đỏ rực rỡ. Tại sao á? Vì màu đỏ quá đỗi xinh đẹp. Xung quanh chúng ta có vô vàn thứ mang sắc đỏ: Chiếc áo len tôi đang mặc màu đỏ, và tôi còn có cả một chiếc áo khoác đỏ nữa." },
      { "start": 15.0, "en": "Are there any foods that are red? Yes, there are. Tomatoes are red. Apples are red too. And so are strawberries. Are there any red plants? Yes. Some flowers are a nice pretty red.", "ipa": "/ɑːr ðɛr ˈɛni fuːdz ðæt ɑːr rɛd? jɛs, ðɛr ɑːr. təˈmɑːtoʊz ɑːr rɛd. ˈæplz ɑːr rɛd tuː. ænd soʊ ɑːr ˈstrɔːˌbɛriz. ɑːr ðɛr ˈɛni rɛd plænts? jɛs. sʌm ˈflaʊərz ɑːr a naɪs ˈprɪti rɛd/", vi: "Thế có món ăn nào màu đỏ không? Đương nhiên là có chứ. Cà chua màu đỏ, táo chín cũng đỏ, và cả những trái dâu tây ngọt ngào nữa. Thế thực vật có cây nào màu đỏ không? Có chứ, vô số loài hoa khoác lên mình sắc đỏ thắm tuyệt đẹp." },
      { "start": 28.0, "en": "Are there any red animals? Yes, some birds are red. They are easy to see. Ladybugs are red too. But they are very small and hard to find. Look around your house. You will find many things that are red. The colour red is everywhere. If you cut your finger the blood is red. Do not be afraid. Everyone has red blood. Red blood means that you are healthy. Red is a good colour. Do you like red?", "ipa": "/ɑːr ðɛr ˈɛni rɛd ˈænɪmlz? jɛs, sʌm bɜːrdz ɑːr rɛd. ðeɪ ɑːr ˈiːzi tuː siː. ˈleɪdiˌbʌɡz ɑːr rɛd tuː. bʌt ðeɪ ɑːr ˈvɛri smɔːl ænd hɑːrd tuː faɪnd. lʊk əˈraʊnd jɔːr haʊs. juː wɪl faɪnd ˈmɛni θɪŋz ðæt ɑːr rɛd. ðə ˈkʌlər rɛd ɪz ˈɛvriˌwɛr. ɪf juː kʌt jɔːr ˈfɪŋɡər ðə blʌd ɪz rɛd. doʊnt biː əˈfreɪd. ˈɛvriˌwʌn hæz rɛd blʌd. rɛd blʌd miːnz ðæt juː ɑːr ˈhɛlθi. rɛd ɪz a ɡʊd ˈkʌlər. duː juː laɪk rɛd?/", vi: "Động vật có loài nào màu đỏ không? Vài loài chim khoác bộ lông đỏ rực rất dễ nhận diện, hay những chú bọ rùa đỏ chấm đen tuy nhỏ bé khó tìm nhưng cực kỳ đáng yêu. Thử đảo mắt nhìn quanh nhà xem, bạn sẽ thấy vô số vật dụng mang sắc đỏ. Sắc đỏ hiện diện ở khắp mọi nơi. Thậm chí nếu không may đứt tay, giọt máu rỉ ra cũng có màu đỏ. Đừng sợ hãi nhé, ai cũng có máu đỏ cả, và dòng máu đỏ tươi chính là minh chứng cho cơ thể khỏe mạnh tràn đầy sức sống. Màu đỏ tuyệt vời lắm chứ bộ, bạn có mến màu đỏ không nào?" }
    ]
  },
  {
    "day": 20,
    "title": "The Lie That Grew and Grew",
    image: "04 April/images/day_20.webp",
    audio: "04 April/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Tom was very bored in class. So he threw a little ball at his friend Dan. Dan threw it back. They started throwing the ball back and forth.", "ipa": "/wʌn deɪ, tɒm wɒz ˈvɛri bɔːrd ɪn klæs. soʊ hiː θruː a ˈlɪtl bɔːl æt hɪz frɛnd dæn. dæn θruː ɪt bæk. ðeɪ ˈstɑːrtɪd ˈθroʊɪŋ ðə bɔːl bæk ænd fɔːrθ/", vi: "Vào một buổi học nọ, Tom cảm thấy buồn chán không có gì làm nên bèn vo viên một mẩu giấy nhỏ ném trêu cậu bạn Dan ngồi cạnh. Dan liền ném trả lại. Thế là cả hai hăng hái chơi trò chuyền bóng qua lại." },
      { "start": 13.0, "en": "One time, Tom threw it too high. Dan had to reach up to get it. By accident, he knocked a girl's glasses off the desk beside him. They fell and broke.", "ipa": "/wʌn taɪm, tɒm θruː ɪt tuː haɪ. dæn hæd tuː riːtʃ ʌp tuː ɡɛt ɪt. baɪ ˈæksədənt, hiː nɒkt a ɡɜːrlz ˈɡlæsɪz ɔːf ðə dɛsk bɪˈsaɪd hɪm. ðeɪ fɛl ænd broʊk/", vi: "Có một lần, Tom lỡ tay ném bóng quá cao khiến Dan phải rướn người với lấy. Do bất cẩn, tay cậu huơ trúng làm rơi chiếc kính cận của cô bạn ngồi bàn bên cạnh xuống đất vỡ tan tành." },
      { "start": 24.0, "en": "Very soon, the two boys were in the principal's office. Dan said they didn't do anything wrong. He blamed Tom. He kept lying and lying. And his face got redder and redder.", "ipa": "/ˈvɛri suːn, ðə tuː bɔɪz wɜːr ɪn ðə ˈprɪnsɪpəlz ˈɔːfɪs. dæn sɛd ðeɪ ˈdɪdnt duː ˈɛniˌθɪŋ rɒŋ. hiː bleɪmd tɒm. hiː kɛpt ˈlaɪɪŋ ænd ˈlaɪɪŋ. ænd hɪz feɪs ɡɒt ˈrɛdər ænd ˈrɛdər/", vi: "Chẳng mấy chốc, hai cậu nhóc đã bị mời lên văn phòng thầy hiệu trưởng. Trước mặt thầy, Dan một mực chối bay chối biến, trơ tráo đổ vạ hết mọi tội lỗi lên đầu Tom. Cậu ta cứ liên tiếp nói dối chồng chất, và khuôn mặt ngày càng đỏ lựng lên vì chột dạ." },
      { "start": 36.0, "en": "All of a sudden, he burst into tears. It seemed that Dan just couldn't tell any more lies. At the end, Tom and Dan had to pay for the girl's new glasses. They learned that lying just makes things worse.", "ipa": "/ɔːl əv a ˈsʌdn, hiː bɜːrst ˈɪntuː tɪərz. ɪt siːmd ðæt dæn dʒʌst ˈkʊdnt tɛl ˈɛni mɔːr laɪz. æt ði ɛnd, tɒm ænd dæn hæd tuː peɪ fɔːr ðə ɡɜːrlz nuː ˈɡlæsɪz. ðeɪ lɜːrnd ðæt ˈlaɪɪŋ dʒʌst meɪks θɪŋz wɜːrs/", vi: "Đột nhiên, cậu ta òa khóc nức nở không kìm chế được nữa. Hóa ra gánh nặng nói dối đã vượt quá sức chịu đựng khiến Dan không thể tiếp tục bịa chuyện thêm được nữa. Cuối cùng, cả Tom và Dan phải chịu phạt dùng tiền tiết kiệm đền bù chiếc kính mới cho cô bạn. Cả hai đã rút ra một bài học xương máu rằng thói nói dối chỉ làm mọi chuyện tồi tệ hơn mà thôi." }
    ]
  },
  {
    "day": 21,
    "title": "My Dog Ate It!",
    image: "04 April/images/day_21.webp",
    audio: "04 April/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day at school, we had a class project. Each student had to make a little house out of wooden sticks. But, instead of making my house, I talked to my friends for most of the class.", "ipa": "/wʌn deɪ æt skuːl, wiː hæd a klæs ˈprɑːdʒɛkt. iːtʃ ˈstuːdnt hæd tuː meɪk a ˈlɪtl haʊs aʊt əv ˈwʊdn stɪks. bʌt, ɪnˈstɛd əv ˈmeɪkɪŋ maɪ haʊs, aɪ tɔːkt tuː maɪ frɛndz fɔːr moʊst əv ðə klæs/", vi: "Vào một buổi học thủ công ở trường, cô giáo giao bài tập thực hành làm mô hình một ngôi nhà nhỏ từ những que gỗ. Thế nhưng thay vì cặm cụi làm bài, tôi lại mải bu chuyện với đám bạn suốt cả tiết học." },
      { "start": 16.0, "en": "The class ended, but I didn't finish my work. My teacher told me to take the sticks home and finish my house for homework.", "ipa": "/ðə klæs ˈɛndɪd, bʌt aɪ ˈdɪdnt ˈfɪnɪʃ maɪ wɜːrk. maɪ ˈtiːtʃər toʊld miː tuː teɪk ðə stɪks hoʊm ænd ˈfɪnɪʃ maɪ haʊs fɔːr ˈhoʊmˌwɜːrk/", vi: "Buổi học kết thúc mà sản phẩm của tôi vẫn hoàn toàn trống trơn. Cô giáo đành phạt tôi mang đống que gỗ về nhà và phải hoàn thành mô hình ngôi nhà như một bài tập về nhà." },
      { "start": 25.0, "en": "I took the sticks home. I glued them together to make a house. 'There! It's done.' I left my house in the corner of the room to dry.", "ipa": "/aɪ tʊk ðə stɪks hoʊm. aɪ ɡluːd ðɛm təˈɡɛðər tuː meɪk a haʊs. ðɛr! ɪts dʌn. aɪ lɛft maɪ haʊs ɪn ðə ˈkɔːrnər əv ðə ruːm tuː draɪ/", vi: "Về đến nhà, tôi hì hục dùng keo gắn kết các que gỗ lại với nhau thành hình ngôi nhà. 'Xong xuôi!' Tôi đặt tạm mô hình ở góc phòng cho keo dính khô hẳn." },
      { "start": 36.0, "en": "When I woke up the next morning, my stick house was broken into pieces! I was surprised and upset. I looked at the sticks. They had tooth marks on them. They were my dog's. My dog actually ate my homework!", "ipa": "/wɛn aɪ woʊk ʌp ðə nɛkst ˈmɔːrnɪŋ, maɪ stɪk haʊs wɒz ˈbroʊkən ˈɪntuː ˈpiːsɪz! aɪ wɒz sərˈpraɪzd ænd ʌpˈsɛt. aɪ lʊkt æt ðə stɪks. ðeɪ hæd tuːθ mɑːrks ɒn ðɛm. ðeɪ wɜːr maɪ dɒɡz. maɪ dɒɡ ˈæktʃuəli eɪt maɪ ˈhoʊmˌwɜːrk!/", vi: "Sáng hôm sau tỉnh dậy, hỡi ôi, ngôi nhà bằng gỗ xinh xắn đã bị ai đó phá nát bét thành từng mảnh vụn! Tôi tá hỏa bàng hoàng kiểm tra kỹ các thanh gỗ và phát hiện trên đó chi chít những vết răng cưa quen thuộc. Hóa ra thủ phạm chính là chú chó cưng nhà tôi. Chó cưng nhà tôi thực sự đã 'ăn' luôn cả bài tập về nhà!" },
      { "start": 54.0, "en": "I got zero out of ten on my stick house project.", "ipa": "/aɪ ɡɒt ˈzɪroʊ aʊt əv tɛn ɒn maɪ stɪk haʊs ˈprɑːdʒɛkt/", vi: "Và kết quả là tôi nhận ngay điểm không tròn trĩnh cho dự án mô hình nhà gỗ bất đắc dĩ ấy." }
    ]
  },
  {
    "day": 22,
    "title": "Be Yourself",
    image: "04 April/images/day_22.webp",
    audio: "04 April/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "Frank was a fish. He had a good fish life, but he wasn't happy with it. All day, he would sit and watch the birds in the air fly from tree to tree.", "ipa": "/fræŋk wɒz a fɪʃ. hiː hæd a ɡʊd fɪʃ laɪf, bʌt hiː ˈwɒznt ˈhæpi wɪð ɪt. ɔːl deɪ, hiː wʊd sɪt ænd wɒtʃ ðə bɜːrdz ɪn ði ɛr flaɪ frɒm triː tuː triː/", vi: "Frank là một chú cá nhỏ có cuộc sống bình yên dưới đáy sông, nhưng ngặt nỗi chú chẳng bao giờ cảm thấy thỏa mãn. Suốt cả ngày, chú chỉ tha thẩn ngồi ngước lên bầu trời ngắm những chú chim chao lượn bay lừng lững từ ngọn cây này sang cành cây khác." },
      { "start": 16.0, "en": "Frank wanted to be a bird, not a fish. Frank swam as fast as he could through the water and leaped into the air. He felt just like a flying bird until... he realized that he was having trouble breathing.", "ipa": "/fræŋk ˈwɒntɪd tuː biː a bɜːrd, nɒt a fɪʃ. fræŋk swæm æz fɑːst æz hiː kʊd θruː ðə ˈwɔːtər ænd liːpt ˈɪntuː ði ɛr. hiː fɛlt dʒʌst laɪk a ˈflaɪɪŋ bɜːrd ənˈtɪl... hiː ˈriːəlaɪzd ðæt hiː wɒz ˈhævɪŋ ˈtrʌbl ˈbriːðɪŋ/", vi: "Frank khao khát được làm chim trời chứ không thèm làm cá nước. Chú vùng vẫy bơi thật lực lấy đà rồi tung mình phóng vút lên không trung. Chú sung sướng ngỡ mình đang cất cánh bay lượn như chim thật, cho đến khi... cảm thấy lồng ngực bắt đầu ngạt thở vì thiếu nước." },
      { "start": 32.0, "en": "He landed back in the water just as he was gasping for his last breath. 'That was strange,' he thought. He jumped into the air again. But this time, he got caught in a low branch by the river. He was in a tree like a bird, but he couldn't breathe. He regretted trying to be a bird and struggled to wiggle free.", "ipa": "/hiː ˈlændɪd bæk ɪn ðə ˈwɔːtər dʒʌst æz hiː wɒz ˈɡæspɪŋ fɔːr hɪz lɑːst brɛθ. ðæt wɒz streɪndʒ, hiː θɔːt. hiː dʒʌmpt ˈɪntuː ði ɛr əˈɡɛn. bʌt ðɪs taɪm, hiː ɡɒt kɔːt ɪn a loʊ bræntʃ baɪ ðə ˈrɪvər. hiː wɒz ɪn a triː laɪk a bɜːrd, bʌt hiː ˈkʊdnt briːð. hiː rɪˈɡrɛtɪd ˈtraɪɪŋ tuː biː a bɜːrd ænd ˈstrʌɡld tuː ˈwɪɡl friː/", vi: "Chú rơi tõm trở lại dòng nước ngay khoảnh khắc ngộp thở sắp lịm đi. 'Lạ thật đấy,' chú ngẩn ngơ tự hỏi. Không nản chí, chú tiếp tục tung mình bay lên lần nữa. Lần này, xui xẻo thay chú vướng kẹt luôn vào cành cây thấp sà xuống mặt nước. Chú đã được ở trên cây y như chim trời mong ước, ngặt nỗi lại chẳng thể thở nổi. Frank vô cùng hối hận vì trò nghịch dại muốn làm chim và vẫy vùng tuyệt vọng tìm đường thoát thân." },
      { "start": 58.0, "en": "Plop! Frank landed back in the water. After a few minutes, he caught his breath. He swam straight home and vowed to be the best fish he could be.", "ipa": "/plɒp! fræŋk ˈlændɪd bæk ɪn ðə ˈwɔːtər. ˈɑːftər a fjuː ˈmɪnɪts, hiː kɔːt hɪz brɛθ. hiː swæm streɪt hoʊm ænd vaʊd tuː biː ðə bɛst fɪʃ hiː kʊd biː/", vi: "Tõm một tiếng! Frank rơi phịch trở lại dòng sông quen thuộc. Phải mất vài phút hít thở hổn hển chú mới hồi sức trở lại. Chú bơi một mạch thẳng về nhà và tự thề với lòng sẽ tu chí làm một chú cá xuất sắc nhất." }
    ]
  },
  {
    "day": 23,
    "title": "Global Warming",
    image: "04 April/images/day_23.webp",
    audio: "04 April/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "The North Pole and the South Pole of the earth are covered with ice. As long as the ice stays frozen, everything is okay. But what happens if this ice begins to melt?", "ipa": "/ðə nɔːrθ poʊl ænd ðə saʊθ poʊl əv ði ɜːrθ ɑːr ˈkʌvərd wɪð aɪs. æz lɒŋ æz ði aɪs steɪz ˈfroʊzn, ˈɛvriˌθɪŋ ɪz oʊˈkeɪ. bʌt wɒt ˈhæpənz ɪf ðɪs aɪs bɪˈɡɪnz tuː mɛlt?/", vi: "Cực Bắc và Cực Nam của Trái Đất vốn được bao phủ bởi những lớp băng tuyết vĩnh cửu. Chừng nào băng còn đóng băng cố định thì mọi hệ sinh thái vẫn duy trì ổn định. Nhưng điều gì sẽ xảy ra nếu khối băng khổng lồ ấy bắt đầu tan chảy?" },
      { "start": 16.0, "en": "Well, for one thing, the water in the world's oceans will rise. You might be thinking, 'So what?' But think a little harder.", "ipa": "/wɛl, fɔːr wʌn θɪŋ, ðə ˈwɔːtər ɪn ðə wɜːrlds ˈoʊʃnz wɪl raɪz. juː maɪt biː ˈθɪŋkɪŋ, soʊ wɒt?. bʌt θɪŋk a ˈlɪtl ˈhɑːrdər/", vi: "Trước hết, mực nước tại các đại dương trên toàn cầu sẽ dâng cao đáng kể. Bạn có thể bĩu môi nghĩ: 'Thì sao nào?' Nhưng hãy suy ngẫm sâu hơn một chút xem." },
      { "start": 25.0, "en": "A lot of people live near the oceans. If the ice in the north and south melts, many cities will be flooded. Millions of people will have to move away from the rising oceans.", "ipa": "/a lɒt əv ˈpiːpl lɪv nɪər ði ˈoʊʃnz. ɪf ði aɪs ɪn ðə nɔːrθ ænd saʊθ mɛlts, ˈmɛni ˈsɪtiz wɪl biː ˈflʌdɪd. ˈmɪljənz əv ˈpiːpl wɪð hæv tuː muːv əˈweɪ frɒm ðə ˈraɪzɪŋ ˈoʊʃnz/", vi: "Vô số cộng đồng dân cư sinh sống tập trung ở các vùng ven biển trũng thấp. Nếu băng ở hai đầu cực tan chảy, hàng loạt thành phố lớn sẽ chìm trong biển nước. Hàng triệu con người buộc phải tha hương di tản đi nơi khác để chạy trốn dòng nước biển dâng." },
      { "start": 41.0, "en": "But that's not all. As the ice melts, the oceans will become colder. Many plants and animals will not be able to adjust to the new water temperatures. Nature's balance will be upset.", "ipa": "/bʌt ðæts nɒt ɔːl. æz ði aɪs mɛlts, ði ˈoʊʃnz wɪl bɪˈkʌm ˈkoʊldər. ˈmɛni plænts ænd ˈænɪmlz wɪð nɒt biː ˈeɪbl tuː əˈdʒʌst tuː ðə nuː ˈwɔːtər ˈtɛmprətʃərz. ˈneɪtʃərz ˈbæləns wɪð biː ʌpˈsɛt/", vi: "Và thảm họa chưa dừng lại ở đó. Khi băng tan ồ ạt đổ xuống, nước biển sẽ trở nên lạnh buốt hơn. Rất nhiều loài động thực vật dưới nước không kịp thích nghi với nền nhiệt độ thay đổi đột ngột ấy, khiến sự cân bằng sinh thái tự nhiên bị phá vỡ nghiêm trọng." },
      { "start": 59.0, "en": "No one knows for sure if the ice in the poles will melt. But if it does, there will be many problems. Let's do something about it now, before it's too late.", "ipa": "/noʊ wʌn noʊz fɔːr ʃʊr ɪf ði aɪs ɪn ðə poʊlz wɪl mɛlt. bʌt ɪf ɪt dʌz, ðɛr wɪl biː ˈmɛni ˈprɒbləmz. lɛts duː ˈsʌmθɪŋ əˈbaʊt ɪt naʊ, bɪˈfɔːr ɪts tuː leɪt/", vi: "Dù chưa ai dám khẳng định chắc chắn 100% băng ở hai cực có tan chảy hoàn toàn hay không, nhưng nếu viễn cảnh đó xảy ra, hậu quả để lại sẽ vô cùng khủng khiếp. Ngay từ bây giờ, chúng ta hãy hành động thiết thực trước khi quá muộn." }
    ]
  },
  {
    "day": 24,
    "title": "The New Kid",
    image: "04 April/images/day_24.webp",
    audio: "04 April/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "Adam was the new kid at his school. One day, he was walking home alone. Suddenly, a boy came from behind and pushed Adam. Adam fell to the ground.", "ipa": "/ˈædəm wɒz ðə nuː kɪd æt hɪz skuːl. wʌn deɪ, hiː wɒz ˈwɔːkɪŋ hoʊm əˈloʊn. ˈsʌdənli, a bɔɪ keɪm frɒm bɪˈhaɪnd ænd pʊʃt ˈædəm. ˈædəm fɛl tuː ðə ɡraʊnd/", vi: "Adam là học sinh mới chuyển đến trường. Vào một buổi chiều nọ khi cậu đang lủi thủi đi bộ về nhà một mình, bất thình lình một nam sinh từ đằng sau lao tới xô ngã nhào xuống đất." },
      { "start": 16.0, "en": "The boy said, 'Give me your MP3 player, now!' 'No! It's mine,' Adam cried. Some boys from school saw this, but they did not stop to help. 'He is not our friend,' they said. 'Why should we help him?' They took another street.", "ipa": "/ðə bɔɪ sɛd, ɡɪv miː jɔːr ɛm-piː-θriː ˈpleɪər, naʊ! noʊ! ɪts maɪn, ˈædəm kraɪd. sʌm bɔɪz frɒm skuːl sɔː ðɪs, bʌt ðeɪ dɪd nɒt stɒp tuː hɛlp. hiː ɪz nɒt ˈaʊər frɛnd, ðeɪ sɛd. waɪ ʃʊd wiː hɛlp hɪm? ðeɪ tʊk əˈnʌðər striːt/", vi: "Kẻ côn đồ hách dịch đe dọa: 'Đưa máy nghe nhạc MP3 đây, nhanh lên!' 'Không đời nào! Đồ của tớ cơ mà,' Adam mếu máo van xin. Vài nam sinh đi ngang qua chứng kiến sự việc nhưng nhẫn tâm quay mặt đi chẳng thèm cứu giúp. 'Cậu ta có phải bạn bè gì của chúng ta đâu,' chúng xì xào. 'Việc gì phải dây dưa rắc rối.' Thế là chúng rẽ sang con phố khác để mặc Adam." },
      { "start": 35.0, "en": "Just then, Greg came over. He shouted to the boy, 'Hey! Stop it. You can't do this.' The boy looked at Greg angrily, then ran away. Greg pulled Adam up. He walked with Adam to his house. From that day on, they became good friends.", "ipa": "/dʒʌst ðɛn, ɡrɛɡ keɪm ˈoʊvər. hiː ˈʃaʊtɪd tuː ðə bɔɪ, heɪ! stɒp ɪt. juː kænt duː ðɪs. ðə bɔɪ lʊkt æt ɡrɛɡ ˈæŋɡrɪli, ðɛn ræn əˈweɪ. ɡrɛɡ pʊld ˈædəm ʌp. hiː wɔːkt wɪð ˈædəm tuː hɪz haʊs. frɒm ðæt deɪ ɒn, ðeɪ bɪˈkeɪm ɡʊd frɛndz/", vi: "Đúng lúc dầu sôi lửa bỏng đó, Greg chạy ào tới. Cậu quát thẳng vào mặt kẻ bắt nạt: 'Này! Dừng tay lại ngay. Mày không có quyền làm thế.' Tên côn đồ trừng mắt tức tối lườm Greg rồi hoảng hốt tháo chạy mất dạng. Greg ân cần đỡ Adam đứng dậy và sóng bước hộ tống cậu về tận nhà an toàn. Kể từ ngày hôm đó, hai cậu bé chính thức trở thành đôi bạn thân thiết keo sơn." }
    ]
  },
  {
    "day": 25,
    "title": "Will It Float?",
    image: "04 April/images/day_25.webp",
    audio: "04 April/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "This past winter, my family went on a vacation. It was a lot of fun. I was surprised to find that I could float with very little effort while swimming in the ocean.", "ipa": "/ðɪs pɑːst ˈwɪntər, maɪ ˈfæməli wɛnt ɒn a veɪˈkeɪʃn. ɪt wɒz a lɒt əv fʌn. aɪ wɒz sərˈpraɪzd tuː faɪnd ðæt aɪ kʊd floʊt wɪð ˈvɛri ˈlɪtl ˈɛfərt waɪl ˈswɪmɪŋ ɪn ði ˈoʊʃn/", vi: "Kỳ nghỉ đông vừa qua, gia đình tôi đã có một chuyến du lịch vô cùng vui vẻ. Điều khiến tôi ngạc nhiên thú vị là mình có thể dễ dàng nổi lềnh bềnh trên mặt nước biển mà chẳng tốn chút sức lực nào khi bơi lội." },
      { "start": 16.0, "en": "I asked my mom why. She said, 'Ocean water is salty. Things do not sink easily in salty water. Let's do an experiment.'", "ipa": "/aɪ ɑːskt maɪ mɒm waɪ. ʃiː sɛd, ˈoʊʃn ˈwɔːtər ɪz ˈsɔːlti. θɪŋz duː nɒt sɪŋk ˈiːzɪli ɪn ˈsɔːlti ˈwɔːtər. lɛts duː ən ɪkˈspɛrɪmənt/", vi: "Tôi tò mò quay sang hỏi mẹ lý do vì sao. Mẹ mỉm cười giải thích: 'Nước biển chứa lượng muối rất cao. Các vật thể khó mà chìm sâu trong môi trường nước mặn. Nào, để mẹ làm thí nghiệm chứng minh cho con xem.'" },
      { "start": 26.0, "en": "She got a glass and an egg. She filled the glass halfway with water. She put the egg in the glass. It sank to the bottom.", "ipa": "/ʃiː ɡɒt a glæs ænd ən ɛɡ. ʃiː fɪld ðə glæs ˈhæfˌweɪ wɪð ˈwɔːtər. ʃiː pʊt ði ɛɡ ɪn ðə glæs. ɪt sæŋk tuː ðə ˈbɑːtəm/", vi: "Mẹ chuẩn bị một chiếc cốc thủy tinh và một quả trứng gà. Mẹ đổ nước vào nửa cốc rồi thả quả trứng vào trong. Lập tức quả trứng chìm nghỉm xuống tận đáy cốc." },
      { "start": 37.0, "en": "'Now, let's add some salt,' she said. One teaspoon, two teaspoons... the egg started to rise a little. Three teaspoons... and it was floating in the water.", "ipa": "/naʊ, lɛts æd sʌm sɔːlt, ʃiː sɛd. wʌn ˈtiːˌspuːn, tuː ˈtiːˌspuːn... ði ɛɡ ˈstɑːrtɪd tuː raɪz a ˈlɪtl. θriː ˈtiːˌspuːn... ænd ɪt wɒz ˈfloʊtɪŋ ɪn ðə ˈwɔːtər/", vi: "'Bây giờ chúng ta sẽ cho thêm muối vào nhé,' mẹ nói. Một thìa muối, hai thìa muối... quả trứng bắt đầu nhích nổi lơ lửng lên một chút. Đến thìa muối thứ ba... và thế là quả trứng nổi bồng bềnh hoàn toàn trên mặt nước." },
      { "start": 51.0, "en": "'Salty water is heavy,' explained Mom. Things do not sink easily in salty water. Ocean water makes you float. That is why you can swim easily in the ocean. Still, you must be a good swimmer to swim in the ocean. And if you get water in your mouth, you can tell that it is really salty!", "ipa": "/ˈsɔːlti ˈwɔːtər ɪz ˈhɛvi, ɪkˈspleɪnd mɒm. θɪŋz duː nɒt sɪŋk ˈiːzɪli ɪn ˈsɔːlti ˈwɔːtər. ˈoʊʃn ˈwɔːtər meɪks juː floʊt. ðæt ɪz waɪ juː kæn swɪm ˈiːzɪli ɪn ði ˈoʊʃn. stɪl, juː mʌst biː a ɡʊd ˈswɪmər tuː swɪm ɪn ði ˈoʊʃn. ænd ɪf juː ɡɛt ˈwɔːtər ɪn jɔːr maʊθ, juː kæn tɛl ðæt ɪt ɪz ˈrɪəli ˈsɔːlti!/", vi: "'Nước muối có trọng lượng nặng hơn nước ngọt nên có sức nâng rất lớn,' mẹ giảng giải. 'Đó chính là lý do các vật thể khó chìm và con có thể thả lỏng cơ thể nổi lềnh bềnh khi bơi lội ngoài đại dương. Dù vậy, con vẫn cần phải bơi lội giỏi mới nên ra biển lớn nhé. Và hễ lỡ để nước biển lọt vào miệng, con sẽ thấy vị mặn chát đến nhăn mặt đấy!'" }
    ]
  },
  {
    "day": 26,
    "title": "How Land Came to Be",
    image: "04 April/images/day_26.webp",
    audio: "04 April/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "Long ago, the world had two parts. The first was the sky, where there were trees, plants of all kinds, mountains and beautiful fields of green grass. And people lived here. Below the sky was the water. This is where all the animals lived.", "ipa": "/lɒŋ əˈɡoʊ, ðə wɜːrld hæd tuː pɑːrts. ðə fɜːrst wɒz ðə skaɪ, wɛr ðɛr wɜːr triːz, plænts əv ɔːl kaɪndz, ˈmaʊntɪnz ænd ˈbjuːtɪfl fiːldz əv ɡriːn ɡræs. ænd ˈpiːpl lɪvd hɪər. bɪˈloʊ ðə skaɪ wɒz ðə ˈwɔːtər. ðɪs ɪz wɛr ɔːl ðə ˈænɪmlz lɪvd/", vi: "Thuở hồng hoang xa xưa, thế giới chỉ phân chia thành hai cõi rõ rệt: Phía trên là bầu trời bao la — nơi có muôn loài cây cỏ, núi non hùng vĩ và những thảo nguyên cỏ xanh mướt ngút ngàn là chốn sinh sống của loài người. Phía bên dưới bầu trời chính là đại dương mênh mông — nơi muôn loài thủy tộc trú ngụ." },
      { "start": 21.0, "en": "One day, a hole opened in the sky, and a girl began to fall towards the water below. The animals saw her falling. Two swans saved her life by catching her on their backs. But the animals didn't know what to do with this girl. They decided to ask the wise turtle for advice.", "ipa": "/wʌn deɪ, a hoʊl ˈoʊpənd ɪn ðə skaɪ, ænd a ɡɜːrl bɪˈɡæn tuː fɔːl təˈwɔːrdz ðə ˈwɔːtər bɪˈloʊ. ðə ˈænɪmlz sɔː hɜːr ˈfɔːlɪŋ. tuː swɑːnz seɪvd hɜːr laɪf baɪ ˈkætʃɪŋ hɜːr ɒn ðɛr bæks. bʌt ðə ˈænɪmlz ˈdɪdnt noʊ wɒt tuː duː wɪð ðɪs ɡɜːrl. ðeɪ dɪˈsaɪdɪd tuː ɑːsk ðə waɪz ˈtɜːrtl fɔːr ədˈvaɪs/", vi: "Đến một ngày nọ, một lỗ hổng đột ngột xuất hiện trên bầu trời khiến một cô gái không may trượt chân rơi ùm xuống vùng nước bên dưới. Đàn thú phát hiện có người rơi xuống liền hốt hoảng cứu giúp; hai chú thiên nga dũng cảm đã đỡ lấy cô gái trên tấm lưng rộng của mình. Tuy nhiên, muôn loài lại bối rối không biết nên xử trí ra sao với vị khách loài người này, nên chúng quyết định đến thỉnh kiến cụ Rùa thông thái." },
      { "start": 41.0, "en": "The wise turtle said, 'Deep below this water, there is soil. Dive down and bring some to me. Then, put it on my big back. The girl can live there.' A couple of frogs dove down and brought up some soil. The rest of the animals then planted seeds in the soil. The girl now had a good place to live. Over time, the soil on the huge turtle's back grew bigger and bigger. And that is how, today, we have water and land below the sky.", "ipa": "/ðə waɪz ˈtɜːrtl sɛd, diːp bɪˈloʊ ðɪs ˈwɔːtər, ðɛr ɪz sɔɪl. daɪv daʊn ænd brɪŋ sʌm tuː miː. ðɛn, pʊt ɪt ɒn maɪ bɪɡ bæk. ðə ɡɜːrl kæn lɪv ðɛr. a ˈkʌpl əv frɒɡz doʊv daʊn ænd brɔːt ʌp sʌm sɔɪl. ðə rɛst əv ðə ˈænɪmlz ðɛn ˈplɑːntɪd siːdz ɪn ðə sɔɪl. ðə ɡɜːrl naʊ hæd a ɡʊd pleɪs tuː lɪv. ˈoʊvər taɪm, ðə sɔɪl ɒn ðə hyudʒ ˈtɜːrtlz bæk ɡruː ˈbɪɡər ænd ˈbɪɡər. ænd ðæt ɪz haʊ, təˈdeɪ, wiː hæv ˈwɔːtər ænd lænd bɪˈloʊ ðə skaɪ/", vi: "Cụ Rùa điềm đạm phán rằng: 'Sâu thẳm dưới đáy đại dương kia có tồn tại đất đai. Hãy lặn xuống mang một ít đất lên đây rồi vun đắp lên tấm lưng rộng lớn của ta, cô gái ấy sẽ có chỗ an cư.' Vài chú ếch nhái nhanh nhẹn lặn sâu xuống ngụp lặn mang bùn đất lên. Muôn loài cùng chung tay gieo hạt gieo mầm trên lớp đất đó. Nhờ vậy cô gái đã có một mái nhà vững chắc để sinh sống. Qua năm tháng, lớp đất trên lưng cụ Rùa ngày một bồi đắp phình to rộng lớn ra. Và đó chính là sự tích hình thành nên các châu lục đất liền hòa cùng đại dương dưới bầu trời ngày nay." }
    ]
  },
  {
    "day": 27,
    "title": "Love of Dragons",
    image: "04 April/images/day_27.webp",
    audio: "04 April/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "Once there was a man named Lord Ye. He was well known for his love of dragons. Everywhere in his home, there were dragons. They were carved on his doors and windows, painted on his walls, and sewed on his clothes.", "ipa": "/wʌns ðɛr wɒz a mæn neɪmd lɔːrd jeɪ. hiː wɒz wɛl noʊn fɔːr hɪz lʌv əv ˈdræɡənz. ˈɛvriˌwɛr ɪn hɪz hoʊm, ðɛr wɜːr ˈdræɡənz. ðeɪ wɜːr kɑːrvd ɒn hɪz dɔːrz ænd ˈwɪndoʊz, ˈpeɪntɪd ɒn hɪz wɔːlz, ænd soʊd ɒn hɪz kloʊðz/", vi: "Thuở xưa có một vị quan nhà nho tên là Diệp Công (Lord Ye), nổi tiếng khắp chốn vì niềm đam mê cuồng nhiệt dành cho loài rồng. Khắp các ngóc ngách trong phủ của ông đâu đâu cũng thấy hình ảnh rồng: Rồng được chạm trổ tinh xảo trên cửa ra vào và khung cửa sổ, vẽ sơn phết lộng lẫy trên các bức tường, và thêu dệt tỉ mỉ trên từng bộ xiêm y ông mặc." },
      { "start": 19.0, "en": "Way up in the heavens, the Dragon King learned about this. He decided to go down to visit Lord Ye. Later, when Lord Ye was having his midday nap, a thunderstorm began.", "ipa": "/weɪ ʌp ɪn ðə ˈhɛvnz, ðə ˈdræɡən kɪŋ lɜːrnd əˈbaʊt ðɪs. hiː dɪˈsaɪdɪd tuː ɡoʊ daʊn tuː ˈvɪzɪt lɔːrd jeɪ. ˈleɪtər, wɛn lɔːrd jeɪ wɒz ˈhævɪŋ hɪz ˈmɪdˌdeɪ næp, a ˈθʌndərˌstɔːrm bɪˈɡæn/", vi: "Tận trên tầng mây cao thẳm cửu trùng, Long Vương hay tin liền vô cùng cảm động và quyết định thân chinh hạ phơi trần gian để đến thăm vị đại thần ái mộ loài rồng này. Đúng vào lúc Diệp Công đang nằm ngả lưng chợp mắt ngủ trưa, bỗng một trận cuồng phong sấm chớp dữ dội nổi lên." },
      { "start": 32.0, "en": "A huge dragon thrust his head through Lord Ye's window, his tail blocking the door and his eyes shining like lanterns.", "ipa": "/a hyudʒ ˈdræɡən θrʌst hɪz hɛd θruː lɔːrd jeɪz ˈwɪndoʊ, hɪz teɪl ˈblɒkɪŋ ðə dɔːr ænd hɪz aɪz ˈʃaɪnɪŋ laɪk ˈlæntərz/", vi: "Một chú rồng thần khổng lồ thò đầu uy nghiêm qua khung cửa sổ phủ xuống phòng ngủ của Diệp Công, chiếc đuôi cuồn cuộn dài ngoằng chặn nghẽn cửa ra vào cùng đôi mắt sáng rực rỡ tựa đèn lồng." },
      { "start": 41.0, "en": "Lord Ye was frightened. He hid under his bed. He covered his head with his hands and trembled with fear. He did not dare open his eyes.", "ipa": "/lɔːrd jeɪ wɒz ˈfraɪtnd. hiː hɪd ˈʌndər hɪz bɛd. hiː ˈkʌvərd hɪz hɛd wɪð hɪz hændz ænd ˈtrɛmbəld wɪð fɪər. hiː dɪd nɒt dɛr ˈoʊpən hɪz aɪz/", vi: "Nào ngờ Diệp Công nhìn thấy cảnh tượng ấy thì sợ mất mật, hoảng loạn chui tọt gầm giường trốn. Ông lấy hai tay ôm chặt đầu, run lẩy bẩy vì khiếp sợ và tuyệt đối không dám hé mắt nhìn dù chỉ nửa giây." },
      { "start": 53.0, "en": "The Dragon King was disappointed. He left, wondering why Lord Ye was so frightened by him. From then on, Lord Ye no longer claimed to love dragons.", "ipa": "/ðə ˈdræɡən kɪŋ wɒz ˌdɪsəˈpɔɪntɪd. hiː lɛft, ˈwʌndərɪŋ waɪ lɔːrd jeɪ wɒz soʊ ˈfraɪtnd baɪ hɪm. frɒm ðɛn ɒn, lɔːrd jeɪ noʊ ˈlɔːŋɡər kleɪmd tuː lʌv ˈdræɡənz/", vi: "Long Vương chưng hửng và vô cùng thất vọng, đành buồn bã quay gót bay về trời, tự hỏi không hiểu sao vị quan này lại sợ mình đến thế. Kể từ dạo đó, Diệp Công chừa hẳn thói huênh hoang tuyên bố yêu thích rồng." }
    ]
  },
  {
    "day": 28,
    "title": "A Special Treat",
    image: "04 April/images/day_28.webp",
    audio: "04 April/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "Everyone has a favourite treat. You may have one or many. Do you know what my special treat is? It's the Beaver Tail.", "ipa": "/ˈɛvriˌwʌn hæz a ˈfeɪvərɪt triːt. juː meɪ hæv wʌn ɔːr ˈmɛni. duː juː noʊ wɒt maɪ ˈspɛʃl triːt ɪz? ɪts ðə ˈbiːvər teɪl/", vi: "Ai trong chúng ta cũng đều có một món quà vặt khoái khẩu cho riêng mình. Bạn có tò mò món tráng miệng đặc biệt của tôi là gì không? Đó chính là món Bánh Đuôi Hải Ly (Beaver Tail)." },
      { "start": 13.0, "en": "A beaver tail? You may be shocked. But don't get me wrong. My Beaver Tail is not actually a beaver's tail. It's a yummy sweet food made of flour.", "ipa": "/a ˈbiːvər teɪl? juː meɪ biː ʃɒkt. bʌt doʊnt ɡɛt miː rɒŋ. maɪ ˈbiːvər teɪl ɪz nɒt ˈæktʃuəli a ˈbiːvərz teɪl. ɪts a ˈjʌmi swiːt fuːd meɪd əv ˈflaʊər/", vi: "Đuôi hải ly thật á? Chắc bạn sẽ giật mình hoảng hốt lắm nhỉ. Nhưng đừng hiểu lầm nhé, món Đuôi Hải Ly của tôi hoàn toàn không phải làm từ đuôi con hải ly thật đâu, mà đó là một loại bánh ngọt thơm ngon nức tiếng làm từ bột mì." },
      { "start": 23.0, "en": "A Beaver Tail is a piece of dough, shaped like a beaver's tail. It is quickly fried and then sprinkled with some brown sugar on top. Mmmm!", "ipa": "/a ˈbiːvər teɪl ɪz a piːs əv doʊ, ʃeɪpt laɪk a ˈbiːvərz teɪl. ɪt ɪz ˈkwɪkli fraɪd ænd ðɛn ˈsprɪŋkəld wɪð sʌm braʊn ˈʃʊɡər ɒn tɒp. mːːm!/", vi: "Cái tên bắt nguồn từ hình dáng miếng bột được nhào nặn dẹt dài hệt như chiếc đuôi của chú hải ly. Bánh được chiên giòn rụm trong dầu nóng rồi rắc ngập đường nâu ngọt lịm lên bề mặt. Ngon tuyệt cú mèo!" },
      { "start": 35.0, "en": "My special treat is really SPECIAL. It's not always available. It's sold on the canal only during the winter, when the water freezes, and people come to skate.", "ipa": "/maɪ ˈspɛʃl triːt ɪz ˈrɪəli ˈspɛʃl. ɪts nɒt ˈɔːlweɪz əˈveɪləbl. ɪts soʊld ɒn ðə kəˈnæl ˈoʊnli ˈdjʊərɪŋ ðə ˈwɪntər, wɛn ðə ˈwɔːtər ˈfriːzɪz, ænd ˈpiːpl kʌm tuː skeɪt/", vi: "Món ăn vặt này đặc biệt ở chỗ nó không bày bán quanh năm. Nó chỉ xuất hiện ở các quầy hàng dọc theo kênh đào vào những tháng mùa đông lạnh giá, khi mặt nước đóng băng dày và mọi người đổ xô đến tham gia trượt băng." },
      { "start": 49.0, "en": "It's sweet. It's hot and soft. It always goes with my favourite winter activity-skating on the canal. I love Beaver Tails. Best of all, I love the atmosphere of a cold winter day with so many people eating Beaver Tails and drinking hot chocolate after skating for hours.", "ipa": "/ɪts swiːt. ɪts hɒt ænd sɒft. ɪt ˈɔːlweɪz ɡoʊz wɪð maɪ ˈfeɪvərɪt ˈwɪntər ækˈtɪvəti-ˈskeɪtɪŋ ɒn ðə kəˈnæl. aɪ lʌv ˈbiːvər teɪlz. bɛst əv ɔːl, aɪ lʌv ði ˈætməsfɪr əv a koʊld ˈwɪntər deɪ wɪð soʊ ˈmɛni ˈpiːpl ˈiːtɪŋ ˈbiːvər teɪlz ænd ˈdrɪŋkɪŋ hɒt ˈtʃɒklət ˈɑːftər ˈskeɪtɪŋ fɔːr ˈaʊərz/", vi: "Bánh vừa ngọt, vừa nóng hổi lại dẻo thơm. Nó luôn là người bạn đồng hành tuyệt vời trong hoạt động yêu thích của tôi — trượt băng trên kênh đào băng giá. Tôi mê mẩn món bánh này, và trên hết, tôi yêu không khí náo nhiệt của những ngày đông lạnh buốt, nơi hàng đoàn người cùng nhau thưởng thức bánh Đuôi Hải Ly và nhâm nhi cốc sô-cô-la nóng hổi sau nhiều giờ trượt băng thấm mệt." }
    ]
  },
  {
    "day": 29,
    "title": "Birthday Flowers",
    image: "04 April/images/day_29.webp",
    audio: "04 April/audio/Track29.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. Smith grows beautiful flowers in his flower shop. Recently, he hired a young man who didn't seem very happy with his life.", "ipa": "/ˈmɪstər smɪθ ɡroʊz ˈbjuːtɪfl ˈflaʊərz ɪn hɪz ˈflaʊər ʃɒp. ˈriːsəntli, hiː ˈhaɪərd a jʌŋ mæn huː ˈdɪdnt siːm ˈvɛri ˈhæpi wɪð hɪz laɪf/", vi: "Ông Smith sở hữu một cửa hàng hoa tươi vô cùng rực rỡ. Dạo gần đây, ông có nhận vào làm việc một thanh niên trẻ tuổi nhưng luôn mang vẻ ủ rũ, bất mãn với cuộc sống." },
      { "start": 13.0, "en": "One day, Mr. Smith received a call. A girl wanted some special flowers delivered to her the next day. It was going to be her birthday.", "ipa": "/wʌn deɪ, ˈmɪstər smɪθ rɪˈsiːvd a kɔːl. a ɡɜːrl ˈwɒntɪd sʌm ˈspɛʃl ˈflaʊərz dɪˈlɪvərd tuː hɜːr ðə nɛkst deɪ. ɪt wɒz ˈɡoʊɪŋ tuː biː hɪz ˈbɜːrθdeɪ/", vi: "Vào một ngày nọ, ông Smith nhận được cuộc điện thoại đặt hàng từ một cô gái muốn đặt bó hoa tươi thật đặc biệt giao đến nhà vào ngày hôm sau nhân dịp sinh nhật cô ấy." },
      { "start": 23.0, "en": "The next morning, Mr. Smith cut twenty fresh roses and asked his new employee to deliver the flowers. Thirty minutes later, the young man came back with a big smile on his face.", "ipa": "/ðə nɛkst ˈmɔːrnɪŋ, ˈmɪstər smɪθ kʌt ˈtwɛnti frɛʃ ˈroʊzɪz ænd ɑːskt hɪz nuː ɪmˈplɔɪiː tuː dɪˈlɪvər ðə ˈflaʊərz. ˈθɜːrti ˈmɪnɪts ˈleɪtər, ðə jʌŋ mæn keɪm bæk wɪð a bɪɡ smaɪl ɒn hɪz feɪs/", vi: "Sáng hôm sau, ông Smith tự tay cắt hai mươi bông hồng tươi thắm nhất và cử nhân viên mới đem đi giao khách. Chỉ nửa tiếng sau, cậu thanh niên đã quay trở lại cửa hàng với nụ cười rạng rỡ nở nụ cười tươi rói trên môi." },
      { "start": 36.0, "en": "'Why are you happy?' Mr. Smith asked. 'I learned something beautiful,' the young man replied. 'The girl who ordered the flowers is blind. She told me that although she cannot see the flowers, she can just imagine their beauty. She can touch and smell the flowers. They make her happy.'", "ipa": "/waɪ ɑːr juː ˈhæpi?, ˈmɪstər smɪθ ɑːskt. aɪ lɜːrnd ˈsʌmθɪŋ ˈbjuːtɪfl, ðə jʌŋ mæn rɪˈplaɪd. ðə ɡɜːrl huː ˈɔːrdərd ðə ˈflaʊərz ɪz blaɪnd. ʃiː toʊld miː ðæt ɔːlˈðoʊ ʃiː ˈkænɒt siː ðə ˈflaʊərz, ʃiː kæn dʒʌst ɪˈmædʒɪn ðɛr ˈbjuːti. ʃiː kæn tʌtʃ ænd smɛl ðə ˈflaʊərz. ðeɪ meɪk hɜːr ˈhæpi/", vi: "'Sao trông cậu vui thế?' ông Smith tò mò hỏi. 'Con vừa lĩnh hội được một điều tuyệt đẹp thưa ông,' cậu nhân viên phấn khởi đáp. 'Cô gái đặt hoa vốn bị khiếm thị (mù). Cậu ấy tâm sự rằng dẫu không thể tận mắt ngắm nhìn, nhưng cô ấy có thể cảm nhận trọn vẹn vẻ đẹp ấy qua trí tưởng tượng bay bổng, qua xúc giác sờ nắn và khứu giác hít hà hương thơm. Điều đó mang lại cho cô ấy niềm vui lớn.'" },
      { "start": 54.0, "en": "The young man gazed at the flowers all around the shop and said, 'For that, I am happier than before.'", "ipa": "/ðə jʌŋ mæn ɡeɪzd æt ðə ˈflaʊərz ɔːl əˈraʊnd ðə ʃɒp ænd sɛd, fɔːr ðæt, aɪ æm ˈhæpiər ðæn bɪˈfɔːr/", vi: "Cậu thanh niên trìu mến đưa mắt ngắm nhìn muôn vàn sắc hoa ngập tràn quanh tiệm rồi thỏ thẻ: 'Chỉ nghĩ đến điều đó thôi cũng đủ khiến con cảm thấy yêu đời và hạnh phúc hơn rất nhiều rồi.'" }
    ]
  },
  {
    "day": 30,
    "title": "Dandelions",
    image: "04 April/images/day_30.webp",
    audio: "04 April/audio/Track30.mp3",
    "sentences": [
      { "start": 4.8, "en": "We were sitting outdoors today. It was a beautiful spring day. Birds were singing. The sky was really blue. We saw our neighbour, Mr. Viner, in his front yard. What was he doing?", "ipa": "/wiː wɜːr ˈsɪtɪŋ ˌaʊtˈdɔːrz təˈdeɪ. ɪt wɒz a ˈbjuːtɪfl sprɪŋ deɪ. bɜːrdz wɜːr ˈsɪŋɪŋ. ðə skaɪ wɒz ˈrɪəli bluː. wiː sɔː ˈaʊər ˈneɪbər, ˈmɪstər ˈvaɪnər, ɪn hɪz frʌnt jɑːrd. wɒt wɒz hiː ˈduːɪŋ?/", vi: "Hôm nay gia đình tôi cùng quây quần ngồi chơi ngoài trời. Một ngày mùa xuân tuyệt đẹp: Chim chót líu lo hòa ca, bầu trời xanh ngắt một màu. Chúng tôi nhìn thấy bác hàng xóm Viner đang cặm cụi ngoài khoảng sân trước nhà. Đố bạn biết bác ấy đang làm gì thế?" },
      { "start": 16.0, "en": "He was digging out small, yellow flowers from his lawn. He worked all day. Mom said, 'He must be very tired. He works hard to get rid of these beautiful yellow flowers.'", "ipa": "/hiː wɒz ˈdɪɡɪŋ aʊt smɔːl, ˈjɛloʊ ˈflaʊərz frɒm hɪz lɔːn. hiː wɜːrkt ɔːl deɪ. mɒm sɛd, hiː mʌst biː ˈvɛri ˈtaɪərd. hiː wɜːrks hɑːrd tuː ɡɛt rɪd əv ðiːz ˈbjuːtɪfl ˈjɛloʊ ˈflaʊərz/", vi: "Bác đang hì hục nhổ bỏ những bông hoa vàng nhỏ xíu mọc rải rác trên thảm cỏ nhà mình suốt cả ngày trời. Mẹ ngắm nhìn rồi lắc đầu bảo: 'Bắc vất vả quá đấy. Chắc bác phải mệt nhoài khi cứ phải hì hục nhổ sạch những đóa hoa vàng xinh xắn ấy đi như thế.'" },
      { "start": 27.0, "en": "Dandelions are weeds. People spend a lot of time trying to get rid of them. They dig them up. They spray chemicals to kill them. Millions of dollars are spent each year getting rid of these pretty yellow flowers. But dandelions just keep growing. They flourish every spring.", "ipa": "/ˈdændəlˌaɪnz ɑːr wiːdz. ˈpiːpl spɛnd a lɒt əv taɪm ˈtraɪɪŋ tuː ɡɛt rɪd əv ðɛm. ðeɪ dɪɡ ðɛm ʌp. ðeɪ spreɪ ˈkɛmɪklz tuː kɪl ðɛm. ˈmɪljənz əv ˈdɑːlərz ɑːr spɛnt iːtʃ jɪər ˈɡɛtɪŋ rɪd əv ðiːz ˈprɪti ˈjɛloʊ ˈflaʊərz. bʌt ˈdændəlˌaɪnz dʒʌst kiːp ˈɡroʊɪŋ. ðeɪ ˈflɜːrɪʃ ˈɛvri sprɪŋ/", vi: "Cây bồ công anh vốn bị xem là loài cỏ dại phiền toái. Người ta tốn biết bao công sức để tiêu diệt chúng: Nào là cuốc xới tận gốc, nào là phun thuốc trừ sâu độc hại. Hàng triệu đô-la bị ném qua cửa sổ mỗi năm chỉ để làm sạch bóng những bông hoa vàng rực này. Thế nhưng bồ công anh vẫn cứ ngoan cường sinh sôi nảy nở mạnh mẽ và bung nở rực rỡ vào mỗi dịp xuân về." },
      { "start": 47.0, "en": "Mom loves dandelions. She really doesn't understand why people do not like them. 'They are pretty. They grow easily. And you can even eat the delicious green leaves,' she says. My mom says she would rather enjoy them than spend all of her time trying to get rid of them.", "ipa": "/mɒm lʌvz ˈdændəlˌaɪnz. ʃiː ˈrɪəli ˈdʌznt ˌʌndərˈstænd waɪ ˈpiːpl duː nɒt laɪk ðɛm. ðeɪ ɑːr ˈprɪti. ðeɪ ɡroʊ ˈiːzɪli. ænd juː kæn ˈiːvn iːt ðə dɪˈlɪʃəs ɡriːn liːvz, ʃiː sɛd. maɪ mɒm sɛd ʃiː wʊd ˈrɑːðər ɪnˈdʒɔɪ ðɛm ðæn spɛnd ɔːl əv hɜːr taɪm ˈtraɪɪŋ tuː ɡɛt rɪd əv ðɛm/", vi: "Trái ngược với số đông, mẹ tôi lại đem lòng yêu mến loài hoa bồ công anh. Mẹ cứ thắc mắc mãi không hiểu sao thiên hạ lại ghét bỏ chúng. 'Chúng trông đáng yêu thế cơ mà, lại dễ sinh trưởng, thậm chí phần lá xanh non còn có thể chế biến thành món ăn ngon miệng,' mẹ hay cười nói thế. Mẹ bảo thà chọn cách ngắm nhìn thưởng thức vẻ đẹp tự nhiên của chúng còn hơn là cắm đầu cắm cổ tốn thời gian nhổ bỏ vô ích." }
    ]
  }
];