if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["08 August"] = [
  {
    "day": 1,
    "title": "Red Jelly",
    "image": "08 August/images/day_01.webp",
    "audio": "08 August/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "There was a jar of jelly in the kitchen cupboard—a very big jar of jelly.", "ipa": "/ðɛər wɒz ə dʒɑːr əv ˈdʒɛli ɪn ðə ˈkɪtʃɪn ˈkʌbərd—ə ˈvɛri bɪɡ dʒɑːr əv ˈdʒɛli/", "vi": "Có một hũ mứt trái cây trong tủ bếp — một hũ mứt rất to." },
      { "start": 13.0, "en": "The jelly was red. Sarah really wanted it. But the jar was very high, and Sarah was very small. Sarah climbed a chair. Then, she climbed a cupboard. Sarah put her foot on the counter and reached up.", "ipa": "/ðə ˈdʒɛli wɒz rɛd. ˈsɛərə ˈrɪəli ˈwɒntɪd ɪt. bʌt ðə dʒɑːr wɒz ˈvɛri haɪ, ænd ˈsɛərə wɒz ˈvɛri smɔːl. ˈsɛərə klaɪmd ə tʃɛər. ðɛn, ʃiː klaɪmd ə ˈkʌbərd. ˈsɛərə pʊt hɜːr fʊt ɒn ðə ˈkaʊntər ænd riːtʃt ʌp/", "vi": "Mứt có màu đỏ và Sarah rất thèm. Nhưng hũ mứt ở quá cao trong khi Sarah lại quá nhỏ. Sarah liền trèo lên ghế, rồi trèo lên tủ bếp, đặt chân lên quầy và với tay lên cao." },
      { "start": 28.0, "en": "She stretched and stretched. The jelly jar was very close now. But, Sarah started to wobble. She started to fall.", "ipa": "/ʃiː strɛtʃt ænd strɛtʃt. ðə ˈdʒɛli dʒɑːr wɒz ˈvɛri kloʊs naʊ. bʌt, ˈsɛərə ˈstɑːrtɪd tuː ˈwɒbl. ʃiː ˈstɑːrtɪd tuː fɔːl/", "vi": "Cô bé rướn người hết cỡ. Hũ mứt đã ở rất gần. Thế nhưng, Sarah bắt đầu chao đảo và ngã quỵ xuống." },
      { "start": 39.0, "en": "Quickly, Sarah grabbed the jar of jelly and fell to the floor with a loud BANG! The jelly jar fell to the floor and broke. There was red jelly everywhere!", "ipa": "/ˈkwɪkli, ˈsɛərə ɡræbt ðə dʒɑːr əv ˈdʒɛli ænd fɛl tuː ðə flɔːr wɪð ə laʊd bæŋ! ðə ˈdʒɛli dʒɑːr fɛl tuː ðə flɔːr ænd broʊk. ðɛər wɒz rɛd ˈdʒɛli ˈɛvriˌwɛər/", "vi": "Trong lúc hoảng hốt, Sarah vớ lấy hũ mứt rồi ngã nhào xuống sàn với một tiếng RẦM thật lớn! Hũ mứt rơi xuống nền nhà vỡ tan tành và mứt đỏ văng tung tóe khắp nơi!" },
      { "start": 54.0, "en": "Sarah cried. Mom comforted Sarah and cleaned up the jelly. She then opened another jar of jelly and made a sandwich for Sarah. 'Don't cry,' said Mom. 'Just remember to ask when you want something!' Sarah ate her sandwich. The jelly was very, very good indeed!", "ipa": "/ˈsɛərə kraɪd. mɒm ˈkʌmfərtɪd ˈsɛərə ænd kliːnd ʌp ðə ˈdʒɛli. ʃiː ðɛn ˈoʊpənd əˈnʌðər dʒɑːr əv ˈdʒɛli ænd meɪd ə ˈsænwɪtʃ fɔːr ˈsɛərə. doʊnt kraɪ, sɛd mɒm. dʒʌst rɪˈmɛmbər tuː ɑːsk wɛn juː wɒnt ˈsʌmθɪŋ! ˈsɛərə eɪt hɜːr ˈsænwɪtʃ. ðə ˈdʒɛli wɒz ˈvɛri, ˈvɛri ɡʊd ɪnˈdiːd!/", "vi": "Sarah òa khóc. Mẹ đến dỗ dành và dọn sạch bãi chiến trường, sau đó mở một hũ mứt khác để làm bánh mì kẹp cho cô bé. 'Đừng khóc nữa con nhé,' mẹ bảo. 'Lần sau muốn gì thì nhớ xin phép mẹ nha!' Sarah ăn liền bánh mì. Mứt quả thật ngon tuyệt cú mèo!" }
    ]
  },
  {
    "day": 2,
    "title": "Fire and Ice",
    "image": "08 August/images/day_02.webp",
    "audio": "08 August/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "Today, our teacher asked the class what things can burn us. Everyone thought this was an easy question to answer.", "ipa": "/təˈdeɪ, ˈaʊər ˈtiːtʃər ɑːskt ðə klɑːs wɒt θɪŋz kæn bɜːrn ʌs. ˈɛvriˌwʌn θɔːt ðɪs wɒz ən ˈiːzi ˈkwɛstʃən tuː ˈɑːnsər/", "vi": "Hôm nay, cô giáo đố cả lớp những thứ gì có thể làm chúng ta bị bỏng. Mọi người đều nghĩ đây là câu hỏi quá dễ." },
      { "start": 14.0, "en": "'Fire can burn us,' we said. Touch your finger to a flame and you will get burnt. You will get a big blister on your finger.", "ipa": "/ˈfaɪər kæn bɜːrn ʌs, wiː sɛd. tʌtʃ jɔːr ˈfɪŋɡər tuː ə fleɪm ænd juː wɪl ɡɛt bɜːrnt. juː wɪl ɡɛt ə bɪɡ ˈblɪstər ɒn jɔːr ˈfɪŋɡər/", "vi": "'Lửa có thể làm chúng ta bỏng,' cả lớp đáp. Chạm ngón tay vào ngọn lửa là sẽ bị bỏng rát và nổi bọng nước lớn." },
      { "start": 23.0, "en": "'The sun will burn you too if you stay out in it too long on hot summer days.' 'Right,' our teacher said. 'Fire will burn. So will the sun. Can you think of anything else?'", "ipa": "/ðə sʌn wɪl bɜːrn juː tuː ɪf juː steɪ aʊt ɪn ɪt tuː lɒŋ ɒn hɒt ˈsʌmər deɪz. raɪt, ˈaʊər ˈtiːtʃər sɛd. ˈfaɪər wɪl bɜːrn. soʊ wɪl ðə sʌn. kæn juː θɪŋk əˈbaʊt ˈɛniˌθɪŋ ɛls?/", "vi": "'Mặt trời cũng sẽ làm bạn bỏng nắng nếu ở ngoài trời quá lâu vào ngày hè.' 'Chính xác,' cô giáo khen. 'Lửa gây bỏng, mặt trời cũng vậy. Các em còn nghĩ ra thứ gì khác nữa không?'" },
      { "start": 38.0, "en": "'Boiling water or hot steam,' we said. 'Good,' said our teacher. 'Many hot things can burn you. But did you know that something very cold can also burn you?' We laughed. How can something cold burn?", "ipa": "/ˈbɔɪlɪŋ ˈwɔːtər ɔːr hɒt stiːm, wiː sɛd. ɡʊd, sɛd ˈaʊər ˈtiːtʃər. ˈmɛni hɒt θɪŋz kæn bɜːrn juː. bʌt dɪd juː noʊ ðæt ˈsʌmθɪŋ ˈvɛri koʊld kæn ˈɔːlsoʊ bɜːrn juː? wiː lɑːft. haʊ kæn ˈsʌmθɪŋ koʊld bɜːrn?/", "vi": "'Nước sôi hoặc hơi nước nóng ạ,' chúng tôi đáp. 'Giỏi lắm,' cô tiếp lời. 'Nhiều thứ nóng có thể gây bỏng. Nhưng các em có biết vật rất lạnh cũng gây bỏng được không?' Chúng tôi phì cười vì không hiểu sao đồ lạnh lại gây bỏng." },
      { "start": 56.0, "en": "Our teacher continued, 'When your skin touches something extremely cold for a long time, it can get damaged. This is called a cold burn.' We learned something amazing today. Hot or cold, fire or ice—many things can burn us.", "ipa": "/ˈaʊər ˈtiːtʃər kənˈtɪnyuːd, wɛn jɔːr skɪn ˈtʌtʃɪz ˈsʌmθɪŋ ɪkˈstriːmli koʊld fɔːr ə lɒŋ taɪm, ɪt kæn ɡɛt ˈdæmɪdʒd. ðɪs ɪz kɔːld ə koʊld bɜːrn. wiː lɜːrnd ˈsʌmθɪŋ əˈmeɪzɪŋ təˈdeɪ. hɒt ɔːr koʊld, ˈfaɪər ɔːr aɪs—ˈmɛni θɪŋz kæn bɜːrn ʌs/", "vi": "Cô giáo giải thích: 'Khi da tiếp xúc với vật cực lạnh trong thời gian dài, các mô sẽ bị tổn thương. Hiện tượng này gọi là bỏng lạnh.' Hôm nay chúng tôi đã học được điều kỳ diệu: Nóng hay lạnh, lửa hay băng — rất nhiều thứ có thể làm tổn thương da chúng ta." }
    ]
  },
  {
    "day": 3,
    "title": "First Man in Space (I)",
    "image": "08 August/images/day_03.webp",
    "audio": "08 August/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Our world keeps changing. We didn't always have computers, the Internet or even cars! But there have always been very smart and very brave people who came up with interesting ideas.", "ipa": "/ˈaʊər wɜːrld kiːps ˈtʃeɪndʒɪŋ. wiː ˈdɪdnt ˈɔːlweɪz hæv kəmˈpjuːtərz, ði ˈɪntərnɛt ɔːr ˈiːvn kɑːrz! bʌt ðɛər hæv ˈɔːlweɪz biːn ˈvɛri smɑːrt ænd ˈvɛri breɪv ˈpiːpl huː keɪm ʌp wɪð ˈɪntrəstɪŋ aɪˈdiːəz/", "vi": "Thế giới của chúng ta không ngừng đổi thay. Xưa kia loài người đâu đã có máy tính, internet hay ô tô! Dù vậy, luôn có những con người thông minh và dũng cảm xuất chúng nghĩ ra những ý tưởng táo bạo." },
      { "start": 21.0, "en": "Some of the smartest and bravest people were those who first went into space. America, Russia, Europe and China have all sent people into space. Today, there are people in space all the time. They circle the earth in space stations.", "ipa": "/sʌm əv ðə ˈsmɑːrtɪst ænd ˈbreɪvɪst ˈpiːpl wɜːr ðoʊz huː fɜːrst wɛnt ˈɪntuː speɪs. əˈmɛrɪkə, ˈrʌʃə, ˈjʊərəp ænd ˈtʃaɪnə hæv ɔːl sɛnt ˈpiːpl ˈvɪzɪt ˈɪntuː speɪs. təˈdeɪ, ðɛər ɑːr ˈpiːpl ɪn speɪs ɔːl ðə taɪm. ðeɪ ˈsɜːrkl ði ɜːrθ ɪn speɪs ˈsteɪʃnz/", "vi": "Những người thông minh và dũng cảm nhất phải kể đến các nhà thám hiểm không gian đầu tiên. Mỹ, Nga, châu Âu và Trung Quốc đều đã đưa người vào vũ trụ. Ngày nay, con người luôn túc trực trong không gian, bay quanh Trái Đất trên các trạm vũ trụ." },
      { "start": 41.0, "en": "Can you imagine how brave the first man must have been to go into space? His name was Yuri Gagarin and he was Russian. It was 1961 when his rocket blasted off into space.", "ipa": "/kæn juː ɪˈmædʒɪn haʊ breɪv ðə fɜːrst mæn mʌst hæv biːn tuː ɡoʊ ˈɪntuː speɪs? hɪz neɪm wɒz ˈjʊəri ɡəˈɡɑːrɪn ænd hiː wɒz ˈrʌʃən. ɪt wɒz ˌnaɪnˈtiːn ˈsɪksti-wʌn wɛn hɪz ˈrɒkɪt ˈblæstɪd ɒf ˈɪntuː speɪs/", "vi": "Bạn có tưởng tượng nổi người đầu tiên bay vào vũ trụ đã dũng cảm nhường nào không? Ông tên là Yuri Gagarin, người Nga. Vào năm 1961, tên lửa chở ông đã gầm rú phóng thẳng lên bầu trời vũ trụ." }
    ]
  },
  {
    "day": 4,
    "title": "First Man in Space (II)",
    "image": "08 August/images/day_04.webp",
    "audio": "08 August/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "Although the rocket was very big, the space inside was very small. That's why a small person, who could easily fit inside, was chosen to go on the first trip into space.", "ipa": "/ɔːlˈðoʊ ðə ˈrɒkɪt wɒz ˈvɛri bɪɡ, ðə speɪs ɪnˈsaɪd wɒz ˈvɛri smɔːl. ðæts waɪ ə smɔːl ˈpɜːrsn, huː kʊd ˈiːzɪli fɪt ɪnˈsaɪd, wɒz ˈtʃoʊzn tuː ɡoʊ ɒn ðə fɜːrst trɪp ˈɪntuː speɪs/", "vi": "Dù quả tên lửa khổng lồ nhưng khoang chứa bên trong lại vô cùng chật chội. Đó là lý do một người có vóc dáng nhỏ gọn, dễ dàng chui lọt vào khoang, được chọn cho chuyến bay lịch sử đầu tiên." },
      { "start": 19.0, "en": "Yuri was only 5'2\" (1.57 metres) tall. But even for him, the rocket was very tight. Today, people spend hundreds of days travelling in space. One person was in space for over 400 days! But that was in a space station, which is about the size of a few city buses.", "ipa": "/ˈjʊəri wɒz ˈoʊnli faɪv-tuː tɔːl. bʌt ˈiːvn fɔːr hɪm, ðə ˈrɒkɪt wɒz ˈvɛri taɪt. təˈdeɪ, ˈpiːpl spɛnd ˈhʌndrədz əv deɪz ˈtrævəlɪŋ ɪn speɪs. wʌn ˈpɜːrsn wɒz ɪn speɪs fɔːr ˈoʊvər ˈfɔːr ˈhʌndrəd deɪz! bʌt ðæt wɒz ɪn ə speɪs ˈsteɪʃn, wɪtʃ ɪz əˈbaʊt ðə saɪz əv ə fjuː ˈsɪti ˈbʌsɪz/", "vi": "Yuri cao chưa đến 1m57. Nhưng dù vậy, khoang tàu vẫn vô cùng chật hẹp. Ngày nay, các phi hành gia có thể sống hàng trăm ngày trong không gian — từng có người ở vũ trụ hơn 400 ngày! Tuy nhiên đó là trên các trạm không gian to lớn tương đương vài chiếc xe buýt." },
      { "start": 44.0, "en": "How much time did Yuri spend in space in that crowded rocket? About 108 minutes! But even that was probably long enough!", "ipa": "/haʊ mʌtʃ taɪm dɪd ˈjʊəri spɛnd ɪn speɪs ɪn ðæt ˈkraʊdɪd ˈrɒkɪt? əˈbaʊt wʌn ˈhʌndrəd ænd eɪt ˈmɪnɪts! bʌt ˈiːvn ðæt wɒz ˈprɒbəbli lɔːŋ ɪˈnʌf!/", "vi": "Yuri đã ở trong không gian bao lâu trên con tàu chật chội ấy? Khoảng 108 phút! Nhưng chừng đó có lẽ cũng đủ để trải nghiệm một đời người." }
    ]
  },
  {
    "day": 5,
    "title": "How Corn Came to the Indians",
    "image": "08 August/images/day_05.webp",
    "audio": "08 August/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Everyone in the village was hungry. There was no food to eat. Two little village boys set out to search for food. They walked for many hours until they saw a small bird. They were very hungry. 'Let's eat this bird and then look for more,' one boy said.", "ipa": "/ˈɛvriˌwʌn ɪn ðə ˈvɪlɪdʒ wɒz ˈhʌŋɡri. ðɛər wɒz noʊ fuːd tuː iːt. tuː ˈlɪtl ˈvɪlɪdʒ bɔɪz sɛt aʊt tuː sɜːrtʃ fɔːr fuːd. ðeɪ wɔːkt fɔːr ˈmɛni ˈaʊərz ənˈtɪl ðeɪ sɔː ə smɔːl bɜːrd. ðeɪ wɜːr ˈvɛri ˈhʌŋɡri. lɛts iːt ðɪs bɜːrd ænd ðɛn lʊk fɔːr mɔːr, wʌn bɔɪ sɛd/", vi: "Cả làng đang lâm vào cảnh đói kém không có gì ăn. Hai cậu bé trong làng quyết định lên đường tìm thức ăn. Đi bộ suốt nhiều giờ, chúng bắt gặp một chú chim nhỏ. Bụng đói cồn cào, một đứa bàn: 'Hay là ăn thịt con chú chim này rồi đi tìm tiếp'." },
      { "start": 25.0, "en": "Suddenly, an old woman came out of the forest. 'I am very hungry. Will you share some of your bird with me?' she asked. The boys were starving, but they respected old people. The old woman made a fire. She ate the whole bird. 'You are good boys,' said the woman. 'Do not worry. Come tomorrow to this same spot. I will reward you.'", "ipa": "/ˈsʌdənli, ən oʊld ˈwʊmən keɪm aʊt əv ðə ˈfɒrɪst. aɪ æm ˈvɛri ˈhʌŋɡri. wɪl juː ʃɛər sʌm əv jɔːr bɜːrd wɪð miː?, ʃiː ɑːskt. ðə bɔɪz wɜːr ˈstɑːrvɪŋ, bʌt ðeɪ rɪˈspɛktɪd oʊld ˈpiːpl. ðə oʊld ˈwʊmən meɪd ə ˈfaɪər. ʃiː eɪt ðə hoʊl bɜːrd. juː ɑːr ɡʊd bɔɪz, sɛd ðə ˈwʊmən. doʊnt ˈwʌri. kʌm təˈmɒroʊ tuː ðɪs seɪm spɒt. aɪ wɪl rɪˈwɔːrd juː/", vi: "Đúng lúc đó, một bà cụ xuất hiện từ trong rừng sâu: 'Ta đói lắm, các cháu cho ta xin chút thịt chim nhé?' Hai cậu bé dù đói lả nhưng vẫn kính trọng người lớn tuổi nên đồng ý. Bà cụ nhóm lửa và ăn hết sạch con chim. 'Các cháu là những đứa trẻ ngoan,' bà bảo. 'Đừng lo, ngày mai hãy quay lại đây, ta sẽ thưởng cho các cháu.'" },
      { "start": 51.0, "en": "The boys returned the next day. The fire was gone. In its place were four small, green plants. There was something yellow on the plants. It tasted very good. The boys brought the plants to their village. Soon, the plants grew tall. And from that time on, the people in the village always had corn to eat.", "ipa": "/ðə bɔɪz rɪˈtɜːrnd ðə nɛkst deɪ. ðə ˈfaɪər wɒz ɡɒn. ɪn ɪts pleɪs wɜːr fɔːr smɔːl, ɡriːn plɑːnts. ðɛər wɒz ˈsʌmθɪŋ ˈjɛloʊ ɒn ðə plɑːnts. ɪt teɪstɪd ˈvɛri ɡʊd. ðə bɔɪz brɔːt ðə plɑːnts tuː ðɛər ˈvɪlɪdʒ. suːn, ðə plɑːnts ɡruː tɔːl. ænd frɒm ðæt taɪm ɒn, ðə ˈpiːpl ɪn ðə ˈvɪlɪdʒ ˈɔːlweɪz hæd kɔːrn tuː iːt/", vi: "Hôm sau, hai cậu bé quay lại. Đống lửa đã tắt, thay vào đó là bốn cây xanh nhỏ nhắn mang những hạt màu vàng óng béo ngậy. Nếm thử thấy rất ngon, hai em bèn mang cây về làng. Chẳng mấy chốc cây mọc cao lớn, và từ đó dân làng không bao giờ phải chịu cảnh thiếu ngô ăn nữa." }
    ]
  },
  {
    "day": 6,
    "title": "Flag",
    "image": "08 August/images/day_06.webp",
    "audio": "08 August/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was Saturday. The Drake family was watching their favourite news channel on television. 'There's our flag!' Dad said as he pointed to the TV screen.", "ipa": "/ɪt wɒz ˈsætərdeɪ. ðə dreɪk ˈfæməli wɒz ˈwɒtʃɪŋ ðɛər ˈfeɪvərɪt nuːz ˈtʃænl ɒn ˈtɛlɪˌvɪʒn. ðɛərz ˈaʊər flæɡ!, dæd sɛd æz hiː ˈpɔɪntɪd tuː ðə tiː-viː skriːn/", vi: "Hôm ấy là thứ Bảy, gia đình Drake đang xem kênh tin tức yêu thích trên ti vi. 'Cờ của nước mình kìa!' bố vừa nói vừa chỉ tay lên màn hình." },
      { "start": 14.0, "en": "'If that's our flag, why do those people have it?' asked Stevie. Dad laughed, 'That's not quite what I meant. I meant that the flag stands for and represents our country.'", "ipa": "/ɪf ðæts ˈaʊər flæɡ, waɪ duː ðoʊz ˈpiːpl hæv ɪt?, ɑːskt ˈstiːvi. dæd lɑːft, ðæts nɒt kwaɪt wɒt aɪ mɛnt. aɪ mɛnt ðæt ðə flæɡ stændz fɔːr ænd ˌrɛprɪˈzɛnts ˈaʊər ˈkʌntri/", vi: "'Nếu đó là cờ của mình, sao những người kia lại cầm nhỉ?' Stevie thắc mắc. Bố cười: 'Ý bố không phải thế. Ý bố là lá cờ tượng trưng và đại diện cho đất nước chúng ta.'" },
      { "start": 29.0, "en": "'We have our flag on a pole at school,' said Chris. 'I wish we had a flag at home,' said Susie. 'Let's go to the store and buy one,' said Dad.", "ipa": "/wiː hæv ˈaʊər flæɡ ɒn ə poʊl æt skuːl, sɛd krɪs. aɪ wɪʃ wiː hæd flæɡ æt hoʊm, sɛd ˈsuːzi. lɛts ɡoʊ tuː ðə stɔːr ænd baɪ wʌn, sɛd dæd/", vi: "'Ở trường chúng con cũng có cột cờ treo cờ mà,' Chris nói. 'Ước gì nhà mình cũng có một lá cờ,' Susie ao ước. 'Thế thì đi ra cửa hàng mua ngay một cái thôi,' bố vui vẻ quyết định." },
      { "start": 43.0, "en": "The whole family went to the store. They looked at big flags, little flags and medium-sized flags. Finally, they bought one that was just right.", "ipa": "/ðə hoʊl ˈfæməli wɛnt tuː ðə stɔːr. ðeɪ lʊkt æt bɪɡ flæɡz, ˈlɪtl flæɡz ænd ˈmiːdiəm-saɪzd flæɡz. ˈfaɪnəli, ðeɪ bɔːt wʌn ðæt wɒz dʒʌst raɪt/", vi: "Cả nhà cùng ra tiệm, ngắm nghía đủ loại cờ to, cờ nhỏ và cờ cỡ vừa. Cuối cùng họ chọn được một lá cờ vừa vặn hoàn hảo." },
      { "start": 54.0, "en": "Back home, Dad put up a flag pole in the front yard and raised the new flag high in the air. The whole family saluted it. They were all happy to fly the flag of their country.", "ipa": "/bæk hoʊm, dæd pʊt ʌp ə flæɡ poʊl ɪn ðə frʌnt jɑːrd ænd reɪzd ðə njuː flæɡ haɪ ɪn ði ɛər. ðə hoʊl ˈfæməli səˈluːtɪd ɪt. ðeɪ wɜːr ɔːl ˈhæpi tuː flaɪ ðə flæɡ əv ðɛər ˈkʌntri/", vi: "Về đến nhà, bố dựng cột cờ ở sân trước và kéo lá cờ mới tung bay phấp phới trên cao. Cả nhà đứng nghiêm chào cờ. Ai nấy đều hạnh phúc khi được giương cao quốc kỳ của quê hương." }
    ]
  },
  {
    "day": 7,
    "title": "Waiting for the Train",
    "image": "08 August/images/day_07.webp",
    "audio": "08 August/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "Have you ever waited for a train to cross the road? Have you tried to count the number of cars that made up the train? Some trains can be very, very long! How long? We'll get to that later...", "ipa": "/hæv juː ˈɛvər ˈweɪtɪd fɔːr ə treɪn tuː krɒs ðə roʊd? hæv juː traɪd tuː kaʊnt ðə ˈnʌmbər əv kɑːrz ðæt meɪd ʌp ðə treɪn? sʌm treɪnz kæn biː ˈvɛri, ˈvɛri lɒŋ! haʊ lɒŋ? wiːl ɡɛt tuː ðæt ˈleɪtər/", vi: "Bạn đã bao giờ phải chờ tàu hỏa chạy qua đường tàu cắt ngang chưa? Bạn đã thử đếm số toa tàu nối dài chưa? Có những đoàn tàu dài ơi là dài! Dài cỡ nào ư? Lát nữa chúng ta sẽ biết..." },
      { "start": 16.0, "en": "Trains are amazing! They have been around for almost 200 years. They carry people and things all over the world. They carry oil, metal, trees and many other things we use. Every day, trains carry millions of people from one place to another.", "ipa": "/treɪnz ɑːr əˈmeɪzɪŋ! ðeɪ hæv biːn əˈraʊnd fɔːr ˈɔːlmoʊst ˈtuː ˈhʌndrəd jɪərz. ðeɪ ˈkæri ˈpiːpl ænd θɪŋz ɔːl ˈoʊvər ðə wɜːrld. ðeɪ ˈkæri ɔɪl, ˈmɛtl, triːz ænd ˈmɛni ˈʌðər θɪŋz wiː juːz. ˈɛvri deɪ, treɪnz ˈkæri ˈmɪljənz əv ˈpiːpl frɒm wʌn pleɪs tuː əˈnʌðər/", vi: "Tàu hỏa thật kỳ diệu! Chúng đã xuất hiện gần 200 năm, chở người và hàng hóa đi khắp thế giới — từ dầu mỏ, kim loại, gỗ lụt cho đến vô vàn vật dụng khác. Mỗi ngày, tàu hỏa phục vụ hàng triệu hành khách di chuyển khắp mọi nơi." },
      { "start": 32.0, "en": "Trains are good for the environment too because the people riding them don't need to use their cars. This means that trains can help reduce pollution. So, next time you see a train, remember how useful it is even nearly two centuries after it was invented!", "ipa": "/treɪnz ɑːr ɡʊd fɔːr ði ɪnˈvaɪrənmənt tuː bɪˈkɒz ðə ˈpiːpl ˈraɪdɪŋ ðɛm doʊnt niːd tuː juːz ðɛər kɑːrz. ðɪs miːnz ðæt treɪnz kæn hɛlp rɪˈduːs pəˈluːʃn. soʊ, nɛkst taɪm juː siː ə treɪn, rɪˈmɛmbər haʊ ˈjuːsfʊl ɪt ɪz ˈiːvn ˈnɪərli tuː ˈsɛntʃəriz ˈɑːftər ɪt wɒz ɪnˈvɛntɪd/", vi: "Tàu hỏa còn rất thân thiện với môi trường vì hành khách đi tàu không phải lái xe riêng, giúp giảm thiểu khí thải ô nhiễm. Thế nên, lần tới khi nhìn thấy đoàn tàu hỏa, hãy nhớ rằng phương tiện này vẫn vô cùng hữu ích dù đã gần hai thế kỷ trôi qua kể từ khi ra đời!" },
      { "start": 52.0, "en": "What was the longest train ever? Well, it was in Australia. It had 8 engines and pulled 682 cars. And it was more than 7 kilometres long! Try counting those cars!", "ipa": "/wɒt wɒz ðə ˈlɒŋɡɪst treɪn ˈɛvər? wɛl, ɪt wɒz ɪn ɔːˈstreɪliə. ɪt hæd eɪt ˈɛndʒɪnz ænd pʊld ˈsɪks ˈhʌndrəd ˈeɪti-tuː kɑːrz. ænd ɪt wɒz mɔːr ðæn ˈsɛvn kɪˈlɒmɪtərz lɒŋ! traɪ ˈkaʊntɪŋ ðoʊz kɑːrz!/", vi: "Đoàn tàu dài nhất thế giới là ở đâu? Đó là ở Australia với 8 đầu máy kéo theo 682 toa tàu, chiều dài khủng khiếp hơn 7 ki-lô-mét! Cứ thử đếm hết số toa đó xem nào!" }
    ]
  },
  {
    "day": 8,
    "title": "Splat the Spider",
    "image": "08 August/images/day_08.webp",
    "audio": "08 August/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "Suzie ran into the kitchen and yelled to her mom, 'I hate spiders! They're so big and hairy!' Mom was grooming Bruno, the family dog. She looked up, confused. Then she smiled and said, 'Well, so is Bruno.'", "ipa": "/ˈsuːzi ræn ˈɪntuː ðə ˈkɪtʃɪn ænd jɛld tuː hɜːr mɒm, aɪ heɪt ˈspaɪdərz! ðeɪr soʊ bɪɡ ænd ˈhɛri! mɒm wɒz ˈɡruːmɪŋ ˈbruːnoʊ, ðə ˈfæməli dɔːɡ. ʃiː lʊkt ʌp, kənˈfjuːzd. ðɛn ʃiː smaɪld ænd sɛd, wɛl, soʊ ɪz ˈbruːnoʊ/", vi: "Suzie chạy vào bếp hớt hải hét lên với mẹ: 'Con ghét nhện lắm! Chúng vừa to vừa nhiều lông!' Mẹ đang chải lông cho Bruno — chú chó cưng của gia đình — liền ngước lên ngạc nhiên, rồi mỉm cười đáp: 'Ờ, Bruno nhà mình cũng thế còn gì.'" },
      { "start": 18.0, "en": "'Go SPLAT it!' shouted Suzie. 'Why?' Mom asked. 'It has long legs!' yelled Suzie. 'So does Bruno,' said Mom again. 'It's ugly and I don't like it!' sobbed Suzie. Mom stopped brushing Bruno. 'Why don't you like it?' 'Because I just don't!' said Suzie. 'Do you like spiders, Mom?' 'No Suzie, I don't.'", "ipa": "/ɡoʊ splæt ɪt!, ˈʃaʊtɪd ˈsuːzi. waɪ?, mɒm ɑːskt. ɪt hæz lɔːŋ lɛɡz!, jɛld ˈsuːzi. soʊ dʌz ˈbruːnoʊ, sɛd mɒm əˈɡɛn. ɪts ˈʌgli ænd aɪ doʊnt laɪk ɪt!, sɒbd ˈsuːzi. mɒm stɒpt ˈbrʌʃɪŋ ˈbruːnoʊ. waɪ doʊnt juː laɪk ɪt? bɪˈkɒz aɪ dʒʌst doʊnt!, sɛd ˈsuːzi. duː juː laɪk ˈspaɪdərz, mɒm? noʊ ˈsuːzi, aɪ doʊnt/", vi: "'Đập bẹp nó đi mẹ!' Suzie hét. 'Tại sao?' mẹ hỏi. 'Nó có chân dài!' Suzie cãi. 'Bruno cũng có mà,' mẹ điềm đạm. 'Nó xấu xí và con không thích!' Suzie sụt sùi. Mẹ dừng tay chải lông: 'Sao con lại ghét nó?' 'Vì con ghét thôi!' Suzie đáp. 'Mẹ có thích nhện không?' 'Không con ạ, mẹ không thích.'" },
      { "start": 41.0, "en": "'So then, why won't you SPLAT it?' demanded Suzie. 'No, Suzie. Where is this spider?' 'It's in the bathroom.' Mom went into the bathroom, got the spider, and moved it to a safe place.", "ipa": "/soʊ ðɛn, waɪ woʊnt juː splæt ɪt?, dɪˈmɑːndɪd ˈsuːzi. noʊ, ˈsuːzi. wɛər ɪz ðɪs ˈspaɪdər? ɪts ɪn ðə ˈbɑːθruːm. mɒm wɛnt ˈɪntuː ðə ˈbɑːθruːm, ɡɒt ðə ˈspaɪdər, ænd muːvd ɪt tuː a seɪf pleɪs/", vi: "'Thế sao mẹ không đập bẹp nó đi?' Suzie vặn vẹo. 'Không con ạ. Con nhện đó ở đâu?' 'Nó ở trong phòng tắm.' Mẹ bước vào phòng tắm, nhẹ nhàng bắt con nhện mang thả đến một nơi an toàn." },
      { "start": 57.0, "en": "Mom smiled and said, 'You are a little girl, right?' Suzie nodded. 'How would you like it if a big bad giant wanted to splat you just because you were small?' Finally, Suzie understood what her mom was trying to say.", "ipa": "/mɒm smaɪld ænd sɛd, juː ɑːr ə ˈlɪtl ɡɜːrl, raɪt? ˈsuːzi ˈnɒdɪd. haʊ wʊd juː laɪk ɪt ɪf ə bɪɡ bæd ˈdʒaɪənt ˈwɒntɪd tuː splæt juː dʒʌst bɪˈkɒz juː wɜːr smɔːl? ˈfaɪnəli, ˈsuːzi ˌʌndərˈstʊd wɒt hɜːr mɒm wɒz ˈtraɪɪŋ tuː seɪ/", vi: "Mẹ mỉm cười xoa đầu: 'Con là một cô bé nhỏ nhắn phải không?' Suzie gật đầu. 'Thế con sẽ cảm thấy thế nào nếu một gã khổng lồ xấu xa muốn đập bẹp con chỉ vì con quá nhỏ bé?' Cuối cùng, Suzie đã thấu hiểu bài học mà mẹ muốn dạy." }
    ]
  },
  {
    "day": 9,
    "title": "Whirling Storm",
    "image": "08 August/images/day_09.webp",
    "audio": "08 August/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "Little Squirrel was an unhappy Indian boy. All the boys his age were going with the men to bring in the horses. But, Little Squirrel's father had told him to stay home. 'You are smaller than most boys your age. You must stay here and take care of the children.'", "ipa": "/ˈlɪtl ˈskwɪrəl wɒz ən ʌnˈhæpi ˈɪndiən bɔɪ. ɔːl ðə bɔɪz hɪz eɪdʒ wɜːr ˈɡoʊɪŋ wɪð ðə mɛn tuː brɪŋ ɪn ðə ˈhɔːrsɪz. bʌt, ˈlɪtl ˈskwɪrəlz ˈfɑːðər hæd toʊld hɪm tuː steɪ hoʊm. juː ɑːr ˈsmɔːlər ðæn moʊst bɔɪz jɔːr eɪdʒ. juː mʌst steɪ hɪər ænd teɪk kɛər əv ðə ˈtʃɪldrən/", vi: "Sóc Nhỏ là một cậu bé da đỏ không mấy vui vẻ. Lũ trẻ cùng trang tuổi đều theo những người đàn ông đi lùa ngựa về, riêng Sóc Nhỏ bị bố bắt ở nhà. 'Con nhỏ con hơn các bạn nên phải ở nhà trông em.' " },
      { "start": 21.0, "en": "Little Squirrel's mother sent him to catch fish. 'We will have a good supper,' she said. While Little Squirrel was fishing, he saw a tornado in the distant sky. It was heading towards his village.", "ipa": "/ˈlɪtl ˈskwɪrəlz ˈmʌðər sɛnt hɪm tuː kætʃ fɪʃ. wiː wɪl hæv ə ɡʊd ˈsʌpər, ʃiː sɛd. waɪl ˈlɪtl ˈskwɪrəl wɒz ˈfɪʃɪŋ, hiː sɔː ə tɔːrˈneɪdoʊ ɪn ðə ˈdɪstənt skaɪ. ɪt wɒz ˈhɛdɪŋ təˈwɔːrdz hɪz ˈvɪlɪdʒ/", vi: "Mẹ sai Sóc Nhỏ ra suối bắt cá để chuẩn bị bữa tối. Đang cặm cụi câu cá, cậu chợt nhìn thấy một cơn lốc xoáy khổng lồ ở đằng xa đang gầm rú tiến thẳng về phía ngôi làng." },
      { "start": 36.0, "en": "Little Squirrel raced home. 'It's a whirling storm!' he shouted. Because of his speed and bravery, he was able to warn everyone about the tornado and get them to safety.", "ipa": "/ˈlɪtl ˈskwɪrəl reɪst hoʊm. ɪts ə ˈwɜːrlɪŋ stɔːrm!, hiː ˈʃaʊtɪd. bɪˈkɒz əv hɪz spiːd ænd ˈbreɪvəri, hiː wɒz ˈeɪbl tuː wɔːrn ˈɛvriˌwʌn əˈbaʊt ðə tɔːrˈneɪdoʊ ænd ɡɛt ðɛm tuː ˈseɪfti/", vi: "Sóc Nhỏ ba chân bốn cẳng cắm cổ chạy về nhà hô hoán: 'Lốc xoáy đến rồi!' Nhờ sự nhanh nhẹn và lòng dũng cảm, cậu đã kịp cảnh báo cho tất cả dân làng chạy trốn an toàn." },
      { "start": 51.0, "en": "When the men and boys returned from their trip, the chiefs declared Little Squirrel a man even though he was only eight years old. They gave him a new name—Whirling Storm. When Whirling Storm grew up into a man, he became a chief and led his people wisely.", "ipa": "/wɛn ðə mɛn ænd bɔɪz rɪˈtɜːrnd frɒm ðɛər trɪp, ðə tʃiːfs dɪˈklɛərd ˈlɪtl ˈskwɪrəl ə mæn ˈiːvn ðoʊ hiː wɒz ˈoʊnli eɪt jɪərz oʊld. ðeɪ ɡeɪv hɪm ə njuː neɪm—ˈwɜːrlɪŋ stɔːrm. wɛn ˈwɜːrlɪŋ stɔːrm ɡruː ʌp ˈɪntuː ə mæn, hiː bɪˈkeɪm ə tʃiːf ænd lɛd hɪz ˈpiːpl ˈwaɪzli/", vi: "Khi đoàn người trở về, các bô lão quyết định công nhận Sóc Nhỏ đã là một người đàn ông thực thụ dù mới lên tám, và ban cho cậu cái tên mới — Bão Lốc. Khi trưởng thành, Bão Lốc trở thành tù trưởng và dẫn dắt bộ tộc ngày một hưng thịnh." }
    ]
  },
  {
    "day": 10,
    "title": "Birthday Party",
    "image": "08 August/images/day_10.webp",
    "audio": "08 August/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "All the kids are excited. It is Maria's birthday. Maria is turning seven. It is her first birthday in her new country. Maria moved to Canada from Mexico with her family.", "ipa": "/ɔːl ðə kɪdz ɑːr ɪkˈsaɪtɪd. ɪt ɪz məˈriːəz ˈbɜːrθdeɪ. məˈriːə ɪz ˈtɜːrnɪŋ ˈsɛvn. ɪt ɪz hɜːr fɜːrst ˈbɜːrθdeɪ ɪn hɜːr njuː ˈkʌntri. məˈriːə muːvd tuː ˈkænədə frɒm ˈmɛksɪkoʊ wɪð hɜːr ˈfæməli/", vi: "Đám trẻ vô cùng háo hức trong ngày sinh nhật lên bảy của Maria. Đây là sinh nhật đầu tiên của cô bé ở đất nước mới sau khi cùng gia đình chuyển từ Mexico sang Canada." },
      { "start": 18.0, "en": "Maria has many new friends. They are all at the birthday party. Everyone is having fun. They play some games. One game is called Pin the Tail on the Donkey.", "ipa": "/məˈriːə hæz ˈmɛni njuː frɛndz. ðeɪ ɑːr ɔːl æt ðə ˈbɜːrθdeɪ ˈpɑːrti. ˈɛvriˌwʌn ɪz ˈhævɪŋ fʌn. ðeɪ pleɪ sʌm ɡeɪmz. wʌn ɡeɪm ɪz kɔːld pɪn ðə teɪl ɒn ðə ˈdɒŋki/", vi: "Maria có rất nhiều bạn mới và tất cả đều có mặt tại bữa tiệc, ai nấy đều cười nói rôm rả và tham gia các trò chơi. Một trong số đó là trò 'Gắn đuôi lừa'." },
      { "start": 32.0, "en": "How do you play? There is a big picture of a donkey. You have a donkey's tail in your hand. You close your eyes and try to put the tail in the right place. You cannot see. It is fun and everyone is laughing.", "ipa": "/haʊ duː juː pleɪ? ðɛər ɪz ə bɪɡ ˈpɪktʃər əv ə ˈdɒŋki. juː hæv ə ˈdɒŋkiz teɪl ɪn jɔːr hænd. juː cloʊs jɔːr aɪz ænd traɪ tuː pʊt ðə teɪl ɪn ðə raɪt pleɪs. juː ˈkænɒt siː. ɪt ɪz fʌn ænd ˈɛvriˌwʌn ɪz ˈlɑːfɪŋ/", vi: "Luật chơi rất đơn giản: Trên tường treo bức tranh chú lừa lớn, bạn sẽ cầm chiếc đuôi lừa bị bịt mắt lại và mò mẫm dán vào đúng vị trí. Vì không thấy đường nên ai nấy cười ngất ngả." },
      { "start": 50.0, "en": "The best part of the party is the piñata. It is a big doll filled with candy. Maria closes her eyes. She tries to break the piñata with a stick. The candies fall out and everyone starts eating them.", "ipa": "/ðə bɛst pɑːrt əv ðə ˈpɑːrti ɪz ðə pɪˈnjɑːtə. ɪt ɪz ə bɪɡ dɒl fɪld wɪð ˈkændi. məˈriːə ˈcloʊzɪz hɜːr aɪz. ʃiː traɪz tuː breɪk ðə pɪˈnjɑːtə wɪð ə stɪk. ðə ˈkændiz fɔːl aʊt ænd ˈɛvriˌwʌn stɑːrts ˈiːtɪŋ ðɛm/", vi: "Phần hấp dẫn nhất tiệc chính là đập kẹo piñata — một hình nộm nhồi đầy kẹo ngọt. Maria bị bịt mắt dùng gậy đập vỡ hình nộm để kẹo tuôn rơi ào ạt cho mọi người cùng tranh nhau nhặt ăn." },
      { "start": 65.0, "en": "Maria's mom brings a cake. Maria blows out the candles. They all sing Happy Birthday. It is a very good party.", "ipa": "/məˈriːəz mɒm brɪŋz ə keɪk. məˈriːə bloʊz aʊt ðə ˈkændlz. ðeɪ ɔːl sɪŋ ˈhæpi ˈbɜːrθdeɪ. ɪt ɪz ə ˈvɛri ɡʊd ˈpɑːrti/", vi: "Mẹ mang bánh kem ra, Maria thổi nến trong tiếng hát chúc mừng sinh nhật vang dội của bạn bè. Quả là một bữa tiệc tuyệt vời." }
    ]
  },
  {
    "day": 11,
    "title": "Our Visit to a Village (I)",
    "image": "08 August/images/day_11.webp",
    "audio": "08 August/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "During our school break, my cousin and I went to Upper Canada Village with my parents. People in this village wear 19th century clothing and everything runs the same way it did one hundred years ago.", "ipa": "/ˈdjʊərɪŋ ˈaʊər skuːl breɪk, maɪ ˈkʌzn ænd aɪ wɛnt tuː ˈʌpər ˈkænədə ˈvɪlɪdʒ wɪð maɪ ˈpɛərənts. ˈpiːpl ɪn ðɪs ˈvɪlɪdʒ wɛər ˈnaɪˈtiːnθ ˈsɛntʃəri ˈkloʊðɪŋ ænd ˈɛvriˌθɪŋ rʌnz ðə seɪm weɪ ɪt dɪd wʌn ˈhʌndrəd jɪərz əˈɡoʊ/", vi: "Trong kỳ nghỉ học, tôi cùng anh họ theo bố mẹ đến thăm Làng cổ Upper Canada. Người dân ở đây mặc trang phục thế kỷ 19 và mọi sinh hoạt đều diễn ra y hệt như cách đây một thế kỷ." },
      { "start": 18.0, "en": "'This is amazing,' said my cousin. 'It's living history!' First, we went to the flour mill. It still works, just like it did long ago. At one end of the mill, people load in the dry grain. At the other end, the flour comes out. 'Wow!' my cousin cried out.", "ipa": "/ðɪs ɪz əˈmeɪzɪŋ, sɛd maɪ ˈkʌzn. ɪts ˈlɪvɪŋ ˈhɪstəri! fɜːrst, wiː wɛnt tuː ðə ˈflaʊər mɪl. ɪt stɪl wɜːrks, dʒʌst laɪk ɪt dɪd lɒŋ əˈɡoʊ. æt wʌn ɛnd əv ðə mɪl, ˈpiːpl loʊd ɪn ðə draɪ ɡreɪn. æt ðə ˈʌðər ɛnd, ðə ˈflaʊər kʌmz aʊt. waʊ!, maɪ ˈkʌzn kraɪd aʊt/", vi: "'Thật tuyệt diệu,' anh họ tôi thốt lên. 'Đây là lịch sử sống động!' Đầu tiên, chúng tôi ghé xối xay bột. Nơi đây vẫn hoạt động như thuở xưa: đầu này đổ ngũ cốc khô vào, đầu kia bột mì mịn màng chảy ra. 'Ôi chao!' anh họ tôi reo lên thích thú." },
      { "start": 39.0, "en": "It was his first time seeing how flour is made. The worker told us that this flour mill was a busy place back in 1821.", "ipa": "/ɪt wɒz hɪz fɜːrst taɪm ˈsiːɪŋ haʊ ˈflaʊər ɪz meɪd. ðə ˈwɜːrkər toʊld ʌs ðæt ðɪs ˈflaʊər mɪl wɒz ə ˈbɪzi pleɪs bæk ɪn ˌeɪtiˈwʌn/", "vi": "Đây là lần đầu tiên cậu được tận mắt thấy quy trình làm bột mì. Người thợ hướng dẫn cho biết cối xay này từng vô cùng tấp nập từ tận năm 1821." },
      { "start": 51.0, "en": "At that time, wheat was Canada's main agricultural crop. Turning wheat into flour was in high demand. Samuel Bellamy built the mill. He received grain from his farmer neighbours. His mill transformed the grain into flour. He wasn't paid with money. Instead, he kept one twelfth of the wheat he ground. My cousin exclaimed, 'I really like the way people traded at that time.' 'Me too!' I replied.", "ipa": "/æt ðæt taɪm, wiːt wɒz ˈkænədəz meɪn ˌæɡrɪˈkʌltʃərəl krɒp. ˈtɜːrnɪŋ wiːt ˈɪntuː ˈflaʊər wɒz ɪn haɪ dɪˈmænd. ˈsæmjuəl ˈbɛləmi bɪlt ðə mɪl. hiː rɪˈsiːvd ɡreɪn frɒm hɪz ˈfɑːrmər ˈneɪbərz. hɪz mɪl trænsˈfɔːrmd ðə ɡreɪn ˈɪntuː ˈflaʊər. hiː ˈwɒznt peɪd wɪð ˈmʌni. ɪnˈstɛd, hiː kɛpt wʌn twɛlfθ əv ðə wiːt hiː ɡraʊnd. maɪ ˈkʌzn ɪkˈskleɪmd, aɪ ˈrɪəli laɪk ðə weɪ ˈpiːpl ˈtreɪdɪd æt ðæt taɪm. miː tuː!, aɪ rɪˈplaɪd/", vi: "Thời đó, lúa mì là cây trồng chủ lực của Canada và nhu cầu xay xát rất lớn. Do Samuel Bellamy xây dựng, cối xay nhận lúa mì từ các nông dân láng giềng và chế biến thành bột mì. Ông không nhận tiền mặt mà giữ lại một phần mười hai số lúa mì đem xay làm thù lao. 'Tớ cực kỳ thích cách trao đổi hàng hóa thời đó,' anh họ thốt lên. 'Tớ cũng vậy!' tôi đáp." }
    ]
  },
  {
    "day": 12,
    "title": "Our Visit to a Village (II)",
    "image": "08 August/images/day_12.webp",
    "audio": "08 August/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "As we moved on to the next house, we came to a blacksmith's shop. We all know that blacksmiths are people who create things from iron. But what we don't know is how important their work was long ago.", "ipa": "/æz wiː muːvd ɒn tuː ðə nɛkst haʊs, wiː keɪm tuː ə ˈblæksmɪθs ʃɒp. wiː ɔːl noʊ ðæt ˈblæksmɪθs ɑːr ˈpiːpl huː kriˈeɪt θɪŋz frɒm ˈaɪər. bʌt wɒt wiː doʊnt noʊ ɪz haʊ ɪmˈpɔːrtənt ðɛər wɜːrk wɒz lɒŋ əˈɡoʊ/", vi: "Rời nhà cối xay, chúng tôi ghé qua lò rèn. Ai cũng biết thợ rèn là người tạo ra các vật dụng bằng sắt, nhưng ít ai tường tận nghề này từng quan trọng thế nào trong quá khứ." },
      { "start": 18.0, "en": "The man told us, 'Back then, blacksmiths made tools for the villagers. They also helped make and repair mill machines.' He went on, 'Blacksmith services were essential to people's everyday lives. They kept a community in good running order.'", "ipa": "/ðə mæn toʊld ʌs, bæk ðɛn, ˈblæksmɪθs meɪd tuːlz fɔːr ðə ˈvɪlɪdʒərz. ðeɪ ˈɔːlsoʊ hɛlpt meɪk ænd rɪˈpɛər mɪl məˈʃiːnz. hiː wɛnt ɒn, ˈblæksmɪθ ˈsɜːrvɪsɪz wɜːr ɪˈsɛnʃl tuː ˈpiːplz ˈɛvriˌdeɪ laɪvz. ðeɪ kɛpt ə kəˈmjuːnəti ɪn ɡʊd ˈrʌnɪŋ ˈɔːrdər/", vi: "Người thợ rèn chia sẻ: 'Hồi đó, thợ rèn làm dụng cụ lao động cho dân làng, đồng thời chế tạo và sửa chữa máy móc cho cối xay.' Ông nói thêm: 'Dịch vụ của thợ rèn sống còn với đời sống thường nhật, giúp cộng đồng vận hành trơn tru.'" },
      { "start": 35.0, "en": "'How much did a blacksmith earn in a day?' I asked. 'A quarter,' the man replied. 'You mean 25 cents?!' 'Yes. It was the highest paid job at the time,' said the man.", "ipa": "/haʊ mʌtʃ dɪd ə ˈblæksmɪθ ɜːrn ɪn ə deɪ?, aɪ ɑːskt. ə ˈkwɔːrtər, ðə mæn rɪˈplaɪd. juː miːn ˈtwɛnti-faɪv sɛnts?! jɛs. ɪt wɒz ðə ˈhaɪɪst peɪd dʒɒb æt ðə taɪm, sɛd ðə mæn/", vi: "'Thợ rèn kiếm được bao nhiêu tiền một ngày ạ?' tôi tò mò. 'Một đồng tư,' ông đáp. 'Ý bác là 25 xu á?!' 'Đúng vậy, đó là nghề có thu nhập cao nhất thời bấy giờ đấy.'" },
      { "start": 51.0, "en": "After that, we watched the man skilfully make a horseshoe from a piece of red hot iron. We were tempted to try it ourselves. The man handed us some hammers, and then my cousin and I hit the hot metal! Strike the iron while it's hot! Now we had done it.", "ipa": "/ˈɑːftər ðæt, wiː wɒtʃt ðə mæn ˈskɪlfʊli meɪk ə ˈhɔːrsˌʃuː frɒm ə piːs əv rɛd hɒt ˈaɪər. wiː wɜːr ˈtɛmptɪd tuː traɪ ɪt ɔːlˈsɛlvz. ðə mæn ˈhændɪd ʌs sʌm ˈhæmərz, ænd ðɛn maɪ ˈkʌzn ænd aɪ hɪt ðə hɒt ˈmɛtl! straɪk ði ˈaɪər waɪl ɪts hɒt! naʊ wiː hæd dʒʌst dʌn ɪt/", "vi": "Tiếp đó, chúng tôi trầm trồ chứng kiến bác thợ rèn tài hoa uốn nắn thanh sắt đỏ rực thành chiếc móng ngựa. Thấy ngứa tay, hai anh em liền xin phép thử sức. Bác thợ đưa búa cho chúng tôi đập vào miếng kim loại nóng hổi! Sắt nung nóng phải đập ngay khi còn đỏ lửa! Thế là chúng tôi đã làm được rồi." }
    ]
  },
  {
    "day": 13,
    "title": "What Is Rain?",
    "image": "08 August/images/day_13.webp",
    "audio": "08 August/audio/Track13.mp3",
    "sentences": [
      { "start": 4.8, "en": "Look up at the clouds. They are very pretty. They are also filled with water. Rain comes from clouds in the sky. Rain is water that falls from the sky.", "ipa": "/lʊk ʌp æt ðə klaʊdz. ðeɪ ɑːr ˈvɛri ˈprɪti. ðeɪ ɑːr ˈɔːlsoʊ fɪld wɪð ˈwɔːtər. reɪn kʌmz frɒm klaʊdz ɪn ðə skaɪ. reɪn ɪz ˈwɔːtər ðæt fɔːlz frɒm ðə skaɪ/", vi: "Ngước nhìn những tầng mây trên cao kìa, chúng thật đẹp và chứa đầy hơi nước. Mưa xuất phát từ những đám mây trên trời. Mưa chính là nước rơi xuống từ bầu trời." },
      { "start": 16.0, "en": "It rains in spring. It rains in summer. It rains in fall. But it does not rain in winter.", "ipa": "/ɪt reɪnz ɪn sprɪŋ. ɪt reɪnz ɪn ˈsʌmər. ɪt reɪnz ɪn fɔːl. bʌt ɪt dʌz nɒt reɪn ɪn ˈwɪntər/", vi: "Trời mưa vào mùa xuân, mùa hè, mùa thu, nhưng thường không mưa vào mùa đông lạnh giá." },
      { "start": 25.0, "en": "Rain is very important. It gives animals water to drink. It gives plants water too. Everything on earth needs water. That is why rain is so important.", "ipa": "/reɪn ɪz ˈvɛri ɪmˈpɔːrtənt. ɪt ɡɪvz ˈænɪmlz ˈwɔːtər tuː drɪŋk. ɪt ɡɪvz plɑːnts ˈwɔːtər tuː. ˈɛvriˌθɪŋ ɒn ɜːrθ niːdz ˈwɔːtər. ðæt ɪz waɪ reɪn ɪz soʊ ɪmˈpɔːrtənt/", vi: "Mưa vô cùng quan trọng. Mưa cung cấp nước uống cho động vật và tưới mát cây cối. Mọi sinh vật trên Trái Đất đều cần nước, đó là lý do mưa lại quan trọng đến thế." },
      { "start": 39.0, "en": "Look at a lake, a river or an ocean. That is a lot of water. Where does it come from? It comes from rain. When it rains, the lakes, rivers and oceans catch the rain. They fill up with water. That is how nature works.", "ipa": "/lʊk æt ə leɪk, ə ˈrɪvər ɔːr ən ˈoʊʃn. ðæt ɪz ə lɒt əv ˈwɔːtər. wɛər dʌz ɪt kʌm frɒm? ɪt kʌmz frɒm reɪn. wɛn ɪt reɪnz, ðə leɪks, ˈrɪvərz ænd ˈoʊʃnz kætʃ ðə reɪn. ðeɪ fɪl ʌp wɪð ˈwɔːtər. ðæt ɪz haʊ ˈneɪtʃər wɜːrks/", vi: "Nhìn hồ, sông hay đại dương mà xem, lượng nước thật khổng lồ. Chúng từ đâu ra vậy? Chính là từ nước mưa. Khi trời mưa, ao hồ sông biển hứng lấy nước mưa để luôn đầy ắp. Quy luật tự nhiên là thế đấy." },
      { "start": 56.0, "en": "Spring rain is especially important to farmers. Just listen to this Chinese saying: Rain in the spring is as precious as oil.", "ipa": "/sprɪŋ reɪn ɪz ɪˈspɛʃəli ɪmˈpɔːrtənt tuː ˈfɑːrmərz. dʒʌst ˈlɪsn tuː ðɪs ˈtʃaɪˈniːz ˈseɪɪŋ: reɪn ɪn ðə sprɪŋ ɪz æz ˈprɛʃəs æz ɔɪl/", vi: "Mưa xuân đặc biệt quan trọng đối với nông dân. Hãy ngẫm câu thành ngữ: 'Mưa xuân quý như dầu'." }
    ]
  },
  {
    "day": 14,
    "title": "Blowing Glass",
    "image": "08 August/images/day_14.webp",
    "audio": "08 August/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "Have you ever touched glass? It's hard, right? Well, glass is hard most of the time. But, when glass gets very, very hot, it becomes soft. It can be blown up like a balloon to make bottles, jars and jugs.", "ipa": "/hæv juː ˈɛvər tʌtʃt ɡlɑːs? ɪts hɑːrd, raɪt? wɛl, ɡlɑːs ɪz hɑːrd moʊst əv ðə taɪm. bʌt, wɛn ɡlɑːs ɡɛts ˈvɛri, ˈvɛri hɒt, ɪt bɪˈkʌmz sɒft. ɪt kæn biː bloʊn ʌp laɪk ə bəˈluːn tuː meɪk ˈbɒtlz, dʒɑːrz ænd dʒʌɡz/", vi: "Bạn đã bao giờ chạm vào thủy tinh chưa? Nó cứng đúng không? Thực ra thủy tinh chỉ cứng hầu hết thời gian, nhưng khi được nung cực nóng, nó sẽ mềm nhũn và có thể thổi phồng như bong bóng để chế tạo chai lọ, bình chứa." },
      { "start": 19.0, "en": "Glass is made by heating a mixture of sand and other things in a furnace for up to 24 hours. Then, a small bit of the hot glass is put on the end of a long metal pipe that looks like a straw.", "ipa": "/ɡlɑːs ɪz meɪd baɪ ˈhiːtɪŋ ə ˈmɪkstʃər əv sænd ænd ˈʌðər θɪŋz ɪn ə ˈfɜːrnɪs fɔːr ʌp tuː ˈtwɛnti-fɔːr ˈaʊərz. ðɛn, ə smɔːl bɪt əv ðə hɒt ɡlɑːs ɪz pʊt ɒn ði ɛnd əv ə lɔːŋ ˈmɛtl paɪp ðæt lʊks laɪk ə strɔː/", vi: "Thủy tinh được tạo ra bằng cách nung hỗn hợp cát cùng các thành phần khác trong lò suốt 24 tiếng. Sau đó, một nhúm thủy tinh nóng chảy được đặt vào đầu một ống kim loại dài trông như ống hút." },
      { "start": 35.0, "en": "Next, air is blown into the pipe. This makes an air bubble in the soft, hot glass at the end of the pipe. The glass blows up like a balloon!", "ipa": "/nɛkst, ɛər ɪz bloʊn ˈɪntuː ðə paɪp. ðɪs meɪks ən ɛər ˈbʌbl ɪn ðə sɒft, hɒt ɡlɑːs æt ði ɛnd əv ðə paɪp. ðə ɡlɑːs bloʊz ʌp laɪk ə bəˈluːn!/", vi: "Tiếp theo, thợ thổi luồng không khí vào ống, tạo ra một bong bóng khí trong khối thủy tinh mềm ở đầu ống. Khối thủy tinh phồng to hệt như quả bóng bay!" },
      { "start": 48.0, "en": "It's reheated and blown up more until it's the right shape. This process is called 'blowing glass'. Once the glass cools down, it becomes hard. Then, you can touch it and use it.", "ipa": "/ɪts ˌriːˈhiːtɪd ænd bloʊn ʌp mɔːr ənˈtɪl ɪts ðə raɪt ʃeɪp. ðɪs ˈproʊsɛs ɪz kɔːld ˈbloʊɪŋ ɡlɑːs. wʌns ðə ɡlɑːs kuːlz daʊn, ɪt bɪˈkʌmz hɑːrd. ðɛn, juː kæn tʌtʃ ɪt ænd juːz ɪt/", vi: "Sản phẩm được nung lại và thổi phồng tiếp cho đến khi đạt hình dáng mong muốn. Quá trình này gọi là 'thổi thủy tinh'. Khi nguội đi, thủy tinh sẽ cứng lại và bạn có thể chạm vào sử dụng." },
      { "start": 63.0, "en": "But even though glass is hard, you have to be careful. It can still break!", "ipa": "/bʌt ˈiːvn ðoʊ ɡlɑːs ɪz hɑːrd, juː hæv tuː biː ˈkɛrfʊl. ɪt kæn stɪl breɪk!/", "vi": "Tuy nhiên, dù cứng cáp thì thủy tinh vẫn rất dễ vỡ nên bạn phải luôn cẩn thận nhé!" }
    ]
  },
  {
    "day": 15,
    "title": "Lots of Presents",
    "image": "08 August/images/day_15.webp",
    "audio": "08 August/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was Jessie's birthday. He was holding a big box wrapped in pretty red and gold paper. It also had a big gold bow on top. Jessie took off the gold bow very carefully. Then, he took off the red and gold paper very carefully. Underneath was the box. Mom and Dad said, 'Open it!'", "ipa": "/ɪt wɒz ˈdʒɛsiz ˈbɜːrθdeɪ. hiː wɒz ˈhoʊldɪŋ ə bɪɡ bɒks ræpt ɪn ˈprɪti rɛd ænd ɡoʊld ˈpeɪpər. ɪt ˈɔːlsoʊ hæd ə bɪɡ ɡoʊld boʊ ɒn tɒp. ˈdʒɛsi tʊk ɒf ðə ɡoʊld boʊ ˈvɛri ˈkɛrfəli. ðɛn, hiː tʊk ɒf ðə rɛd ænd ɡoʊld ˈpeɪpər ˈvɛri ˈkɛrfəli. ˌʌndərˈniːθ wɒz ðə bɒks. mɒm ænd dæd sɛd, ˈoʊpən ɪt!/", vi: "Hôm nay là sinh nhật của Jessie. Cậu đang ôm một chiếc hộp lớn gói bằng giấy đỏ vàng rực rỡ đính nơ vàng to bản. Jessie cẩn thận gỡ chiếc nơ rồi bóc lớp giấy gói. Bên dưới là một chiếc hộp. Bố mẹ giục: 'Mở ra đi con!'" },
      { "start": 26.0, "en": "Jessie opened the box and took out a great big red truck! It had bells and a ladder. It was a fire truck! Jessie climbed into the box. It was a pirate ship! Jessie pulled the red and gold paper around his shoulders. It was a prince's cape!", "ipa": "/ˈdʒɛsi ˈoʊpənd ðə bɒks ænd tʊk aʊt ə ɡreɪt bɪɡ rɛd trʌk! ɪt hæd bɛlz ænd ə ˈlædər. ɪt wɒz ə ˈfaɪər trʌk! ˈdʒɛsi klaɪmd ˈɪntuː ðə bɒks. ɪt wɒz ə ˈpaɪrət ʃɪp! ˈdʒɛsi pʊld ðə rɛd ænd ɡoʊld ˈpeɪpər əˈraʊnd hɪz ˈʃoʊldərz. ɪt wɒz ə ˈprɪnsɪz keɪp!/", vi: "Jessie mở hộp và lấy ra một chiếc xe tải màu đỏ bự chảng có gắn chuông và thang — đó là xe cứu hỏa! Cậu trèo vào trong hộp — biến thành chiếc tàu cướp biển! Cậu quấn tấm giấy gói đỏ vàng quanh vai — hóa ra lại là chiếc áo choàng hoàng tử!" },
      { "start": 48.0, "en": "Jessie then put the beautiful gold bow on Mom's head. She was a princess! Dad smiled, 'Do you like your present?' Jessie laughed, 'I love ALL of my presents: the truck, the pirate ship, the prince's cape and the crown for Mom!' 'This is the best birthday ever!'", "ipa": "/ˈdʒɛsi ðɛn pʊt ðə ˈbjuːtɪfl ɡoʊld boʊ ɒn mɒmz hɛd. ʃiː wɒz ə ˈprɪnsɛs! dæd smaɪld, duː juː laɪk jɔːr ˈprɛznt? ˈdʒɛsi lɑːft, aɪ lʌv ɔːl əv maɪ ˈprɛznts: ðə trʌk, ðə ˈpaɪrət ʃɪp, ðə ˈprɪnsɪz keɪp ænd ðə kraʊn fɔːr mɒm! ðɪs ɪz ðə bɛst ˈbɜːrθdeɪ ˈɛvər!/", "vi": "Jessie liền đội chiếc nơ vàng xinh xắn lên đầu mẹ — mẹ trở thành công chúa! Bố mỉm cười: 'Con có thích quà của mình không?' Jessie cười vang: 'Con thích TẤT CẢ các món quà: Xe tải, tàu hải tặc, áo choàng hoàng tử và cả vương miện của mẹ nữa! Đây là sinh nhật tuyệt vời nhất trên đời!'" }
    ]
  },
  {
    "day": 16,
    "title": "Our New Car",
    "image": "08 August/images/day_16.webp",
    "audio": "08 August/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "In my country, most people can't afford new cars. They repair their old cars and keep them for a long time. But, our car was so old that it just could not be fixed anymore. So one day, my dad said to me and my sisters, 'Okay girls, it's time to buy a new car!'", "ipa": "/ɪn maɪ ˈkʌntri, moʊst ˈpiːpl kænt əˈfɔːrd njuː kɑːrz. ðeɪ rɪˈpɛər ðɛər oʊld kɑːrz ænd kiːp ðɛm fɔːr ə lɒŋ taɪm. bʌt, ˈaʊər kɑːr wɒz soʊ oʊld ðæt ɪt dʒʌst kʊd nɒt biː fɪkst ˈɛniˌmɔːr. soʊ wʌn deɪ, maɪ dæd sɛd toʊ miː ænd maɪ ˈsɪstərz, oʊˈkeɪ ɡɜːrlz, ɪts taɪm tuː baɪ ə njuː kɑːr!/", vi: "Ở xứ tôi, phần lớn mọi người không đủ tiền mua xe mới nên thường sửa xe cũ để đi qua năm tháng. Nhưng chiếc xe nhà tôi đã quá cũ kỹ đến mức không sửa được nữa. Thế là một hôm, bố bảo ba chị em: 'Được rồi các con, đến lúc phải mua một chiếc xe mới thôi!'" },
      { "start": 22.0, "en": "We looked at many nice cars. But, we could not afford any of them. We were very sad. At the car lot, the car dealer was selling a very expensive car to a lady, but the car would not start.", "ipa": "/wiː lʊkt æt ˈmɛni naɪs kɑːrz. bʌt, wiː kʊd nɒt əˈfɔːrd ˈɛni əv ðɛm. wiː wɜːr ˈvɛri sæd. æt ðə kɑːr lɒt, ðə kɑːr ˈdiːlər wɒz ˈsɛlɪŋ ə ˈvɛri ɪkˈspɛnsɪv kɑːr tuː ə ˈleɪdi, bʌt ðə kɑːr wʊd nɒt stɑːrt/", "vi": "Chúng tôi xem qua rất nhiều dòng xe đẹp nhưng ngặt nỗi không đủ tiền mua chiếc nào, ai nấy đều buồn thiu. Tại bãi xe, nhân viên bán hàng đang chốt bán chiếc ô tô đắt tiền cho một vị khách nữ, nhưng ngặt nỗi động cơ mãi không chịu nổ." },
      { "start": 38.0, "en": "Because my dad knows everything about cars, he offered to help. He fixed the problem and the lady ended up buying the car! The car dealer was grateful and told my dad, 'I have a used car that you can have for free if you will work for me. I would like you to fix my cars.' That day, Dad got a new car and a new job!", "ipa": "/bɪˈkɒz maɪ dæd noʊz ˈɛvriˌθɪŋ əv kɑːrz, hiː ˈɒfərd tuː hɛlp. hiː fɪkst ðə ˈprɒbləm ænd ðə ˈleɪdi ˈɛndɪd ʌp ˈbaɪɪŋ ðə kɑːr! ðə kɑːr ˈdiːlər wɒz ˈɡreɪtfʊl ænd toʊld maɪ dæd, aɪ hæv ə juːzd kɑːr ðæt juː kæn hæv fɔːr friː ɪf juː wɪl wɜːrk fɔːr miː. aɪ wʊd laɪk juː tuː fɪks maɪ kɑːrz. ðæt deɪ, dæd ɡɒt ə njuː kɑːr ænd ə njuː dʒɒb!/", vi: "Vốn là tay thợ rành rẽ mọi ngóc ngách về ô tô, bố bèn ngỏ ý giúp đỡ. Bố sửa xèo cái là xong và vị khách quyết định chốt đơn luôn! Ông chủ bãi xe vô cùng cảm kích liền bảo bố: 'Tôi có chiếc xe cũ tặng không cho anh, đổi lại anh về làm thợ sửa xe độc quyền cho tôi nhé.' Thế là hôm ấy, bố vừa có xe mới vừa có luôn việc làm mới!" }
    ]
  },
  {
    "day": 17,
    "title": "Someone Important",
    "image": "08 August/images/day_17.webp",
    "audio": "08 August/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, a young boy told his teacher, 'When I grow up, I want to be someone important. What will I do?' The teacher looked at the boy, and said, 'There are many important people in the world. Some people build bridges and ships. Some people, like doctors, help others.'", "ipa": "/wʌn deɪ, ə jʌŋ bɔɪ toʊld hɪz ˈtiːtʃər, wɛn aɪ ɡroʊ ʌp, aɪ wɒnt tuː biː ˈsʌmwʌn ɪmˈpɔːrtənt. wɒt wɪl aɪ duː? ðə ˈtiːtʃər lʊkt æt ðə bɔɪ, ænd sɛd, ðɛər ɑːr ˈmɛni ɪmˈpɔːrtənt ˈpiːpl ɪn ðə wɜːrld. sʌm ˈpiːpl bɪld brɪdʒɪz ænd ʃɪps. sʌm ˈpiːpl, laɪk ˈdɒktərz, hɛlp ˈʌðərz/", vi: "Một hôm, cậu học trò nhỏ hỏi thầy giáo: 'Lớn lên con muốn trở thành một nhân vật quan trọng. Con nên làm nghề gì ạ?' Thầy nhìn cậu bé rồi đáp: 'Trên đời có rất nhiều người quan trọng. Có người xây cầu cống tàu bè, có người làm bác sĩ cứu người.'" },
      { "start": 21.0, "en": "But then the old teacher said, 'I know a very important person. I have seen a lot of talent in him. This person can do almost anything if he tries his best.' 'Who is it? Is he in my class?' the boy asked.", "ipa": "/bʌt ðɛn ði oʊld ˈtiːtʃər sɛd, aɪ noʊ ə ˈvɛri ɪmˈpɔːrtənt ˈpɜːrsn. aɪ hæv siːn ə lɒt əv ˈtælənt ɪn hɪm. ðɪs ˈpɜːrsn kæn duː ˈɔːlmoʊst ˈɛniˌθɪŋ ɪf hiː traɪz hɪz bɛst. huː ɪz ɪt? ɪz hiː ɪn maɪ klɑːs?, ðə bɔɪ ɑːskt/", vi: "Rồi thầy giáo già chậm rãi nói tiếp: 'Thầy biết một nhân vật rất quan trọng. Thầy nhìn thấy vô vàn tiềm năng ở cậu ấy, người mà nếu cố gắng hết mình thì việc gì cũng làm được.' 'Ai vậy ạ? Cậu ấy học lớp mình hả thầy?' cậu bé tò mò hỏi." },
      { "start": 35.0, "en": "'Yes,' said the teacher. He smiled and said, 'It's you.' Then the teacher pointed to the other kids in the class and said, 'And her, and him, and her...' He looked at all the kids and then said, 'Not all of you will be famous, but you will all be someone important.' The kids were amazed by what their teacher had said.", "ipa": "/jɛs, sɛd ðə ˈtiːtʃər. hiː smaɪld ænd sɛd, ɪts juː. ðɛn ðə ˈtiːtʃər ˈpɔɪntɪd tuː ði ˈʌðər kɪdz ɪn ðə klɑːs ænd sɛd, ænd hɜːr, ænd hɪm, ænd hɜːr... hiː lʊkt æt ɔːl ðə kɪdz ænd ðɛn sɛd, nɒt ɔːl əv juː wɪl biː ˈfeɪməs, bʌt juː wɪl ɔːl biː ˈsʌmwʌn ɪmˈpɔːrtənt. ðə kɪdz wɜːr əˈmeɪzd baɪ wɒt ðɛər ˈtiːtʃər hæd sɛd/", vi: "'Đúng vậy,' thầy mỉm cười: 'Chính là em.' Thầy lần lượt chỉ tay vào các bạn khác trong lớp: 'Và em ấy, cậu ấy, cô bé kia nữa...' Cuối cùng thầy quét mắt nhìn toàn bộ học sinh: 'Không phải ai trong số các em cũng sẽ nổi tiếng, nhưng tất cả các em đều sẽ trở thành những nhân vật vô cùng quan trọng.' Cả lớp ngẩn người kinh ngạc trước lời dạy sâu sắc của thầy." }
    ]
  },
  {
    "day": 18,
    "title": "Life on the Farm",
    "image": "08 August/images/day_18.webp",
    "audio": "08 August/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "Billy lives in the city. His cousin Jane lives on a farm. In the summer, Billy visits Jane. There is always a lot to do on the farm.", "ipa": "/ˈbɪli lɪvz ɪn ðə ˈsɪti. hɪz ˈkʌzn dʒeɪn lɪvz ɒn ə fɑːrm. ɪn ðə ˈsʌmər, ˈbɪli ˈvɪzɪts dʒeɪn. ðɛər ɪz ˈɔːlweɪz ə lɒt tuː duː ɒn ðə fɑːrm/", vi: "Billy sống ở thành phố còn cô em họ Jane ở nông trại. Mùa hè năm nay Billy đến thăm Jane. Ở trang trại lúc nào cũng có vô vàn việc để làm." },
      { "start": 16.0, "en": "Every morning, Billy and Jane wake up early. They eat eggs and toast with butter. Jane's mother likes to ask them questions as they eat. 'Where do we get our eggs?' she asks. 'Easy,' says Billy. 'We get our eggs from the chickens in the chicken house.'", "ipa": "/ˈɛvri ˈmɔːrnɪŋ, ˈbɪli ænd dʒeɪn weɪk ʌp ˈɜːrli. ðeɪ iːt ɛɡz ænd toʊst wɪð ˈbʌtər. dʒeɪnz ˈmʌðər laɪks tuː ɑːsk ðɛm ˈkwɛstʃənz æz ðeɪ iːt. wɛər doʊ net ɡɛt ˈaʊər ɛɡz?, ʃiː ɑːsks. ˈiːzi, sɛd ˈbɪli. wiː ɡɛt ˈaʊər ɛɡz frɒm ðə ˈtʃɪkɪnz ɪn ðə ˈtʃɪkɪn haʊs/", vi: "Sáng nào hai đứa cũng dậy sớm, ăn trứng và bánh mì nướng bết bơ. Mẹ Jane thường đố các con trong lúc ăn: 'Trứng chúng ta ăn lấy từ đâu nào?' 'Dễ ợt,' Billy đáp. 'Trứng lấy từ lũ gà trong chuồng gà ạ.'" },
      { "start": 36.0, "en": "'Yes. And where do we get our bread?' 'Hmmm. That's not so easy,' says Billy. Jane's mother explains, 'Your uncle grows crops of wheat. We get grains from the crops and turn them into flour. Next, I use flour to make bread.'", "ipa": "/jɛs. ænd wɛər doʊ wiː ɡɛt ˈaʊər brɛd? həm. ðæts nɒt soʊ ˈiːzi, sɛd ˈbɪli. dʒeɪnz ˈmʌðər ɪkˈspleɪnz, jɔːr ˈʌŋkl ɡroʊz krɒps əv wiːt. wiː ɡɛt ɡreɪnz frɒm ðə krɒps ænd tɜːrn ðɛm ˈɪntuː ˈflaʊər. nɛkst, aɪ juːz ˈflaʊər tuː meɪk brɛd/", vi: "'Đúng thế. Thế bánh mì chúng ta ăn làm từ đâu?' 'Hừm, câu này khó nha,' Billy gãi đầu. Mẹ Jane giải thích: 'Bác con trồng lúa mì, thu hoạch hạt rồi đem đi xay thành bột mì, sau đó mẹ dùng bột để nhào nướng thành bánh mì.'" },
      { "start": 51.0, "en": "Jane is happy. She likes teaching her cousin more about life on the farm. 'And we get butter from cow's milk.' 'Very good,' says Jane's mother. 'Now, you know a lot about life on the farm, Billy.'", "ipa": "/dʒeɪn ɪz ˈhæpi. ʃiː laɪks ˈtiːtʃɪŋ hɜːr ˈkʌzn mɔːr əˈbaʊt laɪf ɒn ðə fɑːrm. ænd wiː ɡɛt ˈbʌtər frɒm kaʊz mɪlk. ˈvɛri ɡʊd, sɛd dʒeɪnz ˈmʌðər. naʊ, juː noʊ ə lɒt əv laɪf ɒn ðə fɑːrm, ˈbɪli/", vi: "Jane rất vui vì được hướng dẫn anh họ hiểu thêm về cuộc sống điền viên. 'Còn bơ thì làm từ sữa bò anh nhé.' 'Giỏi lắm,' mẹ khen. 'Bây giờ thì con rành rẽ khối thứ về đời sống nông trại rồi đấy Billy ạ.'" }
    ]
  },
  {
    "day": 19,
    "title": "Water into Wine (I)",
    "image": "08 August/images/day_19.webp",
    "audio": "08 August/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "Long ago, a wise king invited everyone to his palace for a feast. Everything was to be free. He asked only one thing of his guests. Each person was to bring a bottle of white wine.", "ipa": "/lɒŋ əˈɡoʊ, ə waɪz kɪŋ ɪnˈvaɪtɪd ˈɛvriˌwʌn tuː hɪz ˈpælɪs fɔːr ə fiːst. ˈɛvriˌθɪŋ wɒz tuː biː friː. hiː ɑːskt ˈoʊnli wʌn θɪŋ əv hɪz ɡɛsts. iːtʃ ˈpɜːrsn wɒz tuː brɪŋ ə ˈbɒtl əv waɪt waɪn/", vi: "Ngày xửa ngày xưa, một vị vua thông thái thiết yến hội đãi toàn dân tại cung điện. Mọi thứ đều miễn phí, ngài chỉ đưa ra một điều kiện duy nhất: Mỗi khách mời phải mang theo một chai rượu vang trắng." },
      { "start": 18.0, "en": "A man in the village wanted to go, but there was a problem. He did not have any wine to bring. 'I can buy some wine,' he thought. 'But it would be foolish to spend money for a party where everything is supposed to be free.'", "ipa": "/ə mæn ɪn ðə ˈvɪlɪdʒ ˈwɒntɪd tuː ɡoʊ, bʌt ðɛər wɒz ə ˈprɒbləm. hiː dɪd nɒt hæv ˈɛni waɪn tuː brɪŋ. aɪ kæn baɪ sʌm waɪn, hiː θɔːt. bʌt ɪt wʊd biː ˈfuːlɪʃ tuː spɛnd ˈmʌni fɔːr ə ˈpɑːrti wɛər ˈɛvriˌθɪŋ ɪz səˈpoʊzd tuː biː friː/", vi: "Có một người trong làng rất muốn đi dự tiệc nhưng ngặt nỗi không có chai rượu nào để mang theo. 'Mình có thể mua rượu,' hắn nghĩ bụng, 'nhưng thật ngốc nghếch khi phải tốn tiền vào một bữa tiệc mọi thứ đều miễn phí.'" },
      { "start": 35.0, "en": "The man thought about what he would do. He knew that there would be many people at the party. Each person would pour his wine into a big bowl, and everyone would drink from that bowl. 'Surely, no one will notice if I bring a bottle of water and pour that into the bowl,' said the man with a smile.", "ipa": "/ðə mæn θɔːt əˈbaʊt wɒt hiː wʊd duː. hiː nuː ðæt ðɛər wʊd biː ˈmɛni ˈpiːpl ænd ðə ˈpɑːrti. iːtʃ ˈpɜːrsn wʊd pɔːr hɪz waɪn ˈɪntuː ə bɪɡ boʊl, ænd ˈɛvriˌwʌn wʊd drɪŋk frɒm ðæt boʊl. ˈʃʊərli, noʊ wʌn wɪl ˈnoʊtɪs ɪf aɪ brɪŋ ə ˈbɒtl əv ˈwɔːtər ænd pɔːr ðæt ˈɪntuː ðə boʊl, sɛd ðə mæn wɪð ə smaɪl/", vi: "Hắn ta liền tính toán mưu mẹo. Hắn biết bữa tiệc có rất nhiều người tham gia, ai nấy đều đổ rượu vào một chiếc vại lớn để mọi người cùng thưởng thức. 'Chắc chắn chẳng ai nhận ra nếu mình mang một chai nước lọc đổ vào vại đâu,' hắn mỉm cười đắc ý." },
      { "start": 54.0, "en": "With so much wine in the bowl, a little water will not make a difference. And so, on the day of the feast, the man arrived at the palace with his bottle of water.", "ipa": "/wɪð soʊ mʌtʃ waɪn ɪn ðə boʊl, ə ˈlɪtl ˈwɔːtər wɪl nɒt meɪk ə ˈdɪfrəns. ænd soʊ, ɒn ðə deɪ əv ðə fiːst, ðə mæn əˈraɪvd æt ðə ˈpælɪs wɪð hɪz ˈbɒtl əv ˈwɔːtər/", vi: "Vói lượng rượu ngập vại như thế, chút nước lã pha vào chắc chắn chẳng khác biệt là bao. Thế là vào ngày hội yến, gã đàn ông mang theo chai nước rành rọt bước vào hoàng cung." }
    ]
  },
  {
    "day": 20,
    "title": "Water into Wine (II)",
    "image": "08 August/images/day_20.webp",
    "audio": "08 August/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "The man entered the palace and went to the table where the wine bowl was sitting. He slowly poured his water into the bowl. He watched as the other guests arrived, each adding the contents of their bottles to the bowl and greeting the king with a smile.", "ipa": "/ðə mæn ˈɛntərd ðə ˈpælɪs ænd wɛnt tuː ðə ˈteɪbl wɛər ðə waɪn boʊl wɒz ˈsɪtɪŋ. hiː ˈsloʊli pɔːrd hɪz ˈwɔːtər ˈɪntuː ðə boʊl. hiː wɒtʃt æz ði ˈʌðər ɡɛsts əˈraɪvd, iːtʃ ˈædɪŋ ðə ˈkɒntɛnts əv ðɛər ˈbɒtlz tuː ðə boʊl ænd ˈɡriːtɪŋ ðə kɪŋ wɪð ə smaɪl/", vi: "Hắn bước vào cung điện, tiến đến chiếc bàn đặt vại rượu rồi lén lút trút chai nước lọc của mình vào vại. Hắn đứng quan sát những vị khách khác lần lượt đổ rượu từ chai của họ vào vại và cúi đầu chào nhà vua." },
      { "start": 21.0, "en": "Soon, it was time for the meal to begin. The king asked everyone to fill their glasses with wine from the bowl. The guests did as they were told and took a sip of the wine. To everyone's surprise, the wine tasted like water.", "ipa": "/suːn, ɪt wɒz taɪm fɔːr ðə miːl tuː bɪˈɡɪn. ðə kɪŋ ɑːskt ˈɛvriˌwʌn tuː fɪl ðɛər ˈɡlæsɪz wɪð waɪn frɒm ðə boʊl. ðə ɡɛsts dɪd æz ðeɪ wɜːr toʊld ænd tʊk ə sɪp əv ðə waɪn. tuː ˈɛvriˌwʌnz sərˈpraɪz, ðə waɪn ˈteɪstɪd laɪk ˈwɔːtər/", vi: "Chẳng mấy chốc, bữa tiệc bắt đầu. Nhà vua mời tất cả nâng ly thưởng thức rượu từ vại chung. Các vị khách làm theo và nhấp một ngụm. Nhưng ôi thôi, vị rượu nhạt thếch hệt như nước lã khiến ai nấy há hốc mồm." },
      { "start": 38.0, "en": "The king discovered that everyone had brought water in their wine bottles! If only one person had added water to the wine, no one would have noticed. But, as it turned out, everyone thought that they would be able to cheat the king this way.", "ipa": "/ðə kɪŋ dɪsˈkʌvərd ðæt ˈɛvriˌwʌn hæd brɔːt ˈwɔːtər ɪn ðɛər waɪn ˈbɒtlz! ɪf ˈoʊnli wʌn ˈpɜːrsn hæd ˈædɪd ˈwɔːtər tuː ðə waɪn, noʊ wʌn wʊd hæv ˈnoʊtɪst. bʌt, æz ɪt tɜːrnd aʊt, ˈɛvriˌwʌn θɔːt ðæt ðeɪ wʊd biː ˈeɪbl tuː tʃiːt ðə kɪŋ ðɪs weɪ/", vi: "Nhà vua phẫn nộ phát hiện ra rằng hóa ra tất cả mọi người đều mang nước lọc đến thay cho rượu! Giá như chỉ một người chơi gian lận thì chẳng ai phát hiện ra, đằng này ai cũng ôm mộng khôn lỏi qua mặt nhà vua." },
      { "start": 56.0, "en": "The king sent all of his guests home, disappointed that his people had tried to pull such a dishonest trick on him.", "ipa": "/ðə kɪŋ sɛnt ɔːl əv hɪz ɡɛsts hoʊm, ˌdɪsəˈpɔɪntɪd ðæt hɪz ˈpiːpl hæd traɪd tuː pʊl sʌtʃ ə dɪsˈɒnɪst trɪk ɒn hɪm/", vi: "Nhà vua thất vọng đuổi toàn bộ khách về nhà, buồn rác vì thần dân của mình lại dám giở trò gian dối đê tiện nhường ấy." }
    ]
  },
  {
    "day": 21,
    "title": "What's Your Address?",
    "image": "08 August/images/day_21.webp",
    "audio": "08 August/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "I know where my house is on my street. I know where my street is in my town. I know where my country is on a map of the world. But sometimes, I wonder, 'Where is the earth?'", "ipa": "/aɪ noʊ wɛr maɪ haʊs ɪz ɒn maɪ striːt. aɪ noʊ wɛr maɪ striːt ɪz ɪn maɪ taʊn. aɪ noʊ wɛr maɪ ˈkʌntri ɪz ɒn ə mæp əv ðə wɜːrld. bʌt ˈsʌmˌtaɪmz, aɪ ˈwʌndər, wɛr ɪz ði ɜːrθ?/", vi: "Tôi biết nhà mình ở đâu trên phố, biết thị trấn nào trên bản đồ quốc gia. Nhưng thỉnh thoảng tôi vẫn tự hỏi: 'Thế Trái Đất nằm ở đâu trong vũ trụ?'" },
      { "start": 16.0, "en": "Imagine if you were trying to tell an alien from another planet your address! 'I live on 24 Flower Lane, Rome, Italy, Earth.' 'Where is that?' it might ask. That's a difficult question to answer.", "ipa": "/ɪˈmædʒɪn ɪf juː wɜːr ˈtraɪɪŋ tuː tɛl ən ˈeɪliən frɒm əˈnʌðər ˈplænɪt jɔːr əˈdrɛs! aɪ lɪv ɒn ˈtwɛnti-fɔːr ˈflaʊər leɪn, roʊm, ˈɪtəli, ɜːrθ. wɛr ɪz ðæt?, ɪt maɪt ɑːsk. ðæts ə ˈdɪfɪkəlt ˈkwɛstʃən tuː ˈɑːnsər/", vi: "Thử tưởng tượng nếu bạn phải khai địa chỉ nhà cho một người ngoài hành tinh xem! 'Tôi sống ở số 24 đường Flower, Roma, Ý, Trái Đất.' 'Nó ở đâu vậy?' sinh lạ đó sẽ hỏi. Quả là một câu hỏi khó nhằn để trả lời." },
      { "start": 32.0, "en": "We live in a galaxy called the 'Milky Way'. It gets its name from all the stars in it. There are so many stars that it looks white, just like milk.", "ipa": "/wiː lɪv ɪn ə ˈɡæləksi kɔːld ðə ˈmɪlki weɪ. ɪt ɡɛts ɪts neɪm frɒm ɔːl ðə stɑːrz ɪn ɪt. ðɛər ɑːr soʊ ˈmɛni stɑːrz ðæt ɪt lʊks waɪt, dʒʌst laɪk mɪlk/", vi: "Chúng ta đang cư ngụ trong một thiên hà tên là 'Ngân Hà' (Milky Way). Thiên hà mang tên này vì quy tụ vô số ngôi sao sáng rực trông xa trắng muốt hệt như dòng sữa." },
      { "start": 47.0, "en": "Our tiny planet sits near the edge of the Milky Way galaxy, with millions of other stars and planets. There are billions of galaxies too! Maybe one day, we will include our planet in our addresses!", "ipa": "/ˈaʊər ˈtaɪni ˈplænɪt sɪts nɪər ði ɛdʒ əv ðə ˈmɪlki weɪ ˈɡæləksi, wɪð ˈmɪljənz əv ˈʌðər stɑːrz ænd ˈplænɪts. ðɛər ɑːr ˈbɪljənz əv ˈɡæləksiz tuː! ˈmeɪbi wʌn deɪ, wiː wɪl ɪnˈkluːd ˈaʊər ˈplænɪt ɪn ˈaʊər əˈdrɛsɪz!/", vi: "Hành tinh tí xíu của chúng ta nằm sát rìa thiên hà Ngân Hà cùng hàng triệu ngôi sao và hành tinh khác. Ngoài kia còn có hàng tỷ thiên hà nữa! Biết đâu một ngày nào đó, chúng ta sẽ bổ sung cả tên hành tinh vào bưu thiếp địa chỉ nhà!" }
    ]
  },
  {
    "day": 22,
    "title": "Tabitha's Treasure",
    "image": "08 August/images/day_22.webp",
    "audio": "08 August/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "Tabitha was excited. Her mom had just asked her if she wanted to go on a treasure hunt. 'Sure!' Tabitha said. She loved treasure hunts. So, her mom handed her the first clue.", "ipa": "/ˈtæbɪθə wɒz ɪkˈsaɪtɪd. hɜːr mɒm hæd dʒʌst ɑːskt hɜːr ɪf ʃiː ˈwɒntɪd tuː ɡoʊ ɒn ə ˈtrɛʒər hʌnt. ʃʊər!, ˈtæbɪθə sɛd. ʃiː lʌvd ˈtrɛʒər hʌnts. soʊ, hɜːr mɒm ˈhændɪd hɜːr ðə fɜːrst kluː/", vi: "Tabitha vô cùng phấn khích khi được mẹ rủ tham gia trò chơi truy tìm khoẻ báu. 'Chắc chắn rồi!' Tabitha đáp vì con bé mê tít trò này. Mẹ liền trao cho cô bé tấm bản đồ manh mối đầu tiên." },
      { "start": 16.0, "en": "'Look into me and yourself you will see.' Tabitha solved it right away. 'That's the mirror,' she thought. She ran to the bathroom. There she found the second clue taped to the bathroom mirror.", "ipa": "/lʊk ˈɪntuː miː ænd jɔːrˈsɛlf juː wɪl siː. ˈtæbɪθə sɒlvd ɪt raɪt əˈweɪ. ðæts ðə ˈmɪrər, ʃiː θɔːt. ʃiː ræn tuː ðə ˈbɑːθruːm. ðɛər ʃiː faʊnd ðə ˈsɛkənd kluː teɪpt tuː ðə ˈbɑːθruːm ˈmɪrər/", vi: "'Hãy nhìn vào tôi, bạn sẽ thấy chính mình.' Tabitha giải mã ngay tắp lự: 'Là chiếc gương rồi!' Cô bé chạy vèo vào nhà tắm và tìm thấy manh mối thứ hai dán trên gương." },
      { "start": 29.0, "en": "She smiled as she read it. 'Piglet is my best friend.' 'It's Pooh Bear!' shouted Tabitha. She knew Pooh Bear would be holding the third clue. Yes, she was right. The third clue read, 'Brrr, it's cold in here!'", "ipa": "/ʃiː smaɪld æz ʃiː riːd ɪt. ˈpɪɡlɪt ɪz maɪ bɛst frɛnd. ɪts puː bɛər!, ˈʃaʊtɪd ˈtæbɪθə. ʃiː nuː puː bɛər wʊd biː ˈhoʊldɪŋ ðə θɜːrd kluː. jɛs, ʃiː wɒz raɪt. ðə θɜːrd kluː riːd, brɜːr, ɪts koʊld ɪn hɪər!/", vi: "Đọc xong cô bé mỉm cười: 'Heo con là bạn thân nhất của tôi.' 'Là gấu Pooh rồi!' Tabitha reo lên và đoán ngay gấu Pooh đang giữ manh mối thứ ba. Quả nhiên đúng vậy, manh mối này viết: 'Brrr, trong này lạnhngắt à ngắt nha!'" },
      { "start": 45.0, "en": "Tabitha went to the freezer and found the fourth clue taped to a popsicle! 'Now the last one. Hear the bell, open the door, and there you'll find treasure galore!' Just then, the doorbell rang. When Tabitha opened the door, she saw her friend, Beth. 'My treasure!' Tabitha exclaimed cheerfully.", "ipa": "/ˈtæbɪθə wɛnt tuː ðə ˈfriːzər ænd faʊnd ðə fɔːrθ kluː teɪpt tuː ə ˈpɒpsɪkl! naʊ ðə lɑːst wʌn. hɪər ðə bɛl, ˈoʊpən ðə dɔːr, ænd ðɛər jʊl faɪnd ˈtrɛʒər ɡəˈlɔːr! dʒʌst ðɛn, ðə ˈdɔːrˌbɛl ræŋ. wɛn ˈtæbɪθə ˈoʊpənd ðə dɔːr, ʃiː sɔː hɜːr frɛnd, bɛθ. maɪ ˈtrɛʒər!, ˈtæbɪθə ɪkˈskleɪmd ˈtʃɪərfəli/", vi: "Tabitha chạy ra tủ lạnh mở ngăn đông và tìm thấy manh mối thứ tư dán trên một cây kem que: 'Nghe tiếng chuông reo, mở cửa ra ngay, kho báu chờ đón ở đây rộn ràng!' Đúng lúc đó chuông cửa reo vang. Mở cửa ra, Tabitha thấy ngay cô bạn thân Beth đứng đó. 'Kho báu của tớ đây rồi!' Tabitha vui mừng ôm chầm lấy bạn." }
    ]
  },
  {
    "day": 23,
    "title": "Compost",
    "image": "08 August/images/day_23.webp",
    "audio": "08 August/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mike was the youngest in his family. His older brother and sister did important chores, like babysitting and mowing the lawn. Mike wanted to do an important chore too.", "ipa": "/maɪk wɒz ðə ˈjʌŋɡɪst ɪn hɪz ˈfæməli. hɪz ˈoʊldər ˈbrʌðər ænd ˈsɪstər dɪd ɪmˈpɔːrtənt tʃɔːrz, laɪk ˈbeɪbiˌsɪtɪŋ ænd ˈmoʊɪŋ ðə lɔːn. maɪk ˈwɒntɪd tuː duː ən ɪmˈpɔːrtənt tʃɔːr tuː/", vi: "Mike là cậu út trong nhà. Anh chị lớn đều làm những việc quan trọng như trông em hay cắt cỏ sân vườn, khiến Mike cũng khao khát được gánh vác một việc to tát." },
      { "start": 16.0, "en": "One day, Mom said, 'You can be in charge of the compost.' This didn't sound too important, but Mike started working anyway. He collected his family's kitchen waste. He put it in a bucket that his mom kept in the backyard and covered it.", "ipa": "/wʌn deɪ, mɒm sɛd, juː kæn biː ɪn tʃɑːrdʒ əv ðə ˈkɒmpoʊst. ðɪs ˈdɪdnt saʊnd tuː ɪmˈpɔːrtənt, bʌt maɪk ˈstɑːrtɪd ˈwɜːrkɪŋ ˈɛniˌweɪ. hiː kəˈlɛktɪd hɪz ˈfæməlɪz ˈkɪtʃɪn weɪst. hiː pʊt ɪt ɪn ə ˈbʌkɪt ðæt hɪz mɒm kɛpt ɪn ðə ˈbækˌjɑːrd ænd ˈkʌvərd ɪt/", vi: "Một hôm mẹ bảo: 'Con sẽ chịu trách nhiệm quản lý thùng ủ phân xanh nhé.' Nghe có vẻ không oai lắm nhưng Mike vẫn chăm chỉ bắt tay vào việc. Cậu thu gom thức ăn thừa nhà bếp bỏ vào chiếc xô mẹ đặt ở góc vườn và đậy nắp kín." },
      { "start": 32.0, "en": "Every Saturday, Mike mixed the waste with a shovel. It was smelly. And Mike could see worms in there. 'This doesn't seem like an important chore,' thought Mike. Still, he did his chore faithfully for ten long weeks.", "ipa": "/ˈɛvri ˈsætərdeɪ, maɪk mɪkst ðə weɪst wɪð ə ˈʃʌvl. ɪt wɒz ˈsmɛli. ænd maɪk kʊd siː wɜːrmz ɪn ðɛər. ðɪs ˈdʌznt siːm laɪk ən ɪmˈpɔːrtənt tʃɔːr, θɔːt maɪk. stɪl, hiː dɪd hɪz tʃɔːr ˈfeɪθfəli fɔːr tɛn lɒŋ wiːks/", vi: "Thứ Bảy hàng tuần, Mike dùng xẻng đảo đều đống rác hữu cơ. Mùi rất khó chịu và cậu còn thấy cả giun bò lúc nhúc. 'Việc này chẳng oai chút nào,' cậu thầm nghĩ. Dù vậy, cậu vẫn kiên trì làm việc đệm đều đặn suốt mười tuần ròng rã." },
      { "start": 48.0, "en": "'How is the compost coming along, Mike?' asked Mom. 'Is it ready?' 'Ready for what?' asked Mike. 'Follow me,' said Mike's mom. She spread the compost around her vegetable garden. 'This will help my vegetables grow. You made great compost!' Mike was proud.", "ipa": "/haʊ ɪz ðə ˈkɒmpoʊst ˈkʌmɪŋ əˈlɒŋ, maɪk?, ɑːskt mɒm. ɪz ɪt ˈrɛdi? ˈrɛdi fɔːr wɒt?, ɑːskt maɪk. ˈfɑːloʊ miː, sɛd maɪks mɒm. ʃiː sprɛd ðə ˈkɒmpoʊst əˈraʊnd hɜːr ˈvɛdʒtəbl ˈɡɑːrdn. ðɪs wɪl hɛlp maɪ ˈvɛdʒtəblz ɡroʊ. juː meɪd ɡreɪt ˈkɒmpoʊst! maɪk wɒz praʊd/", vi: "'Phân ủ tới đâu rồi con, đã dùng được chưa?' mẹ hỏi. 'Dùng làm gì hả mẹ?' 'Đi theo mẹ nào.' Mẹ mang phân xanh bón xung quanh các luống rau: 'Phân này giúp rau của mẹ xanh tốt lắm đấy. Con ủ phân siêu quá!' Mike phổng mũi tự hào." }
    ]
  },
  {
    "day": 24,
    "title": "First Babysitter",
    "image": "08 August/images/day_24.webp",
    "audio": "08 August/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "Emily is ten years old. One day, her next door neighbours, Mr. and Ms. Paulin, were going to a show. They asked if Emily wanted to babysit their son.", "ipa": "/ˈɛmɪli ɪz tɛn jɪərz oʊld. wʌn deɪ, hɜːr nɛkst dɔːr ˈneɪbərz, ˈmɪstər ænd mɪz ˈpɔːlɪn, wɜːr ˈɡoʊɪŋ tuː ə ʃoʊ. ðeɪ ɑːskt ɪf ˈɛmɪli ˈwɒntɪd tuː ˈbeɪbiˌsɪt ðɛər sʌn/", vi: "Emily mười tuổi. Một hôm, anh chị hàng xóm Paulin chuẩn bị ra ngoài xem biểu diễn nên ngỏ ý mời Emily sang trông con giúp họ." },
      { "start": 16.0, "en": "Emily loved children. And she loved to have extra money to buy her favourite things. She gladly said, 'Yes!'", "ipa": "/ˈɛmɪli lʌvd ˈtʃɪldrən. ænd ʃiː lʌvd tuː hæv ˈɛkstrə ˈmʌni tuː baɪ hɜːr ˈfeɪvərɪt θɪŋz. ʃiː ˈɡlædli sɛd, jɛs!/", vi: "Emily rất yêu trẻ con, lại thích kiếm thêm tiền tiêu vặt để mua món đồ mình thích nên vui vẻ nhận lời ngay." },
      { "start": 23.0, "en": "That day, the little boy wanted to cry when he saw his parents leave. He didn't want to let them go. Emily said to him, 'Do you want to guess what is in my hand?' The boy looked at Emily curiously, Emily played a magic game for him. Soon, the boy forgot all about his parents leaving.", "ipa": "/ðæt deɪ, ðə ˈlɪtl bɔɪ ˈwɒntɪd tuː kraɪ wɛn hiː sɔː hɪz ˈpɛərənts liːv. hiː ˈdɪdnt wɒnt tuː lɛt ðɛm ɡoʊ. ˈɛmɪli sɛd tuː hɪm, duː juː wɒnt tuː ɡɛs wɒt ɪz ɪn maɪ hænd? ðə bɔɪ lʊkt æt ˈɛmɪli ˈkjʊəriəsli, ˈɛmɪli pleɪd ə ˈmædʒɪk ɡeɪm fɔːr hɪm. suːn, ðə bɔɪ fərˈɡɒt ɔːl əˈbaʊt hɪz ˈpɛərənts ˈliːvɪŋ/", vi: "Hôm đó, cậu nhóc mếu máo sắp khóc khi thấy bố mẹ đi vắng. Emily liền đánh lạc hướng: 'Em có muốn đoán xem trong tay chị có gì không?' Cậu bé tròn xoe mắt tò mò. Emily biểu diễn vài trò ảo thuật nhỏ khiến cậu quên bẵng đi việc bố mẹ vừa đi." },
      { "start": 41.0, "en": "Then they played games, read books, had snacks, and went to the playground. When Mr. and Mrs. Paulin came home, the boy said, 'I had a great day with the babysitter. I want her to come back again!'", "ipa": "/ðɛn ðeɪ pleɪd ɡeɪmz, rɛd bʊks, hæd snæks, ænd wɛnt tuː ðə ˈpleɪˌɡraʊnd. wɛn ˈmɪstər ænd ˈmɪsɪz ˈpɔːlɪn keɪm hoʊm, ðə bɔɪ sɛd, aɪ hæd ə ɡreɪt deɪ wɪð ðə ˈbeɪbiˌsɪtər. aɪ wɒnt hɜːr tuː kʌm bæk əˈɡɛn!/", vi: "Sau đó hai chị em cùng chơi trò chơi, đọc sách, ăn quà vặt và ra công viên. Khi vợ chồng anh Paulin về đến nhà, cậu bé hí hửng khoe: 'Con chơi vui lắm, con muốn chị ý sang trông con lần sau nữa cơ!'" }
    ]
  },
  {
    "day": 25,
    "title": "Playing in the Rain!",
    "image": "08 August/images/day_25.webp",
    "audio": "08 August/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "I like to play. I like to play in the rain. But, there is a problem. I can't walk. I sit in a wheelchair all day. Does that mean I can't go outside when it rains? No, of course not.", "ipa": "/aɪ laɪk tuː pleɪ. aɪ laɪk tuː pleɪ ɪn ðə reɪn. bʌt, ðɛər ɪz ə ˈprɒbləm. aɪ kænt wɔːk. aɪ sɪt ɪn ə ˈwiːlˌtʃɛər ɔːl deɪ. dʌz ðæt miːn aɪ kænt ɡoʊ ˌaʊtˈsaɪd wɛn ɪt reɪnz? noʊ, əv kɔːrs nɒt/", vi: "Tôi thích chơi đùa, nhất là chơi dưới cơn mưa. Nhưng ngặt một nỗi tôi không thể đi lại được mà phải ngồi xe lăn suốt ngày. Điều đó có nghĩa là tôi không được ra ngoài chơi khi trời mưa sao? Không đâu, dĩ nhiên là được chứ." },
      { "start": 18.0, "en": "When I am outside, I need my hands to move the wheelchair. So, I can't carry an umbrella. Do I get wet? Not really. I wear an umbrella hat.", "ipa": "/wɛn aɪ æm ˌaʊtˈsaɪd, aɪ niːd maɪ hændz tuː muːv ðə ˈwiːlˌtʃɛər. soʊ, aɪ kænt ˈkæri ən ʌmˈbrɛlə. duː aɪ ɡɛt wɛt? nɒt ˈrɪəli. aɪ wɛər ən ʌmˈbrɛlə hæt/", vi: "Khi ra ngoài, tôi phải dùng đôi tay để đẩy xe lăn nên không thể cầm ô. Thế tôi có bị ướt không? Không hẳn đâu, vì tôi đã đội một chiếc mũ gắn ô trên đầu." },
      { "start": 29.0, "en": "People smile when they see me wearing an umbrella hat. It looks funny. They try hard to be polite and not laugh. Margaret is my best friend. She likes rainy days too. We like doing things together. We splash in puddles in the rain and we sing.", "ipa": "/ˈpiːpl smaɪld wɛn ðeɪ siː miː ˈwɛərɪŋ ən ʌmˈbrɛlə hæt. ɪt lʊks ˈfʌni. ðeɪ traɪ hɑːrd tuː biː pəˈlaɪt ænd nɒt lɑːf. ˈmɑːrɡrət ɪz maɪ bɛst frɛnd. ʃiː laɪks ˈreɪni deɪz tuː. wiː laɪk ˈduːɪŋ θɪŋz təˈɡɛðər. wiː splæʃ ɪn ˈpʌdlz ɪn ðə reɪn ænd wiː sɪŋ/", vi: "Mọi người tủm tỉm cười khi thấy chiếc mũ ô buồn cười của tôi và cố nhịn cười cho lịch sự. Margaret là bạn thân của tôi, cô ấy cũng cuồng những ngày mưa. Hai đứa thích vầy nước bì bõm và hát hò thỏa thích dưới mưa." },
      { "start": 51.0, "en": "Oh, there is one thing we have to watch out for. We have to be careful not to get too wet or our moms will be upset. But, we still love playing in the rain!", "ipa": "/oʊ, ðɛər ɪz wʌn θɪŋ wiː hæv tuː wɒtʃ aʊt fɔːr. wiː hæv tuː biː ˈkɛrfʊl nɒt tuː ɡɛt tuː wɛt ɔːr ˈaʊər mɒmz wɪl biː ʌpˈsɛt. bʌt, wiː stɪl lʌv ˈpleɪɪŋ ɪn ðə reɪn!/", vi: "À nà, có một điều chúng tôi phải chú ý là đừng để bị ướt sũng quá nếu không mẹ sẽ mắng. Dù vậy, chúng tôi vẫn cứ thích chơi đùa dưới mưa!" }
    ]
  },
  {
    "day": 26,
    "title": "Video Games",
    "image": "08 August/images/day_26.webp",
    "audio": "08 August/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "My mom doesn't like video games. One day, I had some friends over. We were playing video games and I was winning! Just then, my mom walked in the room and clicked off the television. I was so mad! Even worse, I felt really silly in front of my friends.", "ipa": "/maɪ mɒm ˈdʌznt laɪk ˈvɪdioʊ ɡeɪmz. wʌn deɪ, aɪ hæd sʌm frɛndz ˈoʊvər. wiː wɜːr ˈpleɪɪŋ ˈvɪdioʊ ɡeɪmz ænd aɪ wɒz ˈwɪnɪŋ! dʒʌst ðɛn, maɪ mɒm wɔːkt ɪn ðə ruːm ænd klɪkt ɔːf ðə ˈtɛlɪˌvɪʒn. aɪ wɒz soʊ mæd! ˈiːvn wɜːrs, aɪ fɛlt ˈrɪəli ˈsɪli ɪn frʌnt əv maɪ frɛndz/", vi: "Mẹ tôi cực kỳ ác cảm với trò chơi điện tử. Hôm nọ tôi mời bạn bè sang nhà chơi điện tử và tôi đang thắng thế! Bất ngờ mẹ bước vào phòng rút phích cắm ti vi cáiụp. Tôi điên tiết lên, lại còn muối mặt trước đám bạn." },
      { "start": 23.0, "en": "Then, my mom handed me a football and said, 'Alright, you kids. Outside for some fresh air. I don't want to see you inside for at least one hour!' 'An hour? It's cold outside!' we all said. 'Then put on your jackets and run around. You'll warm up!'", "ipa": "/ðɛn, maɪ mɒm ˈhændɪd miː ə ˈfʊtˌbɔːl ænd sɛd, ɔːlˈraɪt, juː kɪdz. ˌaʊtˈsaɪd fɔːr sʌm frɛʃ ɛr. aɪ doʊnt wɒnt tuː siː juː ɪnˈsaɪd fɔːr æt liːst wʌn ˈaʊər! ən ˈaʊər? ɪts koʊld ˌaʊtˈsaɪd! wiː ɔːl sɛd. ðɛn pʊt ɒn jɔːr ˈdʒækɪts ænd rʌn əˈraʊnd. jʊl wɔːrm ʌp!/", vi: "Rồi mẹ quẳng cho tôi quả bóng đá và bảo: 'Thôi đủ rồi các con, ra ngoài hít thở khí trời đi. Mẹ không muốn thấy bóng dáng đứa nào trong nhà ít nhất một tiếng nữa!' 'Một tiếng á? Ngoài trời lạnh lắm đấy!' chúng tôi kêu trời. 'Vậy mặc áo khoác vào rồi chạy nhảy đi, ấm người ngay thôi!'" },
      { "start": 43.0, "en": "Sadly, we all went outside. Then, Jimmy threw the ball a long way and I caught it. We chased each other around and fell in the dirt. And we started a football game. It was a lot of fun. Before we knew it, two hours had passed.", "ipa": "/ˈsædli, wiː ɔːl wɛnt ˌaʊtˈsaɪd. ðɛn, ˈdʒɪmi θruː ðə bɔːl ə lɔːŋ weɪ ænd aɪ kɔːt ɪt. wiː tʃeɪst iːtʃ ˈʌðər əˈraʊnd ænd fɛl ɪn ðə dɜːrt. ænd wiː ˈstɑːrtɪd ə ˈfʊtˌbɔːl ɡeɪm. ɪt wɒz ə lɒt əv fʌn. bɪˈfɔːr wiː nuː ɪt, tuː ˈaʊərz hæd pɑːst/", vi: "Chán nản kéo nhau ra sân, Jimmy tiện tay ném bóng đi xa và tôi chộp được. Thế là chúng tôi rượt đuổi nhau lăn lộn vào bùn đất và tổ chức luôn trận đá bóng. Vui không tưởng tượng được! Chẳng mấy chốc mà hai tiếng đồng hồ đã trôi qua vèo vèo." },
      { "start": 60.0, "en": "That day I learned that although video games are fun, nothing compares to real fun!", "ipa": "/ðæt deɪ aɪ lɜːrnd ðæt ɔːlˈðoʊ ˈvɪdioʊ ɡeɪmz ɑːr fʌn, ˈnʌθɪŋ kəmˈpɛərz tuː riːl fʌn!/", vi: "Hôm đó tôi đã nhận ra rằng dù game điện tử rất cuốn hút, nhưng chẳng gì sánh bằng niềm vui vận động thực tế ngoài trời!" }
    ]
  },
  {
    "day": 27,
    "title": "Honest Abe",
    "image": "08 August/images/day_27.webp",
    "audio": "08 August/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "In 1809, Abraham Lincoln was born in a log cabin in Kentucky. As a child, he had only one year of schooling. Books were very rare and so was paper. He had to write out his math problems on a wooden board using a knife!", "ipa": "/ɪn ˌeɪtiˈoʊ-naɪn, ˈeɪbrəhæm ˈlɪŋkən wɒz bɔːrn ɪn ə lɒɡ ˈkæbɪn ɪn kɛnˈtʌki. æz ə tʃaɪld, hiː hæd ˈoʊnli wʌn jɪər əv ˈskuːlɪŋ. bʊks wɜːr ˈvɛri rɛər ænd soʊ wɒz ˈpeɪpər. hiː hæd tuː raɪt aʊt hɪz mæθ ˈprɒbləmz ɒn ə ˈwʊdn bɔːrd ˈjuːzɪŋ ə naɪf!/", vi: "Năm 1809, Abraham Lincoln chào đời trong một căn nhà gỗ nghèo ở Kentucky. Thời thơ ấu, ông chỉ được đi học vỏn vẹn một năm. Sách vở và giấy viết vô cùng khan hiếm, cậu bé Lincoln phải dùng dao khắc các bài toán lên một tấm ván gỗ!" },
      { "start": 21.0, "en": "Sometimes, he would have to walk for miles just to borrow a book. But he loved to learn. Over time, he got the name 'Honest Abe'.", "ipa": "/ˈsʌmˌtaɪmz, hiː wʊd hæv tuː wɔːk fɔːr maɪlz dʒʌst tuː ˈbɒroʊ ə bʊk. bʌt hiː lʌvd tuː lɜːrn. ˈoʊvər taɪm, hiː ɡɒt ðə neɪm ˈɒnɪst eɪb/", vi: "Đôi khi ông phải đi bộ hàng dặm đường chỉ để mượn bằng được một cuốn sách. Vì ham học hỏi và luôn chân thật, người dân dần gọi ông với cái tên trìu mến 'Abe trung thực'." },
      { "start": 33.0, "en": "Once, while working in a store, he did not give a woman the right change. He followed her home so he could give her the six cents back.", "ipa": "/wʌns, waɪl ˈwɜːrkɪŋ ɪn ə stɔːr, hiː dɪd nɒt ɡɪv ə ˈwʊmən ðə raɪt tʃeɪndʒ. hiː ˈfɒloʊd hɜːr hoʊm soʊ hiː kʊd ɡɪv hɜːr ðə sɪks sɛnts bæk/", vi: "Có lần làm việc ở cửa hàng, vì thối nhầm tiền thừa cho một khách nữ, Lincoln đã cất công đi bộ theo tận nhà chỉ để trả lại bà sáu xu tiền thừa." },
      { "start": 47.0, "en": "By the time he was seventeen, he wanted to be a lawyer. Every day, he would walk 17 miles to the courthouse to watch the lawyers.", "ipa": "/baɪ ðə taɪm hiː wɒz ˈsɛvnˈtiːn, hiː ˈwɒntɪd tuː biː ə ˈlɔɪər. ˈɛvri deɪ, hiː wʊd wɔːk ˈsɛvnˈtiːn maɪlz tuː ðə ˈkɔːrθaʊs tuː wɒtʃ ðə ˈlɔɪərz/",vi: "Đến tuổi mười bảy, Lincoln nung nấu ước mơ trở thành luật sư. Ngày ngày, ông đi bộ 17 dặm tới tòa án thị trấn chỉ để đứng chăm chú quan sát các luật sư tranh tụng." },
      { "start": 59.0, "en": "He borrowed books and read them by the light of the fireplace. His hard work paid off. In 1861, he became president of the United States. Many people thought slavery was a good idea, but Lincoln did not. Today, he is most known for freeing all the slaves.", "ipa": "/hiː ˈbɒroʊd bʊks ænd rɛd ðɛm baɪ ðə laɪt əv ðə ˈfaɪərˌpleɪs. hɪz hɑːrd wɜːrk peɪd ɔːf. ɪn ˌeɪtiˈsɪksti-wʌn, hiː bɪˈkeɪm ˈprɛzɪdənt əv ðə juˈnaɪtɪd steɪts. ˈmɛni ˈpiːpl θɔːt ˈsleɪvəri wɒz ə ɡʊd aɪˈdiːə, bʌt ˈlɪŋkən dɪd nɒt. təˈdeɪ, hiː ɪz moʊst noʊn fɔːr ˈfriːɪŋ ɔːl ðə sleɪvz/", vi: "Ông mượn sách về nhà và miệt mài đọc dưới ánh lửaập lòe của lò sưởi. Sự chăm chỉ đã gặt hái quả ngọt: năm 1861, ông đắc cử Tổng thống Hợp chủng quốc Hoa Kỳ. Bất chấp nhiều người ủng hộ chế độ nô lệ lúc bấy giờ, Lincoln kiên quyết phản đối. Ngày nay, ông được tôn vinh nhất với công lao giải phóng nô lệ da màu." }
    ]
  },
  {
    "day": 28,
    "title": "What Animal Is This?",
    "image": "08 August/images/day_28.webp",
    "audio": "08 August/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "It lives in Africa. It's not a camel, but it can go for a long time without water. Can you guess what it is?", "ipa": "/ɪt lɪvz ɪn ˈæfrɪkə. ɪts nɒt ə ˈkæml, bʌt ɪt kæn ɡoʊ fɔːr ə lɒŋ taɪm wɪˈðaʊt ˈwɔːtər. kæn juː ɡɛs wɒt ɪt ɪz?/", vi: "Loài này sống ở châu Phi. Không phải lạc đà đâu nhé, nhưng chúng có thể nhịn khát cực lâu. Bạn đoán ra là con gì chưa?" },
      { "start": 14.0, "en": "Here are some more hints. This animal's heart weighs more than 20 kilograms. That's a BIG heart. Even more amazing—its heart pumps 650 litres of blood in only one minute. Do you know what it is?", "ipa": "/hɪər ɑːr sʌm mɔːr hɪnts. ðɪs ˈænɪmlz hɑːrt weɪz mɔːr ðæn ˈtwɛnti ˈkɪləˌɡræmz. ðæts ə bɪɡ hɑːrt. ˈiːvn mɔːr əˈmeɪzɪŋ—ɪts hɑːrt pʌmps ˈsɪks ˈhʌndrəd fɪfti ˈliːtərz əv blʌd ɪn ˈoʊnli wʌn ˈmɪnɪt. duː juː noʊ wɒt ɪt ɪz?/", vi: "Nghe thêm vài gợi ý nè. Trái tim của con vật này nặng hơn 20 kg — quả là một trái tim KHỔNG LỒ! Kỳ diệu hơn nữa, nó bơm tới 650 lít máu chỉ trong một phút. Bạn biết là con gì chưa?" },
      { "start": 30.0, "en": "Be careful if you ever stand behind this animal. It has long legs and can kick really hard. Its kick is so powerful that it can knock the head off a tiger. Watch out for flying legs.", "ipa": "/biː ˈkɛrfʊl ɪf juː ˈɛvər stænd bɪˈhaɪnd ðɪs ˈænɪml. ɪt hæz lɔːŋ lɛɡz ænd kæn kɪk ˈrɪəli hɑːrd. ɪts kɪk ɪz soʊ ˈpaʊərfʊl ðæt ɪt kæn nɒk ðə hɛd ɔːf ə ˈtaɪɡər. wɒtʃ aʊt fɔːr ˈflaɪɪŋ lɛɡz/", vi: "Hãy cẩn thận nếu đứng đằng sau loài vật này. Chúng có đôi chân dài và tung cú đá cực kỳ uy lực — mạnh đến mức có thể thổi bay đầu một con chúa sơn lâm. Cẩn thận cái chân phi nước đại đó nha." },
      { "start": 48.0, "en": "Still can't guess what it is? Well, here's another hint. You will probably be able to guess now. This animal is tall—VERY tall. It is the tallest animal in the world. Do you know what it is?", "ipa": "/stɪl kænt ɡɛs wɒt ɪt ɪz? wɛl, hɪərz əˈnʌðər hɪnt. juː wɪl ˈprɒbəbli biː ˈeɪbl tuː ɡɛs naʊ. ðɪs ˈænɪml ɪz tɔːl—ˈvɛri tɔːl. ɪt ɪz ðə ˈtɔːlɪst ˈænɪml ɪn ðə wɜːrld. duː juː noʊ wɒt ɪt ɪz?/", vi: "Vẫn chưa đoán ra sao? Thêm một gợi ý chốt hạ chắc chắn bạn sẽ biết ngay. Loài vật này rất cao — CỰC KỲ CAO. Chúng giữ kỷ lục là động vật cao nhất thế giới. Bạn biết là con gì chưa?" },
      { "start": 62.0, "en": "This final clue will give it away. It has a long neck. Its neck weighs more than 200 kilograms. It's a giraffe of course! Did you guess correctly?", "ipa": "/ðɪs ˈfaɪnl kluː wɪl ɡɪv ɪt əˈweɪ. ɪt hæz ə lɔːŋ nɛk. ɪts nɛk weɪz mɔːr ðæn ˈtuː ˈhʌndrəd ˈkɪləˌɡræmz. ɪts ə dʒəˈrɑːf əv kɔːrs! dɪd juː ɡɛs kəˈrɛktli?/", vi: "Manh mối cuối cùng đây: Chúng sở hữu chiếc cổ siêu dài, riêng phần cổ đã nặng hơn 200 kg. Đương nhiên đó là hươu cao cổ rồi! Bạn đoán chuẩn không nào?" }
    ]
  },
  {
    "day": 29,
    "title": "Cooking Fish",
    "image": "08 August/images/day_29.webp",
    "audio": "08 August/audio/Track29.mp3",
    "sentences": [
      { "start": 4.8, "en": "Sarah is Joe's sister. When mom and dad are not home, Sarah is the chef of the house. 'Let's have fish for lunch,' Sarah says. 'It will be as easy as making cookies. I will just have to increase the oven temperature a little bit.'", "ipa": "/ˈsɛərə ɪz dʒoʊz ˈsɪstər. wɛn mɒm ænd dæd ɑːr nɒt hoʊm, ˈsɛərə ɪz ðə ʃɛf əv ðə haʊs. lɛts hæv fɪʃ fɔːr lʌntʃ, ˈsɛərə sɛz. ɪt wɪl biː æz ˈiːzi æz ˈmeɪkɪŋ ˈkʊkiz. aɪ wɪl dʒʌst hæv tuː ɪnˈkriːs ði ˈʌvn ˈtɛmprətʃər ə ˈlɪtl bɪt/", vi: "Sarah là chị của Joe. Những lúc bố mẹ vắng nhà, Sarah kiêm luôn đầu bếp chính. 'Hôm nay ăn cá cho bữa trưa nhé,' Sarah đề xuất. 'Dễ như làm bánh quy ấy mà, chị chỉ cần vặn lò nướng to lên một tí là xong.'" },
      { "start": 21.0, "en": "Sarah heats the oven to maximum power. She takes the fish out of the freezer. She puts it in the oven. Then, she sets the table with two plates, two forks and two knives.", "ipa": "/ˈsɛərə hiːts ði ˈʌvn tuː ˈmæksɪməm ˈpaʊər. ʃiː teɪks ðə fɪʃ aʊt əv ðə ˈfriːzər. ʃiː pʊts ɪt ɪn ði ˈʌvn. ðɛn, ʃiː sɛts ðə ˈteɪbl wɪð tuː pleɪts, tuː fɔːrks ænd tuː naɪvz/", vi: "Sarah vặn lò nướng hết cỡ, lấy con cá cứng ngắc từ ngăn đông ra rồi tống thẳng vào lò. Sau đó cô bé thong thả bày đĩa, nĩa và dao ra bàn." },
      { "start": 35.0, "en": "Joe is hungry. 'How much longer do we have to wait?' he asks. 'Not long,' answers Sarah. After ten minutes, Sarah takes the fish out of the oven. It's golden and crispy. 'It's better than mom's!' Sarah thinks.", "ipa": "/dʒoʊ ɪz ˈhʌŋɡri. haʊ mʌtʃ ˈlɔːŋɡər duː wiː hæv tuː weɪt?, hiː ɑːsks. nɒt lʌŋ, ˈɑːnsərd ˈsɛərə. ˈɑːftər tɛn ˈmɪnɪts, ˈsɛərə teɪks ðə fɪʃ aʊt əv ði ˈʌvn. ɪts ˈɡoʊldən ænd ˈkrɪspi. ɪts ˈbɛtər ðæn mɒmz!, ˈsɛərə θɪŋks/", vi: "Joe đói cồn cào: 'Phải chờ bao lâu nữa hả chị?' 'Sắp xong rồi,' Sarah đáp. Mới mười phút sau, Sarah hào hứng lôi cá ra. Miếng cá vàng ươm giòn rụm. 'Ngon hơn cả mẹ làm ấy chứ!' cô bé tự đắc." },
      { "start": 51.0, "en": "'Wow! You are a great chef!' says Joe. 'You are right. Now, let's eat.' But when they try to cut the fish, they realize something is wrong. The fish is still frozen inside!", "ipa": "/waʊ! juː ɑːr ə ɡreɪt ʃɛf!, sɛd dʒoʊ. juː ɑːr raɪt. naʊ, lɛts iːt. bʌt wɛn ðeɪ traɪ tuː kʌt ðə fɪʃ, ðeɪ ˈriːəlaɪz ˈsʌmθɪŋ ɪz rɒŋ. ðə fɪʃ ɪz stɪl ˈfroʊzn ɪnˈsaɪd!/", vi: "'Oà! Chị đúng là đầu bếp cự phách!' Joe trầm trồ. 'Chuẩn luôn, giờ thì chiến thôi.' Nhưng khi vừa cắt miếng cá, cả hai tá hỏa nhận ra có gì đó sai sai: Bên trong cá vẫn còn cứng đá nửa sống nửa chín!" },
      { "start": 64.0, "en": "'It needs a bit more time,' Sarah says as she puts the fish back in the oven. Fifteen minutes later, she smells something burning. When she takes the fish out, it looks like black coal. Sarah says, 'Sorry, Joe. It looks like we will have to eat instant noodles for lunch today.'", "ipa": "/ɪt niːdz ə bɪt mɔːr taɪm, ˈsɛərə sɛz æz ʃiː pʊts ðə fɪʃ bæk ɪn ði ˈʌvn. ˈfɪftiːn ˈmɪnɪts ˈleɪtər, ʃiː smɛlz ˈsʌmθɪŋ ˈbɜːrnɪŋ. wɛn ʃiː teɪks ðə fɪʃ aʊt, ɪt lʊks laɪk blæk koʊl. ˈsɛərə sɛz, ˈsɒri, dʒoʊ. ɪt lʊks laɪk wiː wɪl hæv tuː iːt ˈɪnstənt ˈnuːdlz fɔːr lʌntʃ təˈdeɪ/", vi: "'Chắc cần thêm chút thời gian thôi,' Sarah chữa cháy rồi tống cá vào lò lại. Mười lăm phút sau, mùi khét lẹt xộc lên. Khi lấy ra, con cá đã đen thui cháy thành than. Sarah ngượng ngùng: 'Xin lỗi Joe nhé. Xem ra trưa nay hai chị em mình phải ăn mì gói tẩm cứu đó thôi.'" }
    ]
  },
  {
    "day": 30,
    "title": "Using Your Words",
    "image": "08 August/images/day_30.webp",
    "audio": "08 August/audio/Track30.mp3",
    "sentences": [
      { "start": 4.8, "en": "Leo loved playing with his toy blocks. One afternoon, he was building a tall castle in the living room. His little sister, Mia, walked by and accidentally bumped into it. Crash! The castle fell apart.", "ipa": "/ˈliːoʊ lʌvd ˈpleɪɪŋ wɪð hɪz tɔɪ blɒks. wʌn ˌɑːftərˈnuːn, hiː wɒz ˈbɪldɪŋ ə tɔːl ˈkæsl ɪn ðə ˈlɪvɪŋ ruːm. hɪz ˈlɪtl ˈsɪstər, ˈmiːə, wɔːkt baɪ ænd ˌæksɪˈdɛntli bʌmpt ˈɪntuː ɪt. kræʃ! ðə ˈkæsl fɛl əˈpɑːrt/", vi: "Leo rất thích chơi xếp hình khối. Một buổi chiều nọ, cậu đang say sưa xây một tòa lâu đài cao ở phòng khách thì cô em gái Mia đi qua vô tình va phải. Rầm! Tòa lâu đài đổ sập hoàn toàn." },
      { "start": 18.0, "en": "Leo was furious. He clenched his fists and opened his mouth to yell at Mia. But before he could shout, their mother gently touched his shoulder.", "ipa": "/ˈliːoʊ wɒz ˈfjʊəriəs. hiː klɛntʃt hɪz fɪsts ænd ˈoʊpənd hɪz maʊθ tuː jɛl æt ˈmiːə. bʌt bɪˈfɔːr hiː kʊd ʃaʊt, ðɛər ˈmʌðər ˈdʒɛntli tʌtʃt hɪz ˈʃoʊldər/", vi: "Leo nổi giận lôi đình. Cậu siết chặt nắm đấm và há miệng định quát mắng em. Nhưng chưa kịp thét lên, mẹ đã dịu dàng đặt tay lên vai cậu." },
      { "start": 29.0, "en": "'Remember, Leo, use your words instead of getting mad,' Mom said softly. Leo took a deep breath. He unclenched his fists and looked at his sister.", "ipa": "/rɪˈmɛmbər, ˈliːoʊ, juːz jɔːr wɜːrdz ɪnˈstɛd əv ˈɡɛtɪŋ mæd, mɒm sɛd ˈsɒftli. ˈliːoʊ tʊk ə diːp brɛθ. hiː ʌnˈklɛntʃt hɪz fɪsts ænd lʊkt æt hɪz ˈsɪstər/", vi: "'Con nhớ nhé Leo, hãy dùng lời nói thay vì nổi giận,' mẹ nhẹ nhàng nhắc nhở. Leo hít một hơi thật sâu, buông lỏng hai tay và nhìn sang em gái." },
      { "start": 41.0, "en": "'Mia, you knocked down my castle. It took me a long time to build. Please be careful next time,' Leo said calmly. Mia looked sorry and said, 'Sorry, brother. I'll help you rebuild it.'", "ipa": "/ˈmiːə, juː nɒkt daʊn maɪ ˈkæsl. ɪt tʊk miː ə lɒŋ taɪm tuː bɪld. pliːz biː ˈkɛrfʊl nɛkst taɪm, sɛd ˈliːoʊ ˈkɑːmli. ˈmiːə lʊkt ˈsɒri ænd sɛd, ˈsɒri, ˈbrʌðər. aɪl hɛlp juː ˌriːˈbɪld ɪt/", vi: "'Mia này, em làm đổ lâu đài của anh rồi. Anh mất rất nhiều thời gian mới xếp xong đấy. Lần sau em chú ý hơn nhé,' Leo bình tĩnh nói. Mia hối lỗi đáp: 'Em xin lỗi anh trai. Em sẽ phụ anh xếp lại từ đầu.'" },
      { "start": 56.0, "en": "Mom smiled proudly at Leo. Expressing feelings calmly solved the problem much better than shouting.", "ipa": "/mɒm smaɪld ˈpraʊdli æt ˈliːoʊ. ɪkˈsprɛsɪŋ ˈfiːlɪŋz ˈkɑːmli sɒlvd ðə ˈprɒbləm mʌtʃ ˈbɛtər ðæn ˈʃaʊtɪŋ/", vi: "Mẹ mỉm cười tự hào nhìn Leo. Việc bày tỏ cảm xúc một cách bình tĩnh đã giải quyết vấn đề tốt hơn rất nhiều so với việc la hét giận hờn." }
    ]
  },
  {
    "day": 31,
    "title": "City of Lights",
    "image": "08 August/images/day_31.webp",
    "audio": "08 August/audio/Track31.mp3",
    "sentences": [
      { "start": 4.8, "en": "About 4,000 years ago there was a tribe. The tribe lived in a valley by a wide river. The river was surrounded by beautiful trees and flowers. It was warm in the summer and not too cold in the winter.", "ipa": "/əˈbaʊt ˈfɔːr ˈθaʊznd jɪərz əˈɡoʊ ðɛər wɒz ə traɪb. ðə traɪb lɪvd ɪn ə ˈvæli baɪ ə waɪd ˈrɪvər. ðə ˈrɪvər wɒz səˈraʊndɪd baɪ ˈbjuːtɪfl triːz ænd ˈflaʊərz. ɪt wɒz wɔːrm ɪn ðə ˈsʌmər ænd nɒt tuː koʊld ɪn ðə ˈwɪntər/", vi: "Khoảng 4.000 năm trước, có một bộ lạc sinh sống tại thung lũng bên bờ một con sông rộng lớn. Nơi đây bao quanh bởi cây cối hoa cỏ tươi tốt, mùa hè ấm áp và mùa đông không quá lạnh lẽo." },
      { "start": 20.0, "en": "For thousands of years, people have lived in this place. Now, there is a big city on that spot. It's famous for a tower called the Eiffel Tower. People who live there speak French.", "ipa": "/fɔːr ˈθaʊzndz əv jɪərz, ˈpiːpl hæv lɪvd ɪn ðɪs pleɪs. naʊ, ðɛər ɪz ə bɪɡ ˈsɪti ɒn ðæt spɒt. ɪts ˈfeɪməs fɔːr ə ˈtaʊər kɔːld ði ˈaɪfəl ˈtaʊər. ˈpiːpl huː lɪv ðɛər spiːk frɛntʃ/", vi: "Trải qua hàng ngàn năm, con người vẫn quần tụ sinh sống tại chốn này. Giờ đây, một đô thị sầm uất đã mọc lên, nổi tiếng toàn cầu với Tháp Eiffel kỳ vĩ và ngôn ngữ chính là tiếng Pháp." },
      { "start": 36.0, "en": "From all over the world, people come to see the beautiful Seine River, the wonderful buildings and the art. The name of the tribe was the Parisii. Today we call it Paris, 'The City of Lights'.", "ipa": "/frɒm ɔːl ˈoʊvər ðə wɜːrld, ˈpiːpl kʌm tuː siː ðə ˈbjuːtɪfl sɛn ˈrɪvər, ðə ˈwʌndərfʊl ˈbɪldɪŋz ænd ði ɑːrt. ðə neɪm əv ðə traɪb wɒz ðə pəˈrɪzi. təˈdeɪ wiː kɔːl ɪt ˈpærɪs, ðə ˈsɪti əv laɪts/", vi: "Khách thập phương từ khắp nơi trên thế giới đổ về đây để chiêm ngưỡng dòng sông Seine thơ mộng, những công trình kiến trúc tuyệt mỹ và nền nghệ thuật đỉnh cao. Thuở xưa bộ lạc ấy mang tên Parisii, và ngày nay ta gọi thành phố ấy là Paris — 'Kinh đô Ánh sáng'." }
    ]
  }
];