if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["03 March"] = [
  {
    "day": 1,
    "title": "First Flower in Spring",
    "image": "03 March/images/day_01.webp",
    "audio": "03 March/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "Outside our kitchen window, there is a tree. No one in our family knew what kind of tree it was when we first moved in.", "ipa": "/ˈaʊtˌsaɪd ˈaʊər ˈkɪtʃɪn ˈwɪndoʊ, ðɛr ɪz a triː. noʊ wʌn ɪn ˈaʊər ˈfæməli nuː wɒt kaɪnd əv triː ɪt wɒz wɛn wiː fɜːrst muːvd ɪn/", "vi": "Ngay bên ngoài cửa sổ phòng bếp nhà tôi có một cái cây. Lúc mới dọn về đây, không ai trong gia đình biết đó là loại cây gì." },
      { "start": 14.0, "en": "Early that spring, the tree started to grow little buds and yellow petals. But there was still snow on the ground!", "ipa": "/ˈɜːrli ðæt sprɪŋ, ðə triː ˈstɑːrtɪd tuː ɡroʊ ˈlɪtl bʌdz ænd ˈjɛloʊ ˈpɛtəlz. bʌt ðɛr wɒz stɪl snoʊ ɒn ðə ɡraʊnd/", vi: "Đầu mùa xuân năm đó, cái cây bắt đầu đâm những nụ hoa nhỏ xíu cùng các cánh vàng rực. Thế nhưng mặt đất vẫn còn phủ đầy tuyết trắng!" },
      { "start": 23.0, "en": "At first, I thought the yellow buds were the leaves of the tree. My sister agreed and guessed, 'It must be the cold weather that made the tree leaves yellow, instead of green.'", "ipa": "/æt fɜːrst, aɪ θɔːt ðə ˈjɛloʊ bʌdz wɜːr ðə liːvz əv ðə triː. maɪ ˈsɪstər əˈɡriːd ænd ɡɛst, ɪt mʌst biː ðə koʊld ˈwɛðər ðæt meɪd ðə triː liːvz ˈjɛloʊ, ɪnˈstɛd əv ɡriːn/", vi: "Ban đầu, tôi cứ ngỡ những búp vàng ấy chính là lá cây. Chị tôi cũng đồng tình và đoán: 'Chắc do thời tiết lạnh giá làm lá cây ngả sang màu vàng thay vì màu xanh ấy mà.'" },
      { "start": 37.0, "en": "But a few weeks later, green leaves began to appear on the tree branches along with the yellow petals! We then realized that the yellow 'leaves' that appeared first were actually flowers!", "ipa": "/bʌt a fjuː wiːks ˈleɪtər, ɡriːn liːvz bɪˈɡæn tuː əˈpɪər ɒn ðə triː ˈbræntʃɪz əˈlɒŋ wɪð ðə ˈjɛloʊ ˈpɛtəlz! wiː ðɛn ˈriːəlaɪzd ðæt ðə ˈjɛloʊ liːvz ðæt əˈpɪərd fɜːrst wɜːr ˈæktʃuəli ˈflaʊərz/", vi: "Nhưng chỉ vài tuần sau, những chiếc lá xanh non bắt đầu đâm chồi trên cành xen lẫn với các cánh hoa vàng! Lúc đó chúng tôi mới vỡ lẽ rằng hóa ra những chiếc 'lá vàng' mọc ra trước tiên thực chất lại chính là những bông hoa!" },
      { "start": 53.0, "en": "This was the first time we saw a tree bear flowers before leaves. The discovery made us all very excited!", "ipa": "/ðɪs wɒz ðə fɜːrst taɪm wiː sɔː a triː bɛr ˈflaʊərz bɪˈfɔːr liːvz. ðə dɪsˈkʌvəri meɪd ʌs ɔːl ˈvɛri ɪkˈsaɪtɪd/", vi: "Đây là lần đầu tiên chúng tôi tận mắt thấy một loài cây trổ hoa trước rồi mới ra lá sau. Phát hiện thú vị này khiến tất cả chúng tôi vô cùng phấn khích." },
      { "start": 63.0, "en": "Mom and Dad borrowed a book from the library. Together, we learned about this flowering plant. It is called forsythia. To us, it's the first sign of spring.", "ipa": "/mɒm ænd dæd ˈbɑːroʊd a bʊk frɒm ðə ˈlaɪbreri. təˈɡɛðər, wiː lɜːrnd əˈbaʊt ðɪs ˈflaʊərɪŋ plænt. ɪt ɪz kɔːld fɔːrˈsɪθiə. tuː ʌs, ɪts ðə fɜːrst saɪn əv sprɪŋ/", vi: "Bố mẹ liền mượn một cuốn sách từ thư viện, và cả nhà cùng nhau tìm hiểu về loài cây đặc biệt này. Nó có tên là hoa nghinh xuân (forsythia). Đối với chúng tôi, đó chính là dấu hiệu đầu tiên báo hiệu mùa xuân đã về." }
    ]
  },
  {
    "day": 2,
    "title": "A Day of Fishing",
    image: "03 March/images/day_02.webp",
    audio: "03 March/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "Little Henry really likes fishing. He and his dad spend a lot of time fishing on the river.", "ipa": "/ˈlɪtl ˈhɛnri ˈrɪəli laɪks ˈfɪʃɪŋ. hiː ænd hɪz dæd spɛnd a lɒt əv taɪm ˈfɪʃɪŋ ɒn ðə ˈrɪvər/", vi: "Cậu bé Henry rất có niềm đam mê với câu cá. Cậu và bố thường xuyên dành nhiều thời gian câu cá bên bờ sông." },
      { "start": 12.0, "en": "Most times, Henry catches fish and throws them back into the river. Sometimes, he has a competition with Dad to see who can catch the biggest fish.", "ipa": "/moʊst taɪmz, ˈhɛnri ˈkætʃɪz fɪʃ ænd θroʊz ðɛm bæk ˈɪntuː ðə ˈrɪvər. ˈsʌmˌtaɪmz, hiː hæz a ˌkɒmpəˈtɪʃn wɪð dæd tuː siː huː kæn kætʃ ðə ˈbɪɡɪst fɪʃ/", vi: "Hầu hết các lần câu được cá, Henry đều thả chúng quay trở lại dòng sông. Thỉnh thoảng, cậu còn hào hứng thi đấu với bố xem ai câu được con cá to hơn." },
      { "start": 23.0, "en": "It is Saturday again. Henry sits on the riverbank for almost an hour. Still, no fish bite. His dad smiles and says, 'Fishing is a sport. It exercises your patience.'", "ipa": "/ɪt ɪz ˈsætərdeɪ əˈɡɛn. ˈhɛnri sɪts ɒn ðə ˈrɪvərˌbæŋk fɔːr ˈɔːlmoʊst ən ˈaʊər. stɪl, noʊ fɪʃ baɪt. hɪz dæd smaɪlz ænd sɛd, ˈfɪʃɪŋ ɪz a spɔːrt. ɪt ˈɛksərˌsaɪzɪz jɔːr ˈpeɪʃns/", vi: "Lại một ngày thứ Bảy nữa đến. Henry ngồi kiên nhẫn bên bờ sông ngót nghét gần một tiếng đồng hồ mà chẳng thấy con cá nào cắn câu. Bố mỉm cười hiền hậu bảo: 'Câu cá là một môn thể thao giúp rèn luyện sự kiên nhẫn của con đấy.'" },
      { "start": 38.0, "en": "No problem. Henry loves fishing, even when he is not catching fish. He enjoys the river. He loves watching the birds on the water.", "ipa": "/noʊ ˈprɒbləm. ˈhɛnri lʌvz ˈfɪʃɪŋ, ˈiːvn wɛn hiː ɪz nɒt ˈkætʃɪŋ fɪʃ. hiː ɪnˈdʒɔɪz ðə ˈrɪvər. hiː lʌvz ˈwɒtʃɪŋ ðə bɜːrdz ɒn ðə ˈwɔːtər/", vi: "Chẳng hề gì cả. Henry vẫn rất yêu câu cá ngay cả khi chẳng câu được con nào. Cậu tận hưởng không gian bên dòng sông và thích thú ngắm nhìn những cánh chim chao lượn trên mặt nước." },
      { "start": 50.0, "en": "Suddenly, Henry feels something. He feels a tug at the end of the fishing rod. 'Dad, it's a big one!' Henry cries. His dad comes to help. Henry pulls and pulls. In his mind, he imagines a HUGE fish.", "ipa": "/ˈsʌdənli, hiːlz ˈhɛnri fiːlz ˈsʌmθɪŋ. hiː fiːlz a tʌɡ ænd ðə ɛnd əv ðə ˈfɪʃɪŋ rɒd. dæd, ɪts a bɪɡ wʌn!, ˈhɛnri kraɪz. hɪz dæd kʌmz tuː hɛlp. ˈhɛnri pʊlz ænd pʊlz. ɪn hɪz maɪnd, hiː ɪˈmædʒɪnz a hyudʒ fɪʃ/", vi: "Bỗng nhiên, Henry cảm thấy có gì đó khác lạ. Cần câu bị giật mạnh ở đầu mút. 'Bố ơi, con cá khủng lắm bố ạ!' Henry hét lên. Bố vội chạy lại hỗ trợ. Henry gồng mình kéo giật lên, trong đầu vẽ ra viễn cảnh một con cá KHỔNG LỒ đang mắc câu." },
      { "start": 69.0, "en": "Finally, he brings it out of the water. But, it is not a fish. It's a turtle!", "ipa": "/ˈfaɪnəli, hiː brɪŋz ɪt aʊt əv ðə ˈwɔːtər. bʌt, ɪt ɪz nɒt a fɪʃ. ɪts a ˈtɜːrtl!/", vi: "Cuối cùng, cậu cũng kéo được vật nặng lên khỏi mặt nước. Ôi chao, hóa ra đó chẳng phải là cá mà lại là một chú rùa!" }
    ]
  },
  {
    "day": 3,
    "title": "Danger: Thin Ice",
    image: "03 March/images/day_03.webp",
    audio: "03 March/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Alice and her dad walk beside the river. They are taking their dog Snoopy for a walk. It is a beautiful day in early March. The sun is high and warm. There are no clouds in the sky.", "ipa": "/ˈælɪs ænd hɜːr dæd wɔːk bɪˈsaɪd ðə ˈrɪvər. ðeɪ ɑːr ˈteɪkɪŋ ðɛr dɔːɡ ˈsnuːpi fɔːr a wɔːk. ɪt ɪz a ˈbjuːtɪfl deɪ ɪn ˈɜːrli mɑːrtʃ. ðə sʌn ɪz haɪ ænd wɔːrm. ðɛr ɑːr noʊ klaʊdz ɪn ðə skaɪ/", vi: "Alice cùng bố dắt chú chó cưng Snoopy đi dạo dọc theo bờ sông. Hôm nay là một ngày đầu tháng Ba tuyệt đẹp, ánh nắng vàng rực rỡ và ấm áp vắt ngang qua bầu trời không một bóng mây." },
      { "start": 17.0, "en": "All of a sudden, Snoopy sees something on the ice. He runs to catch it. Alice shouts, 'NO! Stop, Snoopy!' But it is too late.", "ipa": "/ɔːl əv a ˈsʌdn, ˈsnuːpi siːz ˈsʌmθɪŋ ɒn ði aɪs. hiː rʌnz tuː kætʃ ɪt. ˈælɪs ʃaʊts, noʊ! stɒp, ˈsnuːpi! bʌt ɪt ɪz tuː leɪt/", vi: "Đột nhiên, chú chó Snoopy nhìn thấy thứ gì đó thú vị nằm trên lớp băng mỏng ngoài sông và lao vút ra để bắt. Alice hoảng hốt thét lên: 'KHÔNG! Dừng lại đi Snoopy!' nhưng đã quá muộn." },
      { "start": 27.0, "en": "The ice breaks and Snoopy falls into the cold water. Alice runs to help her dog. But Dad stops her. 'Do not go on the ice,' he says. Then, he calls 911. Soon, the firefighters arrive. They crawl on a ladder over the ice to save the little dog.", "ipa": "/ði aɪs breɪks ænd ˈsnuːpi fɔːlz ˈɪntuː ðə koʊld ˈwɔːtər. ˈælɪs rʌnz tuː hɛlp hɜːr dɔːɡ. bʌt dæd stɒps hɜːr. duː nɒt ɡoʊ ɒn ði aɪs, hiː sɛz. ðɛn, hiː kɔːlz naɪn-wʌn-naɪn. suːn, ðə ˈfaɪərˌfaɪərz əˈraɪv. ðeɪ krɔːl ɒn a ˈlædər ˈoʊvər ði aɪs tuː seɪv ðə ˈlɪtl dɔːɡ/", vi: "Lớp băng nứt toác và Snoopy lọtỏm xuống dòng nước lạnh ngắt. Alice toan chạy ra cứu chó cưng nhưng bố đã kịp giữ lại: 'Con tuyệt đối không được bước ra mặt băng,' bố kiên quyết nói rồi nhanh chóng gọi đường dây khẩn cấp 911. Chẳng mấy chốc, các chú lính cứu hỏa đã có mặt. Họ khéo léo bò trên chiếc thang bắc ngang qua lớp băng mỏng để giải cứu chú chó nhỏ." },
      { "start": 50.0, "en": "When they bring it back to shore, Alice cries. She is so happy! The fireman says, 'You were smart. Never go on the ice to save your dog. It is too dangerous. Do not trust the ice in late winter. Always call for help.'", "ipa": "/wɛn ðeɪ brɪŋ ɪt bæk tuː ʃɔːr, ˈælɪs kraɪz. ʃiː ɪz soʊ ˈhæpi! ðə ˈfaɪərmən sɛz, juː wɜːr smɑːrt. ˈnɛvər ɡoʊ ɒn ði aɪs tuː seɪv jɔːr dɔːɡ. ɪt ɪz tuː ˈdeɪndʒərəs. duː nɒt trʌst ði aɪs ɪn leɪt ˈwɪntər. ˈɔːlweɪz kɔːl fɔːr hɛlp/", vi: "Khi đưa được Snoopy an toàn vào bờ, Alice òa khóc vì quá đỗi hạnh phúc. Chú lính cứu hỏa ân cần dặn dò: 'Cháu rất khôn ngoan khi đứng bờ. Tuyệt đối không được mạo hiểm ra mặt băng để cứu thú cưng nhé, vô cùng nguy hiểm đấy. Đừng bao giờ chủ quan tin tưởng vào lớp băng vào thời điểm cuối đông, hãy luôn gọi người lớn trợ giúp ngay lập tức.'" }
    ]
  },
  {
    "day": 4,
    "title": "Afraid of Wind",
    image: "03 March/images/day_04.webp",
    audio: "03 March/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "When I was a little girl, I was afraid of the wind. It made lots of noises and made everyone feel cold. 'I don't like wind,' I told my father. Father smiled.", "ipa": "/wɛn aɪ wɒz a ˈlɪtl ɡɜːrl, aɪ wɒz əˈfreɪd əv ðə wɪnd. ɪt meɪd lɒts əv ˈnɔɪzɪz ænd meɪd ˈɛvriˌwʌn fiːl koʊld. aɪ doʊnt laɪk wɪnd, aɪ toʊld maɪ ˈfɑːðər. ˈfɑːðər smaɪld/", vi: "Hồi còn là một cô bé nhỏ xíu, tôi rất sợ những cơn gió thổi. Gió gầm rít tạo ra đủ thứ âm thanh đáng sợ và làm ai nấy đều thấy lạnh lẽo. 'Con ghét gió lắm,' tôi bĩu môi mách bố. Bố chỉ mỉm cười dịu dàng." },
      { "start": 17.0, "en": "One day, as the wind was blowing strongly, I cried, 'Look at the trees. They are all bent. I think it's trees that cause wind. Let's cut down all the trees. Then there will be no more wind!'", "ipa": "/wʌn deɪ, æz ðə wɪnd wɒz ˈbloʊɪŋ ˈstrɒŋli, aɪ kraɪd, lʊk æt ðə triːz. ðeɪ ɑːr ɔːl bɛnt. aɪ θɪŋk ɪts triːz ðæt kɔːz wɪnd. lɛts kʌt daʊn ɔːl ðə triːz. ðɛn ðɛr wɪl biː noʊ mɔːr wɪnd!/", vi: "Có một hôm gió thổi lồng lộng dữ dội, tôi hớt hải mách bố: 'Bố nhìn những cái cây kìa, chúng bị uốn cong cả lại rồi. Con đoán chính mấy cái cây đã sinh ra gió đấy. Hay là chúng ta chặt hết cây đi để từ nay không còn gió nữa nhé!'" },
      { "start": 33.0, "en": "Father laughed. He told me that trees don't create wind. Instead, trees slow down the wind. 'But where does the wind come from?' I asked.", "ipa": "/ˈfɑːðər lɑːft. hiː toʊld miː ðæt triːz doʊnt kriːˈeɪt wɪnd. ɪnˈstɛd, triːz sloʊ daʊn ðə wɪnd. bʌt wɛr dʌz ðə wɪnd kʌm frɒm?, aɪ ɑːskt/", vi: "Bố phì cười ôm lấy tôi giải thích rằng cây cối không hề tạo ra gió, mà trái lại, chúng còn giúp cản bớt và làm giảm tốc độ gió đi. 'Thế gió từ đâu ra hả bố?' tôi tò mò gặng hỏi." },
      { "start": 44.0, "en": "'It comes from the air—moving air is wind. Air and wind are part of the natural world,' explained my father. 'Without wind, the hot areas would be too hot, and the cold areas would be too cold. It would be a big problem for our world.'", "ipa": "/ɪt kʌmz frɒm ði ɛər—ˈmuːvɪŋ ɛər ɪz wɪnd. ɛər ænd wɪnd ɑːr pɑːrt əv ðə ˈnætʃrəl wɜːrld, ɪkˈspleɪnd maɪ ˈfɑːðər. wɪˈðaʊt wɪnd, ðə hɒt ˈɛriəz wʊd biː tuː hɒt, ænd ðə koʊld ˈɛriəz wʊd biː tuː koʊld. ɪt wʊd biː a bɪɡ ˈprɒbləm fɔːr ˈaʊər wɜːrld/", vi: "'Gió vốn sinh ra từ không khí — không khí chuyển động chính là gió. Không khí và gió là một phần không thể thiếu của tự nhiên,' bố ân cần giảng giải. 'Nếu thiếu gió, những vùng nóng sẽ càng oi bức tột độ, còn vùng lạnh sẽ băng giá khôn cùng. Điều đó sẽ gây ra thảm họa lớn cho hành tinh của chúng ta đấy.'" },
      { "start": 62.0, "en": "I still get nervous when a strong wind blows. But I always remember the way my father took the time to explain it to me.", "ipa": "/aɪ stɪl ɡɛt ˈnɜːrvəs wɛn a strɒŋ wɪnd bloʊz. bʌt aɪ ˈɔːlweɪz rɪˈmɛmbər ðə weɪ maɪ ˈfɑːðər tʊk ðə taɪm tuː ɪkˈspleɪn ɪt tuː miː/", vi: "Đến tận bây giờ, tôi thỉnh thoảng vẫn thấy hơi lo lắng mỗi khi có cơn giông gió lớn thổi qua, nhưng trong lòng luôn khắc ghi bài học sinh động và sự kiên nhẫn giảng giải của bố ngày nào." }
    ]
  },
  {
    "day": 5,
    "title": "Our Amazing Eyes",
    image: "03 March/images/day_05.webp",
    audio: "03 March/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Today in school, we learned something amazing. Nearly 2,500 people in Canada go blind each year because they injure their eyes.", "ipa": "/təˈdeɪ ɪn skuːl, wiː lɜːrnd ˈsʌmθɪŋ əˈmeɪzɪŋ. ˈnɪərli ˈtuː ˈθaʊznd fʌɪv ˈhʌndrəd ˈpiːpl ɪn ˈkænədə ɡoʊ blaɪnd iːtʃ jɪər bɪˈkəz ðeɪ ˈɪndʒər ðɛr aɪz/", vi: "Hôm nay ở trường, chúng tôi được học một sự thật vô cùng bất ngờ: Gần 2.500 người ở Canada bị mất thị lực (mù) mỗi năm do những chấn thương ở mắt." },
      { "start": 16.0, "en": "Our eyes weigh only 28 grams. But they are really important. Imagine what it would be like if you could not see.", "ipa": "/ˈaʊər aɪz weɪ ˈoʊnli ˈtwɛnti-eɪt ɡræmz. bʌt ðeɪ ɑːr ˈrɪəli ɪmˈpɔːrtənt. ɪˈmædʒɪn wɒt ɪt wʊd biː laɪk ɪf juː kʊd nɒt siː/", vi: "Đôi mắt của chúng ta chỉ nặng vỏn vẹn 28 gram nhưng lại đóng vai trò tối quan trọng. Hãy thử hình dung xem cuộc sống sẽ ra sao nếu bạn không thể nhìn thấy mọi vật." },
      { "start": 25.0, "en": "Luckily, our bodies are designed to protect our eyes. Our eyebrows keep salty sweat from running into our eyes. Our eyelashes keep dirt from getting into our eyes. And tears wash away any dirt that gets past our eyelashes.", "ipa": "/ˈlʌkɪli, ˈaʊər ˈbɒdiz ɑːr dɪˈzaɪnd tuː prəˈtɛkt ˈaʊər aɪz. ˈaʊər ˈaɪˌbraʊz kiːp ˈsɔːlti swɛt frɒm ˈrʌnɪŋ ˈɪntuː ˈaʊər aɪz. ˈaʊər ˈaɪˌlæʃɪz kiːp dɜːrt frɒm ˈɡɛtɪŋ ˈɪntuː ˈaʊər aɪz. ænd tɪərz wɒʃ əˈweɪ ˈɛni dɜːrt ðæt ɡɛts pɑːst ˈaʊər ˈaɪˌlæʃɪz/", vi: "May mắn thay, cơ thể chúng ta được cấu tạo tuyệt hảo để bảo vệ đôi mắt. Lông mày ngăn không cho mồ hôi mặn chảy vào mắt; lông mi chặn bụi bẩn; và nước mắt liên tục rửa trôi mọi hạt bụi lọt qua được lớp lông mi." },
      { "start": 44.0, "en": "Want to hear something amazing? We blink our eyes 10 million times a year! Each time we blink, a little water enters our eyes and washes dust and dirt away.", "ipa": "/wɒnt tuː hɪər ˈsʌmθɪŋ əˈmeɪzɪŋ? wiː blɪŋk ˈaʊər aɪz tɛn ˈmɪljən taɪmz a jɪər! iːtʃ taɪm wiː blɪŋk, a ˈlɪtl ˈwɔːtər ˈɛntərz ˈaʊər aɪz ænd ˈwɒʃɪz dʌst ænd dɜːrt əˈweɪ/", vi: "Bạn có muốn nghe một điều kỳ diệu nữa không? Chúng ta chớp mắt tới 10 triệu lần mỗi năm! Mỗi cú chớp mắt là một lần tiết ra chút nước mắt để bôi trơn, cuốn trôi mọi bụi bẩn bám trên bề mặt mắt." },
      { "start": 59.0, "en": "Did you know that you cannot sneeze with your eyes open? It's true. Next time you feel a sneeze coming, see if you can keep your eyes open while you sneeze. You won't be able to!", "ipa": "/dɪd juː noʊ ðæt juː ˈkænɒt sniːz wɪð jɔːr aɪz ˈoʊpən? ɪts truː. nɛkst taɪm juː fiːl a sniːz ˈkʌmɪŋ, siː ɪf juː kæn kiːp jɔːr aɪz ˈoʊpən waɪl juː sniːz. juː woʊnt biː ˈeɪbl tuː!/", vi: "Đố bạn biết vì sao chúng ta không bao giờ hắt hơi mà mở được mắt? Đó là sự thật đấy. Lần tới nếu thấy buồn hắt hơi, bạn cứ thử cố mở trân trân mắt xem, chắc chắn bạn không tài nào làm nổi đâu!" }
    ]
  },
  {
    "day": 6,
    "title": "Where Is the Money From?",
    image: "03 March/images/day_06.webp",
    audio: "03 March/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "Irene doesn't like it when her mother goes to work. Every day, she begs her mom to stay home. 'Can you please stay home? Can you pick me up from school? Pleeease, Mom!'", "ipa": "/aɪˈriːn ˈdʌznt laɪk ɪt wɛn hɜːr ˈmʌðər ɡoʊz tuː wɜːrk. ˈɛvri deɪ, ʃiː bɛɡz hɜːr mɒm tuː steɪ hoʊm. kæn juː pliːz steɪ hoʊm? kæn juː pɪk miː ʌp frɒm skuːl? pliːz, mɒm!/", vi: "Irene rất ghét mỗi khi mẹ phải đi làm. Ngày nào con bé cũng nài nỉ mẹ ở nhà: 'Mẹ ở nhà với con đi ạ? Mẹ qua trường đón con nhé? Đi mà mẹ!' " },
      { "start": 16.0, "en": "But, her mother always says, 'No, honey! I need to work.' Irene doesn't understand. 'Why?' she asks.", "ipa": "/bʌt, hɜːr ˈmʌðər ˈɔːlweɪz sɛz, noʊ, ˈhʌni! aɪ niːd tuː wɜːrk. aɪˈriːn ˈdʌznt ˌʌndərˈstænd. waɪ?, ʃiː ɑːsks/", vi: "Nhưng mẹ lúc nào cũng từ chối: 'Không được đâu con yêu! Mẹ phải đi làm chứ.' Irene ngơ ngác không hiểu: 'Tại sao lại thế hả mẹ?'" },
      { "start": 23.0, "en": "Mom explains it to her, 'We need money to pay for our food, house, car, books and toys. I go to work to make money for us.'", "ipa": "/mɒm ɪkˈspleɪnz ɪt tuː hɜːr, wiː niːd ˈmʌni tuː peɪ fɔːr ˈaʊər fuːd, haʊs, kɑːr, bʊks ænd tɔɪz. aɪ ɡoʊ tuː wɜːrk tuː meɪk ˈmʌni fɔːr ʌs/", vi: "Mẹ ân cần giải thích: 'Chúng ta cần có tiền để chi trả tiền ăn uống, nhà cửa, xe cộ, sách vở và đồ chơi. Mẹ đi làm vất vả là để kiếm tiền lo cho cuộc sống gia đình.'" },
      { "start": 35.0, "en": "Irene quickly replies, 'No, Mom. When you need money, you just go to the bank to get it.' Then she adds, 'I saw that the other day.'", "ipa": "/aɪˈriːn ˈkwɪkli rɪˈplaɪz, noʊ, mɒm. wɛn juː niːd ˈmʌni, juː dʒʌst ɡoʊ tuː ðə bæŋk tuː ɡɛt ɪt. ðɛn ʃiː ædz, aɪ sɔː ðæt ði ˈʌðər deɪ/", vi: "Irene láu lỉnh cãi lại ngay: 'Không phải đâu mẹ. Khi nào mẹ cần tiền, mẹ chỉ việc ra ngân hàng lấy là được mà. Hôm nọ con thấy mẹ làm thế rồi cơ mà.'" },
      { "start": 47.0, "en": "Mom laughs and says, 'Yes, I can go to the bank to get money. But that's only possible once I have earned the money and put it in a bank account.'", "ipa": "/mɒm lɑːfs ænd sɛd, jɛs, aɪ kæn ɡoʊ tuː ðə bæŋk tuː ɡɛt ˈmʌni. bʌt ðæts ˈoʊnli ˈpɒsəbl wʌns aɪ hæv ɜːrnd ðə ˈmʌni ænd pʊt ɪt ɪn a bæŋk əˈkaʊnt/", vi: "Mẹ phì cười xoa đầu con gái: 'Đúng là mẹ ra ngân hàng rút tiền thật, nhưng việc đó chỉ thực hiện được khi mẹ đã phải lao động vất vả để kiếm ra tiền rồi gửi tích lũy vào tài khoản ngân hàng trước đó chứ con.'" }
    ]
  },
  {
    "day": 7,
    "title": "Our Friendly Sun",
    image: "03 March/images/day_07.webp",
    audio: "03 March/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "Look up. Look at the sky. But do not look at the sun. The sun is very strong. Its light is so powerful that it can hurt your eyes.", "ipa": "/lʊk ʌp. lʊk æt ðə skaɪ. bʌt doʊnt lʊk æt ðə sʌn. ðə sʌn ɪz ˈvɛri strɒŋ. ɪts laɪt ɪz soʊ ˈpaʊərfʊl ðæt ɪt kæn hɜːrt jɔːr aɪz/", vi: "Hãy ngước nhìn lên bầu trời kia. Nhưng nhớ tuyệt đối đừng nhìn thẳng vào mặt trời nhé. Ánh sáng mặt trời cực kỳ mạnh mẽ và có thể gây tổn thương nghiêm trọng cho đôi mắt của bạn." },
      { "start": 15.0, "en": "Do you know how far the sun is from the earth? It's about 150 million kilometres away! Wow! That's really far.", "ipa": "/duː juː noʊ haʊ fɑːr ðə sʌn ɪz frɒm ði ɜːrθ? ɪts əˈbaʊt wʌn ˈhʌndrəd fɪfti ˈmɪljən ˈkɪləˌmiːtərz əˈweɪ! waʊ! ðæts ˈrɪəli fɑːr/", vi: "Bạn có biết khoảng cách từ mặt trời đến Trái Đất là bao xa không? Xa tới tận 150 triệu kilômét lận đấy! Chà, một khoảng cách thực sự khổng lồ." },
      { "start": 26.0, "en": "Even though the sun is far away, the light is still very strong when it reaches us. So, the sun is one of the most powerful things in our world.", "ipa": "/ˈiːvn ðoʊ ðə sʌn ɪz fɑːr əˈweɪ, ðə laɪt ɪz stɪl ˈvɛri strɒŋ wɛn ɪt ˈriːtʃɪz ʌs. soʊ, ðə sʌn ɪz wʌn əv ðə moʊst ˈpaʊərfʊl θɪŋz ɪn ˈaʊər wɜːrld/", vi: "Dù ở vị trí xa xôi đến vậy, nhưng luồng ánh sáng mà nó phóng đến chúng ta vẫn cực kỳ mạnh mẽ. Do đó, mặt trời chính là một trong những thực thể tối thượng quyền năng nhất trong vũ trụ của chúng ta." },
      { "start": 40.0, "en": "Do not be afraid of the sun. It is an important friend. It keeps us warm. It gives us light so we can see. It makes flowers and trees grow. There can be no life on earth without the sun. That is why we call it our friendly sun. It is our friend because it gives us many things. But be careful. It is a very powerful friend.", "ipa": "/doʊnt biː əˈfreɪd əv ðə sʌn. ɪt ɪz ən ɪmˈpɔːrtənt frɛnd. ɪt kiːps ʌs wɔːrm. ɪt ɡɪvz ʌs laɪt soʊ wiː kæn siː. ɪt meɪks ˈflaʊərz ænd triːz ɡroʊ. ðɛr kæn biː noʊ laɪf ɒn ɜːrθ wɪˈðaʊt ðə sʌn. ðæt ɪz waɪ wiː kɔːl ɪt ˈaʊər ˈfrɛndli sʌn. ɪt ɪz ˈaʊər frɛnd bɪˈkəz ɪt ɡɪvz ʌs ˈmɛni θɪŋz. bʌt biː ˈkɛrfəl. ɪt ɪz a ˈvɛri ˈpaʊərfʊl frɛnd/", vi: "Đừng vì thế mà sợ hãi mặt trời nhé. Nó là một người bạn vô cùng quan trọng đối với sự sống. Mặt trời sưởi ấm cho ta, ban phát ánh sáng để ta nhìn vạn vật, và nuôi dưỡng cây cối hoa lá đơm bông. Sẽ chẳng thể tồn tại bất kỳ sự sống nào trên Trái Đất nếu vắng bóng mặt trời. Đó là lý do ta gọi nó là 'người bạn mặt trời thân thiết' — bởi nó ban cho ta vô vàn thứ quý giá. Tuy nhiên hãy luôn cẩn trọng, bởi đó là một người bạn có sức mạnh vô song." }
    ]
  },
  {
    "day": 8,
    "title": "Brush Twice a Day (I)",
    image: "03 March/images/day_08.webp",
    audio: "03 March/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "There is one thing that I really, really HATE doing. What is it? Brushing my teeth. I just don't see the reason for all this brushing.", "ipa": "/ðɛr ɪz wʌn θɪŋ ðæt aɪ ˈrɪəli, ˈrɪəli heɪt ˈduːɪŋ. wɒt ɪz ɪt? ˈbrʌʃɪŋ maɪ tiːθ. aɪ dʒʌst doʊnt siː ðə ˈriːzn fɔːr ɔːl ðɪs ˈbrʌʃɪŋ/", vi: "Có một việc duy nhất trên đời mà tôi cực kỳ, cực kỳ GHÉT phải làm. Đó là gì đố bạn biết? Chính là đánh răng. Tôi mãi chẳng hiểu tại sao cứ phải kè kè chải răng suốt ngày làm gì cho mệt." },
      { "start": 16.0, "en": "Mom is always making sure I brush in the morning, and I brush my teeth before bed too. WHY? That's what I want to know.", "ipa": "/mɒm ɪz ˈɔːlweɪz ˈmeɪkɪŋ ʃʊr aɪ brʌʃ ɪn ðə ˈmɔːrnɪŋ, ænd aɪ brʌʃ maɪ tiːθ bɪˈfɔːr bɛd tuː. waɪ? ðæts wɒt aɪ wɒnt tuː noʊ/", vi: "Mẹ lúc nào cũng kè kè giám sát bắt tôi đánh răng vào buổi sáng và trước khi đi ngủ. TẠI SAO chứ? Đó là điều mà tôi luôn thắc mắc." },
      { "start": 26.0, "en": "Mom is a science teacher. She likes experiments. She says, 'Showing is always better than telling.' So, we make a deal.", "ipa": "/mɒm ɪz a ˈsaɪəns ˈtiːtʃər. ʃiː laɪks ɪkˈspɛrɪmənts. ʃiː sɛz, ˈʃoʊɪŋ ɪz ˈɔːlweɪz ˈbɛtər ðæn ˈtɛlɪŋ. soʊ, wiː meɪk a diːl/", vi: "Mẹ tôi vốn là một giáo viên dạy khoa học và rất thích làm thí nghiệm. Mẹ luôn niệm chú: 'Trăm nghe không bằng một thấy.' Thế là hai mẹ con liền lập một giao kèo thú vị." },
      { "start": 37.0, "en": "First, Mom has to prove that it is really important to brush teeth at least twice a day. If she does, I will brush my teeth without any complaining.", "ipa": "/fɜːrst, mɒm hæz tuː pruːv ðæt ɪt ɪz ˈrɪəli ɪmˈpɔːrtənt tuː brʌʃ tiːθ æt liːst twaɪs a deɪ. ɪf ʃiː dʌz, aɪ wɪl brʌʃ maɪ tiːθ wɪˈðaʊt ˈɛni kəmˈpleɪnɪŋ/", vi: "Đầu tiên, mẹ phải chứng minh được việc chải răng ít nhất hai lần mỗi ngày quan trọng đến mức nào. Nếu mẹ chứng minh được, tôi sẽ tự giác ngoan ngoãn đánh răng mà không dám ca thán nửa lời." },
      { "start": 50.0, "en": "'Okay,' says Mom. 'Here is what we need for this experiment. We need a boiled egg. We need a small jar. We need some vinegar.'", "ipa": "/oʊˈkeɪ, sɛd mɒm. hɪər ɪz wɒt wiː niːd fɔːr ðɪs ɪkˈspɛrɪmənt. wiː niːd a bɔɪld ɛɡ. wiː niːd a smɔːl dʒɑːr. wiː niːd sʌm ˈvɪnɪɡər/", vi: "'Được thôi,' mẹ mỉm cười gật đầu. 'Nguyên liệu cho thí nghiệm này rất đơn giản: Một quả trứng gà luộc, một chiếc lọ thủy tinh nhỏ và một ít giấm ăn.'" },
      { "start": 62.0, "en": "Vinegar is sour and really strong. I think this will be interesting. I can hardly wait to see what Mom is going to do!", "ipa": "/ˈvɪnɪɡər ɪz saʊər ænd ˈrɪəli strɒŋ. aɪ θɪŋk ðɪs wɪl biː ˈɪntrəstɪŋ. aɪ kæn ˈhɑːrdli weɪt tuː siː wɒt mɒm ɪz ˈɡoʊɪŋ tuː duː!/", vi: "Giấm ăn có vị chua ngắt và nồng nặc mùi hắc. Tôi nghĩ thí nghiệm này bắt đầu hay ho rồi đây và nóng lòng muốn xem mẹ sắp giở chiêu trò gì!" }
    ]
  },
  {
    "day": 9,
    "title": "Brush Twice a Day (II)",
    image: "03 March/images/day_09.webp",
    audio: "03 March/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "We boil the egg. When it has cooled, Mom hits the shell with a spoon. The shell doesn't break. It protects the inside of the egg,", "ipa": "/wiː bɔɪl ði ɛɡ. wɛn ɪt hæz kuːld, mɒm hɪts ðə ʃɛl wɪð a spuːn. ðə ʃɛl ˈdʌznt breɪk. ɪt prəˈtɛkts ði ˈɪnˌsaɪd əv ði ɛɡ/", vi: "Hai mẹ con luộc chín quả trứng. Khi trứng nguội hẳn, mẹ dùng thìa gõ nhẹ vào vỏ. Vỏ trứng không hề nứt vỡ, nó đóng vai trò như một lớp áo giáp bảo vệ phần lòng bên trong." },
      { "start": 15.0, "en": "She says, 'Your teeth have a shell too. It is called enamel.' Now the fun part. We fill the jar with vinegar. Then we put the egg inside and close the jar with a lid. Now, we wait.", "ipa": "/ʃiː sɛz, jɔːr tiːθ hæv a ʃɛl tuː. ɪt ɪz kɔːld ɪˈnæml. naʊ ðə fʌn pɑːrt. wiː fɪl ðə dʒɑːr wɪð ˈvɪnɪɡər. ðɛn wiː pʊt ði ɛɡ ˈɪnˌsaɪd ænd kloʊz ðə dʒɑːr wɪð a lɪd. naʊ, wiː weɪt/", vi: "'Răng của chúng ta cũng có một lớp vỏ bảo vệ tương tự như vậy đấy con,' mẹ giảng giải. 'Nó được gọi là lớp men răng.' Giờ đến phần hấp dẫn nhất: Đổ đầy giấm vào lọ thủy tinh, thả quả trứng gà vào rồi đậy kín nắp lại và cùng chờ đợi điều kỳ diệu xảy ra." },
      { "start": 32.0, "en": "What will happen? It is exciting. Two days later, we open the jar. The egg shell has become really soft. It is breaking into small pieces. Wow! What is that about?", "ipa": "/wɒt wɪl ˈhæpən? ɪt ɪz ɪkˈsaɪtɪŋ. tuː deɪz ˈleɪtər, wiː ˈoʊpən ðə dʒɑːr. ði ɛɡ ʃɛl hæz bɪˈkʌm ˈrɪəli sɒft. ɪt ɪz ˈbreɪkɪŋ ˈɪntuː smɔːl ˈpiːsɪz. waʊ! wɒt ɪz ðæt əˈbaʊt?/", vi: "Chuyện gì sẽ xảy ra tiếp theo nhỉ? Thật hồi hộp làm sao. Hai ngày sau, mẹ mở nắp lọ ra. Vỏ quả trứng lúc này đã trở nên mềm oặt và mủn ra từng mảng vụn nhỏ. Chà, hiện tượng kỳ lạ gì thế này?" },
      { "start": 47.0, "en": "'The vinegar is a strong acid, just like many foods we eat,' Mom says. 'The vinegar softens the egg shell so it cannot protect what is inside anymore.'", "ipa": "/ðə ˈvɪnɪɡər ɪz a strɒŋ ˈæsɪd, dʒʌst laɪk ˈmɛni fuːdz wiː iːt, mɒm sɛd. ðə ˈvɪnɪɡər ˈsɒftənz ði ɛɡ ʃɛl soʊ ɪt ˈkænɒt prəˈtɛkt wɒt ɪz ˈɪnˌsaɪd ˈɛniˌmɔːr/", vi: "'Giấm thực chất là một loại axit mạnh, tương tự như các loại thực phẩm chua hay nước ngọt chúng ta dung nạp hằng ngày,' mẹ kết luận. 'Axit trong giấm đã ăn mòn và làm mềm vỏ trứng khiến nó mất đi khả năng bảo vệ lớp bên trong.'" },
      { "start": 61.0, "en": "Mom smiles at me and says, 'That is why you must brush your teeth. Brushing cleans the acid off from them. If you do not brush, the acid will break the enamel. You will have many cavities and toothaches after.'", "ipa": "/mɒm smaɪld æt miː ænd sɛd, ðæt ɪz waɪ juː mʌst brʌʃ jɔːr tiːθ. ˈbrʌʃɪŋ kliːnz ði ˈæsɪd ɔːf frɒm ðɛm. ɪf juː duː nɒt brʌʃ, ði ˈæsɪd wɪl breɪk ði ɪˈnæml. juː wɪl hæv ˈmɛni ˈkævətiz ænd ˈtuːθˌeɪks ˈɑːftər/", vi: "Mẹ nhìn tôi mỉm cười trìu mến: 'Đó chính là lý do tại sao con bắt buộc phải đánh răng mỗi ngày. Chải răng giúp làm sạch lớp axit bám trên bề mặt răng. Nếu con lười đánh răng, axit sẽ phá hủy lớp men răng kiên cố, khiến răng bị sâu thủng lỗ chỗ và gây những cơn đau nhức buốt hành hạ.'" },
      { "start": 78.0, "en": "'No, I don't want that!' I reply quickly. My mother is smart. Now I know why I should brush my teeth.", "ipa": "/noʊ, aɪ doʊnt wɒnt ðæt! aɪ rɪˈplaɪ ˈkwɪkli. maɪ ˈʌðər ɪz smɑːrt. naʊ aɪ noʊ waɪ aɪ ʃʊd brʌʃ maɪ tiːθ/", vi: "'Không, con không muốn bị sâu răng đau đớn đâu ạ!' tôi hoảng hốt đáp ngay lập tức. Mẹ tôi quả thật rất cao tay. Giờ thì tôi đã tâm phục khẩu phục lý do vì sao mình phải chăm chỉ chải răng rồi." }
    ]
  },
  {
    "day": 10,
    "title": "Butterflies and Bird Song",
    image: "03 March/images/day_10.webp",
    audio: "03 March/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day in late summer, a magic man was passing through a village. It was a wonderful, sunny day. 'Soon, it will be winter,' thought the man. 'It will be cold and grey. Everyone will be sad.' But, the man had a plan.", "ipa": "/wʌn deɪ ɪn leɪt ˈsʌmər, a ˈmædʒɪk mæn wɒz ˈpɑːsɪŋ θruː a ˈvɪlɪdʒ. ɪt wɒz a ˈwʌndərfʊl, ˈsʌni deɪ. suːn, ɪt wɪl biː ˈwɪntər, θɔːt ðə mæn. ɪt wɪl biː koʊld ænd ɡreɪ. ˈɛvriˌwʌn wɪl biː sæd. bʌt, ðə mæn hæd a plæn/", vi: "Vào một ngày cuối hạ nọ, có một vị pháp sư kỳ tài đi ngang qua một ngôi làng nhỏ ngập tràn ánh nắng ấm áp. 'Chẳng mấy chốc mùa đông lạnh lẽo sẽ kéo đến,' ông thầm nghĩ. 'Mọi thứ sẽ trở nên xám xịt, buốt giá và ai nấy đều buồn rầu.' Nhưng vị pháp sư đã chuẩn bị sẵn một kế hoạch tuyệt hay." },
      { "start": 25.0, "en": "He gathered all the beautiful things of the world and put them into a magic bag. He collected a golden ray of sunshine, the green from the leaves of trees, the rich blue of the summer sky, and the flowers of many colours.", "ipa": "/hiː ˈɡæðərd ɔːl ðə ˈbjuːtɪfl θɪŋz əv ðə wɜːrld ænd pʊt ðɛm ˈɪntuː a ˈmædʒɪk bæɡ. hiː kəˈlɛktɪd a ˈɡoʊldən reɪ əv ˈsʌnˌʃaɪn, ðə ɡriːn frɒm ðə liːvz əv triːz, ðə rɪtʃ bluː əv ðə ˈsʌmər skaɪ, ænd ðə ˈflaʊərz əv ˈmɛni ˈkʌlərz/", vi: "Ông gom góp tất cả những vẻ đẹp tinh túy nhất của đất trời cất vào trong chiếc túi phép thuật của mình: chắt chiu tia nắng vàng óng ả, sắc xanh mướt của lá cây, màu xanh thẳm của bầu trời mùa hè và vô vàn sắc hoa rực rỡ." },
      { "start": 41.0, "en": "He heard the birds singing, so he added all their wonderful songs to the bag too. Then, when he opened the bag, out flew the most beautiful creatures the world had ever seen—butterflies!", "ipa": "/hiː hɜːrd ðə bɜːrdz ˈsɪŋɪŋ, soʊ hiː ˈædɪd ɔːl ðɛr ˈwʌndərfʊl sɔːŋz tuː ðə bæɡ tuː. ðɛn, wɛn hiː ˈoʊpənd ðə bæɡ, aʊt fluː ðə moʊst ˈbjuːtɪfl ˈkriːtʃərz ðə wɜːrld hæd ˈɛvər siːn—ˈbʌtərˌflaɪz!/", vi: "Lại nghe thấy tiếng chim hót líu lo, ông liền thu nhặt luôn cả những khúc ca tuyệt vời ấy vào túi. Đến khi ông mở tung miệng túi ra, những sinh vật lộng lẫy nhất mà thế gian chưa từng thấy bay vút lên bầu trời — đó chính là những chú bướm xinh đẹp!" },
      { "start": 57.0, "en": "The birds agreed that the butterflies were beautiful. They would help the people remember the beauty of the world, even during the dark, cold winters. But the birds asked the man to give them back their songs. 'These belong to us,' they cried. 'Butterflies are still beautiful without our songs.' The man agreed. And so, from that time on, butterflies were silent and beautiful.", "ipa": "/ðə bɜːrdz əˈɡriːd ðæt ðə ˈbʌtərˌflaɪz wɜːr ˈbjuːtɪfl. ðeɪ wʊd hɛlp ðə ˈpiːpl rɪˈmɛmbər ðə ˈbjuːti əv ðə wɜːrld, ˈiːvn ˈdjʊərɪŋ ðə dɑːrk, koʊld ˈwɪntərz. bʌt ðə bɜːrdz ɑːskt ðə mæn tuː ɡɪv ðɛm bæk ðɛr sɔːŋz. ðiːz bɪˈlɔːŋ tuː ʌs, ðeɪ kraɪd. ˈbʌtərˌflaɪz ɑːr stɪl ˈbjuːtɪfl wɪˈðaʊt ˈaʊər sɔːŋz. ðə mæn əˈɡriːd. ænd soʊ, frɒm ðæt taɪm ɒn, ˈbʌtərˌflaɪz wɜːr ˈsaɪlənt ænd ˈbjuːtɪfl/", vi: "Bầy chim công nhận loài bướm quả thực vô cùng lộng lẫy và chúng sẽ thay loài chim nhắc nhở con người về vẻ đẹp của thiên nhiên trong những ngày đông giá rét. Tuy nhiên, bầy chim nài nỉ vị pháp sư trả lại âm thanh tiếng hót cho chúng: 'Đó là báu vật của chúng tôi mà,' chúng kêu lên. 'Loài bướm dù không cất tiếng hót thì vẫn cứ kiều diễm cơ mà.' Vị pháp sư gật đầu đồng ý. Kể từ dạo đó, loài bướm lặng lẽ câm nặng nhưng mang trên mình vẻ đẹp rực rỡ làm say đắm lòng người." }
    ]
  },
  {
    "day": 11,
    "title": "The Judge",
    image: "03 March/images/day_11.webp",
    audio: "03 March/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. Judge is a really nice man. Everyone likes him and respects his honesty. But he is not really a 'judge'. You know, the person who makes decisions in a court of law. That's a judge.", "ipa": "/ˈmɪstər dʒʌdʒ ɪz a ˈrɪəli naɪs mæn. ˈɛvriˌwʌn laɪks hɪm ænd rɪˈspɛkts hɪz ˈɒnɪsti. bʌt hiː ɪz nɒt ˈrɪəli a dʒʌdʒ. juː noʊ, ðə ˈpɜːrsn huː meɪks dɪˈsɪʒnz ɪn a kɔːrt əv lɔː. ðæts a dʒʌdʒ/", vi: "Cụ ông Judge là một người đàn ông vô cùng tốt bụng. Ai nấy trong vùng đều quý mến và kính trọng sự chính trực của cụ. Nhưng ngặt một nỗi, cụ lại chẳng phải là một 'thẩm phán' thực thụ theo nghĩa chuyên môn — tức là người ngồi tòa phán quyết các vụ án pháp lý." },
      { "start": 17.0, "en": "One day, my mother wanted to make a deal with a company from another country. But it was too late to get a lawyer. They were willing to write out the agreement by hand and sign it that day. They asked Mr. Judge to write out the papers.", "ipa": "/wʌn deɪ, maɪ ˈmʌðər ˈwɒntɪd tuː meɪk a diːl wɪð a ˈkʌmpəni frɒm əˈnʌðər ˈkʌntri. bʌt ɪt wɒz tuː leɪt tuː ɡɛt a ˈlɔɪər. ðeɪ wɜːr ˈwɪlɪŋ tuː raɪt aʊt ði əˈɡriːmənt baɪ hænd ænd saɪn ɪt ðæt deɪ. ðeɪ ɑːskt ˈmɪstər dʒʌdʒ tuː raɪt aʊt ðə ˈpeɪpərz/", vi: "Vào một ngày nọ, mẹ tôi cần ký kết một hợp đồng thương mại gấp với một công ty nước ngoài, nhưng đã quá muộn để thuê luật sư. Cả hai bên thống nhất sẽ tự thảo văn bản bằng tay và ký kết ngay trong ngày. Họ liền nghĩ ra cách nhờ cụ ông Judge soạn thảo giấy tờ hộ." },
      { "start": 35.0, "en": "Right away, Mr. Judge put on his glasses. He sat at a big desk. He put the words on paper and read them clearly and loudly, just like a real judge. Then everyone signed the agreement. Mom says that it's interesting when people's jobs match their names. Yes, I'd like to see Ms. Baker bake at the bakery.", "ipa": "/raɪt əˈweɪ, ˈmɪstər dʒʌdʒ pʊt ɒn hɪz ˈɡlæsɪz. hiː sæt æt a bɪɡ dɛsk. hiː pʊt ðə wɜːrdz ɒn ˈpeɪpər ænd riːd ðɛm ˈklɪrli ænd ˈlaʊdli, dʒʌst laɪk a rɪəl dʒʌdʒ. ðɛn ˈɛvriˌwʌn saɪnd ði əˈɡriːmənt. mɒm sɛz ðæt ɪts ˈɪntrəstɪŋ wɛn ˈpiːplz dʒɒbz mætʃ ðɛr neɪmz. jɛs, aɪd laɪk tuː siː mɪz ˈbeɪkər beɪk æt ðə ˈbeɪkəri/", vi: "Ngay lập tức, cụ Judge đeo kính lão vào, oai nghiêm ngồi vào chiếc bàn làm việc lớn. Cụ cẩn thận nắn nót viết từng điều khoản ra giấy, rồi dõng dạc đọc to rõ ràng chẳng khác nào một vị quan tòa thực thụ trên công đường. Thế là mọi người vui vẻ đặt bút ký kết hợp đồng. Mẹ cười bảo thật thú vị khi tên họ của ai đó lại trùng khớp với nghề nghiệp của họ. Chắc thế nên tôi rất tò mò muốn ghé xem cô Baker (Thợ Làm Bánh) trổ tài nướng bánh ở tiệm bánh ngọt ra sao!" }
    ]
  },
  {
    "day": 12,
    "title": "Gold or Corn?",
    image: "03 March/images/day_12.webp",
    audio: "03 March/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, a very hungry rooster was searching for food. He was having no luck. It was getting late. But, no matter how hard he scratched the ground, the rooster could not find anything to eat.", "ipa": "/wʌn deɪ, a ˈvɛri ˈhʌŋɡri ˈruːstər wɒz ˈsɜːrtʃɪŋ fɔːr fuːd. hiː wɒz ˈhævɪŋ noʊ lʌk. ɪt wɒz ˈɡɛtɪŋ leɪt. bʌt, noʊ ˈmætər haʊ hɑːrd hiː skrætʃt ðə ɡraʊnd, ðə ˈruːstər kʊd nɒt faɪnd ˈɛniˌθɪŋ tuː iːt/", vi: "Vào một ngày nọ, chú Gà Trống đang đóи cồn cào đi lùng sục kiếm mồi khắp nơi nhưng chẳng gặp may mắn. Trời đã ngả về chiều, mặc sức cào bới tung tóe mặt đất nhưng Gà Trống vẫn chẳng tìm thấy hạt cơm nào bỏ bụng." },
      { "start": 18.0, "en": "Soon, the rooster struck something with his feet. 'What is this?' he wondered. 'Please let it be food. I really MUST eat, or I shall die.'", "ipa": "/suːn, ðə ˈruːstər strʌk ˈsʌmθɪŋ wɪð hɪz fiːt. wɒt ɪz ðɪs?, hiː ˈwʌndərd. pliːz lɛt ɪt biː fuːd. aɪ ˈrɪəli mʌst iːt, ɔːr aɪ ʃæl daɪ/", vi: "Chợt chân Gà Trống khều trúng một vật cứng nằm sâu dưới đất. 'Thứ gì thế này?' chú thầm nghĩ. 'Lạy trời đó là thức ăn. Tớ đang đói lả người rồi, không ăn chắc tớ chết mất.'" },
      { "start": 29.0, "en": "He scratched again quickly, eager to uncover what was hidden in the ground. To his disappointment, he found a piece of gold.", "ipa": "/hiː skrætʃt əˈɡɛn ˈkwɪkli, ˈiːɡər tuː ʌnˈkʌvər wɒt wɒz ˈhɪdn ɪn ðə ɡraʊnd. tuː hɪz ˌdɪsəˈpɔɪntmənt, hiː faʊnd a piːs əv ɡoʊld/", vi: "Chú ta gấp gáp cào bới dồn dập, hồi hộp mong chờ báu vật giấu kín. Nhưng hỡi ôi, trái ngược hoàn toàn với kỳ vọng, thứ lấp ló lộ diện lại là một thỏi vàng ròng nguyên khối." },
      { "start": 40.0, "en": "The rooster stood sadly, looking at the big piece of shiny gold. What is gold to a rooster? If a human finds gold, he sells it for a fortune. But a rooster cannot do anything with it.", "ipa": "/ðə ˈruːstər stʊd ˈsædli, ˈlʊkɪŋ æt ðə bɪɡ piːs əv ˈʃaɪni ɡoʊld. wɒt ɪz ɡoʊld tuː a ˈruːstər? ɪf a ˈhjuːmən faɪndz ɡoʊld, hiː sɛlz ɪt fɔːr a ˈfɔːrtʃuːn. bʌt a ˈruːstər ˈkænɒt duː ˈɛniˌθɪŋ wɪð ɪt/", vi: "Gà Trống tiu nghỉu đứng thừ người ngắm nghía thỏi vàng lấp lánh. Vàng đối với loài gà thì có tích sự gì cơ chứ? Con người nhặt được vàng thì đổi đời giàu sang phú quý, chứ gà thì chịu chết chẳng múc ăn được." },
      { "start": 53.0, "en": "The rooster walked away thinking, 'Gold has no value to me. I would trade all the gold in a king's castle for one small kernel of corn.'", "ipa": "/ðə ˈruːstər wɔːkt əˈweɪ ˈθɪŋkɪŋ, ɡoʊld hæz noʊ ˈvæljuː tuː miː. aɪ wʊd treɪd ɔːl ðə ɡoʊld ɪn a ˈkɪŋz ˈkæsl fɔːr wʌn smɔːl ˈkɜːrnl əv kɔːrn/", vi: "Gà Trống buồn bã bỏ đi và lẩm bẩm: 'Thứ kim loại này đối với ta vô giá trị. Ta sẵn sàng đánh đổi toàn bộ số vàng trong lâu đài nhà vua chỉ để lấy một hạt ngô bé nhỏ lúc này.'" }
    ]
  },
  {
    "day": 13,
    "title": "Seashells",
    image: "03 March/images/day_13.webp",
    audio: "03 March/audio/Track13.mp3",
    "sentences": [
      { "start": 4.8, "en": "Do you like seashells? Do you enjoy walking on the beach and collecting seashells? I do.", "ipa": "/duː juː laɪk ˈsiːˌʃɛlz? duː juː ɪnˈdʒɔɪ ˈwɔːkɪŋ ɒn ðə biːtʃ ænd kəˈlɛktɪŋ ˈsiːˌʃɛlz? aɪ duː/", vi: "Bạn có thích những chiếc vỏ sò biển không? Bạn có thích dạo bước trên bãi cát mịn màng để săn lùng và sưu tầm vỏ sò không? Riêng tôi thì mê tít." },
      { "start": 11.0, "en": "Recently, my parents took me down south over the Christmas holidays. We had a wonderful time on a small southern island.", "ipa": "/ˈriːsəntli, maɪ ˈpɛrənts tʊk miː daʊn saʊθ ˈoʊvər ðə ˈkrɪsməs ˈhɑːlədeɪz. wiː hæd a ˈwʌndərfʊl taɪm ɒn a smɔːl ˈsʌðərn ˈaɪlənd/", vi: "Cách đây không lâu, bố mẹ đã đưa tôi đi du lịch miền nam nhân dịp nghỉ lễ Giáng sinh. Chúng tôi đã có quãng thời gian tuyệt vời trên một hòn đảo nhiệt đới xinh đẹp." },
      { "start": 21.0, "en": "When we left Canada, the temperature was $-20^{\circ}C$. When we landed at the airport on the island, it was $+30^{\circ}C$. Yes! We had leaped from winter to summer in just five hours!", "ipa": "/wɛn wiː lɛft ˈkænədə, ðə ˈtɛmprətʃər wɒz maɪnəs twɛnti ˈdiːɡriːz. wɛn wiː ˈlændɪd æt ðə ˈɛrˌpɔːrt ɒn ðə ˈaɪlənd, ɪt wɒz ˈθɜːrti ˈdiːɡriːz. jɛs! wiː hæd liːpt frɒm ˈwɪntər tuː ˈsʌmər ɪn dʒʌst fʌɪv ˈaʊərz/", vi: "Lúc rời khỏi Canada băng giá, nhiệt độ ngoài trời là -20°C. Khi máy bay hạ cánh xuống sân bay trên đảo, nhiệt độ vọt lên tận +30°C. Thật kỳ diệu! Chúng tôi đã bay một mạch từ mùa đông sang mùa hè chỉ trong vỏn vẹn năm tiếng đồng hồ!" },
      { "start": 39.0, "en": "After we checked in at our hotel, we all ran to see the ocean. AMAZING! The waves were racing one after another towards the shore. As the water drew away, it left in front of us beautiful shells—shells in various shapes, colours and sizes.", "ipa": "/ˈɑːftər wiː tʃɛkt ɪn æt ˈaʊər hoʊtˈɛl, wiː ɔːl ræn tuː siː ði ˈoʊʃn. əˈmeɪzɪŋ! ðə weɪvz wɜːr ˈreɪsɪŋ wʌn ˈɑːftər əˈnʌðər təˈwɔːrdz ðə ʃɔːr. æz ðə ˈwɔːtər druː əˈweɪ, ɪt lɛft ɪn frʌnt əv ʌs ˈbjuːtɪfl ʃɛlz—ʃɛlz ɪn ˈvɛriəs ʃeɪps, ˈkʌlərz ænd ˈsaɪzɪz/", vi: "Sau khi làm thủ tục nhận phòng khách sạn, cả nhà tức tốc chạy ào ra biển. THẬT CHOÁNG NGỢP! Những con sóng lớn nối đuôi nhau xô vào bờ cát trắng. Khi triều rút đi, để lại trước mắt chúng tôi vô vàn vỏ sò lấp lánh đủ hình thù, màu sắc và kích cỡ khác nhau." },
      { "start": 57.0, "en": "I bent down to pick some up. Soon we had a pile of seashells on the beach. Looking at the seashells, my dad said that each shell showed us a life in the ocean. Imagine how much life there is under the ocean surface!", "ipa": "/aɪ bɛnt daʊn tuː pɪk sʌm ʌp. suːn wiː hæd a paɪl əv ˈsiːˌʃɛlz ɒn ðə biːtʃ. ˈlʊkɪŋ æt ðə ˈsiːˌʃɛlz, maɪ dæd sɛd ðæt iːtʃ ʃɛl ʃoʊd ʌs a laɪf ɪn ði ˈoʊʃn. ɪˈmædʒɪn haʊ mʌtʃ laɪf ðɛr ɪz ˈʌndər ði ˈoʊʃn ˈsɜːrfɪs/", vi: "Tôi khom người nhặt nhạnh, chẳng mấy chốc đã gom được một đống vỏ sò lớn trên bãi biển. Ngắm nhìn những chiếc vỏ sò ấy, bố bảo mỗi chiếc vỏ đều từng là một ngôi nhà của sinh vật dưới đại dương. Thử tưởng tượng xem có biết bao nhiêu sự sống kỳ diệu đang ẩn giấu bên dưới bề mặt biển sâu thẳm!" }
    ]
  },
  {
    "day": 14,
    "title": "Our Little Friend",
    image: "03 March/images/day_14.webp",
    audio: "03 March/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was late fall. We were eating dinner. Suddenly, we heard a loud BANG! A little bird flew right into the window, then fell to the ground.", "ipa": "/ɪt wɒz leɪt fɔːl. wiː wɜːr ˈiːtɪŋ ˈdɪnər. ˈsʌdənli, wiː hɜːrd a laʊd bæŋ! a ˈlɪtl bɜːrd fluː raɪt ˈɪntuː ðə ˈwɪndoʊ, ðɛn fɛl tuː ðə ɡraʊnd/", vi: "Đó là một buổi chiều muộn cuối thu. Khi gia đình đang quây quần ăn tối, bỗng BỤP một tiếng lớn vang lên! Một chú chim nhỏ bay đâm sầm vào khung cửa kính rồi rơi phịch xuống đất." },
      { "start": 16.0, "en": "We ran outside and saw that it was a baby crow. It was alive but one wing was not moving. It could not fly.", "ipa": "/wiː ræn ˈaʊtˌsaɪd ænd sɔː ðæt ɪt wɒz a ˈbeɪbi kroʊ. ɪt wɒz əˈlaɪv bʌt wʌn wɪŋ wɒz nɒt ˈmuːvɪŋ. ɪt kʊd nɒt flaɪ/", vi: "Chúng tôi hớt hải chạy ra xem thì phát hiện đó là một chú quạ con. Chú vẫn còn sống nhưng một bên cánh bị thương bất động, không thể vỗ cánh bay lên được." },
      { "start": 25.0, "en": "My dad picked up the bird. We put it in a box for the night. That one night turned into many nights. We named the bird Max. Max became very friendly to us. He took food from our hands. After a few weeks, his wing healed. Then one day, he flew away.", "ipa": "/maɪ dæd pɪkt ʌp ðə bɜːrd. wiː pʊt ɪt ɪn a bɒks fɔːr ðə naɪt. ðæt wʌn naɪt tɜːrnd ˈɪntuː ˈmɛni naɪts. wiː neɪmd ðə bɜːrd mæks. mæks bɪˈkeɪm ˈvɛri ˈfrɛndli tuː ʌs. hiː tʊk fuːd frɒm ˈaʊər hændz. ˈɑːftər a fjuː wiːks, hɪz wɪŋ hiːld. ðɛn wʌn deɪ, hiː fluː əˈweɪ/", vi: "Bố cẩn thận nâng chú quạ lên, lót một chiếc hộp các-tông để chăm sóc qua đêm. Đêm hôm đó kéo dài thành nhiều đêm tiếp theo. Chúng tôi đặt tên chú là Max. Càng ngày Max càng quấn quýt và thân thiện với gia đình tôi, tự giác mổ thức ăn ngay trên lòng bàn tay chúng tôi. Vài tuần sau, vết thương ở cánh lành hẳn. Và rồi vào một ngày đẹp trời, Max vỗ cánh bay cao về với bầu trời tự do." },
      { "start": 52.0, "en": "Now, every time I see a crow, I wonder, 'Is that Max?' Maybe he will come back for a visit one day.", "ipa": "/naʊ, ˈɛvri taɪm aɪ siː a kroʊ, aɪ ˈwʌndər, ɪz ðæt mæks? ˈmeɪbi hiː wɪl kʌm bæk fɔːr a ˈvɪzɪt wʌn deɪ/", vi: "Giờ đây, mỗi lần nhìn thấy một chú quạ nào đó, tôi lại thầm nghĩ: 'Liệu đó có phải là Max không nhỉ?' Biết đâu một ngày nào đó chú ấy sẽ quay trở lại thăm gia đình tôi thì sao." }
    ]
  },
  {
    "day": 15,
    "title": "Chicken Eggs",
    image: "03 March/images/day_15.webp",
    audio: "03 March/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "You find them on the ground, in trees and even in special houses built just for them. Their mother sits on them for weeks, but she does not hurt them. She just keeps them warm. Their parents have wings, and they will too.", "ipa": "/juː faɪnd ðɛm ɒn ðə ɡraʊnd, ɪn triːz ænd ˈiːvn ɪn ˈspɛʃl ˈhaʊsɪz bɪlt dʒʌst fɔːr ðɛm. ðɛr ˈmʌðər sɪts ɒn ðɛm fɔːr wiːks, bʌt ʃiː dʌz nɒt hɜːrt ðɛm. ʃiː dʒʌst kiːps ðɛm wɔːrm. ðɛr ˈpɛrənts hæv wɪŋz, ænd ðeɪ wɪl tuː/", vi: "Bạn có thể bắt gặp chúng trên mặt đất, trên hốc cây hay thậm chí trong những chuồng trại kiên cố được xây riêng. Gà mẹ ấp ủ chúng suốt nhiều tuần liền với tất cả sự nâng niu để sưởi ấm. Bố mẹ chúng có đôi cánh, và mai sau chúng cũng thế." },
      { "start": 18.0, "en": "Their most common colours are white and brown. They can be big, small or in between. Be careful. Some are very soft and can break easily.", "ipa": "/ðɛr moʊst ˈkɒmən ˈkʌlərz ɑːr waɪt ænd braʊn. ðeɪ kæn biː bɪɡ, smɔːl ɔːr ɪn bɪˈtwiːn. biː ˈkɛrfəl. sʌm ɑːr ˈvɛri sɒft ænd kæn breɪk ˈiːzɪli/", vi: "Màu sắc phổ biến nhất của chúng là trắng và nâu, với đủ kích cỡ lớn nhỏ khác nhau. Hãy cẩn thận nhé, vỏ của một số loại rất mỏng manh và dễ vỡ." },
      { "start": 28.0, "en": "What are they? Eggs, of course! All around the world, people eat eggs. But chicken eggs are the most popular. Boiled or fried, they taste really good.", "ipa": "/wɒt ɑːr ðeɪ? ɛɡz, əv kɔːrs! ɔːl əv ˈraʊnd ðə wɜːrld, ˈpiːpl iːt ɛɡz. bʌt ˈtʃɪkɪn ɛɡz ɑːr ðə moʊst ˈpɒpjələr. bɔɪld ɔːr fraɪd, ðeɪ teɪst ˈrɪəli ɡʊd/", vi: "Đó là gì thế nhỉ? Đương nhiên là trứng rồi! Khắp nơi trên thế giới, con người đều ăn trứng, trong đó trứng gà là phổ biến nhất. Dù đem luộc hay chiên rán lên thì chúng đều vô cùng thơm ngon." },
      { "start": 41.0, "en": "The Chinese are world leaders in chicken egg production, producing nearly 160 billion eggs a year. Here's a challenge: one chicken can lay about 250 eggs in one year. That's a lot of eggs. Can you figure out how many chickens it will take to lay 160 billion eggs?", "ipa": "/ðə ˈtʃaɪˈniːz ɑːr wɜːrld ˈliːdərz ɪn ˈtʃɪkɪn ɛɡ prəˈdʌkʃn, prəˈduːsɪŋ ˈnɪərli wʌn ˈhʌndrəd ˈsɪksti ˈbɪljən ɛɡz a jɪər. hɪərz a ˈtʃælɪndʒ: wʌn ˈtʃɪkɪn kæn leɪ əvˈbaʊt ˈtuː ˈhʌndrəd fɪfti ɛɡz ɪn wʌn jɪər. ðæts a lɒt əv ɛɡz. kæn juː ˈfɪɡər aʊt haʊ ˈmɛni ˈtʃɪkɪnz ɪt wɪl teɪk tuː leɪ wʌn ˈhʌndrəd ˈsɪksti ˈbɪljən ɛɡz?/", vi: "Trung Quốc hiện là quốc gia dẫn đầu thế giới về sản lượng trứng gia cầm, cung cấp gần 160 tỷ quả trứng mỗi năm. Thử thách dành cho bạn đây: Trung bình một cô gà mái có thể đẻ khoảng 250 quả trứng một năm. Vậy đố bạn biết cần phải huy động bao nhiêu con gà mái để sản xuất ra được 160 tỷ quả trứng ấy?" }
    ]
  },
  {
    "day": 16,
    "title": "Why Is It Colder Up There?",
    image: "03 March/images/day_16.webp",
    audio: "03 March/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "Miso and his father are flying from Korea to Canada. Miso is very excited.", "ipa": "/ˈmiːsoʊ ænd hɪz ˈfɑːðər ɑːr ˈflaɪɪŋ frɒm kəˈriːə tuː ˈkænədə. ˈmiːsoʊ ɪz ˈvɛri ɪkˈsaɪtɪd/", vi: "Miso cùng bố đang trên chuyến bay từ Hàn Quốc sang Canada. Cậu bé vô cùng háo hức." },
      { "start": 10.0, "en": "On the back of the seat, there is a small computer screen. It shows the path the jet is taking and how fast it is travelling. It also shows the temperature outside.", "ipa": "/ɒn ðə bæk əv ðə siːt, ðɛr ɪz a smɔːl kəmˈpjuːtər skriːn. ɪt ʃoʊz ðə pæθ ðə dʒɛt ɪz ˈteɪkɪŋ ænd haʊ fɑːst ɪt ɪz ˈtrævəlɪŋ. ɪt ˈɔːlsoʊ ʃoʊz ðə ˈtɛmprətʃər ˈaʊtˌsaɪd/", vi: "Phía lưng ghế phía trước gắn một màn hình máy tính nhỏ hiển thị lộ trình bay của máy bay phản lực, vận tốc di chuyển và cả nhiệt độ ở bên ngoài trời." },
      { "start": 21.0, "en": "Miso notices something really strange. The temperature outside the jet is $-55^{\circ}C$. That's really cold. 'When we left Seoul it was nearly $+25^{\circ}C$,' thinks Miso. 'How can this be?'", "ipa": "/ˈmiːsoʊ ˈnoʊtɪsɪz ˈsʌmθɪŋ ˈrɪəli streɪndʒ. ðə ˈtɛmprətʃər ˈaʊtˌsaɪd ðə dʒɛt ɪz maɪnəs ˈfɪfti-faɪv ˈdiːɡriːz. ðæts ˈrɪəli koʊld. wɛn wiː lɛft soʊl ɪt wɒz ˈnɪərli ˈtwɛnti-faɪv ˈdiːɡriːz, θɪŋks ˈmiːsoʊ. haʊ kæn ðɪs biː?/", vi: "Miso phát hiện ra một điều vô cùng lạ lùng: Nhiệt độ bên ngoài máy bay đang ở mức -55°C, thực sự buốt giá. 'Lúc chúng mình rời Seoul trời ấm gần +25°C cơ mà,' Miso thầm nghĩ. 'Sao lại có sự chênh lệch lớn thế nhỉ?'" },
      { "start": 38.0, "en": "So he asks his father a question. 'In this jet, we are closer to the sun. Shouldn't it be much hotter because we are closer to the sun? Why is it colder up here?'", "ipa": "/soʊ hiː ɑːsks hɪz ˈfɑːðər a ˈkwɛstʃən. ɪn ðɪs dʒɛt, wiː ɑːr ˈkloʊsər tuː ðə sʌn. ˈʃʊdnt ɪt biː mʌtʃ ˈhɒtər bɪˈkəz wiː ɑːr ˈkloʊsər tuː ðə sʌn? waɪ ɪz ɪt ˈkoʊldər ʌp hɪər?/", vi: "Cậu bèn quay sang thắc mắc với bố: 'Ngồi trên máy bay này nghĩa là chúng ta đang ở gần mặt trời hơn. Lẽ ra phải càng nóng hơn chứ vì khoảng cách gần hơn cơ mà? Tại sao lên cao thế này lại càng lạnh buốt thế bố?'" },
      { "start": 53.0, "en": "Father smiles. 'The ground is very good at taking in the heat from the sun,' he explains. 'The sun heats up the ground, which then slowly lets go of the heat. But we are many miles above the ground now in this jet. The heat from the ground cannot reach us here.'", "ipa": "/ˈfɑːðər smaɪlz. ðə ɡraʊnd ɪz ˈvɛri ɡʊd æt ˈteɪkɪŋ ɪn ðə hiːt frɒm ðə sʌn, hiː ɪkˈspleɪnz. ðə sʌn hiːts ʌp ðə ɡraʊnd, wɪtʃ ðɛn ˈsloʊli lɛts ɡoʊ əv ðə hiːt. bʌt wiː ɑːr ˈmɛni maɪlz əˈbʌv ðə ɡraʊnd naʊ ɪn ðɪs dʒɛt. ðə hiːt frɒm ðə ɡraʊnd ˈkænɒt riːtʃ ʌs hɪər/", vi: "Bố mỉm cười giải thích: 'Mặt đất hấp thụ nhiệt lượng từ ánh nắng mặt trời cực kỳ tốt con ạ. Mặt trời nung nóng mặt đất, rồi mặt đất từ từ tỏa hơi ấm đó ngược lại bầu khí quyển. Nhưng hiện tại chúng ta đang bay cách mặt đất hàng dặm trên chiếc phi cơ này, nên hơi ấm từ mặt đất không thể với tới tận đây được.'" },
      { "start": 71.0, "en": "Miso has learned something interesting today.", "ipa": "/ˈmiːsoʊ hæz lɜːrnd ˈsʌmθɪŋ ˈɪntrəstɪŋ təˈdeɪ/", vi: "Miso gật gù và lại lĩnh hội thêm được một kiến thức khoa học vô cùng thú vị trong ngày hôm nay." }
    ]
  },
  {
    "day": 17,
    "title": "The Mouse in the House",
    image: "03 March/images/day_17.webp",
    audio: "03 March/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "One morning, Becky's father said, 'There is a mouse in the kitchen. It is eating our food. We must get rid of it.'", "ipa": "/wʌn ˈmɔːrnɪŋ, ˈbɛkiz ˈfɑːðər sɛd, ðɛr ɪz a maʊs ɪn ðə ˈkɪtʃɪn. ɪt ɪz ˈiːtɪŋ ˈaʊər fuːd. wiː mʌst ɡɛt rɪd əv ɪt/", vi: "Vào một buổi sáng nọ, bố của Becky thông báo: 'Có một con chuột nhắt lẻn vào phòng bếp nhà mình rồi, nó đang ăn trộm thức ăn kìa. Chúng ta phải tìm cách đuổi nó đi thôi.'" },
      { "start": 14.0, "en": "Becky felt sorry for the mouse. 'What will you do? Will you kill the mouse?' she asked.", "ipa": "/ˈbɛki fɛlt ˈsɒri fɔːr ðə maʊs. wɒt wɪl juː duː? wɪl juː kɪl ðə maʊs?, ʃiː ɑːskt/", vi: "Becky nghe vậy liền cảm thấy thương hại chú chuột nhỏ và lo lắng hỏi: 'Thế bố định xử lý thế nào? Bố sẽ giết nó ạ?'" },
      { "start": 21.0, "en": "'No,' replied her father. 'We will set a special trap. When the mouse goes inside, it will not be able to get back out. Then, we will take it to a field. It can live there with other mice.'", "ipa": "/noʊ, rɪˈplaɪd hɜːr ˈfɑːðər. wiː wɪl sɛt a ˈspɛʃl træp. wɛn ðə maʊs ɡoʊz ˈɪnˌsaɪd, ɪt wɪl nɒt biː ˈeɪbl tuː ɡɛt bæk aʊt. ðɛn, wiː wɪl teɪk ɪt tuː a fiːld. ɪt kæn lɪv ðɛr wɪð ˈʌðər maɪs/", vi: "'Không con gái,' bố ôn tồn đáp. 'Bố sẽ dùng một chiếc bẫy chuyên dụng. Khi chú chuột chui vào trong, nó sẽ không thể tìm đường ra ngoài được nữa. Sau đó, hai bố con mình sẽ đem thả nó ra một cánh đồng rộng lớn, nơi nó có thể chung sống tự do cùng bầy chuột khác.'" },
      { "start": 38.0, "en": "That made Becky happy. The next day she looked at the mouse trap. There was a little grey mouse inside. It looked very frightened.", "ipa": "/ðæt meɪd ˈbɛki ˈhæpi. ðə nɛkst deɪ ʃiː lʊkt æt ðə maʊs træp. ðɛr wɒz a ˈlɪtl ɡreɪ maʊs ˈɪnˌsaɪd. ɪt lʊkt ˈvɛri ˈfraɪtnd/", vi: "Nghe bố hứa vậy, Becky vô cùng an tâm và vui sướng. Hôm sau, cô bé chạy ra kiểm tra chiếc bẫy và thấy một chú chuột xám nhỏ xíu đang rúc bên trong với ánh mắt sợ sệt tột độ." },
      { "start": 50.0, "en": "Becky and her father took the mouse to a big field. Her father put the trap on the ground. The mouse ran into the field.", "ipa": "/ˈbɛki ænd hɜːr ˈfɑːðər tʊk ðə maʊs tuː a bɪɡ fiːld. hɜːr ˈfɑːðər pʊt ðə træp ɒn ðə ɡraʊnd. ðə maʊs ræn ˈɪntuː ðə fiːld/", vi: "Becky cùng bố cẩn thận mang chiếc bẫy ra một cánh đồng hoang trải dài. Bố đặt chiếc bẫy xuống đất và mở nắp, chú chuột liền cuống cuồng chạy vút vào trong bãi cỏ xanh ngát." }
    ]
  },
  {
    "day": 18,
    "title": "Mean Mr. Green",
    image: "03 March/images/day_18.webp",
    audio: "03 March/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "'Hi Mr. Green!' Sally waved to the old man sitting on his front porch.", "ipa": "/haɪ ˈmɪstər ɡriːn! ˈsæli weɪvd tuː ðə oʊld mæn ˈsɪtɪŋ ɒn hɪz frʌnt pɔːrtʃ/", vi: "Sally vui vẻ vẫy tay chào: 'Cháu chào ông Green ạ!' hướng về phía cụ ông đang ngồi thừ người ngoài hiên nhà." },
      { "start": 10.0, "en": "'Don't say hi to him. He's mean,' whispered her friend, Josh.", "ipa": "/doʊnt seɪ haɪ tuː hɪm. hiːz miːn, ˈwɪspərd hɜːr frɛnd, dʒɒʃ/", vi: "Cậu bạn Josh đi cùng liền kéo tay cô bé thì thầm: 'Đừng có chào ông ta làm gì, dữ dằn khó tính lắm đấy.'" },
      { "start": 15.0, "en": "'He's not mean. He's just sad.' 'Sad about what?' 'His wife went away. That made him sad.'", "ipa": "/hiːz nɒt miːn. hiːz dʒʌst sæd. sæd əˈbaʊt wɒt? hɜːr waɪf wɛnt əˈweɪ. ðæt meɪd hɪm sæd/", vi: "'Ông ấy không hề dữ đâu, chỉ là ông đang buồn thôi,' Sally bênh vực. 'Buồn chuyện gì cơ?' 'Vợ của ông ấy đã qua đời rồi, điều đó làm ông đau lòng lắm.'" },
      { "start": 25.0, "en": "That night, Sally decided to draw a picture for her neighbour. She drew herself and Mr. Green sitting on his porch, drinking lemonade. She drew big smiles on their faces and a bright sun in the sky.", "ipa": "/ðæt naɪt, ˈsæli dɪˈsaɪdɪd tuː drɔː a ˈpɪktʃər fɔːr hɜːr ˈneɪbər. ʃiː druː hɜːrˈsɛlf ænd ˈmɪstər ɡriːn ˈsɪtɪŋ ɒn hɪz pɔːrtʃ, ˈdrɪŋkɪŋ ˌlɛməˈneɪd. ʃiː druː bɪɡ smaɪlz ɒn ðɛr ˈfeɪsɪz ænd a braɪt sʌn ɪn ðə skaɪ/", vi: "Đêm hôm đó, Sally quyết định vẽ một bức tranh dành tặng cho người hàng xóm đặc biệt của mình. Trong tranh là hình ảnh cô bé và ông Green đang cùng ngồi thưởng thức nước chanh mát lạnh ngoài hiên nhà, với những nụ cười tươi rói nở trên môi dưới bầu trời ngập tràn ánh nắng." },
      { "start": 41.0, "en": "The next day, Sally gave Mr. Green the picture. He looked like he was going to cry. Sally felt bad. 'I just wanted to see you smile again,' she said shyly.", "ipa": "/ðə nɛkst deɪ, ˈsæli ɡeɪv ˈmɪstər ɡriːn ðə ˈpɪktʃər. hiː lʊkt laɪk hiː wɒz ˈɡoʊɪŋ tuː kraɪ. ˈsæli fɛlt bæd. aɪ dʒʌst ˈwɒntɪd tuː siː juː smaɪl əˈɡɛn, ʃiː sɛd ˈʃaɪli/", vi: "Hôm sau, Sally rụt rè mang bức tranh đến biếu ông Green. Cụ đón lấy bức tranh, đôi mắt rưng rưng như trực trào nước mắt khiến Sally chạnh lòng áy náy. 'Cháu chỉ muốn thấy ông cười vui trở lại thôi ạ,' cô bé thẹn thùng thì thầm." },
      { "start": 57.0, "en": "Mr. Green looked up from the picture. 'Would you like some lemonade, Sally?' he asked. 'Yes, I would. Thank you.' As Sally and Mr. Green sat on his porch enjoying their lemonade, mean Mr. Green was smiling again.", "ipa": "/ˈmɪstər ɡriːn lʊkt ʌp frɒm ðə ˈpɪktʃər. wʊd juː laɪk sʌm ˌlɛməˈneɪd, ˈsæli? hiː ɑːskt. jɛs, aɪ wʊd. θæŋk juː. æz ˈsæli ænd ˈmɪstər ɡriːn sæt ɒn hɪz pɔːrtʃ ɪnˈdʒɔɪɪŋ ðɛr ˌlɛməˈneɪd, miːn ˈmɪstər ɡriːn wɒz ˈsmaɪlɪŋ əˈɡɛn/", vi: "Ông Green ngước lên khỏi bức vẽ, giọng nghẹn ngào: 'Sally có muốn uống nước chanh với ông không?' 'Dạ có ạ, cháu cảm ơn ông.' Và cứ thế, dưới hiên nhà ngập nắng, hình ảnh ông cụ cau có khó tính ngày nào nay đã rạng rỡ nụ cười tươi tắn bên cạnh cô bé nhỏ." }
    ]
  },
  {
    "day": 19,
    "title": "My Older Brother",
    image: "03 March/images/day_19.webp",
    audio: "03 March/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "My brother is the oldest among the six children in our family. He is smart, but he had to drop out of school at the age of twelve to help our parents—there were too many mouths to feed.", "ipa": "/maɪ ˈbrʌðər ɪz ði ˈoʊldɪst əˈmʌŋ ðə sɪks ˈtʃɪldrən ɪn ˈaʊər ˈfæməli. hiː ɪz smɑːrt, bʌt hiː hæd tuː drɒp aʊt əv skuːl æt ði eɪdʒ əv twɛlv tuː hɛlp ˈaʊər ˈpɛrənts—ðɛr wɜːr tuː ˈmɛni maʊðz tuː fiːd/", vi: "Anh trai là người anh cả trong số sáu anh chị em nhà tôi. Anh rất thông minh, ngặt nỗi phải nghỉ học từ năm mười hai tuổi để gác bút sách ở nhà phụ giúp bố mẹ kiếm kế sinh nhai vì gia đình quá đông con." },
      { "start": 18.0, "en": "Late fall was the season for harvesting. My brother took me to the field where the sweet potatoes had just been harvested. We got up early to look for any sweet potatoes that had been left in the field.", "ipa": "/leɪt fɔːl wɒz ðə ˈsiːzn fɔːr ˈhɑːrvɪstɪŋ. maɪ ˈbrʌðər tʊk miː tuː ðə fiːld wɛr ðə swiːt pəˈteɪtoʊz hæd dʒʌst biːn ˈhɑːrvɪstɪŋ. wiː ɡɒt ʌp ˈɜːrli tuː lʊk fɔːr ˈɛni swiːt pəˈteɪtoʊz ðæt hæd biːn lɛft ɪn ðə fiːld/", vi: "Cuối mùa thu là thời điểm mùa vụ thu hoạch rộ. Anh trai dẫn tôi ra khoảnh ruộng vừa mới gặt xong để mót khoai lang sót lại. Hai anh em dậy từ mờ sáng để cào xới tìm kiếm những củ khoai bị bỏ quên." },
      { "start": 33.0, "en": "With a heavy shovel, my brother started digging. My job was to watch the ground to see if any sweet potatoes appeared.", "ipa": "/wɪð a ˈhɛvi ˈʃʌvl, maɪ ˈbrʌðər ˈstɑːrtɪd ˈdɪɡɪŋ. maɪ dʒɒb wɒz tuː wɒtʃ ðə ɡraʊnd tuː siː ɪf ˈɛni swiːt pəˈteɪtoʊz əˈpɪərd/", vi: "Cầm trên tay chiếc xẻng nặng trịch, anh tôi bắt đầu cúi gập người cuốc đất. Nhiệm vụ của tôi là dỏng mắt trông chừng từng tấc đất xem có củ khoai nào lộ thiên không." },
      { "start": 43.0, "en": "It was still a little dark. My eyes opened wide while my brother dug in the soil. 'Wait! I saw one!' I yelled. My brother stopped digging. I picked up the sweet potato and put it in a basket. We were so happy. We felt like we had found a gold mine!", "ipa": "/ɪt wɒz stɪl a ˈlɪtl dɑːrk. maɪ aɪz ˈoʊpənd waɪd waɪl maɪ ˈbrʌðər dʌɡ ɪn ðə sɔɪl. weɪt! aɪ sɔː wʌn!, aɪ jɛld. maɪ ˈbrʌðər stɒpt ˈdɪɡɪŋ. aɪ pɪkt ʌp ðə swiːt pəˈteɪtoʊ ænd pʊt ɪt ɪn a ˈbɑːskɪt. wiː wɜːr soʊ ˈhæpi. wiː fɛlt laɪk wiː hæd faʊnd a ɡoʊld maɪn!/", vi: "Trời lúc đó vẫn còn mờ sمو mịt. Tôi trân trân mở to mắt nhìn anh cuốc đất. 'Khoan đã! Em thấy một củ rồi này!' tôi hét lên phấn khích. Anh dừng tay cuốc, tôi chồm tới nhặt củ khoai lang bỏ vào giỏ. Hai anh em sung sướng đến mức cảm giác như vừa trúng được mỏ vàng khổng lồ." },
      { "start": 62.0, "en": "An hour later, when the other people had come to the field, our basket was filled with sweet potatoes.", "ipa": "/ən ˈaʊər ˈleɪtər, wɛn ði ˈʌðər ˈpiːpl hæd kʌm tuː ðə fiːld, ˈaʊər ˈbɑːskɪt wɒz fɪld wɪð swiːt pəˈteɪtoʊz/", vi: "Chỉ một tiếng đồng hồ sau, khi những người dân khác lục tục ra đồng thì chiếc giỏ mót khoai của hai anh em tôi đã đầy ắp củ." }
    ]
  },
  {
    "day": 20,
    "title": "Tommy's Box",
    image: "03 March/images/day_20.webp",
    audio: "03 March/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "Tommy had a magic box. It wasn't too big, and it wasn't too small. It was just the right size—perfect for Tommy to climb in and sit down.", "ipa": "/ˈtɒmiz hæd a ˈmædʒɪk bɒks. ɪt ˈwɒznt tuː bɪɡ, ænd ɪt ˈwɒznt tuː smɔːl. ɪt wɒz dʒʌst ðə raɪt saɪz—ˈpɜːrfɪkt fɔːr ˈtɒmiz tuː klaɪm ɪn ænd sɪt daʊn/", vi: "Cậu bé Tommy sở hữu một chiếc hộp cát-tông thần kỳ. Nó không quá lớn cũng chẳng quá nhỏ — kích thước hoàn hảo để Tommy chui tọt vào trong và ngồi gọn lỏn." },
      { "start": 15.0, "en": "When Tommy sat in his box, the box became whatever Tommy wanted it to be. Sometimes, it was a car and Tommy would drive along the highway. Sometimes, it was a boat and Tommy would go fishing to catch fish for his family's supper.", "ipa": "/wɛn ˈtɒmiz sæt ɪn hɪz bɒks, ðə bɒks bɪˈkeɪm wɒtˈɛvər ˈtɒmiz ˈwɒntɪd ɪt tuː biː. ˈsʌmˌtaɪmz, ɪt wɒz a kɑːr ænd ˈtɒmiz wʊd draɪv əˈlɒŋ ðə ˈhaɪˌweɪ. ˈsʌmˌtaɪmz, ɪt wɒz a boʊt ænd ˈtɒmiz wʊd ɡoʊ ˈfɪʃɪŋ tuː kætʃ fɪʃ fɔːr hɪz ˈfæməlɪz ˈsʌpər/", vi: "Mỗi khi ngồi vào chiếc hộp ấy, nó lập tức biến hóa thành bất cứ thứ gì Tommy ao ước: Lúc thì là một chiếc ô tô để cậu lái vút trên đường cao tốc; lúc lại là chiếc thuyền nan để cậu đi câu cá cải thiện bữa tối cho gia đình." },
      { "start": 36.0, "en": "Sometimes, it was a plane and Tommy would fly high over the town. And sometimes, it was a rocket ship and Tommy was a famous astronaut.", "ipa": "/ˈsʌmˌtaɪmz, ɪt wɒz a pleɪn ænd ˈtɒmiz wʊd flaɪ haɪ ˈoʊvər ðə taʊn. ænd ˈsʌmˌtaɪmz, ɪt wɒz a ˈrɒkɪt ʃɪp ænd ˈtɒmiz wɒz a ˈfeɪməs ˈæstrəˌnɔːt/", vi: "Có lúc nó là chiếc máy bay gầm rú lượn lờ trên bầu trời thị trấn, và có lúc nó hóa thành phi thuyền không gian đưa Tommy bay vào vũ trụ trở thành nhà phi hành gia lừng danh." },
      { "start": 51.0, "en": "Tommy likes his magic box better than any of the toys his mom bought from the store. Don't you wish you had a magic box like Tommy's? Well, you can! All you need is a box!", "ipa": "/ˈtɒmiz laɪks hɪz ˈmædʒɪk bɒks ˈbɛtər ðæn ˈɛni əv ðə tɔɪz hɪz mɒm bɔːt frɒm ðə stɔːr. doʊnt juː wɪʃ juː hæd a ˈmædʒɪk bɒks laɪk ˈtɒmiz? wɛl, juː kæn! ɔːl juː niːd ɪz a bɒks!/", vi: "Tommy thích chiếc hộp phép thuật này hơn tất cả món đồ chơi đắt tiền nào mà mẹ mua ngoài hàng. Bạn có ước gì mình cũng sở hữu một chiếc hộp thần kỳ như thế không? Hoàn toàn được đấy nhé! Tất cả những gì bạn cần đơn giản chỉ là một chiếc hộp cũ mà thôi!" }
    ]
  },
  {
    "day": 21,
    "title": "A Family Picture",
    image: "03 March/images/day_21.webp",
    audio: "03 March/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "Little Irene drew an interesting picture. The picture was of a mother and a daughter sitting at a table in front of a house. Mom asked, 'Who are they?'", "ipa": "/ˈlɪtl aɪˈriːn druː ən ˈɪntrəstɪŋ ˈpɪktʃər. ðə ˈpɪktʃər wɒz əv a ˈmʌðər ænd a ˈdɔːtər ˈsɪtɪŋ æt a ˈteɪbl ɪn frʌnt əv a haʊs. mɒm ɑːskt, huː ɑːr ðeɪ?/", vi: "Cô bé Irene vừa vẽ được một bức tranh rất ý nghĩa. Trong tranh vẽ người mẹ và cô con gái đang ngồi quây quần bên chiếc bàn trước hiên nhà. Mẹ xem xong liền hỏi: 'Hai người trong tranh là ai thế con?'" },
      { "start": 15.0, "en": "'It's me and you,' said the little girl. Dad saw the picture. He wasn't very happy. He asked, 'Where is the daddy? Why am I not in the picture?'", "ipa": "/ɪts miː ænd juː, sɛd ðə ˈlɪtl ɡɜːrl. dæd sɔː ðə ˈpɪktʃər. hiː ˈwɒznt ˈvɛri ˈhæpi. hiː ɑːskt, wɛr ɪz ðə ˈdædi? waɪ æm aɪ nɒt ɪn ðə ˈpɪktʃər?/", vi: "'Là con với mẹ đấy ạ,' cô bé tí xíu đáp. Bố đi ngang qua nhìn thấy bức tranh và tỏ vẻ không vui lắm: 'Thế bố đâu mất rồi? Tại sao lại không có hình bóng của bố trong tranh?'" },
      { "start": 27.0, "en": "'Daddy is reading books inside the house. He is not playing with us.'", "ipa": "/ˈdædi ɪz ˈriːdɪŋ bʊks ˈɪnˌsaɪd ðə haʊs. hiː ɪz nɒt ˈpleɪɪŋ wɪð ʌs/", vi: "'Bố đang mải đọc sách tít trong nhà cơ mà, bố có chịu ra chơi cùng hai mẹ con đâu,' Irene hồn nhiên trả lời." },
      { "start": 34.0, "en": "What Irene said was true. Her dad was busy studying to become a doctor. He spent all his time reading books. He was so busy that he didn't have time to sit outside with them.", "ipa": "/wɒt aɪˈriːnz sɛd wɒz truː. hɜːr dæd wɒz ˈbɪzi ˈstʌdiɪŋ tuː bɪˈkʌm a ˈdɒktər. hiː spɛnt ɔːl hɪz taɪm ˈriːdɪŋ bʊks. hiː wɒz soʊ ˈbɪzi ðæt hiː ˈdɪdnt hæv taɪm tuː sɪt ˈaʊtˌsaɪd wɪð ðɛm/", vi: "Những lời Irene nói hoàn toàn đúng sự thật. Bố đang bận dùi mài kinh sử để thi lấy bằng bác sĩ, dành trọn vẹn thời gian vùi đầu vào đống sách vở đến mức chẳng có nổi một phút thảnh thơi ngồi hóng mát cùng vợ con ngoài sân." },
      { "start": 49.0, "en": "Irene's mom pointed out, 'See? That's how your daughter will remember you. If you keep busy like this all the time, you won't be in any of her childhood pictures.' From that day on, Irene's dad started going out more often with his daughter and wife.", "ipa": "/aɪˈriːnz mɒm ˈpɔɪntɪd aʊt, siː? ðæts haʊ jɔːr ˈdɔːtər wɪl rɪˈmɛmbər juː. ɪf juː kiːp ˈbɪzi laɪk ðɪs ɔːl ðə taɪm, juː woʊnt biː ɪn ˈɛni əv hɜːr ˈtʃaɪldhʊd ˈpɪktʃərz. frɒm ðæt deɪ ɒn, aɪˈriːnz dæd ˈstɑːrtɪd ˈɡoʊɪŋ aʊt mɔːr ˈɒfn wɪð hɪz ˈdɔːtər ænd waɪf/", vi: "Mẹ nghiêm túc nhắc nhở: 'Anh thấy đấy, con gái sẽ khắc họa hình ảnh của anh như thế này đây. Nếu lúc nào anh cũng bận bịu tối mắt tối mũi như thế, anh sẽ vắng mặt hoàn toàn trong mọi bức tranh tuổi thơ của con.' Kể từ hôm đó, bố đã thay đổi hoàn toàn, luôn tranh thủ sắp xếp thời gian đưa vợ con đi dạo chơi." }
    ]
  },
  {
    "day": 22,
    "title": "Tears in the Ocean",
    image: "03 March/images/day_22.webp",
    audio: "03 March/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "Bess was very upset. She hurt her arm in the backyard. She cried a lot. Her mom cleaned the cut and put a bandage on it.", "ipa": "/bɛs wɒz ˈvɛri ʌpˈsɛt. ʃiː hɜːrt hɜːr ɑːrm ɪn ðə ˈbækˌjɑːrd. ʃiː kraɪd a lɒt. hɜːr mɒm kliːnd ðə kʌt ænd pʊt a ˈbændɪdʒ ɒn ɪt/", vi: "Bess đang vô cùng buồn tủi vì lỡ ngã trầy xước tay ở khu vườn sau nhà và khóc nức nở. Mẹ đã dịu dàng sát trùng vết thương và dán băng cá nhân cẩn thận cho cô bé." },
      { "start": 14.0, "en": "Her aunt gave her a glass of water. 'Bess, you know those tears running down your cheeks are falling to the ground?'", "ipa": "/hɜːr ænt ɡeɪv hɜːr a glæs əv ˈwɔːtər. bɛs, juː noʊ ðoʊz tɪərz ˈrʌnɪŋ daʊn jɔːr tʃiːks ɑːr ˈfɔːlɪŋ tuː ðə ɡraʊnd?/", vi: "Người dì bước tới đưa cho bé một cốc nước mát và hỏi: 'Bess này, con có biết những giọt nước mắt đang lăn dài trên má con vừa rồi sẽ đi về đâu không?'" },
      { "start": 23.0, "en": "'Yes,' said Bess. 'Those tears go into the ground. The rain takes them to the river. And the river flows into the sea. Then the hot sun makes the wet air from the sea rise up into the sky.'", "ipa": "/jɛs, sɛd bɛs. ðoʊz tɪərz ɡoʊ ˈɪntuː ðə ɡraʊnd. ðə reɪn teɪks ðɛm tuː ðə ˈrɪvər. ænd ðə ˈrɪvər floʊz ˈɪntuː ðə siː. ðɛn ðə hɒt sʌn meɪks ðə wɛt ɛr frɒm ðə siː raɪz ʌp ˈɪntuː ðə skaɪ/", vi: "'Dạ thưa dì, nước mắt sẽ rơi xuống đất, rồi nước mưa cuốn chúng chảy ra sông, từ sông chảy ra đại dương mênh mông. Sau đó sức nóng của mặt trời làm bốc hơi lượng nước ẩm đó bay ngược lên bầu trời ạ,' Bess ngoan ngoãn đáp." },
      { "start": 41.0, "en": "Her aunt said, 'This wet air becomes clouds. The clouds move over the land and rain falls from them. That rain fills our lakes. Our drinking water comes from those lakes.'", "ipa": "/hɜːr ænt sɛd, ðɪs wɛt ɛr bɪˈkʌmz klaʊdz. ðə klaʊdz muːv ˈoʊvər ðə lænd ænd reɪn fɔːlz frɒm ðɛm. ðæt reɪn fɪlz ˈaʊər leɪks. ˈaʊər ˈdrɪŋkɪŋ ˈwɔːtər kʌmz frɒm ðoʊz leɪks/", vi: "Dì mỉm cười giảng giải tiếp: 'Hơi nước ngưng tụ thành những đám mây. Mây di chuyển bay qua đất liền và trút những hạt mưa xuống. Những cơn mưa ấy bồi đầy nước vào các hồ nước ngọt, và nguồn nước sinh hoạt hằng ngày của chúng ta chính là được lấy từ những chiếc hồ đó đấy.'" },
      { "start": 57.0, "en": "Bess looked at the glass of water she was drinking. 'You mean I'm drinking my own tears?' she said, smiling. Her aunt laughed. 'Maybe!'", "ipa": "/bɛs lʊkt æt ðə glæs əv ˈwɔːtər ʃiː wɒz ˈdrɪŋkɪŋ. juː miːn aɪm ˈdrɪŋkɪŋ maɪ oʊn tɪərz?, ʃiː sɛd, ˈsmaɪlɪŋ. hɜːr ænt lɑːft. ˈmeɪbi!/", vi: "Bess sững người nhìn chằm chằm vào cốc nước trên tay, rồi khúc khích cười: 'Ý dì là con đang uống chính nước mắt của mình phải không ạ?' Người dì bật cười lớn: 'Biết đâu đấy!' " }
    ]
  },
  {
    "day": 23,
    "title": "For the Love of Kids",
    image: "03 March/images/day_23.webp",
    audio: "03 March/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "Some people do things for money. But Jonas Salk did things for people. Mr. Salk was born into a poor family. But he studied hard and became a scientist.", "ipa": "/sʌm ˈpiːpl duː θɪŋk fɔːr ˈmʌni. bʌt ˈdʒoʊnəs sɔːk dɪd θɪŋz fɔːr ˈpiːpl. ˈmɪstər sɔːk wɒz bɔːrn ˈɪntuː a pʊr ˈfæməli. bʌt hiː ˈstʌdid hɑːrd ænd bɪˈkeɪm a ˈsaɪəntɪst/", vi: "Nhiều người làm việc cốt chỉ vì tiền bạc, nhưng nhà bác học Jonas Salk lại cống hiến trọn đời vì hạnh phúc của con người. Salk sinh ra trong một gia đình nghèo khó, nhưng bằng ý chí tôi luyện khổ cực, ông đã vươn lên trở thành một nhà khoa học lỗi lạc." },
      { "start": 17.0, "en": "At that time, a terrible childhood disease was killing many kids. It was making others very sick and unable to walk. It was called polio. It scared people everywhere. They wanted someone to find a way to protect children from this disease. But that was not easy.", "ipa": "/æt ðæt taɪm, a ˈtɛrəbl ˈtʃaɪldhʊd dɪˈziːz wɒz ˈkɪlɪŋ ˈmɛni kɪdz. ɪt wɒz ˈmeɪkɪŋ ˈʌðərz ˈvɛri sɪk ænd ʌnˈeɪbl tuː wɔːk. ɪt wɒz kɔːld ˈpoʊlioʊ. ɪt skɛrd ˈpiːpl ˈɛvriˌwɛr. ðeɪ ˈwɒntɪd ˈsʌmwʌn tuː faɪnd a weɪ tuː prəˈtɛkt ˈtʃɪldrən frɒm ðɪs dɪˈziːz. bʌt ðæt wɒz nɒt ˈiːzi/", vi: "Vào thời điểm đó, một căn bệnh quái ác mang tên bại liệt (polio) đang cướp đi sinh mạng của vô số trẻ em, khiến nhiều đứa trẻ khác bị tàn phế suốt đời không thể đi lại được. Nỗi sợ hãi bao trùm khắp mọi nơi. Ai ai cũng khát khao tìm ra phương thuốc cứu vãn trẻ thơ khỏi đại dịch này, nhưng chặng đường nghiên cứu vô cùng chông gai." },
      { "start": 36.0, "en": "Nevertheless, Jonas Salk worked hard. In 1952, he discovered a vaccination that worked. Soon, polio began to disappear. The world was very happy. They honoured the great scientist.", "ipa": "/ˌnɛvərðəˈlɛs, ˈdʒoʊnəs sɔːk wɜːrkt hɑːrd. ɪn ˈnaɪˈtiːn ˈfɪfti-tuː, hiː dɪsˈkʌvərd a ˌvæksəˈneɪʃn ðæt wɜːrkt. suːn, ˈpoʊlioʊ bɪˈɡæn tuː ˌdɪsəˈpɪər. ðə wɜːrld wɒz ˈvɛri ˈhæpi. ðeɪ ˈɒnərd ðə ɡreɪt ˈsaɪəntɪst/", vi: "Bất chấp muôn vàn gian khó, Jonas Salk vẫn miệt mài ngày đêm trong phòng thí nghiệm. Vào năm 1952, ông đã chế 1thành công vắc-xin phòng bệnh bại liệt thần kỳ. Chẳng bao lâu sau, bóng đen bệnh bại liệt dần bị đẩy lùi. Cả thế giới vỡ òa hạnh phúc và vinh danh nhà khoa học vĩ đại." },
      { "start": 54.0, "en": "Mr. Salk could have made a lot of money from his discovery. But he decided that he did not want to do that. He gave away his discovery for free. When a writer asked him why, he said, 'I want as many kids as possible to get this vaccination. That alone will make me happy.'", "ipa": "/ˈmɪstər sɔːk kʊd hæv meɪd a lɒt əv ˈmʌni frɒm hɪz dɪˈskʌvəri. bʌt hiː dɪsˈsaɪdɪd ðæt hiː dɪd nɒt wɒnt tuː duː ðæt. hiː ɡeɪv əˈweɪ hɪz dɪsˈskʌvəri fɔːr friː. wɛn a ˈraɪtər ɑːskt hɪm waɪ, hiː sɛd, aɪ wɒnt æz ˈmɛni kɪdz æz ˈpɒsəbl tuː ɡɛt ðɪs ˌvæksəˈneɪʃn. ðæt əˈloʊn wɪl meɪk miː ˈhæpi/", vi: "Lẽ ra ông hoàn toàn có thể trở thành tỷ phú nhờ phát minh vĩ đại đó, nhưng Salk đã khước từ mọi lợi ích vật chất cá nhân. Ông quyết định hiến tặng phát minh của mình hoàn toàn miễn phí cho nhân loại. Khi một nhà báo ngạc nhiên hỏi lý do, ông điềm đạm đáp: 'Tôi chỉ mong có càng nhiều trẻ em trên thế giới được tiêm chủng miễn phí càng tốt. Điều đó đối với tôi chính là niềm hạnh phúc lớn lao nhất.'" }
    ]
  },
  {
    "day": 24,
    "title": "What Is Under the Bed?",
    image: "03 March/images/day_24.webp",
    audio: "03 March/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "I'm the youngest girl in my family. My older sisters like scary movies. I do not. But still, I ended up watching a scary movie with them. I was trying to act older.", "ipa": "/aɪm ði ˈjʌŋɡɪst ɡɜːrl ɪn maɪ ˈfæməli. maɪ ˈoʊldər ˈsɪstərz laɪk ˈskɛri ˈmuːviz. aɪ duː nɒt. bʌt stɪl, aɪ ˈɛndɪd ʌp ˈwɒtʃɪŋ a ˈskɛri ˈmuːvi wɪð ðɛm. aɪ wɒz ˈtraɪɪŋ tuː ækt ˈoʊldər/", vi: "Tôi là cô út trong gia đình. Các chị gái tôi rất thích xem phim kinh dị, còn tôi thì ghét cay ghét đắng. Thế nhưng hôm đó vì muốn ra vẻ mình đã lớn khôn nên tôi vẫn tò mò ngồi xem ké phim kinh dị cùng các chị." },
      { "start": 16.0, "en": "After the movie, I went right to bed. But I couldn't sleep. Every sound was scary. Finally, I started to fall asleep. But then, I heard a noise under my bed!", "ipa": "/ˈɑːftər ðə ˈmuːvi, aɪ wɛnt raɪt tuː bɛd. bʌt aɪ ˈkʊdnt sliːp. ˈɛvri saʊnd wɒz ˈskɛri. ˈfaɪnəli, aɪ ˈstɑːrtɪd tuː fɔːl əˈsliːp. bʌt ðɛn, aɪ hɜːrd a nɔɪz ˈʌndər maɪ bɛd!/", vi: "Xem xong bộ phim, tôi sợ hãi trùm chăn đi ngủ ngay nhưng mãi chẳng tài nào chợp mắt nổi. Mọi âm thanh xung quanh bỗng trở nên rùng rợn. Mãi cho đến gần sáng, khi thiu thiu chợp mắt được một lúc, tai tôi bỗng nghe thấy tiếng sột soạt phát ra từ gầm giường!" },
      { "start": 29.0, "en": "I was really scared. I screamed. My whole family came rushing into the bedroom. 'What is under the bed?' I yelled.", "ipa": "/aɪ wɒz ˈrɪəli skɛrd. aɪ skriːmd. maɪ hoʊl ˈfæməli keɪm ˈrʌʃɪŋ ˈɪntuː ðə ˈbɛdˌruːm. wɒt ɪz ˈʌndər ðə bɛd?, aɪ jɛld/", vi: "Sợ dựng tóc gáy, tôi hét toáng lên hoảng loạn. Cả nhà giật mình vùng chạy ùa vào phòng ngủ: 'Con bị làm sao thế? Dưới gầm giường có gì à?' tôi gào khóc." },
      { "start": 39.0, "en": "My dad reached under the bed and pulled out the monster! I screamed again. Then I laughed. It was our cat Willy. Dad put Willy on the bed with me. I finally fell asleep.", "ipa": "/maɪ dæd riːtʃt ˈʌndər ðə bɛd ænd pʊld aʊt ðə ˈmɑːnstər! aɪ skriːmd əˈɡɛn. ðɛn aɪ lɑːft. ɪt wɒz ˈaʊər kæt ˈwɪli. dæd pʊt ˈwɪli ɒn ðə bɛd wɪð miː. aɪ ˈfaɪnəli fɛl əˈsliːp/", vi: "Bố bình tĩnh cúi người thò tay vào gầm giường và lôi 'con quái vật' ra ngoài! Tôi hoảng quá thét lên lần nữa, nhưng rồi lại phì cười thở phào nhẹ nhõm. Hóa ra đó chính là chú mèo Willy nghịch ngợm. Bố đặt Willy lên giường nằm cùng tôi, và thế là tôi yên tâm chìm vào giấc ngủ sâu." },
      { "start": 57.0, "en": "When I woke up in the morning, I said to my cat, 'No more scary movies for me, Willy.' I could see that he agreed. It had been a scary night for him too!", "ipa": "/wɛn aɪ woʊk ʌp ɪn ðə ˈmɔːrnɪŋ, aɪ sɛd tuː maɪ kæt, noʊ mɔːr ˈskɛri ˈmuːviz fɔːr miː, ˈwɪli. aɪ kʊd siː ðæt hiː əˈɡriːd. ɪt hæd biːn a ˈskɛri naɪt fɔːr hɪm tuː/", vi: "Sáng hôm sau tỉnh dậy, tôi nghiêm túc thủ thỉ với chú mèo: 'Từ nay cạch đến già không dám xem phim kinh dị nữa đâu nha Willy.' Trông điệu bộ của chú mèo có vẻ vô cùng đồng tình — chắc đêm qua chú ta cũng một phen hú vía hồn vía lên mây vì tiếng thét của tôi ấy chứ!" }
    ]
  },
  {
    "day": 25,
    "title": "Two Friends",
    image: "03 March/images/day_25.webp",
    audio: "03 March/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "There were two cats. One was Grey. The other was White. White lived in a warm house. Every day, he sat by the window, looking outside and feeling all alone.", "ipa": "/ðɛr wɜːr tuː kæts. wʌn wɒz ɡreɪ. ði ˈʌðər wɒz waɪt. waɪt lɪvd ɪn a wɔːrm haʊs. ˈɛvri deɪ, hiː sæt baɪ ðə ˈwɪndoʊ, ˈlʊkɪŋ ˈaʊtˌsaɪd ænd ˈfiːlɪŋ ɔːl əˈloʊn/", vi: "Câu chuyện kể về hai chú mèo: Một chú lông xám và một chú lông trắng muốt. Mèo Trắng được sống trong một ngôi nhà ấm cúng, ngày qua ngày chỉ biết ngồi thẫn thờ bên khung cửa sổ ngắm nhìn thế giới ngoài kia với nỗi cô đơn trống trải." },
      { "start": 18.0, "en": "Grey did not have a home. He ran outside catching leaves and chasing mice. He did not have any friends either.", "ipa": "/ɡreɪ dɪd nɒt hæv a hoʊm. hiː ræn ˈaʊtˌsaɪd ˈkætʃɪŋ liːvz ænd ˈtʃeɪsɪŋ maɪs. hiː dɪd nɒt hæv ˈɛni frɛndz ˈiːðər/", vi: "Trái lại, Mèo Xám lại là một chú mèo hoang không nơi nương tựa, ngày ngày lang thang ngoài đường bắt lá rơi đuổi bắt chuột, và cô độc chẳng có lấy một người bạn." },
      { "start": 27.0, "en": "Winter was coming, and the days were getting colder. One day, a door opened. Grey looked in. He saw White looking at him. The house was warm. Grey smelled delicious cat food.", "ipa": "/ˈwɪntər wɒz ˈkʌmɪŋ, ænd ðə deɪz wɜːr ˈɡɛtɪŋ ˈkoʊldər. wʌn deɪ, a dɔːr ˈoʊpənd. ɡreɪ lʊkt ɪn. hiː sɔː waɪt ˈlʊkɪŋ æt hɪm. ðə haʊs wɒz wɔːrm. ɡreɪ smɛld dɪˈlɪʃəs kæt fuːd/", vi: "Mùa đông lạnh buốt đang kéo đến từng ngày. Một hôm, cánh cửa nhà hé mở, Mèo Xám rón rén ghé mắt nhìn vào trong và bắt gặp Mèo Trắng đang ngước nhìn mình. Căn nhà ngập tràn hơi ấm, phảng phất mùi thức ăn cho mèo thơm phức kích thích." },
      { "start": 42.0, "en": "He took a step into the house. Then he took another. Soon he was in the house. He looked around. It was safe and warm. White walked over. The two touched nose to nose, sniffing each other. Soon, they were cuddled together in the soft cat bed.", "ipa": "/hiː tʊk a stɛp ˈɪntuː ðə haʊs. ðɛn hiː tʊk əˈnʌðər. suːn hiː wɒz ɪn ðə haʊs. hiː lʊkt əˈraʊnd. ɪt wɒz seɪf ænd wɔːrm. waɪt wɔːkt ˈoʊvər. ðə tuː tʌtʃt noʊz tuː noʊz, ˈsnɪfɪŋ iːtʃ ˈʌðər. suːn, ðeɪ wɜːr ˈkʌdld təˈɡɛðər ɪn ðə sɒft kæt bɛd/", vi: "Chú rụt rè bước một bước vào nhà, rồi bước tiếp bước thứ hai, và chẳng mấy chốc đã đứng hẳn trong phòng khách an toàn, ấm áp. Mèo Trắng thong thả tiến lại gần. Hai chiếc mũi nhỏ chạm khẽ vào nhau hít hà làm quen. Chỉ một thoáng sau, đôi bạn mới quen đã quấn quýt cuộn tròn ôm lấy nhau ngủ say sưa trên chiếc đệm êm ái." }
    ]
  },
  {
    "day": 26,
    "title": "Happy to Be Busy",
    image: "03 March/images/day_26.webp",
    audio: "03 March/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. Plano is more than eighty years old. He is healthy and happy. He rarely needs a doctor. What is the trick of keeping old age away from this old man?", "ipa": "/ˈmɪstər ˈplænoʊ ɪz mɔːr ðæn ˈeɪti jɪərz oʊld. hiː ɪz ˈhɛlθi ænd ˈhæpi. hiː ˈrɛrli niːdz a ˈdɒktər. wɒt ɪz ðə trɪk əv ˈkiːpɪŋ oʊld eɪdʒ əˈweɪ frɒm ðɪs oʊld mæn?/", vi: "Cụ ông Plano năm nay đã bước sang tuổi tám mươi. Trông cụ vẫn vô cùng tráng kiện, tinh thần lạc quan yêu đời và cực kỳ ít khi phải thăm khám bác sĩ. Bí quyết nào giúp cụ đẩy lùi tuổi già tuyệt vời đến vậy?" },
      { "start": 16.0, "en": "He says his trick is 'keeping busy'. When you visit his home, you will find a lot of furniture and picture frames. He makes them himself.", "ipa": "/hiː sɛz hɪz trɪk ɪz ˈkiːpɪŋ ˈbɪzi. wɛn juː ˈvɪzɪt hɪz hoʊm, juː wɪl faɪnd a lɒt əv ˈfɜːrnɪtʃər ænd ˈpɪktʃər freɪmz. hiː meɪks ðɛm hɪmˈsɛlf/", vi: "Cụ tiết lộ bí kíp trường thọ của mình chính là 'luôn bận rộn'. Nếu có dịp ghé thăm nhà cụ, bạn sẽ phải trầm trồ trước vô số đồ nội thất và khung ảnh thủ công tinh xảo — tất cả đều do một tay cụ tự chế tác." },
      { "start": 27.0, "en": "Is he a carpenter? No, Mr. Plano is not a carpenter. He was a gym teacher before he retired.", "ipa": "/ɪz hiː a ˈkɑːrpəntər? noʊ, ˈmɪstər ˈplænoʊ ɪz nɒt a ˈkɑːrpəntər. hiː wɒz a dʒɪm ˈtiːtʃər bɪˈfɔːr hiː rɪˈtaɪərd/", vi: "Phải chăng cụ là thợ mộc chuyên nghiệp? Không đâu, cụ Plano chưa từng làm thợ mộc. Trước khi về hưu, cụ từng là một giáo viên thể dục miệt mài." },
      { "start": 36.0, "en": "When he retired, he started making furniture. He learned to cut, saw, sand and glue. He loves wood. And he loves woodworking. More importantly, he loves to be busy.", "ipa": "/wɛn hiː rɪˈtaɪərd, hiː ˈstɑːrtɪd ˈmeɪkɪŋ ˈfɜːrnɪtʃər. hiː lɜːrnd tuː kʌt, sɔː, sænd ænd gluː. hiː lʌvz wʊd. ænd hiː lʌvz ˈwʊdˌwɜːrkɪŋ. mɔːr ɪmˈpɔːrtəntli, hiː lʌvz tuː biː ˈbɪzi/", vi: "Khi chính thức nghỉ hưu, cụ bắt đầu mày mò tập tành làm đồ gỗ. Cụ tự học cách cưa, xẻ, chà nhám và dán keo. Cụ đem lòng yêu những thớ gỗ mộc mạc và say mê nghệ thuật mộc thủ công. Và trên hết, cụ tận hưởng niềm vui mỗi ngày khi được bận rộn lao động." },
      { "start": 53.0, "en": "He collects the furniture that people throw away. From these old pieces of furniture, he makes stools, desks, tables and picture frames. He says he is happy to be as busy as a bee.", "ipa": "/hiː kəˈlɛkts ðə ˈfɜːrnɪtʃər ðæt ˈpiːpl θroʊ əˈweɪ. frɒm ðiːz oʊld piːsɪz əv ˈfɜːrnɪtʃər, hiː meɪks stuːlz, dɛsks, ˈteɪblz ænd ˈpɪktʃər freɪmz. hiː sɛz hiː ɪz ˈhæpi tuː biː æz ˈbɪzi æz a biː/", vi: "Cụ thường đi gom nhặt những món đồ gỗ cũ kỹ hỏng hóc mà người ta vứt đi, rồi tận dụng tái chế chúng thành những chiếc ghế đẩu, bàn học, bàn trà hay khung ảnh nghệ thuật độc đáo. Cụ cười vui bảo rằng mình mãn nguyện và hạnh phúc biết bao khi lúc nào cũng bận rộn tất bật như một chú ong chăm chỉ." }
    ]
  },
  {
    "day": 27,
    "title": "What Colour Is That?",
    image: "03 March/images/day_27.webp",
    audio: "03 March/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "Allan's father wears a suit with a shirt and tie to work. Sometimes, the shirt is blue. Sometimes, it's green. Sometimes, it's white. But every morning, he needs Allan's help to get a tie that matches his shirt.", "ipa": "/ˈælənz ˈfɑːðər wɛərz a suːt wɪð a ʃɜːrt ænd taɪ tuː wɜːrk. ˈsʌmˌtaɪmz, ðə ʃɜːrt ɪz bluː. ˈsʌmˌtaɪmz, ɪts ɡriːn. ˈsʌmˌtaɪmz, ɪts waɪt. bʌt ˈɛvri ˈmɔːrnɪŋ, hiː niːdz ˈælənz hɛlp tuː ɡɛt a taɪ ðæt ˈmætʃɪz hɪz ʃɜːrt/", vi: "Bố của cậu bé Allan luôn mặc trang phục vest lịch sự kèm áo sơ mi và cà vạt mỗi khi đi làm. Hôm thì sơ mi xanh, lúc lại xanh lá hoặc trắng tinh. Nhưng sáng nào bố cũng phải nhờ Allan phối hợp chọn hộ chiếc cà vạt sao cho hợp tông màu với áo sơ mi." },
      { "start": 21.0, "en": "What's the problem? Allan's father is colour blind. He cannot tell green from red. He cannot tell blue from green.", "ipa": "/wɒts ðə ˈprɒbləm? ˈælənz ˈfɑːðər ɪz ˈkʌlər blaɪnd. hiː ˈkænɒt tɛl ɡriːn frɒm rɛd. hiː ˈkænɒt tɛl bluː frɒm ɡriːn/", vi: "Đâu là nguyên nhân ư? Bố của Allan mắc chứng bệnh mù màu. Bố không thể phân biệt được đâu là màu xanh lá và màu đỏ, cũng chẳng nhận diện được màu xanh dương với xanh lá." },
      { "start": 30.0, "en": "Nearly one in ten men has some kind of colour-blindness. The most common kind is red-green. But some people cannot see any colours at all. Imagine how hard that is! Think of how dull the world looks to someone who cannot see colours! Luckily, Allan's father has Allan to help him out. Still, it's a problem he lives with every day.", "ipa": "/ˈnɪərli wʌn ɪn tɛn mɛn hæz sʌm kaɪnd əv ˈkʌlər-ˈblaɪndnəs. ðə moʊst ˈkɒmən kaɪnd ɪz rɛd-ɡriːn. bʌt sʌm ˈpiːpl ˈkænɒt siː ˈɛni ˈkʌlərz ænd ɔːl. ɪˈmædʒɪn haʊ hɑːrd ðæt ɪz! θɪŋk əv haʊ dʌl ðə wɜːrld lʊks tuː ˈsʌmwʌn huː ˈkænɒt siː ˈkʌlərz! ˈlʌkɪli, ˈælənz ˈfɑːðər hæz ˈælən tuː hɛlp hɪm aʊt. stɪl, ɪts a ˈprɒbləm hiː lɪvz wɪð ˈɛvri deɪ/", vi: "Tính ra cứ mười người đàn ông thì có gần một người mắc phải các dạng mù màu khác nhau, phổ biến nhất là mù màu đỏ - xanh lá. Thậm chí có những người hoàn toàn không thể nhận diện bất kỳ sắc màu nào trên đời. Thật khó khăn biết bao! Hãy thử tượng trưng thế giới sẽ trở nên tẻ nhạt biết nhường nào nếu đôi mắt không thể cảm nhận sắc màu. May mắn thay bố của Allan đã có cậu con trai nhỏ làm trợ lý đắc lực mỗi ngày, dù đó vẫn là một bất tiện đeo bám cuộc sống của bố." }
    ]
  },
  {
    "day": 28,
    "title": "Old Dog, New Tricks",
    image: "03 March/images/day_28.webp",
    audio: "03 March/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "Aunt Lisa is seventy-two years old. She does not own a computer. She sends letters through the post office. We make fun of her. We tell her that the days of stamps, envelopes and letters are long gone. Still, Aunty says, 'It was good enough when I was a girl. It should be good enough now. Besides, you can't teach an old dog new tricks!'", "ipa": "/ænt ˈliːzə ɪz ˈsɛvənti-tuː jɪərz oʊld. ʃiː dʌz nɒt oʊn a kəmˈpjuːtər. ʃiː sɛndz ˈlɛtərz θruː ðə poʊst ˈɔːfɪs. wiː meɪk fʌn əv hɜːr. wiː tɛl hɜːr ðæt ðə deɪz əv stæmps, ˈɛnvəˌloʊps ænd ˈlɛtərz ɑːr lɒŋ ɡɔːn. stɪl, ˈænti sɛd, ɪt wɒz ɡʊd ɪˈnʌf wɛn aɪ wɒz a ɡɜːrl. ɪt ʃʊd biː ɡʊd ɪˈnʌf naʊ. bɪˈsaɪdz, juː kænt tiːtʃ an oʊld dɔːɡ nuː trɪks!/", vi: "Dì Lisa năm nay đã 72 tuổi và không hề sở hữu một cỗ máy vi tính nào. Dì toàn gửi thư tay qua đường bưu điện truyền thống. Chúng tôi hay trêu chọc dì rằng thời đại của tem thư, phong bì và thư tay đã lỗi mốt từ lâu rồi. Thế nhưng dì vẫn quả quyết: 'Thời trẻ của ta dùng tốt thế nào thì bây giờ vẫn cứ tốt thế ấy. Hơn nữa, ngựa già thì khó dạy khôn mới được!'" },
      { "start": 29.0, "en": "So you can imagine our surprise when we got this email from Aunt Lisa: 'Hi Ally and Todd, As you know, I am travelling in Europe. Are you surprised to get this email? I bet you are. Well, before I left for my vacation, I took some lessons at the Seniors Computer Club. I learned how to send an email. So, I am sending you this message. I changed my mind. You CAN teach an old dog new tricks! Love, Aunt Lisa'", "ipa": "/soʊ juː kæn ɪˈmædʒɪn ˈaʊər sərˈpraɪz wɛn wiː ɡɒt ðɪs ˈiːˌmeɪl frɒm ænt ˈliːzə: haɪ ˈæli ænd tɒd, æz juː noʊ, aɪ æm ˈtrævəlɪŋ ɪn ˈjʊərəp. ɑːr juː sərˈpraɪzd tuː ɡɛt ðɪs ˈiːˌmeɪl? aɪ bɛt juː ɑːr. wɛl, bɪˈfɔːr aɪ lɛft fɔːr maɪ veɪˈkeɪʃn, aɪ tʊk sʌm ˈlɛsnz æt ðə ˈsiːnjərz kəmˈpjuːtər klʌb. aɪ lɜːrnd haʊ tuː sɛnd ən ˈiːˌmeɪl. soʊ, aɪ æm ˈsɛndɪŋ juː ðɪs ˈmɛsɪdʒ. aɪ tʃeɪndʒd maɪ maɪnd. juː kæn tiːtʃ an oʊld dɔːɡ nuː trɪks! lʌv, ænt ˈliːzə/", vi: "Thế nên các bạn có thể tưởng tượng được sự kinh ngạc tột độ của chúng tôi khi nhận được email này từ dì Lisa: 'Chào Ally và Todd, Như các cháu đã biết, ta đang đi du lịch vòng quanh châu Âu. Có ngạc nhiên khi nhận được email này không? Ta chắc chắn là có rồi. Sự thật là trước khi đi nghỉ mát, ta đã âm thầm tham gia khóa học tại Câu lạc bộ Vi tính Người cao tuổi và học được cách gửi email. Vậy nên ta gửi tin nhắn này để thông báo rằng: Ta đã đổi ý rồi đấy nhé, hoàn toàn có thể dạy điều mới cho người lớn tuổi được cơ mà! Yêu các cháu, Dì Lisa.'" }
    ]
  },
  {
    "day": 29,
    "title": "The Little Seeds",
    image: "03 March/images/day_29.webp",
    audio: "03 March/audio/Track29.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Dad asked me to help him plant some green peas. We put them a few inches into the ground. We covered them with soil and watered them.", "ipa": "/wʌn deɪ, dæd ɑːskt miː tuː hɛlp hɪm plɑːnt sʌm ɡriːn piːz. wiː pʊt ðɛm a fjuː ˈɪntʃɪz ˈɪntuː ðə ɡraʊnd. wiː ˈkʌvərd ðɛm wɪð sɔɪl ænd ˈwɔːtərd ðɛm/", vi: "Vào một ngày nọ, bố nhờ tôi phụ giúp trồng một ít hạt đậu Hà Lan xanh. Chúng tôi vùi những hạt giống xuống sâu vài inch dưới lòng đất, vun đất phủ kín lại và tưới nước ẩm đẫm." },
      { "start": 14.0, "en": "Every day, I went out to check if anything happened. Days passed and I started to think planting was a waste of time. Then one day, as I was doing my usual check, I noticed something. There were little green leaves poking out of the soil!", "ipa": "/ˈɛvri deɪ, aɪ wɛnt aʊt tuː tʃɛk ɪf ˈɛniˌθɪŋ ˈhæpənd. deɪz pæst ænd aɪ ˈstɑːrtɪd tuː θɪŋk ˈplɑːntɪŋ wɒz a weɪst əv taɪm. ðɛn wʌn deɪ, æz aɪ wɒz ˈduːɪŋ maɪ ˈjuːʒuəl tʃɛk, aɪ ˈnoʊtɪst ˈsʌmθɪŋ. ðɛr wɜːr ˈlɪtl ɡriːn liːvz ˈpoʊkɪŋ aʊt əv ðə sɔɪl/", vi: "Đều đặn mỗi ngày, tôi đều chạy ra hiên ngóng chờ xem có phép màu nào xảy ra chưa. Ngày tháng trôi qua và tôi bắt đầu chán nản nghĩ rằng việc trồng cây này thật tốn thời gian. Thế rồi vào một buổi sáng nọ khi đang kiểm tra quen thuộc, tôi sững người phát hiện ra những chiếc lá mầm xanh non đầu tiên đang nhô lên khỏi mặt đất!" },
      { "start": 35.0, "en": "It may seem silly, but it was very exciting to see this! The seeds we planted turned into plants. And these plants were going to grow sweet little peas. It made me think about how everything grows... even how people grow.", "ipa": "/ɪt meɪ siːm ˈsɪli, bʌt ɪt wɒz ˈvɛri ɪkˈsaɪtɪd tuː siː ðɪs! ðə siːdz wiː ˈplɑːntɪd tɜːrnd ˈɪntuː plænts. ænd ðiːz plænts wɜːr ˈɡoʊɪŋ tuː ɡroʊ swiːt ˈlɪtl piːz. ɪt meɪd miː θɪŋk əv haʊ ˈɛvriˌθɪŋ ɡroʊz... ˈiːvn haʊ ˈpiːpl ɡroʊ/", vi: "Nghe có vẻ ngốc nghếch nhưng khoảnh khắc ấy thực sự kỳ diệu và phấn khích đối với tôi! Những hạt giống bé xíu giờ đây đã vươn mình thành cây mầm xanh mướt, và chẳng mấy chốc chúng sẽ cho ra những trái đậu ngọt lịm. Điều đó khiến tôi miên man suy ngẫm về cách mà vạn vật sinh trưởng... và cả sự lớn khôn của con người chúng ta nữa." },
      { "start": 52.0, "en": "'In some ways, we are not so different from those little peas,' I said to my dad. 'We need food, water and a place to grow.' I learned a lot from those little seeds.", "ipa": "/ɪn sʌm weɪz, wiː ɑːr nɒt soʊ ˈdɪfrənt frɒm ðoʊz ˈlɪtl piːz, aɪ sɛd tuː maɪ dæd. wiː niːd fuːd, ˈwɔːtər ænd a pleɪs tuː ɡroʊ. aɪ lɜːrnd a lɒt frɒm ðoʊz ˈlɪtl siːdz/", vi: "'Nghĩ kỹ thì chúng ta cũng chẳng khác biệt mấy so với những hạt đậu nhỏ bé này đâu bố nhỉ,' tôi tâm sự với bố. 'Tất cả đều cần có thức ăn, nguồn nước và một khoảng không gian để vươn lên.' Quả thực tôi đã học hỏi được rất nhiều bài học quý giá từ những hạt giống nhỏ bé ấy." }
    ]
  },
  {
    "day": 30,
    "title": "Snowflakes",
    image: "03 March/images/day_30.webp",
    audio: "03 March/audio/Track30.mp3",
    "sentences": [
      { "start": 4.8, "en": "Snowflakes come from way up high. Snowflakes reach us from the sky.", "ipa": "/ˈsnoʊˌfleɪks kʌm frɒm weɪ ʌp haɪ. ˈsnoʊˌfleɪks riːtʃ ʌs frɒm ðə skaɪ/", vi: "Những bông tuyết trắng rơi xuống từ tận tít trên cao tận cùng, vượt qua tầng mây xanh để chạm đến mặt đất." },
      { "start": 10.0, "en": "The kids are singing this song. They are singing this song because it's snowing, and they will be going out soon to play in the snow!", "ipa": "/ðə kɪdz ɑːr ˈsɪŋɪŋ ðɪs sɔːŋ. ðeɪ ɑːr ˈsɪŋɪŋ ðɪs sɔːŋ bɪˈkəz ɪts ˈsnoʊɪŋ, ænd ðeɪ wɪl biː ˈɡoʊɪŋ aʊt suːn tuː pleɪ ɪn ðə snoʊ/", vi: "Lũ trẻ đang hào hứng hát vang khúc ca ấy bởi trời bắt đầu đổ tuyết rồi, và chúng sắp được thỏa thích ra ngoài vùng vẫy trong thế giới tuyết trắng!" },
      { "start": 18.0, "en": "Their teacher, Mrs. Austin, knows that her students love the snow. 'Did you know that in one snowstorm, billions of snowflakes fall?' she asks.", "ipa": "/ðɛər ˈtiːtʃər, ˈmɪsɪz ˈɔːstɪn, noʊz ðæt hɜːr ˈstuːdənts lʌv ðə snoʊ. dɪd juː noʊ ðæt ɪn wʌn ˈsnoʊˌstɔːrm, ˈbɪljənz əv ˈsnoʊˌfleɪks fɔːl?, ʃiː ɑːsks/", vi: "Cô giáo chủ nhiệm Austin thừa hiểu học trò của mình cuồng nhiệt tuyết đến nhường nào. Cô mỉm cười đố cả lớp: 'Các em có biết trong mỗi trận bão tuyết có tới bao nhiêu bông tuyết rơi xuống không?'" },
      { "start": 29.0, "en": "'Billions?' The kids are amazed. 'And even more amazing: no two snowflakes look the same. Each snowflake has its own shape. And every snowflake has six sides.'", "ipa": "/ˈbɪljənz? ðə kɪdz ɑːr əˈmeɪzd. ænd ˈiːvn mɔːr əˈmeɪzɪŋ: noʊ tuː ˈsnoʊˌfleɪks lʊk ðə seɪm. iːtʃ ˈsnoʊˌfleɪk hæz ɪts oʊn ʃeɪp. ænd ˈɛvri ˈsnoʊˌfleɪk hæz sɪks saɪdz/", vi: "'Hàng tỷ tỷ ạ?' Đám trẻ há hốc mồm kinh ngạc. 'Và điều kỳ diệu hơn nữa là: Không có bất kỳ hai bông tuyết nào trên đời hoàn toàn giống hệt nhau cả. Mỗi bông mang một hình thù độc bản, và tất cả chúng đều có đúng sáu cạnh cấu trúc.'" },
      { "start": 47.0, "en": "The kids are really excited to learn about snowflakes. Their teacher continues, 'Snowflakes are not always white. In places where there is a lot of pollution, snowflakes can be black or grey.' One kid asks, 'How fast do snowflakes fall?' Mrs. Austin smiles. 'About 5 kilometres an hour,' she says. 'Don't worry. You won't get hurt by falling snow-flakes. They are gentle and light. Now, let's go out and play!'", "ipa": "/ðə kɪdz ɑːr ˈrɪəli ɪkˈsaɪtɪd tuː lɜːrn əˈbaʊt ˈsnoʊˌfleɪks. ðɛər ˈtiːtʃər kənˈtɪnyuːz, ˈsnoʊˌfleɪks ɑːr nɒt ˈɔːlweɪz waɪt. ɪn ˈpleɪsɪz wɛr ðɛr ɪz a lɒt əv pəˈluːʃn, ˈsnoʊˌfleɪks kʌn biː blæk ɔːr ɡreɪ. wʌn kɪd ɑːsks, haʊ fɑːst duː ˈsnoʊˌfleɪks fɔːl? ˈmɪsɪz ˈɔːstɪn smaɪlz. əˈbaʊt fʌɪv ˈkɪləˌmiːtərz ən ˈaʊər, ʃiː sɛd. doʊnt ˈwʌri. juː woʊnt ɡɛt hɜːrt baɪ ˈfɔːlɪŋ ˈsnoʊˌfleɪks. ðeɪ ɑːr ˈdʒɛntl ænd laɪt. naʊ, lɛts ɡoʊ aʊt ænd pleɪ!/", vi: "Lũ trẻ vô cùng phấn khích khi được lĩnh hội những kiến thức mới lạ về tuyết. Cô giáo giảng giải thêm: 'Tuyết rơi không phải lúc nào cũng tinh khiết một màu trắng. Tại những vùng bị ô nhiễm nặng nề, bông tuyết thậm chí còn có màu đen hoặc xám xịt.' Một cậu nhóc tò mò hỏi: 'Thế tốc độ rơi của tuyết nhanh đến mức nào thưa cô?' Cô Austin mỉm cười đáp: 'Chỉ khoảng 5 km/h thôi các em ạ. Các em cứ yên tâm vui chơi, những bông tuyết rất nhẹ nhàng và êm ái nên chẳng thể làm chúng mình bị thương đâu. Nào, tất cả cùng ra sân chơi thôi!'" }
    ]
  },
  {
    "day": 31,
    "title": "Grandma, the Biker",
    image: "03 March/images/day_31.webp",
    audio: "03 March/audio/Track31.mp3",
    "sentences": [
      { "start": 4.8, "en": "'It's easy!' yelled my older brother. 'Anybody can do it!' Anybody but me. I had a new bike. But, I kept falling off. I was about to give up. Then, my grandmother came outside. 'Here, let me show you,' she said.", "ipa": "/ɪts ˈiːzi! jɛld maɪ ˈoʊldər ˈbrʌðər. ˈɛniˌbɒdi kæn duː ɪt! ˈɛniˌbɒdi bʌt miː. aɪ hæd a nuː baɪk. bʌt, aɪ kɛpt ˈfɔːlɪŋ ɔːf. aɪ wɒz əˈbaʊt tuː ɡɪv ʌp. ðɛn, maɪ ˈɡrændˌmʌðər keɪm ˈaʊtˌsaɪd. hɪər, lɛt miː ʃoʊ juː, ʃiː sɛd/", vi: "'Dễ ợt mà!' anh trai tôi hét lên đắc ý. 'Ai mà chẳng tập đi được!' Ai thì được chứ tôi thì hoài vẫn chưa học được. Tôi vừa được tặng một chiếc xe đạp mới tinh nhưng cứ hễ trèo lên là ngã dúi ngã dụi, suýt chút nữa thì định buông xuôi từ bỏ. Đúng lúc đó, bà ngoại từ trong nhà bước ra thong thả bảo: 'Nào, để bà thị phạm cho xem.'" },
      { "start": 18.0, "en": "We all said, 'No Grandma! You'll fall down. You'll hurt yourself!' My grandmother is small. But when she wants to do something, you'd better stay out of her way!", "ipa": "/wiː ɔːl sɛd, noʊ ˈɡrænmɑː! juːl fɔːl daʊn. juːl hɜːrt jɔːrˈsɛlf! maɪ ˈɡrændˌmʌðər ɪz smɔːl. bʌt wɛn ʃiː wɒnts tuː duː ˈsʌmθɪŋ, jʊd ˈbɛtər steɪ aʊt əv hɜːr weɪ!/", vi: "Cả đám hoảng hốt can ngăn: 'Không được đâu bà ơi! Bà ngã đau bây giờ!' Bà ngoại tuy vóc người nhỏ thó, nhưng một khi cụ đã quyết tâm làm gì thì đố ai cản nổi." },
      { "start": 29.0, "en": "My sister helped her get on my bike. Grandma started to pedal. Soon she took off. She rode right down the street. She rode out of sight!", "ipa": "/maɪ ˈsɪstər hɛlpt hɜːr ɡɛt ɒn maɪ baɪk. ˈɡrænmɑː ˈstɑːrtɪd tuː ˈpɛdl. suːn ʃiː tʊk ɔːf. ʃiː roʊd raɪt daʊn ðə striːt. ʃiː roʊd aʊt əv saɪt!/", vi: "Chị gái đành phụ giúp đỡ bà trèo lên yên chiếc xe đạp của tôi. Bà ngoại bắt đầu nhịp nhàng đạp bàn đạp. Chẳng mấy chốc chiếc xe băng băng lao vút đi, lướt thẳng một mạch dọc con phố rồi mất hút sau khúc cua lúc nào không hay!" },
      { "start": 41.0, "en": "We started to worry. Then, we heard a bell behind us. Grandma had gone all the way around the block!", "ipa": "/wiː ˈstɑːrtɪd tuː ˈwʌri. ðɛn, wiː hɜːrd a bɛl bɪˈhaɪnd ʌs. ˈɡrænmɑː hæd ɡɒn ɔːl ðə weɪ əˈraʊnd ðə blɒk/", vi: "Cả bọn bắt đầu thấp thỏm lo lắng thì bỗng nghe thấy tiếng chuông xe reng reng vang lên sau lưng. Hóa ra bà ngoại đã lái xe vòng trọn hết cả một khu phố lớn rồi quay về!" },
      { "start": 50.0, "en": "She got off the bike. 'You see,' she said. 'Once you get it, you'll never forget it!' My grandma was right. Soon I was riding too... Thanks to Grandma, the biker.", "ipa": "/ʃiː ɡɒt ɔːf ðə baɪk. juː siː, ʃiː sɛd. wʌns juː ɡɛt ɪt, juːl ˈnɛvər fərˈɡɛt ɪt! maɪ ˈɡrænmɑː wɒz raɪt. suːn aɪ wɒz ˈraɪdɪŋ tuː... θæŋks tuː ˈɡrænmɑː, ðə ˈbaɪkər/", vi: "Cụ thong thả chống chân bước xuống xe, mỉm cười đắc ý: 'Các cháu thấy chưa, một khi đã nắm được bí quyết thì đời đời kiếp kiếp không bao giờ quên được đâu!' Bà ngoại nói quả không sai chút nào. Chẳng mấy chốc sau đó tôi cũng tự mình đi được xe đạp... Tất cả là nhờ công ơn của 'quái xế' bà ngoại đấy." }
    ]
  }
];