if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["01 January"] = [
  {
    "day": 1,
    "title": "Where Does Milk Come from?",
    "image": "01 January/images/day_01.webp",
    "audio": "01 January/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "Billy is six years old.", "ipa": "/ˈbɪli ɪz sɪks jɪərz oʊld/", "vi": "Billy lên sáu tuổi." },
      { "start": 7.5, "en": "He visits his uncle and aunt every summer. They live on a farm.", "ipa": "/hiː ˈvɪzɪts hɪz ˈʌŋkl ænd ænt ˈɛvri ˈsʌmər. ðeɪ lɪv ɒn ə fɑːrm/", "vi": "Cậu bé đến thăm bác và dì vào mỗi dịp hè. Họ sống ở một trang trại." },
      { "start": 15.0, "en": "They have cows, chickens, sheep, and a big horse on the farm. Billy loves all the animals.", "ipa": "/ðeɪ hæv kaʊz, ˈtʃɪkɪnz, ʃiːp, ænd ə bɪɡ hɔːrs ɒn ðə fɑːrm. ˈbɪli lʌvz ɔːl ði ˈænɪmlz/", "vi": "Ở trang trại có nuôi bò, gà, cừu và một con ngựa lớn. Billy yêu thích tất cả các loài động vật." },
      { "start": 26.0, "en": "This summer, he is going to learn how to milk a cow. Wow! His friends cannot believe it.", "ipa": "/ðɪs ˈsʌmər, hiː ɪz ˈɡoʊɪŋ tuː lɜːrn haʊ tuː mɪlk ə kaʊ. waʊ! hɪz frɛndz ˈkænɒt bɪˈliːv ɪt/", "vi": "Mùa hè này, cậu sẽ học cách vắt sữa bò. Chà! Các bạn của cậu không thể tin nổi điều đó." },
      { "start": 35.0, "en": "'We get our milk from the store,' they say. 'But our friend is going to get it from a cow.'", "ipa": "/wiː ɡɛt ˈaʊər mɪlk frɒm ðə stɔːr, ðeɪ seɪ. bʌt ˈaʊər frɛnd ɪz ˈɡoʊɪŋ tuː ɡɛt ɪt frɒm ə kaʊ/", "vi": "'Chúng tôi mua sữa ở cửa hàng,' họ nói. 'Nhưng bạn của chúng ta lại đi lấy sữa trực tiếp từ con bò.'" },
      { "start": 44.0, "en": "Billy laughs. 'Milk does not come from the store,' he says. 'Milk comes from a cow.'", "ipa": "/ˈbɪli lɑːfs. mɪlk dʌz nɒt kʌm frɒm ðə stɔːr, hiː sɛz. mɪlk kʌmz frɒm ə kaʊ/", "vi": "Billy cười lớn. 'Sữa đâu phải có sẵn ở cửa hàng,' cậu nói. 'Sữa xuất phát từ con bò.'" },
      { "start": 53.0, "en": "His friends do not believe him. But his teacher says, 'Yes, milk comes from cows. Cows eat grass. They change the grass into milk. The farmer sells the milk. And we buy it in the stores.'", "ipa": "/hɪz frɛndz duː nɒt bɪˈliːv hɪm. bʌt hɪz ˈtiːtʃər sɛz, jɛs, mɪlk kʌmz frɒm kaʊz. kaʊz iːt ɡræs. ðeɪ tʃeɪndʒ ðə ɡræs ˈɪntuː mɪlk. ðə ˈfɑːrmər sɛlz ðə mɪlk. ænd wiː baɪ ɪt ɪn ðə stɔːrz/", "vi": "Các bạn không tin cậu. Nhưng cô giáo bảo: 'Đúng vậy, sữa đến từ bò. Bò ăn cỏ và chuyển hóa cỏ thành sữa. Người nông dân bán sữa đó, rồi chúng ta mua lại ở các cửa hàng.'" },
      { "start": 70.0, "en": "The teacher tells them one more thing. 'Did you know that cows have four stomachs?' The kids are surprised. But it's true!", "ipa": "/ðə ˈtiːtʃər tɛlz ðɛm wʌn mɔːr θɪŋ. dɪd juː noʊ ðæt kaʊz hæv fɔːr ˈstʌməks? ðə kɪdz ɑːr sərˈpraɪzd. bʌt ɪts truː/", "vi": "Cô giáo còn kể thêm một điều nữa: 'Các em có biết bò có tới bốn cái dạ dày không?' Lũ trẻ vô cùng ngạc nhiên, nhưng đó là sự thật!" }
    ]
  },
  {
    "day": 2,
    "title": "Grandma's Moving Day",
    "image": "01 January/images/day_02.webp",
    "audio": "01 January/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "The day had come. Grandma was moving out of her big house. I was sad. I had a lot of memories in that house.", "ipa": "/ðə deɪ hæd kʌm. ˈɡrænmɑː wɒz ˈmuːvɪŋ aʊt əv hɜːr bɪɡ haʊs. aɪ wɒz sæd. aɪ hæd a lɒt əv ˈmɛməriz ɪn ðæt haʊs/", "vi": "Ngày đó cuối cùng cũng đến. Bà ngoại chuẩn bị chuyển đi khỏi ngôi nhà lớn của mình. Tôi cảm thấy buồn vì có quá nhiều kỷ niệm gắn bó ở nơi đó." },
      { "start": 16.0, "en": "I asked where Grandma was moving to. My dad just said, 'Somewhere nearby. Don't worry.'", "ipa": "/aɪ ɑːskt wɛr ˈɡrænmɑː wɒz ˈmuːvɪŋ tuː. maɪ dæd dʒʌst sɛd, ˈsʌmˌwɛr ˈnɪrbaɪ. doʊnt ˈwʌri/", "vi": "Tôi hỏi xem bà chuyển đi đâu. Bố chỉ đáp: 'Đâu đó gần đây thôi. Con đừng lo.'" },
      { "start": 26.0, "en": "But I was worried. I spent a lot of time with Grandma. I did not want to see her any less. In fact, I wanted to see her more.", "ipa": "/bʌt aɪ wɒz ˈwʌrid. aɪ spɛnt ə lɒt əv taɪm wɪð ˈɡrænmɑː. aɪ dɪd nɒt wɒnt tuː siː hɜːr ˈɛni lɛs. ɪn fɑːkt, aɪ ˈwɒntɪd tuː siː hɜːr mɔːr/", "vi": "Nhưng tôi vẫn thấy lo lắng. Tôi dành rất nhiều thời gian bên bà và không muốn gặp bà ít đi chút nào, thậm chí còn muốn gặp nhiều hơn." },
      { "start": 39.0, "en": "I could tell that no one wanted to tell me because they knew I would be sad. 'It must be far away,' I thought to myself.", "ipa": "/aɪ kʊd tɛl ðæt ˈnoʊwʌn ˈwɒntɪd tuː tɛl miː bɪˈkəz ðeɪ nuː aɪ wʊd biː sæd. ɪt mʌst biː fɑːr əˈweɪ, aɪ θɔːt tuː maɪˈsɛlf/", "vi": "Tôi nhận ra không ai dám nói thật vì sợ tôi buồn. 'Chắc là phải ở xa lắm đây,' tôi tự thầm nghĩ." },
      { "start": 51.0, "en": "We got all of Grandma's things in the truck. I sat beside her in the car. We talked the whole time.", "ipa": "/wiː ɡɒt ɔːl əv ˈɡrænmɑːz θɪŋz ɪn ðə trʌk. aɪ sæt bɪˈsaɪd hɜːr ɪn ðə kɑːr. wiː tɔːkt ðə hoʊl taɪm/", "vi": "Chúng tôi chuyển toàn bộ đồ đạc của bà lên xe tải. Tôi ngồi cạnh bà trên ô tô và trò chuyện suốt cả chặng đường." },
      { "start": 62.0, "en": "After a while, the truck stopped. I looked out to see her new home. It was our house! Grandma was coming to live with us.", "ipa": "/ˈɑːftər ə waɪl, ðə trʌk stɒpt. aɪ lʊkt aʊt tuː siː hɜːr nuː hoʊm. ɪt wɒz ˈaʊər haʊs! ˈɡrænmɑː wɒz ˈkʌmɪŋ tuː lɪv wɪð ʌs/", "vi": "Một lúc sau, chiếc xe tải dừng lại. Tôi ngó ra ngoài để xem ngôi nhà mới của bà. Hóa ra đó chính là nhà của chúng tôi! Bà ngoại dọn đến sống chung một nhà với gia đình tôi." }
    ]
  },
  {
    "day": 3,
    "title": "A Little Artist",
    "image": "01 January/images/day_03.webp",
    "audio": "01 January/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Irene is only three years old. But to her parents, she is already a little artist.", "ipa": "/aɪˈriːn ɪz ˈoʊnli θriː jɪərz oʊld. bʌt tuː hɜːr ˈpɛrənts, ʃiː ɪz ɔːlˈrɛdi ə ˈlɪtl ˈɑːrtɪst/", "vi": "Irene mới tròn ba tuổi. Nhưng đối với bố mẹ, con bé đã sớm là một họa sĩ nhí." },
      { "start": 13.0, "en": "At their home, her paintings cover the walls of all the rooms—even the bathroom.", "ipa": "/æt ðɛr hoʊm, hɜːr ˈpeɪntɪŋz ˈkʌvər ðə wɔːlz əv ɔːl ðə ruːmz—ˈiːvn ðə ˈbɑːθruːm/", vi: "Ở nhà họ, các bức tranh của bé phủ kín tường khắp các phòng—thậm chí cả phòng tắm." },
      { "start": 21.0, "en": "'A child's creativity is beyond your imagination,' her mom always says. 'And she can be highly productive too.'", "ipa": "/ə tʃaɪldz ˌkriːeɪˈtɪvɪti ɪz bɪˈjɒnd jɔːr ɪˌmædʒɪˈneɪʃn, hɜːr mɒm ˈɔːlweɪz sɛz. ænd ʃiː kæn biː ˈhaɪli prəˈdʌktɪv tuː/", vi: "'Sự sáng tạo của trẻ nhỏ vượt ngoài sức tưởng tượng của bạn,' mẹ bé luôn tự hào nói. 'Và con bé cũng cực kỳ năng suất nữa.'" },
      { "start": 33.0, "en": "One time, her mother counted all of Irene's drawings. Irene had used nearly 500 sheets of paper in just one month!", "ipa": "/wʌn taɪm, hɜːr ˈmʌðər ˈkaʊntɪd ɔːl əv aɪˈriːnz ˈdrɔːɪŋz. aɪˈriːn hæd juːzd ˈnɪərli fʌɪv ˈhʌndrəd ʃiːts əv ˈpeɪpər ɪn dʒʌst wʌn mʌnθ/", vi: "Có lần, mẹ đã đếm tất cả số tranh vẽ của Irene. Chỉ trong vòng một tháng mà bé đã dùng gần 500 tờ giấy vẽ!" },
      { "start": 46.0, "en": "Most of her drawings are of animals: birds, rabbits, turtles, and even raccoons. All the animals in her paintings are in groups of three—a father, a mother, and a baby.", "ipa": "/moʊst əv hɜːr ˈdrɔːɪŋz ɑːr əv ˈænɪmlz: bɜːrdz, ˈræbɪts, ˈtɜːrtlz, ænd ˈiːvn ræˈkuːnz. ɔːl ði ˈænɪmlz ɪn hɜːr ˈpeɪntɪŋz ɑːr ɪn ɡruːps əv θriː—ə ˈfɑːðər, ə ˈmʌðər, ænd ə ˈbeɪbi/", vi: "Phần lớn các bức vẽ của bé là về động vật: chim, thỏ, rùa và cả gấu mèo. Tất cả các loài vật trong tranh đều đi theo nhóm ba con—gồm bố, mẹ và em bé." },
      { "start": 61.0, "en": "That's how it is in little Irene's world.", "ipa": "/ðæts haʊ ɪt ɪz ɪn ˈlɪtl aɪˈriːnz wɜːrld/", vi: "Thế giới trong tâm hồn cô bé Irene nhỏ nhắn là như vậy đấy." }
    ]
  },
  {
    "day": 4,
    "title": "Snow or Not",
    image: "01 January/images/day_04.webp",
    audio: "01 January/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "When I was young, my family always seemed short of food. We were poor. My brothers and sisters and I were hungry all of the time.", "ipa": "/wɛn aɪ wɒz jʌŋ, maɪ ˈfæməli ˈɔːlweɪz siːmd ʃɔːrt əv fuːd. wiː wɜːr pʊr. maɪ ˈbrʌðərz ænd ˈsɪstərz ænd aɪ wɜːr ˈhʌŋɡri ɔːl əv ðə taɪm/", vi: "Khi tôi còn nhỏ, gia đình tôi lúc nào cũng thiếu thốn cái ăn. Chúng tôi rất nghèo. Các anh chị em và tôi lúc nào cũng trong tình trạng đói cồn cào." },
      { "start": 17.0, "en": "We didn't have much flour. And sugar was rare. You know, with flour and sugar, our mom could make delicious treats. Flour and sugar were signs of wealth to us.", "ipa": "/wiː ˈdɪdnt hæv mʌtʃ ˈflaʊər. ænd ˈʃʊɡər wɒz rɛr. juː noʊ, wɪð ˈflaʊər ænd ˈʃʊɡər, ˈaʊər mɒm kʊd meɪk dɪˈlɪʃəs triːts. ˈflaʊər ænd ˈʃʊɡər wɜːr saɪnz əv wɛlθ tuː ʌs/", vi: "Nhà chúng tôi chẳng có mấy bột mì, đường cát lại càng hiếm hoi. Bạn biết đấy, chỉ với bột và đường, mẹ có thể làm ra những món quà vặt ngon lành. Đối với chúng tôi khi ấy, bột mì và đường chính là biểu tượng của sự giàu có." },
      { "start": 33.0, "en": "When it snowed in winter, I always wondered, 'Why doesn't it snow flour?' 'Or sugar,' my young brother would correct me.", "ipa": "/wɛn ɪt snoʊd ɪn ˈwɪntər, aɪ ˈɔːlweɪz ˈwʌndərd, 'waɪ ˈdɪznt ɪt snoʊ ˈflaʊər?' 'ɔːr ˈʃʊɡər,' maɪ jʌŋ ˈbrʌðər wʊd kəˈrɛkt miː/", vi: "Mỗi khi mùa đông đến và tuyết rơi, tôi lại thắc mắc: 'Tại sao trời không đổ tuyết bằng bột mì nhỉ?' 'Hoặc bằng đường chứ,' em trai tôi nhanh nhẩu sửa lại." },
      { "start": 47.0, "en": "We imagined how happy we would be if it snowed flour and sugar—precious white flour and sugar!", "ipa": "/wiː ɪˈmædʒɪnd haʊ ˈhæpi wiː wʊd biː ɪf ɪt snoʊd ˈflaʊər ænd ˈʃʊɡər—ˈprɛʃəs waɪt ˈflaʊər ænd ˈʃʊɡər/", vi: "Chúng tôi từng mơ mộng sẽ hạnh phúc biết bao nếu trời đổ mưa bột mì và đường — những thứ bột và đường trắng tinh quý giá!" },
      { "start": 57.0, "en": "When we grew up, we laughed about how silly we were. If it snowed flour and sugar, there would be big problems in the world. We would not be able to survive very long!", "ipa": "/wɛn wiː ɡruː ʌp, wiː lɑːft əˈbaʊt haʊ ˈsɪli wiː wɜːr. ɪf ɪt snoʊd ˈflaʊər ænd ˈʃʊɡər, ðɛr wʊd biː bɪɡ ˈprɒbləmz ɪn ðə wɜːrld. wiː wʊd nɒt biː ˈeɪbl tuː sərˈvaɪv ˈvɛri lɒŋ/", vi: "Lớn lên rồi, nghĩ lại chuyện đó chúng tôi chỉ biết cười xòa vì sự ngây ngô ngày xưa. Giả sử trời đổ tuyết bằng bột mì và đường thật, thế giới chắc chắn sẽ lâm vào khủng hoảng lớn và con người chẳng thể tồn tại nổi lâu đâu!" }
    ]
  },
  {
    "day": 5,
    "title": "Do Fish Breathe Water?",
    image: "01 January/images/day_05.webp",
    audio: "01 January/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Joey has a pet. Her name is Goldie. She lives in a bowl. Goldie is a fish—a shiny goldfish.", "ipa": "/ˈdʒoʊi hæz ə pɛt. hɜːr neɪm ɪz ˈɡoʊldi. ʃiː lɪvz ɪn ə boʊl. ˈɡoʊldi ɪz a fɪʃ—ə ˈʃaɪni ˈɡoʊldˌfɪʃ/", vi: "Joey nuôi một con vật cưng tên là Goldie sống trong bể kính. Goldie là một chú cá—một chú cá vàng lấp lánh." },
      { "start": 16.0, "en": "Once a week, Joey takes Goldie out of her bowl. He cleans her bowl so she can grow strong and healthy.", "ipa": "/wʌns ə wiːk, ˈdʒoʊi teɪks ˈɡoʊldi aʊt əv hɜːr boʊl. hiː kliːnz hɜːr boʊl soʊ ʃiː kæn ɡroʊ strɒŋ ænd ˈhɛlθi/", vi: "Mỗi tuần một lần, Joey lại cẩn thận bắt Goldie ra ngoài để cọ rửa bể sạch sẽ giúp cá lớn nhanh và khỏe mạnh." },
      { "start": 26.0, "en": "When Joey's parents gave him Goldie, they said, 'You will have to learn to take care of her.' So, Joey started learning a lot about fish.", "ipa": "/wɛn ˈdʒoʊiz ˈpɛərənts ɡeɪv hɪm ˈɡoʊldi, ðeɪ sɛd, 'juː wɪl hæv tuː lɜːrn tuː teɪk kɛər əv hɜːr.' soʊ, ˈdʒoʊi ˈstɑːrtɪd ˈlɜːrnɪŋ ə lɒt əv fɪʃ/", vi: "Lúc bố mẹ tặng Goldie cho Joey, họ dặn: 'Con sẽ phải học cách chăm sóc cho cá đấy.' Thế là Joey bắt đầu tìm hiểu rất nhiều kiến thức về loài cá." },
      { "start": 39.0, "en": "Joey used to think fish did not breathe. 'How can they breathe in the water?' he thought. 'When I swim, I cannot breathe if I put my head under the water!'", "ipa": "/ˈdʒoʊi juːzd tuː θɪŋk fɪʃ dɪd nɒt briːð. 'haʊ kæn ðeɪ briːð ɪn ðə ˈwɔːtər?' hiː θɔːt. 'wɛn aɪ swɪm, aɪ ˈkænɒt briːð ɪf aɪ pʊt maɪ hɛd ˈʌndər ðə ˈwɔːtər!'/", vi: "Trước kia Joey từng nghĩ loài cá không hề biết thở. 'Sao chúng có thể thở dưới nước được nhỉ?' cậu tự hỏi. 'Mình đi bơi mà cứ ngụp đầu xuống nước là sặc không thở nổi cơ mà!'" },
      { "start": 53.0, "en": "But fish get air in a different way. They have 'gills' on the sides of their heads.", "ipa": "/bʌt fɪʃ ɡɛt ɛər ɪn ə ˈdɪfrənt weɪ. ðeɪ hæv 'ɡɪlz' ɒn ðə saɪdz əv ðɛər hɛdz/", vi: "Nhưng loài cá hấp thụ không khí bằng một cách hoàn toàn khác. Chúng có hệ thống 'mang' nằm ở hai bên đầu." },
      { "start": 62.0, "en": "Joey learned that water has oxygen in it. The water passes through the gills. The fish get their oxygen from the water.", "ipa": "/ˈdʒoʊi lɜːrnd ðæt ˈwɔːtər hæz ˈɑːksɪdʒən ɪn ɪt. ðə ˈwɔːtər ˈpæsɪz θruː ðə ɡɪlz. ðə fɪʃ ɡɛt ðɛər ˈɑːksɪdʒən frɒm ðə ˈwɔːtər/", vi: "Joey học được rằng trong nước có chứa oxy. Dòng nước chảy qua mang, và cá hấp thụ lượng oxy hòa tan đó để thở." },
      { "start": 74.0, "en": "When Joey cleans the fish bowl, he puts Goldie in a small glass of water. That way, she can breathe while he cleans her home.", "ipa": "/wɛn ˈdʒoʊi kliːnz ðə fɪʃ boʊl, hiː pʊts ˈɡoʊldi ɪn ə smɔːl ɡlæs əv ˈwɔːtər. ðæt weɪ, ʃiː kæn briːð waɪl hiː kliːnz hɜːr hoʊm/", vi: "Mỗi khi dọn bể, Joey lại thả Goldie vào một cốc nước nhỏ. Nhờ thế mà chú cá vẫn thở bình thường trong lúc cậu dọn dẹp nhà mới cho nó." }
    ]
  },
  {
    "day": 6,
    "title": "Where Is My Pen?",
    image: "01 January/images/day_06.webp",
    audio: "01 January/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "Amy is not happy. She cannot find her favourite pen!", "ipa": "/ˈeɪmi ɪz nɒt ˈhæpi. ʃiː ˈkænɒt faɪnd hɜːr ˈfeɪvərɪt pɛn/", vi: "Amy đang rất buồn bực vì không tìm thấy chiếc bút yêu thích của mình!" },
      { "start": 10.0, "en": "She looks all over the house. She looks under the bed. She looks in her desk. She looks in the kitchen and in her book bag. But she cannot find it.", "ipa": "/ʃiː lʊks ɔːl ˈoʊvər ðə haʊs. ʃiː lʊks ˈʌndər ðə bɛd. ʃiː lʊks ɪn hɜːr dɛsk. ʃiː lʊks ɪn ðə ˈkɪtʃɪn ænd ɪn hɜːr bʊk bæɡ. bʌt ʃiː ˈkænɒt faɪnd ɪt/", vi: "Cô bé tìm kiếm khắp mọi ngóc ngách trong nhà: tìm dưới gầm giường, lục trong bàn học, tìm ở phòng bếp và cả trong cặp sách nhưng vẫn bặt vô âm tín." },
      { "start": 23.0, "en": "Amy is really upset. Amy wants to cry. She cries to her mother, 'Mom, my pen is lost!'", "ipa": "/ˈeɪmi ɪz ˈrɪəli ʌpˈsɛt. ˈeɪmi wɒnts tuː kraɪ. ʃiː kraɪz tuː hɜːr ˈmʌðər, 'mɒm, maɪ pɛn ɪz lɒst!'/", vi: "Amy thực sự quẫn trí và muốn òa khóc. Cô bé mếu máo chạy lại mét mẹ: 'Mẹ ơi, con bị mất bút rồi!'" },
      { "start": 33.0, "en": "Mom says, 'Don't cry. I will help you look for it.' When Mom goes downstairs, she laughs.", "ipa": "/mɒm sɛz, 'doʊnt kraɪ. aɪ wɪl hɛlp juː lʊk fɔːr ɪt.' wɛn mɒm ɡoʊz ˈdaʊnˌstɛərz, ʃiː lɑːfs/", vi: "Mẹ dỗ dành: 'Đừng khóc con. Mẹ sẽ giúp con tìm.' Khi mẹ bước xuống lầu, bà bỗng bật cười khúc khích." },
      { "start": 43.0, "en": "'Why are you laughing, Mom?' Mom says, 'Check behind your ear.' And as Amy checks her ear, she finds her pen. She had put it there earlier. Now she is happy.", "ipa": "/'waɪ ɑːr juː ˈlɑːfɪŋ, mɒm?' mɒm sɛz, 'tʃɛk bɪˈhaɪnd jɔːr ɪər.' ænd æz ˈeɪmi tʃɛks hɜːr ɪər, ʃiː faɪndz hɜːr pɛn. ʃiː hæd pʊt ɪt ðɛər ˈɜːrliər. naʊ ʃiː ɪz ˈhæpi/", vi: "'Mẹ cười gì thế ạ?' Mẹ bảo: 'Con sờ thử sau tai xem nào.' Khi Amy đưa tay kiểm tra, cô bé ngớ người thấy chiếc bút giắt ngay ở đó từ lúc nào. Hóa ra chính cô bé đã nhét nó vào đó trước đó. Giờ thì cô bé đã vui vẻ trở lại." }
    ]
  },
  {
    "day": 7,
    "title": "When the Earth Shakes",
    image: "01 January/images/day_07.webp",
    audio: "01 January/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was a day Tony would never forget. He was playing with his friends in the yard. All of a sudden, there was a strange noise. Then, everything started to shake.", "ipa": "/ɪt wɒz a deɪ ˈtoʊni wʊd ˈnɛvər fərˈɡɛt. hiː wɒz ˈpleɪɪŋ wɪð hɪz frɛndz ɪn ðə jɑːrd. ɔːl əv ə ˈsʌdn, ðɛr wɒz a streɪndʒ nɔɪz. ðɛn, ˈɛvriˌθɪŋ ˈstɑːrtɪd tuː ʃeɪk/", vi: "Đó là ngày mà Tony không bao giờ có thể quên trong đời. Cậu đang cùng các bạn chơi đùa trong sân thì đột nhiên một tiếng động lạ vang lên, rồi vạn vật bắt đầu rung chuyển dữ dội." },
      { "start": 18.0, "en": "Tony saw that his house was moving. Dogs were barking. Chickens were running around in fear. A horse was standing upright on its back legs. What was it? Tony had no idea.", "ipa": "/ˈtoʊni sɔː ðæt hɪz haʊs wɒz ˈmuːvɪŋ. dɒɡz wɜːr ˈbɑːrkɪŋ. ˈtʃɪkɪnz wɜːr ˈrʌnɪŋ əˈraʊnd ɪn fɪər. ə hɔːrs wɒz ˈstændɪŋ ˈʌpˌraɪt ɒn ɪts bæk lɛɡz. wɒt wɒz ɪt? ˈtoʊni hæd noʊ aɪˈdɪə/", vi: "Tony chứng kiến ngôi nhà của mình như đang dịch chuyển. Chó sủa vang trời, gà chạy toán loạn vì hoảng sợ, và một con ngựa chồm hẳn hai chân sau lên. Chuyện gì đang xảy ra thế này? Tony hoàn toàn mù tịt." },
      { "start": 34.0, "en": "Some of kids fell down and others were trying to keep from falling. A woman ran outside and shouted, 'Hurry! It's an earthquake. Get away from the building!'", "ipa": "/sʌm əv kɪdz fɛl daʊn ænd ˈʌðərz wɜːr ˈtraɪɪŋ tuː kiːp frɒm ˈfɔːlɪŋ. ə ˈwʊmən ræn ˈaʊtˌsaɪd ænd ˈʃaʊtɪd, 'ˈhɜːri! ɪts ən ˈɜːrθˌkweɪk. ɡɛt əˈweɪ frɒm ðə ˈbɪldɪŋ!'/", vi: "Vài đứa trẻ ngã nhào xuống đất trong khi số khác cố gắng bám trụ để không bị ngã. Một phụ nữ hớt hải chạy ra ngoài và hét lớn: 'Nhanh lên! Động đất rồi. Tránh xa các tòa nhà ra!'" },
      { "start": 48.0, "en": "Tony was so scared that he couldn't move. The woman grabbed him and led him away from the building. It was his first earthquake.", "ipa": "/ˈtoʊni wɒz soʊ skɛrd ðæt hiː ˈkʊdnt muːv. ðə ˈwʊmən ɡræbd hɪm ænd lɛd hɪm əˈweɪ frɒm ðə ˈbɪldɪŋ. ɪt wɒz hɪz fɜːrst ˈɜːrθˌkweɪk/", vi: "Tony sợ chết trân đến mức chân tay cứng đờ không bước nổi. Người phụ nữ liền kéo tay cậu đưa đến nơi an toàn. Đó là trận động đất đầu tiên trong đời cậu." },
      { "start": 59.0, "en": "Tony was shocked to learn that the ground he stood on every day could shake! And that shaking could hurt a lot of people.", "ipa": "/ˈtoʊni wɒz ʃɒkt tuː lɜːrn ðæt ðə ɡraʊnd hiː stʊd ɒn ˈɛvri deɪ kʊd ʃeɪk! ænd ðæt ˈʃeɪkɪŋ kʊd hɜːrt ə lɒt əv ˈpiːpl/", vi: "Tony bàng hoàng nhận ra mặt đất tưởng chừng vững chãi dưới chân mình hằng ngày lại có thể rung chuyển dữ dội đến thế, và sức mạnh tàn phá của nó có thể làm tổn thương vô số người." }
    ]
  },
  {
    "day": 8,
    "title": "Just the Way You Are",
    image: "01 January/images/day_08.webp",
    audio: "01 January/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "Sometimes, it is fun being tall. Sometimes, it is not. Sure, I can always reach things for my mom, dad, sister or teacher. But sometimes, I would rather be short.", "ipa": "/ˈsʌmˌtaɪmz, ɪt ɪz fʌn ˈbiːɪŋ tɔːl. ˈsʌmˌtaɪmz, ɪt ɪz nɒt. ʃʊr, aɪ kæn ˈɔːlweɪz riːtʃ θɪŋz fɔːr maɪ mɒm, dæd, ˈsɪstər ɔːr ˈtiːtʃər. bʌt ˈsʌmˌtaɪmz, aɪ wʊd ˈrɑːðər biː ʃɔːrt/", vi: "Đôi khi cao ráo cũng mang lại nhiều niềm vui, nhưng đôi khi lại phiền toái. Tất nhiên, tôi luôn dễ dàng lấy giúp đồ vật trên cao cho bố mẹ, cô giáo hay em gái. Nhưng có những lúc, tôi chỉ ước mình lùn đi một chút." },
      { "start": 18.0, "en": "I am always the tallest one in pictures! Sometimes, I wish people didn't notice me as much.", "ipa": "/aɪ æm ˈɔːlweɪz ðə ˈtɔːlɪst wʌn ɪn ˈpɪktʃərz! ˈsʌmˌtaɪmz, aɪ wɪʃ ˈpiːpl ˈdɪdnt ˈnoʊtɪs miː æz mʌtʃ/", vi: "Trong mọi bức ảnh chụp chung, tôi luôn là người cao nổi bật nhất! Thỉnh thoảng, tôi chỉ mong mọi người đừng quá chú ý đến mình." },
      { "start": 26.0, "en": "Another boy, John, is the shortest kid in our class. He told me that he wished people didn't notice him as much either!", "ipa": "/əˈnʌðər bɔɪ, dʒɒn, ɪz ðə ˈʃɔːrtɪst kɪd ɪn ˈaʊər klæs. hiː toʊld miː ðæt hiː wɪʃt ˈpiːpl ˈdɪdnt ˈnoʊtɪs hɪm æz mʌtʃ ˈiːðər/", vi: "Ngược lại, John — cậu bạn thấp nhất lớp — lại tâm sự rằng cậu ấy cũng ước mọi người đừng chú ý đến chiều cao khiêm tốn của mình!" },
      { "start": 36.0, "en": "We became friends because we feel the same, in a strange way. When we play basketball together, people say, 'It's a lot fun to watch a game with the school's tallest and shortest boys on the same team.'", "ipa": "/wiː bɪˈkeɪm frɛndz bɪˈkəz wiː fiːl ðə seɪm, ɪn ə streɪndʒ weɪ. wɛn wiː pleɪ ˈbæskɪtˌbɔːl təˈɡɛðər, ˈpiːpl seɪ, 'ɪts ə lɒt fʌn tuː wɒtʃ ə ɡeɪm wɪð ðə skuːlz ˈtɔːlɪst ænd ˈʃɔːrtɪst bɔɪz ɒn ðə seɪm tiːm.'/", vi: "Chúng tôi trở thành bạn thân từ đó bởi sự đồng cảm kỳ lạ này. Mỗi khi hai đứa cùng chơi bóng rổ, mọi người thường cười thích thú: 'Xem hai cậu bạn cao nhất và lùn nhất trường tề tựu trong cùng một đội bóng mới thú vị làm sao.'" },
      { "start": 52.0, "en": "It's true, you know. You can't be too tall or too short. It's just the way you are.", "ipa": "/ɪts truː, juː noʊ. juː kænt biː tuː tɔːl ɔːr tuː ʃɔːrt. ɪts dʒʌst ðə weɪ juː ɑːr/", vi: "Quả thực là như vậy đấy. Bạn chẳng thể chọn cao quá hay lùn quá được. Đơn giản đó chính là bản ngã độc nhất của bạn." }
    ]
  },
  {
    "day": 9,
    "title": "My Mother's Chair",
    image: "01 January/images/day_09.webp",
    audio: "01 January/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "My mother has a favourite chair. She got it from her mother. This chair is very old. It is the only one of its kind because my grandfather made it.", "ipa": "/maɪ ˈmʌðər hæz ə ˈfeɪvərɪt tʃɛər. ʃiː ɡɒt ɪt frɒm hɜːr ˈmʌðər. ðɪs tʃɛər ɪz ˈvɛri oʊld. ɪt ɪz ði ˈoʊnli wʌn əv ɪts kaɪnd bɪˈkəz maɪ ˈɡrændˌfɑːðər meɪd ɪt/", vi: "Mẹ tôi có một chiếc ghế bành ưa thích được thừa hưởng từ bà ngoại. Chiếc ghế đã rất cổ kính và là món đồ độc nhất vô nhị vì chính tay ông ngoại đã tự đóng nó." },
      { "start": 18.0, "en": "One day, my brother pushed me when we were running through the house. I started to slip and ran right into the chair. One of the legs came off!", "ipa": "/wʌn deɪ, maɪ ˈbrʌðər pʊʃt miː wɛn wiː wɜːr ˈrʌnɪŋ θruː ðə haʊs. aɪ ˈstɑːrtɪd tuː slɪp ænd ræn raɪt ˈɪntuː ðə tʃɛər. wʌn əv ðə lɛɡz keɪm ɒf/", vi: "Một hôm, trong lúc đùa giỡn rượt đuổi nhau trong nhà, anh trai vô tình xô tôi ngã. Tôi trượt chân đâm thẳng vào chiếc ghế khiến một chân ghế bị gãy sập ra!" },
      { "start": 30.0, "en": "We were shocked. We could not speak. I called my dad at work. He came home and glued it together. He put a clamp on it to hold it in place while the glue dried.", "ipa": "/wiː wɜːr ʃɒkt. wiː kʊd nɒt spiːk. aɪ kɔːld maɪ dæd ænd wɜːrk. hiː keɪm hoʊm ænd ɡluːd ɪt təˈɡɛðər. hiː pʊt ə klæmp ɒn ɪt tuː hoʊld ɪt ɪn pleɪs waɪl ðə ɡluː draɪd/", vi: "Chúng tôi chết lặng và chẳng nói nên lời. Tôi vội gọi điện cho bố đang làm việc ở cơ quan. Bố tức tốc phóng xe về nhà, dùng keo dán chặt chân ghế lại và kẹp cố định bằng ê-tô chờ keo khô." },
      { "start": 44.0, "en": "My mom came home. We hoped she wouldn't notice, but she saw the clamp on the chair. We told her what had happened. She was very upset. Luckily, the chair was fixed.", "ipa": "/maɪ mɒm keɪm hoʊm. wiː hoʊpt ʃiː ˈwʊdnt ˈnoʊtɪs, bʌt ʃiː sɔː ðə klæmp ɒn ðə tʃɛər. wiː toʊld hɜːr wɒt hæd ˈhæpənd. ʃiː wɒz ˈvɛri ʌpˈsɛt. ˈlʌkɪli, ðə tʃɛər wɒz fɪkst/", vi: "Khi mẹ đi làm về, chúng tôi thầm cầu mong mẹ không để ý, nhưng mẹ vẫn phát hiện ra chiếc kẹp trên ghế. Chúng tôi đành thú nhận mọi chuyện. Mẹ vô cùng giận dữ và đau lòng. May sao chiếc ghế đã được cứu chữa lành lặn." },
      { "start": 58.0, "en": "Even though that old chair is much stronger now, we are not allowed to run in the house anymore!", "ipa": "/ˈiːvn ðoʊ ðæt oʊld tʃɛər ɪz mʌtʃ ˈstrɒŋɡər naʊ, wiː ɑːr nɒt əˈlaʊd tuː rʌn ɪn ðə haʊs ˈɛniˌmɔːr/", vi: "Mặc dù chiếc ghế cổ giờ đây đã được gia cố chắc chắn hơn trước, nhưng từ đó về sau chúng tôi bị cấm tuyệt đối không được chạy nhảy trong nhà nữa!" }
    ]
  },
  {
    "day": 10,
    "title": "Where Is Danny?",
    image: "01 January/images/day_10.webp",
    audio: "01 January/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "Danny is hiding from his friends today. Usually, Danny and his friends, Jenny and Eddy, play on the playground after school. But not today.", "ipa": "/ˈdæni ɪz ˈhaɪdɪŋ frɒm hɪz frɛndz təˈdeɪ. ˈjuːʒuəli, ˈdæni ænd hɪz frɛndz, ˈdʒɛni ænd ˈɛdi, pleɪ ɒn ðə ˈpleɪɡraʊnd ˈɑːftər skuːl. bʌt nɒt təˈdeɪ/", vi: "Hôm nay Danny đang chơi trốn tìm với các bạn. Thường thì sau giờ tan học, Danny cùng hai người bạn là Jenny và Eddy vẫn hay chơi đùa ở sân chơi, nhưng hôm nay thì khác." },
      { "start": 16.0, "en": "When classes ended, Jenny and Eddy came to meet Danny as usual. But he was not there. Where was he?", "ipa": "/wɛn ˈklæsɪz ˈɛndɪd, ˈdʒɛni ænd ˈɛdi keɪm tuː miːt ˈdæni æz ˈjuːʒuəl. bʌt hiː wɒz nɒt ðɛr. wɛr wɒz hiː/", vi: "Khi tiếng chuông tan học vang lên, Jenny và Eddy đến tìm Danny như mọi khi nhưng chẳng thấy cậu đâu. Cậu ấy đã đi đâu mất rồi nhỉ?" },
      { "start": 25.0, "en": "On Danny's desk, they found a piece of paper with some writing on it. They picked up the note and read it.", "ipa": "/ɒn ˈdæniz dɛsk, ðeɪ faʊnd ə piːs əv ˈpeɪpər wɪð sʌm ˈraɪtɪŋ ɒn ɪt. ðeɪ pɪkt ʌp ðə noʊt ænd rɛd ɪt/", vi: "Trên bàn học của Danny, họ tình cờ nhìn thấy một mảnh giấy có nguệch ngoạc mấy dòng chữ. Cả hai liền cầm mẩu giấy lên đọc." },
      { "start": 35.0, "en": "'Hello my friends. I'm going to a place where we have lunch every day. Find me there.'", "ipa": "/hɛˈloʊ maɪ frɛndz. aɪm ˈɡoʊɪŋ tuː ə pleɪs wɛr wiː hæv lʌntʃ ˈɛvri deɪ. faɪnd miː ðɛr/", vi: "'Xin chào các bạn của tôi. Tớ đang có mặt ở một nơi mà chúng ta vẫn hay ăn trưa mỗi ngày đấy. Hãy tìm tớ ở đó nhé.'" },
      { "start": 43.0, "en": "Eddy scratched his head. 'Where is that?' he asked. 'It's the place where we eat,' said Jenny. 'It's the cafeteria!'", "ipa": "/ˈɛdi skrætʃt hɪz hɛd. 'wɛr ɪz ðæt?' hiː ɑːskt. 'ɪts ðə pleɪs wɛr wiː iːt,' sɛd ˈdʒɛni. 'ɪts ðə ˌkæfəˈtɪriə!'/", vi: "Eddy gãi đầu gãi tai thắc mắc: 'Đó là chỗ nào nhỉ?' 'Là nơi chúng ta ăn uống chứ đâu,' Jenny reo lên. 'Chính là phòng ăn tự phục vụ của trường chứ còn gì nữa!'" },
      { "start": 56.0, "en": "They ran to the school cafeteria. And yes, there he was! Danny was sweeping the floor, and a few other boys and girls were washing the tables, chairs, and counters!", "ipa": "/ðeɪ ræn tuː ðə skuːl ˌkæfəˈtɪriə. ænd jɛs, ðɛr hiː wɒz! ˈdæni wɒz ˈswiːpɪŋ ðə flɔːr, ænd ə fjuː ˈʌðər bɔɪz ænd ɡɜːrlz wɜːr ˈwɒʃɪŋ ðə ˈteɪblz, tʃɛərz, ænd ˈkaʊntərz/", vi: "Cả hai cắm cổ chạy thật nhanh đến nhà ăn trường. Quả nhiên Danny đang ở đó! Cậu đang lom khom quét dọn sàn nhà, trong khi vài bạn nam nữ sinh khác đang lau chùi bàn ghế và quầy kệ sạch bóng." },
      { "start": 69.0, "en": "Right away, they rolled up their sleeves and joined the cleaning with Danny.", "ipa": "/raɪt əˈweɪ, ðeɪ roʊld ʌp ðɛər sliːvz ænd dʒɔɪnd ðə ˈkliːnɪŋ wɪð ˈdæni/", vi: "Chẳng nói chẳng rằng, cả hai liền xắn tay áo lên và lao vào chung sức dọn dẹp cùng Danny." }
    ]
  },
  {
    "day": 11,
    "title": "Earth Day",
    image: "01 January/images/day_11.webp",
    audio: "01 January/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "The first Earth Day was on April 22, 1970. It was in the United States.", "ipa": "/ðə fɜːrst ɜːrθ deɪ wɒz ɒn ˈeɪprəl ˈtwɛnti-sɛkənd, ˈnaɪˈtiːn ˈsɛvnti. ɪt wɒz ɪn ðə jʊˈnaɪtɪd steɪts/", vi: "Ngày Trái Đất đầu tiên được tổ chức vào ngày 22 tháng 4 năm 1970 tại Hợp chủng quốc Hoa Kỳ." },
      { "start": 13.0, "en": "A man named Mr. Nelson started it. He wanted people to take care of the earth. People worked on cleaning the land, water and air. Some people picked up trash. Other people planted trees and flowers.", "ipa": "/ə mæn neɪmd ˈmɪstər ˈnɛlsən ˈstɑːrtɪd ɪt. hiː ˈwɒntɪd ˈpiːpl tuː teɪk kɛər əv ði ɜːrθ. ˈpiːpl wɜːrkt ɒn ˈkliːnɪŋ ðə lænd, ˈwɔːtər ænd ɛr. sʌm ˈpiːpl pɪkt ʌp træʃ. ˈʌðər ˈpiːpl ˈplɑːntɪd triːz ænd ˈflaʊərz/", vi: "Sự kiện này do ông Nelson khởi xướng với mong muốn kêu gọi mọi người chung tay bảo vệ hành tinh xanh. Khắp nơi, người dân cùng nhau làm sạch đất đai, nguồn nước và bầu không khí; người thì nhặt rác thải, kẻ thì trồng thêm cây xanh và hoa lá." },
      { "start": 29.0, "en": "The second Earth Day was on April 22, 1990. This time, people all over the world took part. Now we celebrate Earth Day every year on April 22.", "ipa": "/ðə ˈsɛkənd ɜːrθ deɪ wɒz ɒn ˈeɪprəl ˈtwɛnti-sɛkənd, ˈnaɪˈtiːn ˈnaɪnti. ðɪs taɪm, ˈpiːpl ɔːl ˈoʊvər ðə wɜːrld tʊk pɑːrt. naʊ wiː ˈsɛlɪbreɪt ɜːrθ deɪ ˈɛvri jɪər ɒn ˈeɪprəl ˈtwɛnti-sɛkənd/", vi: "Ngày Trái Đất lần thứ hai diễn ra vào ngày 22 tháng 4 năm 1990. Lần này, phong trào đã lan rộng và thu hút sự tham gia của toàn nhân loại trên khắp thế giới. Giờ đây, chúng ta kỷ niệm Ngày Trái Đất vào ngày 22 tháng 4 hằng năm." },
      { "start": 44.0, "en": "People in Australia clean beaches. People in Jordan and Canada plant trees. People in Russia plant gardens. People in Sweden visit farms. On one Earth Day, people in Japan made soap and postcards out of trash.", "ipa": "/ˈpiːpl ɪn ɔːˈstreɪliə kliːn ˈbiːtʃɪz. ˈpiːpl ɪn ˈdʒɔːrdn ænd ˈkænədə plɑːnt triːz. ˈpiːpl ɪn ˈrʌʃə plɑːnt ˈɡɑːrdnz. ˈpiːpl ɪn ˈswiːdən ˈvɪzɪt fɑːrmz. ɒn wʌn ɜːrθ deɪ, ˈpiːpl ɪn dʒəˈpæn meɪd soʊp ænd ˈpoʊstˌkɑːrdz aʊt əv træʃ/", vi: "Người dân ở Úc cùng nhau dọn sạch bãi biển; người ở Jordan và Canada hăng hái trồng cây; người Nga làm vườn; người Thụy Điển đến thăm các nông trại. Đặc biệt trong một Ngày Trái Đất, người Nhật đã tái chế rác thải thành xà phòng và bưu thiếp độc đáo." },
      { "start": 62.0, "en": "What will you do on Earth Day this year?", "ipa": "/wɒt wɪl juː duː ɒn ɜːrθ deɪ ðɪs jɪər?/", vi: "Thế còn bạn, bạn sẽ làm gì để góp phần bảo vệ Trái Đất vào năm nay?" }
    ]
  },
  {
    "day": 12,
    "title": "Needles Don't Hurt",
    image: "01 January/images/day_12.webp",
    audio: "01 January/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "Gena is scared. Today, she is going to see the doctor. She is going to get a needle.", "ipa": "/ˈdʒiːnə ɪz skɛrd. təˈdeɪ, ʃiː ɪz ˈɡoʊɪŋ tuː siː ðə ˈdɒktər. ʃiː ɪz ˈgʊɪŋ tuː ɡɛt a ˈniːdl/", vi: "Gena đang vô cùng sợ hãi. Hôm nay cô bé phải đến phòng khám bác sĩ để tiêm phòng." },
      { "start": 13.0, "en": "Gena does not like needles. 'It will hurt,' she cries. 'I don't want to get a needle.'", "ipa": "/ˈdʒiːnə dʌz nɒt laɪk ˈniːdlz. ɪt wɪl hɜːrt, ʃiː kraɪz. aɪ doʊnt wɒnt tuː ɡɛt a ˈniːdl/", vi: "Gena ghét tiêm vô cùng. 'Kim tiêm đau lắm,' cô bé khóc thét lên. 'Con nhất quyết không chịu tiêm đâu.'" },
      { "start": 21.0, "en": "Mom says, 'Getting a needle is good for you. It will help you stay healthy.'", "ipa": "/mɒm sɛz, ˈɡɛtɪŋ a ˈniːdl ɪz ɡʊd fɔːr juː. ɪt wɪl hɛlp juː steɪ ˈhɛlθi/", vi: "Mẹ ân cần dỗ dành: 'Tiêm phòng rất tốt cho con. Nó sẽ giúp cơ thể con luôn khỏe mạnh và kháng bệnh.'" },
      { "start": 28.5, "en": "The doctor is wearing a white coat. She has a nice smile. The doctor looks at Gena and says, 'Don't be afraid. The needle will not hurt. Everyone gets needles.'", "ipa": "/ðə ˈdɒktər ɪz ˈwɛərɪŋ a waɪt koʊt. ʃiː hæz a naɪs smaɪl. ðə ˈdɒktər lʊks æt ˈdʒiːnə ænd sɛz, doʊnt biː əˈfreɪd. ðə ˈniːdl wɪl nɒt hɜːrt. ˈɛvriˌwʌn ɡɛts ˈniːdlz/", vi: "Nữ bác sĩ mặc chiếc áo blouse trắng tinh và nở nụ cười hiền hậu. Cô nhìn Gena rồi trấn an: 'Don't be afraid. Mũi tiêm không đau chút nào đâu. Ai rồi cũng phải tiêm cả.'" },
      { "start": 43.0, "en": "Gena holds out her arm. She is still scared. 'Close your eyes and think of something funny,' says the doctor.", "ipa": "/ˈdʒiːnə hoʊldz aʊt hɜːr ɑːrm. ʃiː ɪz stɪl skɛrd. kloʊz jɔːr aɪz ænd θɪŋk əv ˈsʌmθɪŋ ˈfʌni, sɛz ðə ˈdɒktər/", vi: "Gena rụt rè chìa cánh tay ra, trong lòng vẫn còn sợ hãi lắm. 'Nhắm mắt lại và nghĩ đến điều gì thật vui nhộn nhé,' bác sĩ dịu dàng bảo." },
      { "start": 53.0, "en": "Gena closes her eyes, thinking. She feels a small pinch on her arm. 'There now,' says the doctor. 'You are a good girl.'", "ipa": "/ˈdʒiːnə ˈkloʊzɪz hɜːr aɪz, ˈθɪŋkɪŋ. ʃiː fiːlz a smɔːl pɪntʃ ɒn hɜːr ɑːrm. ðɛr naʊ, sɛz ðə ˈdɒktər. juː ɑːr a ɡʊd ɡɜːrl/", vi: "Gena nhắm chặt mắt lại và mường tượng. Cô bé chỉ cảm thấy hơi nhói nhẹ một chút ở tay. 'Xong rồi đấy,' bác sĩ mỉm cười. 'Cháu gái ngoan lắm.'" },
      { "start": 64.0, "en": "It is over. Gena laughs. She is not scared of needles anymore.", "ipa": "/ɪt ɪz ˈoʊvər. ˈdʒiːnə lɑːfs. ʃiː ɪz nɒt skɛrd əv ˈniːdlz ˈɛniˌmɔːr/", vi: "Mọi chuyện đã xong xuôi. Gena bật cười nhẹ nhõm. Cô bé từ nay không còn sợ kim tiêm nữa rồi." }
    ]
  },
  {
    "day": 13,
    "title": "Colours",
    image: "01 January/images/day_13.webp",
    audio: "01 January/audio/Track13.mp3",
    "sentences": [
      { "start": 4.8, "en": "Jake got out a piece of paper. Then he found a paintbrush and four colours of paint. He had red, yellow, blue, and white.", "ipa": "/dʒeɪk ɡɒt aʊt a piːs əv ˈpeɪpər. ðɛn hiː faʊnd a ˈpeɪntˌbrʌʃ ænd fɔːr ˈkʌlərz əv peɪnt. hiː hæd rɛd, ˈjɛloʊ, bluː, ænd waɪt/", vi: "Jake lấy ra một tờ giấy vẽ, tìm một chiếc cọ cùng bốn hộp màu cơ bản gồm đỏ, vàng, xanh dương và trắng." },
      { "start": 16.0, "en": "He painted a red boat floating on blue water. He painted a yellow sun peaking through white clouds.", "ipa": "/hiː ˈpeɪntɪd a rɛd boʊt ˈfloʊtɪŋ ɒn bluː ˈwɔːtər. hiː ˈpeɪntɪd a ˈjɛloʊ sʌn ˈpiːkɪŋ θruː waɪt klaʊdz/", vi: "Cậu vẽ một chiếc thuyền đỏ bập bềnh trên làn nước xanh thẳm, và một ông mặt trời vàng óng đang lấp ló sau những đám mây trắng." },
      { "start": 26.0, "en": "'I need orange for my picture,' said Jake. He mixed some of the red with some of the yellow. It made a nice shade of orange.", "ipa": "/aɪ niːd ˈɒrɪndʒ fɔːr maɪ ˈpɪktʃər, sɛd dʒeɪk. hiː mɪkst sʌm əv ðə rɛd wɪð sʌm əv ðə ˈjɛloʊ. ɪt meɪd a naɪs ʃeɪd əv ˈɒrɪndʒ/", vi: "'Mình cần thêm màu cam cho bức tranh,' Jake lẩm bẩm. Cậu bèn pha chút màu đỏ với màu vàng vào với nhau, thế là tạo ra được một sắc cam tuyệt đẹp." },
      { "start": 37.0, "en": "'That's better,' said Jake. 'But I need green too.' He mixed some of the yellow with some of the blue. It made a nice shade of green.", "ipa": "/ðæts ˈbɛtər, sɛd dʒeɪk. bʌt aɪ niːd ɡriːn tuː. hiː mɪkst sʌm əv ðə ˈjɛloʊ wɪð sʌm əv ðə bluː. ɪt meɪd a naɪs ʃeɪd əv ɡriːn/", vi: "'Được rồi đấy,' Jake gật gù. 'Nhưng mình vẫn cần cả màu xanh lá nữa.' Cậu lại pha màu vàng với màu xanh dương, và thế là ra được màu xanh lá rất đẹp mắt." },
      { "start": 49.0, "en": "'That's better,' said Jake. 'What about purple? I need purple as well.' He mixed some of the blue with some of the red. It made a nice shade of purple.", "ipa": "/ðæts ˈbɛtər, sɛd dʒeɪk. wɒt əˈbaʊt ˈpɜːrpl? aɪ niːd ˈpɜːrpl æz wɛl. hiː mɪkst sʌm əv ðə bluː wɪð sʌm əv ðə rɛd. ɪt meɪd a naɪs ʃeɪd əv ˈpɜːrpl/", vi: "'Hoàn hảo hơn rồi,' cậu tiếp tục. 'Còn màu tím thì sao nhỉ? Mình cần cả màu tím nữa.' Cậu pha màu xanh dương với màu đỏ, và lập tức có được sắc tím mộng mơ." },
      { "start": 62.0, "en": "'Much better,' said Jake. 'Now I'm ready to paint a rainbow.'", "ipa": "/mʌtʃ ˈbɛtər, sɛd dʒeɪk. naʊ aɪm ˈrɛdi tuː peɪnt a ˈreɪnˌboʊ/", vi: "'Tuyệt vời ông mặt trời,' Jake tươi cười. 'Bây giờ thì mình đã sẵn sàng để vẽ một chiếc cầu vồng rực rỡ rồi.'" }
    ]
  },
  {
    "day": 14,
    "title": "Open Your Eyes",
    image: "01 January/images/day_14.webp",
    audio: "01 January/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "My grandpa always says, 'The world is a beautiful place if you just open your eyes.' Now I know what he means.", "ipa": "/maɪ ˈɡrændpɑː ˈɔːlweɪz sɛz, 'ðə wɜːrld ɪz a ˈbjuːtɪfl pleɪs ɪf juː dʒʌst ˈoʊpən jɔːr aɪz.' naʊ aɪ noʊ wɒt hiː miːnz/", vi: "Ông nội tôi vẫn luôn dạy rằng: 'Thế giới ngoài kia vô cùng tươi đẹp nếu con biết mở rộng đôi mắt và tâm hồn để cảm nhận.' Giờ thì tôi đã thực sự thấu hiểu câu nói đó." },
      { "start": 16.0, "en": "One time, my friend's family invited me to go with them for a balloon ride.", "ipa": "/wʌn taɪm, maɪ frɛndz ˈfæməli ɪnˈvaɪtɪd miː tuː ɡoʊ wɪð ðɛm fɔːr a bəˈluːn raɪd/", vi: "Có lần, gia đình người bạn thân đã mời tôi đi trải nghiệm bay bằng khinh khí cầu." },
      { "start": 23.0, "en": "We all got in the basket. Then we started to lift off the ground. I got scared and closed my eyes.", "ipa": "/wiː ɔːl ɡɒt ɪn ðə ˈbɑːskɪt. ðɛn wiː ˈstɑːrtɪd tuː lɪft ɔːf ðə ɡraʊnd. aɪ ɡɒt skɛrd ænd cloʊzd maɪ aɪz/", vi: "Cả nhóm bước vào chiếc giỏ mây. Khi khinh khí cầu bắt đầu rời mặt đất bay lên cao, tôi hoảng sợ đến mức nhắm nghiền hai mắt lại." },
      { "start": 33.0, "en": "When I opened one eye, I saw the trees below us. I quickly shut my eyes again.", "ipa": "/wɛn aɪ ˈoʊpənd wʌn aɪ, aɪ sɔː ðə triːz bɪˈloʊ ʌs. aɪ ˈkwɪkli ʃʌt maɪ aɪz əˈɡɛn/", vi: "Lén mở hé một con mắt nhìn xuống dưới, tôi thấy những rặng cây bé xíu phía bên dưới. Sợ quá, tôi lại vội vàng nhắmịt mắt lại ngay." },
      { "start": 43.0, "en": "Suddenly, my friend yelled, 'Look!' A huge flock of geese was flying right by us. For a while, we blew right along with them. It was the most beautiful thing I had ever seen!", "ipa": "/ˈsʌdənli, maɪ frɛnd jɛld, 'lʊk!' a hyudʒ flɒk əv ɡiːs wɒz ˈflaɪɪŋ raɪt baɪ ʌs. fɔːr a waɪl, wiː bluː raɪt əˈlɒŋ wɪð ðɛm. ɪt wɒz ðə moʊst ˈbjuːtɪfl θɪŋ aɪ hæd ˈɛvər siːn/", vi: "Bỗng nhiên, bạn tôi reo lên: 'Nhìn kìa!' Một đàn ngỗng trời khổng lồ đang bay sát sạt ngay bên cạnh chúng tôi. Có một khoảnh khắc, khinh khí cầu bay song hành cùng cả đàn chim. Đó là khung cảnh tuyệt mỹ nhất mà tôi từng được thấy trong đời!" },
      { "start": 61.0, "en": "It was an amazing sight. Just imagine... all I had to do was open my eyes. Good advice, Grandpa!", "ipa": "/ɪt wɒz ən əˈmeɪzɪŋ saɪt. dʒʌst ɪˈmædʒɪn... ɔːl aɪ hæd tuː duː wɒz ˈoʊpən maɪ aɪz. ɡʊd ədˈvaɪs, ˈɡrændpɑː/", vi: "Thật là một kỳ quan choáng ngợp. Cứ thử nghĩ mà xem... tất cả những gì tôi cần làm chỉ là mở to mắt ra đón nhận. Lời khuyên của ông nội quả thực vô giá!" }
    ]
  },
  {
    "day": 15,
    "title": "The Picture",
    image: "01 January/images/day_15.webp",
    audio: "01 January/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "My uncle took a picture during his trip to Asia. It was taken on the sidewalk of a busy street.", "ipa": "/maɪ ˈʌŋkl tʊk a ˈpɪktʃər ˈdjʊərɪŋ hɪz trɪp tuː ˈeɪʒə. ɪt wɒz ˈteɪkən ɒn ðə ˈsaɪdˌwɔːk əv a ˈbɪzi striːt/", vi: "Chú tôi đã chụp lại một bức ảnh trong chuyến du lịch sang Châu Á. Bức hình được ghi lại ngay trên vỉa hè của một con phố tấp nập người qua lại." },
      { "start": 15.0, "en": "In the picture is a boy with a pencil and a notebook. He is working on his homework. There is no desk and no chair. He is using a stool as his desk.", "ipa": "/ɪn ðə ˈpɪktʃər ɪz a bɔɪ wɪð a ˈpɛnsl ænd a ˈnoʊtˌbʊk. hiː ɪz ˈwɜːrkɪŋ ɒn hɪz ˈhoʊmˌwɜːrk. ðɛr ɪz noʊ dɛsk ænd noʊ tʃɛr. hiː ɪz ˈjuːzɪŋ a stuːl æz hɪz dɛsk/", vi: "Trong ảnh là một cậu bé đang cầm bút chì và vở ghi, chăm chú làm bài tập về nhà. Không có bàn học, cũng chẳng có ghế dựa, cậu bé tận dụng luôn một chiếc ghế đẩu thấp làm bàn học." },
      { "start": 29.0, "en": "Around the boy are his father and mother. The father is pointing to the book, trying to help. The mother is smiling and watching them closely. Beside them is their family business—a bicycle repair stand.", "ipa": "/əˈraʊnd ðə bɔɪ ɑːr hɪz ˈfɑːðər ænd ˈmʌðər. ðə ˈfɑːðər ɪz ˈpɔɪntɪŋ tuː ðə bʊk, ˈtraɪɪŋ tuː hɛlp. ðə ˈmʌðər ɪz ˈsmaɪlɪŋ ænd ˈwɒtʃɪŋ ðɛm ˈkloʊsli. bɪˈsaɪd ðɛm ɪz ðɛər ˈfæməli ˈbɪznəs—a ˈbaɪsɪkl rɪˈpɛr stænd/", vi: "Vây quanh cậu bé là bố và mẹ. Người bố đang chỉ tay vào sách giải thích bài giúp con, còn người mẹ mỉm cười trìu mến quan sát hai bố con. Ngay sát bên họ chính là sinh kế của gia đình — một tiệm sửa xe đạp nhỏ bên đường." },
      { "start": 48.0, "en": "It seems that the parents do not have much education. But you can see that they care strongly about their son's school work. Their eyes are filled with hope.", "ipa": "/ɪt siːmz ðæt ðə ˈpɛrənts duː nɒt hæv mʌtʃ ˌɛdʒʊˈkeɪʃn. bʌt juː kæn siː ðæt ðeɪ kɛr ˈstrɒŋli əˈbaʊt ðɛər sʌnz skuːl wɜːrk. ðɛər aɪz ɑːr fɪld wɪð hoʊp/", vi: "Có vẻ như bố mẹ cậu không được học hành cao suông, nhưng qua ánh mắt tràn ngập hy vọng, ta thấy họ đặt trọn vẹn sự quan tâm và kỳ vọng vào việc học hành của con trai." },
      { "start": 62.0, "en": "Bicycles, cars, buses and people are passing by in the picture. But this family is not disturbed by the noise. To the family, the son's studies seem to be the centre of the world.", "ipa": "/ˈbaɪsɪklz, kɑːrz, ˈbʌsɪz ænd ˈpiːpl ɑːr ˈpɑːsɪŋ baɪ ɪn ðə ˈpɪktʃər. bʌt ðɪs ˈfæməli ɪz nɒt dɪsˈtɜːrbd baɪ ðə nɔɪz. tuː ðə ˈfæməli, ðə sʌnz ˈstʌdiz siːm tuː biː ðə ˈsɛntər əv ðə wɜːrld/", vi: "Xe cộ, ô tô, buýt và dòng người hối hả lướt qua trong khung hình, nhưng gia đình nhỏ ấy dường như chẳng mảy may bận tâm đến tiếng ồn ào ngoài kia. Đối với họ, việc học của đứa con trai chính là tâm điểm của cả thế giới." },
      { "start": 78.0, "en": "I was really touched by this picture.", "ipa": "/aɪ wɒz ˈrɪəli tʌtʃt baɪ ðɪs ˈpɪktʃər/", vi: "Tôi thực sự vô cùng xúc động khi ngắm nhìn bức ảnh này." }
    ]
  },
  {
    "day": 16,
    "title": "Healthy Heart",
    image: "01 January/images/day_16.webp",
    audio: "01 January/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "Thump. Thump. That is the sound of your heart beating. What an amazing muscle! It works all day. It works all night.", "ipa": "/θʌmp. θʌmp. ðæt ɪz ðə saʊnd əv jɔːr hɑːrt ˈbiːtɪŋ. wɒt ən əˈmeɪzɪŋ ˈmʌsl! ɪt wɜːrks ɔːl deɪ. ɪt wɜːrks ɔːl naɪt/", vi: "Thịch. Thịch. Đó là âm thanh nhịp đập trái tim của bạn. Thật là một khối cơ bắp kỳ diệu! Nó miệt mài làm việc suốt cả ngày lẫn đêm không nghỉ." },
      { "start": 16.0, "en": "Your heart pumps blood to all the parts of your body. It pumps blood to your head, your fingers and your feet. And it weighs only about half a kilogram.", "ipa": "/jɔːr hɑːrt pʌmps blʌd tuː ɔːl ðə pɑːrts əv jɔːr ˈbɒdi. ɪt pʌmps blʌd tuː jɔːr hɛd, jɔːr ˈfɪŋɡərz ænd jɔːr fiːt. ænd ɪt weɪz ˈoʊnli əˈbaʊt hæf a ˈkɪləˌɡræm/", vi: "Trái tim có nhiệm vụ bơm máu đi nuôi toàn bộ các bộ phận trên cơ thể: từ đầu, các ngón tay cho đến tận bàn chân. Thế mà trọng lượng của nó chỉ nặng vỏn vẹn khoảng nửa kg." },
      { "start": 31.0, "en": "But it's a very strong muscle. It beats 100,000 times a day. That's 35 million times a year. Wow!", "ipa": "/bʌt ɪts a ˈvɛri strɒŋ ˈmʌsl. ɪt biːts ˈwʌn ˈhʌndrəd ˈtaʊznd taɪmz a deɪ. ðæts ˈθɜːrti-faɪv ˈmɪljən taɪmz a jɪər. waʊ/", vi: "Dù nhỏ bé nhưng đó là một cơ bắp cực kỳ cường tráng. Nó đập tới 100.000 lần mỗi ngày, tính ra là 35 triệu lần trong một năm. Thật đáng kinh ngạc!" },
      { "start": 44.0, "en": "In your lifetime, your heart will beat about two and a half billion times. You know what else is really amazing? Your heart does all of this without you even giving it a thought. It just keeps working.", "ipa": "/ɪn jɔːr ˈlaɪfˌtaɪm, jɔːr hɑːrt wɪl biːt əˈbaʊt tuː ænd ə hæf ˈbɪljən taɪmz. juː noʊ wɒt ɛls ɪz ˈrɪəli əˈmeɪzɪŋ? jɔːr hɑːrt dʌz ɔːl əv ðɪs wɪˈðaʊt juː ˈiːvn ˈɡɪvɪŋ ɪt a θɔːt. ɪt dʒʌst kiːps ˈwɜːrkɪŋ/", vi: "Suốt cuộc đời một con người, trái tim sẽ đập khoảng 2,5 tỷ lần. Bạn có biết điều gì còn diệu kỳ hơn nữa không? Trái tim thực hiện tất cả những công việc vĩ đại đó mà chẳng cần bạn phải bận tâm suy nghĩ gì cả. Nó cứ âm thầm và bền bỉ đập như thế." },
      { "start": 65.0, "en": "Most hearts beat about 70 times every minute. See for yourself. Put your hand on your wrist. Feel your heart beating. Now, count how many times it beats in a minute.", "ipa": "/moʊst hɑːrts biːt əˈbaʊt ˈsɛvnti taɪmz ˈɛvri ˈmɪnɪt. siː fɔːr jɔːrˈsɛlf. pʊt jɔːr hænd ɒn jɔːr rɪst. fiːl jɔːr hɑːrt ˈbiːtɪŋ. naʊ, kaʊnt haʊ ˈmɛni taɪmz ɪt biːts ɪn a ˈmɪnɪt/", vi: "Hầu hết các nhịp tim đập khoảng 70 lần mỗi phút. Hãy tự mình kiểm chứng nhé: Đặt tay lên cổ tay để cảm nhận nhịp đập, sau đó đếm xem tim đập bao nhiêu nhịp trong một phút." },
      { "start": 82.0, "en": "Take care of your heart. Eat well. Sleep well. And get lots of exercise. That way, your heart will be strong and keep on beating.", "ipa": "/teɪk kɛər əv jɔːr hɑːrt. iːt wɛl. sliːp wɛl. ænd ɡɛt lɒts əv ˈɛksərˌsaɪz. ðæt weɪ, jɔːr hɑːrt wɪl biː strɒŋ ænd kiːp ɒn ˈbiːtɪŋ/", vi: "Hãy biết trân trọng và chăm sóc trái tim của mình: Ăn uống điều độ, ngủ đủ giấc và tích cực tập thể dục thể thao. Nhờ đó, trái tim bạn sẽ luôn khỏe mạnh và đập mãi không ngừng." }
    ]
  },
  {
    "day": 17,
    "title": "Baby Jessie",
    image: "01 January/images/day_17.webp",
    audio: "01 January/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "Everyone was waiting for Jessie and her parents to arrive. 'They'll be here soon!'", "ipa": "/ˈɛvriˌwʌn wɒz ˈweɪtɪŋ fɔːr ˈdʒɛsi ænd hɜːr ˈpɛrənts tuː əˈraɪv. ðeɪl biː hɪər suːn/", vi: "Mọi người đang hồi hộp ngóng chờ bé Jessie và bố mẹ em đến. 'Họ sắp tới nơi rồi kìa!'" },
      { "start": 12.0, "en": "'Can Jessie and I play games together?' asked Laurie. 'Not yet,' answered Mom. 'Jessie is still a baby, you know.'", "ipa": "/kæn ˈdʒɛsi ænd aɪ pleɪ ɡeɪmz təˈɡɛðər? ɑːskt ˈlɔːri. nɒt jɛt, ˈɑːnsərd mɒm. ˈdʒɛsi ɪz stɪl a ˈbeɪbi, juː noʊ/", vi: "'Cháu có thể chơi trò chơi cùng Jessie được không ạ?' Laurie hỏi. 'Chưa được đâu con,' mẹ đáp. 'Con biết đấy, Jessie vẫn còn là một em bé mà.'" },
      { "start": 23.0, "en": "'It takes a long time for a baby to turn into a kid, doesn't it?' asked Laurie. Mom laughed, 'Yes, it does.'", "ipa": "/ɪt teɪks a lɒŋ taɪm fɔːr a ˈbeɪbi tuː tɜːrn ˈɪntuː a kɪd, ˈdʌznt ɪt? ɑːskt ˈlɔːri. mɒm lɑːft, jɛs, ɪt dʌz/", vi: "'Cần mất nhiều thời gian lắm để một đứa bé lớn thành trẻ con cơ à mẹ?' Laurie thắc mắc. Mẹ bật cười: 'Đúng vậy con ạ.'" },
      { "start": 33.0, "en": "'Then she isn't good for much yet,' said Laurie. Dad laughed, 'I don't think her parents would agree with that. They kind of like her.'", "ipa": "/ðɛn ʃiː ˈɪznt ɡʊd fɔːr mʌtʃ jɛt, sɛd ˈlɔːri. dæd lɑːft, aɪ doʊnt θɪŋk hɜːr ˈpɛrənts wʊd əˈɡriː wɪð ðæt. ðeɪ kaɪnd əv laɪk hɜːr/", vi: "'Thế thì em ấy chẳng làm được tích sự gì mấy rồi,' Laurie bĩu môi. Bố cười vang: 'Bố nghĩ bố mẹ của con sẽ không đồng tình với ý đó đâu, họ cưng chiều con bé lắm đấy chứ.'" },
      { "start": 48.0, "en": "A moment later, Jessie and her parents finally arrived. Jessie started crying because she didn't recognize Laurie and her family.", "ipa": "/ə ˈmoʊmənt ˈleɪtər, ˈdʒɛsi ænd hɜːr ˈpɛrənts ˈfaɪnəli əˈraɪvd. ˈdʒɛsi ˈstɑːrtɪd ˈkraɪɪŋ bɪˈkəz ʃiː ˈdɪdnt ˈrɛkəɡˌnaɪz ˈlɔːri ænd hɜːr ˈfæməli/", vi: "Chỉ lát sau, bé Jessie và bố mẹ đã đến nơi. Vì lạ mặt không quen biết gia đình Laurie nên Jessie sợ hãi òa khóc nức nở." },
      { "start": 60.0, "en": "'She really isn't worth much,' thought Laurie. But she didn't say this out loud.", "ipa": "/ʃiː ˈrɪəli ˈɪznt wɜːrθ mʌtʃ, θɔːt ˈlɔːri. bʌt ʃiː ˈdɪdnt seɪ ðɪs aʊt laʊd/", vi: "'Đúng là chẳng tích sự gì thật,' Laurie thầm nghĩ trong đầu, nhưng cô bé không dám nói ra thành tiếng." },
      { "start": 68.0, "en": "Laurie then showed Jessie the box of toys. She shook a rattle at her. Jessie laughed. 'I guess maybe she is worth a little bit,' thought Laurie as her eyes lit up.", "ipa": "/ˈlɔːri ðɛn ʃoʊd ˈdʒɛsi ðə bɒks əv tɔɪz. ʃiː ʃʊk a ˈrætl æt hɜːr. ˈdʒɛsi lɑːft. aɪ ɡɛs ˈmeɪbi ʃiː ɪz wɜːrθ a ˈlɪtl bɪt, θɔːt ˈlɔːri æz hɜːr aɪz lɪt ʌp/", vi: "Laurie bèn mang hộp đồ chơi ra dỗ dành, cầm chiếc lúc lắc khua khoắng trước mặt em. Cậu bé Jessie liền nín khóc và phá lên cười thích thú. 'Chắc em ấy cũng đáng yêu phết đấy chứ,' mắt Laurie sáng rực lên khi nghĩ thầm." }
    ]
  },
  {
    "day": 18,
    "title": "The Little Red Teapot",
    image: "01 January/images/day_18.webp",
    audio: "01 January/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "Last winter, I had a bad cold. I could hardly breathe through my nose. In the morning, my mother brought me a little red teapot.", "ipa": "/lɑːst ˈwɪntər, aɪ hæd a bæd koʊld. aɪ kʊd ˈhɑːrdli briːð θruː maɪ noʊz. ɪn ðə ˈmɔːrnɪŋ, maɪ ˈmʌðər brɔːt miː a ˈlɪtl rɛd ˈtiːˌpɒt/", vi: "Mùa đông năm ngoái, tôi bị một trận cảm lạnh nặng, nghẹt mũi đến mức gần như không thể thở được. Sáng hôm ấy, mẹ mang vào cho tôi một chiếc ấm pha trà nhỏ màu đỏ." },
      { "start": 17.0, "en": "'Tea? I don't like tea!' I said. 'I know,' Mom said. 'But tea is one of the best things you can drink. It's very healthy. This is a special tea for when you are sick.'", "ipa": "/tiː? aɪ doʊnt laɪk tiː! aɪ sɛd. aɪ noʊ, mɒm sɛd. bʌt tiː ɪz wʌn əv ðə bɛst θɪŋz juː kæn drɪŋk. ɪts ˈvɛri ˈhɛlθi. ðɪs ɪz a ˈspɛʃl tiː fɔːr wɛn juː ɑːr sɪk/", vi: "'Trà á? Con ghét uống trà lắm!' tôi nhăn mặt. 'Mẹ biết chứ,' mẹ dịu dàng đáp. 'Nhưng trà là một trong những thức uống bổ dưỡng nhất, rất tốt cho sức khỏe. Đây là loại trà đặc biệt dành riêng cho lúc con bị ốm đấy.'" },
      { "start": 33.0, "en": "There was no way out. I brought the cup to my lips and took a small sip. The tea was strong and bitter.", "ipa": "/ðɛr wɒz noʊ weɪ aʊt. aɪ brɔːt ðə kʌp tuː maɪ lɪps ænd tʊk a smɔːl sɪp. ðə tiː wɒz strɒŋ ænd ˈbɪtər/", vi: "Biết không thể từ chối được, tôi đành nâng ly trà lên môi và nhấp một ngụm nhỏ. Vị trà đậm đặc và hơi ngăm đắng." },
      { "start": 43.0, "en": "I knew my mom was trying to help me. So I took another sip. Within a few hours, I could breathe through my nose again!", "ipa": "/aɪ nuː maɪ mɒm wɒz ˈtraɪɪŋ tuː hɛlp miː. soʊ aɪ tʊk əˈnʌðər sɪp. wɪˈðɪn a fjuː ˈaʊərz, aɪ kʊd briːð θruː maɪ noʊz əˈɡɛn/", vi: "Hiểu được dụng ý tốt của mẹ, tôi uống thêm vài ngụm nữa. Kỳ diệu làm sao, chỉ sau vài tiếng đồng hồ, mũi tôi đã thông thoáng trở lại và thở bình thường được!" },
      { "start": 55.0, "en": "Was it the tea? I don't know. But I do know that the next time I'm sick, I'll be looking for that little red teapot again!", "ipa": "/wɒt ɪt ðə tiː? aɪ doʊnt noʊ. bʌt aɪ duː noʊ ðæt ðə nɛkst taɪm aɪm sɪk, aɪl biː ˈlʊkɪŋ fɔːr ðæt ˈlɪtl rɛd ˈtiːˌpɒt əˈɡɛn/", vi: "Có phải nhờ ly trà đó không nhỉ? Tôi cũng không chắc nữa. Nhưng tôi dám chắc rằng lần tới nếu bị ốm, tôi sẽ lại tìm ngay chiếc ấm trà đỏ nhỏ bé ấy cho xem!" }
    ]
  },
  {
    "day": 19,
    "title": "The Party",
    image: "01 January/images/day_19.webp",
    audio: "01 January/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "One hot summer day, Mouse decided to have a party. Mouse walked over to Beaver's house.", "ipa": "/wʌn hɒt ˈsʌmər deɪ, maʊs dɪˈsaɪdɪd tuː hæv a ˈpɑːrti. maʊs wɔːkt ˈoʊvər tuː ˈbiːvərz haʊs/", vi: "Vào một ngày hè oi ả, Chú Chuột nảy ý định tổ chức một buổi tiệc vui vẻ và đến tận nhà Hải Ly để mời." },
      { "start": 13.0, "en": "'Beaver, please come to my party. I'll be serving bananas,' said Mouse. 'Bananas? I'll only come if you serve oranges,' said Beaver.", "ipa": "/ˈbiːvər, pliːz kʌm tuː maɪ ˈpɑːrti. aɪl biː ˈsɜːrvɪŋ bəˈnænəz, sɛd maʊs. bəˈnænəz? aɪl ˈoʊnli kʌm ɪf juː sɜːrv ˈɒrɪndʒɪz, sɛd ˈbiːvər/", vi: "'Hải Ly ơi, bạn đến dự tiệc nhà tớ nhé. Tớ sẽ đãi chuối đấy,' Chuột mời. 'Chuối á? Tớ chỉ đến nếu cậu đãi cam thôi,' Hải Ly kiêu kỳ đáp." },
      { "start": 25.0, "en": "'Okay,' said Mouse. 'My friends will like oranges. I'll make sure to pick some up.'", "ipa": "/oʊˈkeɪ, sɛd maʊs. maɪ frɛndz wɪl laɪk ˈɒrɪndʒɪz. aɪl meɪk ʃʊr tuː pɪk sʌm ʌp/", vi: "'Được thôi,' Chuột vui vẻ nhận lời. 'Chắc các bạn cũng thích ăn cam. Tớ sẽ tranh thủ hái vài quả.'" },
      { "start": 33.0, "en": "Next, Mouse walked to Rabbit's house. 'Rabbit, please come to my party. I'll be serving oranges,' said Mouse.", "ipa": "/nɛkst, maʊs wɔːkt tuː ˈræbɪts haʊs. ˈræbɪt, pliːz kʌm tuː maɪ ˈpɑːrti. aɪl biː ˈsɜːrvɪŋ ˈɒrɪndʒɪz, sɛd maʊs/", vi: "Tiếp đó, Chuột ghé sang nhà Thỏ. 'Thỏ ơi, đến dự tiệc nhà tớ nhé. Tớ có chuẩn bị cam đãi khách đấy,' Chuột nói." },
      { "start": 42.0, "en": "'Oranges? I'll only come if you serve apples,' said Rabbit. 'Okay,' said Mouse. But he was puzzled.", "ipa": "/ˈɒrɪndʒɪz? aɪl ˈoʊnli kʌm ɪf juː sɜːrv ˈæplz, sɛd ˈræbɪt. oʊˈkeɪ, sɛd maʊs. bʌt hiː wɒz ˈpʌzld/", vi: "'Cam á? Tớ chỉ tham gia nếu có táo cơ,' Thỏ đòi hỏi. 'Được rồi,' Chuột gật đầu nhưng trong lòng bắt đầu thấy thắc mắc khó hiểu." },
      { "start": 53.0, "en": "Mouse then walked to Squirrel's house. 'Squirrel, please come to my party. I'll be serving apples,' said Mouse.", "ipa": "/maʊs ðɛn wɔːkt tuː ˈskwɜːrəlz haʊs. ˈskwɜːrəl, pliːz kʌm tuː maɪ ˈpɑːrti. aɪl biː ˈsɜːrvɪŋ ˈæplz, sɛd maʊs/", vi: "Chuột lại lật đật sang nhà Sóc. 'Sóc ơi, đến dự tiệc nhà tớ nhé. Tớ đãi táo ngon lắm,' Chuột mời." },
      { "start": 62.0, "en": "'Apples? I'll only come if you serve bananas,' said Squirrel. 'Alright!' exclaimed Mouse.", "ipa": "/ˈæplz? aɪl ˈoʊnli kʌm ɪf juː sɜːrv bəˈnænəz, sɛd ˈskwɜːrəl. ɔːlˈraɪt! ɪkˈskleɪmd maʊs/", vi: "'Táo á? Tớ nhận lời khi nào cậu đãi chuối cơ,' Sóc đáp. 'Thì chuối đây!' Chuột thốt lên cười ra nước mắt." },
      { "start": 72.0, "en": "Mouse knew exactly what to do. He cut up bananas, oranges and apples. Then, he mixed them all in a bowl. 'Now all of my guests will be happy!'", "ipa": "/maʊs nuː ɪɡˈzæktli wɒt tuː duː. hiː kʌt ʌp bəˈnænəz, ˈɒrɪndʒɪz ænd ˈæplz. ðɛn, hiː mɪkst ðɛm ɔːl ɪn a boʊl. naʊ ɔːl əv maɪ ɡɛsts wɪl biː ˈhæpi/", vi: "Lúc này Chuột đã ngộ ra cách giải quyết hoàn hảo. Cậu cắt nhỏ chuối, cam và táo thành từng miếng, rồi trộn tất cả chúng lại vào một cái thố lớn. 'Thế là tất cả khách quý của tớ đều sẽ hài lòng rồi!'" }
    ]
  },
  {
    "day": 20,
    "title": "The Three Sisters",
    image: "01 January/images/day_20.webp",
    audio: "01 January/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "Eddy and Casey did not like eating vegetables. They liked meat and fish. They liked rice and bread. They even liked apples, grapes and bananas. But they did not like vegetables.", "ipa": "/ˈɛdi ænd ˈkeɪsi dɪd nɒt laɪk ˈiːtɪŋ ˈvɛdʒtəblz. ðeɪ laɪkt miːt ænd fɪʃ. ðeɪ laɪkt raɪs ænd brɛd. ðeɪ ˈiːvn laɪkt ˈæplz, ɡreɪps ænd bəˈnænəz. bʌt ðeɪ dɪd nɒt laɪk ˈvɛdʒtəblz/", vi: "Eddy và Casey vốn không thích ăn rau xanh. Chúng thích ăn thịt và cá, thích cơm và bánh mì, thậm chí còn thích cả táo, nho và chuối. Riêng rau củ thì dứt khoát không thèm đụng tới." },
      { "start": 18.0, "en": "One day, their mom told them a story. Long ago, the Native people in Canada grew three special vegetables. They planted corn, beans and pumpkins very close to each other in the garden.", "ipa": "/wʌn deɪ, ðɛər mɒm toʊld ðɛm a ˈstɔːri. lɒŋ əˈɡoʊ, ðə ˈneɪtɪv ˈpiːpl ɪn ˈkænədə ɡruː θriː ˈspɛʃl ˈvɛdʒtəblz. ðeɪ ˈplɑːntɪd kɔːrn, biːnz ænd ˈpʌmpkɪnz ˈvɛri kloʊs tuː iːtʃ ˈʌðər ɪn ðə ˈɡɑːrdn/", vi: "Một hôm, mẹ kể cho hai anh em nghe một câu chuyện thú vị. Ngày xửa ngày xưa, người thổ dân bản địa ở Canada đã trồng ba loại rau củ đặc biệt cạnh nhau trong vườn: ngô, đậu và bí ngô." },
      { "start": 33.0, "en": "The corn grew strong and tall. The beans climbed up the big strong corn stems. The pumpkins made big leaves as they grew. The leaves kept the ground cool and wet.", "ipa": "/ðə kɔːrn ɡruː strɒŋ ænd tɔːl. ðə biːnz klaɪmd ʌp ðə bɪɡ strɒŋ kɔːrn stɛmz. ðə ˈpʌmpkɪnz meɪd bɪɡ liːvz æz ðeɪ ɡruː. ðə liːvz kɛpt ðə ɡraʊnd kuːl ænd wɛt/", vi: "Cây ngô vươn mình cao lớn và cứng cáp. Những dây đậu leo quấn quanh thân ngô vững chắc. Cây bí ngô thì tỏa ra những chiếc lá to bản rợp bóng, giữ cho đất bên dưới luôn ẩm mát." },
      { "start": 48.0, "en": "The three vegetables helped each other. They were like three sisters in a family.", "ipa": "/ðə θriː ˈvɛdʒtəblz hɛlpt iːtʃ ˈʌðər. ðeɪ wɜːr laɪk θriː ˈsɪstərz ɪn a ˈfæməli/", vi: "Ba loại rau củ ấy hỗ trợ qua lại cho nhau nhịp nhàng, gắn bó thân thiết tựa như ba chị em trong một nhà." },
      { "start": 56.0, "en": "That is why the Native people call these vegetables the three sisters. They are very special. Little kids grow big and strong by eating corn, beans and pumpkins.", "ipa": "/ðæt ɪz waɪ ðə ˈneɪtɪv ˈpiːpl kɔːl ðiːz ˈvɛdʒtəblz ðə θriː ˈsɪstərz. ðeɪ ɑːr ˈvɛri ˈspɛʃl. ˈlɪtl kɪdz ɡroʊ bɪɡ ænd strɒŋ baɪ ˈiːtɪŋ kɔːrn, biːnz ænd ˈpʌmpkɪnz/", vi: "Đó chính là lý do người bản địa gọi chúng là 'Bộ ba chị em'. Chúng vô cùng đặc biệt. Trẻ nhỏ ăn ngô, đậu và bí ngô sẽ mau chóng lớn khôn và khỏe mạnh." },
      { "start": 69.0, "en": "Now, Eddy and Casey eat their vegetables every day.", "ipa": "/naʊ, ˈɛdi ænd ˈkeɪsi iːt ðɛər ˈvɛdʒtəblz ˈɛvri deɪ/", vi: "Từ hôm đó trở đi, Eddy và Casey đã chăm chỉ ăn rau củ đều đặn mỗi ngày." }
    ]
  },
  {
    "day": 21,
    "title": "Baseball or Piano?",
    image: "01 January/images/day_21.webp",
    audio: "01 January/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "My mom loves music. She wants me to become a pianist. But I like sports. I play baseball every day after school. Sometimes, I stay out playing until it gets dark.", "ipa": "/maɪ mɒm lʌvz ˈmjuːzɪk. ʃiː wɒnts miː tuː bɪˈkʌm a ˈpiːənɪst. bʌt aɪ laɪk spɔːrts. aɪ pleɪ ˈbeɪsˌbɔːl ˈɛvri deɪ ˈɑːftər skuːl. ˈsʌmˌtaɪmz, aɪ steɪ aʊt ˈpleɪɪŋ ənˈtɪl ɪt ɡɛts dɑːrk/", vi: "Mẹ tôi cực kỳ mê âm nhạc và luôn khao khát tôi trở thành nghệ sĩ piano chuyên nghiệp. Nhưng ngặt nỗi tôi lại đam mê thể thao, ngày nào tan học cũng chơi bóng rổ hoặc bóng chày, đôi khi mải chơi đến tận tối mịt mới về." },
      { "start": 18.0, "en": "So when my mom signed me up for piano lessons, I was not happy. Mom said that I had to try the piano for one year.", "ipa": "/soʊ wɛn maɪ mɒm saɪnd miː ʌp fɔːr ˈpiːˌnoʊ ˈlɛsnz, aɪ wɒz nɒt ˈhæpi. mɒm sɛd ðæt aɪ hæd tuː traɪ ðə ˈpiːˌnoʊ fɔːr wʌn jɪər/", vi: "Thế nên khi bị mẹ đăng ký cho đi học đàn piano, tôi phụng phịu không buồn. Mẹ nghiêm khắc bảo rằng tôi phải thử kiên trì học đàn trong vòng một năm." },
      { "start": 29.0, "en": "I went to the first lesson. It was very difficult. My fingers were not good at pushing the right piano keys. They were good at holding a ball.", "ipa": "/aɪ wɛnt tuː ðə fɜːrst ˈlɛsn. ɪt wɒz ˈvɛri ˈdɪfɪkəlt. maɪ ˈfɪŋɡərz wɜːr nɒt ɡʊd æt ˈpʊʃɪŋ ðə raɪt ˈpiːˌnoʊ kiːz. ðeɪ wɜːr ɡʊd æt ˈhoʊldɪŋ a bɔːl/", vi: "Buổi học đàn đầu tiên quả là một thử thách khó nhằn. Các ngón tay cứng đờ của tôi không tài nào bấm đúng phím đàn cho chuẩn, trong khi chúng lại rất quen thuộc với việc cầm bóng." },
      { "start": 42.0, "en": "A little girl there saw me struggling. She said to me, 'I will help you learn to play the piano if you teach me to play baseball.'", "ipa": "/aɪ ˈlɪtl ɡɜːrl ðɛr sɔː miː ˈstrʌɡəlɪŋ. ʃiː sɛd tuː miː, 'aɪ wɪl hɛlp juː lɜːrn tuː pleɪ ðə ˈpiːˌnoʊ ɪf juː tiːtʃ miː tuː pleɪ ˈbeɪsˌbɔːl.'/", vi: "Một cô bé ở lớp học thấy tôi đang chật vật liền tiến lại gần đề nghị: 'Tớ sẽ giúp cậu học chơi piano nếu cậu chịu dạy tớ cách đánh bóng chày nhé.'" },
      { "start": 54.0, "en": "We became good friends that day. She taught me how to play Beethoven. And I taught her how to throw a curve ball.", "ipa": "/wiː bɪˈkeɪm ɡʊd frɛndz ðæt deɪ. ʃiː tɔːt miː haʊ tuː pleɪ ˈbeɪtˌhoʊvən. ænd aɪ tɔːt hɜːr haʊ tuː θroʊ a kɜːrv bɔːl/", vi: "Cả hai nhanh chóng trở thành đôi bạn thân thiết từ hôm đó. Cô bé dạy tôi cách đánh các bản nhạc của Beethoven, còn tôi hướng dẫn cậu ấy cách ném bóng xoáy hiểm hóc." },
      { "start": 66.0, "en": "Now, I don't know which I like better, baseball or piano?", "ipa": "/naʊ, aɪ doʊnt noʊ wɪtʃ aɪ laɪk ˈbɛtər, ˈbeɪsˌbɔːl ɔːr ˈpiːˌnoʊ?/", vi: "Đến bây giờ thì thú thực tôi chẳng biết mình thích món nào hơn nữa: bóng chày hay piano đây?" }
    ]
  },
  {
    "day": 22,
    "title": "The Missing Gloves",
    image: "01 January/images/day_22.webp",
    audio: "01 January/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "This year, my mom made me a new pair of gloves for my birthday. That day, I wore them to the skating rink.", "ipa": "/ðɪs jɪər, maɪ mɒm meɪd miː a nuː pɛr əv ɡlʌvz fɔːr maɪ ˈbɜːrθdeɪ. ðæt deɪ, aɪ wɔːr ðɛm tuː ðə ˈskeɪtɪŋ rɪŋk/", vi: "Năm nay, mẹ đã tự tay đan tặng tôi một đôi găng tay mới tinh nhân dịp sinh nhật. Hôm đó, tôi hào hứng diện ngay đôi găng tay ấy ra sân trượt băng." },
      { "start": 14.0, "en": "It got quite warm. Everyone took off their heavy coats and hats. I took off my new gloves. I put them safely in my jacket and skated around in my sweater.", "ipa": "/ɪt ɡɒt kwaɪt wɔːrm. ˈɛvriˌwʌn tʊk ɔːf ðɛər ˈhɛvi koʊts ænd hæts. aɪ tʊk ɔːf maɪ nuː ɡlʌvz. aɪ pʊt ðɛm ˈseɪfli ɪn maɪ ˈdʒækɪt ænd ˈskeɪtɪd əˈraʊnd ɪn maɪ ˈswɛtər/", vi: "Càng về sau thời tiết càng ấm dần lên. Mọi người đều cởi bỏ áo khoác dày và mũ len. Tôi cũng tháo đôi găng tay mới ra, nhét cẩn thận vào túi áo khoác rồi tiếp tục trượt băng với chiếc áo len." },
      { "start": 29.0, "en": "When it was time to go home, I picked up my jacket. But my gloves were gone!", "ipa": "/wɛn ɪt wɒz taɪm tuː ɡoʊ hoʊm, aɪ pɪkt ʌp maɪ ˈdʒækɪt. bʌt maɪ ɡlʌvz wɜːr ɡɒn/", vi: "Đến lúc thu dọn đồ đạc để ra về, tôi cầm áo khoác lên và tá hỏa phát hiện đôi găng tay đã biến mất tiêu!" },
      { "start": 37.0, "en": "I could not believe it. I went home and told my parents. They were upset with me. I felt terrible.", "ipa": "/aɪ kʊd nɒt bɪˈliːv ɪt. aɪ wɛnt hoʊm ænd toʊld maɪ ˈpɛrənts. ðeɪ wɜːr ʌpˈsɛt wɪð miː. aɪ fɛlt ˈtɛrəbl/", vi: "Tôi đứng hình chẳng thể tin nổi. Về đến nhà thú thật với bố mẹ, tôi bị mắng cho một trận tơi bời. Cảm giác lúc ấy thật tồi tệ." },
      { "start": 48.0, "en": "Later that evening, the doorbell rang. It was a boy from school. He had the exact same jacket as me. I had accidentally picked up the wrong jacket!", "ipa": "/ˈleɪtər ðæt ˈiːvnɪŋ, ðə ˈdɔːrˌbɛl ræŋ. ɪt wɒz a bɔɪ frɒm skuːl. hiː hæd ði ɪɡˈzækt seɪm ˈdʒækɪt æz miː. aɪ hæd ˌæksəˈdɛntəli pɪkt ʌp ðə rɒŋ ˈdʒækɪt/", vi: "Đến chập tối hôm đó, chuông cửa reo vang. Hóa ra là một cậu bạn học cùng trường đem đồ đến trả. Cậu ấy mặc chiếc áo khoác y hệt như tôi, và lúc ở sân trượt tôi đã cầm nhầm áo của cậu ấy!" },
      { "start": 62.0, "en": "'Missing these?' he asked as he handed me my gloves and jacket. I had never been so happy to see a pair of gloves in my whole life!", "ipa": "/ˈmɪsɪŋ ðiːz? hiː ɑːskt æz hiː ˈhændɪd miː maɪ ɡlʌvz ænd ˈdʒækɪt. aɪ hæd ˈnɛvər biːn soʊ ˈhæpi tuː siː a pɛr əv ɡlʌvz ɪn maɪ hoʊl laɪf/", vi: "'Cậu đang tìm thứ này phải không?' cậu bạn hỏi và trao trả lại chiếc áo cùng đôi găng tay cho tôi. Chưa bao giờ trong đời tôi lại cảm thấy vui sướng khi nhìn thấy đôi găng tay đến thế!" }
    ]
  },
  {
    "day": 23,
    "title": "The Gentle Giant",
    image: "01 January/images/day_23.webp",
    audio: "01 January/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "You probably already know that elephants are the largest land animals. Some people think that, next to humans, elephants are the smartest creatures on earth.", "ipa": "/juː ˈprɒbəbli ɔːlˈrɛdi noʊ ðæt ˈɛlɪfənts ɑːr ðə ˈlɑːrdʒɪst lænd ˈænɪmlz. sʌm ˈpiːpl θɪŋk ðæt, nɛkst tuː ˈhjuːmənz, ˈɛlɪfənts ɑːr ðə ˈsmɑːrtɪst ˈkriːtʃərz ɒn ɜːrθ/", vi: "Chắc hẳn các bạn đều biết voi là loài động vật có vú trên cạn có kích thước khổng lồ nhất. Nhiều người còn cho rằng, chỉ sau con người, loài voi là sinh vật thông minh bậc nhất trên Trái Đất." },
      { "start": 17.0, "en": "In some ways, they are just like us: they live in groups to be about the same age as a human. The oldest elephant was 82 years old.", "ipa": "/ɪn sʌm weɪz, ðeɪ ɑːr dʒʌst laɪk ʌs: ðeɪ lɪv ɪn ɡruːps tuː biː əˈbaʊt ðə seɪm eɪdʒ æz a ˈhjuːmən. ði ˈoʊldɪst ˈɛlɪfənt wɒz ˈeɪti-tuː jɪərz oʊld/", vi: "Ở nhiều khía cạnh, chúng rất giống chúng ta: sống theo bầy đàn gắn kết và có tuổi thọ tiệm cận con người. Con voi già nhất từng được ghi nhận sống đến 82 tuổi." },
      { "start": 29.0, "en": "Just how big can elephants get? Well, there was once a male elephant that weighed 11,000 kilograms. That's as much as ten cars!", "ipa": "/dʒʌst haʊ bɪɡ kæn ˈɛlɪfənts ɡɛt? wɛl, ðɛr wɒz wʌns a meɪl ˈɛlɪfənt ðæt weɪd ɪˈlɛvn ˈθaʊznd ˈkɪləˌɡræmz. ðæts æz mʌtʃ æz tɛn kɑːrz/", vi: "Vậy loài voi có thể đạt kích thước khủng khiếp đến mức nào? Chà, đã từng có một chú voi đực nặng tới 11.000 kg — tương đương với trọng lượng của mười chiếc ô tô gộp lại!" },
      { "start": 41.0, "en": "Elephants have been known to knock down trees and carry them out of forests. There are even reports of elephants pushing trains off railway tracks.", "ipa": "/ˈɛlɪfənts hæv biːn noʊn tuː nɒk daʊn triːz ænd ˈkæri ðɛm aʊt əv ˈfɔːrɪsts. ðɛr ɑːr ˈiːvn rɪˈpɔːrts əv ˈɛlɪfənts ˈpʊʃɪŋ treɪnz ɔːf ˈreɪlˌweɪ træks/", vi: "Người ta từng chứng kiến voi rừng húc đổ cả cây lớn và dùng vòi nhấc bổng chúng ra khỏi rừng. Thậm chí còn có những ghi nhận hy hữu về việc voi đẩy lật cả tàu hỏa văng khỏi đường ray." },
      { "start": 55.0, "en": "But for all their size and strength, elephants can be very gentle. And any creature that's as big as a house deserves respect!", "ipa": "/bʌt fɔːr ɔːl ðɛr saɪz ænd strɛŋθ, ˈɛlɪfənts kæn biː ˈvɛri ˈdʒɛntl. ænd ˈɛni ˈkriːtʃər ðæts æz bɪɡ ænd a haʊs dɪˈzɜːrvz rɪˈspɛkt/", vi: "Thế nhưng bất chấp vóc dáng khổng lồ và sức mạnh vô địch ấy, loài voi lại vô cùng hiền hòa và dịu dàng. Và bất kỳ sinh vật nào to lớn như một ngôi nhà mà lại thân thiện như thế đều hoàn toàn xứng đáng nhận được sự tôn trọng tuyệt đối!" }
    ]
  },
  {
    "day": 24,
    "title": "Protect Mom's Belly",
    image: "01 January/images/day_24.webp",
    audio: "01 January/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "Irene is four years old. She is very smart. She observes everything. Her mom is going to have a baby!", "ipa": "/aɪˈriːn ɪz fɔːr jɪərz oʊld. ʃiː ɪz ˈvɛri smɑːrt. ʃiː əbˈzɜːrvz ˈɛvriˌθɪŋ. hɜːr mɒm ɪz ˈɡoʊɪŋ tuː hæv a ˈbeɪbi/", vi: "Irene năm nay lên bốn tuổi. Bé cực kỳ thông minh và hay quan sát mọi thứ xung quanh. Có một tin lớn đây: Mẹ sắp sinh em bé!" },
      { "start": 15.0, "en": "One day, her mom asked her, 'Irene, do you want a baby sister? You are too lonely.' 'No!' Irene replied.", "ipa": "/wʌn deɪ, hɜːr mɒm ɑːskt hɜːr, 'aɪˈriːn, duː juː wɒnt a ˈbeɪbi ˈsɪstər? juː ɑːr tuː ˈloʊnli.' 'noʊ!' aɪˈriːn rɪˈplaɪd/", vi: "Một hôm, mẹ hỏi bé: 'Irene này, con có muốn có một cô em gái không? Con ở một mình buồn lắm phải không?' 'Không ạ!' Irene kiên quyết đáp." },
      { "start": 25.0, "en": "'How about a baby brother?' Mom asked. 'No!' Irene replied again.", "ipa": "/haʊ əˈbaʊt a ˈbeɪbi ˈbrʌðər?' mɒm ɑːskt. 'noʊ!' aɪˈriːn rɪˈplaɪd əˈɡɛn/", vi: "'Thế còn một cậu em trai thì sao?' mẹ gặng hỏi. 'Không luôn ạ!' Irene lại lắc đầu nguầy nguậy." },
      { "start": 33.0, "en": "'Why? Wouldn't you like to have a sister or brother to play with?' Mom asked again.", "ipa": "/'waɪ? ˈwʊdnt juː laɪk tuː hæv a ˈsɪstər ɔːr ˈbrʌðər tuː pleɪ wɪð?' mɒm ɑːsks əˈɡɛn/", vi: "'Tại sao thế con? Không lẽ con không thích có anh chị em để cùng chơi đùa hay sao?' mẹ ngạc nhiên hỏi lại." },
      { "start": 41.0, "en": "'I would want to play with my sister or brother! But I just wouldn't want your belly to explode. You will feel so much pain! It's getting so big and round,' Irene said.", "ipa": "/aɪ wɒd wɒnt tuː pleɪ wɪð maɪ ˈsɪstər ɔːr ˈbrʌðər! bʌt aɪ dʒʌst ˈwʊdnt wɒnt jɔːr ˈbɛli tuː ɪkˈsploʊd. juː wɪl fiːl soʊ mʌtʃ peɪn! ɪts ˈɡɛtɪŋ soʊ bɪɡ ænd raʊnd, aɪˈriːn sɛd/", vi: "'Con rất muốn có em chơi cùng chứ bộ! Nhưng con chỉ sợ bụng mẹ bị nổ tung mất thôi. Mẹ sẽ đau đớn lắm đấy! Nhìn bụng mẹ cứ ngày một to tròn vo kìa,' cô bé lo lắng thổ lộ." },
      { "start": 58.0, "en": "Mom laughed, 'Don't worry. My belly won't explode.' 'Why don't we ask Dad to give birth to the baby? He is big and strong,' Irene asked.", "ipa": "/mɒm lɑːft, 'doʊnt ˈwʌri. maɪ ˈbɛli woʊnt ɪkˈsploʊd.' 'waɪ doʊnt wiː ɑːsk dæd tuː ɡɪv bɜːrθ tuː ðə ˈbeɪbi? hiː ɪz bɪɡ ænd strɒŋ,' aɪˈriːn ɑːskt/", vi: "Mẹ bật cười ôm lấy con: 'Đừng lo con yêu, bụng mẹ không nổ tung được đâu.' 'Thế sao chúng ta không nhờ bố sinh em bé hộ đi ạ? Bố vừa to con lại vừa khỏe mạnh cơ mà,' Irene ngây thơ đề xuất." },
      { "start": 70.0, "en": "Dad started laughing too. 'I'm a man and men can't do that.'", "ipa": "/dæd ˈstɑːrtɪd ˈlɑːfɪŋ tuː. 'aɪm a mæn ænd mɛn kænt duː ðæt.'/", vi: "Bố đứng cạnh nghe thấy thế cũng phì cười to: 'Bố là đàn ông con trai, mà đàn ông thì không thể sinh em bé được con ạ.'" }
    ]
  },
  {
    "day": 25,
    "title": "How Old Are You?",
    image: "01 January/images/day_25.webp",
    audio: "01 January/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, some friends were talking. They were talking about how old they were.", "ipa": "/wʌn deɪ, sʌm frɛndz wɜːr ˈtɔːkɪŋ. ðeɪ wɜːr ˈtɔːkɪŋ əˈbaʊt haʊ oʊld ðeɪ wɜːr/", vi: "Một ngày nọ, một nhóm bạn nhỏ tụm năm tụm ba trò chuyện rôm rả với nhau về số tuổi của mỗi người." },
      { "start": 12.0, "en": "James said, 'I am seven years old. My brother is older. He is twice as old as me. How old is my brother?'", "ipa": "/dʒeɪmz sɛd, 'aɪ æm ˈsɛvn jɪərz oʊld. maɪ ˈbrʌðər ɪz ˈoʊldər. hiː ɪz twaɪs æz oʊld æz miː. haʊ oʊld ɪz maɪ ˈbrʌðər?'/", vi: "James khoe: 'Tớ năm nay bảy tuổi. Anh trai tớ lớn hơn tớ, tuổi của anh ấy gấp đôi tuổi tớ. Đố các cậu anh tớ bao nhiêu tuổi?'" },
      { "start": 23.0, "en": "'That's easy,' said Ellen. 'You are seven. He is twice as old as you. So, your brother is seven plus seven. He is fourteen years old.'", "ipa": "/ðæts ˈiːzi, sɛd ˈɛlən. 'juː ɑːr ˈsɛvn. hiː ɪz twaɪs æz oʊld æz juː. soʊ, jɔːr ˈbrʌðər ɪz ˈsɛvn plʌs ˈsɛvn. hiː ɪz fɔːrˈtiːn jɪərz oʊld.'/", vi: "'Dễ ợt,' Ellen đáp ngay. 'Cậu bảy tuổi, anh gấp đôi tuổi cậu, tức là lấy bảy cộng bảy. Vậy anh trai cậu mười bốn tuổi.'" },
      { "start": 35.0, "en": "Then Jane said, 'I am eight. I have a baby sister. She is half my age. How old is my sister?'", "ipa": "/ðɛn dʒeɪn sɛd, 'aɪ æm eɪt. aɪ hæv a ˈbeɪbi ˈsɪstər. ʃiː ɪz hæf maɪ eɪdʒ. haʊ oʊld ɪz maɪ ˈsɪstər?'/", vi: "Tiếp đó Jane đố tiếp: 'Tớ tám tuổi và có một cô em gái nhỏ. Tuổi của em ấy bằng một nửa tuổi tớ. Đố biết em tớ mấy tuổi?'" },
      { "start": 44.0, "en": "'That's so easy!' yelled James. 'She is half of eight. So, your sister is four years old.'", "ipa": "/ðæts soʊ ˈiːzi! jɛld dʒeɪmz. 'ʃiː ɪz hæf əv eɪt. soʊ, jɔːr ˈsɪstər ɪz fɔːr jɪərz oʊld.'/", vi: "'Quá dễ luôn!' James reo lên. 'Một nửa của tám chính là bốn. Em gái cậu bốn tuổi chứ mấy.'" },
      { "start": 54.0, "en": "Chris was thinking hard. There was something on his mind. Then, he asked, 'How old is a dinosaur?' 'A dinosaur?!' said the puzzled children.", "ipa": "/krɪs wɒz ˈθɪŋkɪŋ hɑːrd. ðɛr wɒz ˈsʌmθɪŋ ɒn hɪz maɪnd. ðɛn, hiː ɑːskt, 'haʊ oʊld ɪz a ˈdaɪnəˌsɔːr?' 'a ˈdaɪnəˌsɔːr?!' sɛd ðə ˈpʌzld ˈtʃɪldrən/", vi: "Lúc đó Chris đang trầm ngâm suy nghĩ đăm chiêu. Cậu chợt cất giọng hỏi: 'Thế đố các cậu khủng long thì bao nhiêu tuổi?' 'Khủng long ư?!' đám trẻ ngơ ngác đồng thanh thốt lên." },
      { "start": 69.0, "en": "'Yes, how old is a dinosaur?' said Chris again. The children thought really hard. 'A dinosaur is old, very old,' said Ellen. 'A dinosaur is millions of years old. A dinosaur is old, old, old!'", "ipa": "/jɛs, haʊ oʊld ɪz a ˈdaɪnəˌsɔːr? sɛd krɪs əˈɡɛn. ðə ˈtʃɪldrən θɔːt ˈrɪəli hɑːrd. 'a ˈdaɪnəˌsɔːr ɪz oʊld, ˈvɛri oʊld,' sɛd ˈɛlən. 'a ˈdaɪnəˌsɔːr ɪz ˈmɪljənz əv jɪərz oʊld. a ˈdaɪnəˌsɔːr ɪz oʊld, oʊld, oʊld!'/", vi: "'Đúng vậy, khủng long thọ bao nhiêu tuổi?' Chris kiên trì hỏi lại. Cả bọn vắt óc suy nghĩ thật kỹ. 'Khủng long rất, rất là già,' Ellen quả quyết. 'Chúng sống từ hàng triệu năm trước cơ. Khủng long là cụ của các cụ cổ xưa luôn ấy chứ!'" },
      { "start": 86.0, "en": "The children laughed. James said, 'A dinosaur is older than all of us combined!'", "ipa": "/ðə ˈtʃɪldrən lɑːft. dʒeɪmz sɛd, 'a ˈdaɪnəˌsɔːr ɪz ˈoʊldər ðæn ɔːl əv ʌs kəmˈbaɪnd!'/", vi: "Cả bọn được một trận cười bể bụng. James kết luận: 'Tuổi của khủng long chắc chắn còn già hơn tổng số tuổi của tất cả chúng mình cộng lại ấy chứ!'" }
    ]
  },
  {
    "day": 26,
    "title": "Molly Can't Fall Asleep",
    image: "01 January/images/day_26.webp",
    audio: "01 January/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "Little Molly goes to bed, but she cannot fall asleep. She sits up. She lies down again. Still, she cannot sleep. It is not fun at all. Molly wants to sleep. What can she do?", "ipa": "/ˈlɪtl ˈmɑːli ɡoʊz tuː bɛd, bʌt ʃiː ˈkænɒt fɔːl əˈsliːp. ʃiː sɪts ʌp. ʃiː laɪz daʊn əˈɡɛn. stɪl, ʃiː ˈkænɒt sliːp. ɪt ɪz nɒt fʌn æt ɔːl. ˈmɑːli wɒnts tuː sliːp. wɒt kæn ʃiː duː/", vi: "Bé Molly đã lên giường đi ngủ từ lâu nhưng mãi vẫn không tài nào chợp mắt được. Cúc ngồi dậy rồi lại nằm ngửa ra. Loay hoay đủ mọi cách mà giấc ngủ vẫn chẳng chịu đến, thật chán ngắt hết sức. Molly thèm ngủ quá rồi, phải làm sao bây giờ?" },
      { "start": 21.0, "en": "Mommy teaches Molly a trick. It will help her fall asleep. It is fun and easy. What is it? Counting sheep! Close your eyes and try it.", "ipa": "/ˈmɑːmi ˈtiːtʃɪz ˈmɑːli a trɪk. ɪt wɪl hɛlp hɜːr fɔːl əˈsliːp. ɪt ɪz fʌn ænd ˈiːzi. wɒt ɪz ɪt? ˈkaʊntɪŋ ʃiːp! kloʊz jɔːr aɪz ænd traɪ ɪt/", vi: "Thấy vậy, mẹ liền chỉ cho Molly một mẹo cực kỳ hay ho giúp dễ chợp mắt, vừa vui lại vừa dễ làm. Đố các cậu là gì nào? Đó chính là đếm cừu! Nào, nhắm mắt lại và thử xem sao nhé." },
      { "start": 36.0, "en": "Imagine a small wall—not too high and not too low—just right for sheep to jump over. Now imagine a flock of sheep. How many are there? Let's count them. Count the sheep as they jump over the wall.", "ipa": "/ɪˈmædʒɪn a smɔːl wɔːl—nɒt tuː haɪ ænd nɒt tuː loʊ—dʒʌst raɪt fɔːr ʃiːp tuː dʒʌmp ˈoʊvər. naʊ ɪˈmædʒɪn a flɒk əv ʃiːp. haʊ ˈmɛni ɑːr ðɛr? lɛts kaʊnt ðɛm. kaʊnt ðə ʃiːp ænd ðeɪ dʒʌmp ˈoʊvər ðə wɔːl/", vi: "Hãy tưởng tượng ra một bức tường nhỏ thấp vừa tầm — không quá cao cũng chẳng quá thấp — đúng chuẩn để những chú cừu có thể tung mình nhảy qua. Giờ hãy mường tượng ra một đàn cừu đông đúc. Có bao nhiêu con nhỉ? Nào chúng ta cùng đếm nhé, đếm từng chú cừu một khi chúng phóng qua bức tường." },
      { "start": 54.0, "en": "One sheep, two sheep, three sheep, four... Molly begins to count the sheep. Ten, eleven, twelve... Keep your eyes closed. Keep counting, Molly. Watch the sheep and count.", "ipa": "/wʌn ʃiːp, tuː ʃiːp, θriː ʃiːp, fɔːr... ˈmɑːli bɪˈɡɪnz tuː kaʊnt ðə ʃiːp. tɛn, ɪˈlɛvn, twɛlv... kiːp jɔːr aɪz cloʊzd. kiːp ˈkaʊntɪŋ, ˈmɑːli. wɒtʃ ðə ʃiːp ænd kaʊnt/", vi: "Một con cừu, hai con cừu, ba con cừu, bốn con... Molly bắt đầu lẩm nhẩm đếm. Mười, mười một, mười hai... Cứ nhắm chặt mắt vào con nhé, tiếp tục đếm đi Molly. Hướng ánh nhìn theo những chú cừu và đều đặn đếm." },
      { "start": 72.0, "en": "One hundred, one hundred and one, one hundred and two... Count, count, count. What's that sound? It's the sound of Molly sleeping.", "ipa": "/wʌn ˈhʌndrəd, wʌn ˈhʌndrəd ænd wʌn, wʌn ˈhʌndrəd ænd tuː... kaʊnt, kaʊnt, kaʊnt. wɒts ðæt saʊnd? ɪts ðə saʊnd əv ˈmɑːli ˈsliːpɪŋ/", vi: "Một trăm, một trăm linh một, một trăm linh hai... Đếm, đếm, đếm. Âm thanh gì đang phát ra thế kia nhỉ? À, hóa ra đó chính là tiếng thở đều nhè nhẹ của Molly lúc đang ngủ say sưa rồi đấy." }
    ]
  },
  {
    "day": 27,
    "title": "Working with Dad",
    image: "01 January/images/day_27.webp",
    audio: "01 January/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "One Saturday morning, my dad got me up early and said to me, 'Can you help me in the workshop today?'", "ipa": "/wʌn ˈsætərdeɪ ˈmɔːrnɪŋ, maɪ dæd ɡɒt miː ʌp ˈɜːrli ænd sɛd tuː miː, 'kæn juː hɛlp miː ɪn ðə ˈwɜːrkˌʃɒp təːdeɪ?'/", vi: "Vào một buổi sáng thứ Bảy, bố đánh thức tôi dậy từ rất sớm và ân cần hỏi: 'Hôm nay con có thể vào xưởng mộc phụ giúp bố một tay được không?'" },
      { "start": 16.0, "en": "'Sure!' I said. I was always willing to help Dad in his workshop. But he never asked me. I thought it was because I am a girl. But today was different. He actually asked for my help!", "ipa": "/ʃʊr! aɪ sɛd. aɪ wɒz ˈɔːlweɪz ˈwɪlɪŋ tuː hɛlp dæd ɪn hɪz ˈwɜːrkˌʃɒp. bʌt hiː ˈnɛvər ɑːskt miː. aɪ θɔːt ɪt wɒz bɪˈkəz aɪ æm a ɡɜːrl. bʌt təˈdeɪ wɒz ˈdɪfrənt. hiː ˈæktʃuəli ɑːskt fɔːr maɪ hɛlp/", vi: "'Dạ chắc chắn rồi ạ!' tôi vui mừng đáp ngay. Tôi vẫn luôn ao ước được phụ giúp bố trong xưởng, ngặt nỗi chưa bao giờ bố mở lời. Tôi cứ ngỡ vì mình là con gái nên bố không cho làm. Nhưng hôm nay thật khác lạ, bố đã chủ động nhờ cậy tôi!" },
      { "start": 36.0, "en": "My dad had a drawing of his plans. We followed the plans and cut some wood. Soon, all the pieces were the right size and length.", "ipa": "/maɪ dæd hæd a ˈdrɔːɪŋ əv hɪz plænz. wiː ˈfɒloʊd ðə plænz ænd kʌt sʌm wʊd. suːn, ɔːl ðə piːsɪz wɜːr ðə raɪt saɪz ænd lɛŋθ/", vi: "Bố trải bản vẽ thiết kế chi tiết ra. Hai bố con cùng nhau nghiên cứu bản vẽ rồi cẩn thận cưa cắt những thanh gỗ. Chẳng mấy chốc, các mảnh ghép đều đạt chuẩn kích thước và chiều dài chính xác." },
      { "start": 50.0, "en": "We started to put the pieces together. It was a chair! We glued the pieces and used big clamps to hold them in place while the glue dried.", "ipa": "/wiː ˈstɑːrtɪd tuː pʊt ðə piːsɪz təˈɡɛðər. ɪt wɒz a tʃɛr! wiː ɡluːd ðə piːsɪz ænd juːzd bɪɡ klæmps tuː hoʊld ðɛm ɪn pleɪs waɪl ðə ɡluː draɪd/", vi: "Chúng tôi bắt đầu ráp các bộ phận lại với nhau. Ồ, hóa ra đó là một chiếc ghế bành! Hai bố con bôi keo dán các khớp nối và dùng những chiếc ê-tô kẹp lớn giữ chặt cố định trong lúc chờ keo khô hẳn." },
      { "start": 67.0, "en": "The next day, we went downstairs. 'Go ahead,' my dad said. I sat down. It didn't fall apart!", "ipa": "/ðə nɛkst deɪ, wiː wɛnt ˈdaʊnˌstɛərz. ɡoʊ əˈhɛd, maɪ dæd sɛd. aɪ sæt daʊn. ɪt ˈdɪdnt fɔːl əˈpɑːrt/", vi: "Hôm sau, hai bố con xuống nhà dưới. 'Con ngồi thử xem nào,' bố mỉm cười khuyến khích. Tôi rụt rè ngồi lên ghế. Thật tuyệt vời, chiếc ghế vững chắc chẳng hề suy suyển hay rơi rụng mảnh nào!" },
      { "start": 78.0, "en": "I hope I will have a daughter one day. I will teach her how to make her own chair too.", "ipa": "/aɪ hoʊp aɪ wɪl hæv a ˈdɔːtər wʌn deɪ. aɪ wɪl tiːtʃ hɜːr haʊ tuː meɪk hɜːr oʊn tʃɛr tuː/", vi: "Tôi thầm ước sau này khi sinh con gái, tôi cũng sẽ truyền ngọn lửa đam mê và tự tay dạy con bé cách đóng một chiếc ghế của riêng mình như thế." }
    ]
  },
  {
    "day": 28,
    "title": "What to Be",
    image: "01 January/images/day_28.webp",
    audio: "01 January/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "Our teacher asked us to write a paper. 'I want everyone to write a paper for me,' said the teacher. 'In the paper, tell me what you want to be when you grow up.'", "ipa": "/ˈaʊər ˈtiːtʃər ɑːskt ʌs tuː raɪt a ˈpeɪpər. aɪ wɒnt ˈɛvriˌwʌn tuː raɪt a ˈpeɪpər fɔːr miː, sɛd ðə ˈtiːtʃər. ɪn ðə ˈpeɪpər, tɛl miː wɒt juː wɒnt tuː biː wɛn juː ɡroʊ ʌp/", vi: "Cô giáo giao cho lớp một bài tập viết văn ngắn. 'Cô muốn tất cả các em đều phải hoàn thành bài viết này cho cô,' cô căn dặn. 'Trong bài, hãy bày tỏ ước mơ sau này lớn lên các em muốn trở thành người như thế nào.'" },
      { "start": 20.0, "en": "'I want to work in a store and sell things,' said Bill. 'I want to coach a baseball team,' cried Sam.", "ipa": "/aɪ wɒnt tuː wɜːrk ɪn a stɔːr ænd sɛl θɪŋz, sɛd bɪl. aɪ wɒnt tuː koʊtʃ a ˈbeɪsˌbɔːl tiːm, kraɪd sæm/", vi: "'Tớ thích được làm việc trong cửa hàng và bán hàng,' Bill hào hứng phát biểu. 'Còn tớ ước mơ làm huấn luyện viên đội bóng chày,' Sam reo lên." },
      { "start": 31.0, "en": "'I want to be a writer and write books for people to read,' said Cheryl. 'I want to be a fireman,' said Gerry. 'And maybe a policeman too.'", "ipa": "/aɪ wɒnt tuː biː a ˈraɪtər ænd raɪt bʊks fɔːr ˈpiːpl tuː riːd, sɛd ˈʃɛrəl. aɪ wɒnt tuː biː a ˈfaɪərˌmæn, sɛd ˈdʒɛri. ænd ˈmeɪbi a pəˈliːsmən tuː/", vi: "'Tớ muốn làm nhà văn để sáng tác những cuốn sách hay cho mọi người đọc,' Cheryl chia sẻ. 'Tớ muốn làm lính cứu hỏa,' Gerry tiếp lời. 'Và có lẽ cả cảnh sát nữa.'" },
      { "start": 46.0, "en": "All of the children were excited—all except Joey. 'I can't make up my mind,' he said. 'I want to be a lot of different things.'", "ipa": "/ɔːl əv ðə ˈtʃɪldrən wɜːr ɪkˈsaɪtɪd—ɔːl ɪkˈsɛpt ˈdʒoʊi. aɪ kænt meɪk ʌp maɪ maɪnd, hiː sɛd. aɪ wɒnt tuː biː a lɒt əv ˈdɪfrənt θɪŋz/", vi: "Đứa trẻ nào cũng hào hứng phấn khởi bàn tán sôi nổi — ngoại trừ duy nhất Joey. 'Tớ vẫn chưa quyết định được,' cậu bé ỉu xìu nói. 'Tớ muốn làm vô số ngành nghề khác nhau cơ.'" },
      { "start": 60.0, "en": "The teacher smiled. 'Then that's what you should write,' she told him. 'Write about all the things you want to be. One day, you'll know which one to choose. For right now, wanting to be a lot of things is just right.'", "ipa": "/ðə ˈtiːtʃər smaɪld. ðɛn ðæts wɒt juː ʃʊd raɪt, ʃiː toʊld hɪm. raɪt əˈbaʊt ɔːl ðə θɪŋz juː wɒnt tuː biː. wʌn deɪ, juːl noʊ wɪtʃ wʌn tuː tʃuːz. fɔːr raɪt naʊ, ˈwɒntɪŋ tuː biː a lɒt əv θɪŋz ɪz dʒʌst raɪt/", vi: "Cô giáo hiền hậu mỉm cười: 'Thế thì em cứ viết chính xác điều đó vào bài đi. Hãy viết về tất cả những ước mơ mà em muốn hướng tới. Sẽ có một ngày em tìm ra đáp án thực sự cho riêng mình. Còn hiện tại bây giờ, việc ôm ấp nhiều hoài bão là hoàn toàn tuyệt vời.'" }
    ]
  },
  {
    "day": 29,
    "title": "Big Green Ball",
    image: "01 January/images/day_29.webp",
    audio: "01 January/audio/Track29.mp3",
    "sentences": [
      { "start": 4.8, "en": "Sean had a new green ball—the best ball in the world! He took the ball into the garden. He rolled, bounced and kicked it. It was a great ball!", "ipa": "/ʃɔːn hæd a nuː ɡriːn bɔːl—ðə bɛst bɔːl ɪn ðə wɜːrld! hiː tʊk ðə bɔːl ˈɪntuː ðə ˈɡɑːrdn. hiː roʊld, baʊnst ænd kɪkt ɪt. ɪt wɒz a ɡreɪt bɔːl/", vi: "Sean vừa có được một quả bóng màu xanh lá cây mới tinh — quả bóng tuyệt vời nhất trên đời! Cậu mang quả bóng ra góc vườn, lăn qua lăn lại, nhồi bóng rồi sút tung tăng. Quả bóng thích thật đấy!" },
      { "start": 18.0, "en": "His little brother Sam wanted the ball too. 'No!' said Sean. 'It's my ball! ALL MINE!'", "ipa": "/hɪz ˈlɪtl ˈbrʌðər sæm ˈwɒntɪd ðə bɔːl tuː. noʊ! sɛd ʃɔːn. ɪts maɪ bɔːl! ɔːl maɪn/", vi: "Cậu em trai nhỏ Sam cũng lân la muốn được chơi cùng. 'Không đời nào!' Sean quát lên ích kỷ. 'Quả bóng của tớ cơ mà! CỦA RIÊNG TỚ HẾT!'" },
      { "start": 28.0, "en": "Sean kicked the ball hard. It flew high, high in the sky and over the fence!", "ipa": "/ʃɔːn kɪkt ðə bɔːl hɑːrd. ɪt fluː haɪ, haɪ ɪn ðə skaɪ ænd ˈoʊvər ðə fɛns/", vi: "Vì muốn tranh chấp, Sean tung một cú sút cực mạnh. Quả bóng bay vút lên tận tầng không trung cao tít và rơi qua tận bên kia hàng rào!" },
      { "start": 37.0, "en": "The fence was very tall, much taller than Sean. There was also a hole in the fence. It was much smaller than Sean.", "ipa": "/ðə fɛns wɒz ˈvɛri tɔːl, mʌtʃ ˈtɔːlər ðæn ʃɔːn. ðɛr wɒz ˈɔːlsoʊ a hoʊl ɪn ðə fɛns. ɪt wɒz mʌtʃ ˈsmɔːlər ðæn ʃɔːn/", vi: "Hàng rào vườn nhà hàng xóm rất cao, vượt quá tầm với của Sean. Dưới chân rào có một cái lỗ thủng nhỏ, nhưng kích thước lại quá bé so với vóc dáng của cậu." },
      { "start": 47.0, "en": "Sean started to cry because he couldn't get his ball back. But, Sam was small. He said, 'Let me go get it.'", "ipa": "/ʃɔːn ˈstɑːrtɪd tuː kraɪ bɪˈkəz hiː ˈkʊdnt ɡɛt hɪz bɔːl bæk. bʌt, sæm wɒz smɔːl. hiː sɛd, 'lɛt miː ɡoʊ ɡɛt ɪt.'/", vi: "Sean òa khóc nức nở vì bất lực chẳng tài nào lấy lại được quả bóng cưng. Nhìn thấy vậy, cậu em trai Sam nhỏ con liền lanh lợi bảo: 'Để em bò qua lấy cho.'" },
      { "start": 58.0, "en": "He crawled through the hole and reached for the ball. Then he came back. 'Here is your ball, Sean!' he exclaimed.", "ipa": "/hiː krɔːld θruː ðə hoʊl ænd riːtʃt fɔːr ðə bɔːl. ðɛn hiː keɪm bæk. 'hɪər ɪz jɔːr bɔːl, ʃɔːn!' hiː ɪkˈskleɪmd/", vi: "Cậu bé luồn người chui qua khe hở nhỏ, với tay nhặt lấy quả bóng rồi nhanh nhẹn bò quay trở lại. 'Quả bóng của anh đây nhé, Sean!' em hớn hở khoe." },
      { "start": 69.0, "en": "Sean looked at Sam and smiled. 'No, it's OUR ball!'", "ipa": "/ʃɔːn lʊkt æt sæm ænd smaɪld. 'noʊ, ɪts ˈaʊər bɔːl!'/", vi: "Sean nhìn em trai, mỉm cười hối lỗi: 'Không, phải là quả bóng CỦA CHÚNG TA chứ!'" }
    ]
  },
  {
    "day": 30,
    "title": "Kenny's Adventure",
    image: "01 January/images/day_30.webp",
    audio: "01 January/audio/Track30.mp3",
    "sentences": [
      { "start": 4.8, "en": "Kenny was going on an adventure. Where was he going? He was going to the grocery store!", "ipa": "/ˈkɛni wɒz ˈɡoʊɪŋ ɒn ən ədˈvɛntʃər. wɛr wɒz hiː ˈɡoʊɪŋ? hiː wɒz ˈɡoʊɪŋ tuː ðə ˈɡroʊsəri stɔːr/", vi: "Kenny sắp sửa dấn thân vào một cuộc phiêu lưu thực sự. Cậu chuẩn bị đi đâu thế nhỉ? Hóa ra cậu chuẩn bị đi đến cửa hàng tạp hóa gần nhà!" },
      { "start": 14.0, "en": "He was going to get some groceries, all by himself. Kenny's mom gave him a list and some money.", "ipa": "/hiː wɒz ˈɡoʊɪŋ tuː ɡɛt sʌm ˈɡroʊsəriz, ɔːl baɪ hɪmˈsɛlf. ˈkɛniz mɒm ɡeɪv hɪm a lɪst ænd sʌm ˈmʌni/", vi: "Cậu bé sẽ tự mình đi mua ít đồ tạp hóa một mình mà không có người lớn đi cùng. Mẹ đã đưa cho Kenny một tờ danh sách ghi các món cần mua cùng một ít tiền mặt." },
      { "start": 23.0, "en": "'You need to get bread, milk and butter,' she told him. 'And be sure to use the crosswalk and to look both ways when crossing the street.'", "ipa": "/'juː niːd tuː ɡɛt brɛd, mɪlk ænd ˈbʌtər,' ʃiː toʊld hɪm. 'ænd biː ʃʊr tuː juːz ðə ˈkrɔːsˌwɔːk ænd tuː lʊk boʊθ weɪz wɛn ˈkrɒsɪŋ ðə striːt.'/", vi: "'Con cần mua bánh mì, sữa và bơ nhé,' mẹ dặn dò. 'Và nhớ phải đi đúng vạch qua đường dành cho người đi bộ, quan sát kỹ cả hai hướng trái phải trước khi sang đường đấy.'" },
      { start: 38.0, "en": "Kenny walked to the crosswalk. He looked both ways carefully. Then, he looked again, just to be sure there were no cars coming. Finally, he crossed the street and went into the store.", "ipa": "/ˈkɛni wɔːkt tuː ðə ˈkrɔːsˌwɔːk. hiː lʊkt boʊθ weɪz ˈkɛrfəli. ðɛn, hiː lʊkt əˈɡɛn, dʒʌst tuː biː ʃʊr ðɛr wɜːr noʊ kɑːrz ˈkʌmɪŋ. ˈfaɪnəli, hiː krɒst ðə striːt ænd wɛnt ˈɪntuː ðə stɔːr/", vi: "Kenny rảo bước đến vạch sang đường. Cậu cẩn thận ngó nghiêng quan sát cả hai chiều rồi cẩn thận nhìn lại lần nữa cho chắc chắn không có ô tô nào đang lao tới. Cuối cùng, cậu bước qua đường an toàn và bước vào trong tiệm." },
      { start: 55.0, "en": "Kenny gave the grocery list to the clerk. 'I want bread, milk and butter,' he told the clerk. 'Here is the money.'", "ipa": "/ˈkɛni ɡeɪv ðə ˈɡroʊsəri lɪst tuː ðə klɜːrk. 'aɪ wɒnt brɛd, mɪlk ænd ˈbʌtər,' hiː toʊld ðə klɜːrk. 'hɪər ɪz ðə ˈmʌni.'/", vi: "Kenny đưa danh sách mua hàng cho nhân viên bán hàng. 'Cháu muốn mua bánh mì, sữa và bơ ạ,' cậu lễ phép nói và chìa tiền ra." },
      { start: 67.0, "en": "The clerk put the things in a bag and handed it to Kenny, with some change. Kenny was excited! He walked back safely and made his way home. He had had a wonderful adventure!", "ipa": "/ðə klɜːrk pʊt ðə θɪŋz ɪn a bæɡ ænd ˈhændɪd ɪt tuː ˈkɛni, wɪð sʌm tʃeɪndʒ. ˈkɛni wɒz ɪkˈsaɪtɪd! hiː wɔːkt bæk ˈseɪfli ænd meɪd hɪz weɪ hoʊm. hiː hæd hæd a ˈwʌndərfʊl ədˈvɛntʃər/", vi: "Cô nhân viên nhanh nhẹn cho đồ vào túi giấy rồi đưa lại cho Kenny kèm theo ít tiền thối lại. Kenny phấn khích tột độ! Cậu bé ôm túi đồ đi bộ an toàn trở về nhà. Quả là một chuyến phiêu lưu đầu đời tuyệt vời làm sao!" }
    ]
  },
  {
    "day": 31,
    "title": "Baby Brother",
    image: "01 January/images/day_31.webp",
    audio: "01 January/audio/Track31.mp3",
    "sentences": [
      { "start": 4.8, "en": "Little Mary lives in a big house with her parents. She is the only child in the family. She really wants to have a baby brother.", "ipa": "/ˈlɪtl ˈmɛri lɪvz ɪn a bɪɡ haʊs wɪð hɜːr ˈpɛrənts. ʃiː ɪz ði ˈoʊnli tʃaɪld ɪn ðə ˈfæməli. ʃiː ˈrɪəli wɒnts tuː hæv a ˈbeɪbi ˈbrʌðər/", vi: "Cô bé Mary nhỏ nhắn sống trong một ngôi nhà khổng lồ cùng bố mẹ. Vì là con một trong nhà nên lúc nào Mary cũng khao khát được có một cậu em trai." },
      { "start": 16.0, "en": "One day, when she comes home from school, Mom and Dad are waiting for her. 'We have some good news,' they say. 'You will have a baby brother soon.'", "ipa": "/wʌn deɪ, wɛn ʃiː kʌmz hoʊm frɒm skuːl, mɒm ænd dæd ɑːr ˈweɪtɪŋ fɔːr hɜːr. 'wiː hæv sʌm ɡʊd nuːz,' ðeɪ seɪ. 'juː wɪl hæv a ˈbeɪbi ˈbrʌðər suːn.'/", vi: "Một hôm tan học về nhà, Mary ngạc nhiên khi thấy bố mẹ đang đứng chờ sẵn ở phòng khách. 'Bố mẹ có tin vui muốn thông báo với con đây,' bố mẹ mỉm cười. 'Chẳng bao lâu nữa con sẽ có một cậu em trai.'" },
      { "start": 30.0, "en": "Mary is very, very happy. 'Is this true? When will he be here?' she asks. 'I can't wait for him.' Her father says, 'We will get him in two weeks.'", "ipa": "/ˈmɛri ɪz ˈvɛri, ˈvɛri ˈhæpi. 'ɪz ðɪs truː? wɛn wɪl hiː biː hɪər?' ʃiː ɑːsks. 'aɪ kænt wait fɔːr hɪm.' hɜːr ˈfɑːðər sɛd, 'wiː wɪl ɡɛt hɪm ɪn tuː wiːks.'/", vi: "Mary sung sướng tột độ, nhảy cẫng lên: 'Thật thế hả bố mẹ? Bao giờ em bé mới về nhà mình ạ? Con nôn nóng gặp em quá đi mất.' Bố xoa đầu con gái: 'Hai tuần nữa là chúng ta sẽ đón em về.'" },
      { "start": 44.0, "en": "'Two weeks?' asks Mary. 'Doesn't it take longer than that for a baby?' Mom smiles at Mary. 'We are going to adopt a baby boy,' she explains. 'That means that we are going to choose a baby who has no family. We will be his new family. We will take care of him.'", "ipa": "/'tuː wiːks?' ɑːsks ˈmɛri. 'ˈdʌznt ɪt teɪk ˈlɒŋɡər ðæn ðæt fɔːr a ˈbeɪbi?' mɒm smaɪlz ænd sɛd. 'wiː ɑːr ˈɡoʊɪŋ tuː əˈdɒpt a ˈbeɪbi bɔɪ,' ʃiː ɪkˈplɛɪnz. 'ðæt miːnz ðæt wiː ɑːr ˈɡoʊɪŋ tuː tʃuːz a ˈbeɪbi huː hæz noʊ ˈfæməli. wiː wɪl biː hɪz nuː ˈfæməli. wiː wɪl teɪk kɛər əv hɪm.'/", vi: "'Hai tuần thôi á?' Mary thắc mắc. 'Chẳng phải em bé trong bụng mẹ phải mất nhiều thời gian hơn thế mới sinh ra sao?' Mẹ dịu dàng mỉm cười giải thích: 'Bố mẹ sẽ nhận nuôi một bé trai mồ côi con ạ. Điều đó có nghĩa là gia đình mình sẽ đón một em bé chưa có người thân về làm con nuôi, và chúng ta sẽ trở thành mái ấm mới yêu thương, chăm sóc cho em.'" },
      { "start": 65.0, "en": "Mary is so excited. She will be a big sister in just two weeks!", "ipa": "/ˈmɛri ɪz soʊ ɪkˈsaɪtɪd. ʃiː wɪl biː a bɪɡ ˈsɪstər ɪn dʒʌst tuː wiːks/", vi: "Mary nghe xong vô cùng phấn khích và hạnh phúc. Chỉ vỏn vẹn hai tuần nữa thôi là cô bé sẽ chính thức trở thành một người chị lớn rồi!" }
    ]
  }
];