if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["06 June"] = [
  {
    "day": 1,
    "title": "Emma and the Hot Day",
    "image": "06 June/images/day_01.webp",
    "audio": "06 June/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was a very hot summer day. Emma was hot, but Grandma was hotter.", "ipa": "/ɪt wɒz ə ˈvɛri hɒt ˈsʌmər deɪ. ˈɛmə wɒz hɒt, bʌt ˈɡrænmɑː wɒz ˈhɒtər/", "vi": "Đó là một ngày hè vô cùng oi bức. Emma thấy nóng, nhưng bà ngoại còn thấy nóng hơn." },
      { "start": 13.0, "en": "Grandma sat on the cool porch, waving her fan. But she was no cooler.", "ipa": "/ˈɡrænmɑː sæt ɒn ðə kuːl pɔːrtʃ, ˈweɪvɪŋ hɜːr fæn. bʌt ʃiː wɒz noʊ ˈkuːlər/", "vi": "Bà ngồi ngoài hiên mát, phe phẩy chiếc quạt nan. Nhưng bà vẫn chẳng thấy mát hơn chút nào." },
      { "start": 21.0, "en": "Emma ran to the kitchen and climbed up to the sink. She turned on the faucet. The water was cold. Emma filled a big glass with water. She climbed down and got ice from the freezer. 'Plop! Plop!' The ice dropped into the glass. Now, the water was even colder!", "ipa": "/ˈɛmə ræn tuː ðə ˈkɪtʃɪn ænd klaɪmd ʌp tuː ðə sɪŋk. ʃiː tɜːrnd ɒn ðə ˈfɔːsɪt. ðə ˈwɔːtər wɒz koʊld. ˈɛmə fɪld ə bɪɡ ɡlɑːs wɪð ˈwɔːtər. ʃiː klaɪmd daʊn ænd ɡɒt aɪs frɒm ðə ˈfriːzər. plɒp! plɒp! ði aɪs drɒpt ˈɪntuː ðə ɡlɑːs. naʊ, ðə ˈwɔːtər wɒz ˈiːvn ˈkoʊldər!/", "vi": "Emma chạy vào bếp, trèo lên bồn rửa mở vòi nước lạnh ngắt rồi rót đầy một cốc to. Bé trèo xuống lấy đá trong ngăn đông thả 'Tõm! Tõm!' vào cốc. Bây giờ cốc nước còn mát lạnh hơn nữa!" },
      { "start": 44.0, "en": "Emma took the glass to Grandma, but the cat ran between her legs. Down fell Emma! Away ran the cat! Up flew the glass! And the water landed all over Grandma.", "ipa": "/ˈɛmə tʊk ðə ɡlɑːs tuː ˈɡrænmɑː, bʌt ðə kæt ræn bɪˈtwiːn hɜːr lɛɡz. daʊn fɛl ˈɛmə! əˈweɪ ræn ðə kæt! ʌp fluː ðə ɡlɑːs! ænd ðə ˈwɔːtər ˈlændɪd ɔːl ˈoʊvər ˈɡrænmɑː/", "vi": "Emma bưng cốc nước ra cho bà, nhưng chú mèo bỗng luồn qua hai chân bé. Emma ngã nhào! Mèo chạy biến! Cốc nước văng lên không trung và nước tạt ướt sũng người bà." },
      { "start": 57.0, "en": "Emma cried. She had wanted to help, but now, Grandma was all wet! Grandma smiled. 'Well, that certainly cooled me down! Don't worry Emma, the sun will dry me!'", "ipa": "/ˈɛmə kraɪd. ʃiː hæd ˈwɒntɪd tuː hɛlp, bʌt naʊ, ˈɡrænmɑː wɒz ɔːl wɛt! ˈɡrænmɑː smaɪld. wɛl, ðæt ˈsɜːrtnli kuːld miː daʊn! doʊnt ˈwʌri ˈɛmə, ðə sʌn wɪl draɪ miː!/", "vi": "Emma òa khóc vì muốn giúp bà mà lại làm bà ướt hết. Bà mỉm cười nói: 'Ồ, thế này thì mát thật rồi! Đừng lo Emma, nắng sẽ sấy khô áo bà ngay thôi!'" }
    ]
  },
  {
    "day": 2,
    "title": "Bob",
    "image": "06 June/images/day_02.webp",
    "audio": "06 June/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "Bob likes to play ball. He bounces his ball off the house and runs to catch it. Sometimes, he misses. But most of the time, he doesn't.", "ipa": "/bɒb laɪks tuː pleɪ bɔːl. hiː ˈbaʊnsɪz hɪz bɔːl ɔːf ðə haʊs ænd rʌnz tuː kætʃ ɪt. ˈsʌmˌtaɪmz, hiː ˈmɪsɪz. bʌt moʊst əv ðə taɪm, hiː ˈdʌznt/", "vi": "Bob rất thích chơi bóng. Cậu ném bóng đập vào tường nhà rồi chạy đón bắt. Thỉnh thoảng cậu bắt hụt, nhưng phần lớn thời gian cậu đều bắt trúng." },
      { "start": 16.0, "en": "Is there anything special about that? Yes. Bob is blind. He has a ball with a beeper in it. Bob explains to his best friend Tim, 'I listen for the beeper. This tells me which way to run to catch the ball.'", "ipa": "/ɪz ðɛər ˈɛniˌθɪŋ ˈspɛʃl əˈbaʊt ðæt? jɛs. bɒb ɪz blaɪnd. hiː hæz ə bɔːl wɪð ə ˈbiːpər ɪn ɪt. bɒb ɪkˈspleɪnz tuː hɪz bɛst frɛnd tɪm, aɪ ˈlɪsn fɔːr ðə ˈbiːpər. ðɪs tɛlz miː wɪtʃ weɪ tuː rʌn tuː kætʃ ðə bɔːl/", "vi": "Có điều gì đặc biệt không? Có đấy, Bob bị khiếm thị. Cậu có một quả bóng gắn còi phát tín hiệu. Bob giải thích với bạn thân Tim: 'Tớ lắng nghe tiếng bíp để biết hướng chạy đón bóng.'" },
      { "start": 36.0, "en": "Bob's books are written in Braille. He uses his fingertips to feel and read the writing.", "ipa": "/bɒbz bʊks ɑːr ˈrɪtn ɪn breɪl. hiː ˈjuːzɪz hɪz ˈfɪŋɡərtɪps tuː fiːl ænd riːd ðə ˈraɪtɪŋ/", "vi": "Sách của Bob được in bằng chữ nổi Braille. Cậu dùng đầu ngón tay chạm lướt để đọc từng con chữ." },
      { "start": 44.0, "en": "'When I grow up, I want to be a policeman,' says Bob. 'I want to be the dispatcher—the one who tells the other policemen where to go.' Tim likes his friend, for he never lets his blindness get in the way of his dreams.", "ipa": "/wɛn aɪ ɡroʊ ʌp, aɪ wɒnt tuː biː ə pəˈliːsmən, sɛz bɒb. aɪ wɒnt tuː biː ðə dɪˈspætʃər—ðə wʌn huː tɛlz ði ˈʌðər pəˈliːsmɛn wɛər tuː ɡoʊ. tɪm laɪks hɪz frɛnd, fɔːr hiː ˈnɛvər lɛts hɪz ˈblaɪndnɪs ɡɛt ɪn ðə weɪ əv hɪz driːmz/", "vi": "'Lớn lên tớ muốn làm cảnh sát,' Bob nói. 'Tớ muốn làm nhân viên trực tổng đài — người chỉ dẫn đồng đội vị trí làm nhiệm vụ.' Tim rất quý bạn, vì Bob không bao giờ để đôi mắt khiếm thị ngăn cản ước mơ." }
    ]
  },
  {
    "day": 3,
    "title": "My Story with Fog",
    "image": "06 June/images/day_03.webp",
    "audio": "06 June/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "What is fog? Fog is a cloud that is close to the ground. But do you know what fog can do to us?", "ipa": "/wɒt ɪz fɒɡ? fɒɡ ɪz ə klaʊd ðæt ɪz kloʊs tuː ðə ɡraʊnd. bʌt duː juː noʊ wɒt fɒɡ kæn duː tuː ʌs?/", "vi": "Sương mù là gì? Sương mù là một đám mây nằm sát mặt đất. Nhưng bạn có biết sương mù có thể gây ra chuyện gì không?" },
      { "start": 13.0, "en": "One day, my dad rented a small boat. He left shore. After sailing for a few hours, he suddenly ran into fog. It was like being in a cloud on the water.", "ipa": "/wʌn deɪ, maɪ dæd ˈrɛntɪd ə smɔːl boʊt. hiː lɛft ʃɔːr. ˈɑːftər ˈseɪlɪŋ fɔːr ə fjuː ˈaʊərz, hiː ˈsʌdənli ræn ˈɪntuː fɒɡ. ɪt wɒz laɪk ˈbiːɪŋ ɪn ə klaʊd ɒn ðə ˈwɔːtər/", "vi": "Một hôm, bố tôi thuê một chiếc thuyền nhỏ ra khơi. Lướt sóng được vài giờ, bố bất ngờ đâm vào màn sương mù dày đặc, hệt như đang ở giữa đám mây trên mặt nước." },
      { "start": 25.0, "en": "He could not see a thing. There was nothing he could do. He sat in the boat and waited for the fog to disappear. It got dark and cold.", "ipa": "/hiː kʊd nɒt siː ə θɪŋ. ðɛər wɒz ˈnʌθɪŋ hiː kʊd duː. hiː sæt ɪn ðə boʊt ænd ˈweɪtɪd fɔːr ðə fɒɡ tuː ˌdɪsəˈpɪər. ɪt ɡɒt dɑːrk ænd koʊld/", "vi": "Bố chẳng nhìn thấy được gì cả và hoàn toàn bất lực. Bố đành ngồi im trên thuyền chờ sương tan khi trời dần sụp tối và lạnh." },
      { "start": 38.0, "en": "Then he heard a loud horn. It was getting closer. Was it a big ship? Would the captain see him?", "ipa": "/ðɛn hiː hɜːrd ə laʊd hɔːrn. ɪt wɒz ˈɡɛtɪŋ ˈkloʊsər. wɒz ɪt ə bɪɡ ʃɪp? wʊd ðə ˈkæptɪn siː hɪm?/", "vi": "Bỗng nhiên bố nghe thấy tiếng còi hú vang rền mỗi lúc một gần. Đó có phải là một con tàu lớn không? Liệu thuyền trưởng có nhìn thấy bố không?" },
      { "start": 48.0, "en": "BANG! He ran into a small island. The island had a fog horn on it! He stayed on the island until morning, and then he sailed home. Isn't fog a powerful thing?", "ipa": "/bæŋ! hiː ræn ˈɪntuː ə smɔːl ˈaɪlənd. ði ˈaɪlənd hæd ə fɒɡ hɔːrn ɒn ɪt! hiː steɪd ɒn ði ˈaɪlənd ənˈtɪl ˈmɔːrnɪŋ, ænd ðɛn hiː seɪld hoʊm. ˈɪznt fɒɡ ə ˈpaʊərfʊl θɪŋ?/", "vi": "RẦM! Thuyền va vào một hòn đảo nhỏ — nơi đặt chiếc còi báo hiệu sương mù! Bố nán lại trên đảo đến sáng hôm sau rồi lái thuyền về nhà. Sương mù quả là đáng gờm đúng không?" }
    ]
  },
  {
    "day": 4,
    "title": "A Boy Learns",
    "image": "06 June/images/day_04.webp",
    "audio": "06 June/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "Jose is a teenage boy. He used to do well in school. But lately, things changed. He started skipping class. Soon, his parents got a phone call from the school.", "ipa": "/hoʊˈzeɪ ɪz ə ˈtiːnˌeɪdʒ bɔɪ. hiː juːzd tuː duː wɛl ɪn skuːl. bʌt ˈleɪtli, θɪŋz tʃeɪndʒd. hiː ˈstɑːrtɪd ˈskɪpɪŋ klɑːs. suːn, hɪz ˈpeərənts ɡɒt ə foʊn kɔːl frɒm ðə skuːl/", "vi": "Jose là một cậu thiếu niên từng học rất giỏi. Nhưng gần đây cậu bắt đầu trốn học khiến bố mẹ nhận được cuộc gọi từ nhà trường." },
      { "start": 18.0, "en": "Where was Jose? With a little investigating, they found out that their son was going to an Internet café to play computer games. They were very upset.", "ipa": "/wɛər wɒz hoʊˈzeɪ? wɪð ə ˈlɪtl ɪnˈvɛstɪˌɡeɪtɪŋ, ðeɪ faʊnd aʊt ðæt ðɛər sʌn wɒz ˈɡoʊɪŋ tuː ən ˈɪntərnɛt kæˈfeɪ tuː pleɪ kəmˈpjuːtər ɡeɪmz. ðeɪ wɜːr ˈvɛri ʌpˈsɛt/", "vi": "Jose đã đi đâu? Dò hỏi một chút, bố mẹ phát hiện con trai trốn vào quán net chơi game. Họ rất buồn lòng." },
      { "start": 32.0, "en": "The next weekend, they took him to visit his grandfather. His grandfather is a farmer. He grows vegetables, cotton, corn and many other crops. He walked with his grandson in the fields, looking at the crops.", "ipa": "/ðə nɛkst ˈwiːkˌɛnd, ðeɪ tʊk hɪm tuː ˈvɪzɪt hɪz ˈɡrændˌfɑːðər. hɪz ˈɡrændˌfɑːðər ɪz ə ˈfɑːrmər. hiː ɡroʊz ˈvɛdʒtəblz, ˈkɒtn, kɔːrn ænd ˈmɛni ˈʌðər krɒps. hiː wɔːkt wɪð hɪz ˈɡrændsʌn ɪn ðə fiːldz, ˈlʊkɪŋ æt ðə krɒps/", "vi": "Cuối tuần sau, bố mẹ đưa Jose về quê thăm ông nội làm nông. Ông trồng rau, bông, bắp ngô và nhiều loại hoa màu. Hai ông cháu cùng dạo bước ngắm đồng ruộng." },
      { "start": 48.0, "en": "Grandpa said to Jose, 'I plant every crop—each in its own season. Otherwise, I would have nothing to harvest. Everything has its time.'", "ipa": "/ˈɡrændpɑː sɛd tuː hoʊˈzeɪ, aɪ plɑːnt ˈɛvri krɒp—iːtʃ ɪn ɪts oʊn ˈsiːzn. ˈʌðərwaɪz, aɪ wʊd hæv ˈnʌθɪŋ tuː ˈhɑːrvɪst. ˈɛvriˌwɪŋ hæz ɪts taɪm/", "vi": "Ông bảo Jose: 'Mỗi loại cây ông đều phải gieo hạt đúng vụ. Nếu gieo sai thời điểm, ông sẽ chẳng có gì để gặt hái. Việc gì cũng có lúc của nó.'" },
      { "start": 61.0, "en": "He stopped and looked at his grandson. 'For you, it's the same,' he said. 'I don't want you to become a man who missed the season for planting.' Jose learned a good lesson from his grandfather.", "ipa": "/hiː stɒpt ænd lʊkt æt hɪz ˈɡrændsʌn. fɔːr juː, ɪts ðə seɪm, hiː sɛd. aɪ doʊnt wɒnt juː tuː bɪˈkʌm ə mæn huː mɪst ðə ˈsiːzn fɔːr ˈplɑːntɪŋ. hoʊˈzeɪ lɜːrnd ə ɡʊd ˈlɛsn frɒm hɪz ˈɡrændˌfɑːðər/", "vi": "Ông dừng lại ân cần nhìn cháu: 'Cháu cũng vậy thôi. Ông không muốn cháu thành người lỡ mất mùa gieo mầm tươi đẹp nhất.' Jose đã thấm thía bài học sâu sắc từ ông." }
    ]
  },
  {
    "day": 5,
    "title": "Brain Power",
    "image": "06 June/images/day_05.webp",
    "audio": "06 June/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Feel your head. Under the hard bone is your brain. Your brain makes it possible for you to do nearly everything: sit down, stand up, hear a bird sing, watch a movie, taste ice cream—you name it. Your brain makes it possible. And what's more, you don't have to think about it at all.", "ipa": "/fiːl jɔːr hɛd. ˈʌndər ðə hɑːrd boʊn ɪz jɔːr breɪn. jɔːr breɪn meɪks ɪt ˈpɒsəbl fɔːr juː tuː duː ˈnɪərli ˈɛvriˌθɪŋ: sɪt daʊn, stænd ʌp, hɪər ə bɜːrd sɪŋ, wɒtʃ ə ˈmuːvi, teɪst aɪs kriːm—juː neɪm ɪt. jɔːr breɪn meɪks ɪt ˈpɒsəbl. ænd wɒts mɔːr, juː doʊnt hæv tuː θɪŋk əˈbaʊt ɪt æt ɔːl/", "vi": "Hãy sờ lên đầu xem. Dưới hộp sọ cứng cáp chính là bộ não kỳ diệu. Bộ não điều khiển gần như mọi hoạt động: ngồi xuống, đứng lên, nghe chim hót, xem phim, nếm kem... và bạn chẳng cần tốn công suy nghĩ về nó." },
      { "start": 26.0, "en": "Your brain is soft and grey, and is made mostly of water. It is filled with electricity. That's how it works.", "ipa": "/jɔːr breɪn ɪz sɒft ænd ɡreɪ, ænd ɪz meɪd ˈmoʊstli əv ˈwɔːtər. ɪt ɪz fɪld wɪð ɪˌlɛkˈtrɪsəti. ðæts haʊ ɪt wɜːrks/", "vi": "Não bộ mềm, màu xám và chứa phần lớn là nước. Nó hoạt động nhờ chứa đầy các tín hiệu điện sinh học." },
      { "start": 35.0, "en": "Electricity moves from your brain throughout your whole body. Your brain has nearly 100 billion little electric receivers. That's about the same as the number of stars in our galaxy! There is enough electricity in your brain to turn on a small light bulb!", "ipa": "/ɪˌlɛkˈtrɪsəti muːvz frɒm jɔːr breɪn θruːˈaʊt jɔːr hoʊl ˈbɒdi. jɔːr breɪn hæz ˈnɪərli wʌn ˈhʌndrəd ˈbɪljən ˈlɪtl ɪˈlɛktrɪk rɪˈsiːvərz. ðæts əˈbaʊt ðə seɪm æz ðə ˈnʌmbər əv stɑːrz ɪn ˈaʊər ˈɡæləksi! ðɛər ɪz ɪˈnʌf ɪˌlɛkˈtrɪsəti ɪn jɔːr breɪn tuː tɜːrn ɒn ə smɔːl laɪt bʌlb!/", "vi": "Các xung điện truyền từ não đi khắp cơ thể bạn qua gần 100 tỷ tế bào nhận tín hiệu — tương đương số ngôi sao trong thiên hà! Não tạo ra đủ năng lượng điện để thắp sáng một bóng đèn nhỏ!" },
      { "start": 54.0, "en": "We don't understand everything about the brain. But one thing is certain—it is very powerful. Each day, a person has more than 70,000 thoughts. And size doesn't really matter. For example, Einstein's brain was about 20 percent smaller than most human brains. And he was a really smart guy!", "ipa": "/wiː doʊnt ˌʌndərˈstænd ˈɛvriˌwʌn əˈbaʊt ðə breɪn. bʌt wʌn θɪŋ ɪz ˈsɜːrtn—ɪt ɪz ˈvɛri ˈpaʊərfʊl. iːtʃ deɪ, ə ˈpɜːrsn hæz mɔːr ðæn ˈsɛvnti ˈθaʊznd θɔːts. ænd saɪz ˈdʌznt ˈrɪəli ˈmætər. fɔːr ɪɡˈzɑːmpl, ˈaɪnstaɪnz breɪn wɒz əˈbaʊt ˈtwɛnti pərˈsɛnt ˈsmɔːlər ðæn moʊst ˈhjuːmən breɪnz. ænd hiː wɒz ə ˈrɪəli smɑːrt ɡaɪ!/", "vi": "Con người chưa hiểu hết về não bộ, nhưng chắc chắn nó vô cùng mạnh mẽ với hơn 70.000 suy nghĩ mỗi ngày. Kích thước não không quyết định độ thông minh — ví dụ não của Einstein nhỏ hơn 20% so với người thường, thế mà ông là một thiên tài lỗi lạc!" }
    ]
  },
  {
    "day": 6,
    "title": "The Farm",
    "image": "06 June/images/day_06.webp",
    "audio": "06 June/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. and Mrs. Jones bought a farm. 'I have always wanted to live on a farm,' said Mr. Jones. 'Me too,' said Mrs. Jones. 'But this isn't a farm yet. We need animals to make it a farm.'", "ipa": "/ˈmɪstər ænd ˈmɪsɪz dʒoʊnz bɔːt ə fɑːrm. aɪ hæv ˈɔːlweɪz ˈwɒntɪd tuː lɪv ɒn ə fɑːrm, sɛd ˈmɪstər dʒoʊnz. miː tuː, sɛd ˈmɪsɪz dʒoʊnz. bʌt ðɪs ˈɪznt ə fɑːrm jɛt. wiː niːd ˈænɪmlz tuː meɪk ɪt ə fɑːrm/", "vi": "Vợ chồng ông Jones vừa mua một trang trại. 'Tôi luôn mong được sống ở nông trang,' ông Jones nói. 'Tôi cũng thế,' bà Jones đáp. 'Nhưng đây chưa phải trang trại thực thụ vì ta cần có thêm vật nuôi.'" },
      { "start": 21.0, "en": "'I would like a cat. Let's just get a cat for now. That's enough animals for me.' So Mr. and Mrs. Jones got a kitten and named it Callie. 'Now we have a real farm,' said Mr. Jones.", "ipa": "/aɪ wʊd laɪk ə kæt. lɛts dʒʌst ɡɛt ə kæt fɔːr naʊ. ðæts ɪˈnʌf ˈænɪmlz fɔːr miː. soʊ ˈmɪstər ænd ˈmɪsɪz dʒoʊnz ɡɒt ə ˈkɪtn ænd neɪmd ɪt ˈkæli. naʊ wiː hæv ə rɪəl fɑːrm, sɛd ˈmɪstər dʒoʊnz/", "vi": "'Bà thích nuôi mèo. Giờ cứ nuôi một chú mèo là đủ rồi.' Thế là hai ông bà nhận nuôi một chú mèo con đặt tên là Callie. 'Giờ ta có trang trại thật rồi!' ông Jones bảo." },
      { "start": 38.0, "en": "'No, we need a garden to make this a real farm,' said Mrs. Jones. 'Let's get a geranium for the window sill,' said Mr. Jones. 'That will be enough of a garden for me.'", "ipa": "/noʊ, wiː niːd ə ˈɡɑːrdn tuː meɪk ðɪs ə rɪəl fɑːrm, sɛd ˈmɪsɪz dʒoʊnz. lɛts ɡɛt ə dʒɪˈreɪniəm fɔːr ðə ˈwɪndoʊ sɪl, sɛd ˈmɪstər dʒoʊnz. ðæt wɪl biː ɪˈnʌf əv ə ˈɡɑːrdn fɔːr miː/", "vi": "'Chưa đâu, muốn thành trang trại thật phải có vườn tược nữa,' bà Jones nhắc. 'Vậy mình mua một chậu phong lữ đặt bậu cửa sổ nhé, thế là đủ thành khu vườn nhỏ rồi,' ông Jones vui vẻ đáp." },
      { "start": 53.0, "en": "So Mr. and Mrs. Jones bought a geranium and put it on the window sill. 'Now we have a farm,' said Mr. Jones. 'We have an animal and a plant. This is just the right farm for us.' And so it was.", "ipa": "/soʊ ˈmɪstər ænd ˈmɪsɪz dʒoʊnz bɔːt ə dʒɪˈreɪniəm ænd pʊt ɪt ɒn ðə ˈwɪndoʊ sɪl. naʊ wiː hæv ə fɑːrm, sɛd ˈmɪstər dʒoʊnz. wiː hæv ən ˈænɪml ænd ə plɑːnt. ðɪs ɪz dʒʌst ðə raɪt fɑːrm fɔːr ʌs. ænd soʊ ɪt wɒz/", "vi": "Thế là hai ông bà mua chậu phong lữ đặt lên bậu cửa. 'Bây giờ chúng ta đã có một nông trang hoàn chỉnh: có thú cưng và cây xanh. Trang trại này thật vừa vặn cho đôi ta!' Và quả đúng là như vậy." }
    ]
  },
  {
    "day": 7,
    "title": "Father Was Beaten",
    "image": "06 June/images/day_07.webp",
    "audio": "06 June/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "My dad is a very strong and athletic man. He loves playing table tennis and has won many matches.", "ipa": "/maɪ dæd ɪz ə ˈvɛri strɒŋ ænd æθˈlɛtɪk mæn. hiː lʌvz ˈpleɪɪŋ ˈteɪbl ˈtɛnɪs ænd hæz wʌn ˈmɛni ˈmætʃɪz/", "vi": "Bố tôi là một người đàn ông lực lưỡng và mê thể thao. Bố rất thích chơi bóng bàn và từng vô địch nhiều giải." },
      { "start": 14.0, "en": "One weekend, a new neighbour invited my dad for a friendly table tennis game. My dad smiled, confident that he would win easily.", "ipa": "/wʌn ˈwiːkˌɛnd, ə njuː ˈneɪbər ɪnˈvaɪtɪd maɪ dæd fɔːr ə ˈfrɛndli ˈteɪbl ˈtɛnɪs ɡeɪm. maɪ dæd smaɪld, ˈkɒnfɪdənt ðæt hiː wʊd wɪn ˈiːzɪli/", "vi": "Một cuối tuần nọ, người hàng xóm mới mời bố giao lưu một ván bóng bàn. Bố mỉm cười đầy tự tin nghĩ mình sẽ thắng dễ dàng." },
      { "start": 25.0, "en": "However, to everyone's surprise, the neighbour played with incredible skill and beat my dad completely!", "ipa": "/haʊˈɛvər, tuː ˈɛvriˌwʌnz sərˈpraɪz, ðə ˈneɪbər pleɪd wɪð ɪnˈkrɛdəbl skɪl ænd biːt maɪ dæd kəmˈpliːtli/", "vi": "Thế nhưng, mọi người đều ngỡ ngàng khi người hàng xóm ra những đường bóng điêu luyện và đánh bại bố hoàn toàn!" },
      { "start": 36.0, "en": "Dad wasn't upset at all. Instead, he smiled and shook the neighbor's hand warmly.", "ipa": "/dæd ˈwɒznt ʌpˈsɛt æt ɔːl. ɪnˈstɛd, hiː smaɪld ænd ʃʊk ðə ˈneɪbərz hænd ˈwɔːrmli/", "vi": "Bố không hề buồn bực mà mỉm cười bắt tay chúc mừng người bạn mới thật ấm áp." },
      { "start": 47.0, "en": "Dad said, 'There is always someone better out there. That is why we should always remain humble and keep learning.'", "ipa": "/dæd sɛd, ðɛər ɪz ˈɔːlweɪz ˈsʌmwʌn ˈbɛtər aʊt ðɛər. ðæt ɪz waɪ wiː ʃʊd ˈɔːlweɪz rɪˈmeɪn ˈhʌmbl ænd kiːp ˈlɜːrnɪŋ/", "vi": "Bố bảo: 'Núi cao còn có núi cao hơn con à. Đó là lý do ta phải luôn khiêm tốn và không ngừng học hỏi.'" }
    ]
  },
  {
    "day": 8,
    "title": "Finding a Husband (I)",
    "image": "06 June/images/day_08.webp",
    "audio": "06 June/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "Once, there lived a happy mouse family. They had a beautiful daughter. Mr. and Mrs. Mouse would always say, 'Our daughter is the best girl in all the land. We must find the most powerful person to marry her.'", "ipa": "/wʌns, ðɛər lɪvd ə ˈhæpi maʊs ˈfæməli. ðeɪ hæd ə ˈbjuːtɪfl ˈdɔːtər. ˈmɪstər ænd ˈmɪsɪz maʊs wʊd ˈɔːlweɪz seɪ, ˈaʊər ˈdɔːtər ɪz ðə bɛst ɡɜːrl ɪn ɔːl ðə lænd. wiː mʌst faɪnd ðə moʊst ˈpaʊərfʊl ˈpɜːrsn tuː ˈmæri hɜːr/", "vi": "Thuở xưa có một gia đình chuột sống êm ấm. Họ có cô con gái xinh đẹp tuyệt trần nên bố mẹ chuột luôn tấm tắc: 'Con gái ta là tuyệt nhất trần đời. Ta phải tìm cho con người quyền năng nhất thế gian.'" },
      { "start": 21.0, "en": "They decided that the sun would be the best person to marry their daughter. So they went on a journey to see the sun. 'Sun,' they said. 'You are most powerful. You shine brightly and bring light everywhere. Will you marry our daughter?'", "ipa": "/ðeɪ dɪˈsaɪdɪd ðæt ðə sʌn wʊd biː ðə bɛst ˈpɜːrsn tuː ˈmæri ðɛər ˈdɔːtər. soʊ ðeɪ wɛnt ɒn ə ˈdʒɜːrni tuː siː ðə sʌn. sʌn, ðeɪ sɛd. juː ɑːr moʊst ˈpaʊərfʊl. juː ʃaɪn ˈbraɪtli ænd brɪŋ laɪt ˈɛvriˌwɛər. wɪl juː ˈmæri ˈaʊər ˈdɔːtər?/", "vi": "Họ quyết định Mặt Trời là ứng viên sáng giá nhất và lặn lội đến ngỏ lời: 'Thưa Mặt Trời quyền uy, ngài tỏa ánh sáng rực rỡ khắp nơi, ngài có đồng ý cưới con gái chúng tôi không?'" },
      { "start": 40.0, "en": "Sun replied, 'I am strong and powerful. But Cloud is more powerful than me. Cloud can cover me and hide my light. He will make a good husband.'", "ipa": "/sʌn rɪˈplaɪd, aɪ æm strɒŋ ænd ˈpaʊərfʊl. bʌt klaʊd ɪz mɔːr ˈpaʊərfʊl ðæn miː. klaʊd kæn ˈkʌvər miː ænd haɪd maɪ laɪt. hiː wɪl meɪk ə ɡʊd ˈhʌzbənd/", "vi": "Mặt Trời đáp: 'Ta mạnh mẽ thật đấy, nhưng Mây còn quyền năng hơn ta. Mây có thể che khuất ánh sáng của ta. Hãy gả con cho Mây thì hơn.'" },
      { "start": 53.0, "en": "So, Mr. and Mrs. Mouse travelled to see Cloud and asked him to marry their daughter. But Cloud said, 'I am flattered, but I am not the most powerful. Wind is more powerful. Wind can blow me away with no effort.'", "ipa": "/soʊ, ˈmɪstər ænd ˈmɪsɪz maʊs ˈtrævld tuː siː klaʊd ænd ɑːskt hɪm tuː ˈmæri ðɛər ˈdɔːtər. bʌt klaʊd sɛd, aɪ æm ˈflætərd, bʌt aɪ æm nɒt ðə moʊst ˈpaʊərfʊl. wɪnd ɪz mɔːr ˈpaʊərfʊl. wɪnd kæn bloʊ miː əˈweɪ wɪð noʊ ˈɛfərt/", "vi": "Vợ chồng chuột lại tìm đến Mây. Nhưng Mây từ tốn: 'Tôi rất vinh hạnh nhưng Gió mới mạnh hơn tôi, Gió thổi nhẹ một cái là tôi bay biến mất.'" },
      { "start": 68.0, "en": "Mr. and Mrs. Mouse were astonished. But they wanted the best husband for their daughter. So, they decided to search for Wind.", "ipa": "/ˈmɪstər ænd ˈmɪsɪz maʊs wɜːr əˈstɒnɪʃt. bʌt ðeɪ ˈwɒntɪd ðə bɛst ˈhʌzbənd fɔːr ðɛər ˈdɔːtər. soʊ, ðeɪ dɪˈsaɪdɪd tuː sɜːrtʃ fɔːr wɪnd/", "vi": "Hai ông bà chuột vô cùng kinh ngạc nhưng quyết tâm tìm người tài giỏi nhất nên lại lên đường tìm Thần Gió." }
    ]
  },
  {
    "day": 9,
    "title": "Finding a Husband (II)",
    "image": "06 June/images/day_09.webp",
    "audio": "06 June/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "Soon, the mouse parents found Wind. They asked him to marry their daughter. Wind, too, was surprised. He said, 'I am not the most powerful. I am strong, yes. But when I come up against a wall, I am stopped right in my tracks.'", "ipa": "/suːn, ðə maʊs ˈpeərənts faʊnd wɪnd. ðeɪ ɑːskt hɪm tuː ˈmæri ðɛər ˈdɔːtər. wɪnd, tuː, wɒz sərˈpraɪzd. hiː sɛd, aɪ æm nɒt ðə moʊst ˈpaʊərfʊl. aɪ æm strɒŋ, jɛs. bʌt wɛn aɪ kʌm ʌp əˈɡɛnst ə wɔːl, aɪ æm stɒpt raɪt ɪn maɪ træks/", "vi": "Chẳng mấy chốc, bố mẹ chuột tìm thấy Gió. Gió ngạc nhiên đáp: 'Tôi không phải người mạnh nhất đâu. Dù tôi rất mạnh, nhưng hễ gặp Bức Tường là tôi phải dừng bước ngay lập tức.'" },
      { "start": 24.0, "en": "Discouraged, the two mice went to visit Wall. They asked him to marry their daughter. 'I would be honoured,' said Wall. 'But you seek the most powerful of all. I am strong. But as you know, a mouse can chew through me with little effort.'", "ipa": "/dɪsˈkʌrɪdʒd, ðə tuː maɪs wɛnt tuː ˈvɪzɪt wɔːl. ðeɪ ɑːskt hɪm tuː ˈmæri ðɛər ˈdɔːtər. aɪ wʊd biː ˈɒnərd, sɛd wɔːl. bʌt juː siːk ðə moʊst ˈpaʊərfʊl əv ɔːl. aɪ æm strɒŋ. bʌt æz juː noʊ, ə maʊs kæn tʃuː θruː miː wɪð ˈlɪtl ˈɛfərt/", "vi": "Thất vọng, hai chú chuột tìm đến Bức Tường. Bức Tường nói: 'Tôi rất vinh hạnh. Nhưng người các vị tìm là kẻ mạnh nhất: Tôi kiên cố thật đấy, nhưng một chú chuột có thể dễ dàng đục thủng tôi!'" },
      { "start": 42.0, "en": "Mr. and Mrs. Mouse were amazed. 'So, we, the mice, are powerful. We can make holes in walls. This is true.' And so, they returned home.", "ipa": "/ˈmɪstər ænd ˈmɪsɪz maʊs wɜːr əˈmeɪzd. soʊ, wiː, ðə maɪs, ɑːr ˈpaʊərfʊl. wiː kæn meɪk hoʊlz ɪn wɔːlz. ðɪs ɪz truː. ænd soʊ, ðeɪ rɪˈtɜːrnd hoʊm/", "vi": "Bố mẹ chuột vỡ òa kinh ngạc: 'Hóa ra loài chuột chúng ta mới là mạnh nhất, có thể đục thủng cả bức tường kiên cố!' Thế là họ hân hoan quay về nhà." },
      { "start": 55.0, "en": "Around the corner from their house, there lived a good and honest mouse. He had lived there all his life. Mr. and Mrs. Mouse asked him to marry their daughter. Of course, he did as they asked. The two young mice married and lived a long and happy life together.", "ipa": "/əˈraʊnd ðə ˈkɔːrnər frɒm ðɛər haʊs, ðɛər lɪvd ə ɡʊd ænd ˈɒnɪst maʊs. hiː hæd lɪvd ðɛər ɔːl hɪz laɪf. ˈmɪstər ænd ˈmɪsɪz maʊs ɑːskt hɪm tuː ˈmæri ðɛər ˈdɔːtər. əv kɔːrs, hiː dɪd æz ðeɪ ɑːskt. ðə tuː jʌŋ maɪs ˈmærid ænd lɪvd ə lɒŋ ænd ˈhæpi laɪf təˈɡɛðər/", "vi": "Ngay góc phố gần nhà có một chàng chuột hiền lành, trung thực sống ở đó từ nhỏ. Bố mẹ chuột liền gả con gái cho cậu. Chàng chuột vui mừng nhận lời. Đôi chuột trẻ nên duyên vợ chồng và sống bên nhau trọn đời hạnh phúc." }
    ]
  },
  {
    "day": 10,
    "title": "Polly's Pudding",
    "image": "06 June/images/day_10.webp",
    "audio": "06 June/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "Polly was happy. Her grandpa and grandma were coming over for supper. 'May I make pudding for dessert?' asked Polly. 'Yes, that would be a big help,' answered Mom. 'Just remember to make extra.' 'I will,' promised Polly.", "ipa": "/ˈpɒli wɒz ˈhæpi. hɜːr ˈɡrændpɑː ænd ˈɡrænmɑː wɜːr ˈkʌmɪŋ ˈoʊvər fɔːr ˈsʌpər. meɪ aɪ meɪk ˈpʊdɪŋ fɔːr dɪˈzɜːrt?, ɑːskt ˈpɒli. jɛs, ðæt wʊd biː ə bɪɡ hɛlp, ˈɑːnsərd mɒm. dʒʌst rɪˈmɛmbər tuː meɪk ˈɛkstrə. aɪ wɪl, ˈprɒmɪst ˈpɒli/", "vi": "Polly rất vui vì ông bà sắp sang ăn tối. 'Con làm món pudding tráng miệng nhé?' Polly xin phép. Mẹ cười: 'Được chứ, con làm giúp mẹ một tay, nhớ làm thêm nhiều một chút nhé.' 'Vâng ạ!' Polly hứa." },
      { "start": 21.0, "en": "Polly got to work. She got out everything she would need to make the pudding. 'I will make chocolate pudding,' she said to herself. 'That's the best kind!'", "ipa": "/ˈpɒli ɡɒt tuː wɜːrk. ʃiː ɡɒt aʊt ˈɛvriˌwʌn ʃiː wʊd niːd tuː meɪk ðə ˈpʊdɪŋ. aɪ wɪl meɪk ˈtʃɒklət ˈpʊdɪŋ, ʃiː sɛd tuː hɜːrˈsɛlf. ðæts ðə bɛst kaɪnd!/", "vi": "Polly bắt tay vào việc ngay. Cô bé chuẩn bị đầy đủ nguyên liệu làm bánh. 'Mình sẽ làm món pudding sô-cô-la, món này là ngon nhất trần đời!'" },
      { "start": 35.0, "en": "But, there was a little problem. Polly didn't know how much of everything she needed for a bigger batch. Then, she came up with an idea. She made her usual amount and dumped it into a bowl. Then, she made another batch—exactly the same as the first one—and put it in the same bowl.", "ipa": "/bʌt, ðɛər wɒz ə ˈlɪtl ˈprɒbləm. ˈpɒli ˈdɪdnt noʊ haʊ mʌtʃ əv ˈɛvriˌwʌn ʃiː ˈniːdɪd fɔːr ə ˈbɪɡər bætʃ. ðɛn, ʃiː keɪm ʌp wɪð ən aɪˈdiːə. ʃiː meɪd hɜːr ˈjuːʒuəl əˈmaʊnt ænd dʌmpt ɪt ˈɪntuː ə boʊl. ðɛn, ʃiː meɪd əˈnʌðər bætʃ—ɪɡˈzæktli ðə seɪm æz ðə fɜːrst wʌn—ænd pʊt ɪt ɪn ðə seɪm boʊl/", "vi": "Thế nhưng có một rắc rối nhỏ: Polly không biết phải đong đếm nguyên liệu bao nhiêu để làm một mẻ bánh lớn hơn bình thường. Rồi cô bé nảy ra sáng kiến: Cứ làm một mẻ theo công thức quen thuộc đổ vào tô lớn, rồi làm tiếp mẻ thứ hai y hệt như vậy trút chung vào tô!" },
      { "start": 58.0, "en": "'Now I have enough pudding for everyone and perhaps some extra!' she said.", "ipa": "/naʊ aɪ hæv ɪˈnʌf ˈpʊdɪŋ fɔːr ˈɛvriˌwʌn ænd pərˈhæps sʌm ˈɛkstrə!, ʃiː sɛd/", "vi": "'Giờ thì mình có đủ pudding cho cả nhà mà còn dư thêm phần nữa rồi!' cô bé thích thú reo lên." }
    ]
  },
  {
    "day": 11,
    "title": "What's the Difference?",
    "image": "06 June/images/day_11.webp",
    "audio": "06 June/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "Jerry was different from the other kids. He was ten years old, but less than one metre tall. The boys would not play with him. The girls made fun of him. Every day, he cried before going to school. He did not want to face another day at school.", "ipa": "/ˈdʒɛri wɒz ˈdɪfrənt frɒm ði ˈʌðər kɪdz. hiː wɒz tɛn jɪərz oʊld, bʌt lɛs ðæn wʌn ˈmiːtər tɔːl. ðə bɔɪz wʊd nɒt pleɪ wɪð hɪm. ðə ɡɜːrlz meɪd fʌn əv hɪm. ˈɛvri deɪ, hiː kraɪd bɪˈfɔːr ˈɡoʊɪŋ tuː skuːl. hiː dɪd nɒt wɒnt tuː feɪs əˈnʌðər deɪ æt skuːl/", "vi": "Jerry khác biệt với các bạn: Cậu mười tuổi nhưng cao chưa đầy một mét. Đám con trai không thèm chơi cùng, con gái thì trêu chọc. Ngày nào cậu cũng khóc rấm rứt không muốn đến trường." },
      { "start": 24.0, "en": "'It's just the way you are,' his mom said. 'You were born this way. Someday, you might grow big and tall. But for now, you are short.'", "ipa": "/ɪts dʒʌst ðə weɪ juː ɑːr, hɪz mɒm sɛd. juː wɜːr bɔːrn ðɪs weɪ. ˈsʌmdeɪ, juː maɪt ɡroʊ bɪɡ ænd tɔːl. bʌt fɔːr naʊ, juː ɑːr ʃɔːrt/", "vi": "'Con vốn sinh ra đã như vậy rồi,' mẹ an ủi. 'Sau này con có thể lớn bổng lên, nhưng hiện tại con cứ chấp nhận chiều cao khiêm tốn của mình nhé.'" },
      { "start": 36.0, "en": "One day before school, while Jerry was crying, he saw a really tall man. He was at least 2.25 metres tall. The tall man asked, 'What is the problem?' The boy explained what was wrong.", "ipa": "/wʌn deɪ bɪˈfɔːr skuːl, waɪl ˈdʒɛri wɒz ˈkraɪɪŋ, hiː sɔː ə ˈrɪəli tɔːl mæn. hiː wɒz æt liːst tuː pɔɪnt ˈtwɛnti-faɪv ˈmiːtərz tɔːl. ðə tɔːl mæn ɑːskt, wɒt ɪz ðə ˈprɒbləm? ðə bɔɪ ɪkˈspleɪnd wɒt wɒz rɒŋ/", "vi": "Một sáng trước giờ học, khi Jerry đang khóc thì gặp một người đàn ông cao tới 2,25 mét. Người đàn ông hỏi han và Jerry kể hết nỗi ấm ức của mình." },
      { "start": 52.0, "en": "The tall man smiled. 'When I was a boy, they teased me too. I was too tall. But you know what? Today, I am a pro basketball star. Now everyone wants to be my friend.'", "ipa": "/ðə tɔːl mæn smaɪld. wɛn aɪ wɒz ə bɔɪ, ðeɪ tiːzd miː tuː. aɪ wɒz tuː tɔːl. bʌt juː noʊ wɒt? təˈdeɪ, aɪ æm ə proʊ ˈbæskɪtbɔːl stɑːr. naʊ ˈɛvriˌwʌn wɒnts tuː biː maɪ frɛnd/", "vi": "Người đàn ông mỉm cười: 'Hồi bé chú cũng bị bạn bè trêu chọc vì quá cao. Nhưng cháu biết không? Giờ chú là siêu sao bóng rổ chuyên nghiệp, ai cũng muốn làm bạn với chú đấy.'" },
      { "start": 67.0, "en": "Jerry learned something new that day. It's no fun being different. But you never know how things will turn out.", "ipa": "/ˈdʒɛri lɜːrnd ˈsʌmθɪŋ njuː ðæt deɪ. ɪts noʊ fʌn ˈbiːɪŋ ˈdɪfrənt. bʌt juː ˈnɛvər noʊ haʊ θɪŋz wɪl tɜːrn aʊt/", "vi": "Jerry đã ngộ ra một điều mới: Khác biệt tuy chẳng mấy dễ chịu lúc này, nhưng bạn sẽ không thể ngờ tương lai sẽ mở ra những điều kỳ diệu ra sao." }
    ]
  },
  {
    "day": 12,
    "title": "Recycling Cans",
    "image": "06 June/images/day_12.webp",
    "audio": "06 June/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "Turning old things into new things is called recycling. One thing that can be recycled is cans. Cans are made of aluminum. Aluminum is a metal. It is light and strong. It can be used over and over again. This saves energy and money.", "ipa": "/ˈtɜːrnɪŋ oʊld θɪŋz ˈɪntuː njuː θɪŋz ɪz kɔːld ˌriːˈsaɪklɪŋ. wʌn θɪŋ ðæt kæn biː ˌriːˈsaɪkld ɪz kænz. kænz ɑːr meɪd əv əˈluːmɪnəm. əˈluːmɪnəm ɪz ə ˈmɛtl. ɪt ɪz laɪt ænd strɒŋ. ɪt kæn biː juːzd ˈoʊvər ænd ˈoʊvər əˈɡɛn. ðɪs seɪvz ˈɛnərdʒi ænd ˈmʌni/", "vi": "Biến đồ cũ thành vật dụng mới gọi là tái chế. Một trong những thứ dễ tái chế nhất là vỏ lon bằng nhôm — một kim loại nhẹ, bền và có thể tái sử dụng nhiều lần, giúp tiết kiệm năng lượng và tiền bạc." },
      { "start": 22.0, "en": "We buy many things in cans. Soup and pop come in cans. Tuna and tomatoes come in cans too. Old cans should not be thrown away. Old cans need to be taken to a recycling centre. A recycling centre will make new cans out of your old cans.", "ipa": "/wiː baɪ ˈmɛni θɪŋz ɪn kænz. suːp ænd pɒp kʌm ɪn kænz. ˈtjuːnə ænd təˈmɑːtoʊz kʌm ɪn kænz tuː. oʊld kænz ʃʊd nɒt biː θroʊn əˈweɪ. oʊld kænz niːd tuː biː ˈteɪkən tuː ə ˌriːˈsaɪklɪŋ ˈsɛntər. ə ˌriːˈsaɪklɪŋ ˈsɛntər wɪl meɪk njuː kænz aʊt əv jɔːr oʊld kænz/", "vi": "Chúng ta mua rất nhiều đồ hộp: Súp, nước ngọt, cá ngừ hay cà chua. Vỏ lon cũ đừng vứt bừa bãi mà hãy gom lại đưa đến trung tâm tái chế để làm thành những chiếc lon mới tinh." },
      { "start": 45.0, "en": "Recycling cans is easy and fast. First, the old cans are cut into pieces. Then, they are melted. Next, they are flattened into sheets. Finally, they are made into new cans.", "ipa": "/ˌriːˈsaɪklɪŋ kænz ɪz ˈiːzi ænd fɑːst. fɜːrst, ði oʊld kænz ɑːr kʌt ˈɪntuː ˈpiːsɪz. ðɛn, ðeɪ ɑːr ˈmɛltɪd. nɛkst, ðeɪ ɑːr ˈflætnd ˈɪntuː ʃiːts. ˈfaɪnəli, ðeɪ ɑːr meɪd ˈɪntuː njuː kænz/", "vi": "Tái chế lon rất nhanh và dễ: Đầu tiên lon được cắt vụn, nấu chảy thành kim loại lỏng, cán mỏng thành từng tấm nhôm và dập thành những chiếc lon mới." },
      { "start": 62.0, "en": "What other old things can be recycled?", "ipa": "/wɒt ˈʌðər oʊld θɪŋz kæn biː ˌriːˈsaɪkld?/", "vi": "Còn những món đồ cũ nào khác có thể tái chế được nữa bạn nhỉ?" }
    ]
  },
  {
    "day": 13,
    "title": "A Place to Find Wood",
    "image": "06 June/images/day_13.webp",
    "audio": "06 June/audio/Track13.mp3",
    "sentences": [
      { "start": 4.8, "en": "The year was 1628. The land was called New Amsterdam because it was owned by a Dutch fur company. They had bought it from the Indians for 60 Dutch guilders, which is about 6,500 Chinese yuan or 65 US dollars today.", "ipa": "/ðə jɪər wɒz ˈsɪksˈtiːn ˈtwɛnti-eɪt. ðə lænd wɒz kɔːld njuː ˈæmstərdæm bɪˈkɒz ɪt wɒz oʊnd baɪ ə dʌtʃ fɜːr ˈkʌmpəni. ðeɪ hæd bɔːt ɪt frɒm ði ˈɪndiənz fɔːr ˈsɪksti dʌtʃ ˈɡɪldərz, wɪtʃ ɪz əˈbaʊt sɪks ˈθaʊznd faɪv ˈhʌndrəd ˈtʃaɪˈniːz juːˈɑːn ɔːr ˈsɪksti-faɪv juː-ɛs ˈdɒlərz təˈdeɪ/", "vi": "Vào năm 1628, vùng đất này có tên New Amsterdam thuộc công ty lông thú Hà Lan. Họ mua lại từ người da đỏ bản địa với giá vỏn vẹn 60 đồng tiền Hà Lan (tương đương khoảng 65 đô-la ngày nay)." },
      { "start": 23.0, "en": "The land was mainly forest. The Indians named it Manhattan, which means 'a place to find wood for making bows and arrows'. Today, that island is still called Manhattan. And it is a good place to find people!", "ipa": "/ðə lænd wɒz ˈmeɪnli ˈfɒrɪst. ði ˈɪndiənz neɪmd ɪt mænˈhætn, wɪtʃ miːnz ə pleɪs tuː faɪnd wʊd fɔːr ˈmeɪkɪŋ boʊz ænd ˈæroʊz. təˈdeɪ, ðæt ˈaɪlənd ɪz stɪl kɔːld mænˈhætn. ænd ɪt ɪz ə ɡʊd pleɪs tuː faɪnd ˈpiːpl!/", "vi": "Thuở ấy nơi đây bạt ngàn rừng rậm, người da đỏ gọi là Manhattan — nghĩa là 'nơi lấy gỗ làm cung tên'. Ngày nay hòn đảo ấy vẫn mang tên Manhattan, nhưng lại là nơi sầm uất ngập tràn bóng người!" },
      { "start": 41.0, "en": "The whole city is called New York City. It has about 20 million people who come from all over the world to live there. And about 50 million people visit the city each year! It is full of different people, ideas, cultures and even food.", "ipa": "/ðə hoʊl ˈsɪti ɪz kɔːld njuː jɔːrk ˈsɪti. ɪt hæz əˈbaʊt ˈtwɛnti ˈmɪljən ˈpiːpl huː kʌm frɒm ɔːl ˈoʊvər ðə wɜːrld tuː lɪv ðɛər. ænd əˈbaʊt ˈfɪfti ˈmɪljən ˈpiːpl ˈvɪzɪt ðə ˈsɪti iːtʃ jɪər! ɪt ɪz fʊl əv ˈdɪfrənt ˈpiːpl, aɪˈdiːəz, ˈkʌltʃərz ænd ˈiːvn fuːd/", vi: "Thành phố này chính là New York với khoảng 20 triệu cư dân đa sắc tộc và đón 50 triệu du khách mỗi năm, hội tụ muôn vàn nét văn hóa và ẩm thực phong phú." },
      { "start": 61.0, "en": "Manhattan has many famous tourist attractions. It is also home to the United Nations, located in the centre of New York City. Wouldn't it be fun to visit a country and see a little of other countries too?", "ipa": "/mænˈhætn hæz ˈmɛni ˈfeɪməs ˈtʊərɪst əˈtrækʃnz. ɪt ɪz ˈɔːlsoʊ hoʊm tuː ðə juːˈnaɪtɪd ˈneɪʃnz, loʊˈkeɪtɪd ɪn ðə ˈsɛntər əv njuː jɔːrk ˈsɪti. ˈwʊdnt ɪt biː fʌn tuː ˈvɪzɪt ə ˈkʌntri ænd siː ə ˈlɪtl əv ˈʌðər ˈkʌntriz tuː?/", vi: "Manhattan có nhiều danh thắng nổi tiếng và là nơi đặt trụ sở Liên Hợp Quốc. Đến đây, bạn như được ngắm nhìn cả thế giới thu nhỏ trong tầm mắt." }
    ]
  },
  {
    "day": 14,
    "title": "Can You Solve This Riddle?",
    "image": "06 June/images/day_14.webp",
    "audio": "06 June/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "Our English teacher, Ms. Young, wants us to have fun in school. At the end of each day, she gives us some riddles to solve. It's fun trying to find the answers to her riddles. We have to think really hard.", "ipa": "/ˈaʊər ˈɪŋɡlɪʃ ˈtiːtʃər, mɪz jʌŋ, wɒnts ʌs tuː hæv fʌn ɪn skuːl. æt ði ɛnd əv iːtʃ deɪ, ʃiː ɡɪvz ʌs sʌm ˈrɪdlz tuː sɒlv. ɪts fʌn ˈtraɪɪŋ tuː faɪnd ði ˈɑːnsərz tuː hɜːr ˈrɪdlz. wiː hæv tuː θɪŋk ˈrɪəli hɑːrd/", "vi": "Cô giáo tiếng Anh Young luôn muốn chúng tôi thấy vui vẻ ở trường. Cuối mỗi ngày, cô cho cả lớp giải các câu đố mẹo rất thú vị và hóc búa." },
      { "start": 20.0, "en": "Today, Ms. Young put this riddle on the blackboard: What goes up, but never comes down? We tried and tried, but we could not figure out the answer. Ms. Young laughed and finally gave us the answer. 'Your age, of course!' she said.", "ipa": "/təˈdeɪ, mɪz jʌŋ pʊt ðɪs ˈrɪdl ɒn ðə ˈblækbɔːrd: wɒt ɡoʊz ʌp, bʌt ˈnɛvər kʌmz daʊn? wiː traɪd ænd traɪd, bʌt wiː kʊd nɒt ˈfɪɡjər aʊt ði ˈɑːnsər. mɪz jʌŋ lɑːft ænd ˈfaɪnəli ɡeɪv ʌs ði ˈɑːnsər. jɔːr eɪdʒ, əv kɔːrs!, ʃiː sɛd/", vi: "Hôm nay cô viết lên bảng câu đố: 'Cái gì chỉ tăng lên mà không bao giờ giảm xuống?' Cả lớp vắt óc suy nghĩ không ra. Cô bật cười đưa đáp án: 'Chính là tuổi tác của các em chứ đâu!'" },
      { "start": 39.0, "en": "'Another one, please!' we all begged. 'Okay. What month has 28 days?' That riddle was very easy. 'February!' we shouted. 'Are you sure?' asked Mrs. Young. 'Take a minute to think about it.' 'It's February. We are sure.'", "ipa": "/əˈnʌðər wʌn, pliːz!, wiː ɔːl bɛɡd. oʊˈkeɪ. wɒt mʌnθ hæz ˈtwɛnti-eɪt deɪz? ðæt ˈrɪdl wɒz ˈvɛri ˈiːzi. ˈfɛbruəri!, wiː ˈʃaʊtɪd. ɑːr juː ʃʊər?, ɑːskt ˈmɪsɪz jʌŋ. teɪk ə ˈmɪnɪt tuː θɪŋk əˈbaʊt ɪt. ɪts ˈfɛbruəri. wiː ɑːr ʃʊər/", vi: "'Đố nữa đi cô!' cả lớp nhao nhao. 'Được rồi: Tháng nào có 28 ngày?' Dễ ợt, cả lớp đồng thanh hét: 'Tháng Hai ạ!' Cô hỏi lại: 'Chắc chưa, nghĩ kỹ xem nào?' 'Chắc chắn là tháng Hai ạ!'" },
      { "start": 57.0, "en": "Ms. Young laughed. 'You are wrong,' she said. 'Look at the calendar. You will see that EVERY month has 28 days!' We all laughed too. Ms. Young is so smart. We love her riddles. They are fun!", "ipa": "/mɪz jʌŋ lɑːft. juː ɑːr rɒŋ, ʃiː sɛd. lʊk æt ðə ˈkælɪndər. juː wɪl siː ðæt ˈɛvri mʌnθ hæz ˈtwɛnti-eɪt deɪz! wiː ɔːl lɑːft tuː. mɪz jʌŋ ɪz soʊ smɑːrt. wiː lʌv hɜːr ˈrɪdlz. ðeɪ ɑːr fʌn!/", vi: "Cô cười phá lên: 'Sai bét rồi. Nhìn lịch mà xem, tháng NÀO trong năm cũng có ngày 28 cả!' Cả lớp cười ồ thích thú. Cô Young thật thông minh và những câu đố của cô luôn đem lại niềm vui bất tận!" }
    ]
  },
  {
    "day": 15,
    "title": "Popcorn",
    "image": "06 June/images/day_15.webp",
    "audio": "06 June/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. Kelly has been teaching science for nearly twenty-five years. Every day, he tries to inspire his students. That's why there is never a boring moment in his science class.", "ipa": "/ˈmɪstər ˈkɛli hæz biːn ˈtiːtʃɪŋ ˈsaɪəns fɔːr ˈnɪərli ˈtwɛnti-faɪv jɪərz. ˈɛvri deɪ, hiː traɪz tuː ɪnˈspaɪər hɪz ˈstjuːdnts. ðæts waɪ ðɛər ɪz ˈnɛvər ə ˈbɔːrɪŋ ˈmoʊmənt ɪn hɪz ˈsaɪəns klɑːs/", "vi": "Thầy Kelly đã dạy khoa học gần 25 năm. Thầy luôn truyền cảm hứng cho học trò nên lớp học của thầy chưa bao giờ nhàm chán." },
      { "start": 16.0, "en": "Today, he says, 'We will make popcorn.' On his desk is a small pot, a small stove and a bowl of raw popcorn. He lights the stove and then puts the popcorn in the pot. The pot gets hot fast.", "ipa": "/təˈdeɪ, hiː sɛz, wiː wɪl meɪk ˈpɒpkɔːrn. ɒn hɪz dɛsk ɪz ə smɔːl pɒt, ə smɔːl stoʊv ænd ə boʊl əv rɔː ˈpɒpkɔːrn. hiː laɪts ðə stoʊv ænd ðɛn pʊts ðə ˈpɒpkɔːrn ɪn ðə pɒt. ðə pɒt ɡɛts hɒt fɑːst/", vi: "Hôm nay thầy bảo: 'Chúng ta sẽ làm bắp rang bơ.' Trên bàn có một chiếc nồi nhỏ, bếp mini và bát hạt ngô khô. Thầy bật bếp và cho ngô vào nồi nóng." },
      { "start": 32.0, "en": "Soon, everyone can hear the sound of corn popping. A strong smell of popcorn comes out of the pot! Five minutes later, everyone is eating popcorn.", "ipa": "/suːn, ˈɛvriˌwʌn kæn hɪər ðə saʊnd əv kɔːrn ˈpɒpɪŋ. ə strɒŋ smɛl əv ˈpɒpkɔːrn kʌmz aʊt əv ðə pɒt! faɪv ˈmɪnɪts ˈleɪtər, ˈɛvriˌwʌn ɪz ˈiːtɪŋ ˈpɒpkɔːrn/", vi: "Chẳng mấy chốc, tiếng nổ lách tách giòn giã vang lên kèm mùi bắp rang thơm phức. Chỉ năm phút sau, cả lớp đã được thưởng thức món bắp rang nóng hổi." },
      { "start": 45.0, "en": "'Why does it pop?' asks Mr. Kelly. No one knows the answer. 'In each little grain of corn, there is a small drop of water. The heat turns the water to steam. The steam is powerful. It breaks the shell and makes the corn pop,' says Mr. Kelly.", "ipa": "/waɪ dʌz ɪt pɒp?, ɑːskt ˈmɪstər ˈkɛli. noʊ wʌn noʊz ði ˈɑːnsər. ɪn iːtʃ ˈlɪtl ɡreɪn əv kɔːrn, ðɛər ɪz ə smɔːl drɒp əv ˈwɔːtər. ðə hiːt tɜːrnz ðə ˈwɔːtər tuː stiːm. ðə stiːm ɪz ˈpaʊərfʊl. ɪt breɪks ðə ʃɛl ænd meɪks ðə kɔːrn pɒp, sɛd ˈmɪstər ˈkɛli/", vi: "'Tại sao ngô lại nổ?' thầy Kelly hỏi. Thầy giải thích: 'Trong mỗi hạt ngô có một giọt nước tí hon. Nhiệt độ cao biến nước thành hơi làm nứt vỏ và nổ bung hạt ngô!'" },
      { "start": 62.0, "en": "'Regular corn will not pop. Why? There are no drops of water in the kernels. So when the kernels are heated, there is no steam to burst out.' Everyone loves the tasty popcorn. Now we all know why popcorn pops. The mystery is solved!", "ipa": "/ˈrɛɡjələr kɔːrn wɪl nɒt pɒp. waɪ? ðɛər ɑːr noʊ drɒps əv ˈwɔːtər ɪn ðə ˈkɜːrnlz. soʊ wɛn ðə ˈkɜːrnlz ɑːr ˈhiːtɪd, ðɛər ɪz noʊ stiːm tuː bɜːrst aʊt. ˈɛvriˌwʌn lʌvz ðə ˈteɪsti ˈpɒpkɔːrn. naʊ wiː ɔːl noʊ waɪ ˈpɒpkɔːrn pɒps. ðə ˈmɪstəri ɪz sɒlvd!/", vi: "'Ngô thường không nổ vì không có nước bên trong. Ai cũng mê món bắp rang, và giờ bí ẩn đã được giải mã!'" }
    ]
  },
  {
    "day": 16,
    "title": "Gerry",
    "image": "06 June/images/day_16.webp",
    "audio": "06 June/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "Gerry screamed. He jumped up and down and he stamped his feet. He was so young that he couldn't talk well enough to tell his parents what he was looking for. So, he ran through the house.", "ipa": "/ˈɡɛri skriːmd. hiː dʒʌmpt ʌp ænd daʊn ænd hiː stæmpt hɪz fiːt. hiː wɒz soʊ jʌŋ ðæt hiː ˈkʊdnt tɔːk wɛl ɪˈnʌf tuː tɛl hɪz ˈpeərənts wɒt hiː wɒz ˈlʊkɪŋ fɔːr. soʊ, hiː ræn θruː ðə haʊs/", vi: "Gerry la hét, nhảy cẫng lên giậm chân bình bịch. Cậu bé còn quá nhỏ chưa nói sõi để bảo bố mẹ mình tìm gì, bèn chạy lăng xăng khắp nhà." },
      { "start": 18.0, "en": "He ran into the kitchen and pulled out all the pots and pans. But the thing he was looking for wasn't there. So, he kicked the pots and pans. Then, he ran into the living room and dumped out his mother's sewing basket. But the thing he was looking for wasn't there either. So he kicked the basket across the room.", "ipa": "/hiː ræn ˈɪntuː ðə ˈkɪtʃɪn ænd pʊld aʊt ɔːl ðə pɒts ænd pænz. bʌt ðə θɪŋ hiː wɒz ˈlʊkɪŋ fɔːr ˈwɒznt ðɛər. soʊ, hiː kɪkt ðə pɒts ænd pænz. ðɛn, hiː ræn ˈɪntuː ðə ˈlɪvɪŋ ruːm ænd dʌmpt aʊt hɪz ˈmʌðərz ˈsoʊɪŋ ˈbɑːskɪt. bʌt ðə θɪŋ hiː wɒz ˈlʊkɪŋ fɔːr ˈwɒznt ðɛər ˈaɪðər. soʊ hiː kɪkt ðə ˈbɑːskɪt əˈkrɒs ðə ruːm/", vi: "Cậu kéo xoong chảo trong bếp ra tìm không thấy bèn đá tung lên. Cậu chạy ra phòng khách lật tung giỏ kim chỉ của mẹ rồi lại hất văng chiếc giỏ qua phòng." },
      { "start": 42.0, "en": "He ran into the bathroom and looked behind the toilet and under the tub. He kicked the tub and hurt his toe. 'You'll feel better after your nap,' his mother said, as she carried Gerry into his bedroom.", "ipa": "/hiː ræn ˈɪntuː ðə ˈbɑːθruːm ænd lʊkt bɪˈhaɪnd ðə ˈtɔɪlət ænd ˈʌndər ðə tʌb. hiː kɪkt ðə tʌb ænd hɜːrt hɪz toʊ. juːl fiːl ˈbɛtər ˈɑːftər jɔːr næp, hɪz ˈmʌðər sɛd, æz ʃiː ˈkærid ˈɡɛri ˈɪntuː hɪz ˈbɛdruːm/", vi: "Cậu vào nhà tắm tìm quanh bồn cầu và dưới bồn tắm, đá vào bồn đau cả ngón chân. 'Ngủ một giấc con sẽ đỡ hơn,' mẹ vừa nói vừa bế Gerry vào phòng ngủ." },
      { "start": 58.0, "en": "Gerry stopped screaming and smiled. There was his teddy bear right on his bed—exactly where it had been the whole time.", "ipa": "/ˈɡɛri stɒpt ˈskriːmɪŋ ænd smaɪld. ðɛər wɒz hɪz ˈtɛdi bɛər raɪt ɒn hɪz bɛd—ɪɡˈzæktli wɛər ɪt hæd biːn ðə hoʊl taɪm/", vi: "Gerry nín bặt và nhoẻn miệng cười: Chú gấu bông đang nằm ngoan ngoãn ngay trên giường — đúng chỗ từ đầu đến giờ!" }
    ]
  },
  {
    "day": 17,
    "title": "All in One Family",
    "image": "06 June/images/day_17.webp",
    "audio": "06 June/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "Our family has many different talents and interests. My dad loves playing soccer, while my mom enjoys painting pictures in her quiet studio.", "ipa": "/ˈaʊər ˈfæməli hæz ˈmɛni ˈdɪfrənt ˈtælənts ænd ˈɪntrəsts. maɪ dæd lʌvz ˈpleɪɪŋ ˈsɒkər, waɪl maɪ mɒm ɪnˈdʒɔɪz ˈpeɪntɪŋ ˈpɪktʃərz ɪn hɜːr ˈkwaɪət ˈstjuːdiˌoʊ/", "vi": "Gia đình tôi mỗi người một sở thích và năng khiếu riêng: Bố mê đá bóng, còn mẹ thích vẽ tranh trong phòng tranh yên tĩnh." },
      { "start": 16.0, "en": "My older brother is crazy about computer programming, and my little sister loves singing and dancing all day.", "ipa": "/maɪ ˈoʊldər ˈbrʌðər ɪz ˈkreɪzi əˈbaʊt kəmˈpjuːtər ˈproʊɡræmɪŋ, ænd maɪ ˈlɪtl ˈsɪstər lʌvz ˈsɪŋɪŋ ænd ˈdænsɪŋ ɔːl deɪ/", "vi": "Anh trai tôi say mê lập trình máy tính, còn em gái nhỏ lại thích ca hát nhảy múa suốt ngày." },
      { "start": 27.0, "en": "Even though we are all very different, we love and support each other warmly. Every Sunday evening, we sit together around the living room to share our weekly stories.", "ipa": "/ˈiːvn ðoʊ wiː ɑːr ɔːl ˈvɛri ˈdɪfrənt, wiː lʌv ænd səˈpɔːrt iːtʃ ˈʌðər ˈwɔːrmli. ˈɛvri ˈsʌndeɪ ˈiːvnɪŋ, wiː sɪt təˈɡɛðər əˈraʊnd ðə ˈlɪvɪŋ ruːm tuː ʃɛər ˈaʊər ˈwiːkli ˈstɔːriz/", "vi": "Dù mỗi người một tính cách khác biệt, cả nhà luôn yêu thương và ủng hộ lẫn nhau. Tối Chủ nhật nào cả nhà cũng quây quần bên phòng khách để chia sẻ những câu chuyện trong tuần." },
      { "start": 44.0, "en": "Being different makes our family life colorful and wonderful!", "ipa": "/ˈbiːɪŋ ˈdɪfrənt meɪks ˈaʊər ˈfæməli laɪf ˈkʌlərfʊl ænd ˈwʌndərfʊl!/", "vi": "Chính sự khác biệt đó đã tạo nên một mái ấm gia đình muôn màu rực rỡ và tràn ngập niềm vui!" }
    ]
  },
  {
    "day": 18,
    "title": "Stuffed Animal Parade",
    "image": "06 June/images/day_18.webp",
    "audio": "06 June/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was a good day for a stuffed animal parade. Ben started getting Teddy Bear ready. Teddy Bear's fur was a little clumped, so Ben combed it smooth. Teddy Bear's eyes were a little loose, so Ben asked Mom to sew them on tight. Teddy Bear's clothes were a little dirty, so Ben washed them clean. Finally, Teddy Bear was ready!", "ipa": "/ɪt wɒz ə ɡʊd deɪ fɔːr ə stʌft ˈænɪml pəˈreɪd. bɛn ˈstɑːrtɪd ˈɡɛtɪŋ ˈtɛdi bɛər ˈrɛdi. ˈtɛdi bɛərz fɜːr wɒz ə ˈlɪtl klʌmpt, soʊ bɛn koʊmd ɪt smuːð. ˈtɛdi bɛərz aɪz wɜːr ə ˈlɪtl luːs, soʊ bɛn ɑːskt mɒm tuː soʊ ðɛm ɒn taɪt. ˈtɛdi bɛərz kloʊðz wɜːr ə ˈlɪtl ˈdɜːrti, soʊ bɛn wɒʃt ðɛm kliːn. ˈfaɪnəli, ˈtɛdi bɛər wɒz ˈrɛdi!/", "vi": "Hôm nay là ngày tuyệt vời cho cuộc diễu hành thú bông. Ben chải mượt lông cho Gấu Teddy, nhờ mẹ đơm lại mắt cho chặt và giặt sạch quần áo. Cuối cùng chú gấu đã sẵn sàng!" },
      { "start": 28.0, "en": "Now, Teddy Bear needed something to ride in. Ben fixed up an old shoe box. He coloured it with crayons and put stickers all over it. He made a soft seat for Teddy Bear to sit on. Ben placed Teddy Bear on the seat. Now, Teddy Bear was ready to go!", "ipa": "/naʊ, ˈtɛdi bɛər ˈniːdɪd ˈsʌmθɪŋ tuː raɪd ɪn. bɛn fɪkst ʌp ən oʊld ʃuː bɒks. hiː ˈkʌlərd ɪt wɪð ˈkreɪənz ænd pʊt ˈstɪkərz ɔːl ˈoʊvər ɪt. hiː meɪd ə sɒft siːt fɔːr ˈtɛdi bɛər tuː sɪt ɒn. bɛn pleɪst ˈtɛdi bɛər ɒn ðə siːt. naʊ, ˈtɛdi bɛər wɒz ˈrɛdi tuː ɡoʊ!/", "vi": "Ben biến hộp giày cũ thành xe diễu hành bằng bút màu, dán đầy hình dán và lót đệm êm cho Teddy ngồi. Giờ thì Teddy đã sẵn sàng xuất phát!" },
      { "start": 47.0, "en": "Jack brought his stuffed elephant. Liz brought her stuffed pig. Jane brought her stuffed dog. Each of the stuffed animals rode in a decorated shoe box. The stuffed animal parade started. Ben and Teddy Bear led the way.", "ipa": "/dʒæk brɔːt hɪz stʌft ˈɛlɪfənt. lɪz brɔːt hɜːr stʌft pɪɡ. dʒeɪn brɔːt hɜːr stʌft dɒɡ. iːtʃ əv ðə stʌft ˈænɪmlz roʊd ɪn ə ˈdɛkəreɪtɪd ʃuː bɒks. ðə stʌft ˈænɪml pəˈreɪd ˈstɑːrtɪd. bɛn ænd ˈtɛdi bɛər lɛd ðə weɪ/", "vi": "Jack mang voi bông, Liz mang heo bông, Jane mang cún bông. Mỗi con thú ngồi kiêu hãnh trên chiếc hộp giày rực rỡ. Buổi diễu hành bắt đầu với Ben và Teddy dẫn đầu!" }
    ]
  },
  {
    "day": 19,
    "title": "Getting in Shape",
    "image": "06 June/images/day_19.webp",
    "audio": "06 June/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "My grandma was getting older. She had a hard time walking. One day, her friend suggested that she try Tai Chi.", "ipa": "/maɪ ˈɡrænmɑː wɒz ˈɡɛtɪŋ ˈoʊldər. ʃiː hæd ə hɑːrd taɪm ˈwɔːkɪŋ. wʌn deɪ, hɜːr frɛnd səˈdʒɛstɪd ðæt ʃiː traɪ taɪ tʃiː/", "vi": "Bà tôi ngày càng cao tuổi và đi lại khó khăn. Một ngày nọ, bạn của bà khuyên nên thử tập Thái Cực Quyền." },
      { "start": 14.0, "en": "'Tai Chi?' asked my grandmother. 'Is that a type of tea?' Her friend laughed and explained, 'It is a type of exercise that is very slow and easy on the body.'", "ipa": "/taɪ tʃiː?, ɑːskt maɪ ˈɡrændˌmʌðər. ɪz ðæt ə taɪp əv tiː? hɜːr frɛnd lɑːft ænd ɪkˈspleɪnd, ɪt ɪz ə taɪp əv ˈɛksərsaɪz ðæt ɪz ˈvɛri sloʊ ænd ˈiːzi ɒn ðə ˈbɒdi/", "vi": "'Tai Chi á?' bà tôi hỏi. 'Đó là một loại trà à?' Bạn bà bật cười giải thích: 'Đó là một môn thể dục vô cùng chậm rãi và rất nhẹ nhàng cho cơ thể.'" },
      { "start": 26.0, "en": "To help my grandma, our whole family decided to try it. We went with my grandmother to a class.", "ipa": "/tuː hɛlp maɪ ˈɡrænmɑː, ˈaʊər hoʊl ˈfæməli dɪˈsaɪdɪd tuː traɪ ɪt. wiː wɛnt wɪð maɪ ˈɡrændˌmʌðər tuː ə klɑːs/", "vi": "Để giúp đỡ bà, cả nhà tôi quyết định cùng thử tập. Chúng tôi đã cùng bà đến một lớp học." },
      { "start": 36.0, "en": "It looked easy... until I tried it. Even my older brother fell a few times trying to do the movements and he is a soccer player!", "ipa": "/ɪt lʊkt ˈiːzi... ənˈtɪl aɪ traɪd ɪt. ˈiːvn maɪ ˈoʊldər ˈbrʌðər fɛl ə fjuː taɪmz ˈtraɪɪŋ tuː duː ðə ˈmuːvmənts ænd hiː ɪz ə ˈsɒkər ˈpleɪər/", "vi": "Trông có vẻ dễ dàng... cho đến khi tôi tự mình thử sức. Ngay cả anh trai tôi — một cầu thủ đá bóng — cũng ngã dúi dụi vài lần khi làm theo các động tác!" },
      { "start": 51.0, "en": "But my grandma liked Tai Chi. She continued going to the classes twice a week. A year later, Grandma was almost 80 years old and she had no trouble walking anymore.", "ipa": "/bʌt maɪ ˈɡrænmɑː laɪkt taɪ tʃiː. ʃiː kənˈtɪnyuːd ˈɡoʊɪŋ tuː ðə ˈklɑːsɪz twaɪs ə wiːk. ə jɪər ˈleɪtər, ˈɡrænmɑː wɒz ˈɔːlmoʊst ˈeɪti jɪərz oʊld ænd ʃiː hæd noʊ ˈtrʌbl ˈwɔːkɪŋ ˈɛniˌmɔːr/", "vi": "Thế nhưng bà tôi lại rất thích Tai Chi. Bà đều đặn đến lớp hai lần một tuần. Một năm sau, khi đã gần 80 tuổi, bà chẳng còn gặp chút khó khăn nào trong việc đi lại nữa." },
      { "start": 65.0, "en": "She proved that it is never too late to get in shape.", "ipa": "/ʃiː pruːvd ðæt ɪt ɪz ˈnɛvər tuː leɪt tuː ɡɛt ɪn ʃeɪp/", "vi": "Bà đã chứng minh rằng không bao giờ là quá muộn để rèn luyện sức khỏe." }
    ]
  },
  {
    "day": 20,
    "title": "Summer on the Farm",
    "image": "06 June/images/day_20.webp",
    "audio": "06 June/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "Last summer, I worked on my uncle's farm. I have never worked so hard in my life. Every day, he got up at 5 a.m. to feed the animals.", "ipa": "/lɑːst ˈsʌmər, aɪ wɜːrkt ɒn maɪ ˈʌŋklz fɑːrm. aɪ hæv ˈnɛvər wɜːrkt soʊ hɑːrd ɪn maɪ laɪf. ˈɛvri deɪ, hiː ɡɒt ʌp æt faɪv eɪ-ɛm tuː fiːd ðə ˈænɪmlz/", "vi": "Mùa hè năm ngoái, tôi làm việc ở nông trại của chú. Chưa bao giờ trong đời tôi phải làm việc vất vả đến thế. Ngày nào tôi cũng dậy từ 5 giờ sáng để cho động vật ăn." },
      { "start": 17.0, "en": "The hardest work of all was called 'haying'. That means gathering all the hay in the fields. Hay is like tall grass. The animals eat it. You need a huge amount to feed all the animals on the farm.", "ipa": "/ðə ˈhɑːrdɪst wɜːrk əv ɔːl wɒz kɔːld ˈheɪɪŋ. ðæt miːnz ˈɡæðərɪŋ ɔːl ðə heɪ ɪn ðə fiːldz. heɪ ɪz laɪk tɔːl ɡræs. ði ˈænɪmlz iːt ɪt. juː niːd ə hjuːdʒ əˈmaʊnt tuː fiːd ɔːl ði ˈænɪmlz ɒn ðə fɑːrm/", "vi": "Công việc nặng nhọc nhất gọi là 'làm cỏ khô'. Nghĩa là gom hết cỏ khô ngoài đồng. Cỏ khô giống như cỏ cao mà loài vật rất thích ăn, và trang trại cần một lượng khổng lồ để nuôi lũ thú." },
      { "start": 36.0, "en": "A big machine cuts the hay and wraps it into big squares. The squares weigh at least 30 kilograms. You have to pick them up and throw them onto a big wagon. That summer, I lifted thousands of them.", "ipa": "/ə bɪɡ məˈʃiːn kʌts ðə heɪ ænd ræps ɪt ˈɪntuː bɪɡ skwɛərz. ðə skwɛərz weɪ æt liːst ˈθɜːrti ˈkɪləˌɡræmz. juː hæv tuː pɪk ðɛm ʌp ænd θroʊ ðɛm ˈɒntuː ə bɪɡ ˈwæɡən. ðæt ˈsʌmər, aɪ ˈlɪftɪd ˈθaʊzndz əv ðɛm/", "vi": "Một cỗ máy lớn cắt cỏ và cuộn thành các khối vuông nặng ít nhất 30 kg. Bạn phải nhấc chúng lên và ném lên chiếc xe kéo lớn. Mùa hè đó, tôi đã khuân vác hàng ngàn khối cỏ như vậy." },
      { "start": 56.0, "en": "When I got home at the end of the summer, none of my clothes fit me. I had grown such big muscles! That summer, I learned that hard work really pays off. Now I can't wait until next year!", "ipa": "/wɛn aɪ ɡɒt hoʊm æt ði ɛnd əv ðə ˈsʌmər, nʌn əv maɪ kloʊðz fɪt miː. aɪ hæd ɡroʊn sʌtʃ bɪɡ ˈmʌslz! ðæt ˈsʌmər, aɪ lɜːrnd ðæt hɑːrd wɜːrk ˈrɪəli peɪz ɒf. naʊ aɪ kænt weɪt ənˈtɪl nɛkst jɪər!/", "vi": "Khi về nhà vào cuối mùa hè, chẳng bộ quần áo nào vừa với tôi nữa. Tôi đã phát triển những cơ bắp cuồn cuộn! Mùa hè đó dạy tôi rằng làm việc chăm chỉ thực sự mang lại thành quả xứng đáng, và giờ tôi đang nóng lòng mong tới năm sau!" }
    ]
  },
  {
    "day": 21,
    "title": "Half Full",
    "image": "06 June/images/day_21.webp",
    "audio": "06 June/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "There was once a young man who always saw the bad side of things.", "ipa": "/ðɛər wɒz wʌns ə jʌŋ mæn huː ˈɔːlweɪz sɔː ðə bæd saɪd əv θɪŋz/", "vi": "Ngày xửa ngày xưa có một chàng thanh niên lúc nào cũng nhìn nhận mọi việc theo chiều hướng tiêu cực." },
      { "start": 12.0, "en": "One day, he and his friend went on a trip to an island. The wind blew their boat away. They called for help, but it would be at least a couple of hours before anyone would find them.", "ipa": "/wʌn deɪ, hiː ænd hɪz frɛnd wɛnt ɒn ə trɪp tuː ən ˈaɪlənd. ðə wɪnd bluː ðɛər boʊt əˈweɪ. ðeɪ kɔːld fɔːr hɛlp, bʌt ɪt wʊd biː æt liːst ə ˈkʌpl əv ˈaʊərz bɪˈfɔːr ˈɛniˌwʌn wʊd faɪnd ðɛm/", "vi": "Một hôm, anh và bạn cùng đi chơi đảo. Gió thổi bay mất chiếc thuyền của họ. Cả hai gọi cứu trợ, nhưng phải mất ít nhất vài tiếng mới có người đến tìm." },
      { "start": 28.0, "en": "As they waited, the young man complained about the heat and the bad luck they were having.", "ipa": "/æz ðeɪ ˈweɪtɪd, ðə jʌŋ mæn kəmˈpleɪnd əˈbaʊt ðə hiːt ænd ðə bæd lʌk ðeɪ wɜːr ˈhævɪŋ/", "vi": "Trong lúc chờ đợi, chàng trai liên tục càu nhàu về thời tiết oi bức và vận xui đeo bám." },
      { "start": 37.0, "en": "When he reached for their water bottle, he said, 'Oh no! The water bottle is half empty!' Then his friend looked at the bottle and said, 'But it is half full too.'", "ipa": "/wɛn hiː riːtʃt fɔːr ðɛər ˈwɔːtər ˈbɒtl, hiː sɛd, oʊ noʊ! ðə ˈwɔːtər ˈbɒtl ɪz hæf ˈɛmpti! ðɛn hɪz frɛnd lʊkt æt ðə ˈbɒtl ænd sɛd, bʌt ɪt ɪz hæf fʊl tuː/", "vi": "Khi với lấy chai nước, anh ta kêu lên: 'Ôi không! Chai nước vơi một nửa rồi!' Bạn anh liền nhìn vào chai và điềm tĩnh đáp: 'Nhưng nó cũng còn đầy một nửa mà.'" },
      { "start": 52.0, "en": "The young man looked at his friend very seriously. A smile slowly appeared on his face and they both laughed. He thought, 'She is right. Being negative doesn't help.'", "ipa": "/ðə jʌŋ mæn lʊkt æt hɪz frɛnd ˈvɛri ˈsɪriəsli. ə smaɪl ˈsloʊli əˈpɪərd ɒn hɪz feɪs ænd ðeɪ boʊθ lɑːft. hiː θɔːt, ʃiː ɪz raɪt. ˈbiːɪŋ ˈnɛɡətɪv ˈdʌznt hɛlp/", "vi": "Chàng trai nhìn bạn đầy suy ngẫm. Nụ cười từ từ nở trên môi và cả hai cùng bật cười. Anh thầm nghĩ: 'Cậu ấy nói đúng. Tiêu cực chẳng giải quyết được gì.'" },
      { "start": 67.0, "en": "Now the man is much older and has a happy family. He became a person who sees the glass half full, not half empty!", "ipa": "/naʊ ðə mæn ɪz mʌtʃ ˈoʊldər ænd hæz ə ˈhæpi ˈfæməli. hiː bɪˈkeɪm ə ˈpɜːrsn huː siːz ðə ɡlɑːs hæf fʊl, nɒt hæf ˈɛmpti!/", "vi": "Giờ đây anh ấy đã lớn tuổi và có một gia đình hạnh phúc. Anh đã trở thành người luôn nhìn nhận mọi việc theo hướng tích cực, lạc quan!" }
    ]
  },
  {
    "day": 22,
    "title": "Daddy-Daughter Day",
    "image": "06 June/images/day_22.webp",
    "audio": "06 June/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "Today after school, Sara and her dad are going to the beach. Sara loves splashing in the waves and digging for sand crabs. Afterwards, they will walk to the ice cream shop. Sara likes the bubble gum flavour ice cream there. It has real gumballs in it!", "ipa": "/təˈdeɪ ˈɑːftər skuːl, ˈsɛərə ænd hɜːr dæd ɑːr ˈɡoʊɪŋ tuː ðə biːtʃ. ˈsɛərə lʌvz ˈsplæʃɪŋ ɪn ðə weɪvz ænd ˈdɪɡɪŋ fɔːr sænd kræbz. ˈɑːftərwərdz, ðeɪ wɪl wɔːk tuː ði aɪs kriːm ʃɒp. ˈsɛərə laɪks ðə ˈbʌbl ɡʌm ˈfleɪvər aɪs kriːm ðɛər. ɪt hæz riːəl ˈɡʌmˌbɔːlz ɪn ɪt/", "vi": "Hôm nay tan học, Sara và bố sẽ đi ra biển. Sara rất thích vầy nước sóng vỗ và đào bắt cua cát. Sau đó, hai bố con sẽ ghé tiệm kem. Sara thích kem vị kẹo cao su ở đó vì có cả những viên kẹo thật trong viên kem!" },
      { "start": 23.0, "en": "'Today is Daddy-Daughter Day!' Sara told her friend, Rachel. 'That's great,' Rachel said. She sounded sad. 'What's the matter?' 'You're just lucky, that's all.' Rachel didn't have a dad. Sara understood. Then, Sara had an idea. 'Would you like to spend the day with me and my dad?'", "ipa": "/təˈdeɪ ɪz ˈdædi-ˈdɔːtər deɪ!, ˈsɛərə toʊld hɜːr frɛnd, ˈreɪtʃəl. ðæts ɡreɪt, ˈreɪtʃəl sɛd. ʃiː ˈsaʊndɪd sæd. wɒts ðə ˈmætər? jʊər dʒʌst ˈlʌki, ðæts ɔːl. ˈreɪtʃəl ˈdɪdnt hæv ə dæd. ˈsɛərə ˌʌndərˈstʊd. ðɛn, ˈsɛərə hæd ən aɪˈdiːə. wʊd juː laɪk tuː spɛnd ðə deɪ wɪð miː ænd maɪ dæd?/", "vi": "'Hôm nay là Ngày Bố và Con Gái đấy!' Sara khoe với bạn Rachel. 'Tuyệt quá nhỉ,' Rachel nói với giọng buồn buồn. 'Cậu sao thế?' 'Cậu may mắn thật đấy, thế thôi.' Rachel không có bố. Sara hiểu ra và nảy ra ý kiến: 'Cậu có muốn đi chơi cùng tớ và bố tớ không?'" },
      { "start": 48.0, "en": "'It's your special day,' replied Rachel. But Sara thought the idea was grand. And so, the three of them spent the afternoon together. They got the bubble gum ice cream and blew bubbles all the way home. Sara discovered that sharing her special day with her friend made it even more special.", "ipa": "/ɪts jɔːr ˈspɛʃl deɪ, rɪˈplaɪd ˈreɪtʃəl. bʌt ˈsɛərə θɔːt ði aɪˈdiːə wɒz ɡrænd. ænd soʊ, ðə θriː əv ðɛm spɛnt ði ˌɑːftərˈnuːn təˈɡɛðər. ðeɪ ɡɒt ðə ˈbʌbl ɡʌm aɪs kriːm ænd bluː ˈbʌblz ɔːl ðə weɪ hoʊm. ˈsɛərə dɪsˈkʌvərd ðæt ˈʃɛərɪŋ hɜːr ˈspɛʃl deɪ wɪð hɜːr frɛnd meɪd ɪt ˈiːvn mɔːr ˈspɛʃl/", "vi": "'Đây là ngày đặc biệt của cậu mà,' Rachel đáp. Nhưng Sara thấy đó là một ý hay. Thế là cả ba cùng nhau trải qua buổi chiều vui vẻ. Họ ăn kem kẹo cao su và thổi bong bóng suốt quãng đường về nhà. Sara nhận ra rằng việc sẻ chia ngày vui với bạn bè còn làm cho ngày ấy trở nên đặc biệt hơn gấp bội." }
    ]
  },
  {
    "day": 23,
    "title": "The Key",
    "image": "06 June/images/day_23.webp",
    "audio": "06 June/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. Smith and his wife were coming back from shopping. Suddenly, Mr. Smith said, 'Oh my! I can't find my keys.' Mrs. Smith started looking for the keys, but she couldn't find them either.", "ipa": "/ˈmɪstər smɪθ ænd hɪz waɪf wɜːr ˈkʌmɪŋ bæk frɒm ˈʃɒpɪŋ. ˈsʌdənli, ˈmɪstər smɪθ sɛd, oʊ maɪ! aɪ kænt faɪnd maɪ kiːz. ˈmɪsɪz smɪθ ˈstɑːrtɪd ˈlʊkɪŋ fɔːr ðə kiːz, bʌt ʃiː ˈkʊdnt faɪnd ðɛm ˈaɪðər/", "vi": "Ông Smith và vợ vừa đi mua sắm về. Bỗng ông kêu lên: 'Ôi trời! Tôi không thấy chìa khóa đâu cả.' Bà Smith liền phụ tìm nhưng cũng không thấy." },
      { "start": 21.0, "en": "'Is something wrong?' asked their neighbour, Mr. Oriel. 'We lost our keys,' said Mr. Smith. Mr. Oriel also joined the search for the missing keys. But, he didn't have any luck either.", "ipa": "/ɪz ˈsʌmθɪŋ rɒŋ?, ɑːskt ðɛər ˈneɪbər, ˈmɪstər ˈɔːriəl. wiː lɒst ˈaʊər kiːz, sɛd ˈmɪstər smɪθ. ˈmɪstər ˈɔːriəl ˈɔːlsoʊ dʒɔɪnd ðə sɜːrtʃ fɔːr ðə ˈmɪsɪŋ kiːz. bʌt, hiː ˈdɪdnt hæv ˈɛni lʌk ˈaɪðər/", "vi": "'Có chuyện gì thế ạ?' bác hàng xóm Oriel hỏi. 'Chúng tôi mất chìa khóa rồi,' ông Smith đáp. Bác Oriel cũng xắn tay tìm giúp nhưng đành bó tay." },
      { "start": 38.0, "en": "After almost an hour of searching, Mr. Smith decided to break the lock on the door. 'I have another lock you can use,' said Mr. Oriel. Soon, they broke the lock and put a new one on.", "ipa": "/ˈɑːftər ˈɔːlmoʊst ən ˈaʊər əv ˈsɜːrtʃɪŋ, ˈmɪstər smɪθ dɪˈsaɪdɪd tuː breɪk ðə lɒk ɒn ðə dɔːr. aɪ hæv əˈnʌðər lɒk juː kæn juːz, sɛd ˈmɪstər ˈɔːriəl. suːn, ðeɪ broʊk ðə lɒk ænd pʊt ə njuː wʌn ɒn/", "vi": "Tìm kiếm gần một tiếng đồng hồ, ông Smith quyết định phá khóa cửa. 'Tôi có ổ khóa khác cho anh dùng tạm,' bác Oriel nói. Thế là họ đập bỏ ổ khóa cũ và lắp ổ khóa mới vào." },
      { "start": 56.0, "en": "'Here is the key for your new lock,' said Mr. Oriel. 'Thank you,' said Mr. Smith. 'I'll put it on my new keychain that I have on my belt.' Mrs. Smith and Mr. Oriel looked at him. 'Oh my!' said Mr. Smith. 'I forgot that I put the key on my belt. I had the key the whole time!'", "ipa": "/hɪər ɪz ðə kiː fɔːr jɔːr njuː lɒk, sɛd ˈmɪstər ˈɔːriəl. ˈθæŋk juː, sɛd ˈmɪstər smɪθ. aɪl pʊt ɪt ɒn maɪ njuː ˈkiːˌtʃeɪn ðæt aɪ hæv ɒn maɪ bɛlt. ˈmɪsɪz smɪθ ænd ˈmɪstər ˈɔːriəl lʊkt æt hɪm. oʊ maɪ!, sɛd ˈmɪstər smɪθ. aɪ fərˈɡɒt ðæt aɪ pʊt ðə kiː ɒn maɪ bɛlt. aɪ hæd ðə kiː ðə hoʊl taɪm!/", "vi": "'Đây là chìa khóa ổ mới nhé,' bác Oriel đưa. 'Cảm ơn bác,' ông Smith nói. 'Để tôi tròng vào móc khóa ở thắt lưng.' Vợ ông và bác Oriel nhìn chằm chằm vào ông. 'Ôi trời!' ông Smith ngớ người. 'Tôi quên mất là mình đã kẹp chìa khóa vào thắt lưng. Hóa ra tôi cầm chìa khóa suốt nãy giờ!'" }
    ]
  },
  {
    "day": 24,
    "title": "I Can Do It!",
    "image": "06 June/images/day_24.webp",
    "audio": "06 June/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was Saturday morning and Adam had just gotten his first real bike. 'I can't do it!' Adam sat down on the ground next to his bike.", "ipa": "/ɪt wɒz ˈsætərdeɪ ˈmɔːrnɪŋ ænd ˈædəm hæd dʒʌst ˈɡɒtn hɪz fɜːrst riːl baɪk. aɪ kænt duː ɪt!, ˈædəm sæt daʊn ɒn ðə ɡraʊnd nɛkst tuː hɪz baɪk/", "vi": "Sáng thứ Bảy, Adam vừa nhận được chiếc xe đạp thật sự đầu tiên trong đời. 'Con không tài nào đi được đâu!' Adam sụt sùi ngồi bệt xuống đất cạnh chiếc xe." },
      { "start": 17.0, "en": "'You can,' said his dad. 'Maybe not the first time you try, or even the second time. The most important thing is to believe in yourself.'", "ipa": "/juː kæn, sɛd hɪz dæd. ˈmeɪbi nɒt ðə fɜːrst taɪm juː traɪ, ɔːr ˈiːvn ðə ˈsɛkənd taɪm. ðə moʊst ɪmˈpɔːrtənt θɪŋ ɪz tuː bɪˈliːv ɪn jɔːrˈsɛlf/", "vi": "'Con làm được mà,' bố động viên. 'Có thể không thành công ngay lần đầu hay lần thứ hai. Điều quan trọng nhất là phải tin vào chính mình.'" },
      { "start": 29.0, "en": "'But I can't!' Adam stormed into the house. Learning to ride a two-wheeler was just too hard. The next day, Adam's new bike was up in the rafters of the garage.", "ipa": "/bʌt aɪ kænt!, ˈædəm stɔːrmt ˈɪntuː ðə haʊs. ˈlɜːrnɪŋ tuː raɪd ə tuː-ˈwiːlər wɒz dʒʌst tuː hɑːrd. ðə nɛkst deɪ, ˈædəmz njuː baɪk wɒz ʌp ɪn ðə ˈrɑːftərz əv ðə ɡəˈrɑːʒ/", "vi": "'Nhưng con không thể!' Adam tức giận chạy ù vào nhà. Học đạp xe hai bánh quá khó đối với cậu. Hôm sau, chiếc xe đạp mới của Adam đã bị treo lên xà nhà để xe." },
      { "start": 44.0, "en": "'Hey, Dad! What's my bike doing up there?' 'Since you can't ride it, I thought I would move it out of the way.' Adam didn't like seeing his bike put away. He closed his eyes and tried to picture himself riding it. 'Dad, I believe I can ride it now!'", "ipa": "/heɪ, dæd! wɒts maɪ baɪk ˈduːɪŋ ʌp ðɛər? sɪns juː kænt raɪd ɪt, aɪ θɔːt aɪ wʊd muːv ɪt aʊt əv ðə weɪ. ˈædəm ˈdɪdnt laɪk ˈsiːɪŋ hɪz baɪk pʊt əˈweɪ. hiː cloʊzd hɪz aɪz ænd traɪd tuː ˈpɪktʃər hɪmˈsɛlf ˈraɪdɪŋ ɪt. dæd, aɪ bɪˈliːv aɪ kæn raɪd ɪt naʊ!/", "vi": "'Ơ bố ơi! Sao xe đạp của con lại ở trên đó thế ạ?' 'Vì con không đi được nên bố cất đi cho đỡ vướng.' Adam không thích nhìn chiếc xe bị cất đi chút nào. Cậu nhắm mắt lại và tưởng tượng cảnh mình đang chạy xe. 'Bố ơi, con tin là giờ con đi được rồi!'" },
      { "start": 62.0, "en": "It took three more tries, but Adam didn't give up. Before the day was over, he was riding like the wind!", "ipa": "/ɪt tʊk θriː mɔːr traɪz, bʌt ˈædəm ˈdɪdnt ɡɪv ʌp. bɪˈfɔːr ðə deɪ wɒz ˈoʊvər, hiː wɒz ˈraɪdɪŋ laɪk ðə wɪnd!/", "vi": "Thêm ba lần ngã nữa nhưng Adam không hề bỏ cuộc. Trước khi ngày kết thúc, cậu bé đã phóng xe nhanh như bay theo gió!" }
    ]
  },
  {
    "day": 25,
    "title": "Not Goodbye",
    "image": "06 June/images/day_25.webp",
    "audio": "06 June/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "Max was my bird. He lived to be almost nine years old. When he was young, Max was very playful. He would sit on my shoulder and bob his head up and down. He even played with our cat!", "ipa": "/mæks wɒz maɪ bɜːrd. hiː lɪvd tuː biː ˈɔːlmoʊst naɪn jɪərz oʊld. wɛn hiː wɒz jʌŋ, mæks wɒz ˈvɛri ˈpleɪfʊl. hiː wʊd sɪt ɒn maɪ ˈʃoʊldər ænd bɒb hɪz hɛd ʌp ænd daʊn. hiː ˈiːvn pleɪd wɪð ˈaʊər kæt!/", "vi": "Max là chú chim cưng của tôi. Chú sống được gần chín tuổi. Hồi nhỏ, Max rất tinh nghịch. Chú hay đậu trên vai tôi, gật gù cái đầu lên xuống và thậm chí còn đùa giỡn với mèo nhà tôi!" },
      { "start": 21.0, "en": "The backyard was his whole world. He would sit in the window and watch the other birds all day.", "ipa": "/ðə ˈbækˌjɑːrd wɒz hɪz hoʊl wɜːrld. hiː wʊd sɪt ɪn ðə ˈwɪndoʊ ænd wɒtʃ ði ˈʌðər bɜːrdz ɔːl deɪ/", "vi": "Khu vườn sau nhà chính là cả thế giới của chú. Chú thường ngồi bên cửa sổ ngắm nhìn những chú chim khác suốt cả ngày." },
      { "start": 32.0, "en": "One day, I woke up and brought Max his water. He wasn't sitting on his perch. He was lying on the bottom of the cage.", "ipa": "/wʌn deɪ, aɪ woʊk ʌp ænd brɔːt mæks hɪz ˈwɔːtər. hiː ˈwɒznt ˈsɪtɪŋ ɒn hɪz pɜːrtʃ. hiː wɒz ˈlaɪɪŋ ɒn ðə ˈbɒtəm əv ðə keɪdʒ/", "vi": "Một hôm, tôi thức dậy mang nước cho Max. Chú không còn đậu trên thanh gỗ nữa mà nằm dưới đáy lồng." },
      { "start": 44.0, "en": "My great friend Max was gone. It was very hard. But I knew that he had a good and long life. We decided to bury him in the backyard. Now he is part of that little world he loved so much.", "ipa": "/maɪ ɡreɪt frɛnd mæks wɒz ɡɒn. ɪt wɒz ˈvɛri hɑːrd. bʌt aɪ nuː ðæt hiː hæd ə ɡʊd ænd lɔːŋ laɪf. wiː dɪˈsaɪdɪd tuː ˈbɛri hɪm ɪn ðə ˈbækˌjɑːrd. naʊ hiː ɪz pɑːrt əv ðæt ˈlɪtl wɜːrld hiː lʌvd soʊ mʌtʃ/", "vi": "Người bạn tuyệt vời Max đã ra đi mãi mãi. Thật đau đớn biết bao. Nhưng tôi biết chú đã có một cuộc đời trọn vẹn và dài lâu. Chúng tôi quyết định chôn chú ở góc vườn. Giờ đây chú đã trở thành một phần của thế giới nhỏ bé mà chú từng hết mực yêu quý." },
      { "start": 62.0, "en": "It makes me feel better to know that Max is still with us in a way. He is back with nature in our backyard. We will never have to say goodbye.", "ipa": "/ɪt meɪks miː fiːl ˈbɛtər tuː noʊ ðæt mæks ɪz stɪl wɪð ʌs ɪn ə weɪ. hiː ɪz bæk wɪð ˈneɪtʃər ɪn ˈaʊər ˈbækˌjɑːrd. wiː wɪl ˈnɛvər hæv tuː seɪ ˌɡʊdˈbaɪ/", "vi": "Tôi thấy ấm lòng khi biết rằng Max vẫn luôn ở bên chúng ta theo một cách nào đó. Chú đã hòa mình vào thiên nhiên ở khu vườn sau nhà. Chúng ta sẽ chẳng bao giờ phải nói lời tạm biệt." }
    ]
  },
  {
    "day": 26,
    "title": "Why Is the Sky Blue?",
    "image": "06 June/images/day_26.webp",
    "audio": "06 June/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "Betty is a smart little girl. She is always asking questions. 'Mommy, why is the sky blue?' Betty asks.", "ipa": "/ˈbɛti ɪz ə smɑːrt ˈlɪtl ɡɜːrl. ʃiː ɪz ˈɔːlweɪz ˈɑːskɪŋ ˈkwɛstʃənz. ˈmɒmi, waɪ ɪz ðə skaɪ bluː?, ˈbɛti ɑːsks/", vi: "Betty là một cô bé thông minh và luôn tò mò hỏi han mọi thứ. 'Mẹ ơi, tại sao bầu trời lại có màu xanh dương?' Betty hỏi." },
      { "start": 16.0, "en": "Little Betty really wants to know the answer. 'Why is it not red or green? Why is it not black or white? Why, Mommy? Why is the sky blue?'", "ipa": "/ˈlɪtl ˈbɛti ˈrɪəli wɒnts tuː noʊ ði ˈɑːnsər. waɪ ɪz ɪt nɒt rɛd ɔːr ɡriːn? waɪ ɪz ɪt nɒt blæk ɔːr waɪt? waɪ, ˈmɒmi? waɪ ɪz ðə skaɪ bluː?/", "vi": "Bé Betty rất muốn biết câu trả lời. 'Sao trời không màu đỏ hay xanh lá? Sao không phải đen hay trắng? Tại sao vậy mẹ? Tại sao bầu trời lại màu xanh dương?'" },
      { "start": 28.0, "en": "Betty's mom looks at her daughter. The answer is not easy to understand. But she tries to explain it in the simplest way possible.", "ipa": "/ˈbɛtiz mɒm lʊks æt hɜːr ˈdɔːtər. ði ˈɑːnsər ɪz nɒt ˈiːzi tuː ˌʌndərˈstænd. bʌt ʃiː traɪz tuː ɪkˈspleɪn ɪt ɪn ðə ˈsɪmplɪst weɪ ˈpɒsəbl/", "vi": "Mẹ Betty mỉm cười nhìn con gái. Câu trả lời vốn không dễ hiểu chút nào, nhưng mẹ cố gắng giải thích theo cách đơn giản nhất có thể." },
      { "start": 42.0, "en": "She says, 'The sun gives off light that has all the colours of the rainbow in it—red, orange, yellow, green, blue, and violet.'", "ipa": "/ʃiː sɛz, ðə sʌn ɡɪvz ɒf laɪt ðæt hæz ɔːl ðə ˈkʌlərz əv ðə ˈreɪnˌboʊ ɪn ɪt—rɛd, ˈɒrɪndʒ, ˈjɛloʊ, ɡriːn, bluː, ænd ˈvaɪəlɪt/", "vi": "Mẹ giảng giải: 'Ánh sáng mặt trời chiếu ra chứa tất cả các màu của cầu vồng — đỏ, cam, vàng, xanh lá, xanh dương và tím.'" },
      { "start": 57.0, "en": "She continues, 'When the light travels to earth, it meets the small particles in the air. The light bounces off these particles and spreads the different colours all over the sky. Blue light spreads the most. This is why we see a blue sky.'", "ipa": "/ʃiː kənˈtɪnjuːz, wɛn ðə laɪt ˈtrævlz tuː ɜːrθ, ɪt miːts ðə smɔːl ˈpɑːrtɪklz ɪn ðə ɛər. ðə laɪt ˈbaʊnsɪz ɔːf ðiːz ˈpɑːrtɪklz ænd sprɛdz ðə ˈdɪfrənt ˈkʌlərz ɔːl ˈoʊvər ðə skaɪ. bluː laɪt sprɛdz ðə moʊst. ðɪs ɪz waɪ wiː siː a bluː skaɪ/", "vi": "Mẹ tiếp tục: 'Khi ánh sáng truyền đến Trái Đất, nó gặp những hạt bụi nhỏ li ti trong không khí. Ánh sáng va chạm bật nảy và tán xạ các màu khắp bầu trời. Ánh sáng xanh khuếch tán mạnh nhất, đó là lý do ta nhìn thấy bầu trời màu xanh.'" },
      { "start": 76.0, "en": "Betty looks up at the sky. She sees blue. She understands a little now. When she is older, she will understand more.", "ipa": "/ˈbɛti lʊks ʌp æt ðə skaɪ. ʃiː siːz bluː. ʃiː ˌʌndərˈstændz ə ˈlɪtl naʊ. wɛn ʃiː ɪz ˈoʊldər, ʃiː wɪl ˌʌndərˈstænd mɔːr/", "vi": "Betty ngước nhìn lên bầu trời, cô bé thấy một màu xanh bao la và đã lỡ hiểu thêm một chút. Lớn lên chắc chắn em sẽ hiểu sâu hơn nữa." }
    ]
  },
  {
    "day": 27,
    "title": "Save Water",
    "image": "06 June/images/day_27.webp",
    "audio": "06 June/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "Drip. Drip. Drip. One drop at a time. Brian watches the small drops of water coming from the water tap. The tap leaks.", "ipa": "/drɪp. drɪp. drɪp. wʌn drɒp æt ə taɪm. ˈbraɪən ˈwɒtʃɪz ðə smɔːl drɒps əv ˈwɔːtər ˈkʌmɪŋ frɒm ðə ˈwɔːtər tæp. ðə tæp liːks/", "vi": "Tí tách. Tí tách. Từng giọt một. Brian ngắm nhìn những giọt nước rỉ ra từ vòi nước. Vòi nước đang bị rò rỉ." },
      { "start": 16.0, "en": "It is only one small drop of water at a time. How can this hurt? Well, think about this. There are 3,500 drops of water in one litre. Add up all the drips coming from the leaking tap in the bathroom and that is a lot of wasted water.", "ipa": "/ɪt ɪz ˈoʊnli wʌn smɔːl drɒp əv ˈwɔːtər ænd aɪ tæp. haʊ kæn ðɪs hɜːrt? wɛl, θɪŋk əˈbaʊt ðɪs. ðɛər ɑːr ˈθriː ˈθaʊznd faɪv ˈhʌndrəd drɒps əv ˈwɔːtər ɪn wʌn ˈliːtər. æd ʌp ɔːl ðə drɪps ˈkʌmɪŋ frɒm ðə ˈliːkɪŋ tæp ɪn ðə ˈbɑːθruːm ænd ðæt ɪz ə lɒt əv ˈweɪstɪd ˈwɔːtər/", "vi": "Chỉ là một giọt nước nhỏ mỗi lần thì có hại gì đâu cơ chứ? Nhưng hãy ngẫm xem: Có tới 3.500 giọt nước trong một lít. Tính tổng số giọt rỉ ra từ chiếc vòi hỏng trong nhà tắm thì đó là một lượng nước lãng phí khổng lồ." },
      { "start": 35.0, "en": "When Brian's father gets home, Brian says, 'I want to do something to save water in our house.'", "ipa": "/wɛn ˈbraɪənz ˈfɑːðər ɡɛts hoʊm, ˈbraɪən sɛz, aɪ wɒnt tuː duː ˈsʌmθɪŋ tuː seɪv ˈwɔːtər ɪn ˈaʊər haʊs/", vi: "Khi bố đi làm về, Brian liền nói: 'Con muốn làm gì đó để tiết kiệm nước cho nhà mình.'" },
      { "start": 46.0, "en": "Brian and his father fix the taps. This makes Brian very happy. His father says, 'Now, let's see what else we can do to save more water.'", "ipa": "/ˈbraɪən ænd hɪz ˈfɑːðər fɪks ðə tæps. ðɪs meɪks ˈbraɪən ˈvɛri ˈhæpi. hɪz ˈfɑːðər sɛz, naʊ, lɛts siː wɒt ɛls wiː kæn duː tuː seɪv mɔːr ˈwɔːtər/", vi: "Brian cùng bố sửa lại các vòi nước. Việc này làm cậu rất vui. Bố bảo: 'Giờ thì xem chúng ta có thể làm gì khác để tiết kiệm thêm nước nữa nào.'" },
      { "start": 59.0, "en": "They learn that they can save 8 litres of water in one minute if they turn the tap off while they brush their teeth. If they shower for one minute less, they will save 40 litres of water. It all adds up. Start with the small things and see what you can do.", "ipa": "/ðeɪ lɜːrn ðæt ðeɪ kæn seɪv eɪt ˈliːtərz əv ˈwɔːtər ɪn wʌn ˈmɪnɪt ɪf ðeɪ tɜːrn ðə tæp ɔːf waɪl ðeɪ brʌʃ ðɛər tiːθ. ɪf ðeɪ ˈʃaʊər fɔːr wʌn ˈmɪnɪt lɛs, ðeɪ wɪl seɪv ˈfɔːrti ˈliːtərz əv ˈwɔːtər. ɪt ɔːl ædz ʌp. stɑːrt wɪð ðə smɔːl θɪŋz ænd siː wɒt juː kæn duː/", "vi": "Họ học được rằng có thể tiết kiệm 8 lít nước trong một phút nếu khóa vòi khi đánh răng. Nếu tắm nhanh hơn một phút, họ sẽ tiết kiệm được 40 lít nước. Tích tiểu thành đại. Hãy bắt đầu từ những việc nhỏ nhất và xem bạn có thể làm được gì." }
    ]
  },
  {
    "day": 28,
    "title": "Summer Vacation",
    "image": "06 June/images/day_28.webp",
    "audio": "06 June/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "School is out for the summer. Yay! No more studying. Nothing to do but run and play! It's every kid's dream, right? Well, one boy does not think so. His name is Ellis. He wants to keep going to school all summer.", "ipa": "/skuːl ɪz aʊt fɔːr ðə ˈsʌmər. jeɪ! noʊ mɔːr ˈstʌdiɪŋ. ˈnʌθɪŋ tuː duː bʌt rʌn ænd pleɪ! ɪts ˈɛvri kɪdz driːm, raɪt? wɛl, wʌn bɔɪ dʌz nɒt θɪŋk soʊ. hɪz neɪm ɪz ˈɛlɪs. hiː wɒnts tuː kiːp ˈɡoʊɪŋ tuː skuːl ɔːl ˈsʌmər/", vi: "Học sinh được nghỉ hè rồi. Hoan hô! Không còn phải học hành gì nữa, chỉ tha hồ chạy nhảy vui chơi! Đó là mơ ước của mọi đứa trẻ phải không? Thế nhưng, có một cậu bé không nghĩ vậy. Cậu tên là Ellis, cậu muốn tiếp tục được đi học suốt mùa hè." },
      { "start": 21.0, "en": "'I love school,' he says. 'Why do we have to take these holidays?' Ellis isn't weird or anything. He just loves school. He thinks there is plenty of time for playing after school. He wonders why kids should have the whole summer off.", "ipa": "/aɪ lʌv skuːl, hiː sɛz. waɪ duː wiː hæv tuː teɪk ðiːz ˈhɒlədeɪz? ˈɛlɪs ˈɪznt wɪərd ɔːr ˈɛniˌθɪŋ. hiː dʒʌst lʌvz skuːl. hiː θɪŋks ðɛər ɪz ˈplɛnti əv taɪm fɔːr ˈpleɪɪŋ ˈɑːftər skuːl. hiː ˈwʌndərz waɪ kɪdz ʃʊd hæv ðə hoʊl ˈsʌmər ɔːf/", vi: "'Tớ rất yêu trường lớp,' cậu nói. 'Sao chúng ta cứ phải nghỉ lễ dài ngày thế này?' Ellis không hề kỳ quặc chút nào, cậu chỉ đơn giản là quá mê đi học. Cậu nghĩ sau giờ học vẫn còn khối thời gian để chơi, và thắc mắc tại sao trẻ con lại phải nghỉ cả một mùa hè." },
      {
        "start": 40.0,
        "en": "When Ellis tells his mother that summer will be boring, she smiles and says, 'I thought of 50 fun things to do in the summer. Let's see which one you choose.'",
        "ipa": "/wɛn ˈɛlɪs tɛlz hɪz ˈmʌðər ðæt ˈsʌmər wɪl biː ˈbɔːrɪŋ, ʃiː smaɪld ænd sɛz, aɪ θɔːt əv ˈfɪfti fʌn θɪŋz tuː duː ɪn ðə ˈsʌmər. lɛts siː wɪtʃ wʌn juː tʃuːz/",
        "vi": "Khi Ellis phàn nàn với mẹ rằng mùa hè sẽ rất chán ngắt, mẹ mỉm cười bảo: 'Mẹ đã nghĩ ra 50 điều thú vị để làm trong hè này đấy. Để xem con sẽ chọn điều gì nào.'"
      },
      {
        "start": 54.0,
        "en": "His mom starts reading the list, 'Going to the beach, reading, playing sports, games, picnics, gardening, volunteering and...' 'Wait!' Ellis found one: teaching seniors how to use computers. That summer, he would be the teacher at school.",
        "ipa": "/hɪz mɒm stɑːrts ˈriːdɪŋ ðə lɪst, ˈɡoʊɪŋ tuː ðə biːtʃ, ˈriːdɪŋ, ˈpleɪɪŋ spɔːrts, ɡeɪmz, ˈpɪknɪks, ˈɡɑːrdnɪŋ, ˌvɒlənˈtɪərɪŋ ænd... weɪt! ˈɛlɪs faʊnd wʌn: ˈtiːtʃɪŋ ˈsiːnjərz haʊ tuː juːz kəmˈpjuːtərz. ðæt ˈsʌmər, hiː wʊd biː ðə ˈtiːtʃər æt skuːl/",
        "vi": "Mẹ bắt đầu đọc danh sách: 'Đi biển, đọc sách, chơi thể thao, trò chơi, cắm trại, làm vườn, tình nguyện và...' 'Khoan đã!' Ellis dừng lại ở một mục: Dạy người cao tuổi cách sử dụng máy tính. Hóa ra mùa hè đó, cậu lại được làm thầy giáo ở trường."
      }
    ]
  },
  {
    "day": 29,
    "title": "Snakes Are Different",
    "image": "06 June/images/day_29.webp",
    "audio": "06 June/audio/Track29.mp3",
    "sentences": [
      { "start": 4.8, "en": "My aunt is an expert on snakes. But my friend Molly is very afraid of snakes. One day, my aunt said, 'Molly, snakes are wonderful animals. Would you like to touch one?'", "ipa": "/maɪ ænt ɪz ən ˈɛkspɜːrt ɒn sneɪks. bʌt maɪ frɛnd ˈmɒli ɪz ˈvɛri əˈfreɪd əv sneɪks. wʌn deɪ, maɪ ænt sɛd, ˈmɒli, sneɪks ɑːr ˈwʌndərfʊl ˈænɪmlz. wʊd juː laɪk tuː tʌtʃ wʌn?/", vi: "Dì tôi là chuyên gia về loài rắn. Nhưng cô bạn Molly của tôi lại sợ rắn vô cùng. Một hôm, dì bảo: 'Molly này, loài rắn rất tuyệt vời. Cháu có muốn chạm thử vào một con không?'" },
      { "start": 18.0, "en": "'They are awful!' cried Molly. 'I would never touch a snake. NEVER.' 'But why?' my aunt asked. 'What scares you about them?'", "ipa": "/ðeɪ ɑːr ˈɔːfʊl!, kraɪd ˈmɒli. aɪ wʊd ˈnɛvər tʌtʃ ə sneɪk. ˈnɛvər. bʌt waɪ?, maɪ ænt ɑːskt. wɒt skɛərz juː əˈbaʊt ðɛm?/", vi: "'Chúng kinh khủng lắm!' Molly hét lên. 'Tớ không bao giờ chạm vào rắn đâu. KHÔNG BAO GIỜ.' 'Nhưng tại sao?' dì hỏi. 'Điều gì làm cháu sợ ở chúng thế?'" },
      { "start": 30.0, "en": "'They give me the creeps,' cried Molly. 'They might bite me. What scares me most is their tongues. No, no, no! I will never touch a snake.'", "ipa": "/ðeɪ ɡɪv miː ðə kriːps, kraɪd ˈmɒli. ðeɪ maɪt baɪt miː. wɒt skɛərz miː moʊst ɪz ðɛər tʌŋz. noʊ, noʊ, noʊ! aɪ wɪl ˈnɛvər tʌtʃ ə sneɪk/", "vi": "'Chúng làm tớ nổi da gà,' Molly kêu lên. 'Chúng có thể cắn tớ. Sợ nhất là cái lưỡi của chúng. Không, không, không! Tớ thề không bao giờ chạm vào rắn.'" },
      { "start": 43.0, "en": "My aunt explained that snakes use their tongues to smell. That made Molly laugh. 'Imagine that,' my aunt said. 'We smell with our noses, but snakes smell with their tongues.'", "ipa": "/maɪ ænt ɪkˈspleɪnd ðæt sneɪks juːz ðɛər tʌŋz tuː smɛl. ðæt meɪd ˈmɒli lɑːft. ɪˈmædʒɪn ðæt, maɪ ænt sɛd. wiː smɛl wɪð ˈaʊər ˈnoʊzɪz, bʌt sneɪks smɛl wɪð ðɛər tʌŋz/", "vi": "Dì giải thích rằng loài rắn dùng lưỡi để đánh hơi. Điều đó khiến Molly phì cười. 'Thật khó tưởng tượng nổi,' dì nói. 'Chúng ta ngửi bằng mũi, còn loài rắn lại ngửi bằng lưỡi đấy.'" },
      { "start": 56.0, "en": "'Sometimes we are afraid of things just because they are different,' said my aunt. She took us to her laboratory. She brought out a small green snake. Molly took a deep breath. Then she touched the snake! It felt warm and silky.", "ipa": "/ˈsʌmˌtaɪmz wiː ɑːr əˈfreɪd əv θɪŋz dʒʌst bɪˈkɒz ðeɪ ɑːr ˈdɪfrənt, sɛd maɪ ænt. ʃiː tʊk ʌs tuː hɜːr ˈlæbrətɔːri. ʃiː brɔːt aʊt ə smɔːl ɡriːn sneɪk. ˈmɒli tʊk ə diːp brɛθ. ðɛn ʃiː tʌtʃt ðə sneɪk! ɪt fɛlt wɔːrm ænd ˈsɪlki/", "vi": "'Đôi khi chúng ta sợ hãi những thứ chỉ vì chúng khác biệt,' dì bảo. Dì dẫn chúng tôi vào phòng thí nghiệm và mang ra một chú rắn lục nhỏ. Molly hít một hơi thật sâu rồi chạm vào chú rắn! Cảm giác ấm áp và mượt mà như lụa." }
    ]
  },
  {
    "day": 30,
    "title": "The Great Guitar Player",
    "image": "06 June/images/day_30.webp",
    "audio": "06 June/audio/Track30.mp3",
    "sentences": [
      { "start": 4.8, "en": "My dad hurt his hand at work. His doctor said he had to exercise the muscles in his hand to help it get better. So we bought him a guitar. But he did not play it. He was too sad.", "ipa": "/maɪ dæd hɜːrt hɪz hænd æt wɜːrk. hɪz ˈdɒktər sɛd hiː hæd tuː ˈɛksərsaɪz ðə ˈmʌslz ɪn hɪz hænd tuː hɛlp ɪt ɡɛt ˈbɛtər. soʊ wiː bɔːt hɪm ə ɡɪˈtɑːr. bʌt hiː dɪd nɒt pleɪ ɪt. hiː wɒz tuː sæd/", vi: "Bố tôi bị thương ở tay khi làm việc. Bác sĩ bảo bố phải tập vận động cơ tay để mau hồi phục. Vì thế chúng tôi mua tặng bố một cây đàn guitar. Nhưng bố chẳng thèm chơi vì quá buồn rầu." },
      { "start": 21.0, "en": "My music teacher learned about this. She gave me a CD with guitar music on it. My dad loved it. But he said, 'I could never play like that.'", "ipa": "/maɪ ˈmjuːzɪk ˈtiːtʃər lɜːrnd əˈbaʊt ðɪs. ʃiː ɡeɪv miː ə siː-diː wɪð ɡɪˈtɑːr ˈmjuːzɪk ɒn ɪt. maɪ dæd lʌvd ɪt. bʌt hiː sɛd, aɪ kʊd ˈnɛvər pleɪ laɪk ðæt/", "vi": "Cô giáo dạy nhạc biết chuyện bèn đưa cho tôi một đĩa CD nhạc guitar. Bố rất thích, nhưng lại thở dài: 'Tớ đời nào chơi được đỉnh như thế.'" },
      { "start": 36.0, "en": "When my dad picked me up after my music lesson, my teacher told him, 'The guitar player's name is Django Reinhardt. He was one of the greatest guitar players ever. But he burned one of his hands, and only two of his fingers worked.'", "ipa": "/wɛn maɪ dæd pɪkt miː ʌp ˈɑːftər maɪ ˈmjuːzɪk ˈlɛsn, maɪ ˈtiːtʃər toʊld hɪm, ðə ɡɪˈtɑːr ˈpleɪərz neɪm ɪz ˈdʒæŋɡoʊ ˈraɪnhɑːrt. hiː wɒz wʌn əv ðə ˈɡreɪtɪst ɡɪˈtɑːr ˈpleɪərz ˈɛvər. bʌt hiː bɜːrnd wʌn əv hɪz hændz, ænd ˈoʊnli tuː əv hɪz ˈfɪŋɡərz wɜːrkt/", vi: "Hôm đó khi bố đến đón tan học, cô giáo kể cho bố nghe: 'Nghệ sĩ guitar ấy tên là Django Reinhardt, một trong những tay guitar vĩ đại nhất mọi thời đại. Dù bị bỏng một bàn tay và chỉ cử động được hai ngón, ông ấy vẫn chơi đàn xuất chúng.'" },
      { "start": 56.0, "en": "The look on my dad's face was amazing. After this, my dad played and played. His hand got better. Now it's better than ever! Django Reinhardt has inspired many people to play the guitar. His story proves that you can do almost anything if you really try.", "ipa": "/ðə lʊk ɒn maɪ dædz feɪs wɒz əˈmeɪzɪŋ. ˈɑːftər ðɪs, maɪ dæd pleɪd ænd pleɪd. hɪz hænd ɡɒt ˈbɛtər. naʊ ɪts ˈbɛtər ðæn ˈɛvər! ˈdʒæŋɡoʊ ˈraɪnhɑːrt hæz ɪnˈspaɪərd ˈmɛni ˈpiːpl tuː pleɪ ðə ɡɪˈtɑːr. hɪz ˈstɔːri pruːvz ðæt juː kæn duː ˈɔːlmoʊst ˈɛniˌθɪŋ ɪf juː ˈrɪəli traɪ/", vi: "Biểu cảm trên khuôn mặt bố lúc đó thật kỳ diệu. Từ hôm đó, bố cặm cụi tập đàn không ngừng nghỉ. Tay bố đã khỏe lại, thậm chí còn dẻo dai hơn xưa! Câu chuyện về Django Reinhardt đã truyền cảm hứng cho bao người, minh chứng rằng bạn có thể làm được mọi thứ nếu thực sự nỗ lực hết mình." }
    ]
  }
];