if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["09 September"] = [
  {
    "day": 1,
    "title": "Lemonade Stand",
    "image": "09 September/images/day_01.webp",
    "audio": "09 September/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "Jeannie put up her sign. It said, Lemunaid: five cents a glass!", "ipa": "/ˈdʒiːni pʊt ʌp hɜːr saɪn. ɪt sɛd, lɛmʊˈneɪd: faɪv sɛnts ə ɡlɑːs!/", "vi": "Jeannie treo tấm biển của mình lên. Trên biển viết: Nước chanh năm xu một cốc!" },
      { "start": 13.0, "en": "Her neighbour, Mr. Brown, was walking by. He stopped and said, 'You didn't spell lemonade right. It should be spelled l-e-m-o-n-a-d-e.'", "ipa": "/hɜːr ˈneɪbər, ˈmɪstər braʊn, wɒz ˈwɔːkɪŋ baɪ. hiː stɒpt ænd sɛd, juː ˈdɪdnt spɛl ˈlɛməˌneɪd raɪt. ɪt ʃʊd biː spɛld ɛl-i-ɛm-o-en-e-di-i/", "vi": "Hàng xóm của cô bé, bác Brown, đi ngang qua. Bác dừng lại và bảo: 'Cháu viết sai chính tả từ nước chanh rồi kìa. Phải viết là l-e-m-o-n-a-d-e cơ.'" },
      { "start": 25.0, "en": "'Thank you,' said Jeannie. 'I'll write it down so I know how to spell it in the future.'", "ipa": "/ˈθæŋk juː, sɛd ˈdʒiːni. aɪl raɪt ɪt daʊn soʊ aɪ noʊ haʊ tuː spɛl ɪt ɪn ðə ˈfjuːtʃər/", "vi": "'Cháu cảm ơn bác,' Jeannie nói. 'Cháu sẽ ghi lại để sau này biết cách viết đúng.'" },
      { "start": 35.0, "en": "All morning, people stopped to tell Jeannie about her spelling mistake. And right before leaving, they all bought a glass of lemonade.", "ipa": "/ɔːl ˈmɔːrnɪŋ, ˈpiːpl stɒpt tuː tɛl ˈdʒiːni əˈbaʊt hɜːr ˈspɛlɪŋ mɪsˈteɪk. ænd raɪt bɪˈfɔːr ˈliːvɪŋ, ðeɪ ɔːl bɔːt ə ɡlɑːs əv ˈlɛməˌneɪd/", "vi": "Suốt buổi sáng, mọi người cứ dừng lại để nhắc Jeannie về lỗi chính tả. Và trước khi rời đi, ai nấy đều mua ủng hộ một cốc nước chanh." },
      { "start": 48.0, "en": "A couple of hours later, Mr. Brown came back. This time, he had a sign with him. 'I saw that you have been too busy to make a new sign. So, I made one for you,' he told Jeannie.", "ipa": "/ə ˈkʌpl əv ˈaʊərz ˈleɪtər, ˈmɪstər braʊn keɪm bæk. ðɪs taɪm, hiː hæd ə saɪn wɪð hɪm. aɪ sɔː ðæt juː hæv biːn tuː ˈbɪzi tuː meɪk ə njuː saɪn. soʊ, aɪ meɪd wʌn fɔːr juː, hiː toʊld ˈdʒiːni/", "vi": "Vài tiếng sau, bác Brown quay lại. Lần này bác mang theo một tấm biển: 'Bác thấy cháu quá bận không kịp làm biển mới nên làm giùm cháu đấy,' bác bảo Jeannie." },
      { "start": 65.0, "en": "'Thank you, Mr. Brown. Yes, it's true that lemonade is spelled wrong. But my sign is just right,' said Jeannie. 'Why?' said Mr. Brown. 'Everyone stops to tell me about the mistake,' said Jeannie. 'And then, they always buy lemonade.' Jeannie held up a jar full of money and smiled.", "ipa": "/ˈθæŋk juː, ˈmɪstər braʊn. jɛs, ɪts truː ðæt ˈlɛməˌneɪd ɪz spɛld rɒŋ. bʌt maɪ saɪn ɪz dʒʌst raɪt, sɛd ˈdʒiːni. waɪ?, sɛd ˈmɪstər braʊn. ˈɛvriˌwʌn stɒpts tuː tɛl miː əˈbaʊt ðə mɪsˈteɪk, sɛd ˈdʒiːni. ænd ðɛn, ðeɪ ˈɔːlweɪz baɪ ˈlɛməˌneɪd. ˈdʒiːni hɛld ʌp ə dʒɑːr fʊl əv ˈmʌni ænd smaɪld/", "vi": "'Cháu cảm ơn bác Brown. Vâng, đúng là chữ lemonade bị viết sai thật. Nhưng tấm biển của cháu lại cực kỳ hoàn hảo,' Jeannie nói. 'Sao lại thế?' bác Brown ngạc nhiên. 'Mọi người đều dừng lại để nhắc lỗi sai của cháu,' Jeannie cười tươi. 'Và thế là họ đều mua nước chanh.' Jeannie giơ hũ đựng đầy tiền lên và mỉm cười rạng rỡ." }
    ]
  },
  {
    "day": 2,
    "title": "Teeth",
    "image": "09 September/images/day_02.webp",
    "audio": "09 September/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "On Monday, Amy bit into some corn. 'Ouch!' she said. Her tooth felt strange.", "ipa": "/ɒn ˈmʌndeɪ, ˈeɪmi bɪt ˈɪntuː sʌm kɔːrn. aʊtʃ!, ʃiː sɛd. hɜːr tuːθ fɛlt streɪndʒ/", "vi": "Thứ Hai, Amy cắn bắp ngô và kêu 'Ái chà!' Chiếc răng của cô bé có cảm giác rất lạ." },
      { "start": 13.0, "en": "On Tuesday, Amy bit into an apple. 'Ouch!' she said. Her tooth felt wiggly.", "ipa": "/ɒn ˈtuzdeɪ, ˈeɪmi bɪt ˈɪntuː ən ˈæpl. aʊtʃ!, ʃiː sɛd. hɜːr tuːθ fɛlt ˈwɪɡli/", "vi": "Thứ Ba, Amy cắn quả táo và lại 'Ái chà!'. Răng cô bé bắt đầu lung lay." },
      { "start": 21.0, "en": "On Wednesday, Amy bit into a piece of cheese. 'Ouch!' she said. 'My tooth is loose!' She had heard about kids losing their teeth and she didn't like the way it sounded. She wanted to keep all of her teeth.", "ipa": "/ɒn ˈwɛnzdeɪ, ˈeɪmi bɪt ˈɪntuː ə piːs əv tʃiːz. aʊtʃ!, ʃiː sɛd. maɪ tuːθ ɪz luːs! ʃiː hæd hɜːrd əˈbaʊt kɪdz ˈluːzɪŋ ðɛər tiːθ ænd ʃiː ˈdɪdnt laɪk ðə weɪ ɪt ˈsaʊndɪd. ʃiː ˈwɒntɪd tuː kiːp ɔːl əv hɜːr tiːθ/", "vi": "Thứ Tư, Amy cắn miếng phô mai. 'Ái chà! Răng con sắp rụng rồi!' cô bé thốt lên. Từng nghe kể về chuyện trẻ con thay răng và cô bé không thích điều đó chút nào. Cô muốn giữ lại tất cả răng của mình." },
      { "start": 38.0, "en": "On Thursday, she was careful. So she ate yogurt, oatmeal and pudding. It worked. She didn't lose any of her teeth.", "ipa": "/ɒn ˈθɜːrzdeɪ, ʃiː wɒz ˈkɛrfʊl. soʊ ʃiː eɪt ˈjoʊɡərt, ˈoʊtˌmiːl ænd ˈpʊdɪŋ. ɪt wɜːrkt. ʃiː ˈdɪdnt luːs ˈɛni əv hɜːr tiːθ/", "vi": "Thứ Năm, cô bé cực kỳ cẩn thận. Cô chỉ ăn sữa chua, cháo yến mạch và bánh pudding. Mưu kế thành công, chẳng chiếc răng nào bị rụng cả." },
      { "start": 52.0, "en": "On Friday, her mom made pizza for dinner. She poked the pizza. It felt soft enough, so she bit into a slice. 'Ouch!' she cried. Her tooth had fallen out!", "ipa": "/ɒn ˈfraɪdeɪ, hɜːr mɒm meɪd ˈpiːtsə fɔːr ˈdɪnər. ʃiː poʊkt ðə ˈpiːtsə. ɪt fɛlt sɒft ɪˈnʌf, soʊ ʃiː bɪt ˈɪntuː ə slaɪs. aʊtʃ!, ʃiː kraɪd. hɜːr tuːθ hæd ˈfɔːlən aʊt/", "vi": "Đến thứ Sáu, mẹ làm pizza cho bữa tối. Cô bé ấn thử thấy bánh đủ mềm nên cắn một miếng. 'Ái chà!' cô khóc thét. Chiếc răng đã rụng ra mất rồi!" },
      { "start": 67.0, "en": "That night, Amy put her tooth under her pillow. In the morning, her tooth was gone. But, in its place was a coin! On Saturday, Amy ate corn on the cob, an apple, a piece of cheese and pizza. She wanted to lose more teeth!", "ipa": "/ðæt naɪt, ˈeɪmi pʊt hɜːr tuːθ ˈʌndər hɜːr ˈpɪloʊ. ɪn ðə ˈmɔːrnɪŋ, hɜːr tuːθ wɒz ɡɒn. bʌt, ɪn ɪts pleɪs wɒz ə kɔɪn! ɒn ˈsætərdeɪ, ˈeɪmi eɪt kɔːrn ɒn ðə kɒb, ən ˈæpl, ə piːs əv tʃiːz ænd ˈpiːtsə. ʃiː ˈwɒntɪd tuː luːz mɔːr tiːθ!/", "vi": "Đêm đó, Amy nhét chiếc răng xuống dưới gối. Sáng hôm sau, chiếc răng biến mất và thay vào đó là một đồng xu sáng loáng! Thế là vào thứ Bảy, cô bé ăn ngô luộc, táo, phô mai và cả pizza. Cô bé lại đang mong rụng thêm nhiều răng nữa!" }
    ]
  },
  {
    "day": 3,
    "title": "The Boy Who Cares",
    "image": "09 September/images/day_03.webp",
    "audio": "09 September/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Sandy is seven years old. Recently, his mom noticed that Sandy worries about things a lot.", "ipa": "/ˈsændi ɪz ˈsɛvn jɪərz oʊld. ˈriːsəntli, hɪz mɒm ˈnoʊtɪst ðæt ˈsændi ˈwʌriz əˈbaʊt θɪŋz ə lɒt/", "vi": "Sandy mới bảy tuổi. Dạo gần đây, mẹ nhận thấy cậu bé hay lo lắng về mọi thứ xung quanh." },
      { "start": 14.0, "en": "Every night before bed, Sandy's mom fills the bathtub for her son to take a bath. She used to fill it more than half full so that he could enjoy his hot bath.", "ipa": "/ˈɛvri naɪt bɪˈfɔːr bɛd, ˈsændiz mɒm fɪlz ðə ˈbæθˌtʌb fɔːr hɜːr sʌn tuː teɪk ə bæθ. ʃiː juːzd tuː fɪl ɪt mɔːr ðæn hæf fʊl soʊ ðæt hiː kʊd ɪnˈdʒɔɪ hɪz hɒt bæθ/", vi: "Mỗi tối trước khi đi ngủ, mẹ thường xả bồn tắm nước nóng cho con trai ngâm mình. Trước kia mẹ hay xả đầy hơn nửa bồn cho con thỏa thích." },
      { "start": 26.0, "en": "But now, Sandy asks his mom to shut off the tap when the tub is only one third full.", "ipa": "/bʌt naʊ, ˈsændy ɑːsks hɪz mɒm tuː ʃʌt ɔːf ðə tæp wɛn ðə tʌb ɪz ˈoʊnli wʌn θɜːrd fʊl/", "vi": "Nhưng giờ đây, Sandy lại dặn mẹ khóa vòi khi nước mới chỉ ngập một phần ba bồn." },
      { "start": 35.0, "en": "Why? Sandy tells his mom that it is not easy for water to come to the tap. He doesn't want to waste any. He says, 'Our teacher said that many people have trouble getting drinking water. Some kids walk miles to fetch water.'", "ipa": "/waɪ? ˈsændi tɛlz hɪz mɒm ðæt ɪt ɪz nɒt ˈiːzi fɔːr ˈwɔːtər tuː kʌm tuː ðə tæp. hiː ˈdʌznt wɒnt tuː weɪst ˈɛni. hiː sɛz, ˈaʊər ˈtiːtʃər sɛd ðæt ˈmɛni ˈpiːpl hæv ˈtrʌbl ˈɡɛtɪŋ ˈdrɪŋkɪŋ ˈwɔːtər. sʌm kɪdz wɔːk maɪlz tuː fɛtʃ ˈwɔːtər/", "vi": "Tại sao vậy? Cậu giải thích với mẹ rằng nước sạch chảy đến vòi không hề dễ dàng và cậu không muốn lãng phí giọt nào. 'Thầy giáo bảo nhiều nơi trên thế giới thiếu nước sạch trầm trọng, có những bạn nhỏ phải đi bộ cả dặm đường mới gánh được nước về,' cậu nói." },
      { "start": 54.0, "en": "Mom is moved by her little son. She tells her friends, 'Sandy is only seven, but he thinks about how to solve problems in the world.' She then adds, 'Shouldn't we all do our share to save this planet? We should not let our children worry all the time.' Yes. They all agree.", "ipa": "/mɒm ɪz muːvd baɪ hɜːr ˈlɪtl sʌn. ʃiː tɛlz hɜːr frɛndz, ˈsændi ɪz ˈoʊnli ˈsɛvn, bʌt hiː θɪŋks əˈbaʊt haʊ tuː sɒlv ˈprɒbləmz ɪn ðə wɜːrld. ʃiː ðɛn ædz, ˈʃʊdnt wiː ɔːl duː ˈaʊər ʃɛər tuː seɪv ðɪs ˈplænɪt? wiː ʃʊd nɒt lɛt ˈaʊər ˈtʃɪldrən ˈwʌri ɔːl ðə taɪm. jɛs. ðeɪ ɔːl əˈɡriː/", "vi": "Mẹ vô cùng xúc động trước tấm lòng của con trai. Mẹ kể với bạn bè: 'Sandy mới bảy tuổi mà đã biết trăn trở tìm cách giải quyết các vấn đề toàn cầu.' Rồi mẹ chiêm nghiệm: 'Chẳng lẽ chúng ta không nên chung tay cứu lấy hành tinh này sao? Đừng để con trẻ phải bận tâm lo lắng mãi thế.' Mọi người đều gật đầu đồng tình." }
    ]
  },
  {
    "day": 4,
    "title": "Car Keys",
    "image": "09 September/images/day_04.webp",
    "audio": "09 September/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Freddy came to his father and asked, 'Dad, may I borrow your car keys?' 'I don't think so!' answered his father. 'You're not ready to drive yet.'", "ipa": "/wʌn deɪ, ˈfrɛdi keɪm tuː hɪz ˈfɑːðər ænd ɑːskt, dæd, meɪ aɪ ˈbɒroʊ jɔːr kɑːr kiːz? aɪ doʊnt θɪŋk soʊ!, ˈɑːnsərd hɪz ˈfɑːðər. jʊər nɒt ˈrɛdi tuː draɪv jɛt/", "vi": "Một hôm, Freddy đến xin bố: 'Bố ơi, cho con mượn chìa khóa ô tô nhé?' 'Bố không nghĩ vậy đâu!' bố từ chối. 'Con chưa đủ tuổi lái xe đâu.'" },
      { "start": 16.0, "en": "Freddy laughed. 'Mom locked the car. I just need to get my baseball glove from the front seat.' 'I see. Here you go,' said Dad. 'Just don't try to drive.' 'Thanks,' said Freddy. 'I'll bring them right back.'", "ipa": "/ˈfrɛdi lɑːft. mɒm lɒkt ðə kɑːr. aɪ dʒʌst niːd tuː ɡɛt maɪ ˈbeɪsˌbɔːl ɡlʌv frɒm ðə frʌnt siːt. aɪ siː. hɪər juː ɡoʊ, sɛd dæd. dʒʌst doʊnt traɪ tuː draɪv. θæŋks, sɛd ˈfrɛdi. aɪl brɪŋ ðɛm raɪt bæk/", "vi": "Freddy cười xòa: 'Mẹ khóa xe mất rồi, con chỉ lấy găng tay bóng chày ở ghế trước thôi.' 'À ra thế, cầm lấy này,' bố đưa chìa khóa. 'Miễn là đừng táy máy lái xe đấy.' 'Vâng, con mang trả ngay đây ạ.'" },
      { "start": 32.0, "en": "A couple of minutes later, Freddy got his glove and started walking back. Suddenly, the car started moving. Freddy raced after it, unlocked the door and grabbed the emergency break. The car stopped rolling.", "ipa": "/ə ˈkʌpl əv ˈmɪnɪts ˈleɪtər, ˈfrɛdi ɡɒt hɪz ɡlʌv ænd ˈstɑːrtɪd ˈwɔːkɪŋ bæk. ˈsʌdənli, ðə kɑːr ˈstɑːrtɪd ˈmuːvɪŋ. ˈfrɛdi reɪst ˈɑːftər ɪt, ʌnˈlɒkt ðə dɔːr ænd ɡræbt ði ɪˈmɜːrdʒənsi breɪk. ðə kɑːr stɒpt ˈroʊlɪŋ/", "vi": "Vài phút sau, Freddy lấy được găng tay và quay ra. Bỗng nhiên, chiếc xe chầm chậm lăn bánh! Freddy hoảng hốt đuổi theo, mở cửa và giật phắt phanh tay khẩn cấp. Chiếc xe dừng hẳn lại." },
      { "start": 49.0, "en": "Dad came running out of the house. 'What did you do?' he asked. 'I must have hit something while I was getting my glove,' answered Freddy. 'I'm sorry. I didn't mean to drive the car.'", "ipa": "/dæd keɪm ˈrʌnɪŋ aʊt əv ðə haʊs. wɒt dɪd juː duː?, hiː ɑːskt. aɪ mʌst hæv hɪt ˈsʌmθɪŋ waɪl aɪ wɒz ˈɡɛtɪŋ maɪ ɡlʌv, ˈɑːnsərd ˈfrɛdi. aɪm ˈsɒri. aɪ ˈdɪdnt miːn tuː draɪv ðə kɑːr/", "vi": "Bố hộc tốc chạy ra từ trong nhà: 'Con làm cái quái gì thế?' 'Chắc con lỡ va phải cần số lúc lấy găng tay ạ,' Freddy mếu máo. 'Con xin lỗi, con không có ý định lái xe đâu ạ.'" },
      { "start": 62.0, "en": "'I know,' said Dad. 'Accidents happen. I'm glad you acted quickly. But, next time you kids want something from the car, I'll get it for you. That made me age way too fast and I can't afford to do that!'", "ipa": "/aɪ noʊ, sɛd dæd. ˈæksɪdənts ˈhæpən. aɪm ɡlæd juː ˈæktɪd ˈkwɪkli. bʌt, nɛkst taɪm juː kɪdz wɒnt ˈsʌmθɪŋ frɒm ðə kɑːr, aɪl ɡɛt ɪt fɔːr juː. ðæt meɪd miː eɪdʒ weɪ tuː fɑːst ænd aɪ kænt əˈfɔːrd tuː duː ðæt!/", "vi": "'Bố biết rồi,' bố thở phào. 'Tai nạn bất ngờ có thể xảy ra. May mà con xử lý kịp thời. Nhưng từ nay về sau, cứ cần đồ ở xe thì bảo bố lấy cho nhé. Vừa rồi suýt nữa làm bố già đi chục tuổi đấy, bố chịu không thọ nổi đâu!'" }
    ]
  },
  {
    "day": 5,
    "title": "Red Wolves",
    "image": "09 September/images/day_05.webp",
    "audio": "09 September/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Red wolves are the smallest wolves in the world. They are only about 26 inches tall at the shoulder.", "ipa": "/rɛd wʊlvz ɑːr ðə ˈsmɔːlɪst wʊlvz ɪn ðə wɜːrld. ðeɪ ɑːr ˈoʊnli əˈbaʊt ˈtwɛnti-sɪks ˈɪntʃɪz tɔːl æt ðə ˈʃoʊldər/", vi: "Sói đỏ là loài sói có kích thước nhỏ nhất thế giới, chiều cao tính từ vai chỉ khoảng 66 cm." },
      { "start": 13.0, "en": "Red wolves live in packs of five to eight. A pack is made up of a father wolf, a mother wolf and their children. The pack lives and hunts together. They hunt for small animals to eat, like rabbits and rodents. They eat insects and berries too.", "ipa": "/rɛd wʊlvz lɪv ɪn pæks əv faɪv tuː eɪt. ə pæk ɪz meɪd ʌp əv ə ˈfɑːðər wʊlf, ə ˈmʌðər wʊlf ænd ðɛər ˈtʃɪldrən. ðə pæk lɪvz ænd hʌnts təˈɡɛðər. ðeɪ hʌnt fɔːr smɔːl ˈænɪmlz tuː iːt, laɪk ˈræbɪts ænd ˈroʊdnts. ðeɪ iːt ˈɪnsɛkts ænd ˈbɛriz tuː/", vi: "Sói đỏ sống theo bầy đàn từ năm đến tám con, gồm sói bố, sói mẹ và các con. Cả đàn cùng sinh sống và đi săn mồi chung, thức ăn là động vật nhỏ như thỏ, loài gặm nhấm, côn trùng và quả mọng." },
      { "start": 32.0, "en": "Red wolves in a pack communicate in many different ways. They make noises and bark. They make faces and use body language as well.", "ipa": "/rɛd wʊlvz ɪn ə pæk kəˈmjuːnɪkeɪt ɪn ˈmɛni ˈdɪfrənt weɪz. ðeɪ meɪk ˈnɔɪzɪz ænd bɑːrk. ðeɪ meɪk ˈfeɪsɪz ænd juːz ˈbɒdi ˈlæŋɡwɪdʒ æz wɛl/", vi: "Các thành viên trong bầy giao tiếp với nhau bằng nhiều cách: phát ra âm thanh, sủa, biểu cảm khuôn mặt và sử dụng ngôn ngữ cơ thể." },
      { "start": 44.0, "en": "One time, red wolves lived all over the south-eastern United States. But thirty years ago, they almost disappeared completely. Then, in 1980, twenty red wolves were found in the wild and taken to a safe place. There, they were able to have babies and increase their numbers. Now, there are over one hundred red wolves living in the wild.", "ipa": "/wʌn taɪm, rɛd wʊlvz lɪvd ɔːl ˈoʊvər ðə saʊθ-ˈiːstərn juˈnaɪtɪd steɪts. bʌt ˈθɜːrti jɪərz əˈɡoʊ, ðeɪ ˈɔːlmoʊst ˌdɪsəˈpɪərd kəmˈpliːtli. ðɛn, ɪn ˌnaɪnˈtiːn ˈeɪti, ˈtwɛnti rɛd wʊlvz wɜːr faʊnd ɪn ðə waɪld ænd ˈteɪkən tuː ə seɪf pleɪs. ðɛər, ðeɪ wɜːr ˈeɪbl tuː hæv ˈbeɪbiːz ænd ˈɪnkriːs ðɛər ˈnʌmbərz. naʊ, ðɛər ɑːr ˈoʊvər wʌn ˈhʌndrəd rɛd wʊlvz ˈlɪvɪŋ ɪn ðə waɪld/", "vi": "Từng có thời điểm sói đỏ sinh sống khắp vùng Đông Nam nước Mỹ. Nhưng ba mươi năm trước, chúng suýt bị tuyệt chủng hoàn toàn. Đến năm 1980, hai mươi con sói đỏ được tìm thấy trong tự nhiên và đưa đến khu bảo tồn an toàn. Nhờ đó, chúng sinh sôi nảy nở và nay đã có hơn một trăm cá thể sống hoang dã." }
    ]
  },
  {
    "day": 6,
    "title": "Family Tree",
    "image": "09 September/images/day_06.webp",
    "audio": "09 September/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mom was drawing a picture. 'What are you drawing?' asked Barbara, looking over her mother's shoulder. 'This is our family tree,' answered her mother. 'It shows you, your sister and brother, Dad, and me. It also shows our parents, their parents and others from long ago.'", "ipa": "/mɒm wɒz ˈdrɔːɪŋ ə ˈpɪktʃər. wɒt ɑːr juː ˈdrɔːɪŋ?, ɑːskt ˈbɑːrbərə, ˈlʊkɪŋ ˈoʊvər hɜːr ˈmʌðərz ˈʃoʊldər. ðɪs ɪz ˈaʊər ˈfæməli triː, ˈɑːnsərd hɜːr ˈmʌðər. ɪt ʃoʊz juː, jɔːr ˈsɪstər ænd ˈbrʌðər, dæd, ænd miː. ɪt ˈɔːlsoʊ ʃoʊz ˈaʊər ˈpɛərənts, ðɛər ˈpɛərənts ænd ˈʌðərz frɒm lɒŋ əˈɡoʊ/", vi: "Mẹ đang ngồi vẽ tranh. 'Mẹ đang vẽ gì thế ạ?' Barbara ghé vai hỏi. 'Đây là cây phả hệ gia đình mình,' mẹ đáp. 'Nó thể hiện tên con, anh chị em con, bố và mẹ, cùng ông bà tổ tiên từ nhiều đời trước.'" },
      { "start": 23.0, "en": "'That's neat!' said Barbara. 'Who is Olive Willard?' she asked, pointing to a name. 'That's Grandma Olive,' answered Mom. 'But I thought her name was Olive Flanders,' said Barbara. 'Before she married Grandpa Clint, her name was Olive Willard,' answered Mom. 'Look here. Here is my name. My name used to be Flanders.'", "ipa": "/ðæts niːt!, sɛd ˈbɑːrbərə. huː ɪz ˈɒlɪv ˈwɪlərd?, ʃiː ɑːskt, ˈpɔɪntɪŋ tuː ə neɪm. ðæts ˈɡrændmɑː ˈɒlɪv, ˈɑːnsərd mɒm. bʌt aɪ θɔːt hɜːr neɪm wɒz ˈɒlɪv ˈflændərz, sɛd ˈbɑːrbərə. bɪˈfɔːr ʃiː ˈmærid ˈɡrændpɑː klɪnt, hɜːr neɪm wɒz ˈɒlɪv ˈwɪlərd, ˈɑːnsərd mɒm. lʊk hɪər. hɪər ɪz maɪ neɪm. maɪ neɪm ˈjuːzd tuː biː ˈflændərz/", "vi": "'Hay quá nhỉ! Thế Olive Willard là ai ạ?' Barbara chỉ vào một cái tên. 'Đó là bà nội Olive,' mẹ đáp. 'Nhưng con tưởng tên bà là Olive Flanders cơ mà?' 'Trước khi kết hôn với ông Clint, tên cụ là Olive Willard,' mẹ giải thích. 'Nhìn đây này, tên mẹ hồi xưa cũng là Flanders đấy.'" },
      { "start": 48.0, "en": "'It seems strange to think that you weren't always you, but someone else,' said Barbara. Her mother laughed.", "ipa": "/ɪt siːmz streɪndʒ tuː θɪŋk ðæt juː ˈwɜːnt ˈɔːlweɪz juː, bʌt ˈsʌmwʌn ɛls, sɛd ˈbɑːrbərə. hɜːr ˈmʌðər lɑːft/", vi: "'Nghe lạ thật đấy, cứ như thể hồi trước mẹ không phải là mẹ mà là một người khác vậy,' Barbara lẩm bẩm khiến mẹ phì cười." }
    ]
  },
  {
    "day": 7,
    "title": "The Father of South America",
    "image": "09 September/images/day_07.webp",
    "audio": "09 September/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "Imagine being so famous that a country is named after you? Well, about 200 years ago, there lived a man who was called the 'father of South America'. His name was Simon Bolivar. He was born in South America in 1783.", "ipa": "/ɪˈmædʒɪŋ ˈbiːɪŋ soʊ ˈfeɪməs ðæt ə ˈkʌntri ɪz neɪmd ˈɑːftər juː? wɛl, əˈbaʊt ˈtuː ˈhʌndrəd jɪərz əˈɡoʊ, ðɛər lɪvd ə mæn huː wɒz kɔːld ðə ˈfɑːðər əv saʊθ əˈmɛrɪkə. hɪz neɪm wɒz ˈsaɪmən bəˈliːvɑːr. hiː wɒz bɔːrn ɪn saʊθ əˈmɛrɪkə ɪn ˌeɪtiˈeɪti-θriː/", vi: "Hãy thử tưởng tượng bạn nổi tiếng đến mức được đặt tên cho cả một quốc gia xem nào? Khoảng 200 năm trước, từng có một nhân vật vĩ đại được mệnh danh là 'cha đẻ của Nam Mỹ'. Ông tên là Simon Bolivar, sinh năm 1783." },
      { "start": 21.0, "en": "Back then, Spain ruled South America. Most people in South America did not like this. Simon was one of those people. So he led small groups of men to fight against the Spanish armies.", "ipa": "/bæk ðɛn, speɪn ruːld saʊθ əˈmɛrɪkə. moʊst ˈpiːpl ɪn saʊθ əˈmɛrɪkə dɪd nɒt laɪk ðɪs. ˈsaɪmən wɒz wʌn əv ðoʊz ˈpiːpl. soʊ hiː lɛd smɔːl ɡruːps əv mɛn tuː faɪt əˈɡɛnst ðə ˈspænɪʃ ˈɑːrmiz/", vi: "Thời đó, Tây Ban Nha thống trị Nam Mỹ và người dân vô cùng bất bình. Simon là một trong những thủ lĩnh tiên phong đứng lên quy tụ nghĩa quân đánh đuổi quân đội Tây Ban Nha." },
      { "start": 36.0, "en": "People called him 'El Liberator'. That means someone who makes people free. He helped to free Colombia, Venezuela, Peru, Ecuador and... Bolivia!", "ipa": "/ˈpiːpl kɔːld hɪm ɛl ˈlɪbəˌreɪtər. ðæt miːnz ˈsʌmwʌn huː meɪks ˈpiːpl friː. hiː hɛlpt tuː friː kəˈlʌmbɪja, ˌvɛnəˈzweɪlə, pəˈruː, ˈɛkwədɔːr ænd... bəˈlɪviə!/", "vi": "Người dân tôn kính gọi ông là 'El Liberator' — nghĩa là Người Giải Phóng. Ông đã góp công lớn giải phóng Colombia, Venezuela, Peru, Ecuador và... Bolivia!" },
      { "start": 52.0, "en": "That's right, the country of Bolivia is named after Simon Bolivar. I wonder how many other countries are named after people?", "ipa": "/ðæts raɪt, ðə ˈkʌntri əv bəˈlɪviə ɪz neɪmd ˈɑːftər ˈsaɪmən bəˈliːvɑːr. aɪ ˈwʌndər haʊ ˈmɛni ˈʌðər ˈkʌntriz ɑːr neɪmd ˈɑːftər ˈpiːpl?/", vi: "Đúng vậy, quốc gia Bolivia được vinh dự mang tên Simon Bolivar. Thật tò mò không biết còn bao nhiêu quốc gia khác trên thế giới được đặt tên theo các vĩ nhân như thế?" }
    ]
  },
  {
    "day": 8,
    "title": "Dark or Light-It's Amazing",
    "image": "09 September/images/day_08.webp",
    "audio": "09 September/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "We all know what organs are. Things like the heart, lungs and kidneys are all organs. But, do you know what is the biggest organ of all? Here are some hints. It can be very dark or it can be very light. It can be very smooth or very rough. That's right—it's skin!", "ipa": "/wiː ɔːl noʊ wɒt ˈɔːrɡənz ɑːr. θɪŋz laɪk ðə hɑːrt, lʌŋz ænd ˈkɪdniːz ɑːr ɔːl ˈɔːrɡənz. bʌt, duː juː noʊ wɒt ɪz ðə ˈbɪɡɪst ˈɔːrɡən əv ɔːl? hɪər ɑːr sʌm hɪnts. ɪt kæn biː ˈvɛri dɑːrk ɔːr ɪt kæn biː ˈvɛri laɪt. ɪt kæn biː ˈvɛri smuːð ɔːr ˈvɛri rʌf. ðæts raɪt—ɪts skɪn/", vi: "Chúng ta đều biết cơ quan trong cơ thể là gì, ví dụ như tim, phổi hay thận. Nhưng bạn có biết cơ quan nào lớn nhất không? Gợi ý nhé: Nó có thể rất tối hoặc rất sáng màu, rất mịn màng hoặc sần sùi. Chính xác — đó là làn da!" },
      { "start": 21.0, "en": "Our skin is an amazing thing. Imagine if scientists could invent something that could heal itself? That's exactly what skin does! Adults have more than 11 miles of blood vessels in their skin! Those blood vessels help to keep skin warm or to cool it down. In fact, on a hot summer day, a person can sweat as much as 3 gallons.", "ipa": "/ˈaʊər skɪn ɪz ən əˈmeɪzɪŋ θɪŋ. ɪˈmædʒɪn ɪf ˈsaɪəntɪsts kʊd ɪnˈvɛnt ˈsʌmθɪŋ ðæt kʊd hiːl ɪtˈsɛlf? ðæts ɪɡˈzæktli wɒt skɪn dʌz! əˈdʌlts hæv mɔːr ðæn ˈlɛvn maɪlz əv blʌd ˈvɛsəlz ɪn ðɛər skɪn! ðoʊz blʌd ˈvɛsəlz hɛlp tuː kiːp skɪn wɔːrm ɔːr tuː kuːl ɪt daʊn. ɪn fækt, ɒn ə hɒt ˈsʌmər deɪ, ə ˈpɜːrsn kæn swɛt ænd mʌtʃ æz θriː ˈɡælənz/", vi: "Da là một kỳ quan thực sự. Thử tưởng tượng nếu các nhà khoa học phát minh ra vật liệu tự lành vết thương thì sao? Da chúng ta làm được đúng việc đó! Người lớn có tới hơn 11 dặm mạch máu dưới da giúp điều hòa thân nhiệt sưởi ấm hoặc làm mát. Thậm chí vào ngày hè oi bức, cơ thể có thể tiết ra tới 3 gallon mồ hôi." },
      {
        "start": 47.0,
        "en": "The reason why there are different colours of skin is pigment. The more pigment you have in your skin, the darker it is. So, take care of your skin. Remember, you are going to need it for a long time!",
        "ipa": "/ðə ˈriːzn waɪ ðɛər ɑːr ˈdɪfrənt ˈkʌlərz əv skɪn ɪz ˈpɪɡmənt. ðə mɔːr ˈpɪɡmənt juː hæv ɪn jɔːr skɪn, ðə ˈdɑːrkər ɪt ɪz. soʊ, teɪk kɛər əv jɔːr skɪn. rɪˈmɛmbər, juː ɑːr ˈɡoʊɪŋ tuː niːd ɪt fɔːr ə lɒŋ taɪm/", vi: "Nguyên nhân tạo nên các sắc độ da khác nhau chính là sắc tố melanin. Càng có nhiều sắc tố, da càng sậm màu. Vì thế, hãy nâng niu làn da của mình nhé, vì bạn sẽ phải gắn bó với nó suốt cả cuộc đời đấy!"
      }
    ]
  },
  {
    "day": 9,
    "title": "Race Car",
    "image": "09 September/images/day_09.webp",
    "audio": "09 September/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "Billy loves cars. So does his brother Jeff. One day, Billy saw his brother working on something. He was curious. 'What are you building?' asked Billy. 'A race car,' answered Jeff. 'One that's big enough for me to get into.'", "ipa": "/ˈbɪli lʌvz kɑːrz. soʊ dʌz hɪz ˈbrʌðər dʒɛf. wʌn deɪ, ˈbɪli sɔː hɪz ˈbrʌðər ˈwɜːrkɪŋ ɒn ˈsʌmθɪŋ. hiː wɒz ˈkjʊəriəs. wɒt ɑːr juː ˈbɪldɪŋ?, ɑːskt ˈbɪli. ə reɪs kɑːr, ˈɑːnsərd dʒɛf. wʌn ðæts bɪɡ ɪˈnʌf fɔːr miː tuː ɡɛt ˈɪntuː/", vi: "Billy rất mê ô tô, anh trai Jeff của cậu cũng vậy. Một hôm, thấy anh đang cặm cụi làm gì đó, Billy tò mò hỏi: 'Anh đang dựng cái gì thế?' 'Xe đua,' Jeff đáp. 'Loại to đủ để anh chui vào ngồi lái luôn.'" },
      { "start": 18.0, "en": "'Can I help? Then, we can share it!' said Billy. Jeff agreed. It would be fun to have someone to build his race car with. And so, the two boys got to work.", "ipa": "/kæn aɪ hɛlp? ðɛn, wiː kæn ʃɛr ɪt!, sɛd ˈbɪli. dʒɛf əˈɡriːd. ɪt wʊd biː fʌn tuː hæv ˈsʌmwʌn tuː bɪld hɪz reɪs kɑːr wɪð. ænd soʊ, ðə tuː bɔɪz ɡɒt tuː wɜːrk/", vi: "'Con giúp một tay nhé, rồi hai anh em mình cùng chạy chung!' Billy nài nỉ. Jeff đồng ý ngay vì có bạn đồng hành dựng xe sẽ vui hơn nhiều. Thế là hai anh em bắt tay vào việc." },
      { "start": 32.0, "en": "They worked hard. Mrs. Smith from next door saw what they were doing. She gave them an old baby carriage. 'The wheels on this are still good,' she said. 'Maybe you can use them.' The boys worked even harder. Soon, it was finished—a very nice race car!", "ipa": "/ðeɪ wɜːrkt hɑːrd. ˈmɪsɪz smɪθ frɒm nɛkst dɔːr sɔː wɒt ðeɪ wɜːr ˈduːɪŋ. ʃiː ɡeɪv ðɛm ən oʊld ˈbeɪbi ˈkærɪdʒ. ðə wiːlz ɒn ðɪs ɑːr stɪl ɡʊd, ʃiː sɛd. ˈmeɪbi juː kæn juːz ðɛm. ðə bɔɪz wɜːrkt ˈiːvn ˈhɑːrdər. suːn, ɪt wɒz ˈfɪnɪʃt—ə ˈvɛri naɪs reɪs kɑːr/", vi: "Hai cậu bé làm việc cực kỳ chăm chỉ. Bà Smith nhà bên thấy vậy liền tặng cho hai anh em chiếc xe đẩy em bé cũ: 'Bánh xe của chiếc này vẫn tốt chán, mấy đứa cứ tháo ra mà dùng.'" },
      { "start": 52.0, "en": "When their father came home from work, he smiled as he saw the car. Then, he brought out some more wood and wheels. 'If you build two, then you can race each other.' Soon, the boys had two race cars. They were ready to race each other in their own cars!", "ipa": "/wɛn ðɛər ˈfɑːðər keɪm hoʊm frɒm wɜːrk, hiː smaɪld æz hiː sɔː ðə kɑːr. ðɛn, hiː brɔːt aʊt sʌm mɔːr wʊd ænd wiːlz. ɪf juː bɪld tuː, ðɛn juː kæn reɪs iːtʃ ˈʌðər. suːn, ðə bɔɪz hæd tuː reɪs kɑːrz. ðeɪ wɜːr ˈrɛdi tuː reɪs iːtʃ ˈʌðər ɪn ðɛər oʊn kɑːrz/", vi: "Bố đi làm về, mỉm cười tán thưởng chiếc xe tự chế. Bố liền mang thêm gỗ và bánh xe ra hỗ trợ: 'Nếu các con làm hẳn hai chiếc thì có thể đem ra đường đua tranh tài đấy.' Chẳng mấy chốc, hai anh em đã hoàn thành hai chiếc xe sẵn sàng cho cuộc đua tốc độ ngay trong vườn." }
    ]
  },
  {
    "day": 10,
    "title": "Henry Ford",
    "image": "09 September/images/day_10.webp",
    "audio": "09 September/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "Henry Ford was a man who truly changed the world. He was born on July 30, 1863. He grew up on a farm in Michigan in the United States. When he was old enough, he left his family's farm and moved to Detroit to start living his dream.", "ipa": "/ˈhɛnri fɔːrd wɒz ə mæn huː ˈtruːli tʃeɪndʒd ðə wɜːrld. hiː wɔːz bɔːrn ɒn dʒuˈlaɪ ˈθɜːrti, ˌeɪtiːn ˈsɪksti-θriː. hiː ɡruː ʌp ɒn ə fɑːrm ɪn ˈmɪʃɪɡən ɪn ði juˈnaɪtɪd steɪts. wɛn hiː wɒz oʊld ɪˈnʌf, hiː lɛft hɪz ˈfæməlɪz fɑːrm ænd muːvd tuː dɪˈtrɔɪt tuː stɑːrt ˈlɪvɪŋ hɪz driːm/", vi: "Henry Ford là nhân vật vĩ đại đã thay đổi cả thế giới. Ông sinh ngày 30/7/1863, lớn lên tại một trang trại ở Michigan (Mỹ). Khi đến tuổi trưởng thành, ông rời quê hương để đến Detroit lập nghiệp và theo đuổi ước mơ." },
      { "start": 21.0, "en": "Mr. Ford wanted to make cars. In 1903, Mr. Ford started the Ford Motor Company. At that time, the company was able to make only a few cars each day.", "ipa": "/ˈmɪstər fɔːrd ˈwɒntɪd tuː meɪk kɑːrz. ɪn ˌnaɪnˈtiːn ˈoʊ-θriː, ˈmɪstər fɔːrd ˈstɑːrtɪd ðə fɔːrd ˈmoʊtər ˈkʌmpəni. æt ðæt taɪm, ðə ˈkʌmpəni wɒz ˈeɪbl tuː meɪk ˈoʊnli ə fjuː kɑːrz iːtʃ deɪ/", vi: "Ông Ford ấp ủ khát vọng chế tạo ô tô. Năm 1903, ông thành lập Công ty ô tô Ford. Vào thuở ban đầu, mỗi ngày hãng chỉ xuất xưởng được vài chiếc xe." },
      { "start": 35.0, "en": "In 1908, Mr. Ford made the Model T. Everyone loved it! However, Mr. Ford could not make the Model T cars fast enough to meet the high demand.", "ipa": "/ɪn ˌnaɪnˈtiːn ˈoʊ-eɪt, ˈmɪstər fɔːrd meɪd ðə ˈmɒdl tiː. ˈɛvriˌwʌn lʌvd ɪt! haʊˈɛvər, ˈmɪstər fɔːrd kʊd nɒt meɪk ðə ˈmɒdl tiː kɑːrz fɑːst ɪˈnʌf tuː miːt ðə haɪ dɪˈmænd/", vi: "Năm 1908, ông ra mắt dòng xe Model T và lập tức gây tiếng vang lớn! Thế nhưng tốc độ sản xuất lúc ấy quá chậm, không đủ cung cấp cho nhu cầu khổng lồ của thị trường." },
      { "start": 47.0, "en": "In 1913, Mr. Ford changed the way his company made cars. He decided to make a moving assembly line. The workers stayed in one place while the car parts moved on a conveyor belt. This```javascript
if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["09 September"] = [
  {
    "day": 1,
    "title": "Lemonade Stand",
    "image": "09 September/images/day_01.webp",
    "audio": "09 September/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "Jeannie put up her sign. It said, Lemunaid: five cents a glass!", "ipa": "/ˈdʒiːni pʊt ʌp hɜːr saɪn. ɪt sɛd, lɪˈmuːneɪd: faɪv sɛnts ə ɡlɑːs/", "vi": "Jeannie dựng tấm biển của mình lên. Trên biển viết: 'Lemunaid: năm xu một cốc!'" },
      { "start": 12.0, "en": "Her neighbour, Mr. Brown, was walking by. He stopped and said, 'You didn't spell lemonade right. It should be spelled l-e-m-o-n-a-d-e.'", "ipa": "/hɜːr ˈneɪbər, ˈmɪstər braʊn, wɒz ˈwɔːkɪŋ baɪ. hiː stɒpt ænd sɛd, juː ˈdɪdnt spɛl ˈlɛməˌneɪd raɪt. ɪt ʃʊd biː spɛld ɛl-i-ɛm-o-en-e-di-i/", "vi": "Bác hàng xóm Mr. Brown đi ngang qua, dừng lại và bảo: 'Cháu viết sai chính tả chữ lemonade rồi. Phải viết là l-e-m-o-n-a-d-e cơ.'" },
      { "start": 23.0, "en": "'Thank you,' said Jeannie. 'I'll write it down so I know how to spell it in the future.'", "ipa": "/ˈθæŋk juː, sɛd ˈdʒiːni. aɪl raɪt ɪt daʊn soʊ aɪ noʊ haʊ tuː spɛl ɪt ɪn ðə ˈfjuːtʃər/", "vi": "'Cháu cảm ơn bác,' Jeannie nói. 'Cháu sẽ ghi lại để sau này biết cách viết đúng.'" },
      { "start": 32.0, "en": "All morning, people stopped to tell Jeannie about her spelling mistake. And right before leaving, they all bought a glass of lemonade.", "ipa": "/ɔːl ˈmɔːrnɪŋ, ˈpiːpl stɒpt tuː tɛl ˈdʒiːni əˈbaʊt hɜːr ˈspɛlɪŋ ˈmɪsteɪk. ænd raɪt bɪˈfɔːr ˈliːvɪŋ, ðeɪ ɔːl bɔːt ə ɡlɑːs əv ˈlɛməˌneɪd/", "vi": "Suốt buổi sáng, mọi người liên tục dừng chân để nhắc Jeannie về lỗi chính tả. Và trước khi rời đi, tất cả bọn họ đều mua một cốc nước chanh." },
      { "start": 44.0, "en": "A couple of hours later, Mr. Brown came back. This time, he had a sign with him. 'I saw that you have been too busy to make a new sign. So, I made one for you,' he told Jeannie.", "ipa": "/ə ˈkʌpl əv ˈaʊərz ˈleɪtər, ˈmɪstər braʊn keɪm bæk. ðɪs taɪm, hiː hæd ə saɪn wɪð hɪm. aɪ sɔː ðæt juː hæv biːn tuː ˈbɪzi tuː meɪk ə njuː saɪn. soʊ, aɪ meɪd wʌn fɔːr juː, hiː toʊld ˈdʒiːni/", "vi": "Vài tiếng sau, Mr. Brown quay lại. Lần này bác mang theo một tấm biển: 'Bác thấy cháu bận quá chưa kịp làm biển mới nên bác làm hộ cháu đấy,' bác bảo Jeannie." },
      { "start": 58.0, "en": "'Thank you, Mr. Brown. Yes, it's true that lemonade is spelled wrong. But my sign is just right,' said Jeannie. 'Why?' said Mr. Brown.", "ipa": "/ˈθæŋk juː, ˈmɪstər braʊn. jɛs, ɪts truː ðæt ˈlɛməˌneɪd ɪz spɛld rɒŋ. bʌt maɪ saɪn ɪz dʒʌst raɪt, sɛd ˈdʒiːni. waɪ?, sɛd ˈmɪstər braʊn/", "vi": "'Cháu cảm ơn bác Brown. Đúng là chữ lemonade trên biển bị sai chính tả thật. Nhưng tấm biển của cháu lại chuẩn không cần chỉnh ạ,' Jeannie nói. 'Sao lại thế?' bác Brown ngạc nhiên hỏi." },
      { "start": 68.0, "en": "'Everyone stops to tell me about the mistake,' said Jeannie. 'And then, they always buy lemonade.' Jeannie held up a jar full of money and smiled.", "ipa": "/ˈɛvriˌwʌn stɒps tuː tɛl miː əˈbaʊt ðə mɪsˈteɪk, sɛd ˈdʒiːni. ænd ðɛn, ðeɪ ˈɔːlweɪz baɪ ˈlɛməˌneɪd. ˈdʒiːni hɛld ʌp ə dʒɑːr fʊl əv ˈmʌni ænd smaɪld/", "vi": "'Mọi người đều dừng lại để góp ý lỗi sai cho cháu,' Jeannie đáp. 'Và thế là họ luôn mua nước chanh.' Jeannie giơ cao hũ đựng đầy tiền và mỉm cười rạng rỡ." }
    ]
  },
  {
    "day": 2,
    "title": "Teeth",
    "image": "09 September/images/day_02.webp",
    "audio": "09 September/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "On Monday, Amy bit into some corn. 'Ouch!' she said. Her tooth felt strange.", "ipa": "/ɒn ˈmʌndeɪ, ˈeɪmi bɪt ˈɪntuː sʌm kɔːrn. aʊtʃ!, ʃiː sɛd. hɜːr tuːθ fɛlt streɪndʒ/", "vi": "Thứ Hai, Amy cắn một bắp ngô. 'Ái chà!' cô bé kêu lên. Chiếc răng của cô bỗng thấy lạ lạ." },
      { "start": 12.0, "en": "On Tuesday, Amy bit into an apple. 'Ouch!' she said. Her tooth felt wiggly.", "ipa": "/ɒn ˈtuːzdeɪ, ˈeɪmi bɪt ˈɪntuː ən ˈæpl. aʊtʃ!, ʃiː sɛd. hɜːr tuːθ fɛlt ˈwɪɡli/", "vi": "Thứ Ba, Amy cắn một quả táo. 'Ái chà!' cô bé lại kêu. Chiếc răng bắt đầu lung lay." },
      { "start": 19.0, "en": "On Wednesday, Amy bit into a piece of cheese. 'Ouch!' she said. 'My tooth is loose!' She had heard about kids losing their teeth and she didn't like the way it sounded. She wanted to keep all of her teeth.", "ipa": "/ɒn ˈwɛnzdeɪ, ˈeɪmi bɪt ˈɪntuː ə piːs əv tʃiːz. aʊtʃ!, ʃiː sɛd. maɪ tuːθ ɪz luːs! ʃiː hæd hɜːrd əˈbaʊt kɪdz ˈluːzɪŋ ðɛər tiːθ ænd ʃiː ˈdɪdnt laɪk ðə weɪ ɪt ˈsaʊndɪd. ʃiː ˈwɒntɪd tuː kiːp ɔːl əv hɜːr tiːθ/", "vi": "Thứ Tư, Amy cắn một miếng phô mai. 'Ái chà!' cô thét lên. 'Răng tớ sắp rụng rồi!' Cô từng nghe các bạn kể chuyện thay răng và không thích chút nào. Cô muốn giữ lại tất cả hàm răng của mình." },
      { "start": 35.0, "en": "On Thursday, she was careful. So she ate yogurt, oatmeal and pudding. It worked. She didn't lose any of her teeth.", "ipa": "/ɒn ˈθɜːrzdeɪ, ʃiː wɒz ˈkɛrfʊl. soʊ ʃiː eɪt ˈjoʊɡərt, ˈoʊtˌmiːl ænd ˈpʊdɪŋ. ɪt wɜːrkt. ʃiː ˈdɪdnt luːz ˈɛni əv hɜːr tiːθ/", "vi": "Thứ Năm, cô bé cẩn thận hơn hẳn bằng cách ăn sữa chua, cháo yến mạch và bánh pudding. Cách này rất hiệu quả, cô chẳng bị rụng chiếc răng nào." },
      { "start": 48.0, "en": "On Friday, her mom made pizza for dinner. She poked the pizza. It felt soft enough, so she bit into a slice. 'Ouch!' she cried. Her tooth had fallen out!", "ipa": "/ɒn ˈfraɪdeɪ, hɜːr mɒm meɪd ˈpiːtsə fɔːr ˈdɪnər. ʃiː poʊkt ðə ˈpiːtsə. ɪt fɛlt sɒft ɪˈnʌf, soʊ ʃiː bɪt ˈɪntuː ə slaɪs. aʊtʃ!, ʃiː kraɪd. hɜːr tuːθ hæd ˈfɔːlən aʊt/", "vi": "Thứ Sáu, mẹ làm bánh pizza cho bữa tối. Cô bé ấn thử thấy bánh đủ mềm nên cắn một miếng. 'Ái chà!' cô khóc thét lên. Chiếc răng đã rụng ra mất rồi!" },
      { "start": 62.0, "en": "That night, Amy put her tooth under her pillow. In the morning, her tooth was gone. But, in its place was a coin!", "ipa": "/ðæt naɪt, ˈeɪmi pʊt hɜːr tuːθ ˈʌndər hɜːr ˈpɪloʊ. ɪn ðə ˈmɔːrnɪŋ, hɜːr tuːθ wɒz ɡɒn. bʌt, ɪn ɪts pleɪs wɒz ə kɔɪn/", "vi": "Đêm đó, Amy đặt chiếc răng dưới gối. Sáng hôm sau thức dậy, chiếc răng đã biến mất nhưng thay vào đó lại là một đồng xu sáng loáng!" },
      { "start": 72.0, "en": "On Saturday, Amy ate corn on the cob, an apple, a piece of cheese and pizza. She wanted to lose more teeth!", "ipa": "/ɒn ˈsætərdeɪ, ˈeɪmi eɪt kɔːrn ɒn ðə kɒb, ən ˈæpl, ə piːs əv tʃiːz ænd ˈpiːtsə. ʃiː ˈwɒntɪd tuː luːz mɔːr tiːθ/", "vi": "Thứ Bảy, Amy thoải mái ăn bắp ngô luộc, táo, phô mai và pizza. Giờ thì cô bé lại cực kỳ mong rụng thêm nhiều răng nữa!" }
    ]
  },
  {
    "day": 3,
    "title": "The Boy Who Cares",
    "image": "09 September/images/day_03.webp",
    "audio": "09 September/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Sandy is seven years old. Recently, his mom noticed that Sandy worries about things a lot.", "ipa": "/ˈsændi ɪz ˈsɛvn jɪərz oʊld. ˈriːsəntli, hɪz mɒm ˈnoʊtɪst ðæt ˈsændi ˈwʌriz əˈbaʊt θɪŋz ə lɒt/", vi: "Sandy mới bảy tuổi. Dạo gần đây, mẹ nhận thấy cậu bé hay lo lắng về mọi thứ xung quanh." },
      { "start": 12.0, "en": "Every night before bed, Sandy's mom fills the bathtub for her son to take a bath. She used to fill it more than half full so that he could enjoy his hot bath.", "ipa": "/ˈɛvri naɪt bɪˈfɔːr bɛd, ˈsandiz mɒm fɪlz ðə ˈbæˌtʌb fɔːr hɜːr sʌn tuː teɪk ə bæθ. ʃiː juːzd tuː fɪl ɪt mɔːr ðæn hæf fʊl soʊ ðæt hiː kʊd ɪnˈdʒɔɪ hɪz hɒt bæθ/", "vi": "Mỗi tối trước khi đi ngủ, mẹ thường xả nước đầy bồn tắm để cậu con trai ngâm mình. Trước kia mẹ thường xả hơn nửa bồn để con ngâm nước nóng thỏa thích." },
      { "start": 25.0, "en": "But now, Sandy asks his mom to shut off the tap when the tub is only one third full.", "ipa": "/bʌt naʊ, ˈsændi ɑːsks hɪz mɒm tuː ʃʌt ɔːf ðə tæp wɛn ðə tʌb ɪz ˈoʊnli wʌn θɜːrd fʊl/", "vi": "Nhưng giờ đây, Sandy toàn nhờ mẹ khóa vòi khi nước mới chỉ ngập một phần ba bồn." },
      { "start": 33.0, "en": "Why? Sandy tells his mom that it is not easy for water to come to the tap. He doesn't want to waste any.", "ipa": "/waɪ? ˈsændi tɛlz hɪz mɒm ðæt ɪt ɪz nɒt ˈiːzi fɔːr ˈwɔːtər tuː kʌm tuː ðə tæp. hiː ˈdʌznt wɒnt tuː weɪst ˈɛni/", "vi": "Tại sao vậy? Sandy giải thích với mẹ rằng nước sạch chảy đến vòi không phải chuyện dễ dàng và cậu không muốn lãng phí dù chỉ một giọt." },
      { "start": 43.0, "en": "He says, 'Our teacher said that many people have trouble getting drinking water. Some kids walk miles to fetch water.'", "ipa": "/hiː sɛz, ˈaʊər ˈtiːtʃər sɛd ðæt ˈmɛni ˈpiːpl hæv ˈtrʌbl ˈɡɛtɪŋ ˈdrɪŋkɪŋ ˈwɔːtər. sʌm kɪdz wɔːk maɪlz tuː fɛtʃ ˈwɔːtər/", "vi": "Cậu bé nói: 'Thầy giáo bảo nhiều nơi trên thế giới đang thiếu nước sinh hoạt trầm trọng. Nhiều bạn nhỏ phải đi bộ hàng dặm đường mới gánh được nước về đấy mẹ ạ.'" },
      { "start": 56.0, "en": "Mom is moved by her little son. She tells her friends, 'Sandy is only seven, but he thinks about how to solve problems in the world.'", "ipa": "/mɒm ɪz muːvd baɪ hɜːr ˈlɪtl sʌn. ʃiː tɛlz hɜːr frɛndz, ˈsændi ɪz ˈoʊnli ˈsɛvn, bʌt hiː θɪŋks əˈbaʊt haʊ tuː sɒlv ˈprɒbləmz ɪn ðə wɜːrld/", vi: "Mẹ vô cùng xúc động trước tấm lòng của cậu con trai nhỏ. Mẹ hay khoe với bạn bè: 'Sandy mới bảy tuổi thôi mà đã biết trăn trở tìm cách giải quyết các vấn đề lớn của thế giới rồi.'" },
      { "start": 68.0, "en": "She then adds, 'Shouldn't we all do our share to save this planet? We should not let our children worry all the time.' Yes. They all agree.", "ipa": "/ʃiː ðɛn ædz, ˈʃʊdnt wiː ɔːl duː ˈaʊər ʃɛər tuː seɪv ðɪs ˈplænɪt? wiː ʃʊd nɒt lɛt ˈaʊər ˈtʃɪldrən ˈwʌri ɔːl ðə taɪm. jɛs. ðeɪ ɔːl əˈɡriː/", "vi": "Mẹ nói thêm: 'Chẳng phải tất cả chúng ta nên chung tay cứu lấy hành tinh này sao? Ta không thể để con trẻ cứ mãi lo âu như thế được.' Vâng, mọi người đều đồng tình như thế." }
    ]
  },
  {
    "day": 4,
    "title": "Car Keys",
    "image": "09 September/images/day_04.webp",
    "audio": "09 September/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Freddy came to his father and asked, 'Dad, may I borrow your car keys?' 'I don't think so!' answered his father. 'You're not ready to drive yet.'", "ipa": "/wʌn deɪ, ˈfrɛdi keɪm tuː hɪz ˈfɑːðər ænd ɑːskt, dæd, meɪ aɪ ˈbɒroʊ jɔːr kɑːr kiːz? aɪ doʊnt θɪŋk soʊ!, ˈɑːnsərd hɪz ˈfɑːðər. jʊər nɒt ˈrɛdi tuː draɪv jɛt/", "vi": "Một hôm, Freddy đến gặp bố và xin mượn chìa khóa ô tô. 'Bố không nghĩ thế đâu!' bố từ chối ngay. 'Con chưa đủ tuổi và chưa sẵn sàng để lái xe đâu.'" },
      { "start": 16.0, "en": "Freddy laughed. 'Mom locked the car. I just need to get my baseball glove from the front seat.' 'I see. Here you go,' said Dad. 'Just don't try to drive.' 'Thanks,' said Freddy. 'I'll bring them right back.'", "ipa": "/ˈfrɛdi lɑːft. mɒm lɒkt ðə kɑːr. aɪ dʒʌst niːd tuː ɡɛt maɪ ˈbeɪsˌbɔːl ɡlʌv frɒm ðə frʌnt siːt. aɪ siː. hɪər juː ɡoʊ, sɛd dæd. dʒʌst doʊnt traɪ tuː draɪv. θæŋks, sɛd ˈfrɛdi. aɪl brɪŋ ðɛm raɪt bæk/", "vi": "Freddy cười xòa: 'Mẹ khóa cửa xe mất rồi, con chỉ muốn lấy chiếc găng tay bóng chày ở ghế trước thôi.' 'À ra vậy, cầm lấy này,' bố đưa chìa khóa. 'Miễn đừng tò mò tập lái nhé.' 'Vâng, con mang trả lại ngay đây ạ,' Freddy đáp." },
      { "start": 32.0, "en": "A couple of minutes later, Freddy got his glove and started walking back. Suddenly, the car started moving. Freddy raced after it, unlocked the door and grabbed the emergency break. The car stopped rolling.", "ipa": "/ə ˈkʌpl əv ˈmɪnɪts ˈleɪtər, ˈfrɛdi ɡɒt hɪz ɡlʌv ænd ˈstɑːrtɪd ˈwɔːkɪŋ bæk. ˈsʌdənli, ðə kɑːr ˈstɑːrtɪd ˈmuːvɪŋ. ˈfrɛdi reɪst ˈɑːftər ɪt, ˌʌnˈlɒkt ðə dɔːr ænd ɡræbt ði ɪˈmɜːrdʒənsi breɪk. ðə kɑːr stɒpt ˈroʊlɪŋ/", "vi": "Vài phút sau, lấy được găng tay xong, Freddy thong thả quay lại. Bỗng nhiên, chiếc xe chầm chậm lăn bánh! Cậu hộc tốc đuổi theo, mở cửa và giật phắt phanh tay. Chiếc xe khựng lại đứng yên." },
      { "start": 48.0, "en": "Dad came running out of the house. 'What did you do?' he asked. 'I must have hit something while I was getting my glove,' answered Freddy. 'I'm sorry. I didn't mean to drive the car.'", "ipa": "/dæd keɪm ˈrʌnɪŋ aʊt əv ðə haʊs. wɒt dɪd juː duː?, hiː ɑːskt. aɪ mʌst hæv hɪt ˈsʌmθɪŋ waɪl aɪ wɒz ˈɡɛtɪŋ maɪ ɡlʌv, ˈɑːnsərd ˈfrɛdi. aɪm ˈsɒri. aɪ ˈdɪdnt miːn tuː draɪv ðə kɑːr/", "vi": "Bố hộc tốc chạy từ trong nhà ra: 'Con làm cái quái gì thế?' 'Chắc lúc lấy găng tay con vô tình đụng phải cần số,' Freddy thanh minh. 'Con xin lỗi, con không cố ý lái xe đâu ạ.'" },
      { "start": 62.0, "en": "'I know,' said Dad. 'Accidents happen. I'm glad you acted quickly. But, next time you kids want something from the car, I'll get it for you. That made me age way too fast and I can't afford to do that!'", "ipa": "/aɪ noʊ, sɛd dæd. ˈæksɪdənts ˈhæpən. aɪm ɡlæd juː ˈæktɪd ˈkwɪkli. bʌt, nɛkst taɪm juː kɪdz wɒnt ˈsʌmθɪŋ frɒm ðə kɑːr, aɪl ɡɛt ɪt fɔːr juː. ðæt meɪd miː eɪdʒ weɪ tuː fɑːst ænd aɪ kænt əˈfɔːrd tuː duː ðæt!/", "vi": "'Bố biết rồi,' bố thở phào. 'Tai nạn có thể xảy ra bất cứ lúc nào, may mà con xử lý kịp thời. Nhưng từ nay về sau, cứ cần gì ở xe thì bảo bố lấy cho nhé. Vừa rồi suýt nữa làm bố già đi chục tuổi mất thôi!'" }
    ]
  },
  {
    "day": 5,
    "title": "Red Wolves",
    "image": "09 September/images/day_05.webp",
    "audio":