if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["05 May"] = [
  {
    "day": 1,
    "title": "No More Pork",
    "image": "05 May/images/day_01.webp",
    "audio": "05 May/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "Irene received a little piglet from her aunt. But it wasn't a real pig. It was a wool piglet that her aunt had knit. Little Irene just loved it!", "ipa": "/aɪˈriːn rɪˈsiːvd ə ˈlɪtl ˈpɪɡlɪt frɒm hɜːr ænt. bʌt ɪt ˈwɒznt ə rɪəl pɪɡ. ɪt wɒz ə wʊl ˈpɪɡlɪt ðæt hɜːr ænt hæd nɪt. ˈlɪtl aɪˈriːn dʒʌst lʌvd ɪt!/", "vi": "Irene nhận được một chú heo con từ người dì. Nhưng đó không phải là heo thật mà là chú heo bằng len do dì tự tay đan. Bé Irene thích mê món quà này!" },
      { "start": 16.5, "en": "After Irene received this gift, something unusual happened. Irene stopped eating pork. And she would not let her parents eat pork either.", "ipa": "/ˈɑːftər aɪˈriːn rɪˈsiːvd ðɪs ɡɪft, ˈsʌmθɪŋ ʌnˈjuːʒuəl ˈhæpənd. aɪˈriːn stɒpt ˈiːtɪŋ pɔːrk. ænd ʃiː wʊd nɒt lɛt hɜːr ˈpeərənts iːt pɔːrk ˈaɪðər/", "vi": "Sau khi nhận được món quà, một chuyện lạ lùng đã xảy ra: Irene không chịu ăn thịt heo nữa, và cô bé cũng không cho bố mẹ ăn thịt heo luôn." },
      { "start": 27.0, "en": "'Why?' asked her mother. Irene answered, 'Because piglets are my friends. I don't want them to be killed.'", "ipa": "/waɪ?, ɑːskt hɜːr ˈmʌðər. aɪˈriːn ˈɑːnsərd, bɪˈkɒz ˈpɪɡlɪts ɑːr maɪ frɛndz. aɪ doʊnt wɒnt ðɛm tuː biː kɪld/", "vi": "'Tại sao thế con?' mẹ hỏi. Irene đáp: 'Vì heo con là bạn của con. Con không muốn các bạn ấy bị giết thịt.'" },
      { "start": 38.0, "en": "Later, Irene told her mom about her plan for the future. 'I want to have a HUGE house when I grow up,' she said. 'Why do you need a huge house?' asked her mom.", "ipa": "/ˈleɪtər, aɪˈriːn toʊld hɜːr mɒm əˈbaʊt hɜːr plæn fɔːr ðə ˈfjuːtʃər. aɪ wɒnt tuː hæv ə hjuːdʒ haʊs wɛn aɪ ɡroʊ ʌp, ʃiː sɛd. waɪ duː juː niːd ə hjuːdʒ haʊs?, ɑːskt hɜːr mɒm/", "vi": "Sau đó, Irene kể cho mẹ nghe về dự định tương lai: 'Lớn lên con muốn có một ngôi nhà THẬT LỚN,' bé nói. 'Sao con lại cần nhà lớn thế?' mẹ hỏi." },
      { "start": 54.0, "en": "'Because,' she said, 'I want to invite all the piglets in the whole world to live there.' Irene's mom looked at her little girl. She realized just how much Irene loved piglets!", "ipa": "/bɪˈkɒz, ʃiː sɛd, aɪ wɒnt tuː ɪnˈvaɪt ɔːl ðə ˈpɪɡlɪts ɪn ðə hoʊl wɜːrld tuː lɪv ðɛər. aɪˈriːnz mɒm lʊkt æt hɜːr ˈlɪtl ɡɜːrl. ʃiː ˈriːəlaɪzd dʒʌst haʊ mʌtʃ aɪˈriːn lʌvd ˈpɪɡlɪts!/", "vi": "'Bởi vì,' cô bé nói, 'con muốn mời tất cả các bạn heo con trên khắp thế giới về đó sống cùng con.' Mẹ nhìn cô con gái nhỏ và nhận ra Irene yêu quý heo con biết nhường nào!" }
    ]
  },
  {
    "day": 2,
    "title": "Watermelon",
    "image": "05 May/images/day_02.webp",
    "audio": "05 May/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "My uncle is a farmer. He grows watermelons. Each year in June, he harvests his watermelons. Then he sells them at the farmer's market.", "ipa": "/maɪ ˈʌŋkl ɪz ə ˈfɑːrmər. hiː ɡroʊz ˈwɔːtərˌmɛlənz. iːtʃ jɪər ɪn dʒuːn, hiː ˈhɑːrvɪsts hɪz ˈwɔːtərˌmɛlənz. ðɛn hiː sɛlz ðɛm æt ðə ˈfɑːrmərz ˈmɑːrkɪt/", "vi": "Chú tôi là một nông dân trồng dưa hấu. Hằng năm cứ vào tháng Sáu, chú lại thu hoạch dưa hấu rồi mang ra chợ nông sản bán." },
      { "start": 16.0, "en": "This year, someone began selling watermelons in early May. Most people think, 'The earlier, the better.' If they sell their watermelons early, surely they can make more money because people can't wait to buy their first watermelon of the season—even at a higher price.", "ipa": "/ðɪs jɪər, ˈsʌmwʌn bɪˈɡæn ˈsɛlɪŋ ˈwɔːtərˌmɛlənz ɪn ˈɜːrli meɪ. moʊst ˈpiːpl θɪŋk, ði ˈɜːrliər, ðə ˈbɛtər. ɪf ðeɪ sɛl ðɛər ˈwɔːtərˌmɛlənz ˈɜːrli, ˈʃʊərli ðeɪ kæn meɪk mɔːr ˈmʌni bɪˈkɒz ˈpiːpl kænt weɪt tuː baɪ ðɛər fɜːrst ˈwɔːtərˌmɛlən əv ðə ˈsiːzn—ˈiːvn æt ə ˈhaɪər praɪs/", "vi": "Năm nay, có người đã bắt đầu bán dưa hấu từ đầu tháng Năm. Nhiều người nghĩ 'càng sớm càng tốt', bán sớm chắc chắn kiếm được nhiều tiền hơn vì ai nấy đều nôn nóng mua quả dưa đầu mùa — dù giá có đắt hơn." },
      { "start": 36.0, "en": "But there is a problem. Watermelons take time to grow. The fruits are juicy and sweet only when they are fully grown.", "ipa": "/bʌt ðɛər ɪz ə ˈprɒbləm. ˈwɔːtərˌmɛlənz teɪk taɪm tuː ɡroʊ. ðə fruːts ɑːr ˈdʒuːsi ænd swiːt ˈoʊnli wɛn ðeɪ ɑːr ˈfʊli ɡroʊn/", "vi": "Thế nhưng có một vấn đề: Dưa hấu cần thời gian để phát triển. Trái dưa chỉ thực sự mọng nước và ngọt lịm khi đã chín già đủ độ." },
      { "start": 48.0, "en": "Grandma saw some farmers rushing to harvest their watermelons. She told my uncle, 'Don't be a fool. Think about it. If you buy a watermelon that tastes sour, will you buy it again? A farmer should always be proud of growing the best food for people.'", "ipa": "/ˈɡrænmɑː sɔː sʌm ˈfɑːrmərz ˈrʌʃɪŋ tuː ˈhɑːrvɪst ðɛər ˈwɔːtərˌmɛlənz. ʃiː toʊld maɪ ˈʌŋkl, doʊnt biː ə fuːl. θɪŋk əˈbaʊt ɪt. ɪf juː baɪ ə ˈwɔːtərˌmɛlən ðæt teɪsts ˈsaʊər, wɪl juː baɪ ɪt əˈɡɛn? ə ˈfɑːrmər ʃʊd ˈɔːlweɪz biː praʊd əv ˈɡroʊɪŋ ðə bɛst fuːd fɔːr ˈpiːpl/", "vi": "Bà tôi thấy vài nông dân vội vã hái dưa non bèn khuyên chú: 'Đừng dại thế con. Nghĩ xem, nếu mua phải quả dưa chua loét thì người ta có mua lại lần nữa không? Một người làm nông phải luôn tự hào vì làm ra nông sản ngon nhất cho mọi người.'" },
      { "start": 68.0, "en": "Of course, my uncle didn't sell his watermelons early. He sells his sweet, juicy watermelons with pride.", "ipa": "/əv kɔːrs, maɪ ˈʌŋkl ˈdɪdnt sɛl hɪz ˈwɔːtərˌmɛlənz ˈɜːrli. hiː sɛlz hɪz swiːt, ˈdʒuːsi ˈwɔːtərˌmɛlənz wɪð praɪd/", "vi": "Tất nhiên, chú tôi không hề bán dưa hái non. Chú luôn tự hào bán những trái dưa chín già ngọt lịm, mọng nước." }
    ]
  },
  {
    "day": 3,
    "title": "Honey Bees",
    "image": "05 May/images/day_03.webp",
    "audio": "05 May/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Buzz. Buzz. We visited a farmer today. He is not a regular farmer. He's a beekeeper. His honey bees make honey. I love this sweet sticky treat!", "ipa": "/bʌz. bʌz. wiː ˈvɪzɪtɪd ə ˈfɑːrmər təˈdeɪ. hiː ɪz nɒt ə ˈrɛɡjələr ˈfɑːrmər. hiːz ə ˈbiːˌkiːpər. hɪz ˈhʌni biːz meɪk ˈhʌni. aɪ lʌv ðɪs swiːt ˈstɪki triːt!/", "vi": "Vo ve. Vo ve. Hôm nay chúng tôi đến thăm một bác nông dân đặc biệt — một người nuôi ong lấy mật. Đàn ong của bác làm ra mật ngọt, và tôi mê tít món quà ngọt ngào dính dính này!" },
      { "start": 16.5, "en": "Honey bees are the only insects that make food for humans. How do they do it?", "ipa": "/ˈhʌni biːz ɑːr ði ˈoʊnli ˈɪnsɛkts ðæt meɪk fuːd fɔːr ˈhjuːmənz. haʊ duː ðeɪ duː ɪt?/", vi: "Ong mật là loài côn trùng duy nhất tạo ra thức ăn cho con người. Chúng làm điều đó bằng cách nào?" },
      { "start": 23.0, "en": "They gather a sweet liquid from flowers and turn it into honey. They live in a hive and travel many kilometres in search of flowers.", "ipa": "/ðeɪ ˈɡæðər ə swiːt ˈlɪkwɪd frɒm ˈflaʊərz ænd tɜːrn ɪt ˈɪntuː ˈhʌni. ðeɪ lɪv ɪn ə haɪv ænd ˈtrævl ˈmɛni kɪˈlɒmɪtərz ɪn sɜːrtʃ əv ˈflaʊərz/", "vi": "Chúng hút dịch ngọt từ hoa rồi luyện thành mật ong. Chúng sống trong tổ và bay xa hàng cây số để tìm hoa." },
      { "start": 34.0, "en": "Honey bees travel more than 80,000 kilometres and visit about 2 million flowers to make just half a kilogram of honey!", "ipa": "/ˈhʌni biːz ˈtrævl mɔːr ðæn ˈeɪti ˈθaʊznd kɪˈlɒmɪtərz ænd ˈvɪzɪt əˈbaʊt tuː ˈmɪljən ˈflaʊərz tuː meɪk dʒʌst hæf ə ˈkɪləˌɡræm əv ˈhʌni!/", "vi": "Những chú ong mật phải bay hơn 80.000 km và ghé thăm khoảng 2 triệu bông hoa chỉ để làm ra nửa cân mật ong!" },
      { "start": 47.0, "en": "Does the beekeeper get stung a lot? Well, he wears special clothing for protection. He has a special hat with a net that covers his face. He wears gloves and a shirt with long sleeves.", "ipa": "/dʌz ðə ˈbiːˌkiːpər ɡɛt stʌŋ ə lɒt? wɛl, hiː wɛərz ˈspɛʃl ˈkloʊðɪŋ fɔːr prəˈtɛkʃn. hiː hæz ə ˈspɛʃl hæt wɪð ə nɛt ðæt ˈkʌvərz hɪz feɪs. hiː wɛərz ɡlʌvz ænd ə ʃɜːrt wɪð lɔːŋ sliːvz/", "vi": "Bác nuôi ong có bị đốt nhiều không? Bác mặc đồ bảo hộ chuyên dụng: Chiếc mũ đặc biệt có lưới phủ che mặt, găng tay dày và áo dài tay kín đáo." },
      { "start": 62.0, "en": "He uses a little machine that makes smoke. He says this helps to keep the bees calm. It was amazing to see him work with thousands of bees flying around!", "ipa": "/hiː ˈjuːzɪz ə ˈlɪtl məˈʃiːn ðæt meɪks smoʊk. hiː sɛz ðɪs hɛlps tuː kiːp ðə biːz kɑːm. ɪt wɒz əˈmeɪzɪŋ tuː siː hɪm wɜːrk wɪð ˈθaʊzndz əv biːz ˈflaɪɪŋ əˈraʊnd!/", "vi": "Bác dùng một bình tạo khói nhỏ để giữ cho bầy ong bình tĩnh lại. Thật đáng kinh ngạc khi thấy bác làm việc giữa hàng ngàn chú ong bay rợp xung quanh!" }
    ]
  },
  {
    "day": 4,
    "title": "Chores",
    "image": "05 May/images/day_04.webp",
    "audio": "05 May/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was a hot summer day. Amy did not feel like doing anything at home. 'I'm hot. Can I go swim in the pool?' asked Amy. Mom said, 'You may swim after you finish your chores.'", "ipa": "/ɪt wɒz ə hɒt ˈsʌmər deɪ. ˈeɪmi dɪd nɒt fiːl laɪk ˈduːɪŋ ˈɛniˌθɪŋ æt hoʊm. aɪm hɒt. kæn aɪ ɡoʊ swɪm ɪn ðə puːl?, ɑːskt ˈeɪmi. mɒm sɛd, juː meɪ swɪm ˈɑːftər juː ˈfɪnɪʃ jɔːr tʃɔːrz/", "vi": "Đó là một ngày hè oi ả, Amy chẳng muốn làm gì ở nhà cả. 'Nóng quá mẹ ơi, con đi bơi được không ạ?' Mẹ bảo: 'Con làm xong việc nhà rồi hãy đi bơi nhé.'" },
      { "start": 17.0, "en": "Amy swept the floor quickly. 'I'm so hot. I want to cool off in the pool.' 'You may, but only after you finish your chores,' Mom insisted.", "ipa": "/ˈeɪmi swɛpt ðə flɔːr ˈkwɪkli. aɪm soʊ hɒt. aɪ wɒnt tuː kuːl ɔːf ɪn ðə puːl. juː meɪ, bʌt ˈoʊnli ˈɑːftər juː ˈfɪnɪʃ jɔːr tʃɔːrz, mɒm ɪnˈsɪstɪd/", "vi": "Amy quét nhà thật nhanh. 'Con nóng quá, muốn xuống hồ bơi cho mát.' 'Được chứ, nhưng phải làm xong hết việc nhà đã,' mẹ kiên quyết." },
      { "start": 29.0, "en": "So, Amy washed the dishes. 'I'm too hot!' said Amy. 'I just want to go swimming!' Mom handed Amy two dollars. 'Good job finishing your chores, Amy. Here's your allowance for this week,' said Mom. 'You can go swimming now.'", "ipa": "/soʊ, ˈeɪmi wɒʃt ðə ˈdɪʃɪz. aɪm tuː hɒt!, sɛd ˈeɪmi. aɪ dʒʌst wɒnt tuː ɡoʊ ˈswɪmɪŋ! mɒm ˈhændɪd ˈeɪmi tuː ˈdɒlərz. ɡʊd dʒɒb ˈfɪnɪʃɪŋ jɔːr tʃɔːrz, ˈeɪmi. hɪərz jɔːr əˈlaʊəns fɔːr ðɪs wiːk, sɛd mɒm. juː kæn ɡoʊ ˈswɪmɪŋ naʊ/", vi: "Thế là Amy rửa bát đĩa sạch sẽ: 'Nóng nực quá mẹ ơi! Con chỉ muốn đi bơi thôi!' Mẹ mỉm cười đưa cho Amy hai đô-la: 'Làm tốt lắm Amy. Đây là tiền tiêu vặt tuần này của con, giờ con có thể đi bơi rồi đấy.'" },
      { "start": 48.0, "en": "Ding, ding, ding. Ding, ding, ding. 'The ice cream truck!' yelled Amy. Amy ran down the street with her two dollars. She bought an ice cream bar.", "ipa": "/dɪŋ, dɪŋ, dɪŋ. dɪŋ, dɪŋ, dɪŋ. ðə aɪs kriːm trʌk!, jɛld ˈeɪmi. ˈeɪmi ræn daʊn ðə striːt wɪð hɜːr tuː ˈdɒlərz. ʃiː bɔːt ən aɪs kriːm bɑːr/", vi: "Kính coong, kính coong. 'Xe kem kìa!' Amy reo lên. Cầm hai đô-la trong tay, cô bé chạy tót ra phố mua ngay một que kem mát lạnh." },
      { "start": 60.0, "en": "She sat down on the curb and licked the cold sweet treat. 'This is even better than swimming!' said Amy. 'Especially since I earned it all myself!'", "ipa": "/ʃiː sæt daʊn ɒn ðə kɜːrb ænd lɪkt ðə koʊld swiːt triːt. ðɪs ɪz ˈiːvn ˈbɛtər ðæn ˈswɪmɪŋ!, sɛd ˈeɪmi. ɪˈspɛʃəli sɪns aɪ ɜːrnd ɪt ɔːl maɪˈsɛlf!/", vi: "Ngồi bệt bên lề đường nhâm nhi que kem ngọt ngào, Amy thích thú reo lên: 'Thế này còn tuyệt hơn cả đi bơi! Nhất là khi đây là que kem do chính tay mình kiếm được!'" }
    ]
  },
  {
    "day": 5,
    "title": "Food for Thought",
    "image": "05 May/images/day_05.webp",
    "audio": "05 May/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "What can we do to make the world a better place? Many people ask themselves this question. It's easy to see why. All over the world, people are hungry. A lot of kids don't go to school. Many kids don't have parents.", "ipa": "/wɒt kæn wiː duː tuː meɪk ðə wɜːrld ə ˈbɛtər pleɪs? ˈmɛni ˈpiːpl ɑːsk ðəmˈsɛlvz ðɪs ˈkwɛstʃən. ɪts ˈiːzi tuː siː waɪ. ɔːl ˈoʊvər ðə wɜːrld, ˈpiːpl ɑːr ˈhʌŋɡri. ə lɒt əv kɪdz doʊnt ɡoʊ tuː skuːl. ˈmɛni kɪdz doʊnt hæv ˈpeərənts/", vi: "Chúng ta có thể làm gì để thế giới tốt đẹp hơn? Rất nhiều người tự hỏi bản thân câu này. Khắp nơi trên thế giới, bao người còn đói rách, nhiều trẻ em thất học, nhiều em mồ côi cha mẹ." },
      { "start": 21.0, "en": "All these problems seem too big. What can I do? Just asking the question means you care. What's the next step? Just do something, ANYTHING.", "ipa": "/ɔːl ðiːz ˈprɒbləmz siːm tuː bɪɡ. wɒt kæn aɪ duː? dʒʌst ˈɑːskɪŋ ðə ˈkwɛstʃən miːnz juː kɛər. wɒts ðə nɛkst stɛp? dʒʌst duː ˈsʌmθɪŋ, ˈɛniˌθɪŋ/", vi: "Những vấn đề ấy dường như quá to lớn. Một mình tôi có thể làm được gì? Chỉ cần bạn trăn trở câu hỏi ấy thôi đã chứng tỏ bạn có lòng trắc ẩn rồi. Bước tiếp theo là gì? Hãy hành động, làm BẤT CỨ ĐIỀU GÌ có thể." },
      { "start": 33.0, "en": "You might have heard about Mother Teresa. She lived in India. One day, after seeing all the hunger and poverty around her, she decided to do something about it.", "ipa": "/juː maɪt hæv hɜːrd əˈbaʊt ˈmʌðər təˈreɪzə. ʃiː lɪvd ɪn ˈɪndiə. wʌn deɪ, ˈɑːftər ˈsiːɪŋ ɔːl ðə ˈhʌŋɡər ænd ˈpɒvərti əˈraʊnd hɜːr, ʃiː dɪˈsaɪdɪd tuː duː ˈsʌmθɪŋ əˈbaʊt ɪt/", vi: "Có thể bạn từng nghe về Mẹ Teresa ở Ấn Độ. Khi chứng kiến cảnh đói nghèo cùng cực quanh mình, bà quyết tâm phải hành động." },
      { "start": 47.0, "en": "So she spent her life helping to feed many hungry people. She worked day and night trying to make the world a little bit better. She once said, 'If you cannot feed one hundred people, then feed one person.'", "ipa": "/soʊ ʃiː spɛnt hɜːr laɪf ˈhɛlpɪŋ tuː fiːd ˈmɛni ˈhʌŋɡri ˈpiːpl. ʃiː wɜːrkt deɪ ænd naɪt ˈtraɪɪŋ tuː meɪk ðə wɜːrld ə ˈlɪtl bɪt ˈbɛtər. ʃiː wʌns sɛd, ɪf juː ˈkænɒt fiːd wʌn ˈhʌndrəd ˈpiːpl, ðɛn fiːd wʌn ˈpɜːrsn/", vi: "Bà dành cả cuộc đời cứu giúp và nuôi ăn bao người khốn khó, miệt mài ngày đêm làm cho thế giới tươi sáng hơn. Bà từng nói: 'Nếu con không thể nuôi nổi một trăm người, thì hãy nuôi lấy một người thôi.'" },
      { "start": 63.0, "en": "This is good advice. Think about it. What did she mean? There is always a way. But it's up to us to find it.", "ipa": "/ðɪs ɪz ɡʊd ədˈvaɪs. θɪŋk əˈbaʊt ɪt. wɒt dɪd ʃiː miːn? ðɛər ɪz ˈɔːlweɪz ə weɪ. bʌt ɪts ʌp tuː ʌs tuː faɪnd ɪt/", vi: "Đó là lời khuyên vô giá. Hãy suy ngẫm xem, ý của bà là gì? Luôn luôn có một con đường, quan trọng là chúng ta có sẵn lòng tìm ra nó hay không." }
    ]
  },
  {
    "day": 6,
    "title": "The Littler Hero",
    "image": "05 May/images/day_06.webp",
    "audio": "05 May/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "Daniel is only four years old. But he makes friends wherever he goes. Once in a while, he even teaches adults some lessons.", "ipa": "/ˈdænjəl ɪz ˈoʊnli fɔːr jɪərz oʊld. bʌt hiː meɪks frɛndz wɛrˈɛvər hiː ɡoʊz. wʌns ɪn ə waɪl, hiː ˈiːvn ˈtiːtʃɪz ˈædʌlts sʌm ˈlɛsnz/", vi: "Daniel mới tròn bốn tuổi nhưng đi tới đâu cậu bé cũng kết bạn được tới đó. Thỉnh thoảng, cậu bé còn dạy cho người lớn những bài học ý nghĩa." },
      { "start": 14.0, "en": "One time, Daniel was taking a bus with his mom. At one point during the bus ride, he saw an old lady getting on the bus. Daniel stood up right away. He wanted to give his seat to the lady even though he himself couldn't stand firmly on the moving bus.", "ipa": "/wʌn taɪm, ˈdænjəl wɒz ˈteɪkɪŋ ə bʌs wɪð hɪz mɒm. æt wʌn pɔɪnt ˈdjʊərɪŋ ðə bʌs raɪd, hiː sɔː ən oʊld ˈleɪdi ˈɡɛtɪŋ ɒn ðə bʌs. ˈdænjəl stʊd ʌp raɪt əˈweɪ. hiː ˈwɒntɪd tuː ɡɪv hɪz siːt tuː ðə ˈleɪdi ˈiːvn ðoʊ hiː hɪmˈsɛlf ˈkʊdnt stænd ˈfɜːrmli ɒn ðə ˈmuːvɪŋ bʌs/", vi: "Có lần đi xe buýt cùng mẹ, thấy một bà cụ bước lên xe, Daniel lập tức đứng dậy nhường ghế dù bản thân cậu bé còn đứng chưa vững trên chuyến xe đang chuyển động." },
      { "start": 32.0, "en": "Another time, Daniel's mom and dad were working in their garden. They were busy digging dirt for the flower bed. They didn't see their neighbour come out to his garden. But Daniel saw him. He ran to his parents and whispered, 'Mr. Becker is there. Say hello to him.'", "ipa": "/əˈnʌðər taɪm, ˈdænjəlz mɒm ænd dæd wɜːr ˈwɜːrkɪŋ ɪn ðɛər ˈɡɑːrdn. ðeɪ wɜːr ˈbɪzi ˈdɪɡɪŋ dɜːrt fɔːr ðə ˈflaʊər bɛd. ðeɪ ˈdɪdnt siː ðɛər ˈneɪbər kʌm aʊt tuː hɪz ˈɡɑːrdn. bʌt ˈdænjəl sɔː hɪm. hiː ræn tuː hɪz ˈpeərənts ænd ˈwɪspərd, ˈmɪstər ˈbɛkər ɪz ðɛər. seɪ həˈloʊ tuː hɪm/", vi: "Lần khác, bố mẹ đang cặm cụi cuốc đất trồng hoa ngoài vườn nên không để ý thấy bác hàng xóm bước ra. Daniel thấy liền chạy lại nhắc khẽ: 'Bác Becker kìa bố mẹ, chào bác đi ạ.'" },
      { "start": 51.0, "en": "Daniel's mom and dad stopped digging. They chatted with their neighbour. Daniel smiled when he saw them talking. Later, his parents said, 'We are really thankful to have a son who wants everyone in the world to be happy. He is our little hero.'", "ipa": "/ˈdænjəlz mɒm ænd dæd stɒpt ˈdɪɡɪŋ. ðeɪ ˈtʃætɪd wɪð ðɛər ˈneɪbər. ˈdænjəl smaɪld wɛn hiː sɔː ðɛm ˈtɔːkɪŋ. ˈleɪtər, hɪz ˈpeərənts sɛd, wiː ɑːr ˈrɪəli ˈθæŋkfʊl tuː hæv ə sʌn huː wɒnts ˈɛvriˌwʌn ɪn ðə wɜːrld tuː biː ˈhæpi. hiː ɪz ˈaʊər ˈlɪtl ˈhɪəroʊ/", vi: "Bố mẹ ngừng tay trò chuyện vui vẻ cùng người hàng xóm. Thấy mọi người thân thiện, Daniel mỉm cười mãn nguyện. Bố mẹ tự hào nói: 'Bố mẹ thực sự biết ơn vì có cậu con trai luôn muốn mọi người hạnh phúc. Con chính là người hùng bé nhỏ của bố mẹ.'" }
    ]
  },
  {
    "day": 7,
    "title": "Apples and the Pie",
    "image": "05 May/images/day_07.webp",
    "audio": "05 May/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was a nice autumn day. Mom and Dad decided to take the family to the apple farm. 'Yay!' shouted Will and Ann. The apple farm was one of their favourite places to go.", "ipa": "/ɪt wɒz ə naɪs ˈɔːtəm deɪ. mɒm ænd dæd dɪˈsaɪdɪd tuː teɪk ðə ˈfæməli tuː ði ˈæpl fɑːrm. jeɪ!, ˈʃaʊtɪd wɪl ænd æn. ði ˈæpl fɑːrm wɒz wʌn əv ðɛər ˈfeɪvərɪt ˈpleɪsɪz tuː ɡoʊ/", vi: "Đó là một ngày mùa thu đẹp trời, bố mẹ đưa cả nhà đi chơi nông trại táo. 'Hoan hô!' Will và Ann reo hò ầm ĩ. Nông trại táo luôn là điểm đến yêu thích của hai đứa." },
      { "start": 18.0, "en": "When they arrived at the farm, the air smelled sweet and yummy. Apple trees grew in rows on top of the hill. The kids could see perfect apples hanging on every branch.", "ipa": "/wɛn ðeɪ əˈraɪvd æt ðə fɑːrm, ði ɛər smɛld swiːt ænd ˈjʌmi. ˈæpl triːz ɡruː ɪn roʊz ɒn tɒp əv ðə hɪl. ðə kɪdz kʊd siː ˈpɜːrfɪkt ˈæplz ˈhæŋɪŋ ɒn ˈɛvri bræntʃ/", vi: "Đến nơi, không khí thoang thoảng mùi hương táo ngọt ngào. Những hàng táo thẳng tắp trải dài trên đồi, cành nào cũng trĩu những quả táo chín mọng tuyệt đẹp." },
      { "start": 31.0, "en": "A tractor pulled them on a wagon up the hill. There, they picked many different kinds of apples, filling a big basket to the top.", "ipa": "/ə ˈtræktər pʊld ðɛm ɒn ə ˈwæɡən ʌp ðə hɪl. ðɛər, ðeɪ pɪkt ˈmɛni ˈdɪfrənt kaɪndz əv ˈæplz, ˈfɪlɪŋ ə bɪɡ ˈbɑːskɪt tuː ðə tɒp/", vi: "Máy kéo chở cả nhà trên cỗ xe ngựa lên đồi. Ở đó, hai đứa hái đủ loại táo thơm ngon đầy ắp cả chiếc giỏ lớn." },
      { "start": 41.0, "en": "Will bit into an apple. It made a loud, crisp sound. Ann bit into an apple and juice started dripping down her chin.", "ipa": "/wɪl bɪt ˈɪntuː ən ˈæpl. ɪt meɪd ə laʊd, krɪsp saʊnd. æn bɪt ˈɪntuː ən ˈæpl ænd dʒuːs ˈstɑːrtɪd ˈdrɪpɪŋ daʊn hɜːr tʃɪn/", vi: "Will cắn một miếng táo giòn tan rôm rốp, còn Ann cắn vào quả táo ngọt lịm đến mức nước quả chảy tràn cả cằm." },
      { "start": 51.0, "en": "After Mom paid for the apples, the family took their basket of apples home. Mom peeled and sliced the apples. Then she rolled the dough. Finally, after all that work, she served everyone a slice of fresh apple pie. Yum!", "ipa": "/ˈɑːftər mɒm peɪd fɔːr ði ˈæplz, ðə ˈfæməli tʊk ðɛər ˈbɑːskɪt əv ˈæplz hoʊm. mɒm piːld ænd slaɪst ði ˈæplz. ðɛn ʃiː roʊld ðə doʊ. ˈfaɪnəli, ˈɑːftər ɔːl ðæt wɜːrk, ʃiː sɜːrvd ˈɛvriˌwʌn ə slaɪs əv frɛʃ ˈæpl paɪ. jʌm!/", vi: "Sau khi mẹ thanh toán tiền mua táo, cả nhà mang giỏ táo về. Mẹ gọt vỏ, thái lát táo rồi nhào bột nướng bánh. Sau bao công sức, mẹ chiêu đãi cả nhà món bánh táo nướng thơm lừng nóng hổi. Ngon tuyệt cú mèo!" }
    ]
  },
  {
    "day": 8,
    "title": "Walking to Montreal",
    "image": "05 May/images/day_08.webp",
    "audio": "05 May/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was Mother's Day. My uncle's restaurant was VERY busy. It seemed that every family took their mother out to eat that day.", "ipa": "/ɪt wɒz ˈmʌðərz deɪ. maɪ ˈʌŋklz ˈrɛstrɒnt wɒz ˈvɛri ˈbɪzi. ɪt siːmd ðæt ˈɛvri ˈfæməli tʊk ðɛər ˈmʌðər aʊt tuː iːt ðæt deɪ/", vi: "Đó là Ngày của Mẹ, nhà hàng của chú tôi ĐÔNG NGHỊT khách. Dường như mọi gia đình đều đưa mẹ ra ngoài ăn uống nhân dịp này." },
      { "start": 14.0, "en": "My uncle called me from the restaurant. 'Henry, people are lining up outside,' he said. 'Can you come to help out?' 'Sure!' I stopped playing my computer game and went to the restaurant with my brother.", "ipa": "/maɪ ˈʌŋkl kɔːld miː frɒm ðə ˈrɛstrɒnt. ˈhɛnri, ˈpiːpl ɑːr ˈlaɪnɪŋ ʌp ˈaʊtˌsaɪd, hiː sɛd. kæn juː kʌm tuː hɛlp aʊt? ʃʊər! aɪ stɒpt ˈpleɪɪŋ maɪ kəmˈpjuːtər ɡeɪm ænd wɛnt tuː ðə ˈrɛstrɒnt wɪð maɪ ˈbrʌðər/", vi: "Chú gọi điện cầu cứu: 'Henry ơi, khách xếp hàng dài ngoài cửa rồi, cháu sang phụ chú một tay được không?' 'Dạ được chứ!' Tôi gác lại trò chơi điện tử và cùng em trai chạy sang ngay." },
      { "start": 29.0, "en": "All we had to do was bring food and water to the tables and take the dirty dishes away when the customers were finished eating.", "ipa": "/ɔːl wiː hæd tuː duː wɒz brɪŋ fuːd ænd ˈwɔːtər tuː ðə ˈteɪblz ænd teɪk ðə ˈdɜːrti ˈdɪʃɪz əˈweɪ wɛn ðə ˈkʌstəmərz wɜːr ˈfɪnɪʃt ˈiːtɪŋ/", vi: "Công việc của chúng tôi là bưng bê đồ ăn, rót nước phục vụ bàn và dọn dẹp bát đĩa bẩn khi khách dùng bữa xong." },
      { "start": 39.0, "en": "The chefs and their helpers worked like crazy. The kitchen manager called out the orders. The kitchen helpers ran to get things in place. The chefs worked like magic, turning meats and vegetables into delicious food in just minutes.", "ipa": "/ðə ʃɛfs ænd ðɛər ˈhɛlpərz wɜːrkt laɪk ˈkreɪzi. ðə ˈkɪtʃɪn ˈmænɪdʒər kɔːld aʊt ði ˈɔːrdərz. ðə ˈkɪtʃɪn ˈhɛlpərz ræn tuː ɡɛt θɪŋz ɪn pleɪs. ðə ʃɛfs wɜːrkt laɪk ˈmædʒɪk, ˈtɜːrnɪŋ miːts ænd ˈvɛdʒtəblz ˈɪntuː dɪˈlɪʃəs fuːd ɪn dʒʌst ˈmɪnɪts/", vi: "Các đầu bếp và phụ bếp làm việc cật lực. Quản lý bếp gọi món liên tục, phụ bếp chạy đôn chạy đáo chuẩn bị nguyên liệu. Đầu bếp thoăn thoắt biến thịt rau thành những món ăn thơm ngon chỉ trong vài phút." },
      { "start": 57.0, "en": "I don't remember how many times I brought things in and out through that kitchen door. I just remember that at the end of the day, my legs were very sore. I was really tired. The next day, I told my friends, 'It felt like I walked all the way from Ottawa to Montreal.'", "ipa": "/aɪ doʊnt rɪˈmɛmbər haʊ ˈmɛni taɪmz aɪ brɔːt θɪŋz ɪn ænd aʊt θruː ðæt ˈkɪtʃɪn dɔːr. aɪ dʒʌst rɪˈmɛmbər ðæt æt ði ɛnd əv ðə deɪ, maɪ lɛɡz wɜːr ˈvɛri sɔːr. aɪ wɒz ˈrɪəli ˈtaɪərd. ðə nɛkst deɪ, aɪ toʊld maɪ frɛndz, ɪt fɛlt laɪk aɪ wɔːkt ɔːl ðə weɪ frɒm ˈɒtəwə tuː ˌmɒntriˈɔːl/", vi: "Tôi không nhớ nổi mình đã ra vào cánh cửa bếp đó bao nhiêu lần. Chỉ nhớ khi hết ngày, chân tôi mỏi nhừ rã rời. Hôm sau, tôi kể với đám bạn: 'Cảm giác như tớ vừa đi bộ một mạch từ Ottawa đến tận Montreal vậy.'" }
    ]
  },
  {
    "day": 9,
    "title": "The Greedy Monkey",
    "image": "05 May/images/day_09.webp",
    "audio": "05 May/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "Long ago, in India, a monkey was sitting in a tree, looking down over the jungle. A king and his servant stopped under that tree to rest their horses.", "ipa": "/lɒŋ əˈɡoʊ, ɪn ˈɪndiə, ə ˈmʌŋki wɒz ˈsɪtɪŋ ɪn ə triː, ˈlʊkɪŋ daʊn ˈoʊvər ðə ˈdʒʌŋɡl. ə kɪŋ ænd hɪz ˈsɜːrvənt stɒpt ˈʌndər ðæt triː tuː rɛst ðɛər ˈhɔːrsɪz/", vi: "Ngày xưa ở Ấn Độ, có một chú khỉ ngồi trên cây ngắm nhìn xuống khu rừng. Nhà vua và người hầu dừng chân dưới gốc cây ấy để cho ngựa nghỉ ngơi." },
      { "start": 16.0, "en": "The monkey sat watching the servant set out the peas for the horses. While the servant wasn't looking, the monkey rushed out of the tree and stole a handful of peas.", "ipa": "/ðə ˈmʌŋki sæt ˈwɒtʃɪŋ ðə ˈsɜːrvənt sɛt aʊt ðə piːz fɔːr ðə ˈhɔːrsɪz. waɪl ðə ˈsɜːrvənt ˈwɒznt ˈlʊkɪŋ, ðə ˈmʌŋki rʌʃt aʊt əv ðə triː ænd stoʊl ə ˈhændfʊl əv piːz/", vi: "Chú khỉ ngồi quan sát người hầu dọn đậu cho ngựa ăn. Nhân lúc người hầu sơ ý, chú khỉ lao nhanh xuống cây thó ngay một vốc đậu đầy." },
      { "start": 29.0, "en": "Then, he began climbing back up the tree quickly. But one pea fell from the monkey's hand as he climbed. Without thinking, the monkey opened his hand, trying to catch the pea.", "ipa": "/ðɛn, hiː bɪˈɡæn ˈklaɪmɪŋ bæk ʌp ðə triː ˈkwɪkli. bʌt wʌn piː fɛl frɒm ðə ˈmʌŋkiz hænd æz hiː klaɪmd. wɪˈðaʊt ˈθɪŋkɪŋ, ðə ˈmʌŋki ˈoʊpənd hɪz hænd, ˈtraɪɪŋ tuː kætʃ ðə piː/", vi: "Rồi chú vội vàng leo tót lên cây. Thế nhưng một hạt đậu bị rơi khỏi tay chú lúc đang leo. Chẳng suy nghĩ gì, chú khỉ vội xòe tay ra chộp lấy hạt đậu đó." },
      { "start": 43.0, "en": "Of course, as he did this, all the other peas fell out of his hand and dropped to the ground.", "ipa": "/əv kɔːrs, æz hiː dɪd ðɪs, ɔːl ði ˈʌðər piːz fɛl aʊt əv hɪz hænd ænd drɒpt tuː ðə ɡraʊnd/", vi: "Tất nhiên, khi chú mở tay ra, tất cả những hạt đậu còn lại trong vốc rơi lả tả xuống đất." },
      { "start": 52.0, "en": "The monkey watched sadly as the horses feasted on the peas. He was hungry, but there was nothing he could do. His one chance to get the sweet peas was gone.", "ipa": "/ðə ˈmʌŋki wɒtʃt ˈsædli æz ðə ˈhɔːrsɪz ˈfiːstɪd ɒn ðə piːz. hiː wɒz ˈhʌŋɡri, bʌt ðɛər wɒz ˈnʌθɪŋ hiː kʊd duː. hɪz wʌn tʃɑːns tuː ɡɛt ðə swiːt piːz wɒz ɡɒn/", vi: "Chú khỉ buồn bã nhìn đàn ngựa chén sạch số đậu. Bụng thì đói meo nhưng chú chẳng thể làm gì được nữa, cơ hội duy nhất có được những hạt đậu ngọt ngào đã tan biến mất." }
    ]
  },
  {
    "day": 10,
    "title": "Amazing English",
    "image": "05 May/images/day_10.webp",
    "audio": "05 May/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "There are only 26 letters in the English alphabet. It must be an easy language to learn, right? Well, ask anyone who has mastered English and they'll tell you that nothing could be further from the truth.", "ipa": "/ðɛər ɑːr ˈoʊnli ˈtwɛnti-sɪks ˈlɛtərz ɪn ði ˈɪŋɡlɪʃ ˈælfəbɛt. ɪt mʌst biː ən ˈiːzi ˈlæŋɡwɪdʒ tuː lɜːrn, raɪt? wɛl, ɑːsk ˈɛniˌwʌn huː hæz ˈmæstərd ˈɪŋɡlɪʃ ænd ðeɪl tɛl juː ðæt ˈnʌθɪŋ kʊd biː ˈfɜːrðər frɒm ðə truːθ/", vi: "Bảng chữ cái tiếng Anh chỉ có vỏn vẹn 26 chữ cái. Chắc hẳn đây là ngôn ngữ dễ học lắm nhỉ? Cứ thử hỏi những người thành thạo tiếng Anh xem, họ sẽ bảo bạn rằng sự thật hoàn toàn ngược lại đấy." },
      { "start": 21.0, "en": "Although English has only 26 letters, you can make many words with those letters. In fact, English has more words than any other language in the world. How many? About 800,000 words—give or take a few hundred.", "ipa": "/ɔːlˈðoʊ ˈɪŋɡlɪʃ hæz ˈoʊnli ˈtwɛnti-sɪks ˈlɛtərz, juː kæn meɪk ˈmɛni wɜːrdz wɪð ðoʊz ˈlɛtərz. ɪn fækt, ˈɪŋɡlɪʃ hæz mɔːr wɜːrdz ðæn ˈɛni ˈʌðər ˈlæŋɡwɪdʒ ɪn ðə wɜːrld. haʊ ˈmɛni? əˈbaʊt ˈeɪt ˈhʌndrəd ˈθaʊznd wɜːrdz—ɡɪv ɔːr teɪk ə fjuː ˈhʌndrəd/", vi: "Dù chỉ có 26 chữ cái nhưng bạn có thể ghép thành vô vàn từ ngữ. Thực tế, tiếng Anh có vốn từ phong phú hơn bất kỳ ngôn ngữ nào: Khoảng 800.000 từ vựng!" },
      { "start": 39.0, "en": "English words can be as short as just one letter. The shortest sentence in English is only one word. What is it? GO.", "ipa": "/ˈɪŋɡlɪʃ wɜːrdz kæn biː æz ʃɔːrt æz dʒʌst wʌn ˈlɛtər. ðə ˈʃɔːrtɪst ˈsɛntəns ɪn ˈɪŋɡlɪʃ ɪz ˈoʊnli wʌn wɜːrd. wɒt ɪz ɪt? ɡoʊ/", vi: "Từ tiếng Anh có thể ngắn ngủn chỉ bằng một chữ cái. Câu ngắn nhất trong tiếng Anh chỉ gồm duy nhất một từ: GO (Đi đi)." },
      { "start": 50.0, "en": "If you like spelling contests, you might like to know that there is a word in English with 1,909 letters in it. Can you imagine a single word with all those letters?", "ipa": "/ɪf juː laɪk ˈspɛlɪŋ ˈkɒntɛsts, juː maɪt laɪk tuː noʊ ðæt ðɛər ɪz ə wɜːrd ɪn ˈɪŋɡlɪʃ wɪð wʌn ˈθaʊznd naɪn ˈhʌndrəd ænd naɪn ˈlɛtərz ɪn ɪt. kæn juː ɪˈmædʒɪn ə ˈsɪŋɡl wɜːrd wɪð ɔːl ðoʊz ˈlɛtərz?/", vi: "Nếu bạn mê thi đánh vần, chắc bạn sẽ bất ngờ khi biết có một từ tiếng Anh dài tới 1.909 chữ cái. Có tưởng tượng nổi một từ dài ngoằng như vậy không?" },
      { "start": 64.0, "en": "This next sentence uses all 26 letters of the alphabet: The quick brown fox jumps over the lazy dog. If you are learning English, don't give up. Dig in and enjoy.", "ipa": "/ðɪs nɛkst ˈsɛntəns ˈjuːzɪz ɔːl ˈtwɛnti-sɪks ˈlɛtərz əv ði ˈælfəbɛt: ðə kwɪk braʊn fɒks dʒʌmps ˈoʊvər ðə ˈleɪzi dɒɡ. ɪf juː ɑːr ˈlɜːrnɪŋ ˈɪŋɡlɪʃ, doʊnt ɡɪv ʌp. dɪɡ ɪn ænd ɪnˈdʒɔɪ/", vi: "Câu sau đây sử dụng đủ 26 chữ cái trong bảng chữ cái: 'The quick brown fox jumps over the lazy dog'. Nếu đang học tiếng Anh, đừng nản lòng nhé. Hãy khám phá và tận hưởng nó!" }
    ]
  },
  {
    "day": 11,
    "title": "A Famous Writer?",
    "image": "05 May/images/day_11.webp",
    "audio": "05 May/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "Do you want to be a famous writer? I do. That's right. I love writing! When our teacher asked us what we wanted to be, many kids said they wanted to be doctors or police officers. But I said, 'I want to be a writer—a famous writer.' Everyone laughed. They didn't believe me.", "ipa": "/duː juː wɒnt tuː biː ə ˈfeɪməs ˈraɪtər? aɪ duː. ðæts raɪt. aɪ lʌv ˈraɪtɪŋ! wɛn ˈaʊər ˈtiːtʃər ɑːskt ʌs wɒt wiː ˈwɒntɪd tuː biː, ˈmɛni kɪdz sɛd ðeɪ ˈwɒntɪd tuː biː ˈdɒktərz ɔːr pəˈliːs ˈɒfɪsərz. bʌt aɪ sɛd, aɪ wɒnt tuː biː ə ˈraɪtər—ə ˈfeɪməs ˈraɪtər. ˈɛvriˌwʌn lɑːft. ðeɪ ˈdɪdnt bɪˈliːv miː/", vi: "Bạn có muốn thành nhà văn nổi tiếng không? Tôi thì có đấy. Tôi cực kỳ mê viết lách! Khi cô giáo hỏi ước mơ sau này, nhiều bạn bảo muốn làm bác sĩ hay cảnh sát. Riêng tôi tự tin nói: 'Em muốn làm nhà văn — một nhà văn lừng danh.' Cả lớp cười ồ lên không tin." },
      { "start": 26.0, "en": "But then, our teacher told us a story about a famous writer. His name was Rudyard Kipling. He wrote many great books. Even today, people all over the world love his stories.", "ipa": "/bʌt ðɛn, ˈaʊər ˈtiːtʃər toʊld ʌs ə ˈstɔːri əˈbaʊt ə ˈfeɪməs ˈraɪtər. hɪz neɪm wɒz ˈrʌdjɑːrd ˈkɪplɪŋ. hiː roʊt ˈmɛni ɡreɪt bʊks. ˈiːvn təˈdeɪ, ˈpiːpl ɔːl ˈoʊvər ðə wɜːrld lʌv hɪz ˈstɔːriz/", vi: "Thế rồi, cô giáo kể cho cả lớp nghe câu chuyện về đại văn hào Rudyard Kipling. Ông là tác giả của bao cuốn sách vĩ đại mà đến tận ngày nay độc giả khắp thế giới vẫn say mê." },
      { "start": 39.0, "en": "When Mr. Kipling was just a young man, he got a job at a newspaper. But his boss didn't like his stories. He sent him a letter saying, 'I'm sorry, Mr. Kipling. You don't know how to use the English language. This isn't a kindergarten for amateur writers.'", "ipa": "/wɛn ˈmɪstər ˈkɪplɪŋ wɒz dʒʌst ə jʌŋ mæn, hiː ɡɒt ə dʒɒb æt ə ˈnjuːzˌpeɪpər. bʌt hɪz bɒs ˈdɪdnt laɪk hɪz ˈstɔːriz. hiː sɛnt hɪm ə ˈlɛtər ˈseɪɪŋ, aɪm ˈsɒri, ˈmɪstər ˈkɪplɪŋ. juː doʊnt noʊ haʊ tuː juːz ði ˈɪŋɡlɪʃ ˈlæŋɡwɪdʒ. ðɪs ˈɪznt ə ˈkɪndərˌɡɑːrtn fɔːr ˈæmətər ˈraɪtərz/", vi: "Thời trẻ, Kipling xin vào làm việc cho một tòa soạn báo. Nhưng sếp của ông lại chê bai bài viết của ông thậm tệ: 'Thứ lỗi nhé Kipling. Cậu chẳng biết dùng tiếng Anh gì cả. Đây không phải nhà trẻ dành cho mấy tay viết nghiệp dư đâu.'" },
      { "start": 57.0, "en": "But Mr. Kipling didn't stop writing. He went on to become the most popular writer of his generation. So, I am going to keep trying. It's always better to believe in yourself and follow your dreams.", "ipa": "/bʌt ˈmɪstər ˈkɪplɪŋ ˈdɪdnt stɒp ˈraɪtɪŋ. hiː wɛnt ɒn tuː bɪˈkʌm ðə moʊst ˈpɒpjələr ˈraɪtər əv hɪz ˌdʒɛnəˈreɪʃn. soʊ, aɪ æm ˈɡoʊɪŋ tuː kiːp ˈtraɪɪŋ. ɪts ˈɔːlweɪz ˈbɛtər tuː bɪˈliːv ɪn jɔːrˈsɛlf ænd ˈfɒloʊ jɔːr driːmz/", vi: "Nhưng Kipling không hề từ bỏ. Ông tiếp tục kiên trì cầm bút và trở thành nhà văn lừng lẫy nhất thời đại của mình. Vì thế, tôi cũng sẽ không ngừng nỗ lực. Hãy luôn tin vào chính mình và theo đuổi ước mơ đến cùng." }
    ]
  },
  {
    "day": 12,
    "title": "In the Swimming Pool",
    "image": "05 May/images/day_12.webp",
    "audio": "05 May/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Tommy and his brother Alex went swimming. As they got close to the swimming pool, they saw something strange—a man was jogging in the water.", "ipa": "/wʌn deɪ, ˈtɒmi ænd hɪz ˈbrʌðər ˈælɪks wɛnt ˈswɪmɪŋ. æz ðeɪ ɡɒt kloʊs tuː ðə ˈswɪmɪŋ puːl, ðeɪ sɔː ˈsʌmθɪŋ streɪndʒ—ə mæn wɒz ˈdʒɒɡɪŋ ɪn ðə ˈwɔːtər/", vi: "Một hôm, Tommy và anh trai Alex đi bơi. Khi đến gần bể bơi, hai anh em bắt gặp một cảnh tượng kỳ lạ: Một bác lớn tuổi đang chạy bộ dưới nước." },
      { "start": 17.0, "en": "The two brothers were very curious. Tommy asked the man, 'Why are you jogging in the water, not on land?' The old man smiled and said, 'Well, that is simple. Running in water uses the same muscles as running on land. But it is much easier on my knee joints.'", "ipa": "/ðə tuː ˈbrʌðərz wɜːr ˈvɛri ˈkjʊəriəs. ˈtɒmi ɑːskt ðə mæn, waɪ ɑːr juː ˈdʒɒɡɪŋ ɪn ðə ˈwɔːtər, nɒt ɒn lænd? ði oʊld mæn smaɪld ænd sɛd, wɛl, ðæt ɪz ˈsɪmpl. ˈrʌnɪŋ ɪn ˈwɔːtər ˈjuːzɪz ðə seɪm ˈmʌslz æz ˈrʌnɪŋ ɒn lænd. bʌt ɪt ɪz mʌtʃ ˈiːziər ɒn maɪ niː dʒɔɪnts/", vi: "Cả hai tò mò hỏi bác: 'Sao bác lại chạy bộ dưới nước mà không chạy trên cạn ạ?' Bác mỉm cười giải thích: 'Đơn giản thôi cháu. Chạy dưới nước vận động các nhóm cơ y hệt như trên cạn, nhưng lại giảm bớt áp lực rất nhiều lên khớp gối của bác.'" },
      { "start": 38.0, "en": "'Why do you prefer jogging to swimming?' asked Tommy. 'Jogging is slower than swimming, but it is more tiring. It is also more difficult to keep your balance while jogging in water. And it's just as good for the heart, lungs and muscles.'", "ipa": "/waɪ duː juː prɪˈfɜːr ˈdʒɒɡɪŋ tuː ˈswɪmɪŋ?, ɑːskt ˈtɒmi. ˈdʒɒɡɪŋ ɪz ˈsloʊər ðæn ˈswɪmɪŋ, bʌt ɪt ɪz mɔːr ˈtaɪərɪŋ. ɪt ɪz ˈɔːlsoʊ mɔːr ˈdɪfɪkəlt tuː kiːp jɔːr ˈbæləns waɪl ˈdʒɒɡɪŋ ɪn ˈwɔːtər. ænd ɪts dʒʌst æz ɡʊd fɔːr ðə hɑːrt, lʌŋz ænd ˈmʌslz/", vi: "'Thế sao bác thích chạy hơn bơi lội ạ?' Tommy thắc mắc. 'Chạy chậm hơn bơi nhưng tốn sức hơn, giữ thăng bằng dưới nước cũng khó hơn. Nó cực kỳ tốt cho tim mạch, phổi và cơ bắp.'" },
      { "start": 57.0, "en": "The two kids happily jumped in the water. They learned that jogging in water is a fun way to get fit!", "ipa": "/ðə tuː kɪdz ˈhæpɪli dʒʌmpt ɪn ðə ˈwɔːtər. ðeɪ lɜːrnd ðæt ˈdʒɒɡɪŋ ɪn ˈwɔːtər ɪz ə fʌn weɪ tuː ɡɛt fɪt!/", vi: "Hai anh em thích thú nhảy ùm xuống nước. Chúng đã học được rằng chạy bộ dưới nước là một phương pháp rèn luyện sức khỏe cực kỳ thú vị!" }
    ]
  },
  {
    "day": 13,
    "title": "Deep Below",
    "image": "05 May/images/day_13.webp",
    "audio": "05 May/audio/Track13.mp3",
    "sentences": [
      { "start": 4.8, "en": "Do you like to swim? Have you ever been in a swimming pool? How deep was it? One metre? Two metres? Or maybe even five metres?", "ipa": "/duː juː laɪk tuː swɪm? hæv juː ˈɛvər biːn ɪn ə ˈswɪmɪŋ puːl? haʊ diːp wɒz ɪt? wʌn ˈmiːtər? tuː ˈmiːtərz? ɔːr ˈmeɪbi ˈiːvn faɪv ˈmiːtərz?/", vi: "Bạn có thích bơi không? Bể bơi sâu nhất bạn từng bơi là bao nhiêu? Một mét? Hai mét? Hay năm mét?" },
      { "start": 16.0, "en": "Well, let me tell you about a very special place where you could go swimming. But I wouldn't recommend it because the water is 11 kilometres deep!", "ipa": "/wɛl, lɛt miː tɛl juː əˈbaʊt ə ˈvɛri ˈspɛʃl pleɪs wɛər juː kʊd ɡoʊ ˈswɪmɪŋ. bʌt aɪ ˈwʊdnt ˌrɛkəˈmɛnd ɪt bɪˈkɒz ðə ˈwɔːtər ɪz ɪˈlɛvn kɪˈlɒmɪtərz diːp!/", vi: "Để tôi kể cho bạn nghe về một vùng nước đặc biệt. Nhưng tôi không khuyến khích bạn bơi ở đó đâu, vì nó sâu tới tận... 11 kilômét!" },
      { "start": 27.0, "en": "Located in the Pacific Ocean, right beside Japan, is something called the Mariana Trench. It is like a deep valley in the ocean. Deep down, it is very dark and cold. Scary, right?", "ipa": "/loʊˈkeɪtɪd ɪn ðə pəˈsɪfɪk ˈoʊʃn, raɪt bɪˈsaɪd dʒəˈpæn, ɪz ˈsʌmθɪŋ kɔːld ðə ˌmæriˈænə trɛntʃ. ɪt ɪz laɪk ə diːp ˈvæli ɪn ði ˈoʊʃn. diːp daʊn, ɪt ɪz ˈvɛri dɑːrk ænd koʊld. ˈskɛəri, raɪt?/", vi: "Nằm ở Thái Bình Dương ngay cạnh Nhật Bản là rãnh Mariana, sâu như một hẻm núi dưới đáy biển. Dưới đó tối tăm và lạnh lẽo vô cùng. Nghe rợn người đúng không?" },
      { "start": 44.0, "en": "When you are swimming, do you ever feel the pressure in your ears? This is caused by the weight of the water. Imagine how your ears would feel with 11 kilometres of water on top of you!", "ipa": "/wɛn juː ɑːr ˈswɪmɪŋ, duː juː ˈɛvər fiːl ðə ˈprɛʃər ɪn jɔːr ɪərz? ðɪs ɪz kɔːzd baɪ ðə weɪt əv ðə ˈwɔːtər. ɪˈmædʒɪn haʊ jɔːr ɪərz wʊd fiːl wɪð ɪˈlɛvn kɪˈlɒmɪtərz əv ˈwɔːtər ɒn tɒp əv juː!/", vi: "Khi lặn sâu bạn có thấy tai bị ù và ép lại không? Đó là do áp suất nước ép lên. Thử tưởng tượng tai bạn sẽ ra sao nếu có cả một cột nước dày 11 cây số đè lên người!" },
      { "start": 58.0, "en": "Underneath all of that water, there are still creatures living there. They must be really strange. Maybe, to some people, the Mariana Trench sounds like a fun place to go swimming. But not to me. I'd choose a nice, warm beach any day!", "ipa": "/ˌʌndərˈniːθ ɔːl əv ðæt ˈwɔːtər, ðɛər ɑːr stɪl ˈkriːtʃərz ˈlɪvɪŋ ðɛər. ðeɪ mʌst biː ˈrɪəli streɪndʒ. ˈmeɪbi, tuː sʌm ˈpiːpl, ðə ˌmæriˈænə trɛntʃ saʊndz laɪk ə fʌn pleɪs tuː ɡoʊ ˈswɪmɪŋ. bʌt nɒt tuː miː. aɪd tʃuːz ə naɪs, wɔːrm biːtʃ ˈɛni deɪ!/", vi: "Dưới đáy vực sâu ấy vẫn có những sinh vật kỳ lạ sinh sống. Có thể với vài người rãnh Mariana nghe có vẻ ly kỳ, nhưng với tôi thì không. Tôi thà chọn một bãi biển đầy nắng ấm áp để bơi lội còn hơn!" }
    ]
  },
  {
    "day": 14,
    "title": "The Elephant and the Fly",
    "image": "05 May/images/day_14.webp",
    "audio": "05 May/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "There was once an elephant living in a forest. When summer came, his skin became very itchy. To make things worse, the flies came to bother him. He used his long tail, ears and even his trunk to swat at them. But, there was a spot on his back that he could not reach.", "ipa": "/ðɛər wɒz wʌns ən ˈɛlɪfənt ˈlɪvɪŋ ɪn ə ˈfɒrɪst. wɛn ˈsʌmər keɪm, hɪz skɪn bɪˈkeɪm ˈvɛri ˈɪtʃi. tuː meɪk θɪŋz wɜːrs, ðə flaɪz keɪm tuː ˈbɒðər hɪm. hiː juːzd hɪz lɔːŋ teɪl, ɪərz ænd ˈiːvn hɪz trʌŋk tuː swɒt æt ðɛm. bʌt, ðɛər wɒz ə spɒt ɒn hɪz bæk ðæt hiː kʊd nɒt riːtʃ/", vi: "Có một chú voi sống trong rừng. Vào mùa hè, da chú ngứa ngáy khó chịu, lại thêm lũ ruồi cứ bay tới quấy rầy. Chú dùng đuôi, tai và vòi để xua đuổi, nhưng có một vị trí trên lưng chú không tài nào với tới được." },
      { "start": 26.0, "en": "One day, a fly was on the elephant again, licking the salt off him. It was a spot that the elephant could reach. Just as the elephant prepared to kill the fly with his tail, he had an idea.", "ipa": "/wʌn deɪ, ə flaɪ wɒz ɒn ði ˈɛlɪfənt əˈɡɛn, ˈlɪkɪŋ ðə sɔːlt ɔːf hɪm. ɪt wɒz ə spɒt ðæt ði ˈɛlɪfənt kʊd riːtʃ. dʒʌst æz ði ˈɛlɪfənt prɪˈpɛərd tuː kɪl ðə flaɪ wɪð hɪz teɪl, hiː hæd ən aɪˈdiːə/", vi: "Một hôm, một con ruồi lại đậu lên người chú voi để liếm muối mồ hôi, đúng vị trí đuôi chú voi có thể với tới. Vừa định quất đuôi đập chết con ruồi, chú voi bỗng nảy ra sáng kiến." },
      { "start": 42.0, "en": "He said, 'Fly, I could kill you with my tail right now. But if you scratch my back where I can't reach, I will let you sit on me and eat all the salt you want!'", "ipa": "/hiː sɛd, flaɪ, aɪ kʊd kɪl juː wɪð maɪ teɪl raɪt naʊ. bʌt ɪf juː skrætʃ maɪ bæk wɛər aɪ kænt riːtʃ, aɪ wɪl lɛt juː sɪt ɒn miː ænd iːt ɔːl ðə sɔːlt juː wɒnt!/", vi: "Chú voi nói: 'Này ruồi, ta có thể quất đuôi đập chết ngươi ngay lúc này. Nhưng nếu ngươi gãi ngứa chỗ lưng ta không với tới, ta sẽ cho ngươi thỏa thích đậu ở đây liếm muối!'" },
      { "start": 57.0, "en": "The fly buzzed, 'Sure!' It flew to the top of the elephant's back and started working. The elephant smiled when his itch was finally scratched. And he learned an important lesson. Sometimes, if we try, the worst of enemies can become the best of friends.", "ipa": "/ðə flaɪ bʌzd, ʃʊər! ɪt fluː tuː ðə tɒp əv ði ˈɛlɪfənts bæk ænd ˈstɑːrtɪd ˈwɜːrkɪŋ. ði ˈɛlɪfənt smaɪld wɛn hɪz ɪtʃ wɒz ˈfaɪnəli skrætʃt. ænd hiː lɜːrnd ən ɪmˈpɔːrtənt ˈlɛsn. ˈsʌmˌtaɪmz, ɪf wiː traɪ, ðə wɜːrst əv ˈɛnəmiz kæn bɪˈkʌm ðə bɛst əv frɛndz/", vi: "Con ruồi vo ve đồng ý ngay, bay lên chỗ ngứa trên lưng voi cặm cụi làm việc. Chú voi mỉm cười khoan khoái vì hết ngứa và rút ra bài học: Đôi khi kẻ thù truyền kiếp hoàn toàn có thể trở thành người bạn tuyệt vời nếu đôi bên cùng hợp tác." }
    ]
  },
  {
    "day": 15,
    "title": "Don't Mess with Mom",
    "image": "05 May/images/day_15.webp",
    "audio": "05 May/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "There's an old saying: a little person doing the right thing is more powerful than a giant. I learned the exact meaning of this the other day.", "ipa": "/ðɛərz ən oʊld ˈseɪɪŋ: ə ˈlɪtl ˈpɜːrsn ˈduːɪŋ ðə raɪt θɪŋ ɪz mɔːr ˈpaʊərfʊl ðæn ə ˈdʒaɪənt. aɪ lɜːrnd ði ɪɡˈzækt ˈmiːnɪŋ əv ðɪs ði ˈʌðər deɪ/", vi: "Có câu ngạn ngữ: Một người nhỏ bé làm điều đúng đắn còn mạnh mẽ hơn một kẻ khổng lồ. Gần đây tôi đã hiểu thấu ý nghĩa câu nói đó." },
      { "start": 16.0, "en": "On our street, there lives a very big man, Mr. Boos. His house and yard are a mess. One day, my mom and I were walking past his house. There were bottles on the ground everywhere. The grass had not been cut for weeks. And the garden was full of garbage.", "ipa": "/ɒn ˈaʊər striːt, ðɛər lɪvz ə ˈvɛri bɪɡ mæn, ˈmɪstər buːs. hɪz haʊs ænd jɑːrd ɑːr ə mɛs. wʌn deɪ, maɪ mɒm ænd aɪ wɜːr ˈwɔːkɪŋ pæst hɪz haʊs. ðɛər wɜːr ˈbɒtlz ɒn ðə ɡraʊnd ˈɛvriˌwɛər. ðə ɡræs hæd nɒt biːn kʌt fɔːr wiːks. ænd ðə ˈɡɑːrdn wɒz fʊl əv ˈɡɑːrbɪdʒ/", vi: "Trên phố nhà tôi có ông Boos, một người đàn ông to lớn lực lưỡng. Nhà và sân vườn của ông bừa bộn như bãi rác. Chai lọ vứt la liệt, cỏ dại mọc um tùm suốt mấy tuần không cắt." },
      { "start": 36.0, "en": "My mother, who is very small, said to the huge man, 'Mr. Boos, this yard is terrible. We're going to help you clean it up.'", "ipa": "/maɪ ˈmʌðər, huː ɪz ˈvɛri smɔːl, sɛd tuː ðə hjuːdʒ mæn, ˈmɪstər buːs, ðɪs jɑːrd ɪz ˈtɛrəbl. wɪər ˈɡoʊɪŋ tuː hɛlp juː kliːn ɪt ʌp/", vi: "Mẹ tôi vóc dáng nhỏ nhắn nhưng nghiêm nghị bảo người đàn ông to xác: 'Bác Boos, cái sân này trông tệ quá. Mẹ con tôi sẽ phụ bác dọn sạch nó ngay bây giờ.'" },
      { "start": 48.0, "en": "So all of us, including Mr. Boos, worked for about an hour. Then the strangest thing happened. His yard became clean and neat. On top of that, Mr. Boos didn't hate the cleaning anymore. Now, he has the most beautiful garden in our neighbourhood.", "ipa": "/soʊ ɔːl əv ʌs, ɪnˈkluːdɪŋ ˈmɪstər buːs, wɜːrkt fɔːr əˈbaʊt ən ˈaʊər. ðɛn ðə ˈstreɪndʒɪst θɪŋ ˈhæpənd. hɪz jɑːrd bɪˈkeɪm kliːn ænd niːt. ɒn tɒp əv ðæt, ˈmɪstər buːs ˈdɪdnt heɪt ðə ˈkliːnɪŋ ˈɛniˌmɔːr. naʊ, hiː hæz ðə moʊst ˈbjuːtɪfl ˈɡɑːrdn ɪn ˈaʊər ˈneɪbərˌhʊd/", vi: "Thế là cả ba người bắt tay vào dọn dẹp suốt một tiếng đồng hồ. Sân vườn trở nên ngăn nắp, sạch bóng. Kể từ hôm đó, ông Boos không còn lười dọn dẹp nữa mà luôn chăm sóc khu vườn đẹp nhất xóm." }
    ]
  },
  {
    "day": 16,
    "title": "My Favourite Animal",
    "image": "05 May/images/day_16.webp",
    "audio": "05 May/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "I like bears. They are strong and powerful. But I have never seen a bear in nature—at least not face to face.", "ipa": "/aɪ laɪk bɛərz. ðeɪ ɑːr strɒŋ ænd ˈpaʊərfʊl. bʌt aɪ hæv ˈnɛvər siːn ə bɛər ɪn ˈneɪtʃər—æt liːst nɒt feɪs tuː feɪs/", vi: "Tôi rất thích loài gấu vì chúng mạnh mẽ và dũng mãnh. Nhưng tôi chưa bao giờ gặp một chú gấu ngoài tự nhiên — ít nhất là chưa từng chạm trán mặt đối mặt." },
      { "start": 15.0, "en": "Last summer, I went camping in a park with my mom and dad. The man at the entrance warned us to be careful because there could be bears around. I thought he was joking.", "ipa": "/lɑːst ˈsʌmər, aɪ wɛnt ˈkæmpɪŋ ɪn ə pɑːrk wɪð maɪ mɒm ænd dæd. ðə mæn æt ði ˈɛntrəns wɔːrnd ʌs tuː biː ˈkɛrfʊl bɪˈkɒz ðɛər kʊd biː bɛərz əˈraʊnd. aɪ θɔːt hiː wɒz ˈdʒoʊkɪŋ/", vi: "Mùa hè năm ngoái, tôi đi cắm trại cùng bố mẹ trong công viên quốc gia. Nhân viên kiểm lâm cảnh báo phải cẩn thận vì có gấu quanh đây, lúc đó tôi cứ ngỡ bác ấy đùa." },
      { "start": 29.0, "en": "We had a nice time. We played, fished and had picnics. 'There are no bears here,' I thought.", "ipa": "/wiː hæd ə naɪs taɪm. wiː pleɪd, fɪʃt ænd hæd ˈpɪknɪks. ðɛər ɑːr noʊ bɛərz hɪər, aɪ θɔːt/", vi: "Chúng tôi chơi đùa, câu cá và dã ngoại rất vui vẻ. 'Làm gì có con gấu nào ở đây,' tôi thầm nghĩ." },
      { "start": 39.0, "en": "That night, as I slept in my tent, I heard a sound. I sat up to see what it was. There was a shadowy figure outside my tent. It was a bear! It was eating the food we had left outside.", "ipa": "/ðæt naɪt, æz aɪ slɛpt ɪn maɪ tɛnt, aɪ hɜːrd ə saʊnd. aɪ sæt ʌp tuː siː wɒt ɪt wɒz. ðɛər wɒz ə ˈʃædoʊi ˈfɪɡjər ˈaʊtˌsaɪd maɪ tɛnt. ɪt wɒz ə bɛər! ɪt wɒz ˈiːtɪŋ ðə fuːd wiː hæd lɛft ˈaʊtˌsaɪd/", vi: "Đêm hôm đó khi đang ngủ trong lều, tôi nghe tiếng động lạ bên ngoài. Tôi ngồi dậy nhìn thì thấy một bóng đen lù lù: Đó là một con gấu thật! Nó đang chén sạch số thức ăn chúng tôi để quên ngoài lều." },
      { "start": 56.0, "en": "I was terrified. I did not want to meet my favourite animal at all! The next morning, we packed up and went home.", "ipa": "/aɪ wɒz ˈtɛrɪfaɪd. aɪ dɪd nɒt wɒnt tuː miːt maɪ ˈfeɪvərɪt ˈænɪml æt ɔːl! ðə nɛkst ˈmɔːrnɪŋ, wiː pækt ʌp ænd wɛnt hoʊm/", vi: "Tôi sợ chết khiếp, chẳng còn tha thiết muốn gặp loài động vật yêu thích này ngoài đời nữa! Sáng hôm sau, cả nhà tức tốc dọn đồ đi về ngay lập tức." }
    ]
  },
  {
    "day": 17,
    "title": "Belly Button",
    "image": "05 May/images/day_17.webp",
    "audio": "05 May/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "Little Dan has a big question. On his stomach, there is a round, funny-looking bump. What is it? It is his belly button. But why does he have a belly button?", "ipa": "/ˈlɪtl dæn hæz ə bɪɡ ˈkwɛstʃən. ɒn hɪz ˈstʌmək, ðɛər ɪz ə raʊnd, ˈfʌni-ˈlʊkɪŋ bʌmp. wɒt ɪz ɪt? ɪt ɪz hɪz ˈbɛli ˈbʌtn. bʌt waɪ dʌz hiː hæv ə ˈbɛli ˈbʌtn?/", vi: "Cậu bé Dan có một thắc mắc lớn: Trên bụng cậu có một cái núm tròn tròn trông rất ngộ nghĩnh. Đó là cái gì? Đó là cái rốn. Nhưng tại sao ai cũng có rốn nhỉ?" },
      { "start": 17.0, "en": "Dan asks his father. His dad says, 'Everyone has a belly button.' Dan thinks this is very interesting. 'But why do we all have belly buttons?' he asks.", "ipa": "/dæn ɑːsks hɪz ˈfɑːðər. hɪz dæd sɛz, ˈɛvriˌwʌn hæz ə ˈbɛli ˈbʌtn. dæn θɪŋks ðɪs ɪz ˈvɛri ˈɪntrəstɪŋ. bʌt waɪ duː wiː ɔːl hæv ˈbɛli ˈbʌtnz?, hiː ɑːsks/", vi: "Dan hỏi bố. Bố bảo: 'Ai sinh ra cũng có rốn cả con ạ.' Dan thấy lạ lùng: 'Nhưng tại sao chúng ta lại có rốn hả bố?'" },
      { "start": 29.0, "en": "'Before you were born, you lived inside your mommy,' explains Dad. 'You needed food and air. But you could not get them on your own. So there was a cord on your belly that attached you to your mommy. Mom shared her food and air with you.'", "ipa": "/bɪˈfɔːr juː wɜːr bɔːrn, juː lɪvd ɪnˈsaɪd jɔːr ˈmɒmi, ɪkˈspleɪnz dæd. juː ˈniːdɪd fuːd ænd ɛər. bʌt juː kʊd nɒt ɡɛt ðɛm ɒn jɔːr oʊn. soʊ ðɛər wɒz ə kɔːrd ɒn jɔːr ˈbɛli ðæt əˈtætʃt juː tuː jɔːr ˈmɒmi. mɒm ʃɛərd hɜːr fuːd ænd ɛər wɪð juː/", vi: "Bố giải thích: 'Trước khi chào đời, con sống trong bụng mẹ. Con cần thức ăn và không khí nhưng chưa tự thở tự ăn được. Vì thế có một sợi dây rốn nối từ bụng con vào bụng mẹ để mẹ truyền dưỡng chất và oxy cho con.'" },
      { "start": 48.0, "en": "'This is VERY interesting,' thinks Dan. 'When you were born, the doctor cut this cord because you did not need it anymore,' says Dad. 'Your belly button is the place where this cord was attached to you.' Dan is happy. He has solved the mystery of the belly button.", "ipa": "/ðɪs ɪz ˈvɛri ˈɪntrəstɪŋ, θɪŋks dæn. wɛn juː wɜːr bɔːrn, ðə ˈdɒktər kʌt ðɪs kɔːrd bɪˈkɒz juː dɪd nɒt niːd ɪt ˌɛniˈmɔːr, sɛz dæd. jɔːr ˈbɛli ˈbʌtn ɪz ðə pleɪs wɛər ðɪs kɔːrd wɒz əˈtætʃt tuː juː. dæn ɪz ˈhæpi. hiː hæz sɒlvd ðə ˈmɪstəri əv ðə ˈbɛli ˈbʌtn/", vi: "'Nghe thú vị quá,' Dan thầm nghĩ. Bố nói tiếp: 'Khi con cất tiếng khóc chào đời, bác sĩ cắt sợi dây đó đi vì con đã tự thở tự ăn được rồi. Cái rốn chính là dấu vết nơi sợi dây gắn kết con với mẹ.' Dan vui sướng vì đã giải mã được bí ẩn về chiếc rốn của mình." }
    ]
  },
  {
    "day": 18,
    "title": "Irene's Blanket (I)",
    "image": "05 May/images/day_18.webp",
    "audio": "05 May/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "Before Irene was born, her mom and dad bought a soft, yellow blanket for her. To them, it was just a blanket to keep the baby warm.", "ipa": "/bɪˈfɔːr aɪˈriːn wɒz bɔːrn, hɜːr mɒm ænd dæd bɔːt ə sɒft, ˈjɛloʊ ˈblæŋkɪt fɔːr hɜːr. tuː ðɛm, ɪt wɒz dʒʌst ə ˈblæŋkɪt tuː kiːp ðə ˈbeɪbi wɔːrm/", vi: "Trước khi Irene chào đời, bố mẹ mua cho bé một chiếc chăn bông màu vàng mềm mại chỉ để ủ ấm cho em bé sơ sinh." },
      { "start": 16.0, "en": "The first day Irene came into this wonderful world, her mom wrapped her up in this special blanket. The little baby was very quiet, moving her tiny body from inside this big blanket.", "ipa": "/ðə fɜːrst deɪ aɪˈriːn keɪm ˈɪntuː ðɪs ˈwʌndərfʊl wɜːrld, hɜːr mɒm ræpt hɜːr ʌp ɪn ðɪs ˈspɛʃl ˈblæŋkɪt. ðə ˈlɪtl ˈbeɪbi wɒz ˈvɛri ˈkwaɪət, ˈmuːvɪŋ hɜːr ˈtaɪni ˈbɒdi frɒm ɪnˈsaɪd ðɪs bɪɡ ˈblæŋkɪt/", vi: "Ngày đầu tiên đến với thế giới, mẹ đã bọc bé trong chiếc chăn ấm áp này. Cô bé nằm ngoan ngoãn ngọ nguậy thân hình bé bỏng bên trong chiếc chăn rộng." },
      { "start": 30.0, "en": "Four months later, while Irene was sleeping, her mom washed her blanket for the first time. But when Irene woke up, she started crying. Irene's mom tried everything to calm her, but nothing worked.", "ipa": "/fɔːr mʌnθs ˈleɪtər, waɪl aɪˈriːn wɒz ˈsliːpɪŋ, hɜːr mɒm wɒʃt hɜːr ˈblæŋkɪt fɔːr ðə fɜːrst taɪm. bʌt wɛn aɪˈriːn woʊk ʌp, ʃiː ˈstɑːrtɪd ˈkraɪɪŋ. aɪˈriːnz mɒm traɪd ˈɛvriˌθɪŋ tuː kɑːm hɜːr, bʌt ˈnʌθɪŋ wɜːrkt/", vi: "Bốn tháng sau, nhân lúc con ngủ, mẹ đem chiếc chăn đi giặt lần đầu tiên. Khi tỉnh dậy, Irene khóc thét lên. Mẹ dỗ dành đủ cách nhưng bé vẫn không chịu nín." },
      { "start": 48.0, "en": "She checked her carefully to make sure that her little girl wasn't sick. She even checked her temperature. Nothing was wrong. So the mother held Irene in her arms and walked around the room.", "ipa": "/ʃiː tʃɛkt hɜːr ˈkɛərfʊli tuː meɪk ʃʊər ðæt hɜːr ˈlɪtl ɡɜːrl ˈwɒznt sɪk. ʃiː ˈiːvn tʃɛkt hɜːr ˈtɛmprətʃər. ˈnʌθɪŋ wɒz rɒŋ. soʊ ðə ˈmʌðər hɛld aɪˈriːn ɪn hɜːr ɑːrmz ænd wɔːkt əˈraʊnd ðə ruːm/", vi: "Mẹ kiểm tra kỹ càng, đo cả nhiệt độ xem con có bị sốt không nhưng bé hoàn toàn khỏe mạnh. Mẹ đành bế Irene đi qua đi lại quanh phòng." },
      { "start": 62.0, "en": "When she came to the window, Irene suddenly stopped crying. She saw the blanket hanging on the balcony and her face lit up with a smile! Now, her mom knew why she was crying.", "ipa": "/wɛn ʃiː keɪm tuː ðə ˈwɪndoʊ, aɪˈriːn ˈsʌdənli stɒpt ˈkraɪɪŋ. ʃiː sɔː ðə ˈblæŋkɪt ˈhæŋɪŋ ɒn ðə ˈbælkəni ænd hɜːr feɪs lɪt ʌp wɪð ə smaɪl! naʊ, hɜːr mɒm nuː waɪ ʃiː wɒz ˈkraɪɪŋ/", vi: "Khi bế con ra gần cửa sổ, Irene bỗng nín bặt. Nhìn thấy chiếc chăn vàng đang phơi ngoài ban công, mặt bé rạng rỡ nở nụ cười tươi rói! Giờ thì mẹ đã hiểu vì sao con gái khóc rồi." }
    ]
  },
  {
    "day": 19,
    "title": "Irene's Blanket (II)",
    "image": "05 May/images/day_19.webp",
    "audio": "05 May/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "A couple of years later, Irene became a toddler. But her love for the blanket hadn't changed. One day, her mom said, 'Irene, I have to wash your blanket! It's dirty and smelly.' 'No! No! No! I need it all the time! Never wash my blanket!' Irene said loudly.", "ipa": "/ə ˈkʌpl əv jɪərz ˈleɪtər, aɪˈriːn bɪˈkeɪm ə ˈtɒdlər. bʌt hɜːr lʌv fɔːr ðə ˈblæŋkɪt ˈhædnt tʃeɪndʒd. wʌn deɪ, hɜːr mɒm sɛd, aɪˈriːn, aɪ hæv tuː wɒʃ jɔːr ˈblæŋkɪt! ɪts ˈdɜːrti ænd ˈsmɛli. noʊ! noʊ! noʊ! aɪ niːd ɪt ɔːl ðə taɪm! ˈnɛvər wɒʃ maɪ ˈblæŋkɪt!, aɪˈriːn sɛd ˈlaʊdli/", vi: "Vài năm sau Irene đã biết đi chập chững, nhưng tình yêu với chiếc chăn vẫn nguyên vẹn. Mẹ bảo: 'Irene, mẹ phải giặt chăn thôi, nó bẩn và bốc mùi rồi!' Bé hét to: 'Không được giặt chăn của con! Lúc nào con cũng cần nó!'" },
      { "start": 24.0, "en": "'But it's too dirty. It will make you sick!' 'I don't think so. I will get sick WITHOUT it!' Irene insisted.", "ipa": "/bʌt ɪts tuː ˈdɜːrti. ɪt wɪl meɪk juː sɪk! aɪ doʊnt θɪŋk soʊ. aɪ wɪl ɡɛt sɪk wɪˈðaʊt ɪt!, aɪˈriːn ɪnˈsɪstɪd/", vi: "'Nhưng nó bẩn quá sẽ làm con ốm đấy!' 'Không đâu, KHÔNG CÓ NÓ con mới bị ốm ấy!' Irene khăng khăng cãi lại." },
      { "start": 33.0, "en": "The next day at the park, Irene had her blanket with her as usual. One of the kids came close to Irene, then ran back to his mom and cried, 'Mom! That girl's blanket is so smelly! Please take me home!' Irene stared at him and said, 'You're wrong! My blanket smells SO good!'", "ipa": "/ðə nɛkst deɪ æt ðə pɑːrk, aɪˈriːn hæd hɜːr ˈblæŋkɪt wɪð hɜːr æz ˈjuːʒuəl. wʌn əv ðə kɪdz keɪm kloʊs tuː aɪˈriːn, ðɛn ræn bæk tuː hɪz mɒm ænd kraɪd, mɒm! ðæt ɡɜːrlz ˈblæŋkɪt ɪz soʊ ˈsmɛli! pliːz teɪk miː hoʊm! aɪˈriːn stɛərd æt hɪm ænd sɛd, jʊər rɒŋ! maɪ ˈblæŋkɪt smɛlz soʊ ɡʊd!/", vi: "Hôm sau ra công viên chơi, Irene vẫn ôm khư khư chiếc chăn. Một bạn nhỏ đến gần ngửi thấy mùi liền chạy về mé máo với mẹ: 'Mẹ ơi cái chăn của bạn kia hôi quá, cho con về nhà đi!' Irene lườm bạn: 'Cậu sai rồi, chăn của tớ thơm phức thế này cơ mà!'" },
      { "start": 52.0, "en": "At that moment, another kid cried, 'It smells awful! I don't want to play with you!' Irene's mom said, 'Irene, did you hear what they said? Let's go home and wash your blanket right away.' Irene was still upset. But she seemed to understand a little.", "ipa": "/æt ðæt ˈmoʊmənt, əˈnʌðər kɪd kraɪd, ɪt smɛlz ˈɔːfʊl! aɪ doʊnt wɒnt tuː pleɪ wɪð juː! aɪˈriːnz mɒm sɛd, aɪˈriːn, dɪd juː hɪər wɒt ðeɪ sɛd? lɛts ɡoʊ hoʊm ænd wɒʃ jɔːr ˈblæŋkɪt raɪt əˈweɪ. aɪˈriːn wɒz stɪl ʌpˈsɛt. bʌt ʃiː siːmd tuː ˌʌndərˈstænd ə ˈlɪtl/", vi: "Đúng lúc đó, một bạn khác lại la lên: 'Mùi ghê quá, tớ không thèm chơi với cậu đâu!' Mẹ Irene liền bảo: 'Con nghe thấy các bạn nói chưa? Về nhà mẹ giặt chăn ngay nhé.' Irene tuy hậm hực nhưng bắt đầu hiểu ra vấn đề." },
      { "start": 68.0, "en": "'Can you wash it quickly?' she asked. 'Sure!' Mom promised her gladly. From then on, Irene allowed her mom to wash her blanket once in a while, but not too often.", "ipa": "/kæn juː wɒʃ ɪt ˈkwɪkli?, ʃiː ɑːskt. ʃʊər!, mɒm ˈprɒmɪst hɜːr ˈɡlædli. frɒm ðɛn ɒn, aɪˈriːn əˈlaʊd hɜːr mɒm tuː wɒʃ hɜːr ˈblæŋkɪt wʌns ɪn ə waɪl, bʌt nɒt tuː ˈɒfn/", vi: "'Mẹ giặt nhanh thật nhanh nhé?' bé hỏi. 'Được chứ!' mẹ vui vẻ hứa. Từ đó trở đi, Irene đã chịu cho mẹ giặt chăn thỉnh thoảng một lần, nhưng không được quá thường xuyên." }
    ]
  },
  {
    "day": 20,
    "title": "Fishing Trip",
    "image": "05 May/images/day_20.webp",
    "audio": "05 May/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "One warm Saturday morning, Grandpa decided to take his granddaughter Mary fishing. But she didn't have a fishing rod. 'We'll make one when we get to the pond,' said Grandpa. And off they went.", "ipa": "/wʌn wɔːrm ˈsætərdeɪ ˈmɔːrnɪŋ, ˈɡrændpɑː dɪˈsaɪdɪd tuː teɪk hɪz ˈɡrændˌdɔːtər ˈmɛəri ˈfɪʃɪŋ. bʌt ʃiː ˈdɪdnt hæv ə ˈfɪʃɪŋ rɒd. wiːl meɪk wʌn wɛn wiː ɡɛt tuː ðə pɒnd, sɛd ˈɡrændpɑː. ænd ɔːf ðeɪ wɛnt/", vi: "Một sáng thứ Bảy ấm áp, ông dắt cháu gái Mary đi câu cá. Nhưng cô bé lại không có cần câu. 'Ra đến bờ ao hai ông cháu mình sẽ tự làm cần nhé,' ông bảo. Thế là hai ông cháu lên đường." },
      { "start": 18.0, "en": "Grandpa carried his pole while Mary carried the worms. When they got to the pond, Grandpa cut a branch from a tree. He tied a string to it and put on a hook. Then, Mary put on a worm. 'Now you can fish,' Grandpa said.", "ipa": "/ˈɡrændpɑː ˈkærid hɪz poʊl waɪl ˈmɛəri ˈkærid ðə wɜːrmz. wɛn ðeɪ ɡɒt tuː ðə pɒnd, ˈɡrændpɑː kʌt ə brɑːntʃ frɒm ə triː. hiː taɪd ə strɪŋ tuː ɪt ænd pʊt ɒn ə hʊk. ðɛn, ˈmɛəri pʊt ɒn ə wɜːrm. naʊ juː kæn fɪʃ, ˈɡrændpɑː sɛd/", vi: "Ông xách cần câu còn Mary lon ton cầm hộp giun. Đến bờ ao, ông bẻ một cành cây, buộc dây cước và gắn lưỡi câu vào, rồi Mary móc mồi giun. 'Bây giờ cháu có thể câu cá được rồi,' ông mỉm cười." },
      { "start": 36.0, "en": "Soon, Mary had caught three fish using her new fishing rod. 'These fish aren't good for eating,' said Grandpa. 'They can be my pets,' said Mary. 'They don't like living in bowls,' explained Grandpa. 'They will die very quickly.'", "ipa": "/suːn, ˈmɛəri hæd kɔːt θriː fɪʃ ˈjuːzɪŋ hɜːr njuː ˈfɪʃɪŋ rɒd. ðiːz fɪʃ ɑːrnt ɡʊd fɔːr ˈiːtɪŋ, sɛd ˈɡrændpɑː. ðeɪ kæn biː maɪ pɛts, sɛd ˈmɛəri. ðeɪ doʊnt laɪk ˈlɪvɪŋ ɪn boʊlz, ɪkˈspleɪnd ˈɡrændpɑː. ðeɪ wɪl daɪ ˈvɛri ˈkwɪkli/", vi: "Chẳng mấy chốc, chiếc cần câu tự chế đã giúp Mary câu được ba con cá nhỏ. 'Cá này không ăn được đâu cháu,' ông bảo. 'Thế cháu nuôi làm thú cưng nhé?' 'Chúng không sống nổi trong chậu đâu con, sẽ chết nhanh lắm đấy,' ông giải thích." },
      { "start": 54.0, "en": "'I don't want them to die,' said Mary. 'I guess I'll let them go.' Grandpa smiled. When it was time to go home, Mary dumped the fish back into the pond. Mary smiled as she watched the fish swim away.", "ipa": "/aɪ doʊnt wɒnt ðɛm tuː daɪ, sɛd ˈmɛəri. aɪ ɡɛs aɪl lɛt ðɛm ɡoʊ. ˈɡrændpɑː smaɪld. wɛn ɪt wɒz taɪm tuː ɡoʊ hoʊm, ˈmɛəri dʌmpt ðə fɪʃ bæk ˈɪntuː ðə pɒnd. ˈmɛəri smaɪld æz ʃiː wɒtʃt ðə fɪʃ swɪm əˈweɪ/", vi: "'Cháu không muốn chúng chết đâu, cháu thả chúng về với ao vậy.' Ông mỉm cười xoa đầu bé. Đến giờ về, Mary nghiêng xô thả cá về lại làn nước trong xanh và tươi cười ngắm đàn cá tung tăng bơi đi." }
    ]
  },
  {
    "day": 21,
    "title": "Breakfast",
    "image": "05 May/images/day_21.webp",
    "audio": "05 May/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mom was on her way to the kitchen. Just then, she heard Sarah say, 'Let's surprise Mom today.' So, Mom hurried back to bed. She didn't want to spoil the children's surprise.", "ipa": "/mɒm wɒz ɒn hɜːr weɪ tuː ðə ˈkɪtʃɪn. dʒʌst ðɛn, ʃiː hɜːrd ˈsɛərə seɪ, lɛts sərˈpraɪz mɒm təˈdeɪ. soʊ, mɒm ˈhʌrid bæk tuː bɛd. ʃiː ˈdɪdnt wɒnt tuː spɔɪl ðə ˈtʃɪldrənz sərˈpraɪz/", vi: "Mẹ đang đi xuống bếp thì tình cờ nghe Sarah bàn bạc: 'Hôm nay chúng mình làm mẹ bất ngờ nhé.' Thế là mẹ rón rén quay lại giường nằm để không làm hỏng sự bất ngờ của các con." },
      { "start": 17.0, "en": "In the kitchen, Sarah made toast with lots of jelly on top. Mark cooked some eggs and put them in the prettiest dish he could find. Bill poured a big glass of orange juice. Then, they put everything on a tray. Away they marched to Mom's room.", "ipa": "/ɪn ðə ˈkɪtʃɪn, ˈsɛərə meɪd toʊst wɪð lɒts əv ˈdʒɛli ɒn tɒp. mɑːrk kʊkt sʌm ɛɡz ænd pʊt ðɛm ɪn ðə ˈprɪtiɪst dɪʃ hiː kʊd faɪnd. bɪl pɔːrd ə bɪɡ ɡlɑːs əv ˈɒrɪndʒ dʒuːs. ðɛn, ðeɪ pʊt ˈɛvriˌθɪŋ ɒn ə treɪ. əˈweɪ ðeɪ mɑːrtʃt tuː mɒmz ruːm/", vi: "Dưới bếp, Sarah phết mứt lên bánh mì nướng. Mark chiên trứng rồi bày vào chiếc đĩa đẹp nhất tìm được. Bill rót một ly nước cam đầy ắp. Xếp tất cả lên khay, ba đứa diễu hành tiến về phòng mẹ." },
      { "start": 38.0, "en": "Sarah, the oldest of them, carried the tray. Mark played his tin horn and Bill played his drum. 'Is this breakfast parade just for me?' asked Mom, very surprised and happy.", "ipa": "/ˈsɛərə, ði ˈoʊldɪst əv ðɛm, ˈkærid ðə treɪ. mɑːrk pleɪd hɪz tɪn hɔːrn ænd bɪl pleɪd hɪz drʌm. ɪz ðɪs ˈbrɛkfəst pəˈreɪd dʒʌst fɔːr miː?, ɑːskt mɒm, ˈvɛri sərˈpraɪzd ænd ˈhæpi/", vi: "Chị cả Sarah bưng khay, Mark thổi kèn thiếc còn Bill gõ trống rộn rã. 'Đoàn diễu hành bữa sáng này là dành riêng cho mẹ đấy ư?' mẹ vừa ngạc nhiên vừa xúc động nghẹn ngào." },
      { "start": 52.0, "en": "'Yes!' Sarah, Mark and Bill were happy too because they had finally made their mom breakfast in bed.", "ipa": "/jɛs! ˈsɛərə, mɑːrk ænd bɪl wɜːr ˈhæpi tuː bɪˈkɒz ðeɪ hæd ˈfaɪnəli meɪd ðɛər mɒm ˈbrɛkfəst ɪn bɛd/", vi: "'Dạ đúng rồi ạ!' Sarah, Mark và Bill hớn hở reo lên vì cuối cùng đã tự tay chuẩn bị được bữa sáng tận giường cho mẹ yêu." }
    ]
  },
  {
    "day": 22,
    "title": "New School Friend",
    "image": "05 May/images/day_22.webp",
    "audio": "05 May/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "John is excited and scared. He is starting at a new school today. He doesn't know anyone at the school. No one talks to him that day. And he sits all by himself at lunchtime. No one wants to be his friend.", "ipa": "/dʒɒn ɪz ɪkˈsaɪtɪd ænd skɛərd. hiː ɪz ˈstɑːrtɪŋ æt ə njuː skuːl təˈdeɪ. hiː ˈdʌznt noʊ ˈɛniˌwʌn æt ðə skuːl. noʊ wʌn tɔːks tuː hɪm ðæt deɪ. ænd hiː sɪts ɔːl baɪ hɪmˈsɛlf æt ˈlʌntʃˌtaɪm. noʊ wʌn wɒnts tuː biː hɪz frɛnd/", vi: "John vừa háo hức vừa lo lắng khi chuyển sang ngôi trường mới hôm nay. Cậu chẳng quen biết ai, cả ngày chẳng ai bắt chuyện và giờ ăn trưa cậu phải ngồi lủi thủi một mình." },
      { "start": 21.0, "en": "That night, John's father has a surprise for him. It is a puppy! John is very happy. Now he has a new friend. The puppy sleeps in a bed next to John.", "ipa": "/ðæt naɪt, ˈdʒɒnz ˈfɑːðər hæz ə sərˈpraɪz fɔːr hɪm. ɪt ɪz ə ˈpʌpi! dʒɒn ɪz ˈvɛri ˈhæpi. naʊ hiː hæz ə njuː frɛnd. ðə ˈpʌpi sliːps ɪn ə bɛd nɛkst tuː dʒɒn/", vi: "Tối hôm đó, bố dành cho John một bất ngờ: Một chú cún con xinh xắn! John vui sướng khôn xiết vì từ nay đã có bạn thân mới nằm ngủ cạnh giường mình." },
      { "start": 35.0, "en": "The next day at school John tells his class about his new puppy. He shows everyone a picture of the puppy. One boy puts up his hand and asks, 'Can I come to your house after school and see your puppy?'", "ipa": "/ðə nɛkst deɪ æt skuːl dʒɒn tɛlz hɪz klɑːs əˈbaʊt hɪz njuː ˈpʌpi. hiː ʃoʊz ˈɛvriˌwʌn ə ˈpɪktʃər əv ðə ˈpʌpi. wʌn bɔɪ pʊts ʌp hɪz hænd ænd ɑːsks, kæn aɪ kʌm tuː jɔːr haʊs ˈɑːftər skuːl ænd siː jɔːr ˈpʌpi?/", vi: "Hôm sau ở lớp, John kể cho các bạn nghe về chú cún cưng và khoe ảnh nó. Một cậu bạn giơ tay xin phép: 'Tan học tớ sang nhà cậu ngắm cún con được không?'" },
      { "start": 51.0, "en": "John says, 'Yes, you can come and meet my friend.' After school, the two boys go to John's house and play with the puppy. John is happy. Now he has two new friends!", "ipa": "/dʒɒn sɛz, jɛs, juː kæn kʌm ænd miːt maɪ frɛnd. ˈɑːftər skuːl, ðə tuː bɔɪz ɡoʊ tuː ˈdʒɒnz haʊs ænd pleɪ wɪð ðə ˈpʌpi. dʒɒn ɪz ˈhæpi. naʊ hiː hæz tuː njuː frɛndz!/", vi: "John tươi cười: 'Được chứ, sang chơi với bạn tớ đi!' Sau giờ học, hai đứa rủ nhau về nhà John chơi với chú cún. Giờ đây John đã có thêm hai người bạn mới rồi!" }
    ]
  },
  {
    "day": 23,
    "title": "Too Much Talking",
    "image": "05 May/images/day_23.webp",
    "audio": "05 May/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "Once there was a boy who could not stop talking. All day long, he talked and talked. He had no friends. Why? Because he always talked and never listened. Yak, yak, yak... words came from the boy's mouth all day long.", "ipa": "/wʌns ðɛər wɒz ə bɔɪ huː kʊd nɒt stɒp ˈtɔːkɪŋ. ɔːl deɪ lɔːŋ, hiː tɔːkt ænd tɔːkt. hiː hæd noʊ frɛndz. waɪ? bɪˈkɒz hiː ˈɔːlweɪz tɔːkt ænd ˈnɛvər ˈlɪsnd. jæk, jæk, jæk... wɜːrdz keɪm frɒm ðə bɔɪz maʊθ ɔːl deɪ lɔːŋ/", vi: "Thuở xưa có một cậu bé nói không ngừng nghỉ, huyên thuyên suốt ngày đêm. Cậu chẳng có lấy một người bạn vì chỉ thích nói mà chẳng bao giờ chịu lắng nghe ai." },
      { "start": 21.0, "en": "The boy asked his father, 'Why don't I have any friends?' He wanted so much to have friends. His father said, 'Listen, my son. Do you hear the frogs in the pond? They never stop croaking. They croak all day. They croak all night. But does anyone really hear them?'", "ipa": "/ðə bɔɪ ɑːskt hɪz ˈfɑːðər, waɪ doʊnt aɪ hæv ˈɛni frɛndz? hiː ˈwɒntɪd soʊ mʌtʃ tuː hæv frɛndz. hɪz ˈfɑːðər sɛd, ˈlɪsn, maɪ sʌn. duː juː hɪər ðə frɒɡz ɪn ðə pɒnd? ðeɪ ˈnɛvər stɒp ˈkroʊkɪŋ. ðeɪ kroʊk ɔːl deɪ. ðeɪ kroʊk ɔːl naɪt. bʌt dʌz ˈɛniˌwʌn ˈrɪəli hɪər ðɛm?/", vi: "Cậu bé buồn bã hỏi bố: 'Sao con không có bạn nào thế bố?' Người bố bảo: 'Con hãy lắng nghe xem, con có nghe thấy bầy ếch dưới ao không? Chúng ộp oạp cả ngày lẫn đêm không ngớt, nhưng liệu có ai bận tâm lắng nghe chúng không?'" },
      { "start": 41.0, "en": "The boy agreed that nobody listened to the frogs when they croaked. 'Early tomorrow morning, the rooster will crow,' said the father. 'He crows only at this time. But everyone listens to him. He wakes us all up from our sleep.'", "ipa": "/ðə bɔɪ əˈɡriːd ðæt ˈnoʊbədi ˈlɪsnd tuː ðə frɒɡz wɛn ðeɪ kroʊkt. ˈɜːrli təˈmɒroʊ ˈmɔːrnɪŋ, ðə ˈruːstər wɪl kroʊ, sɛd ðə ˈfɑːðər. hiː kroʊz ˈoʊnli æt ðɪs taɪm. bʌt ˈɛvriˌwʌn ˈlɪsnz tuː hɪm. hiː weɪks ʌs ɔːl ʌp frɒm ˈaʊər sliːp/", vi: "Cậu bé công nhận chẳng ai buồn nghe tiếng ếch kêu. Bố tiếp lời: 'Sáng sớm mai chú gà trống sẽ cất tiếng gáy. Chú chỉ gáy vào khoảnh khắc ấy thôi, nhưng ai nấy đều lắng nghe để thức giấc bắt đầu ngày mới.'" },
      { "start": 57.0, "en": "The boy understood. From then on, he would be like the rooster—a boy of few words.", "ipa": "/ðə bɔɪ ˌʌndərˈstʊd. frɒm ðɛn ɒn, hiː wʊd biː laɪk ðə ˈruːstər—ə bɔɪ əv fjuː wɜːrdz/", vi: "Cậu bé đã hiểu ra lời cha dạy. Từ đó về sau, cậu học tập chú gà trống — nói ít, nói đúng lúc và biết lắng nghe nhiều hơn." }
    ]
  },
  {
    "day": 24,
    "title": "A Dinosaur in Your Lunchbox!",
    "image": "05 May/images/day_24.webp",
    "audio": "05 May/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "Our teacher told us about a dinosaur called the T-Rex. It was 12 metres long and 6 metres tall. It weighed 7 tons and had teeth that were 30 centimetres long!", "ipa": "/ˈaʊər ˈtiːtʃər toʊld ʌs əˈbaʊt ə ˈdaɪnəsɔːr kɔːld ðə tiː-rɛks. ɪt wɒz twɛlv ˈmiːtərz lɒŋ ænd sɪks ˈmiːtərz tɔːl. ɪt weɪd ˈsɛvn tʌnz ænd hæd tiːθ ðæt wɜːr ˈθɜːrti ˈsɛntɪˌmiːtərz lɒŋ!/", vi: "Cô giáo kể cho chúng tôi nghe về khủng long T-Rex. Nó dài tới 12 mét, cao 6 mét, nặng 7 tấn và sở hữu hàm răng dài đến 30 centimet!" },
      { "start": 18.0, "en": "Its full name was actually Tyrannosaurus Rex. You say it like this: Tai-Ran-O-Sore-Us-Wrecks. It means: king of the lizards.", "ipa": "/ɪts fʊl neɪm wɒz ˈæktʃuəli taɪˌrænəˈsɔːrəs rɛks. juː seɪ ɪt laɪk ðɪs: taɪ-ræn-oʊ-sɔːr-əs-rɛks. ɪt miːnz: kɪŋ əv ðə ˈlɪzərdz/", vi: "Tên đầy đủ của nó là Tyrannosaurus Rex, phát âm là Tai-Ran-O-Sore-Us-Wrecks, có nghĩa là: Vua của các loài thằn lằn." },
      { "start": 30.0, "en": "It was the biggest meat eater ever to live on earth. There were bigger dinosaurs, but they ate only trees, leaves and grass.", "ipa": "/ɪt wɒz ðə ˈbɪɡɪst miːt ˈiːtər ˈɛvər tuː lɪv ɒn ɜːrθ. ðɛər wɜːr ˈbɪɡər ˈdaɪnəsɔːrz, bʌt ðeɪ eɪt ˈoʊnli triːz, liːvz ænd ɡræs/", vi: "Đây là loài khủng long ăn thịt hung dữ nhất từng ngự trị trên mặt đất. Có những loài khủng long to lớn hơn, nhưng chúng chỉ ăn cỏ lá cây thuần túy." },
      { "start": 41.0, "en": "'Believe it or not,' our teacher said. 'One creature that still exists today is related to T-Rex. Can you guess what it is?' Some kids guessed the lion, the bear or even the crocodile.", "ipa": "/bɪˈliːv ɪt ɔːr nɒt, ˈaʊər ˈtiːtʃər sɛd. wʌn ˈkriːtʃər ðæt stɪl ɪɡˈzɪsts təˈdeɪ ɪz rɪˈleɪtɪd tuː tiː-rɛks. kæn juː ɡɛs wɒt ɪt ɪz? sʌm kɪdz ɡɛst ðə ˈlaɪən, ðə bɛər ɔːr ˈiːvn ðə ˈkrɒkədaɪl/", vi: "'Tin hay không tùy các em,' cô giáo mỉm cười đố. 'Có một loài vật vẫn đang sống ngày nay là họ hàng của T-Rex đấy. Các em đoán xem là con gì nào?' Đứa thì đoán sư tử, đứa đoán gấu, đứa lại đoán cá sấu." },
      { "start": 56.0, "en": "'No, but I have this creature in my lunchbox!' Then, she pulled something out and took a big bite of it. 'Mmmm, I love chicken legs!' she said. We were amazed!", "ipa": "/noʊ, bʌt aɪ hæv ðɪs ˈkriːtʃər ɪn maɪ ˈlʌntʃbɒks! ðɛn, ʃiː pʊld ˈsʌmθɪŋ aʊt ænd tʊk ə bɪɡ baɪt əv ɪt. mːːm, aɪ lʌv ˈtʃɪkɪn lɛɡz!, ʃiː sɛd. wiː wɜːr əˈmeɪzd!/", vi: "'Sai hết rồi, cô có con vật này ngay trong hộp cơm trưa của mình đây!' Nói rồi cô rút ra một miếng đùi gà và cắn ngon lành: 'Ngon quá, cô mê nhất là đùi gà!' Cả lớp òa lên ngỡ ngàng thích thú!" }
    ]
  },
  {
    "day": 25,
    "title": "My Neighbourhood",
    "image": "05 May/images/day_25.webp",
    "audio": "05 May/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "I live downtown. My home is only two blocks away from the busiest street in the city. One day, our teacher gave us some homework: to interview people in different jobs. How interesting!", "ipa": "/aɪ lɪv ˈdaʊntaʊn. maɪ hoʊm ɪz ˈoʊnli tuː blɒks əˈweɪ frɒm ðə ˈbɪziɪst striːt ɪn ðə ˈsɪti. wʌn deɪ, ˈaʊər ˈtiːtʃər ɡeɪv ʌs sʌm ˈhoʊmwɜːrk: tuː ˈɪntərvjuː ˈpiːpl ɪn ˈdɪfrənt dʒɒbz. haʊ ˈɪntrəstɪŋ!/", vi: "Tôi sống ở trung tâm thành phố, nhà chỉ cách con phố sầm uất nhất hai dãy nhà. Hôm nay cô giáo giao bài tập về nhà: Phỏng vấn những người làm các ngành nghề khác nhau. Thật thú vị làm sao!" },
      { "start": 18.0, "en": "I couldn't wait to start my homework. First, I went to a tailor shop. Mr. Moe had been a tailor for more than twenty years. He was busy fixing a pair of pants for a lady. Mr. Moe cut the fabric with his magic scissors while we talked. Ten minutes later, the old lady left the shop with a big smile on her face.", "ipa": "/aɪ ˈkʊdnt weɪt tuː stɑːrt maɪ ˈhoʊmwɜːrk. fɜːrst, aɪ wɛnt tuː ə ˈteɪlər ʃɒp. ˈmɪstər moʊ hæd biːn ə ˈteɪlər fɔːr mɔːr ðæn ˈtwɛnti jɪərz. hiː wɒz ˈbɪzi ˈfɪksɪŋ ə pɛər əv pænts fɔːr ə ˈleɪdi. ˈmɪstər moʊ kʌt ðə ˈfæbrɪk wɪð hɪz ˈmædʒɪk ˈsɪzərz waɪl wiː tɔːkt. tɛn ˈmɪnɪts ˈleɪtər, ði oʊld ˈleɪdi lɛft ðə ʃɒp wɪð ə bɪɡ smaɪl ɒn hɜːr feɪs/", vi: "Tôi háo hức bắt tay vào làm bài ngay. Điểm dừng đầu tiên là tiệm may của bác Moe đã gắn bó với nghề hơn 20 năm. Bác vừa thoăn thoắt cắt vải sửa quần cho khách vừa vui vẻ trò chuyện với tôi. Mười phút sau, vị khách tươi cười rời tiệm với chiếc quần ưng ý." },
      { "start": 41.0, "en": "My second stop was Ms. Ricci's bakery. The bakery shop was warm and the air smelled delicious! There were many treats. Yummy! Ms. Ricci gets up at 5:30 a.m. every day. By 7 a.m., all the breads are ready and her store opens.", "ipa": "/maɪ ˈsɛkənd stɒp wɒz mɪz ˈriːtʃiz ˈbeɪkəri. ðə ˈbeɪkəri ʃɒp wɒz wɔːrm ænd ði ɛər smɛld dɪˈlɪʃəs! ðɛər wɜːr ˈmɛni triːts. ˈjʌmi! mɪz ˈriːtʃi ɡɛts ʌp æt faɪv ˈθɜːrti eɪ-ɛm ˈɛvri deɪ. baɪ ˈsɛvn eɪ-ɛm, ɔːl ðə brɛdz ɑːr ˈrɛdi ænd hɜːr stɔːr ˈoʊpənz/", vi: "Điểm đến thứ hai là tiệm bánh của cô Ricci. Không gian ấm sực phảng phất mùi bánh nướng thơm lừng kích thích. Cô Ricci thức dậy từ 5 giờ rưỡi sáng để kịp chuẩn bị những mẻ bánh nóng hổi mở cửa đón khách lúc 7 giờ." },
      { "start": 60.0, "en": "After the bakery, I visited a grocery store, a clinic, a flower shop, a bookstore and a clothing shop. Oh, I love my neighbourhood!", "ipa": "/ˈɑːftər ðə ˈbeɪkəri, aɪ ˈvɪzɪtɪd ə ˈɡroʊsəri stɔːr, ə ˈklɪnɪk, ə ˈflaʊər ʃɒp, ə ˈbʊkstɔːr ænd ə ˈkloʊðɪŋ ʃɒp. oʊ, aɪ lʌv maɪ ˈneɪbərˌhʊd!/", vi: "Sau tiệm bánh, tôi còn ghé thăm tiệm tạp hóa, phòng khám, tiệm hoa tươi, hiệu sách và cửa hàng thời trang. Ôi, tôi yêu khu phố thân thương của mình biết bao!" }
    ]
  },
  {
    "day": 26,
    "title": "First Day of School",
    "image": "05 May/images/day_26.webp",
    "audio": "05 May/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "Tommy was a young boy. He was eager to start school. Every day, he would ask his mom, 'Is today the day I go to school?' 'No, not yet,' his mom would say.", "ipa": "/ˈtɒmi wɒz ə jʌŋ bɔɪ. hiː wɒz ˈiːɡər tuː stɑːrt skuːl. ˈɛvri deɪ, hiː wʊd ɑːsk hɪz mɒm, ɪz təˈdeɪ ðə deɪ aɪ ɡoʊ tuː skuːl? noʊ, nɒt jɛt, hɪz mɒm wʊd seɪ/", vi: "Tommy là một cậu bé rất háo hức được đi học. Ngày nào cậu cũng hỏi mẹ: 'Hôm nay con được đi học chưa mẹ?' 'Chưa đâu con yêu,' mẹ bảo." },
      { "start": 18.0, "en": "This went on for months. Finally, one day, his mom said, 'Yes, today is the day you go to school.' Suddenly, Tommy felt scared. He didn't want to be away from his mom.", "ipa": "/ðɪs wɛnt ɒn fɔːr mʌnθs. ˈfaɪnəli, wʌn deɪ, hɪz mɒm sɛd, jɛs, təˈdeɪ ɪz ðə deɪ juː ɡoʊ tuː skuːl. ˈsʌdənli, ˈtɒmi fɛlt skɛərd. hiː ˈdɪdnt wɒnt tuː biː əˈweɪ frɒm hɪz mɒm/", vi: "Cứ thế suốt mấy tháng trôi qua. Cho đến một hôm mẹ bảo: 'Đúng rồi, hôm nay là ngày con chính thức đến trường đấy.' Đột nhiên Tommy thấy sợ hãi, cậu bé không muốn phải rời xa mẹ." },
      { "start": 32.0, "en": "'No, I'm not going!' He ran upstairs and hid under his bed. He heard his mom calling him, but he didn't answer. Then, his mom came to his room. 'Are you under the bed?' she asked. 'No, I'm not,' said Tommy.", "ipa": "/noʊ, aɪm nɒt ˈɡoʊɪŋ! hiː ræn ˌʌpˈstɛərz ænd hɪd ˈʌndər hɪz bɛd. hiː hɜːrd hɪz mɒm ˈkɔːlɪŋ hɪm, bʌt hiː ˈdɪdnt ˈɑːnsər. ðɛn, hɪz mɒm keɪm tuː hɪz ruːm. ɑːr juː ˈʌndər ðə bɛd?, ʃiː ɑːskt. noʊ, aɪm nɒt, sɛd ˈtɒmi/", vi: "'Con không đi đâu!' Cậu chạy tót lên gác trốn biệt dưới gầm giường, nghe mẹ gọi cũng chẳng buồn thưa. Mẹ bước vào phòng dịu dàng hỏi: 'Có phải con đang trốn dưới gầm giường không?' 'Không phải con đâu ạ,' Tommy hồn nhiên trả lời." },
      { "start": 52.0, "en": "Mom laughed. She pulled Tommy out. Then she sent him to school. She stayed there for a little while. Other mothers were there too. At the end of the day, Tommy came out of the school with a big smile on his face. He was very glad he went.", "ipa": "/mɒm lɑːft. ʃiː pʊld ˈtɒmi aʊt. ðɛn ʃiː sɛnt hɪm tuː skuːl. ʃiː steɪd ðɛər fɔːr ə ˈlɪtl waɪl. ˈʌðər ˈmʌðərz wɜːr ðɛər tuː. æt ði ɛnd əv ðə deɪ, ˈtɒmi keɪm aʊt əv ðə skuːl wɪð ə bɪɡ smaɪl ɒn hɪz feɪs. hiː wɒz ˈvɛri ɡlæd hiː wɛnt/", vi: "Mẹ phì cười kéo Tommy ra rồi đưa cậu đến trường. Mẹ nán lại một lát cùng các phụ huynh khác để cậu quen dần. Cuối ngày tan học, Tommy bước ra với nụ cười rạng rỡ trên môi, cậu bé cảm thấy thật vui vì mình đã can đảm đi học." }
    ]
  },
  {
    "day": 27,
    "title": "Love the Sun",
    "image": "05 May/images/day_27.webp",
    "audio": "05 May/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "One morning, Lillian was sitting in the garden. She was looking at the wonderful flowers of every colour. Her favourites were the big yellow sunflowers. They had big yellow faces.", "ipa": "/wʌn ˈmɔːrnɪŋ, ˈlɪliən wɒz ˈsɪtɪŋ ɪn ðə ˈɡɑːrdn. ʃiː wɒz ˈlʊkɪŋ æt ðə ˈwʌndərfʊl ˈflaʊərz əv ˈɛvri ˈkʌlər. hɜːr ˈfeɪvərɪts wɜːr ðə bɪɡ ˈjɛloʊ ˈsʌnˌflaʊərz. ðeɪ hæd bɪɡ ˈjɛloʊ ˈfeɪsɪz/", vi: "Một sáng nọ, Lillian ngồi ngắm muôn hoa khoe sắc rực rỡ ngoài vườn. Loài hoa bé yêu thích nhất chính là những đóa hướng dương vàng rực với gương mặt tròn to như mặt trời." },
      { "start": 18.0, "en": "She noticed that the sunflowers turned their big heads towards the sun as it rose in the east. 'Wow! No wonder they are called sunflowers,' she thought. 'Do sunflowers really LOVE the sun?' she wondered.", "ipa": "/ʃiː ˈnoʊtɪst ðæt ðə ˈsʌnˌflaʊərz tɜːrnd ðɛər bɪɡ hɛdz təˈwɔːrdz ðə sʌn æz ɪt roʊz ɪn ði iːst. waʊ! noʊ ˈwʌndər ðeɪ ɑːr kɔːld ˈsʌnˌflaʊərz, ʃiː θɔːt. duː ˈsʌnˌflaʊərz ˈrɪəli lʌv ðə sʌn?, ʃiː ˈwʌndərd/", vi: "Bé nhận thấy những bông hoa luôn ngoảnh đầu về hướng đông đón ánh mặt trời vừa thức giấc. 'Chà! Thảo nào người ta gọi là hoa hướng dương,' bé thầm nghĩ. 'Liệu có phải chúng thực sự YÊU mặt trời không nhỉ?'" },
      { "start": 33.0, "en": "At noon, Lillian looked at the sunflowers again. Amazing! The sun had moved across the sky. And all the sunflowers had turned their heads to follow it as it moved.", "ipa": "/æt nuːn, ˈlɪliən lʊkt æt ðə ˈsʌnˌflaʊərz əˈɡɛn. əˈmeɪzɪŋ! ðə sʌn hæd muːvd əˈkrɒs ðə skaɪ. ænd ɔːl ðə ˈsʌnˌflaʊərz hæd tɜːrnd ðɛər hɛdz tuː ˈfɒloʊ ɪt æz ɪt muːvd/", vi: "Đến giữa trưa, Lillian lại ra ngắm hoa. Thật kỳ diệu! Mặt trời đã di chuyển lên đỉnh đầu, và bầy hoa hướng dương cũng ngước nhìn thẳng lên trời dõi theo từng bước đi của mặt trời." },
      { "start": 48.0, "en": "That evening, as the sun was setting, Lillian noticed that the sunflowers were all facing west—towards the setting sun. Their faces had turned again!", "ipa": "/ðæt ˈiːvnɪŋ, æz ðə sʌn wɒz ˈsɛtɪŋ, ˈlɪliən ˈnoʊtɪst ðæt ðə ˈsʌnˌflaʊərz wɜːr ɔːl ˈfeɪsɪŋ wɛst—təˈwɔːrdz ðə ˈsɛtɪŋ sʌn. ðɛər ˈfeɪsɪz hæd tɜːrnd əˈɡɛn!/", vi: "Chiều tà khi hoàng hôn buông xuống, Lillian nhận ra tất cả các đóa hướng dương đã quay mặt về hướng tây — đón những tia nắng ấm áp cuối ngày. Chúng lại đổi hướng lần nữa!" },
      { "start": 61.0, "en": "'Sunflowers really do love the sun,' she thought to herself. 'They follow it across the sky each day, turning their faces to catch as much sun as they can.' The sunflower—what an interesting name and plant!", "ipa": "/ˈsʌnˌflaʊərz ˈrɪəli duː lʌv ðə sʌn, ʃiː θɔːt tuː hɜːrˈsɛlf. ðeɪ ˈfɒloʊ ɪt əˈkrɒs ðə skaɪ iːtʃ deɪ, ˈtɜːrnɪŋ ðɛər ˈfeɪsɪz tuː kætʃ æz mʌtʃ sʌn æz ðeɪ kæn. ðə ˈsʌnˌflaʊər—wɒt ən ˈɪntrəstɪŋ neɪm ænd plænt!/", vi: "'Hoa hướng dương thực sự rất yêu mặt trời,' cô bé thích thú reo lên. 'Ngày nào hoa cũng miệt mài dõi theo vầng dương để đón trọn từng tia nắng ấm.' Hoa hướng dương — quả là một cái tên và một loài cây kỳ diệu!" }
    ]
  },
  {
    "day": 28,
    "title": "Surprise",
    "image": "05 May/images/day_28.webp",
    "audio": "05 May/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "Alex was very excited today. 'Mom, will you help me bake a cake?' asked Alex. 'Okay,' said Mom. 'Get out a bowl.'", "ipa": "/ˈælɪks wɒz ˈvɛri ɪkˈsaɪtɪd təˈdeɪ. mɒm, wɪl juː hɛlp miː beɪk ə keɪk?, ɑːskt ˈælɪks. oʊˈkeɪ, sɛd mɒm. ɡɛt aʊt ə boʊl/", vi: "Hôm nay Alex rất háo hức: 'Mẹ ơi, mẹ giúp con nướng một chiếc bánh kem nhé?' Mẹ mỉm cười: 'Được chứ, con lấy một chiếc tô to ra đây nào.'" },
      { "start": 16.0, "en": "First, Mom put butter, sugar and eggs in the bowl. Alex mixed, and mixed, and mixed. The batter looked smooth and shiny. Then, Mom added flour, salt, and baking powder. Alex mixed, mixed and mixed. The batter looked thick and lumpy.", "ipa": "/fɜːrst, mɒm pʊt ˈbʌtər, ˈʃʊɡər ænd ɛɡz ɪn ðə boʊl. ˈælɪks mɪkst, ænd mɪkst, ænd mɪkst. ðə ˈbætər lʊkt smuːð ænd ˈʃaɪni. ðɛn, mɒm ˈædɪd ˈflaʊər, sɔːlt, ænd ˈbeɪkɪŋ ˌpaʊdər. ˈælɪks mɪkst, mɪkst ænd mɪkst. ðə ˈbætər lʊkt θɪk ænd ˈlʌmpi/", vi: "Đầu tiên mẹ cho bơ, đường và trứng vào tô. Alex khuấy đều tay đến khi hỗn hợp mịn màng óng ánh. Rồi mẹ cho thêm bột mì, muối và bột nở. Alex lại ra sức khuấy, bột bắt đầu đặc quánh lại." },
      { "start": 35.0, "en": "Mom said, 'Keep mixing.' Alex mixed, and mixed, and mixed some more. His arm hurt, but the batter was smooth. Alex poured the batter into a cake pan. He then put the cake pan in the oven.", "ipa": "/mɒm sɛd, kiːp ˈmɪksɪŋ. ˈælɪks mɪkst, ænd mɪkst, ænd mɪkst sʌm mɔːr. hɪz ɑːrm hɜːrt, bʌt ðə ˈbætər wɒz smuːð. ˈælɪks pɔːrd ðə ˈbætər ˈɪntuː ə keɪk pæn. hiː ðɛn pʊt ðə keɪk pæn ɪn ði ˈʌvn/", vi: "Mẹ bảo: 'Khuấy tiếp đi con.' Alex dồn sức khuấy thêm một lúc nữa dẫu tay mỏi nhừ, cho đến khi bột thật mịn. Cậu đổ hỗn hợp vào khuôn rồi cẩn thận đặt vào lò nướng." },
      { "start": 52.0, "en": "Alex waited. The cake smelled sweet and sugary. His mouth watered. Mom pulled the cake out of the oven. The top was golden brown. 'The cake is ready to eat, Alex!' called his mom.", "ipa": "/ˈælɪks ˈweɪtɪd. ðə keɪk smɛld swiːt ænd ˈʃʊɡəri. hɪz maʊθ ˈwɔːtərd. mɒm pʊld ðə keɪk aʊt əv ði ˈʌvn. ðə tɒp wɒz ˈɡoʊldən braʊn. ðə keɪk ɪz ˈrɛdi tuː iːt, ˈælɪks!, kɔːld hɪz mɒm/", vi: "Alex kiên nhẫn ngồi đợi. Hương thơm ngọt ngào của bánh lan tỏa khắp gian bếp làm cậu ứa cả nước miếng. Mẹ kéo chiếc bánh nở vàng ươm ra khỏi lò: 'Bánh chín rồi nè Alex ơi!'" },
      { "start": 68.0, "en": "'There!' Alex pushed the cake to his mom and said, 'Happy Birthday, Mom!'", "ipa": "/ðɛər! ˈælɪks pʊʃt ðə keɪk tuː hɪz mɒm ænd sɛd, ˈhæpi ˈbɜːrθdeɪ, mɒm!/", vi: "'Bánh đây ạ!' Alex đẩy chiếc bánh về phía mẹ và tươi cười reo lên: 'Con chúc mừng sinh nhật mẹ yêu!'" }
    ]
  },
  {
    "day": 29,
    "title": "Celebrate Mothers",
    "image": "05 May/images/day_29.webp",
    "audio": "05 May/audio/Track29.mp3",
    "sentences": [
      { "start": 4.8, "en": "Let's all think about this: almost every country in the world celebrates Mother's Day. Isn't that amazing? Australia, Canada, Brazil, China, Bulgaria, Germany, Greece, Japan, Italy, Mexico, India, Portugal, Sweden—the list goes on and on.", "ipa": "/lɛts ɔːl θɪŋk əˈbaʊt ðɪs: ˈɔːlmoʊst ˈɛvri ˈkʌntri ɪn ðə wɜːrld ˈsɛlɪbreɪts ˈmʌðərz deɪ. ˈɪznt ðæt əˈmeɪzɪŋ? ɒˈstreɪliə, ˈkænədə, brəˈzɪl, ˈtʃaɪnə, bʊlˈɡɛəriə, ˈdʒɜːrməni, ɡriːs, dʒəˈpæn, ˈɪtəli, ˈmɛksɪkoʊ, ˈɪndiə, ˈpɔːrtʃʊɡl, ˈswiːdn—ðə lɪst ɡoʊz ɒn ænd ɒn/", vi: "Thử ngẫm mà xem: Hầu như mọi quốc gia trên thế giới đều kỷ niệm Ngày của Mẹ. Thật kỳ diệu phải không nào? Từ Úc, Canada, Brazil, Trung Quốc, Đức, Nhật Bản, Ý đến Mexico... danh sách còn kéo dài mãi." },
      { "start": 26.0, "en": "Although different countries celebrate this special day in different ways, they all recognize the importance and role of mothers in society.", "ipa": "/ɔːlˈðoʊ ˈdɪfrənt ˈkʌntriz ˈsɛlɪbreɪt ðɪs ˈspɛʃl deɪ ɪn ˈdɪfrənt weɪz, ðeɪ ɔːl ˈrɛkəɡnaɪz ði ɪmˈpɔːrtns ænd roʊl əv ˈmʌðərz ɪn səˈsaɪəti/", vi: "Dù mỗi nơi đón chào ngày này theo những phong tục tập quán riêng biệt, nhưng tất cả đều tôn vinh vai trò thiêng liêng và vĩ đại của người mẹ trong xã hội." },
      { "start": 39.0, "en": "On this special day, we all honour our mothers and their contribution to this world. We do things to show them that we value and love them. It's one of the greatest things we can do to show them we care and appreciate everything they have done for us.", "ipa": "/ɒn ðɪs ˈspɛʃl deɪ, wiː ɔːl ˈɒnər ˈaʊər ˈmʌðərz ænd ðɛər ˌkɒntrɪˈbjuːʃn tuː ðɪs wɜːrld. wiː duː θɪŋz tuː ʃoʊ ðɛm ðæt wiː ˈvæljuː ænd lʌv ðɛm. ɪts wʌn əv ðə ˈɡreɪtɪst θɪŋz wiː kæn duː tuː ʃoʊ ðɛm wiː kɛər ænd əˈpriːʃieɪt ˈɛvriˌθɪŋ ðeɪ hæv dʌn fɔːr ʌs/", vi: "Vào ngày đặc biệt này, chúng ta bày tỏ lòng biết ơn sâu sắc trước những hy sinh của mẹ. Đó là cơ hội tuyệt vời để trao gửi yêu thương và thể hiện sự trân trọng trước tất cả những gì mẹ đã dành cho ta." },
      { "start": 61.0, "en": "So, next Mother's Day, do something special for your mom!", "ipa": "/soʊ, nɛkst ˈmʌðərz deɪ, duː ˈsʌmθɪŋ ˈspɛʃl fɔːr jɔːr mɒm!/", vi: "Vì thế, vào Ngày của Mẹ sắp tới, bạn hãy làm một điều gì đó thật ý nghĩa dành tặng mẹ yêu nhé!" }
    ]
  },
  {
    "day": 30,
    "title": "African Safari",
    "image": "05 May/images/day_30.webp",
    "audio": "05 May/audio/Track30.mp3",
    "sentences": [
      { "start": 4.8, "en": "Africa is home to some of the most wonderful wildlife on our planet. Many visitors travel there to go on an exciting safari. They ride in open vehicles across the grassy plains to see wild animals living freely in nature.", "ipa": "/ˈæfrɪkə ɪz hoʊm tuː sʌm əv ðə moʊst ˈwʌndərfʊl ˈwaɪldlaɪf ɒn ˈaʊər ˈplænɪt. ˈmɛni ˈvɪzɪtərz ˈtrævl ðɛər tuː ɡoʊ ɒn ən ɪkˈsaɪtɪŋ səˈfɑːri. ðeɪ raɪd ɪn ˈoʊpən ˈviːəklz əˈkrɒs ðə ˈɡrɑːsi pleɪnz tuː siː waɪld ˈænɪmlz ˈlɪvɪŋ ˈfriːli ɪn ˈneɪtʃər/", vi: "Châu Phi là ngôi nhà chung của những loài động vật hoang dã kỳ thú bậc nhất hành tinh. Du khách từ khắp nơi đổ về đây để tham gia những chuyến thám hiểm safari hấp dẫn, ngồi trên xe mui trần băng qua thảo nguyên bao la ngắm muôn loài tự do sinh sống." },
      { "start": 25.0, "en": "You can spot graceful giraffes eating leaves from tall acacia trees, majestic lions resting under the shade, and giant elephants marching together in large families.", "ipa": "/juː kæn spɒt ˈɡreɪsfʊl dʒɪˈrɑːfs ˈiːtɪŋ liːvz frɒm tɔːl əˈkeɪʃə triːz, məˈdʒɛstɪk ˈlaɪənz ˈrɛstɪŋ ˈʌndər ðə ʃeɪd, ænd ˈdʒaɪənt ˈɛlɪfənts ˈmɑːrtʃɪŋ təˈɡɛðər ɪn lɑːrdʒ ˈfæməlɪz/", vi: "Bạn có thể bắt gặp những chú hươu cao cổ duyên dáng vươn cổ ăn lá cây xiêm gai, bầy sư tử oai phong nằm nghỉ dưới bóng râm, và đàn voi khổng lồ nối đuôi nhau sải bước." },
      { "start": 42.0, "en": "Seeing these magnificent creatures up close in their natural habitat is an unforgettable adventure that reminds everyone why we must protect wildlife and preserve our earth.", "ipa": "/ˈsiːɪŋ ðiːz mæɡˈnɪfɪsnt ˈkriːtʃərz ʌp kloʊs ɪn ðɛər ˈnætʃrəl ˈhæbɪtæt ɪz ən ˌʌnfərˈɡɛtəbl ədˈvɛntʃər ðæt rɪˈmaɪndz ˈɛvriˌwʌn waɪ wiː mʌst prəˈtɛkt ˈwaɪldlaɪf ænd prɪˈzɜːrv ˈaʊər ɜːrθ/", vi: "Được tận mắt chiêm ngưỡng những sinh vật tuyệt đẹp này nơi hoang dã là một trải nghiệm khó quên, nhắc nhở chúng ta về trách nhiệm bảo vệ muôn loài và giữ gìn Trái Đất tươi xanh." }
    ]
  },
  {
    "day": 31,
    "title": "Queen's Day",
    "image": "05 May/images/day_31.webp",
    "audio": "05 May/audio/Track31.mp3",
    "sentences": [
      { "start": 4.8, "en": "Today is April 30. My family travelled to Amsterdam to celebrate the Queen's birthday. My favourite part of Queen's Day is the orange craze.", "ipa": "/təˈdeɪ ɪz ˈeɪprəl ˈθɜːrtiəθ. maɪ ˈfæməli ˈtrævld tuː ˈæmstərdæm tuː ˈsɛlɪbreɪt ðə kwiːnz ˈbɜːrθdeɪ. maɪ ˈfeɪvərɪt pɑːrt əv kwiːnz deɪ ɪz ði ˈɒrɪndʒ kreɪz/", vi: "Hôm nay là ngày 30 tháng Tư. Cả gia đình tôi cùng đi du lịch tới Amsterdam để chúc mừng sinh nhật Nữ hoàng. Phần tôi thích nhất chính là lễ hội sắc cam rực rỡ." },
      { "start": 16.0, "en": "To honour the Dutch royal family, The House of Orange, we all wore the fun, bright colours. I had pretty orange ribbons tied in my hair. They fluttered in the breeze and tickled my face.", "ipa": "/tuː ˈɒnər ðə dʌtʃ ˈrɔɪəl ˈfæməli, ðə haʊs əv ˈɒrɪndʒ, wiː ɔːl wɔːr ðə fʌn, braɪt ˈkʌlərz. aɪ hæd ˈprɪti ˈɒrɪndʒ ˈrɪbənz taɪd ɪn maɪ hɛər. ðeɪ ˈflʌtərd ɪn ðə briːz ænd ˈtɪkld maɪ feɪs/", vi: "Để tôn vinh hoàng gia Hà Lan (Dòng họ Orange), mọi người đều diện trang phục màu cam tươi sáng. Tôi thắt dải ruy băng cam xinh xắn trên tóc, bay bay theo làn gió nhẹ mơn man trên má." },
      { "start": 32.0, "en": "At one of the stands, Dad bought each of us a Dutch flag to wave around during the parade. Then, we made our way to the parade route. 'Look, Dad. It's the Queen! I see Queen Beatrix!'", "ipa": "/æt wʌn əv ðə stændz, dæd bɔːt iːtʃ əv ʌs ə dʌtʃ flæɡ tuː weɪv əˈraʊnd ˈdjʊərɪŋ ðə pəˈreɪd. ðɛn, wiː meɪd ˈaʊər weɪ tuː ðə pəˈreɪd ruːt. lʊk, dæd. ɪts ðə kwiːn! aɪ siː kwiːn biˈeɪtrɪks!/", vi: "Ở một quầy hàng, bố mua cho mỗi người một lá cờ Hà Lan để vẫy chào trong đoàn diễu hành. 'Bố nhìn kìa! Nữ hoàng kìa bố! Con thấy Nữ hoàng Beatrix rồi!'" },
      { "start": 48.0, "en": "Mom told me that Queen's Day is meant to be a national day of togetherness. Here, on Dad's shoulders, I could see it. People were holding hands, talking and laughing. They were showing their love for their queen and their country.", "ipa": "/mɒm toʊld miː ðæt kwiːnz deɪ ɪz mɛnt tuː biː ə ˈnæʃnəl deɪ əv təˈɡɛðərnəs. hɪər, ɒn dædz ˈʃoʊldərz, aɪ kʊd siː ɪt. ˈpiːpl wɜːr ˈhoʊldɪŋ hændz, ˈtɔːkɪŋ ænd ˈlɑːfɪŋ. ðeɪ wɜːr ˈʃoʊɪŋ ðɛər lʌv fɔːr ðɛər kwiːn ænd ðɛər ˈkʌntri/", vi: "Mẹ bảo Ngày Nữ hoàng chính là ngày hội đoàn kết toàn dân tộc. Ngồi trên vai bố, tôi cảm nhận rõ điều đó: Mọi người nắm tay nhau, chuyện trò rộn rã và cất tiếng cười vang, thể hiện tình yêu nồng nhiệt với Nữ hoàng và đất nước." },
      { "start": 68.0, "en": "I waved my flag as high as my arm could reach and became a part of it all.", "ipa": "/aɪ weɪvd maɪ flæɡ æz haɪ æz maɪ ɑːrm kʊd riːtʃ ænd bɪˈkeɪm ə pɑːrt əv ɪt ɔːl/", vi: "Tôi giơ cao cánh tay vẫy lá cờ hết sức có thể và hòa mình trọn vẹn vào ngày hội tuyệt vời ấy." }
    ]
  }
];