if (typeof STORIES_DATA === 'undefined') {
  var STORIES_DATA = {};
}

STORIES_DATA["02 February"] = [
  {
    "day": 1,
    "title": "Getting a Pet",
    "image": "02 February/images/day_01.webp",
    "audio": "02 February/audio/Track01.mp3",
    "sentences": [
      { "start": 4.8, "en": "Yan loves animals. He wants a pet. There is only one problem. His family lives in a very small apartment.", "ipa": "/jæn lʌvz ˈænɪmlz. hiː wɒnts a pɛt. ðɛr ɪz ˈoʊnli wʌn ˈprɒbləm. hɪz ˈfæməli lɪvz ɪn a ˈvɛri smɔːl əˈpɑːrtmənt/", "vi": "Yan rất yêu động vật và muốn nuôi một con thú cưng. Chỉ có một vấn đề duy nhất là gia đình cậu đang sống trong một căn hộ rất nhỏ." },
      { "start": 15.0, "en": "He begs his parents to let him have a puppy. But his father says, 'A puppy is small. But puppies grow into big dogs. We have no space for a dog.'", "ipa": "/hiː bɛɡz hɪz ˈpɛrənts tuː lɛt hɪm hæv a ˈpʌpi. bʌt hɪz ˈfɑːðər sɛz, a ˈpʌpi ɪz smɔːl. bʌt ˈpʌpiz ɡroʊ ˈɪntuː bɪɡ dɔːɡz. wiː hæv noʊ speɪs fɔːr a dɔːɡ/", "vi": "Cậu nài nỉ bố mẹ cho nuôi một chú chó con. Nhưng bố bảo: 'Chó con bây giờ thì nhỏ, nhưng chúng sẽ lớn thành chó trưởng thành. Nhà chúng ta không có chỗ cho chó lớn.'" },
      { "start": 27.0, "en": "So, Yan asks for a kitten. His mom looks at her son. She wants him to have a pet. But the apartment is SO small.", "ipa": "/soʊ, jæn ɑːsks fɔːr a ˈkɪtn. hɪz mɒm lʊks æt hɜːr sʌn. ʃiː wɒnts hɪm tuː hæv a pɛt. bʌt ðə əˈpɑːrtmənt ɪz soʊ smɔːl/", "vi": "Thế là Yan đổi ý xin nuôi mèo con. Mẹ nhìn con trai với ánh mắt thông cảm; mẹ rất muốn con có thú cưng, ngặt nỗi căn hộ quá ư chật chội." },
      { "start": 38.0, "en": "'We cannot get a kitten either,' she says. 'Kittens become cats. And cats are big.'", "ipa": "/wiː ˈkænɒt ɡɛt a ˈkɪtn ˈiːðər, ʃiː sɛz. ˈkɪtnz bɪˈkʌm kæts. ænd kæts ɑːr bɪɡ/", "vi": "'Chúng ta cũng không thể nuôi mèo con được đâu,' mẹ nói. 'Mèo con rồi sẽ lớn thành mèo lớn.'" },
      { "start": 46.0, "en": "Yan is sad. But he understands. Then one day, he comes home from school and sees something on his table.", "ipa": "/jæn ɪz sæd. bʌt hiː ˌʌndərˈstændz. ðɛn wʌn deɪ, hiː kʌmz hoʊm frɒm skuːl ænd siːz ˈsʌmθɪŋ ɒn hɪz ˈteɪbl/", vi: "Yan buồn bã nhưng cậu hiểu cho hoàn cảnh gia đình. Thế rồi vào một ngày nọ, đi học về bước vào phòng, cậu nhìn thấy một vật gì đó đang đặt trên bàn." },
      { "start": 57.0, "en": "It's a bowl filled with water. Inside is a pretty little goldfish! It is swimming around and around. Yan laughs with joy.", "ipa": "/ɪts a boʊl fɪld wɪð ˈwɔːtər. ˈɪnˌsaɪd ɪz a ˈprɪti ˈlɪtl ˈɡoʊldˌfɪʃ! ɪt ɪz ˈswɪmɪŋ əˈraʊnd ænd əˈraʊnd. jæn lɑːfs wɪð dʒɔɪ/", vi: "Đó là một chiếc bình thủy tinh đầy nước. Bên trong có một chú cá vàng nhỏ xinh xắn đang bơi lượn vòng quanh. Yan cười tít mắt vì quá đỗi vui sướng." },
      { "start": 69.0, "en": "Now, Yan has a pet. He calls his goldfish Goldie. Goldie is his very best friend!", "ipa": "/naʊ, jæn hæz a pɛt. hiː kɔːlz hɪz ˈɡoʊldˌfɪʃ ˈɡoʊldi. ˈɡoʊldi ɪz hɪz ˈvɛri bɛst frɛnd/", vi: "Giờ đây Yan đã thực sự có thú cưng của riêng mình. Cậu đặt tên cho chú cá vàng là Goldie. Goldie chính là người bạn thân thiết nhất của cậu!" }
    ]
  },
  {
    "day": 2,
    "title": "Running a Race",
    "image": "02 February/images/day_02.webp",
    "audio": "02 February/audio/Track02.mp3",
    "sentences": [
      { "start": 4.8, "en": "Every year, we have a race at school to see who can run the fastest. And every year, my friend Jim wins.", "ipa": "/ˈɛvri jɪər, wiː hæv a reɪs æt skuːl tuː siː huː kæn rʌn ðə ˈfæstɪst. ænd ˈɛvri jɪər, maɪ frɛnd dʒɪm wɪnz/", vi: "Hằng năm, trường chúng tôi đều tổ chức một cuộc đua để xem ai chạy nhanh nhất. Và năm nào cũng vậy, người giành chiến thắng luôn là cậu bạn Jim của tôi." },
      { "start": 14.0, "en": "This year, I decided to work very hard to beat Jim. I trained very hard and ran every day. Finally, the day of the race came.", "ipa": "/ðɪs jɪər, aɪ dɪˈsaɪdɪd tuː wɜːrk ˈvɛri hɑːrd tuː biːt dʒɪm. aɪ treɪnd ˈvɛri hɑːrd ænd ræn ˈɛvri deɪ. ˈfaɪnəli, ðə deɪ əv ðə reɪs keɪm/", vi: "Năm nay, tôi quyết tâm tập luyện thật chăm chỉ để đánh bại Jim. Tôi rèn luyện cật lực và chạy bộ mỗi ngày. Cuối cùng, ngày cuộc đua cũng đã đến." },
      { "start": 26.0, "en": "Everyone got ready at the start line. Then, the gun went off with a 'Bang!' I was in the lead, but I could tell Jim was catching up fast.", "ipa": "/ˈɛvriˌwʌn ɡɒt ˈrɛdi æt ðə stɑːrt laɪn. ðɛn, ðə ɡʌn wɛnt ɔːf wɪð a bæŋ! aɪ wɒz ɪn ðə liːd, bʌt aɪ kʊd tɛl dʒɪm wɒz ˈkætʃɪŋ ʌp fɑːst/", vi: "Mọi người tập trung sẵn sàng ở vạch xuất phát. Tiếng súng lệnh vang lên 'Đoàng!' Một hơi bứt tốc, tôi vươn lên dẫn đầu, nhưng tôi cảm nhận rõ Jim đang bám đuổi theo sát nút." },
      { "start": 38.0, "en": "Soon, we were running together. It was the last turn before the finish line. We ran side by side. It was fun! We did not care who won anymore. We could always share the prize.", "ipa": "/suːn, wiː wɜːr ˈrʌnɪŋ təˈɡɛðər. ɪt wɒz ðə lɑːst tɜːrn bɪˈfɔːr ðə ˈfɪnɪʃ laɪn. wiː ræn saɪd baɪ saɪd. ɪt wɒz fʌn! wiː dɪd nɒt kɛər huː wʌn ˈɛniˌmɔːr. wiː kʊd ˈɔːlweɪz ʃɛr ðə praɪz/", vi: "Chẳng mấy chốc, hai đứa chạy song song kè kè bên nhau ở khúc cua cuối cùng trước vạch đích. Thật là phấn khích làm sao! Lúc đó chúng tôi chẳng còn bận tâm ai thắng ai thua nữa, vì cả hai hoàn toàn có thể chia sẻ phần thưởng cùng nhau." },
      { "start": 53.0, "en": "We were having so much fun that we did not notice that another boy had passed us both! Joey zipped by at the very last second.", "ipa": "/wiː wɜːr ˈhævɪŋ soʊ mʌtʃ fʌn ðæt wiː dɪd nɒt ˈnoʊtɪs ðæt əˈnʌðər bɔɪ hæd pɑːst ʌs boʊθ! ˈdʒoʊi zɪpt baɪ æt ðə ˈvɛri lɑːst ˈsɛkənd/", vi: "Mải mê tận hưởng niềm vui đua tranh mà chúng tôi quên bẵng mất một cậu bạn khác đã vượt qua cả hai từ lúc nào! Joey đã vùn vụt phóng qua ở khoảnh khắc sát nút cuối cùng." },
      { "start": 65.0, "en": "In the end, Jim and I shared second place.", "ipa": "/ɪn ði ɛnd, dʒɪm ænd aɪ ʃɛrd ˈsɛkənd pleɪs/", vi: "Kết cục là Jim và tôi đành ngậm ngùi chia sẻ nhau vị trí á quân." }
    ]
  },
  {
    "day": 3,
    "title": "A Simple Man",
    image: "02 February/images/day_03.webp",
    audio: "02 February/audio/Track03.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mahatma Gandhi was a simple man who did great things. He led his country to independence. And the way he did it was amazing!", "ipa": "/məˈhɑːtmə ˈɡɑːndi wɒz a ˈsɪmpl mæn huː dɪd ɡreɪt θɪŋz. hiː lɛd hɪz ˈkʌntri tuː ˌɪndɪˈpɛndəns. ænd ðə weɪ hiː dɪd ɪt wɒz əˈmeɪzɪŋ/", vi: "Mahatma Gandhi là một con người vô cùng bình dị nhưng lại làm được những điều vĩ đại. Ông đã lãnh đạo đất nước đi đến độc lập, và phương thức ông chọn thật phi thường biết bao!" },
      { "start": 16.0, "en": "He did not believe in violence. He did not believe in fighting or in wars. He believed in talking things out. The Indian people agreed with him. In 1947, India became a free country.", "ipa": "/hiː dɪd nɒt bɪˈliːv ɪn ˈvaɪələns. hiː dɪd nɒt bɪˈliːv ɪn ˈfaɪtɪŋ ɔːr ɪn wɔːrz. hiː bɪˈliːvd ɪn ˈtɔːkɪŋ θɪŋz aʊt. ði ˈɪndiən ˈpiːpl əˈɡriːd wɪð hɪm. ɪn ˈnaɪˈtiːn ˈfɔːrti-ˈsɛvn, ˈɪndiə bɪˈkeɪm a friː ˈkʌntri/", vi: "Ông không tin vào bạo lực, chiến tranh hay sự xung đột, mà tin tưởng tuyệt đối vào việc đối thoại hòa bình để giải quyết mọi vấn đề. Người dân Ấn Độ đã đồng lòng ủng hộ ông. Vào năm 1947, Ấn Độ chính thức trở thành một quốc gia tự do." },
      { "start": 32.0, "en": "Gandhi lived a poor life by choice. He was a well-educated lawyer. He earned a good salary. But he saw the poor people around him and decided to help them.", "ipa": "/ˈɡɑːndi lɪvd a pʊr laɪf baɪ tʃɔɪs. hiː wɒz a wɛl-ˈɛdʒuˌkeɪtɪd ˈlɔɪər. hiː ɜːrnd a ɡʊd ˈsæləri. bʌt hiː sɔː ðə pʊr ˈpiːpl əˈraʊnd hɪm ænd dɪˈsaɪdɪd tuː hɛlp ðɛm/", vi: "Gandhi tự nguyện chọn một cuộc sống nghèo khó dù bản thân là một luật sư được đào tạo bài bản và có mức thu nhập cao. Chứng kiến nỗi khổ của những người nghèo xung quanh, ông quyết tâm đứng lên giúp đỡ họ." },
      { "start": 44.0, "en": "He learned how to live in the simplest way possible and still be healthy. He ate mostly fruit, goat's milk and olive oil. He wore only a simple rag as clothing. But people followed him. They could see that he was honest.", "ipa": "/hiː lɜːrnd haʊ tuː lɪv ɪn ðə ˈsɪmplɪst weɪ ˈpɒsəbl ænd stɪl biː ˈhɛlθi. hiː eɪt ˈmoʊstli fruːt, ɡoʊts mɪlk ænd ˈɒlɪv ɔɪl. hiː wɔːr ˈoʊnli a ˈsɪmpl ræɡ æz ˈkloʊðɪŋ. bʌt ˈpiːpl ˈfɒloʊd hɪm. ðeɪ kʊd siː ðæt hiː wɒz ˈɒnɪst/", vi: "Ông học cách duy trì lối sống tối giản nhất có thể mà vẫn đảm bảo sức khỏe. Khẩu phần ăn chủ yếu là trái cây, sữa dê và dầu ô-liu; trang phục chỉ là một mảnh vải thô sơ quấn quanh người. Thế nhưng nhân dân vẫn một lòng đi theo ông bởi họ cảm nhận rõ sự chân thành và chính trực từ con người ông." },
      { "start": 62.0, "en": "Gandhi spoke his native language. He also learned English. But he spoke English with an Irish accent. Why? His first English teacher was Irish!", "ipa": "/ˈɡɑːndi spoʊk hɪz ˈneɪtɪv ˈlæŋɡwɪdʒ. hiː ˈɔːlsoʊ lɜːrnd ˈɪŋɡlɪʃ. bʌt hiː spoʊk ˈɪŋɡlɪʃ wɪð ən ˈaɪrɪʃ ˈæksɛnt. waɪ? hɪz fɜːrst ˈɪŋɡlɪʃ ˈtiːtʃər wɒz ˈaɪrɪʃ!/", vi: "Bên cạnh tiếng mẹ đẻ, Gandhi còn học thêm tiếng Anh. Nhưng điều thú vị là ông nói tiếng Anh đặc giọng Ai-len. Tại sao vậy? Bởi vì người thầy dạy tiếng Anh đầu tiên của ông chính là một người gốc Ai-len!" }
    ]
  },
  {
    "day": 4,
    "title": "A Little Good Luck",
    image: "02 February/images/day_04.webp",
    audio: "02 February/audio/Track04.mp3",
    "sentences": [
      { "start": 4.8, "en": "An old lady lives on our street. She is very rich. One day, I saw her bending down, trying to pick something up off the ground. She was having a hard time.", "ipa": "/ən oʊld ˈleɪdi lɪvz ɒn ˈaʊər striːt. ʃiː ɪz ˈvɛri rɪtʃ. wʌn deɪ, aɪ sɔː hɜːr ˈbɛndɪŋ daʊn, ˈtraɪɪŋ tuː pɪk ˈsʌmθɪŋ ʌp ɔːf ðə ɡraʊnd. ʃiː wɒz ˈhævɪŋ a hɑːrd taɪm/", vi: "Có một cụ bà giàu có sống ở khu phố nhà tôi. Một hôm, tôi bắt gặp cụ đang lom khom nhặt thứ gì đó dưới đất và có vẻ khá vất vả." },
      { "start": 16.0, "en": "So, I came over and asked if I could help. She told me there was a penny on the ground. I wondered why a rich lady was worried about a penny.", "ipa": "/soʊ, aɪ keɪm ˈoʊvər ænd ɑːskt ɪf aɪ kʊd hɛlp. ʃiː toʊld miː ðɛr wɒz a ˈpɛni ɒn ðə ɡraʊnd. aɪ ˈwʌndərd waɪ a rɪtʃ ˈleɪdi wɒz ˈwʌrid əˈbaʊt a ˈpɛni/", vi: "Tôi liền tiến lại gần ngỏ ý giúp đỡ. Cụ bảo có một đồng xu xu rơi dưới đất. Tôi tự hỏi không hiểu sao một bà cụ giàu có thế lại bận tâm vì một đồng xu lẻ." },
      { "start": 26.0, "en": "'Oh, I don't need it,' she said. 'But it is good luck to find a penny!' I gave her the penny and walked away. Just then, the old lady called me back.", "ipa": "/oʊ, aɪ doʊnt niːd ɪt, ʃiː sɛd. bʌt ɪt ɪz ɡʊd lʌk tuː faɪnd a ˈpɛni! aɪ ɡeɪv hɜːr ðə ˈpɛni ænd wɔːkt əˈweɪ. dʒʌst ðɛn, ði oʊld ˈleɪdi kɔːld miː bæk/", vi: "'Ồ, ta đâu cần tiền lẻ đó,' cụ mỉm cười. 'Nhưng nhặt được đồng xu rơi sẽ mang lại nhiều may mắn lắm cháu ạ!' Tôi nhặt đồng xu đưa cho cụ rồi quay bước đi. Ngay lúc đó, cụ bà liền gọi giật tôi lại." },
      { "start": 41.0, "en": "She put the coin in my shirt pocket and said, 'It will bring you extra good luck because you helped me!'", "ipa": "/ʃiː pʊt ðə kɔɪn ɪn maɪ ʃɜːrt ˈpɒkɪt ænd sɛd, ɪt wɪl brɪŋ juː ˈɛkstrə ɡʊd lʌk bɪˈkəz juː hɛlpt miː!/", vi: "Cụ nhét thẳng đồng tiền vào túi áo ngực của tôi và bảo: 'Bởi vì cháu đã giúp đỡ ta nên nó sẽ đem lại cho cháu thật nhiều may mắn đặc biệt!'" },
      { "start": 51.0, "en": "At home, I pulled out the coin. I was surprised—she hadn't given me the penny. She had given me a dollar coin!", "ipa": "/æt hoʊm, aɪ pʊld aʊt ðə kɔɪn. aɪ wɒz sərˈpraɪzd—ʃiː ˈhædnt ˈɡɪvn miː ðə ˈpɛni. ʃiː hæd ˈɡɪvn miː a ˈdɒlər kɔɪn!/", vi: "Về đến nhà, tôi lấy đồng xu ra xem và há hốc mồm kinh ngạc — cụ không hề trả lại đồng xu một xu đơn thuần, mà đó chính là một đồng đô-la bằng kim loại có giá trị lớn!" }
    ]
  },
  {
    "day": 5,
    "title": "The Sky Is Falling",
    image: "02 February/images/day_05.webp",
    audio: "02 February/audio/Track05.mp3",
    "sentences": [
      { "start": 4.8, "en": "Chicken was resting under a tree when a nut fell and hit her on the head. She jumped up and yelled, 'The sky is falling! The sky is falling!'", "ipa": "/ˈtʃɪkɪn wɒz ˈrɛstɪŋ ˈʌndər a triː wɛn a nʌt fɛl ænd hɪt hɜːr ɒn ðə hɛd. ʃiː dʒʌmpt ʌp ænd jɛld, ðə skaɪ ɪz ˈfɔːlɪŋ! ðə skaɪ ɪz ˈfɔːlɪŋ!/", vi: "Cô Gà Mái đang nghỉ ngơi dưới gốc cây thì bất ngờ một quả hạt sồi rơi trúng đầu. Cô hoảng hốt chồm dậy hét toáng lên: 'Trời sập rồi! Trời sập mất thôi!'" },
      { "start": 14.0, "en": "She started to run. 'I must tell the king,' she cried. 'There is surely danger here.'", "ipa": "/ʃiː ˈstɑːrtɪd tuː rʌn. aɪ mʌst tɛl ðə kɪŋ, ʃiː kraɪd. ðɛr ɪz ˈʃʊrli ˈdeɪndʒər hɪər/", vi: "Cô cắm cổ chạy thục mạng và mếu máo khóc: 'Mình phải vào tâu bệ hạ ngay, ở đây nguy hiểm quá rồi.'" },
      { "start": 21.0, "en": "On the way, Chicken met Duck. 'The sky is falling!' she cried. 'How do you know?' asked Duck.", "ipa": "/ɒn ðə weɪ, ˈtʃɪkɪn mɛt dʌk. ðə skaɪ ɪz ˈfɔːlɪŋ!, ʃiː kraɪd. haʊ duː juː noʊ?, ɑːskt dʌk/", vi: "Dọc đường, Gà Mái gặp Vịt và hớt hải báo tin: 'Trời sập rồi!' Vịt ngơ ngác hỏi: 'Sao cậu biết chắc thế?'" },
      { "start": 29.0, "en": "'I saw it! A piece of it hit me on the head.' And so, the two set off to warn the king.", "ipa": "/aɪ sɔː ɪt! a piːs əv ɪt hɪt miː ɒn ðə hɛd. ænd soʊ, ðə tuː sɛt ɔːf tuː wɔːrn ðə kɪŋ/", vi: "'Tớ tận mắt thấy đấy chứ! Một mảng trời vừa rơi trúng đầu tớ đau điếng đây này.' Thế là cả hai cùng rủ nhau lên đường đi cảnh báo nhà vua." },
      { "start": 39.0, "en": "They met Rabbit and Turtle on the way. Chicken cried, 'The sky is falling!' She said that she had seen it with her own eyes. Rabbit and Turtle were scared too. So they joined the race to warn the king.", "ipa": "/ðeɪ mɛt ˈræbɪt ænd ˈtɜːrtl ɒn ðə weɪ. ˈtʃɪkɪn kraɪd, ðə skaɪ ɪz ˈfɔːlɪŋ! ʃiː sɛd ðæt ʃiː hæd siːn ɪt wɪð hɜːr oʊn aɪz. ˈræbɪt ænd ˈtɜːrtl wɜːr skɛrd tuː. soʊ ðeɪ dʒɔɪnd ðə reɪs tuː wɔːrn ðə kɪŋ/", vi: "Trên đường đi, họ tiếp tục chạm mặt Thỏ và Rùa. Gà Mái lại gào lên: 'Trời sập rồi!' và thề thốt rằng chính mắt cô đã nhìn thấy. Thỏ và Rùa nghe xong cũng hồn vía lên mây, thế là nhập hội chạy đua đi cấp báo nhà vua." },
      { "start": 54.0, "en": "Then, Fox showed up. 'What is the matter?' he asked. When he heard the answer, he smiled and said, 'You will have to let me show you the way. Follow me.'", "ipa": "/ðɛn, fɒks ʃoʊd ʌp. wɒt ɪz ðə ˈmætər?, hiː ɑːskt. wɛn hiː hɜːrd ðə ˈænsər, hiː smaɪld ænd sɛd, juː wɪl hæv tuː lɛt miː ʃoʊ juː ðə weɪ. ˈfɑːloʊ miː/", vi: "Đúng lúc đó, Cáo tinh ranh xuất hiện giả vờ quan tâm: 'Có chuyện gì mà náo động thế?' Khi nghe rõ đầu đuôi sự tình, Cáo mỉm cười thâm độc: 'Các ngươi không thể tìm nổi đường vào cung vua đâu để ta dẫn đường cho. Theo ta nào.'" },
      { "start": 68.0, "en": "The animals followed Fox into his home. All of a sudden, he locked the door and ate them all up!", "ipa": "/ðə ˈænɪmlz ˈfɒloʊd fɒks ˈɪntuː hɪz hoʊm. ɔːl əv a ˈsʌdn, hiː lɒkt ðə dɔːr ænd eɪt ðɛm ɔːl ʌp!/", vi: "Đám thú ngel ngơ tin theo và lũ lượt kéo vào hang ổ của Cáo. Chớp mắt một cái, Cáo khóa chặt cửa lại rồi nuốt chửng tất cả bọn chúng vào bụng!" }
    ]
  },
  {
    "day": 6,
    "title": "Get Some Air",
    image: "02 February/images/day_06.webp",
    audio: "02 February/audio/Track06.mp3",
    "sentences": [
      { "start": 4.8, "en": "You do it all the time. If you stopped doing it, you would be in trouble. What is it? It's breathing!", "ipa": "/juː duː ɪt ɔːl ðə taɪm. ɪf juː stɒpt ˈduːɪŋ ɪt, juː wʊd biː ɪn ˈtrʌbl. wɒt ɪz ɪt? ɪts ˈbriːðɪŋ!/", vi: "Bạn làm việc này suốt mọi khoảnh khắc trong đời. Nếu bỗng nhiên ngừng lại, bạn sẽ gặp nguy hiểm lớn. Đó là việc gì thế? Chính là hít thở!" },
      { "start": 13.0, "en": "Everyone needs air. We breathe without even thinking about it. It's automatic.", "ipa": "/ˈɛvriˌwʌn niːdz ɛər. wiː briːð wɪˈðaʊt ˈiːvn ˈθɪŋkɪŋ əˈbaʊt ɪt. ɪts ˌɔːtəˈmætɪk/", vi: "Bất kỳ ai cũng cần không khí để sống. Chúng ta hít thở một cách tự nhiên mà chẳng cần phải bận tâm suy nghĩ gì cả, hoàn toàn tự động." },
      { "start": 20.0, "en": "But how do we do it? Put your hand on your chest. Take a deep breath of air. Do you feel your chest getting bigger? Now let the air out. Feel how small it gets.", "ipa": "/bʌt haʊ duː wiː duː ɪt? pʊt jɔːr hænd ɒn jɔːr tʃɛst. teɪk a diːp brɛθ əv ɛər. duː juː fiːl jɔːr tʃɛst ˈɡɛtɪŋ ˈbɪɡər? naʊ lɛt ðə ɛər aʊt. fiːl haʊ smɔːl ɪt ɡɛts/", vi: "Nhưng cơ chế hoạt động ra sao? Hãy đặt tay lên lồng ngực và hít một hơi thật sâu. Bạn có cảm nhận lồng ngực mình đang phồng to lên không? Giờ hãy thở ra từ từ và cảm nhận nó xẹp xuống." },
      { "start": 36.0, "en": "Inside your chest are two large sacks. They are like big balloons. They are your lungs.", "ipa": "/ˈɪnˌsaɪd jɔːr tʃɛst ɑːr tuː lɑːrdʒ sæks. ðeɪ ɑːr laɪk bɪɡ bəˈluːnz. ðeɪ ɑːr jɔːr lʌŋz/", vi: "Bên trong khoang ngực chứa hai chiếc túi lớn trông giống hệt hai quả bóng bay căng phồng. Đó chính là đôi lá phổi của bạn." },
      { "start": 44.0, "en": "When you breathe in, your lungs fill up with air. Breathe out, and the air goes out too.", "ipa": "/wɛn juː briːð ɪn, jɔːr lʌŋz fɪl ʌp wɪð ɛər. briːð aʊt, ænd ðə ɛər ɡoʊz aʊt tuː/", vi: "Mỗi khi hít vào, phổi sẽ tràn ngập không khí; và khi thở ra, luồng không khí đó sẽ được đẩy ngược ra ngoài." },
      { "start": 53.0, "en": "Most people take 22,000 breaths of air each day! Your lungs work really hard. That's why you should take good care of your lungs. Do not smoke. Get exercise and breathe deeply.", "ipa": "/moʊst ˈpiːpl teɪk ˈtwɛnti-tuː ˈθaʊznd brɛðz əv ɛər iːtʃ deɪ! jɔːr lʌŋz wɜːrk ˈrɪəli hɑːrd. ðæts waɪ juː ʃʊd teɪk ɡʊd kɛər əv jɔːr lʌŋz. duː nɒt smoʊk. ɡɛt ˈɛksərˌsaɪz ænd briːð ˈdiːpli/", vi: "Hầu hết con người thực hiện tới 22.000 nhịp thở mỗi ngày! Phổi phải làm việc cực kỳ vất vả. Chính vì thế bạn cần bảo vệ phổi thật tốt: Không hút thuốc lá, siêng năng tập thể dục và duy trì thói quen hít thở sâu." },
      { "start": 69.0, "en": "One more thing... when you yawn, it means you're not getting enough air. Your lungs are telling you to take another big breath.", "ipa": "/wʌn mɔːr θɪŋ... wɛn juː jɔːn, ɪt miːnz jʊr nɒt ˈɡɛtɪŋ ɪˈnʌf ɛər. jɔːr lʌŋz ɑːr ˈtɛlɪŋ juː tuː teɪk əˈnʌðər bɪɡ brɛθ/", vi: "Thêm một điều thú vị nữa... khi bạn ngáp, điều đó báo hiệu cơ thể đang thiếu hụt oxy. Phổi đang phát tín hiệu nhắc nhở bạn cần phải hít một hơi thật sâu nữa đấy." }
    ]
  },
  {
    "day": 7,
    "title": "The Barber Shop",
    image: "02 February/images/day_07.webp",
    audio: "02 February/audio/Track07.mp3",
    "sentences": [
      { "start": 4.8, "en": "Jimmy is crying. He doesn't want to get his hair cut. He is afraid.", "ipa": "/ˈdʒɪmi ɪz ˈkraɪɪŋ. hiː ˈdʌznt wɒnt tuː ɡɛt hɪz hɛr kʌt. hiː ɪz əˈfreɪd/", vi: "Jimmy đang khóc thét lên vì nhất quyết không chịu đi cắt tóc. Cậu bé sợ hãi." },
      { "start": 10.0, "en": "It is his first time going to a barber. He does not like the sounds in a barber shop. There are many strange smells too.", "ipa": "/ɪt ɪz hɪz fɜːrst taɪm ˈɡoʊɪŋ tuː a ˈbɑːrbər. hiː dʌz nɒt laɪk ðə saʊndz ɪn a ˈbɑːrbər ʃɒp. ðɛr ɑːr ˈmɛni streɪndʒ smɛlz tuː/", vi: "Đây là lần đầu tiên cậu đặt chân đến tiệm hớt tóc. Cậu không thích những âm thanh vo ve lạ lẫm trong tiệm, và còn cả những mùi hương nồng khác lạ nữa." },
      { "start": 19.0, "en": "Mr. Howard, the barber, smiles. 'Hello Jimmy,' he says. 'So, this is your first haircut? I will take good care of you.'", "ipa": "/ˈmɪstər ˈhaʊərd, ðə ˈbɑːrbər, smaɪlz. hɛˈloʊ ˈdʒɪmi, hiː sɛz. soʊ, ðɪs ɪz jɔːr fɜːrst ˈhɛrˌkʌt? aɪ wɪl teɪk ɡʊd kɛər əv juː/", vi: "Bác Howard — người thợ cắt tóc — mỉm cười hiền hậu: 'Chào cháu Jimmy. Thế hóa ra đây là lần đầu tiên cháu đi cắt tóc à? Cứ yên tâm để bác chăm sóc cho nhé.'" },
      { "start": 29.0, "en": "He begins to cut. Jimmy closes his eyes. 'Please don't cut my ear!' he cries.", "ipa": "/hiː bɪˈɡɪnz tuː kʌt. ˈdʒɪmi ˈkloʊzɪz hɪz aɪz. pliːz doʊnt kʌt maɪ ɪər!, hiː kraɪz/", vi: "Bác thợ bắt đầu cầm kéo cắt tỉa. Jimmy nhắm tịt mắt lại và mếu máo: 'Xin bác đừng cắt nhầm tai cháu nhé!'" },
      { "start": 36.0, "en": "As he works, the barber talks to Jimmy. 'Do you know that people who have red hair like you have only 90,000 hairs on their head? People who have black hair have more than 110,000 hairs.'", "ipa": "/æz hiː wɜːrks, ðə ˈbɑːrbər tɔːks tuː ˈdʒɪmi. duː juː noʊ ðæt ˈpiːpl huː hæv rɛd hɛr laɪk juː hæv ˈoʊnli ˈnaɪnti ˈθaʊznd hɛrz ɒn ðɛər hɛd? ˈpiːpl huː hæv blæk hɛr hæv mɔːr ðæn wʌn ˈhʌndrəd tɛn ˈθaʊznd hɛrz/", vi: "Vừa thao tác đôi tay uyển chuyển, bác thợ vừa ân cần trò chuyện để dỗ dành cậu bé: 'Cháu có biết những người có mái tóc đỏ giống cháu chỉ sở hữu khoảng 90.000 sợi tóc trên đầu thôi không? Trong khi đó, người tóc đen có tới hơn 110.000 sợi lận đấy.'" },
      { "start": 54.0, "en": "'Hmmm, that is interesting,' thinks Jimmy.", "ipa": "/hʊm, ðæt ɪz ˈɪntrəstɪŋ, θɪŋks ˈdʒɪmi/", vi: "'Hừm, nghe cũng thú vị phết nhỉ,' Jimmy thầm nghĩ trong đầu." },
      { "start": 58.0, "en": "'The average hair lives about five and a half years. And we lose about 100 hairs a day,' says Mr. Howard.", "ipa": "/ði ˈævərɪdʒ hɛr lɪvz əʊˈbaʊt faɪv ænd a hæf jɪərz. ænd wiː luːz əˈbaʊt wʌn ˈhʌndrəd hɛrz a deɪ, sɛz ˈmɪstər ˈhaʊərd/", vi: "'Tuổi thọ trung bình của một sợi tóc kéo dài khoảng năm năm rưỡi, và mỗi ngày chúng ta rụng đi khoảng 100 sợi đấy cháu ạ,' bác Howard giải thích thêm." },
      { "start": 69.0, "en": "Jimmy likes the barber. In no time at all, the barber says, 'You can open your eyes now.' Jimmy cannot believe it. It didn't hurt. It was fun. And, he learned something interesting about hair.", "ipa": "/ˈdʒɪmi laɪks ðə ˈbɑːrbər. ɪn noʊ taɪm æt ɔːl, ðə ˈbɑːrbər sɛz, juː kæn ˈoʊpən jɔːr aɪz naʊ. ˈdʒɪmi ˈkænɒt bɪˈliːv ɪt. ɪt ˈdɪdnt hɜːrt. ɪt wɒz fʌn. ænd, hiː lɜːrnd ˈsʌmθɪŋ ˈɪntrəstɪŋ ə-baʊt hɛr/", vi: "Jimmy bỗng cảm thấy mến bác thợ lúc nào không hay. Chớp mắt một cái, bác thợ đã thông báo: 'Cháu mở mắt ra được rồi đấy.' Jimmy mở to mắt ngỡ ngàng chẳng dám tin. Hóa ra chẳng đau tẹo nào, lại còn rất vui nữa chứ, lại còn được lĩnh hội thêm bao nhiêu kiến thức thú vị về mái tóc." }
    ]
  },
  {
    "day": 8,
    "title": "The Twin Sisters",
    image: "02 February/images/day_08.webp",
    audio: "02 February/audio/Track08.mp3",
    "sentences": [
      { "start": 4.8, "en": "Becky and Sherry are twins. Becky loves dresses. Her sister Sherry loves sports.", "ipa": "/ˈbɛki ænd ˈʃɛri ɑːr twɪnz. ˈbɛki lʌvz ˈdrɛsɪz. hɜːr ˈsɪstər ˈʃɛri lʌvz spɔːrts/", vi: "Becky và Sherry là một cặp sinh đôi. Trong khi Becky cuồng những chiếc váy công chúa điệu đà, thì cô em Sherry lại có niềm đam mê đặc biệt với thể thao." },
      { "start": 13.0, "en": "One day, their mother said to them, 'Let's buy some new clothes for you.' So they went to the store together.", "ipa": "/wʌn deɪ, ðɛər ˈmʌðər sɛd toʊ ðɛm, lɛts baɪ sʌm nuː kloʊðz fɔːr juː. soʊ ðeɪ wɛnt tuː ðə stɔːr təˈɡɛðər/", vi: "Một hôm, mẹ bảo hai chị em: 'Hôm nay mẹ dẫn các con đi mua sắm quần áo mới nhé.' Thế là cả nhà cùng dắt nhau đến cửa hàng thời trang." },
      { "start": 23.0, "en": "Their mother chose some very nice dresses for them. Becky was happy. But Sherry was not. 'How can I play baseball in this?' she asked.", "ipa": "/ðɛər ˈmʌðər tʃoʊz sʌm ˈvɛri naɪs ˈdrɛsɪz fɔːr ðɛm. ˈbɛki wɒz ˈhæpi. bʌt ˈʃɛri wɒz nɒt. haʊ kæn aɪ pleɪ ˈbeɪsˌbɔːl ɪn ðɪs?, ʃiː ɑːskt/", vi: "Mẹ chọn cho hai chị em vài chiếc váy trông vô cùng xinh xắn. Becky vô cùng thích thú, nhưng Sherry thì ngược lại, mặt xị xuống: 'Mặc váy thế này thì sao con chơi bóng chày nổi hả mẹ?'" },
      { "start": 36.0, "en": "Sherry looked at a boy who was trying on a pair of shorts. Sherry's mom saw this. 'Well,' she said. 'Would you like some shorts instead?'", "ipa": "/ˈʃɛri lʊkt æt a bɔɪ huː wɒz ˈtraɪɪŋ ɒn a pɛr əv ʃɔːrts. ˈʃɛriz mɒm sɔː ðɪs. wɛl, ʃiː sɛd. wʊd juː laɪk sʌm ʃɔːrts ɪnˈstɛd?/", vi: "Sherry liếc nhìn sang cậu bé bên cạnh đang thử một chiếc quần đùi thể thao năng động. Mẹ nhận ra ánh mắt của con gái liền chủ động hỏi: 'Thế con có thích mặc quần đùi thay cho váy không nào?'" },
      { "start": 49.0, "en": "Sherry was very happy. 'That would be great!' she said. 'All right. I will buy a dress for Becky and shorts for Sherry,' Mom said.", "ipa": "/ˈʃɛri wɒz ˈvɛri ˈhæpi. ðæt wʊd biː ɡreɪt!, ʃiː sɛd. ɔːl raɪt. aɪ wɪl baɪ a drɛs fɔːr ˈbɛki ænd ʃɔːrts fɔːr ˈʃɛri, mɒm sɛd/", vi: "Sherry phấn khích nhảy cẫng lên: 'Tuyệt vời ông mặt trời ạ!' Mẹ mỉm cười chốt đơn: 'Được rồi, mẹ sẽ mua váy cho Becky và mua quần short cho Sherry nhé.'" },
      { "start": 62.0, "en": "'Sometimes I forget that although you two look the same, it doesn't mean you ARE the same,' laughed their mother.", "ipa": "/ˈsʌmˌtaɪmz aɪ fərˈɡɛt ðæt ɔːlˈðoʊ juː tuː lʊk ðə seɪm, ɪt ˈdʌznt miːn juː ɑːr ðə seɪm, lɑːft ðɛər ˈmʌðər/", vi: "Mẹ cười vang ôn tồn bảo: 'Nhiều lúc mẹ cứ hay quên mất rằng dù hai đứa sinh đôi bề ngoài y đúc nhau, nhưng điều đó đâu có nghĩa tính cách bên trong các con hoàn toàn giống hệt nhau đâu cơ chứ.'" }
    ]
  },
  {
    "day": 9,
    "title": "Gift of Hope",
    image: "02 February/images/day_09.webp",
    audio: "02 February/audio/Track09.mp3",
    "sentences": [
      { "start": 4.8, "en": "My mom always gives money to charities. We get more and more calls to our home. Letters are sent to Mom, all of them with good reasons to ask for donations.", "ipa": "/maɪ mɒm ˈɔːlweɪz ɡɪvz ˈmʌni tuː ˈtʃærətiz. wiː ɡɛt mɔːr ænd mɔːr kɔːlz tuː ˈaʊər hoʊm. ˈlɛtərz ɑːr sɛnt tuː mɒm, ɔːl əv ðɛm wɪð ɡʊd ˈriːznz tuː ɑːsk fɔːr doʊˈneɪʃnz/", vi: "Mẹ tôi vẫn thường xuyên quyên góp tiền cho các quỹ từ thiện. Điện thoại ở nhà chúng tôi ngày càng nhận nhiều cuộc gọi kêu gọi, và những lá thư tha thiết xin ủng hộ từ thiện cũng liên tục gửi đến tay mẹ." },
      { "start": 17.0, "en": "But Mom does not have enough money to meet all her urges to give. She has to consider her choices carefully.", "ipa": "/bʌt mɒm dʌz nɒt hæv ɪˈnʌf ˈmʌni tuː miːt ɔːl hɜːr ˈɜːrdʒɪz tuː ɡɪv. ʃiː hæz tuː kənˈsɪdər hɜːr ˈtʃɔɪsɪz ˈkɛrfəli/", vi: "Nhưng ngặt nỗi ngân sách của mẹ có hạn nên không thể đáp ứng hết mọi lời kêu gọi tốt đẹp ấy được. Mẹ buộc phải cân nhắc thật kỹ lưỡng các lựa chọn của mình." },
      { "start": 25.0, "en": "One day, Mom received a letter with the title Gift of Hope. The letter said, 'It's not money. It's hope. It's the gift of hope for families in poor countries.'", "ipa": "/wʌn deɪ, mɒm rɪˈsiːvd a ˈlɛtər wɪð ðə ˈtaɪtl ɡɪft əv hoʊp. ðə ˈlɛtər sɛd, ɪts nɒt ˈmʌni. ɪts hoʊp. ɪts ðə ɡɪft əv hoʊp fɔːr ˈfæməliːz ɪn pʊr ˈkʌntriz/", vi: "Một ngày nọ, mẹ nhận được một bức thư có tiêu đề đầy ý nghĩa: 'Món quà của niềm tin và hy vọng'. Trong thư đề dòng chữ: 'Đây không đơn thuần là tiền bạc, mà là hy vọng — món quà hy vọng thiết thực trao gửi đến những mảnh đời khó khăn ở các quốc gia nghèo đói.'" },
      { "start": 43.0, "en": "Mom continued reading the letter. 'With $19, you can give three hens to a family. The hens will lay eggs, which the family can then sell. With this money, the family can pay for their basic needs.'", "ipa": "/mɒm kənˈtɪnyuːd ˈriːdɪŋ ðə ˈlɛtər. wɪð ˈnaɪˈtiːn ˈdɒlərz, juː kæn ɡɪv θriː hɛnz tuː a ˈfæməli. ðə hɛnz wɪl leɪ ɛɡz, wɪtʃ ðə ˈfæməli kæn ðɛn sɛl. wɪð ðɪs ˈmʌni, ðə ˈfæməli kæn peɪ fɔːr ðɛər ˈbeɪsɪk niːdz/", vi: "Mẹ kiên nhẫn đọc tiếp nội dung: 'Chỉ với 19 đô-la, bạn có thể gửi tặng ba chú gà mái cho một hộ gia đình nghèo. Những cô gà này sẽ đẻ trứng để gia đình họ đem ra chợ bán lấy tiền trang trải các nhu cầu sinh hoạt thiết yếu hằng ngày.'" },
      { "start": 59.0, "en": "Mom smiled as she read. She made a plan to save money and send to this charity regularly.", "ipa": "/mɒm smaɪld æz ʃiː rɛd. ʃiː meɪd a plæn tuː seɪv ˈmʌni ænd sɛnd tuː ðɪs ˈtʃærəti ˈrɛɡjələrli/", vi: "Đọc đến đây, nét mặt mẹ rạng rỡ nở nụ cười ấm áp. Mẹ lập tức lên kế hoạch tiết kiệm tiền đều đặn để gửi ủng hộ cho chương trình ý nghĩa này." }
    ]
  },
  {
    "day": 10,
    "title": "Panic",
    image: "02 February/images/day_10.webp",
    audio: "02 February/audio/Track10.mp3",
    "sentences": [
      { "start": 4.8, "en": "It's always fun to learn about words. Sometimes, if we know where a word comes from, it is easier to understand its meaning. Take the word panic, for example.", "ipa": "/ɪts ˈɔːlweɪz fʌn tuː lɜːrn əˈbaʊt wɜːrdz. ˈsʌmˌtaɪmz, ɪf wiː noʊ wɛr a wɜːrld kʌmz frɒm, ɪt ɪz ˈiːziər tuː ˌʌndərˈstænd ɪts ˈmiːnɪŋ. teɪk ðə wɜːrd ˈpænɪk, fɔːr ɪɡˈzæmpl/", vi: "Khám phá nguồn gốc các từ vựng quả thực luôn là một hành trình thú vị. Đôi khi, nắm bắt được xuất xứ của một từ sẽ giúp chúng ta thấu hiểu ý nghĩa của nó sâu sắc hơn rất nhiều. Lấy từ 'panic' (hoảng loạn) làm ví dụ nhé." },
      { "start": 16.0, "en": "This popular English word comes from the Greek language. Many English words are based on this ancient language.", "ipa": "/ðɪs ˈpɒpjələr ˈɪŋɡlɪʃ wɜːrd kʌmz frɒm ðə ɡriːk ˈlæŋɡwɪdʒ. ˈmɛni ˈɪŋɡlɪʃ wɜːrdz ɑːr beɪst ɒn ðɪs ˈeɪnʃənt ˈlæŋɡwɪdʒ/", vi: "Từ tiếng Anh rất phổ biến này thực chất có xuất phát điểm từ tiếng Hy Lạp cổ đại. Rất nhiều từ vựng trong tiếng Anh hiện đại đều bắt nguồn từ kho tàng ngôn ngữ cổ xưa này." },
      { "start": 24.0, "en": "Pan was the Greek god of shepherds. He was half man, half animal. He liked to hunt and play music. He liked to walk through the woods, playing his special flute.", "ipa": "/pæn wɒz ðə ɡriːk ɡɒd əv ˈʃɛpərdz. hiː wɒz hæf mæn, hæf ˈænɪml. hiː laɪkt tuː hʌnt ænd pleɪ ˈmjuːzɪk. hiː laɪkt tuː wɔːk θruː ðə wʊdz, ˈpleɪɪŋ hɪz ˈspɛʃl fluːt/", vi: "Theo thần thoại, Pan chính là vị thần Hy Lạp cai quản các mục đồng và đồng cỏ. Ngài mang thân hình nửa người nửa thú, có sở thích đi săn và tấu nhạc, thường thong thả dạo bước trong những cánh rừng sâu và thổi cây sáo thần kỳ của mình." },
      { "start": 38.0, "en": "He often frightened people with his strange appearance. When people met him, they were so fearful that they did not know what to do. They were in a panic.", "ipa": "/hiː ˈɒfn ˈfraɪtnd ˈpiːpl wɪð hɪz streɪndʒ əˈpɪrəns. wɛn ˈpiːpl mɛt hɪm, ðeɪ wɜːr soʊ ˈfɪrfl ðæt ðeɪ dɪd nɒt noʊ wɒt tuː duː. ðeɪ wɜːr ɪn a ˈpænɪk/", vi: "Tuy nhiên, diện mạo kỳ dị của thần Pan lại thường khiến người phàm trần hoảng sợ khi bất ngờ chạm mặt. Sự kinh hoàng lớn đến mức họ mất hết lý trí, không biết phải xử lý ra sao — trạng thái đó gọi là hoảng loạn tột độ (panic)." },
      { "start": 50.0, "en": "This is the origin of the word panic. A person in a panic is frightened and confused. Often, people in a panic do foolish things.", "ipa": "/ðɪs ɪz ði ˈɔːrɪdʒɪn əv ðə wɜːrd ˈpænɪk. a ˈpɜːrsn ɪn a ˈpænɪk ɪz ˈfraɪtnd ænd kənˈfjuːzd. ˈɔːfn, ˈpiːpl ɪn a ˈpænɪk duː ˈfuːlɪʃ θɪŋz/", vi: "Đó chính là nguyên thủy ra đời của từ 'panic'. Một kẻ rơi vào trạng thái hoảng loạn thường cực kỳ sợ hãi, mất phương hướng và rất hay đưa ra những hành động dại dột, ngốc nghếch." }
    ]
  },
  {
    "day": 11,
    "title": "Living Things",
    image: "02 February/images/day_11.webp",
    audio: "02 February/audio/Track11.mp3",
    "sentences": [
      { "start": 4.8, "en": "A flower is a living thing. A tree is a living thing. Grass is a living thing too.", "ipa": "/a ˈflaʊər ɪz a ˈlɪvɪŋ θɪŋ. a triː ɪz a ˈlɪvɪŋ θɪŋ. ɡræs ɪz a ˈlɪvɪŋ θɪŋ tuː/", vi: "Một bông hoa là một sinh thể sống. Một cái cây là một sinh thể sống. Cỏ xanh cũng là một sinh thể sống." },
      { "start": 12.0, "en": "You are a living thing. I am a living thing. Bees, birds, dogs and cats—these are all living things.", "ipa": "/juː ɑːr a ˈlɪvɪŋ θɪŋ. aɪ æm a ˈlɪvɪŋ θɪŋ. biːz, bɜːrdz, dɔːɡz ænd kæts—ðiːz ɑːr ɔːl ˈlɪvɪŋ θɪŋz/", vi: "Bạn chính là một sinh thể sống, và tôi cũng vậy. Loài ong, chim chóc, chó và mèo — tất cả chúng đều thuộc về thế giới các sinh thể sống." },
      { "start": 21.0, "en": "What is a living thing? It is something that is alive. It starts out small. But it grows big and strong. The world is filled with many living things.", "ipa": "/wɒt ɪz a ˈlɪvɪŋ θɪŋ? ɪt ɪz ˈsʌmθɪŋ ðæt ɪz əˈlaɪv. ɪt stɑːrts aʊt smɔːl. bʌt ɪt ɡroʊz bɪɡ ænd strɒŋ. ðə wɜːrld ɪz fɪld wɪð ˈmɛni ˈlɪvɪŋ θɪŋz/", vi: "Vậy thế nào là một sinh thể sống? Đó là bất cứ thứ gì có sự sống. Khởi đầu chúng có thể rất bé nhỏ, nhưng sau đó sẽ lớn vụt lên to lớn và mạnh mẽ. Khắp nơi trên hành tinh này đều tràn ngập các sinh thể sống." },
      { "start": 36.0, "en": "All living things need food and water to grow. Think about yourself. When you are hungry, you need to eat. When a tree is hungry, it needs to eat too.", "ipa": "/ɔːl ˈlɪvɪŋ θɪŋz niːd fuːd ænd ˈwɔːtər tuː ɡroʊ. θɪŋk əˈbaʊt jɔːrˈsɛlf. wɛn juː ɑːr ˈhʌŋɡri, juː niːd tuː iːt. wɛn a triː ɪz ˈhʌŋɡri, ɪt niːdz tuː iːt tuː/", vi: "Mọi sinh vật sống đều cần có thức ăn và nguồn nước để sinh trưởng. Hãy ngẫm về chính bản thân bạn xem: Khi đói bụng bạn cần phải ăn, và khi một cái cây 'đói', nó cũng cần 'ăn' vậy." },
      { "start": 49.0, "en": "You eat fruit and vegetables. You eat meat and fish. But a tree gets its food from things in the ground.", "ipa": "/juː iːt fruːt ænd ˈvɛdʒtəblz. juː iːt miːt ænd fɪʃ. bʌt a triː ɡɛts ɪts fuːd frɒm θɪŋz ɪn ðə ɡraʊnd/", vi: "Bạn ăn trái cây, rau củ, thịt và cá. Trong khi đó, cái cây lại hấp thụ dưỡng chất nuôi cơ thể từ các khoáng chất nằm sâu trong lòng đất." },
      { "start": 59.0, "en": "You drink water when you are thirsty. A flower drinks water too. A tree gets its water from the ground.", "ipa": "/juː drɪŋk ˈwɔːtər wɛn juː ɑːr ˈθɜːrsti. a ˈflaʊər drɪŋks ˈwɔːtər tuː. a triː ɡɛts ɪts ˈwɔːtər frɒm ðə ɡraʊnd/", vi: "Bạn uống nước mỗi khi khát cổ; những bông hoa cũng 'uống' nước, và cái cây thì hút nguồn nước ngầm mát lành từ dưới đất lên." },
      { "start": 68.0, "en": "Take a look at all living things. We are the same. But we are all different too.", "ipa": "/teɪk a lʊk æt ɔːl ˈlɪvɪŋ θɪŋz. wiː ɑːr ðə seɪm. bʌt wiː ɑːr ɔːl ˈdɪfrənt tuː/", vi: "Nhìn ngắm toàn bộ thế giới sự sống mà xem, chúng ta có những điểm tương đồng kỳ lạ, nhưng đồng thời cũng vô cùng đa dạng và khác biệt." }
    ]
  },
  {
    "day": 12,
    "title": "Proud of My Past",
    image: "02 February/images/day_12.webp",
    audio: "02 February/audio/Track12.mp3",
    "sentences": [
      { "start": 4.8, "en": "My name is Leo. My family is from the Ojibway tribe. At first, I didn't think this was special. But that was before I learned how interesting my people are!", "ipa": "/maɪ neɪm ɪz ˈliːoʊ. maɪ ˈfæməli ɪz frɒm ði ˈoʊdʒɪˌbweɪ traɪb. æt fɜːrst, aɪ ˈdɪdnt θɪŋk ðɪs wɒz ˈspɛʃl. bʌt ðæt wɒz bɪˈfɔːr aɪ lɜːrnd haʊ ˈɪntrəstɪŋ maɪ ˈpiːpl ɑːr/", vi: "Tớ tên là Leo, và gia đình tớ thuộc về bộ tộc Ojibway bản địa. Ban đầu tớ cứ nghĩ điều đó chẳng có gì to tát cho đến khi tớ thực sự hiểu về bề dày lịch sử thú vị của cội nguồn dân tộc mình!" },
      { "start": 16.0, "en": "We lived in North America long before anyone else. Some people think we might have come from Asia thousands of years ago.", "ipa": "/wiː lɪvd ɪn nɔːrθ əˈmɛrɪkə lɒŋ bɪˈfɔːr ˈɛniˌwʌn ɛls. sʌm ˈpiːpl θɪŋk wiː maɪt hæv kʌm frɒm ˈeɪʒə ˈθaʊzndz əv jɪərz əˈɡoʊ/", vi: "Tổ tiên chúng tôi đã sinh sống trên mảnh đất Bắc Mỹ từ ngàn đời trước, từ rất lâu trước khi có sự xuất hiện của bất kỳ ai khác. Nhiều học giả cho rằng người dân tộc chúng tôi đã di cư từ châu Á sang đây từ hàng ngàn năm trước." },
      { "start": 26.0, "en": "In those days, my people lived off the land. We never did anything that would cause pollution. We respected the earth.", "ipa": "/ɪn ðoʊz deɪz, maɪ ˈpiːpl lɪvd ɒf ðə lænd. wiː ˈnɛvər dɪd ˈɛniˌθɪŋ ðæt wʊd kɔːz pəˈluːʃn. wiː rɪˈspɛktɪd ði ɜːrθ/", vi: "Vào những thời kỳ ấy, đồng bào chúng tôi sống hòa mình và nương tựa hoàn toàn vào thiên nhiên. Chúng tôi chưa bao giờ làm bất cứ điều gì gây hại hay ô nhiễm môi trường, bởi chúng tôi tôn trọng Trái Đất như mẹ hiền." },
      { "start": 37.0, "en": "We respected each other. We never wasted anything either. The water, the trees, and the land were very special to us.", "ipa": "/wiː rɪˈspɛktɪd iːtʃ ˈʌðər. wiː ˈnɛvər ˈweɪstɪd ˈɛniˌθɪŋ ˈiːðər. ðə ˈwɔːtər, ðə triːz, ænd ðə lænd wɜːr ˈvɛri ˈspɛʃl tuː ʌs/", vi: "Chúng tôi luôn đối xử với nhau bằng sự tôn trọng và tuyệt đối không lãng phí bất cứ tài nguyên nào. Nguồn nước, những rặng cây và mảnh đất này đều mang ý nghĩa thiêng liêng đối với chúng tôi." },
      { "start": 50.0, "en": "Today, the whole world thinks about these things. But we have always been like this. I am proud of the history of the Native people. I am also proud to be a Canadian.", "ipa": "/təˈdeɪ, ðə hoʊl wɜːrld θɪŋks əˈbaʊt ðiːz θɪŋz. bʌt wiː hæv ˈɔːlweɪz biːn laɪk ðɪs. aɪ æm praʊd əv ðə ˈhɪstəri əv ðə ˈneɪtɪv ˈpiːpl. aɪ æm ˈɔːlsoʊ praʊd tuː biː a kəˈneɪdiən/", vi: "Giờ đây, toàn nhân loại đang dần thức tỉnh và quan tâm đến các vấn đề bảo vệ môi trường ấy, nhưng đối với chúng tôi, lối sống đó đã chảy trong huyết quản từ muôn đời nay. Tớ vô cùng tự hào về lịch sử hào hùng của người bản địa, và cũng tự hào khi được là một công dân Canada." }
    ]
  },
  {
    "day": 13,
    "title": "Don't Cry, Mom",
    image: "02 February/images/day_13.webp",
    audio: "02 February/audio/Track13.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, when I walked into the kitchen, I saw my mom crying. 'Mommy, what happened? Why are you sad?' I asked.", "ipa": "/wʌn deɪ, wɛn aɪ wɔːkt ˈɪntuː ðə ˈkɪtʃɪn, aɪ sɔː maɪ mɒm ˈkraɪɪŋ. ˈmɑːmi, wɒt ˈhæpənd? waɪ ɑːr juː sæd?, aɪ ɑːskt/", vi: "Có một hôm bước vào phòng bếp, tôi giật mình thấy mẹ đang rơm rớm nước mắt. 'Mẹ ơi, có chuyện gì xảy ra thế ạ? Sao mẹ buồn vậy?' tôi lo lắng hỏi." },
      { "start": 13.0, "en": "Mom smiled at my concern. 'I have tears in my eyes,' she said. 'But I am not sad. I am cutting onions, as you can see.'", "ipa": "/mɒm smaɪld æt maɪ kənˈsɜːrn. aɪ hæv tɪərz ɪn maɪ aɪz, ʃiː sɛd. bʌt aɪ æm nɒt sæd. aɪ æm ˈkʌtɪŋ ˈʌnjənz, æz juː kæn siː/", vi: "Mẹ mỉm cười trấn an tôi: 'Mẹ đang đọng nước mắt thật con ạ, nhưng mẹ không hề buồn đâu. Con thấy đấy, mẹ đang thái hành tây mà.'" },
      { "start": 23.0, "en": "'Onions have a strong chemical that hurts our eyes. But don't worry. Our body is amazing. It senses the danger of this chemical and sends tears to our eyes to get rid of it. Tears protect our eyes from danger.'", "ipa": "/ˈʌnjənz hæv a strɒŋ ˈkɛmɪkl ðæt hɜːrts ˈaʊər aɪz. bʌt doʊnt ˈwʌri. ˈaʊər ˈbɒdi ɪz əˈmeɪzɪŋ. ɪt sɛnsɪz ðə ˈdeɪndʒər əv ðɪs ˈkɛmɪkl ænd sɛndz tɪərz tuː ˈaʊər aɪz tuː ɡɛt rɪd əv ɪt. tɪərz prəˈtɛkt ˈaʊər aɪz frɒm ˈdeɪndʒər/", vi: "'Trong củ hành tây có chứa một loại hợp chất hóa học đặc biệt gây kích ứng mắt. Nhưng con đừng lo, cơ thể chúng ta vô cùng kỳ diệu; nó lập tức nhận diện được mối nguy hiểm và kích hoạt tuyến lệ tiết ra nước mắt để rửa trôi chất cay đó đi. Nước mắt chính là cơ chế tự vệ giúp bảo vệ đôi mắt khỏi tổn thương đấy con yêu ạ.'" },
      { "start": 44.0, "en": "That is interesting! I learned something else too. All animals cry to protect their eyes. But humans are the only animals that cry when they are sad.", "ipa": "/ðæt ɪz ˈɪntrəstɪŋ! aɪ lɜːrnd ˈsʌmθɪŋ ɛls tuː. ɔːl ˈænɪmlz kraɪ tuː prə_tɛkt ðɛər aɪz. bʌt ˈhjuːmənz ɑːr ði ˈoʊnli ˈænɪmlz ðæt kraɪ wɛn ðeɪ ɑːr sæd/", vi: "Thật là một kiến thức sinh học tuyệt vời! Tôi còn được biết thêm rằng tất cả các loài động vật đều biết khóc để bảo vệ mắt, nhưng chỉ có con người mới rơi nước mắt vì cảm xúc buồn bã trong tâm hồn." },
      { "start": 57.0, "en": "I love learning about my body. It all seems to work perfectly! The more I learn about it, the more amazed I am.", "ipa": "/aɪ lʌv ˈlɜːrnɪŋ əˈbaʊt maɪ ˈbɒdi. ɪt ɔːl siːmz tuː wɜːrk ˈpɜːrfɪktli! ðə mɔːr aɪ lɜːrn əˈbaʊt ɪt, ðə mɔːr əˈmeɪzd aɪ æm/", vi: "Tôi cực kỳ thích thú khi được khám phá những bí ẩn về cơ thể mình. Mọi cơ quan đều vận hành hoàn hảo đến khó tin! Càng tìm hiểu sâu, tôi lại càng cảm thấy kinh ngạc trước tạo hóa." }
    ]
  },
  {
    "day": 14,
    "title": "A Day to Say 'I Like You!'",
    image: "02 February/images/day_14.webp",
    audio: "02 February/audio/Track14.mp3",
    "sentences": [
      { "start": 4.8, "en": "Every year, on February 14, people around the world say, 'I like you!' in a special way.", "ipa": "/ˈɛvri jɪər, ɒn ˈfɛbruɛri ˈfɔːrˈtiːnθ, ˈpiːpl əˈraʊnd ðə wɜːrld seɪ, aɪ laɪk juː! ɪn a ˈspɛʃl weɪ/", vi: "Hằng năm, cứ đến ngày 14 tháng Hai, mọi người trên khắp hành tinh lại chọn một cách thức thật đặc biệt để thì thầm câu nói: 'Tớ mến cậu lắm!'" },
      { "start": 13.0, "en": "They send or give a card to a person they really like. The day is called Valentine's Day. It is very popular in the United States, Canada and England.", "ipa": "/ðeɪ sɛnd ɔːr ɡɪv a kɑːrd tuː a ˈpɜːrsn ðeɪ ˈrɪəli laɪk. ðə deɪ ɪz kɔːld ˈvæləntaɪnz deɪ. ɪt ɪz ˈvɛri ˈpɒpjələr ɪn ðə jʊˈnaɪtɪd steɪts, ˈkænədə ænd ˈɪŋɡlənd/", vi: "Họ gửi tặng những tấm thiệp xinh xắn cho những người mà họ yêu mến. Ngày này được gọi là lễ Valentine. Nó rất phổ biến ở các nước như Mỹ, Canada và Anh Quốc." },
      { "start": 26.0, "en": "In many schools, kids spend part of Valentine's Day making cards. They give them to friends, teachers and special people.", "ipa": "/ɪn ˈmɛni skuːlz, kɪdz spɛnd pɑːrt əv ˈvæləntaɪnz deɪ ˈmeɪkɪŋ kɑːrdz. ðeɪ ɡɪv ðɛm tuː frɛndz, ˈtiːtʃərz ænd ˈspɛʃl ˈpiːpl/", vi: "Ở rất nhiều trường học, các bạn nhỏ thường dành một phần thời gian trong ngày Valentine để tự tay làm thiệp thủ công rồi trao tận tay bạn bè, thầy cô cùng những người đặc biệt." },
      { "start": 37.0, "en": "No one knows for sure why this special day began. It takes its name from a Christian saint, called Saint Valentine. But not much is known about him.", "ipa": "/noʊ wʌn noʊz fɔːr ʃʊr waɪ ðɪs ˈspɛʃl deɪ bɪˈɡæn. ɪt teɪks ɪts neɪm frɒm a ˈkrɪstʃən seɪnt, kɔːld seɪnt ˈvæləntaɪn. bʌt nɒt mʌtʃ ɪz noʊn əˈbaʊt hɪm/", vi: "Không ai thực sự biết chắc chắn nguồn gốc chính xác của ngày lễ đặc biệt này bắt đầu từ đâu. Nó được đặt theo tên của một vị thánh Thiên Chúa giáo tên là Saint Valentine, dù tiểu sử về ngài không còn lưu lại quá nhiều." },
      { "start": 50.0, "en": "It's always a good thing to stop and tell someone how much you like them on any day of the year. But it's kind of nice to know that on February 14, millions of people are doing the same thing you are.", "ipa": "/ɪts ˈɔːlweɪz a ɡʊd θɪŋ tuː stɒp ænd tɛl ˈsʌmwʌn haʊ mʌtʃ juː laɪk ðɛm ɒn ˈɛni deɪ əv ðə jɪər. bʌt ɪts kaɪnd əv naɪs tuː noʊ ðæt ɒn ˈfɛbruɛri ˈfɔːrˈtiːnθ, ˈmɪljənz əv ˈpiːpl ɑːr ˈduːɪŋ ðə seɪm θɪŋ juː ɑːr/", vi: "Tất nhiên việc dừng lại một nhịp và bày tỏ tình cảm với ai đó là điều tuyệt vời có thể làm vào bất cứ ngày nào trong năm, nhưng thật ấm áp biết bao khi biết rằng vào đúng ngày 14 tháng Hai, hàng triệu con người trên thế giới cũng đang đồng điệu chung nhịp đập yêu thương giống như bạn." }
    ]
  },
  {
    "day": 15,
    "title": "Getting Eyeglasses",
    image: "02 February/images/day_15.webp",
    audio: "02 February/audio/Track15.mp3",
    "sentences": [
      { "start": 4.8, "en": "Little Freddie was having trouble in school. His mom was worried. So she took Freddie to see a doctor.", "ipa": "/ˈlɪtl ˈfrɛdi wɒz ˈhævɪŋ ˈtrʌbl ɪn skuːl. hɪz mɒm wɒz ˈwʌrid. soʊ ʃiː tʊk ˈfrɛdi tuː siː a ˈdɒktər/", vi: "Cậu bé Freddie gặp khá nhiều rắc rối trong việc học tập ở trường khiến mẹ vô cùng lo lắng. Thế là mẹ quyết định đưa Freddie đến phòng khám bác sĩ nhãn khoa." },
      { "start": 13.0, "en": "Dr. Adams gave him an eye test. He told Freddie that he did not see as well as the other kids.", "ipa": "/ˈdɒktər ˈædəmz ɡeɪv hɪm ən aɪ tɛst. hiː toʊld ˈfrɛdi ðæt hiː dɪd nɒt siː æz wɛl æz ði ˈʌðər kɪdz/", vi: "Bác sĩ Adams tiến hành đo thị lực và thông báo rằng thị lực của Freddie kém hơn so với các bạn cùng trang lứa." },
      { "start": 21.0, "en": "'Your eyes are weak,' said Dr. Adams. 'You have trouble seeing what the teacher writes on the board. That's why you need to get eyeglasses.'", "ipa": "/jɔːr aɪz ɑːr wiːk, sɛd ˈdɒktər ˈædəmz. juː hæv ˈtrʌbl ˈsiːɪŋ wɒt ðə ˈtiːtʃər raɪts ɒn ðə bɔːrd. ðæts waɪ juː niːd tuː ɡɛt ˈaɪˌɡlæsɪz/", vi: "'Đôi mắt của cháu đang bị suy giảm thị lực,' bác sĩ Adams giải thích. 'Cháu gặp khó khăn trong việc nhìn rõ chữ cô giáo viết trên bảng. Đó chính là lý do cháu cần phải đeo kính cận.'" },
      { "start": 34.0, "en": "'Oh no!' Freddie cried. 'I don't want to wear glasses. The kids will make fun of me.' His mom said, 'Don't you want to do better in school?'", "ipa": "/oʊ noʊ! ˈfrɛdi kraɪd. aɪ doʊnt wɒnt tuː wɛr ˈɡlæsɪz. ðə kɪdz wɪl meɪk fʌn əv miː. hɪz mɒm sɛd, doʊnt juː wɒnt tuː duː ˈbɛtər ɪn skuːl?/", vi: "'Ôi không!' Freddie mếu máo kêu lên. 'Con không thích đeo kính đâu, các bạn sẽ trêu chọc con mất.' Mẹ ân cần khuyên nhủ: 'Thế con không muốn kết quả học tập ở trường tốt hơn sao?'" },
      { "start": 46.0, "en": "The doctor said, 'You have a problem with your eyesight. Wearing glasses will help prevent it from getting worse. Some people can even go blind if they don't take care of this problem. I'm sure your friends will understand.'", "ipa": "/ðə ˈdɒktər sɛd, juː hæv a ˈprɒbləm wɪð jɔːr ˈaɪˌsaɪt. ˈwɛərɪŋ ˈɡlæsɪz wɪl hɛlp prɪˈvɛnt ɪt frɒm ˈɡɛtɪŋ wɜːrs. sʌm ˈpiːpl kæn ˈiːvn ɡoʊ blaɪnd ɪf ðeɪ doʊnt teɪk kɛər əv ðɪs ˈprɒbləm. aɪm ʃʊr jɔːr frɛndz wɪl ˌʌndərˈstænd/", vi: "Bác sĩ tiếp lời: 'Cháu đang gặp vấn đề thực sự về thị lực. Việc đeo kính sẽ giúp ngăn chặn tình trạng này chuyển biến nặng hơn. Thậm chí nhiều người có thể bị mù vĩnh viễn nếu xem nhẹ việc điều trị sớm. Bác tin chắc bạn bè ở lớp sẽ thông cảm cho cháu thôi.'" },
      { "start": 64.0, "en": "That night, Freddie decided that it was better to wear glasses than to grow up and become blind.", "ipa": "/ðæt naɪt, ˈfrɛdi dɪˈsaɪdɪd ðæt ɪt wɒz ˈbɛtər tuː wɛr ˈɡlæsɪz ðæn tuː ɡroʊ ʌp ænd bɪˈkʌm blaɪnd/", vi: "Đêm hôm đó, sau khi suy nghĩ kỹ càng, Freddie nhận ra việc đeo kính chắc chắn tốt hơn nhiều so với việc để bản thân bị mù lòa khi lớn lên." }
    ]
  },
  {
    "day": 16,
    "title": "Help the Whales",
    image: "02 February/images/day_16.webp",
    audio: "02 February/audio/Track16.mp3",
    "sentences": [
      { "start": 4.8, "en": "Whales are big animals—really BIG! Some whales are bigger than elephants. One kind of whale is actually the biggest animal in the world.", "ipa": "/weɪlz ɑːr bɪɡ ˈænɪmlz—ˈrɪəli bɪɡ! sʌm weɪlz ɑːr ˈbɪɡər ðæn ˈɛlɪfənts. wʌn kaɪnd əv weɪl ɪz ˈæktʃuəli ðə ˈbɪɡɪst ˈænɪml ɪn ðə wɜːrld/", vi: "Cá voi là những sinh vật vô cùng khổng lồ — thực sự KHỔNG LỒ! Thậm chí vài loài cá voi còn to lớn hơn cả loài voi trên cạn. Và có một loài cá voi giữ kỷ lục là động vật lớn nhất trên hành tinh." },
      { "start": 16.0, "en": "Whales swim in water. Fish swim in water too. But whales are not fish. Fish can breathe under water. But, whales have to come up to the surface of the water to breathe.", "ipa": "/weɪlz swɪm ɪn ˈwɔːtər. fɪʃ swɪm ɪn ˈwɔːtər tuː. bʌt weɪlz ɑːr nɒt fɪʃ. fɪʃ kæn briːð ˈʌndər ˈwɔːtər. bʌt, weɪlz hæv tuː kʌm ʌp tuː ðə ˈsɜːrfɪs əv ðə ˈwɔːtər tuː briːð/", vi: "Cá voi bơi lội dưới nước, loài cá cũng bơi dưới nước. Nhưng cá voi không phải là cá. Loài cá có thể hô hấp trực tiếp dưới nước, trong khi cá voi bắt buộc phải trồi lên mặt nước để hít thở không khí." },
      { "start": 30.0, "en": "Whales can talk to each other. They have a special language. People cannot understand whale talk. But whales understand each other.", "ipa": "/weɪlz kæn tɔːk tuː iːtʃ ˈʌðər. ðeɪ hæv a ˈspɛʃl ˈlæŋɡwɪdʒ. ˈpiːpl ˈkænɒt ˌʌndərˈstænd weɪl tɔːk. bʌt weɪlz ˌʌndərˈstænd iːtʃ ˈʌðər/", vi: "Cá voi có khả năng giao tiếp và trò chuyện với nhau bằng một thứ ngôn ngữ riêng biệt. Con người chúng ta không thể tài nào hiểu nổi tiếng cá voi, nhưng đồng loại của chúng thì hiểu nhau rất rõ." },
      { "start": 41.0, "en": "Today, people are trying to help the whales. There are not many places left in the world where whales can live safely. The oceans are dirty. There are many bad things in the oceans. Whales are getting sick. That's why people are helping them.", "ipa": "/təˈdeɪ, ˈpiːpl ɑːr ˈtraɪɪŋ tuː hɛlp ðə weɪlz. ðɛr ɑːr nɒt ˈmɛni pleɪsɪz lɛft ɪn ðə wɜːrld wɛr weɪlz kæn lɪv ˈseɪfli. ði ˈoʊʃnz ɑːr ˈdɜːrti. ðɛr ɑːr ˈmɛni bæd θɪŋz ɪn ði ˈoʊʃnz. weɪlz ɑːr ˈɡɛtɪŋ sɪk. ðæts waɪ ˈpiːpl ɑːr ˈhɛlpɪŋ ðɛm/", vi: "Ngày nay, nhân loại đang nỗ lực hết sức để giải cứu loài cá voi. Môi trường sống an toàn cho chúng đang ngày một thu hẹp do các đại dương đã bị ô nhiễm nặng nề bởi rác thải độc hại khiến cá voi nhiễm bệnh. Đó là lý do vì sao chúng ta cần phải chung tay bảo vệ chúng." },
      { "start": 61.0, "en": "What can you do to help the whales? Tell people how special whales are. Tell people not to put garbage in the oceans.", "ipa": "/wɒt kæn juː duː tuː hɛlp ðə weɪlz? tɛl ˈpiːpl haʊ ˈspɛʃl weɪlz ɑːr. tɛl ˈpiːpl nɒt tuː pʊt ˈɡɑːrbɪdʒ ɪn ði ˈoʊʃnz/", vi: "Vậy bạn có thể làm gì để giúp đỡ cá voi? Hãy lan tỏa cho mọi người biết loài cá voi kỳ diệu thế nào, và nhắc nhở nhau đừng bao giờ vứt rác bừa bãi xuống lòng đại dương xanh." }
    ]
  },
  {
    "day": 17,
    "title": "A Visit with Dr. Mom",
    image: "02 February/images/day_17.webp",
    audio: "02 February/audio/Track17.mp3",
    "sentences": [
      { "start": 4.8, "en": "Emmy dropped her teddy bear in the yard. 'Oh, his leg is broken,' cried Emmy.", "ipa": "/ˈɛmi drɒpt hɜːr ˈtɛdi bɛr ɪn ðə jɑːrd. oʊ, hɪz lɛɡ ɪz ˈbroʊkn, kraɪd ˈɛmi/", vi: "Bé Emmy vô tình đánh rơi chú gấu bông yêu quý xuống sân vườn. 'Ôi không, chân gấu bị rách tuột mất rồi,' Emmy mếu máo khóc." },
      { "start": 12.0, "en": "'I think you need a doctor,' Emmy told him. The teddy bear seemed scared. He stared at Emmy.", "ipa": "/aɪ θɪŋk juː niːd a ˈdɒktər, ˈɛmi toʊld hɪm. ðə ˈtɛdi bɛr siːmd skɛrd. hiː stɛrd æt ˈɛmi/", vi: "'Chắc cậu phải đi khám bác sĩ ngay thôi,' Emmy thì thầm với chú gấu. Chú gấu bông trông có vẻ sợ sệt, ngước đôi mắt tròn xoe nhìn cô chủ nhỏ." },
      { "start": 20.0, "en": "'Don't worry,' Emmy said. 'I'll take you to Dr. Mom. It won't hurt a bit.'", "ipa": "/doʊnt ˈwʌri, ˈɛmi sɛd. aɪl teɪk juː tuː ˈdɒktər mɒm. ɪt woʊnt hɜːrt a bɪt/", vi: "'Đừng lo lắng nhé,' Emmy an ủi. 'Tớ sẽ đưa cậu đến chỗ Bác sĩ Mẹ. Sẽ không đau chút nào đâu.'" },
      { "start": 27.0, "en": "Emmy told the teddy bear what would happen. 'First, we'll go inside. Then, we'll read stories while we wait for Dr. Mom to see us. When Dr. Mom is ready, she'll look at your leg and fix it.'", "ipa": "/ˈɛmi toʊld ðə ˈtɛdi bɛr wɒt wʊd ˈhæpən. fɜːrst, wiːl ɡoʊ ɪnˈsaɪd. ðɛn, wiːl riːd ˈstɔːriz waɪl wiː weɪt fɔːr ˈdɒktər mɒm tuː siː ʌs. wɛn ˈdɒktər mɒm ɪz ˈrɛdi, ʃiːl lʊk æt jɔːr lɛɡ ænd fɪks ɪt/", vi: "Emmy tận tình trấn an gấu bông bằng cách vẽ ra quy trình khám bệnh: 'Đầu tiên chúng ta sẽ vào nhà, ngồi đọc truyện tranh trong lúc chờ đến lượt bác sĩ Mẹ gọi tên. Khi bác sĩ Mẹ rảnh, người sẽ khám chân và chữa lành cho cậu.'" },
      { "start": 43.0, "en": "Emmy told him that she would hold his hand. He wasn't scared anymore. So, Emmy carried her teddy bear inside. Then she read him a story.", "ipa": "/ˈɛmi toʊld hɪm ðæt ʃiː wʊd hoʊld hɪz hænd. hiː ˈwɒznt skɛrd ˈɛniˌmɔːr. soʊ, ˈɛmi ˈkærid hɜːr ˈtɛdi bɛr ɪnˈsaɪd. ðɛn ʃiː rɛd hɪm a ˈstɔːri/", vi: "Emmy hứa sẽ nắm chặt tay gấu bông suốt buổi, thế là chú ta hết sợ ngay lập tức. Cô bé ôm gấu vào nhà và bắt đầu đọc những câu chuyện cổ tích vui nhộn cho gấu nghe." },
      { "start": 56.0, "en": "Finally, Dr. Mom was ready to see them. She fixed the teddy bear's leg and said, 'He's as good as new now.' Emmy gave her teddy bear a big hug. He was brave while Dr. Mom fixed his leg!", "ipa": "/ˈfaɪnəli, ˈdɒktər mɒm wɒz ˈrɛdi tuː siː ðɛm. ʃiː fɪkst ðə ˈtɛdi bɛrz lɛɡ ænd sɛd, hiːz æz ɡʊd æz nuː naʊ. ˈɛmi ɡeɪv hɜːr ˈtɛdi bɛr a bɪɡ hʌɡ. hiː wɒz breɪv waɪl ˈdɒktər mɒm fɪkst hɪz lɛɡ/", vi: "Cuối cùng thì bác sĩ Mẹ cũng sẵn sàng tiếp đón bệnh nhân đặc biệt. Mẹ khéo léo khâu vá lại chiếc chân bị rách và mỉm cười: 'Xong rồi đấy, em gấu lại lành lặn như mới rồi.' Emmy ôm chầm lấy chú gấu bông và khen ngợi vì chú đã rất dũng cảm trong suốt ca phẫu thuật!" }
    ]
  },
  {
    "day": 18,
    "title": "A Star for My Birthday",
    image: "02 February/images/day_18.webp",
    audio: "02 February/audio/Track18.mp3",
    "sentences": [
      { "start": 4.8, "en": "It was my birthday. My whole family went horseback riding. It's easy for us because we live on a farm in the countryside.", "ipa": "/ɪt wɒz maɪ ˈbɜːrθdeɪ. maɪ hoʊl ˈfæməli wɛnt ˈhʊrsˌbæk ˈraɪdɪŋ. ɪts ˈiːzi fɔːr ʌs bɪˈkəz wiː lɪv ɒn a fɑːrm ɪn ðə ˈkʌntriˌsaɪd/", vi: "Đó là ngày sinh nhật tôi. Cả gia đình đã cùng nhau tổ chức đi cưỡi ngựa dã ngoại. Việc này với chúng tôi vô cùng dễ dàng vì nhà tôi sở hữu một trang trại rộng lớn ở vùng quê thanh bình." },
      { "start": 15.0, "en": "That night, we sat around a campfire and looked at the stars. My mother brought out a cake with candles on it.", "ipa": "/ðæt naɪt, wiː sæt əˈraʊnd a ˈkæmpˌfaɪr ænd lʊkt æt ðə stɑːrz. maɪ ˈmʌðər brɔːt aʊt a keɪk wɪð ˈkændlz ɒn ɪt/", vi: "Đêm xuống, chúng tôi quây quần bên đống lửa trại ấm cúng và ngắm nhìn bầu trời đầy sao lấp lánh. Mẹ mang ra một chiếc bánh sinh nhật cắm đầy nến lung linh." },
      { "start": 25.0, "en": "'Make a wish,' she said. I wished for my own horse. Just as I blew out the candle, a bright light filled the sky. It was a shooting star. It soared across the sky.", "ipa": "/meɪk a wɪʃ, ʃiː sɛd. aɪ wɪʃt fɔːr maɪ oʊn hɔːrs. dʒʌst æz aɪ bluː aʊt ðə ˈkændl, a braɪt laɪt fɪld ðə skaɪ. ɪt wɒz a ˈʃuːtɪŋ stɑːr. ɪt sɔːrd əˈkrɒs ðə skaɪ/", vi: "'Con hãy nhắm mắt ước một điều đi nào,' mẹ dịu dàng bảo. Tôi ước ao sẽ có một chú ngựa thuộc về riêng mình. Vừa lúc tôi thổi tắt nến, một vệt sáng chói lọi bỗng rực sáng cả bầu trời — đó là một ngôi sao băng đang vút bay băng qua dải ngân hà." },
      { "start": 41.0, "en": "My mom said a shooting star is a very small rock. It moves so fast that it makes the air around it catch fire. I'm sure she's right, but I think it's a sign that my wish will come true. If it does, I think I'll name my horse Star.", "ipa": "/maɪ mɒm sɛd a ˈʃuːtɪŋ stɑːr ɪz a ˈvɛri smɔːl rɒk. ɪt muːvz soʊ fɑːst ðæt ɪt meɪks ðə ɛər əˈraʊnd ɪt kætʃ ˈfaɪər. aɪm ʃʊr ʃiːz raɪt, bʌt aɪ θɪŋk ɪts a saɪn ðæt maɪ wɪʃ wɪl kʌm truː. ɪf ɪt dʌz, aɪ θɪŋk aɪl neɪm maɪ hɔːrs stɑːr/", vi: "Mẹ giải thích rằng sao băng thực chất chỉ là một mảnh thiên thạch nhỏ di chuyển với vận tốc cực nhanh làm ma sát bốc cháy trong khí quyển. Tôi biết mẹ nói chuẩn khoa học rồi, nhưng trong thâm tâm tôi vẫn tin đó là điềm lành báo hiệu ước nguyện sinh nhật của mình sẽ thành hiện thực. Nếu điều đó xảy ra, chắc chắn tôi sẽ đặt tên chú ngựa tương lai của mình là Star (Ngôi Sao)." }
    ]
  },
  {
    "day": 19,
    "title": "Is My Sister a Foreigner?",
    image: "02 February/images/day_19.webp",
    audio: "02 February/audio/Track19.mp3",
    "sentences": [
      { "start": 4.8, "en": "Erin lives with her parents in Canada. Both of her parents are Chinese. But Erin was born in Canada. Her friends in kindergarten are different colours.", "ipa": "/ˈɛrɪn lɪvz wɪð hɜːr ˈpɛrənts ɪn ˈkænədə. boʊθ əv hɜːr ˈpɛrənts ɑːr ˌtʃaɪˈniːz. bʌt ˈɛrɪn wɒz bɔːrn ɪn ˈkænədə. hɜːr frɛndz ɪn ˈkɪndərˌɡɑːrtn ɑːr ˈdɪfrənt ˈkʌlərz/", vi: "Erin sinh sống cùng bố mẹ tại Canada. Cả bố và mẹ đều là người gốc Trung Quốc, nhưng bản thân Erin lại cất tiếng khóc chào đời ngay trên đất nước Canada. Những người bạn ở trường mẫu giáo của cô bé có đủ màu da khác nhau." },
      { "start": 16.0, "en": "One day, Mom said to her, 'Erin, you will have a baby sister very soon.' Erin was very happy.", "ipa": "/wʌn deɪ, mɒm sɛd tuː hɜːr, ˈɛrɪn, juː wɪl hæv a ˈbeɪbi ˈsɪstər ˈvɛri suːn. ˈɛrɪn wɒz ˈvɛri ˈhæpi/", vi: "Một hôm, mẹ gọi Erin lại và thông báo: 'Erin sắp được làm chị rồi đấy, mẹ chuẩn bị sinh em bé.' Erin nghe xong liền nhảy cẫng lên vì sung sướng." },
      { "start": 24.0, "en": "She thought for a little while, then asked, 'Mom, is my sister going to be Chinese or a foreigner? Will her eyes be black or blue? And what about her hair? What colour will it be? Will it be black or brown?'", "ipa": "/ʃiː θɔːt fɔːr a ˈlɪtl waɪl, ðɛn ɑːskt, mɒm, ɪz maɪ ˈsɪstər ˈɡoʊɪŋ tuː biː ˌtʃaɪˈniːz ɔːr a ˈfɔːrɪnər? wɪl hɜːr aɪz biː blæk ɔːr bluː? ænd wɒt əˈbaʊt hɜːr hɛr? wɒt ˈkʌlər wɪl ɪt biː? wɪl ɪt biː blæk ɔːr braʊn?/", vi: "Trầm ngâm suy nghĩ một lát, cô bé ngây thơ hỏi dồn: 'Mẹ ơi, thế em con là người Trung Quốc hay người ngoại quốc ạ? Mắt em sẽ màu đen hay màu xanh dương? Còn tóc em thì sao, tóc em màu đen hay màu nâu thế mẹ?'" },
      { "start": 41.0, "en": "Mom laughed, 'Your dad and mom are Chinese, so you will have a baby sister just like you.' Erin smiled. She walked away thinking of all the fun she was going to have with her new baby sister.", "ipa": "/mɒm lɑːft, jɔːr dæd ænd mɒm ɑːr ˌtʃaɪˈniːz, soʊ juː wɪl hæv a ˈbeɪbi ˈsɪstər dʒʌst laɪk juː. ˈɛrɪn smaɪld. ʃiː wɔːkt əˈweɪ ˈθɪŋkɪŋ əv ɔːl ðə fʌn ʃiː wɒz ˈgoʊɪŋ tuː hæv wɪð hɜːr nuː ˈbeɪbi ˈsɪstər/", vi: "Mẹ phì cười ôm con gái vào lòng: 'Bố và mẹ đều là người Trung Quốc cơ mà, thế nên em bé sinh ra chắc chắn sẽ y hệt như chị hai của nó thôi.' Erin nghe vậy liền mỉm cười thỏa mãn, lon ton chạy đi với hàng loạt viễn tưởng thú vị về những trò chơi sẽ chơi cùng em bé tương lai." }
    ]
  },
  {
    "day": 20,
    "title": "Tomorrow",
    image: "02 February/images/day_20.webp",
    audio: "02 February/audio/Track20.mp3",
    "sentences": [
      { "start": 4.8, "en": "There once was a man who was very lazy. Every day, a farmer would tell the man, 'If you help me bring in my crops, I will give you food.' But the lazy man would always answer, 'Maybe tomorrow.'", "ipa": "/ðɛr wʌns wɒz a mæn huː wɒz ˈvɛri ˈleɪzi. ˈɛvri deɪ, a ˈfɑːrmər wʊd tɛl ðə mæn, ɪf juː hɛlp miː brɪŋ ɪn maɪ krɒps, aɪ wɪl ɡɪv juː fuːd. bʌt ðə ˈleɪzi mæn wʊd ˈɔːlweɪz ˈɑːnsər, ˈmeɪbi təˈmɑːroʊ/", vi: "Ngày xửa ngày xưa có một kẻ lười chảy thây. Ngày nào người nông dân tốt bụng cũng đến khuyên bảo: 'Nếu anh chịu phụ tôi thu hoạch hoa màu ngoài đồng, tôi sẽ cho anh thức ăn đầy đủ.' Nhưng gã lười biếng ấy lúc nào cũng ngoác miệng đáp bài ca muôn thuở: 'Chắc để... ngày mai đi nhé.'" },
      { "start": 21.0, "en": "The summer turned to winter. One day, the lazy man did not have any food left. So, he went to the farmer and knocked on his door. He asked, 'Can I work for some food today?'", "ipa": "/ðə ˈsʌmər tɜːrnd tuː ˈwɪntər. wʌn deɪ, ðə ˈleɪzi mæn dɪd nɒt hæv ˈɛni fuːd lɛft. soʊ, hiː wɛnt tuː ðə ˈfɑːrmər ænd nɒkt ɒn hɪz dɔːr. hiː ɑːskt, kæn aɪ wɜːrk fɔːr sʌm fuːd təˈdeɪ?/", vi: "Cứ thế mùa hè qua đi nhường chỗ cho mùa đông lạnh giá. Đến một ngày nọ, gã lười cạn kiệt sạch sẽ lương thực trong nhà, đành lủi thủi sang nhà người nông dân gõ cửa cầu cứu: 'Hôm nay cháu có thể làm việc để đổi lấy chút thức ăn được không ạ?'" },
      { "start": 36.0, "en": "The farmer said, 'I'm sorry, there's no more work to be done.' The man walked away. He sat by the side of the road. He was really hungry.", "ipa": "/ðə ˈfɑːrmər sɛd, aɪm ˈsɒri, ðɛrz noʊ mɔːr wɜːrk tuː biː dʌn. ðə mæn wɔːkt əˈweɪ. hiː sæt baɪ ðə saɪd əv ðə roʊd. hiː wɒz ˈrɪəli ˈhʌŋɡri/", vi: "Người nông dân điềm tĩnh đáp: 'Tiếc quá, bây giờ chẳng còn việc gì quanh đây để làm nữa rồi.' Gã lười thất thểu lê bước ra bên vệ đường ngồi thụp xuống với chiếc bụng đói cồn cào." },
      { "start": 48.0, "en": "Later, the farmer came up to him and said, 'If you help me cut wood, I'll give you some food.' Then, the farmer smiled and said, 'Or would you like to wait until tomorrow?'", "ipa": "/ˈleɪtər, ðə ˈfɑːrmər keɪm ʌp tuː hɪm ænd sɛd, ɪf juː hɛlp miː kʌt wʊd, aɪl ɡɪv juː sʌm fuːd. ðɛn, ðə ˈfɑːrmər smaɪld ænd sɛd, ɔːr wʊd juː laɪk tuː weɪt ənˈtɪl təˈmɑːroʊ?/", vi: "Lát sau, người nông dân bước đến, nhếch mép cười và bảo: 'Thôi được, nếu anh chịu khó phụ tôi chặt củi, tôi sẽ cho anh phần ăn.' Nói đoạn, ông cười ẩn ý: 'Hay là anh lại muốn đợi đến... ngày mai mới làm?'" },
      { "start": 63.0, "en": "The man jumped up and started to work immediately.", "ipa": "/ðə mæn dʒʌmpt ʌp ænd ˈstɑːrtɪd tuː wɜːrk ɪˈmiːdiətli/", vi: "Nghe tới đó, gã lười giật mình chồm dậy, vớ lấy rìu và lao vào làm việc ngay lập tức không dám chần chừ thêm giây nào nữa." }
    ]
  },
  {
    "day": 21,
    "title": "Friends",
    image: "02 February/images/day_21.webp",
    audio: "02 February/audio/Track21.mp3",
    "sentences": [
      { "start": 4.8, "en": "One day, Turtle lost his footing and rolled down a riverbank. He landed belly-up on his shell. The riverbank was very muddy and Turtle was stuck.", "ipa": "/wʌn deɪ, ˈtɜːrtl lɒst hɪz ˈfʊtɪŋ ænd roʊld daʊn a ˈrɪvərˌbæŋk. hiː ˈlændɪd ˈbɛli-ʌp ɒn hɪz ʃɛl. ðə ˈrɪvərˌbæŋk wɒz ˈvɛri ˈmʌdi ænd ˈtɜːrtl wɒz stʌk/", vi: "Vào một ngày nọ, chú Rùa bất cẩn trượt chân lăn tòm xuống bờ sông, hạ cánh với tư thế ngửa bụng lên trời nằm kẹt cứng giữa vũng bùn lầy." },
      { "start": 16.0, "en": "'Help! Help!' called Turtle. Cat came strolling by. 'What's wrong?' asked the cat. 'I'm stuck. Can you roll me over?' asked Turtle.", "ipa": "/hɛlp! hɛlp!, kɔːld ˈtɜːrtl. kæt keɪm ˈstroʊlɪŋ baɪ. wɒts rɒŋ?, ɑːskt ðə kæt. aɪm stʌk. kæn juː roʊl miː ˈoʊvər?, ɑːskt ˈtɜːrtl/", vi: "'Cứu tôi với! Ai cứu tôi với!' Rùa hoảng hốt kêu cứu. Vừa lúc đó chú Mèo đang thong thả đi dạo ngang qua bèn dừng lại hỏi: 'Cậu bị sao thế?' 'Tớ bị kẹt rồi. Cậu lật giúp tớ nằm sấp lại được không?' Rùa mếu máo nhờ vả." },
      { "start": 30.0, "en": "Cat pushed Turtle over onto his belly. Turtle swam away and said, 'Thanks Cat. I'll remember this!'", "ipa": "/kæt pʊʃt ˈtɜːrtl ˈoʊvər ˈɒntuː hɪz ˈbɛli. ˈtɜːrtl swæm əˈweɪ ænd sɛd, θæŋks kæt. aɪl rɪˈmɛmbər ðɪs!/", vi: "Mèo liền dùng chân đẩy nhẹ giúp Rùa xoay người úp bụng xuống nước. Rùa bơi vùng đi và ngoái đầu gọi với lại: 'Cảm ơn Mèo nhé, tớ sẽ ghi nhớ ơn này!'" },
      { "start": 39.0, "en": "Not long after, Cat was chasing a squirrel on a tree. Snap! The tree branch cracked and fell. Cat landed on a large rock in the middle of the river.", "ipa": "/nɒt lɒŋ ˈɑːftər, kæt wɒz ˈtʃeɪsɪŋ a ˈskwɜːrəl ɒn a triː. snæp! ðə triː bræntʃ krækt ænd fɛl. kæt ˈlændɪd ɒn a lɑːrdʒ rɒk ɪn ðə ˈmɪdl əv ðə ˈrɪvər/", vi: "Chẳng bao lâu sau, trong lúc Mèo đang hăng hái rượt đuổi sóc con trên ngọn cây, rắc! Cành cây đột ngột gãy sập khiến Mèo rơi tõm xuống một tảng đá lớn giữa dòng sông chảy xiết." },
      { "start": 52.0, "en": "'Help! Help!' called Cat. Turtle came swimming by. 'What's wrong?' asked Turtle. 'I can't swim. Can you carry me to land?' asked Cat. 'Sure,' said Turtle. 'Climb onto my back.' Cat rode to safety on the back of her new friend, Turtle.", "ipa": "/hɛlp! hɛlp!, kɔːld kæt. ˈtɜːrtl keɪm ˈswɪmɪŋ baɪ. wɒts rɒŋ?, ɑːskt ˈtɜːrtl. aɪ kænt swɪm. kæn juː ˈkæri miː tuː lænd?, ɑːskt kæt. ʃʊr, sɛd ˈtɜːrtl. klaɪm ˈɒntuː maɪ bæk. kæt roʊd tuː ˈseɪfti ɒn ðə bæk əv hɜːr nuː frɛnd, ˈtɜːrtl/", vi: "'Cứu tôi với!' Mèo hoảng loạn hét lên. Rùa bơi ngang qua nghe tiếng liền bơi đến: 'Có chuyện gì thế?' 'Tớ không biết bơi. Cậu đưa tớ vô bờ được không?' Mèo khóc thét. 'Được chứ,' Rùa thân thiện đáp. 'Leo ngay lên lưng tớ đi.' Thế là Mèo được người bạn mới cứu nguy an toàn trên tấm lưng chắc nịch của chú Rùa." }
    ]
  },
  {
    "day": 22,
    "title": "A Morning Surprise",
    image: "02 February/images/day_22.webp",
    audio: "02 February/audio/Track22.mp3",
    "sentences": [
      { "start": 4.8, "en": "There are many kinds of hair. There is long hair and short hair. There is straight hair and curly hair. Some people have black or brown hair. Other people have red or blonde hair.", "ipa": "/ðɛr ɑːr ˈmɛni kaɪndz əv hɛr. ðɛr ɪz lɒŋ hɛr ænd ʃɔːrt hɛr. ðɛr ɪz streɪt hɛr ænd ˈkɜːrli hɛr. sʌm ˈpiːpl hæv blæk ɔːr braʊn hɛr. ˈʌðər ˈpiːpl hæv rɛd ɔːr blɒnd hɛr/", vi: "Trên đời có vô vàn kiểu tóc khác nhau: tóc dài, tóc ngắn, tóc thẳng, tóc xoăn tít. Người sở hữu mái tóc đen hoặc nâu, kẻ lại mang sắc tóc đỏ hay vàng óng." },
      { "start": 18.0, "en": "Some people lose their hair when they get old. Other people's hair turns grey. It usually takes many years for a person's hair to turn grey.", "ipa": "/sʌm ˈpiːpl luːz ðɛr hɛr wɛn ðeɪ ɡɛt oʊld. ˈʌðər ˈpiːplz hɛr tɜːrnz ɡreɪ. ɪt ˈjuːʒuəli teɪks ˈmɛni jɪərz fɔːr a ˈpɜːrsnz hɛr tuː tɜːrn ɡreɪ/", vi: "Nhiều người sẽ bị rụng tóc khi tuổi già xộc tới, số khác thì tóc chuyển sang màu bạc phơ. Quá trình chuyển hóa hoa râm này thường phải mất rất nhiều năm tháng." },
      { "start": 28.0, "en": "But something strange happened to my father. His hair was black when he went to bed. By morning, it had turned completely grey! Why?", "ipa": "/bʌt ˈsʌmθɪŋ streɪndʒ ˈhæpənd tuː maɪ ˈfɑːðər. hɪz hɛr wɒz blæk wɛn hiː wɛnt tuː bɛd. baɪ ˈmɔːrnɪŋ, ɪt hæd tɜːrnd kəmˈpliːtli ɡreɪ! waɪ?/", vi: "Nhưng một sự việc kỳ lạ khó tin đã xảy ra với bố tôi: Mái tóc của bố vẫn đen nhánh lúc lên giường đi ngủ tối hôm trước, thế mà sáng hôm sau tỉnh dậy đã bạc trắng hoàn toàn! Tại sao lại có chuyện vô lý thế nhỉ?" },
      { "start": 41.0, "en": "Dad had been feeling very stressed lately. He had lost his job. He was worried about his family. He was worried about paying the bills. He was worried about feeding us. He was worrying all the time.", "ipa": "/dæd hæd biːn ˈfiːlɪŋ ˈvɛri strɛst ˈleɪtli. hiː hæd lɒst hɪz dʒɒb. hiː wɒz ˈwʌrid əˈbaʊt hɪz ˈfæməli. hiː wɒz ˈwʌrid əˈbaʊt ˈpeɪɪŋ ðə bɪlz. hiː wɒz ˈwʌrid əˈbaʊt ˈfiːdɪŋ ʌs. hiː wɒz ˈwʌriɪŋ ɔːl ðə taɪm/", vi: "Hóa ra thời gian gần đây bố chịu áp lực tâm lý vô cùng nặng nề. Bố vừa mới bị mất việc làm, lại thêm gánh nặng lo toan cho gia đình, tiền hóa đơn các khoản chi phí, tiền ăn uống của mấy chị em. Bố trăn trở, lo âu không lúc nào ngơi nghỉ." },
      { "start": 59.0, "en": "The doctor said that what happened to my dad does not happen often. But it does happen. Worry and stress are very bad. They can turn hair grey overnight!", "ipa": "/ðə ˈdɒktər sɛd ðæt wɒt ˈhæpənd tuː maɪ dæd dʌz nɒt ˈhæpən ˈɒfn. bʌt ɪt dʌz ˈhæpən. ˈwʌri ænd strɛs ɑːr ˈvɛri bæd. ðeɪ kæn tɜːrn hɛr ɡreɪ ˈoʊvərˌnaɪt/", vi: "Bác sĩ giải thích rằng trường hợp đột ngột như của bố tuy hiếm gặp nhưng không phải là không có thật. Sự lo âu và căng thẳng tột độ thực sự rất độc hại, chúng hoàn toàn có thể khiến mái tóc đổi màu bạc trắng chỉ sau một đêm!" }
    ]
  },
  {
    "day": 23,
    "title": "Mr. Slow and Mr. Fast",
    image: "02 February/images/day_23.webp",
    audio: "02 February/audio/Track23.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. Slow and Mr. Fast are friends. But they are not the same.", "ipa": "/ˈmɪstər sloʊ ænd ˈmɪstər fɑːst ɑːr frɛndz. bʌt ðeɪ ɑːr nɒt ðə seɪm/", vi: "Ông Chậm Chạp và ông Nhanh Nhẩu vốn là đôi bạn thân thiết, nhưng tính cách của họ lại trái ngược nhau một trời một vực." },
      { "start": 10.0, "en": "Mr. Slow always takes his time. He talks slowly. He walks slowly. He even takes a long time to eat. Mr. Slow is really slow.", "ipa": "/ˈmɪstər sloʊ ˈɔːlweɪz teɪks hɪz taɪm. hiː tɔːks ˈsloʊli. hiː wɔːks ˈsloʊli. hiː ˈiːvn teɪks a lɒŋ taɪm tuː iːt. ˈmɪstər sloʊ ɪz ˈrɪəli sloʊ/", vi: "Ông Chậm Chạp lúc nào cũng thong thả, từ tốn trong mọi việc. Ông nói năng chậm rãi, bước đi khoan thai, và thậm chí mất rất nhiều thời gian cho mỗi bữa ăn. Quả thực ông đúng chuẩn 'chúa chậm chạp'." },
      { "start": 22.0, "en": "Mr. Fast is the opposite. He is always in a hurry. He talks fast. He walks fast. He even rushes when he eats. Mr. Fast is really fast.", "ipa": "/ˈmɪstər fɑːst ɪz ði ˈɒpəzɪt. hiː ɪz ˈɔːlweɪz ɪn a ˈhɜːri. hiː tɔːks fɑːst. hiː wɔːks fɑːst. hiː ˈiːvn ˈrʌʃɪz wɛn hiː iːts. ˈmɪstər fɑːst ɪz ˈrɪəli fɑːst/", vi: "Ngược lại hoàn toàn với bạn mình, ông Nhanh Nhẩu lúc nào cũng tất tả trong trạng thái vội vã. Ông nói nhanh, đi nhanh, và ăn uống cũng nuốt chửng cho mau lẹ. Đúng là một người 'siêu tốc độ'." },
      { "start": 35.0, "en": "One day, the two men went to a restaurant. As usual, Mr. Fast ordered his food right away. Mr. Slow took a long time to decide what he wanted. Mr. Fast finished eating before Mr. Slow even got his meal.", "ipa": "/wʌn deɪ, ðə tuː mɛn wɛnt tuː a ˈrɛstərɒnt. æz ˈjuːʒuəl, ˈmɪstər fɑːst ˈɔːrdərd hɪz fuːd raɪt əˈweɪ. ˈmɪstər sloʊ tʊk a lɒŋ taɪm tuː dɪˈsaɪd wɒt hiː ˈwɒntɪd. ˈmɪstər fɑːst ˈfɪnɪʃt ˈiːtɪŋ bɪˈfɔːr ˈmɪstər sloʊ ˈiːvn ɡɒt hɪz miːl/", vi: "Có một hôm, hai người cùng hẹn nhau ra nhà hàng dùng bữa. Theo thói quen, ông Nhanh Nhẩu gọi món ngay tức khắc, trong khi ông Chậm Chạp mất khối thời gian đắn đo suy nghĩ xem mình thích ăn gì. Kết quả là ông Nhanh Nhẩu đã chén sạch đĩa thức ăn trước cả khi món của ông Chậm Chạp được mang lên bàn." },
      { "start": 54.0, "en": "Still, Mr. Fast waited for his friend. 'Take your time,' he said quickly. 'You are slow, like a turtle. I am fast, like a rabbit. But I can wait because you are my friend.'", "ipa": "/stɪl, ˈmɪstər fɑːst ˈweɪtɪd fɔːr hɪz frɛnd. teɪk jɔːr taɪm, hiː sɛd ˈkwɪkli. juː ɑːr sloʊ, laɪk a ˈtɜːrtl. aɪ æm fɑːst, laɪk a ˈræbɪt. bʌt aɪ kæn weɪt bɪˈkəz juː ɑːr maɪ frɛnd/", vi: "Mặc dù vậy, ông Nhanh Nhẩu vẫn vui vẻ ngồi chờ người bạn của mình. 'Cứ thong thả nhé, không phải vội,' ông lém lỉnh nói nhanh. 'Cậu thì chậm chạp như rùa, tớ thì nhanh nhẹn như thỏ. Nhưng tớ sẵn sàng chờ vì cậu là bạn thân của tớ cơ mà.'" }
    ]
  },
  {
    "day": 24,
    "title": "Never Too Old to Travel",
    image: "02 February/images/day_24.webp",
    audio: "02 February/audio/Track24.mp3",
    "sentences": [
      { "start": 4.8, "en": "My grandma was coming for a visit on her birthday. What was so special about that? Grandma was turning 100 years old! But even more amazing—she was travelling by airplane.", "ipa": "/maɪ ˈɡrænmɑː wɒz ˈkʌmɪŋ fɔːr a ˈvɪzɪt ɒn hɜːr ˈbɜːrθdeɪ. wɒt wɒz soʊ ˈspɛʃl əˈbaʊt ðæt? ˈɡrænmɑː wɒz ˈtɜːrnɪŋ wʌn ˈhʌndrəd jɪərz oʊld! bʌt ˈiːvn mɔːr əˈmeɪzɪŋ—ʃiː wɒz ˈtrævəlɪŋ baɪ ˈɛrˌpleɪn/", vi: "Bà ngoại sắp sửa đến thăm gia đình chúng tôi nhân dịp sinh nhật của bà. Điều gì khiến sự kiện này trở nên đặc biệt ư? Bà ngoại chuẩn bị bước sang tuổi 100! Và điều kinh ngạc hơn nữa là cụ di chuyển bằng... máy bay." },
      { "start": 18.0, "en": "Mom said flying was not easy. What if Grandma got lost at the airport? What if she got sick on the plane? Many things could go wrong.", "ipa": "/mɒm sɛd ˈflaɪɪŋ wɒz nɒt ˈiːzi. wɒt ɪf ˈɡrænmɑː ɡɒt lɒst æt ði ˈɛrˌpɔːrt? wɒt ɪf ʃiː ɡɒt sɪk ɒn ðə pleɪn? ˈmɛni θɪŋz kʊd ɡoʊ rɒŋ/", vi: "Mẹ lo lắng bảo đi máy bay không hề đơn giản chút nào. Lỡ bà ngoại bị lạc ở sân bay thì sao? Lỡ bà bị mệt trên máy bay thì tính thế nào? Vô số rủi ro có thể xảy ra." },
      { "start": 29.0, "en": "We were nervous. We went to the airport early. Then we saw her. Grandma was with the pilot. He was smiling. Grandma waved. I ran to give her a hug.", "ipa": "/wiː wɜːr ˈnɜːrvəs. wiː wɛnt tuː ði ˈɛrˌpɔːrt ˈɜːrli. ðɛn wiː sɔː hɜːr. ˈɡrænmɑː wɒz wɪð ðə ˈpaɪlət. hiː wɒz ˈsmaɪlɪŋ. ˈɡrænmɑː weɪvd. aɪ ræn tuː ɡɪv hɜːr a hʌɡ/", vi: "Cả nhà thấp thỏm không yên và ra sân bay từ rất sớm. Kìa, chúng tôi đã nhìn thấy bà! Bà bước ra cùng cơ trưởng với nụ cười rạng rỡ trên môi. Bà vẫy tay chào, tôi liền cắm cổ chạy lao tới ôm chầm lấy bà." },
      { "start": 42.0, "en": "The pilot said, 'When I heard she was coming to celebrate her 100th birthday, I knew how lucky I was. She is the oldest passenger I have ever had fly on my plane.'", "ipa": "/ðə ˈpaɪlət sɛd, wɛn aɪ hɜːrd ʃiː wɒz ˈkʌmɪŋ tuː ˈsɛlɪbreɪt hɜːr ˈhʌndrəθ ˈbɜːrθdeɪ, aɪ nuː haʊ ˈlʌki aɪ wɒz. ʃiː ɪz ði ˈoʊldɪst ˈpæsɪndʒər aɪ hæv ˈɛvər hæd flaɪ ɒn maɪ pleɪn/", vi: "Viên phi công vui mừng chia sẻ: 'Khi biết cụ cất công đi máy bay để mừng sinh nhật tròn 100 tuổi, tôi thấy mình thật may mắn biết bao. Cụ chính là hành khách lớn tuổi nhất mà tôi từng vinh dự phục vụ trên chuyến bay của mình.'" },
      { "start": 57.0, "en": "I gave Grandma a big kiss. She smiled and said, 'On my 101st birthday, maybe I will dive in the ocean.' We all laughed. Grandma is not afraid of anything.", "ipa": "/aɪ ɡeɪv ˈɡrænmɑː a bɪɡ kɪs. ʃiː smaɪld ænd sɛd, ɒn maɪ wʌn ˈhʌndrəd fɜːrst ˈbɜːrθdeɪ, ˈmeɪbi aɪ wɪl daɪv ɪn ði ˈoʊʃn. wiː ɔːl lɑːft. ˈɡrænmɑː ɪz nɒt əˈfreɪd əv ˈɛniˌθɪŋ/", vi: "Tôi thơm lên má bà một cái thật kêu. Bà mỉm cười hóm hỉnh: 'Đến sinh nhật 101 tuổi tới đây, biết đâu bà lại thử lặn xuống đáy đại dương xem sao.' Ai nấy nghe xong đều phì cười thích thú. Quả thật bà ngoại chẳng sợ bất cứ điều gì trên đời!" }
    ]
  },
  {
    "day": 25,
    "title": "How We Got Night and Day",
    image: "02 February/images/day_25.webp",
    audio: "02 February/audio/Track25.mp3",
    "sentences": [
      { "start": 4.8, "en": "Long ago, the world was new. It was fresh and clean. Everyone agreed on everything.", "ipa": "/lɒŋ əˈɡoʊ, ðə wɜːrld wɒz nuː. ɪt wɒz frɛʃ ænd kliːn. ˈɛvriˌwʌn əˈɡriːd ɒn ˈɛvriˌθɪŋ/", vi: "Ngày xửa ngày xưa, khi thế giới vừa mới hình thành, vạn vật vô cùng tinh khôi và trong lành. Khi ấy, muôn loài luôn đồng thuận và hòa hợp với nhau trong mọi chuyện." },
      { "start": 12.0, "en": "Then, the animals began to argue. Some of them wanted it to be night all the time. Others wanted it to be day all the time.", "ipa": "/ðɛn, ðə ˈænɪmlz bɪˈɡæn tuː ˈɑːrɡjuː. sʌm əv ðɛm ˈwɒntɪd ɪt tuː biː naɪt ɔːl ðə taɪm. ˈʌðərz ˈwɒntɪd ɪt tuː biː deɪ ɔːl ðə taɪm/", vi: "Rồi một ngày nọ, lũ thú bắt đầu nảy sinh tranh cãi. Một số loài muốn thế giới chìm trong màn đêm vĩnh cửu, trong khi phe khác lại đòi ban ngày phải kéo dài mãi mãi." },
      { "start": 21.0, "en": "They asked Bear to make the decision for them. Bear liked the night. 'Let's have night all the time,' he said.", "ipa": "/ðeɪ ɑːskt bɛr tuː meɪk ðə dɪˈsɪʒn fɔːr ðɛm. bɛr laɪkt ðə naɪt. lɛts hæv naɪt ɔːl ðə taɪm, hiː sɛd/", vi: "Bí bách quá, chúng liền tôn Gấu làm trọng tài để đưa ra phán quyết cuối cùng. Vốn ưa thích sự tĩnh mịch, Gấu tuyên bố: 'Cứ để màn đêm bao trùm mãi mãi đi là tốt nhất.'" },
      { "start": 29.0, "en": "But Squirrel jumped up and said, 'Look at Racoon. See the rings on his tail? One is dark, then light, then dark again. The number of dark rings is the same as the number of light rings. I say we have equal parts of night and day.'", "ipa": "/bʌt ˈskwɜːrəl dʒʌmpt ʌp ænd sɛd, lʊk æt rəˈkuːn. siː ðə rɪŋz ɒn hɪz teɪl? wʌn ɪz dɑːrk, ðɛn laɪt, ðɛn dɑːrk əˈɡɛn. ðə ˈnʌmbər əv dɑːrk rɪŋz ɪz ðə seɪm æz ðə ˈnʌmbər əv laɪt rɪŋz. aɪ seɪ wiː hæv ˈiːkwəl pɑːrts əv naɪt ænd deɪ/", vi: "Nghe vậy, Sóc nhanh nhẩu nhảy dựng lên phản bác: 'Các cậu hãy nhìn vào đuôi chú Gấu Mèo mà xem. Thấy các khoang vòng trên đuôi chứ? Khoang tối rồi đến khoang sáng, cứ đan xen luân phiên nhau. Số lượng vòng tối cân bằng hoàn toàn với số lượng vòng sáng. Theo tớ, chúng ta nên chia đôi thời gian bằng nhau cho cả ban đêm lẫn ban ngày.'" },
      { "start": 48.0, "en": "The animals were impressed. They saw the wisdom in this. And that is how we came to have day and night.", "ipa": "/ðə ˈænɪmlz wɜːr ɪmˈprɛst. ðeɪ sɔː ðə ˈwɪzdəm ɪn ðɪs. ænd ðæt ɪz haʊ wiː keɪm tuː hæv deɪ ænd naɪt/", vi: "Muôn loài nghe xong đều vô cùng thán phục trước sự thông thái của Sóc và đồng tình tuyệt đối. Và đó chính là sự tích ra đời của ngày và đêm từ thuở hồng hoang." }
    ]
  },
  {
    "day": 26,
    "title": "A Big Cat",
    image: "02 February/images/day_26.webp",
    audio: "02 February/audio/Track26.mp3",
    "sentences": [
      { "start": 4.8, "en": "The average cat weighs about five or six kilograms. And most cats like to catch mice.", "ipa": "/ði ˈævərɪdʒ kæt weɪz əˈbaʊt faɪv ɔːr sɪks ˈkɪləˌɡræmz. ænd moʊst kæts laɪk tuː kætʃ maɪs/", vi: "Một chú mèo nhà bình thường chỉ nặng khoảng năm hoặc sáu kg và sở thích muôn thuở của chúng là rình bắt những con chuột nhắt." },
      { "start": 12.0, "en": "But there is one cat who doesn't bother with mice. His name is Hercules. You see, Hercules weighs over 400 kilograms. He is two metres tall and three metres long!", "ipa": "/bʌt ðɛr ɪz wʌn kæt huː ˈdʌznt ˈbɒðər wɪð maɪs. hɪz neɪm ɪz ˈhɜːrkjuliːz. juː siː, ˈhɜːrkjuliːz weɪz ˈoʊvər ˈfɔːr ˈhʌndrəd ˈkɪləˌɡræmz. hiː ɪz tuː ˈmiːtərz tɔːl ænd θriː ˈmiːtərz lɒŋ!/", vi: "Thế nhưng có một chú mèo khổng lồ chẳng thèm mảy may bận tâm đến loài chuột. Tên chú ta là Hercules. Cậu chủ à, Hercules nặng tới hơn 400 kg, chiều cao chạm mốc 2 mét và chiều dài thân hình lên đến 3 mét!" },
      { "start": 26.0, "en": "He prefers to eat much bigger things than mice. He is the biggest cat in the world. Hercules was born in a zoo. His father was a lion and his mother was a tiger. He is called a Liger.", "ipa": "/hiː prɪˈfɜːrz tuː iːt mʌtʃ ˈbɪɡər θɪŋz ðæn maɪs. hiː ɪz ðə ˈbɪɡɪst kæt ɪn ðə wɜːrld. ˈhɜːrkjuliːz wɒz bɔːrn ɪn a zuː. hɪz ˈfɑːðər wɒz a ˈlaɪən ænd hɪz ˈmʌðər wɒz a ˈtaɪɡər. hiː ɪz kɔːld a ˈlaɪɡər/", vi: "Đương nhiên chú thích săn những con mồi lớn hơn chuột rất nhiều. Đây chính là chú mèo vĩ đại nhất hành tinh. Hercules sinh ra trong một vườn thú; bố chú là sư tử còn mẹ là hổ, thế nên người ta gọi chú là Liger (Con lai giữa sư tử và hổ)." },
      { "start": 44.0, "en": "You would think that something so big must not be able to move very fast. How can he? But Hercules can run at 90 kilometres per hour. And he needs this exercise because he eats 100 pounds of food for every meal! That would be a lot of mice!", "ipa": "/juː wʊd θɪŋk ðæt ˈsʌmθɪŋ soʊ bɪɡ mʌst nɒt biː ˈeɪbl tuː muːv ˈvɛri fɑːst. haʊ kæn hiː? bʌt ˈhɜːrkjuliːz kæn rʌn æt ˈnaɪnti ˈkɪləˌmiːtərz pɜːr ˈaʊər. ænd hiː niːdz ðɪs ˈɛksərˌsaɪz bɪˈkəz hiː iːts wʌn ˈhʌndrəd paʊndz əv fuːd fɔːr ˈɛvri miːl! ðæt wʊd biː a lɒt əv maɪs!/", vi: "Nhiều người sẽ nghĩ một sinh vật cồng kềnh như thế chắc chắn chẳng thể di chuyển nhanh nhẹn được. Nào ngờ đâu, Hercules có thể phi nước đại với vận tốc lên tới 90 km/h! Và chú rất cần vận động để tiêu hao năng lượng vì mỗi bữa ăn chú nốc trọn tận 100 pound thức ăn lận đấy! Tính ra thì cần phải gom biết bao nhiêu là chuột mới đủ bữa nhỉ!" }
    ]
  },
  {
    "day": 27,
    "title": "A Painful Lesson",
    image: "02 February/images/day_27.webp",
    audio: "02 February/audio/Track27.mp3",
    "sentences": [
      { "start": 4.8, "en": "Becky loves to win. She wants to be the first in everything. One day we were out biking. Becky was in front. It bothered me that my friend always had to be in charge. I felt angry. I started to pedal faster and I passed her. Soon, she passed me again.", "ipa": "/ˈbɛki lʌvz tuː wɪn. ʃiː wɒnts tuː biː ðə fɜːrst ɪn ˈɛvriˌθɪŋ. wʌn deɪ wiː wɜːr aʊt ˈbaɪkɪŋ. ˈbɛki wɒz ɪn frʌnt. ɪt ˈbɒðərd miː ðæt maɪ frɛnd ˈɔːlweɪz hæd tuː biː ɪn tʃɑːrdʒ. aɪ fɛlt ˈæŋɡri. aɪ ˈstɑːrtɪd tuː ˈpɛdl ˈfɑːstər ænd aɪ pɑːst hɜːr. suːn, ʃiː pɑːst miː əˈɡɛn/", vi: "Becky có tính hiếu thắng và luôn muốn mình phải là số một trong mọi chuyện. Một hôm khi đang đạp xe dạo chơi, Becky cố tình chạy lên đầu dẫn trước. Việc bạn mình lúc nào cũng thích ra oai khiến tôi cảm thấy khó chịu và bực bội. Tôi liền dồn sức đạp nhanh hơn để vượt mặt cậu ấy, nhưng chẳng mấy chốc Becky lại tăng tốc vượt lên lại." },
      { "start": 25.0, "en": "When we reached a corner, I ran right into Becky. We both went flying and landed on the grass. I hurt my knee and Becky's elbow was badly bruised.", "ipa": "/wɛn wiː riːtʃt a ˈkɔːrnər, aɪ ræn raɪt ˈɪntuː ˈbɛki. wiː boʊθ wɛnt ˈflaɪɪŋ ænd ˈlændɪd ɒn ðə ɡræs. aɪ hɜːrt maɪ niː ænd ˈbɛkiz ˈɛlboʊ wɒz ˈbædli bruːzd/", vi: "Đến khúc cua quẹo, do không kiểm soát kịp tốc độ nên tôi đâm sầm vào Becky. Cả hai ngã nhào văng xuống thảm cỏ bên đường; tôi bị trầy xước đầu gối còn khuỷu tay của Becky thì sưng vù bầm tím." },
      { "start": 36.0, "en": "Our parents took us to the hospital. I felt terrible. 'I wanted to win so much that I cut across the lawn and we collided,' I said.", "ipa": "/ˈaʊər ˈpɛrənts tʊk ʌs tuː ðə ˈhɒspɪtl. aɪ fɛlt ˈtɛrəbl. aɪ ˈwɒntɪd tuː wɪn soʊ mʌtʃ ðæt aɪ kʌt əˈkrɒs ðə lɔːn ænd wiː kəˈlaɪdɪd, aɪ sɛd/", vi: "Bố mẹ hoảng hốt đưa hai đứa vào bệnh viện. Tôi cúi đầu ân hận tột cùng: 'Chỉ vì con quá hiếu thắng muốn tranh đua nên mới cố lấn qua bãi cỏ dẫn đến tai nạn va chạm này ạ.'" },
      { "start": 47.0, "en": "'It's my fault,' Becky said. 'Instead of letting you pass, I had to win. I'm sorry.' I gave her the best friend a hug. We had both grown up a little that day. But it was a painful lesson.", "ipa": "/ɪts maɪ fɔːlt, ˈbɛki sɛd. ɪnˈstɛd əv ˈlɛtɪŋ juː pɑːs, aɪ hæd tuː wɪn. aɪm ˈsɒri. aɪ ɡeɪv hɜːr a hʌɡ. wiː hæd boʊθ ɡroʊn ʌp a ˈlɪtl ðæt deɪ. bʌt ɪt wɒz a ˈpeɪnfʊl ˈlɛsn/", vi: "'Đó cũng là lỗi của tớ,' Becky nghẹn ngào thừa nhận. 'Lẽ ra tớ nên nhường cậu vượt qua thay vì cố chấp tranh thắng thua. Tớ xin lỗi cậu.' Tôi ôm chầm lấy cô bạn thân. Sau sự cố ngày hôm đó, cả hai đứa hình như đều đã trưởng thành thêm được một chút, dẫu đó là một bài học xương máu vô cùng đau đớn." }
    ]
  },
  {
    "day": 28,
    "title": "Reading to Grandchildren",
    image: "02 February/images/day_28.webp",
    audio: "02 February/audio/Track28.mp3",
    "sentences": [
      { "start": 4.8, "en": "Mr. Than is seventy years old. He lives in a village in Vietnam. He worked hard all his life as a rice farmer. But now, he is retired. He spends his days enjoying his old age.", "ipa": "/ˈmɪstər θæn ɪz ˈsɛvənti jɪərz oʊld. hiː lɪvz ɪn a ˈvɪlɪdʒ ɪn viːɛtˈnɑːm. hiː wɜːrkt hɑːrd ɔːl hɪz laɪf æz a raɪs ˈfɑːrmər. bʌt naʊ, hiː ɪz rɪˈtaɪərd. hiː spɛndz hɪz deɪz ɪnˈdʒɔɪɪŋ hɪz oʊld eɪdʒ/", vi: "Cụ ông Thân năm nay đã bước sang tuổi bảy mươi, sinh sống tại một vùng quê yên bình ở Việt Nam. Cả cuộc đời cụ đã lao động vất vả cực nhọc bằng nghề làm ruộng. Giờ đây khi đã về hưu, cụ thảnh thơi tận hưởng những tháng ngày an yên tuổi xế chiều." },
      { "start": 18.0, "en": "There is one thing you should know about Mr. Than. Mr. Than never went to school. When he was a boy, he had to go to work. Now, Mr. Than has a dream. He wants to learn to read. He wants to read to his grandchildren.", "ipa": "/ðɛr ɪz wʌn θɪŋ juː ʃʊd noʊ əˈbaʊt ˈmɪstər θæn. ˈmɪstər θæn ˈnɛvər wɛnt tuː skuːl. wɛn hiː wɒz a bɔɪ, hiː hæd tuː ɡoʊ tuː wɜːrk. naʊ, ˈmɪstər θæn hæz a driːm. hiː wɒnts tuː lɜːrn tuː riːd. hiː wɒnts tuː riːd tuː hɪz ˈɡrændˌtʃɪldrən/", vi: "Có một chi tiết đặc biệt về cụ Thân mà ít ai biết: Cụ chưa từng được đặt chân đến trường học. Thời thơ ấu nghèo khó buộc cụ phải sớm bươn chải mưu sinh. Nhưng giờ đây, cụ đang ấp ủ một ước mơ lớn — đó là học đọc chữ để sau này tự tay đọc những câu chuyện thú vị cho bầy cháu nội ngoại nghe." },
      { "start": 36.0, "en": "Last year, a new teacher came to the school in his village. The teacher opened a night class to teach adults to read. Of course, Mr. Than signed up right away. Now, he goes to school two nights a week.", "ipa": "/lɑːst jɪər, a nuː ˈtiːtʃər keɪm tuː ðə skuːl ɪn hɪz ˈvɪlɪdʒ. ðə ˈtiːtʃər ˈoʊpənd a naɪt klæs tuː tiːtʃ ˈædʌlts tuː riːd. əv kɔːrs, ˈmɪstər θæn saɪnd ʌp raɪt əˈweɪ. naʊ, hiː ɡoʊz tuː skuːl tuː naɪts a wiːk/", vi: "Năm ngoái, có một giáo viên trẻ chuyển về công tác tại điểm trường trong làng và mở lớp học bổ túc ban đêm miễn phí cho người lớn. Cụ Thân liền hào hứng đăng ký tham gia ngay lập tức. Giờ đây, đều đặn mỗi tuần cụ tới lớp hai buổi vào ban đêm." },
      { "start": 53.0, "en": "It is not easy. But already, he can read more than 500 words. Mr. Than is dreaming about the day he will be able to read to his grandchildren. It makes him very happy to think about it.", "ipa": "/ɪt ɪz nɒt ˈiːzi. bʌt ɔːlˈrɛdi, hiː kæn riːd mɔːr ðæn fʌɪv ˈhʌndrəd wɜːrdz. ˈmɪstər θæn ɪz ˈdriːmɪŋ əˈbaʊt ðə deɪ hiː wɪl biː ˈeɪbl tuː riːd tuː hɪz ˈɡrændˌtʃɪldrən. ɪt meɪks hɪm ˈvɛri ˈhæpi tuː θɪŋk əv ɪt/", vi: "Việc học chữ ở tuổi này tất nhiên không hề dễ dàng gì đối với cụ. Dù vậy, đến nay cụ đã đọc thông viết thạo hơn 500 từ vựng. Hình ảnh ngày mai được ngồi đọc sách cho các cháu nghe cứ chắp cánh bay bổng trong tâm trí, mang lại cho cụ niềm hạnh phúc vô bờ bến." }
    ]
  }
];